### ISSUE TITLE
nlbwmon: Sometimes is stuck at 100% CPU

### ISSUE THREAD

**Issue by danielfdickinson** [openwrt/packages#10003]
Maintainer: @jow- 
Environment: ath79, CR3000, snapshot, packages master from a month to two months ago

Description:

This is more to be a placeholder until someone has more meaty information, as I noticed but haven't had time to dig into it.

Anyway I've observed that on some of my devices that nlbwmon gets stuck at 100% CPU, and this bogs down the network speeds on the router (but it'll stick at 100% even with minimal network activity).  Stopping and disabling nlbwmon gets the router back to normal.

The 100% CPU happens for long periods of time, not just a brief spike.

**Comment by diizzyy** [comment]
I've noticed that issue too a few months back, never had time to track it down.

**Comment by danielfdickinson** [comment]
No longer using OpenWrt; not sure if still happens or not.
