### ISSUE TITLE
lltng-tools fails to build with libkmod (buildbot)

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#1004]
```
Package lttng-tools is missing dependencies for the following libraries:
libkmod.so.2
```
reported by (examples): 
- http://buildbot.openwrt.org:8010/broken_packages/x86/lttng-tools/compile.txt
- http://buildbot.openwrt.org:8010/broken_packages/ramips/lttng-tools/compile.txt

**Comment by psycho-nico** [comment]
Fixed in 2224d60af4d6be6d0d3ab988513b8e73754e23a2, thanks!
