### ISSUE TITLE
shadowsocks-libev: How can I set the ipt_args option, thank you

### ISSUE THREAD

**Issue by vbzc** [openwrt/packages#10114]
How can I set the ipt_args option

I want to use this function to set the port of the proxy. I tried a lot of writing methods and it is not successful. Please tell me how to set it in luci, thank you.

**Comment by neheb** [comment]
This question seems to have to do with shadowsocks-libev.

**Comment by yousong** [comment]
> I want to use this function to set the port of the proxy. I tried a lot of writing methods and it is not successful. Please tell me how to set it in luci, thank you.

"port of the proxy".  Please be more specific which component's port, local port or remote servers' port?  Likely ipt_args is not the argument to achieve what you want.

**Comment by yousong** [comment]
@vbzc , any updates?

**Comment by vbzc** [comment]
@yousong I use the official original version of shadowsocks, which can be set to proxy the local port. openwrt version, I no longer use

**Comment by yousong** [comment]
> @yousong I use the official original version of shadowsocks, which can be set to proxy the local port. openwrt version, I no longer use

Sorry, with the information provided thus far, I still do not know which part went wrong and how to help you.  There is a generic [README.md](https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/README.md#recipes) 
 with a recipe that should work.  Hope it helps

**Comment by yousong** [comment]
For too long this issue receives no updates, I close it for now.  Feel free to comment here to provide further updates.
