### ISSUE TITLE
Is vlmcsd acceptable?

### ISSUE THREAD

**Issue by ysc3839** [openwrt/packages#10115]
Vlmcsd is a portable open-source KMS Emulator in C.
Released in https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/ (requires login).

But there's two issues I concern:
1. vlmcsd is a KMS emulator, which may have legal issue with Microsoft.
2. vlmcsd doesn't have an open-source license. (Which means all rights reserved?)

**Comment by ysc3839** [comment]
I found that pr #2265 is about vlmcsd. So it means vlmcsd is acceptable?

**Comment by ysc3839** [comment]
Ping @neheb

**Comment by ryzhovau** [comment]
Not sure it's a good idea. This is a risk of ban openwrt/packages project here because of one "half-legal" package.

**Comment by ysc3839** [comment]
No other reply? Well I consider it's not acceptable.
