### ISSUE TITLE
frr fails to compile with libunwind

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10110]
https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a72/packages/frr/compile.txt
Maintainer: @lucize 

frr is picking up libunwind. This is probably a mistake.

**Comment by lucize** [comment]
seems to be an option for backtrace, but it should be manually specified

**Comment by lucize** [comment]
this https://github.com/openwrt/packages/pull/10111 should fix it
