### ISSUE TITLE
L2TP reconnect problem

### ISSUE THREAD

**Issue by iDarkEmpire** [openwrt/packages#10135]
I have a problem, checked already on all openwrt that on stable that on snapshots:
I pull out a router from a network, I connect, there is no network on L2TP
I do restart through the interface in a router, a network on L2TP is
I reboot L2TP connection in the router interface, the network also is

In what there can be a problem that the router does not connect L2TP after disconnection from a network?

https://pastebin.com/N5qwkKJB

**Comment by neheb** [comment]
I think this should go in https://bugs.openwrt.org/
