### ISSUE TITLE
openconnect:  Too many arguments on command line

### ISSUE THREAD

**Issue by rufik** [openwrt/packages#10137]
**Maintainer:** @nmav
**Environment:** (x86_64, VirtualBox 6.10, OpenWrt 19.07-SNAPSHOT  r10532-cf3b50377e)

**Description:**
It looks like openconnect client is having troubles with command line arguments when Auth Group has a space inside:
```
Thu Oct  3 15:42:54 2019 user.notice openconnect: executing 'openconnect vpn.xxxxxx.com -i vpn-ocvpn --non-inter --syslog -s /lib/netifd/vpnc-script -u mylogin --passwd-on-stdin --csd-wrapper=/etc/config/csd.sh --authgroup=GROUP WITH SPACE'
Thu Oct  3 15:42:54 2019 daemon.notice netifd: ocvpn (2855): Too many arguments on command line
Thu Oct  3 15:42:54 2019 daemon.notice netifd: ocvpn (2855): Usage:  openconnect [options] <server>
[...]
```

My config of Openconnect interface is:
```
root@wrt:~# uci show network.ocvpn
network.ocvpn=interface
network.ocvpn.proto='openconnect'
network.ocvpn.interface='wan'
network.ocvpn.server='vpn.xxxxxx.com'
network.ocvpn.csd_wrapper='/etc/config/csd.sh'
network.ocvpn.username='mylogin'
network.ocvpn.password='mypassword'
network.ocvpn.authgroup='GROUP WITH SPACE'
```

I've tried to put Auth Group in quotes like that:
```
network.ocvpn.authgroup='"GROUP WITH SPACE"'
```
But still no go:
```
Thu Oct  3 15:48:12 2019 user.notice openconnect: executing 'openconnect vpn.xxxxxx.com -i vpn-ocvpn --non-inter --syslog -s /lib/netifd/vpnc-script -u mylogin --passwd-on-stdin --csd-wrapper=/etc/config/csd.sh --authgroup="GROUP WITH SPACE"'
Thu Oct  3 15:48:12 2019 daemon.notice netifd: ocvpn (2855): Too many arguments on command line
```

I've tried single quotes also `'` and no go. I've tried to run this command "by hand" and it's fine with double quotes but ends up with error message `this script must be called for an active interface`.
So, how can I define Auth Group with space that will be properly passed to openconnect command? Is there `proto_run_command` to be blamed?

**Comment by nmav** [comment]
Most likely yes. I wouldn't know how to help on that issue.

**Comment by rmarkiewicz** [comment]
Any suggestions to whom it should be reported?

**Comment by nmav** [comment]
For the main system there is https://bugs.openwrt.org/

For this particular problem are there other work-arounds we can use such as slashes?

**Comment by rufik** [comment]
I've tried with backslashes but no go. Maybe some quotes and backslashes? Any idea to try?

**Comment by jow-** [comment]
The `proto_run_command()` function is not to blame here, it is a variadic function so an invocation like `proto_run_command foo bar "baz qrx"` is properly turned into `("foo", "bar", "baz qrx")`.

The problem stems from first concatinating all arguments into a flat string, then passing this flat string unquoted to `proto_run_command` - this will cause the shell to split on `$IFS` (space, tab, newline) breaking argument values with spaces.

It is also prone to injctions, e.g. a value like `option auth_group '$(rm -rf /)'` would be happily interpolated by the shell before invoking `proto_run_command`.

**Comment by jow-** [comment]
Can you give this patch a try? https://gist.github.com/jow-/f3d6687df398b5f3f472d5630356fff4

**Comment by rufik** [comment]
Is this patch suitable to OpenWrt 19.07 revision r10532-cf3b50377e? Or could you just publish whole `openconnect.sh` file also, please?

**Comment by jow-** [comment]
See here for the whole file: https://gist.github.com/jow-/c9b6bd14cc3832c9f6fd4974b714ea18

**Comment by nmav** [comment]
@jow- would you like to send an MR? The patch doesn't have signoff-by for me to apply it.

**Comment by nmav** [comment]
@jow- I'm attaching your patch in the git form. Could you add the Signoff-by line?
[0001-openconnect-allow-spaces-on-auth-groups.txt](https://github.com/openwrt/packages/files/4145410/0001-openconnect-allow-spaces-on-auth-groups.txt)

**Comment by jow-** [comment]
@nmav - sorry I've only seen your inquiry now. I'm fine if you simply commit that change onder your name with me in `Suggested-by: ` if that's okay for you. Otherwise I'll open an MR tomorrow.
