### ISSUE TITLE
python3-pip is not working /bin/ash: pip3: not found

### ISSUE THREAD

**Issue by DrUlysses** [openwrt/packages#10130]
On Onion Omega 2 Plus python3-pip package is not working, but old python-pip runs without the problems

I have got 

`bash: /usr/bin/pip3: /codebuild/output/src727/src/github.com/OnionIoT/source/staging_dir/hostpkg/bin/python3.6: bad interpreter: No such file or directory`

in bash. Probably this is Onion problem, not yours

**Comment by BKPepe** [comment]
Would you please share OpenWrt version?

**Comment by DrUlysses** [comment]
It is Ω-ware: 0.3.2 b232 , not pure OpenWrt

**Comment by DrUlysses** [comment]
Works of stable omega2p-v0.2.2-b200.bin , this thing appears on latest 0.3.2 b232

**Comment by BKPepe** [comment]
Is python-pip working for you? I was able to find culprit in OpenWrt 18.06. Will be fixed soon.

**Comment by BKPepe** [comment]
Should be fixed by this PR https://github.com/openwrt/packages/pull/10172 if the latest version of Ω-ware: 0.3.2 b232 is based on OpenWrt 18.06.

**Comment by DrUlysses** [comment]
Ok, I'm already on stable version, can't check, but thanks
