### ISSUE TITLE
luci-app-simple-adblock: DIV error with version git-19.275.23087-48f5..-37

### ISSUE THREAD

**Issue by josephreynolds1** [openwrt/packages#10166]
Maintainer: @\Stan Grishin
Environment: (arm_cortex-a15_neon-vfpv4 , Netgear r7800, 18.06.4 r7808-ef686b7292)

Description: luci-app-simple-adblock fails to load with a DIV error since version git-19.275.23087-48f5..-37.

XML Parsing Error: mismatched tag. Expected: </div>.
Location: https://192.168.1.1:444/cgi-bin/luci/admin/services/simple-adblock
Line Number 179, Column 232:

**Comment by feckert** [comment]
This is the wrong repo please open this issue in https://github.com/openwrt/luci
