### ISSUE TITLE
cannot compile kmod

### ISSUE THREAD

**Issue by finasfinas** [openwrt/packages#1018]
make[3]: Entering directory `/home/finas/openwrt.c5/feeds/packages/utils/kmod'
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -mdspr2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -mdspr2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/usr/lib -L/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/lib " make   -C /home/finas/openwrt.c5/build_dir/target-mips_34kc_uClibc-0.9.33.2/kmod-20/. AR="mips-openwrt-linux-uclibc-gcc-ar" AS="mips-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -mdspr2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float" LD=mips-openwrt-linux-uclibc-ld NM="mips-openwrt-linux-uclibc-gcc-nm" CC="mips-openwrt-linux-uclibc-gcc" GCC="mips-openwrt-linux-uclibc-gcc" CXX="mips-openwrt-linux-uclibc-g++" RANLIB="mips-openwrt-linux-uclibc-gcc-ranlib" STRIP=mips-openwrt-linux-uclibc-strip OBJCOPY=mips-openwrt-linux-uclibc-objcopy OBJDUMP=mips-openwrt-linux-uclibc-objdump SIZE=mips-openwrt-linux-uclibc-size CROSS="mips-openwrt-linux-uclibc-" ARCH="mips" ;
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
make[4]: Entering directory `/home/finas/openwrt.c5/build_dir/target-mips_34kc_uClibc-0.9.33.2/kmod-20'
make --no-print-directory all-recursive
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Making all in .
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
depbase=`echo libkmod/libkmod.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CC   --mode=compile mips-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -I.  -include ./config.h -I. -DSYSCONFDIR=\""/etc"\" -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include  -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/usr/include -I/home/finas/openwrt.c5/staging_dir/toolchain-mips_34kc_gcc-4.9-linaro_uClibc-0.9.33.2/include  -pipe -DANOTHER_BRICK_IN_THE -Wall -W -Wextra -Wno-inline -Wvla -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=3 -Wwrite-strings -Wno-long-long -Wno-overlength-strings -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wnested-externs -Wchar-subscripts -Wtype-limits -Wuninitialized -fno-common -fdiagnostics-show-option -fvisibility=hidden -ffunction-sections -fdata-sections  -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -mdspr2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -MT libkmod/libkmod.lo -MD -MP -MF $depbase.Tpo -c -o libkmod/libkmod.lo libkmod/libkmod.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: Version mismatch error.  This is libtool 2.4.5, but the
libtool: definition of this LT_INIT comes from libtool 2.4.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.5
libtool: and run autoconf again.
make[6]: *** [libkmod/libkmod.lo] Error 63
make[5]: *** [all-recursive] Error 1
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/finas/openwrt.c5/build_dir/target-mips_34kc_uClibc-0.9.33.2/kmod-20'
make[3]: *** [/home/finas/openwrt.c5/build_dir/target-mips_34kc_uClibc-0.9.33.2/kmod-20/.built] Error 2
make[3]: Leaving directory `/home/finas/openwrt.c5/feeds/packages/utils/kmod'
make[2]: *** [package/feeds/packages/kmod/compile] Error 2
make[2]: Leaving directory `/home/finas/openwrt.c5'
make[1]: *** [/home/finas/openwrt.c5/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/finas/openwrt.c5'
make: *** [world] Error 2

**Comment by sbyx** [comment]
solved
