### ISSUE TITLE
why package `psmsic` was missing after 14.07

### ISSUE THREAD

**Issue by yurenchen000** [openwrt/packages#10213]
and can we add them back  to packages ?

https://git.openwrt.org/?p=openwrt/svn-archive/archive.git;f=utils/psmisc;hb=refs/heads/packages

try to search in `packages-abandoned ` and openwrt forum, didn't found.

**Comment by diizzyy** [comment]
No maintainer and all of these are more or less replaced by utilities provided by busybox

**Comment by neheb** [comment]
@diizzyy provided the answer. If you want this in here, open a PR. Closing.
