### ISSUE TITLE
Glibc tcpdump compile failed

### ISSUE THREAD

**Issue by panda-mute** [openwrt/packages#10214]
Maintainer: @DENG Qingfang <dengqf6@mail2.sysu.edu.cn>
Environment: (host: ubuntu16.04 x86_64, mvebu, OpenWrt master)

Description:

tcpdump configure report failed

[libpcap config.log](https://github.com/openwrt/packages/files/3721584/config.log)
[tcpdump config.log](https://github.com/openwrt/packages/files/3721585/config.log)

**Comment by dengqf6** [comment]
Thanks for the report, I will look into it

**Comment by diizzyy** [comment]
Wrong repo, tcpdump is in openwrt not packages.

**Comment by yousong** [comment]
For the record, the issue should be fixed now that we build libpcap using cmake
