### ISSUE TITLE
502 Bad Gateway of nginx

### ISSUE THREAD

**Issue by panda-mute** [openwrt/packages#10235]
Maintainer: @Ansuel 
Environment: (mvebu, OpenWrt latest master version with nginx/uwsgi/cgi-io fix)

Description:

```
Mon Oct 14 15:06:38 2019 daemon.info uwsgi-emperor: workers have been inactive for more than 360 seconds (1571036798-1571036437)
Mon Oct 14 15:06:38 2019 daemon.info uwsgi-emperor: Mon Oct 14 15:06:38 2019 - [emperor] bringing back instance /etc/uwsgi/vassals/luci-webui.ini to on-demand mode
Mon Oct 14 15:06:38 2019 daemon.info uwsgi-emperor: Mon Oct 14 15:06:38 2019 - received message 0 from emperor
Mon Oct 14 15:06:38 2019 daemon.info uwsgi-emperor: SIGINT/SIGQUIT received...killing workers...
Mon Oct 14 15:06:38 2019 daemon.info uwsgi-emperor: Mon Oct 14 15:06:38 2019 - [emperor] curse the uwsgi instance /etc/uwsgi/vassals/luci-webui.ini (pid: 19560)
Mon Oct 14 15:06:39 2019 daemon.info uwsgi-emperor: worker 1 buried after 1 seconds
Mon Oct 14 15:06:39 2019 daemon.info uwsgi-emperor: goodbye to uWSGI.
Mon Oct 14 15:06:39 2019 daemon.info uwsgi-emperor: VACUUM: unix socket /var/run/luci-webui.socket removed.
Mon Oct 14 15:06:39 2019 daemon.info uwsgi-emperor: unlink(): No such file or directory [core/uwsgi.c line 1660]
Mon Oct 14 15:06:40 2019 daemon.info uwsgi-emperor: [uwsgi-emperor] /etc/uwsgi/vassals/luci-webui.ini -> back to "on demand" mode, waiting for connections on socket "/var/run//luci-webui.socket" ...

```

Then surf the router web page, report 502 Bad Gateway

root@OpenWrt:~# ls /var/run/*socket
/var/run/luci-cgi_io.socket

**Comment by Ansuel** [comment]
Post your nginx.conf

Is the firmware from latest commit?

Il Lun 14 Ott 2019, 09:25 panda-mute <notifications@github.com> ha scritto:

**Comment by panda-mute** [comment]
'''
root@OpenWrt:~# cat /etc/nginx/nginx.conf

user nobody nogroup;
worker_processes  2;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 0;

    client_body_buffer_size 10K;
    client_header_buffer_size 1k;
    client_max_body_size 1G;
    large_client_header_buffers 2 1k;

    gzip on;
    gzip_http_version 1.1;
    gzip_vary on;
    gzip_comp_level 1;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;

    root /www;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name  localhost;
		include ariang.conf;

        location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 365d;
        }

        include luci_uwsgi.conf;

    }

    include /etc/nginx/conf.d/*.conf;
}

'''

**Comment by Ansuel** [comment]
What about the other questions?

Il Lun 14 Ott 2019, 14:57 panda-mute <notifications@github.com> ha scritto:

**Comment by panda-mute** [comment]
It is the  commit.

commit aeb198bb82252e937a122edb2ce47b56a28be7e2
Author: Nikos Mavrogiannopoulos <n.mavrogiannopoulos@gmail.com>
Date:   Sun Oct 13 08:06:10 2019 +0200

    Merge pull request #10208 from dengqf6/oc
    
    openconnect: update to 8.05

**Comment by Ansuel** [comment]
As I thought your latest is not latest ahahah
Just update the firmware / package
Master to that commit lack of a crucial change to nginx (included in later
commit)

Il Lun 14 Ott 2019, 15:14 panda-mute <notifications@github.com> ha scritto:

**Comment by panda-mute** [comment]
I think it include all your fix about nginx/uwsgi/cgi-io, please help to check

**Comment by Ansuel** [comment]
Again if you build your firmware just update your repo...

Anyway this is missing

https://git.openwrt.org/?p=feed/packages.git;a=commit;h=b9c7a570a2342c65ad049e4e77e038b3f8f3b90a

that got merged AFTER commit that updates openconnect

Il Lun 14 Ott 2019, 15:18 panda-mute <notifications@github.com> ha scritto:

**Comment by panda-mute** [comment]
@Ansuel 

xw@xw-ubuntu:~/workspace/github/openwrt-master/package$ cat feeds/packages/nginx/files-luci-support/luci_uwsgi.conf
location /cgi-bin/luci {
                index  index.html;
                include uwsgi_params;
                uwsgi_param SERVER_ADDR $server_addr;
                uwsgi_modifier1 9;
                uwsgi_pass unix:////var/run/luci-webui.socket;
}
location ~ /cgi-bin/cgi-(backup|download|upload) {
                include uwsgi_params;
                uwsgi_param SERVER_ADDR $server_addr;
                uwsgi_modifier1 9;
                uwsgi_pass unix:////var/run/luci-cgi_io.socket;
}

location /luci-static {
}

**Comment by panda-mute** [comment]
This bug is when idle timeout, the /var/run/luci-webui.socket been removed

**Comment by Ansuel** [comment]
So a uwsgi restart fix it?
I'm using it from 2 days and never experienced this problem

Il Lun 14 Ott 2019, 15:50 panda-mute <notifications@github.com> ha scritto:

**Comment by panda-mute** [comment]
yes, you are right, restart uwsgi  
make it work  again.

**Comment by panda-mute** [comment]
Can you check the log I pasted, do you have same log of socket remove releated?

**Comment by leonardpitzu** [comment]
Sort of the same happens to me but I do not see the socket removed in the log. Restarting uwsgi brings everything back online for a while. I am on openwrt master running on mvebu

**Comment by Ansuel** [comment]
@peter-stadler any hint on this?

**Comment by peter-stadler** [comment]
I cannot test it right now, try removing the `vacuum` line in the uwsgi configurations /etc/uwsgi/vassals/* (For testing it, a smaller timeout could be useful, too. Reset it to a higher value after debugging)

**Comment by leonardpitzu** [comment]
@peter-stadler same thing, it does not fix it

**Comment by peter-stadler** [comment]
Reading https://uwsgi-docs.readthedocs.io/en/latest/OnDemandVassals.html I saw that the vassals config should not set the socket. Try to remove that ...
@Ansuel: If that works, a cleaner solution would be if the emperor removes the socket option of the vassals that are activated by socket. I don't know if this is possible.

**Comment by peter-stadler** [comment]
A possible problem could be that the socket is not chmod (see `ls -al /var/run/*.socket`). And we cannot use the vacuum, can we?

**Comment by peter-stadler** [comment]
If it is not working, is the uwsgi log changing? You could enable more verbose logging by uncommenting the `logger = syslog:uwsgi-luci` line in /etc/uwsgi/vassals/luci-webui.ini, too ...

**Comment by Ansuel** [comment]
Consider that we must keep the socket or we can't call the app to be
started...



Il Mar 15 Ott 2019, 17:01 peter-stadler <notifications@github.com> ha
scritto:

**Comment by peter-stadler** [comment]
Yes we have to keep the socket, but it must not be created by the vassals (that is how I understand the OnDemandVassals docs). To make the ini files useable with and without emperor some [if statement]( https://uwsgi-docs.readthedocs.io/en/latest/ConfigLogic.html) could be useful ...

**Comment by Ansuel** [comment]
Think the problem here is vassal socket and vacuum

Il Mar 15 Ott 2019, 17:17 peter-stadler <notifications@github.com> ha
scritto:

**Comment by panda-mute** [comment]
@Ansuel @peter-stadler 

Refer to https://stackoverflow.com/questions/45437713/uwsgi-not-restarting-after-being-idle

I try to remove the socket option in /etc/uwsgi/vassals/luci-webui.ini
`root@OpenWrt:~# cat /etc/uwsgi/vassals/luci-webui.ini 
[uwsgi]
strict = true
#socket = /var/run/luci-webui.socket
cgi-mode = true
cgi = /www/
chdir = /usr/lib/lua/luci/
buffer-size = 10000
reload-mercy = 8
max-requests = 2000
limit-as = 200
reload-on-as = 256
reload-on-rss = 192
no-orphans = true
vacuum = true
enable-threads = true
post-buffering = 8192
socket-timeout = 120
thunder-lock = true
logger = syslog:uwsgi-luci
disable-logging = true
log-format = %(addr) %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs
threads = 3
processes = 3
chmod-socket = 666
cheap = true
cheaper-algo = spare
cheaper = 1
cheaper-initial = 2
cheaper-step = 1
master = true
`

**Comment by leonardpitzu** [comment]
i managed only now to get my hand on a computer
removing the socket from the vassals solves the issue
