### ISSUE TITLE
domoticz: Missing dependency

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10246]
https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/domoticz/compile.txt

ping @stintel

**Comment by stintel** [comment]
Unfortunately telldus-core does not build on x86/64. This explains why domoticz packages are still being built for x86/64. As long as telldus-core doesn't build I will not add the dependency to domoticz as x86/64 is the only platform I'm using domoticz on.

**Comment by neheb** [comment]
I believe @PeterFromSweden fixed telldus-core for x86. Can you check?
