### ISSUE TITLE
<adblock>: documentation unclear about blocklist update

### ISSUE THREAD

**Issue by novoid** [openwrt/packages#10251]
Maintainer: @dibdot  
Environment: mips_24kc; ar71xx/generic; OpenWrt SNAPSHOT r6738-a4322eb

Description:

https://github.com/openwrt/packages/blob/master/net/adblock/files/README.md contains:

```
Cronjob for a regular block list update (/etc/crontabs/root):
0 06 * * *    /etc/init.d/adblock reload
```

I would like to have it rephrased so that somebody clearly knows whether or not (1) the list of possible blacklist sources is updated or (2) each(?) individual blacklist gets updated from their source so that they hold the most current IPs/domains to block.

The latter one is my current interpretation of the documentation.

**Comment by dibdot** [comment]
fixed with #10278
