### ISSUE TITLE
utils: tmux satisfy_dependencies_for: Cannot satisfy the following dependencies for tmux: libevent2-6

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/packages#10262]
openwrt master r11237-d107209

https://github.com/openwrt/openwrt/commit/f351beedfd47766e5e44a04af50e3724bec54dbc
has been upgrade libevent2-7

tmux maybe upgrade 
```
satisfy_dependencies_for: Cannot satisfy the following dependencies for tmux:
 * 	libevent2-6
```

**Comment by neheb** [comment]
I assume recompiling will fix this.
