### ISSUE TITLE
python3-pip

### ISSUE THREAD

**Issue by ubiquitousthey** [openwrt/packages#10266]
Maintainer: @commodo (find it by checking history of the package Makefile)
Environment: Onion.io Omega2S

Description:
The reference to python is wrong in the /usr/bin/pip3.  It is currently `#!/codebuild/output/src727/src/github.com/OnionIoT/source/staging_dir/hostpkg/bin/python3.6` instead of `#!/usr/bin/python3`

**Comment by jefferyto** [comment]
From the shebang line it looks like you are using Onion's fork, not "vanilla" OpenWrt?

**Comment by ubiquitousthey** [comment]
I should have noticed that.  Thanks.
