### ISSUE TITLE
pdns-recursor missing dependency

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10273]
https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc_24kf/packages/pdns-recursor/compile.txt

ping @James-TR 

I'm curious about this dependency. I downloaded the source code and saw that it is not being used at all. It's only used in the configure script.

The failure is due to https://github.com/openwrt/packages/commit/260d4a346afeffec5f7e4818d1179ea8db70420e#diff-eda03f2256b0bcbeec4978a233231a89

And similarly, it's not used here either.

**Comment by James-TR** [comment]
That's a good point. I'll open an issue in the upstream project to see what their thoughts are.

**Comment by James-TR** [comment]
But if you look in the actual library code you'll see there has been a check for `<mutex>` since 1.61.0 to use that instead of Boost::Thread where it is available.

https://github.com/boostorg/context/blob/boost-1.71.0/build/Jamfile.v2#L783-L789

**Comment by hnyman** [comment]
Any forthcoming fix for this error?  (as right now the package does not compile at all)

Even a temporary fix?
Add the (actually unnecessary?) dependency to the package?

**Comment by James-TR** [comment]
I don't know why I didn't think of that as a stop gap. I'll whip up a PR tonight.
