### ISSUE TITLE
[OpenWrt-1907] cherry-pick "add librouteros"

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/packages#10295]
Please cherry-pick abaca50b5775bfe18104580598877312ee8876d3 into the openwrt-19.07 branch. 
This will add the package "librouteros" - an abstraction library to Mikrotik RouterOS

**Comment by SvenRoederer** [comment]
also see https://github.com/openwrt/packages/pull/9471

**Comment by BKPepe** [comment]
librouteros was cherry-picked as requested. https://github.com/openwrt/packages/commit/137069f90e20230eada923c1d1e7366a9a22168a

**Comment by SvenRoederer** [comment]
Thanks for cherry-picking. Just created PR https://github.com/openwrt/packages/pull/10327 for collectd-plugin.
