### ISSUE TITLE
CI: use cdn.openwrt.org instead of downloads.openwrt.org

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#10358]
There is now cdn.openwrt.org to lower our own server usage, please rewrite the CircleCI `config.yml` to reflect that.

Tricky part is to replace `rsync` with `wget` which doesn't support globs, therefore the real filename has to be grepped out of the checksum file before.

@champtar @jefferyto @thess

**Comment by diizzyy** [comment]
If that's an issue why not use one of the mirrors instead of some third party cdn?

**Comment by aparcar** [comment]
I'd be fine with this too however if there are stable and ast OpenWrt mirrors. It introduces the same `rsync` code change, so changing this would make it flexible to use whatever.
