### ISSUE TITLE
100-add-rtsp-conntrack.patch NO TIMESHIFT with IPTV

### ISSUE THREAD

**Issue by Yonoesio** [openwrt/packages#10373]
Hi all,

I only get the timeshift  to work with my IPTV ISP, if I change:

`
+- nf_ct_l3num(ct), &srvaddr,
++ nf_ct_l3num(ct), NULL, //&srvaddr
`

otherwise I don't get the live playback control to work

**Comment by dengqf6** [comment]
Please report the issue upstream
https://github.com/maru-sama/rtsp-linux

**Comment by Yonoesio** [comment]
Mike's answer:

 no longer have the hardware available to test it, I cannot even do a

compile time check right now. Feel free to fork the source on github

and issue a pull request with this change.

**Comment by dengqf6** [comment]
Just open a PR then

**Comment by neheb** [comment]
Fixed.
