### ISSUE TITLE
Use nginx upstream version 

### ISSUE THREAD

**Issue by Ansuel** [openwrt/packages#10371]
As we have 19.01 branch... why not switch to nginx upstream version instead of keep stay with stable version ? 

Also from nginx site stable version and upstream versione are equally stable... The only difference is that stable doesn't receive new feature so... I really think that keep stable nginx version is plain wrong.

**Comment by diizzyy** [comment]
By upstream you mean mainline, by all means do so if you want.

**Comment by Ansuel** [comment]
yes.. i mean mainline
