### ISSUE TITLE
tinc not compiling 

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10382]
Maintainer: @zioproto

You needed to remove the patch, which was upstreamed.

**Comment by zioproto** [comment]
What is the target architecture not compiling ?
Could you paste here the build error ?
thank you

**Comment by neheb** [comment]
http://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/tinc/compile.txt

**Comment by zioproto** [comment]
I understand now. My mistake. Those two patches had to be dropped because are now included in the upstream version. My git commit updated only the Makefile.
I can push the fix in 2 hours. Sorry for the regression.

**Comment by zioproto** [comment]
Fixed in 251d4043dfc47d1385253ca8c107ffe522e06c8e
thank you for reporting and sorry for the regression.
