### ISSUE TITLE
coova-chilli: not working

### ISSUE THREAD

**Issue by juampi092** [openwrt/packages#10392]
Maintainer: @ynezz 
Environment: Ubiquiti AirCube

Description:
Coova-Chilli not working.
This section in Chilli.init
config_get_bool disabled "$1" 'disabled' 1

must be

config_get_bool disabled "$1" 'disabled' 0

**Comment by ynezz** [comment]
@juampi092 can you share your config file and add information about what is expected to be working and what doesn't?
