### ISSUE TITLE
<lighttpd-mod-webdav> seg faults

### ISSUE THREAD

**Issue by nerdhardest** [openwrt/packages#10447]
Please make sure that the issue subject starts with `<package-name>: `

Also make sure that the package is maintained in this repository and not in base which should be submitted at https://bugs.openwrt.org or in the LuCI repository which should be submitted at https://github.com/openwrt/luci/issues.

Issues related to releases below 18.06 and forks are not supported or maintained and will be closed.

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version) 

GL-MT300A
MediaTek MT7620A ver:2 eco:6
OpenWrt SNAPSHOT r11254-54d9ac8ba8 / LuCI Master (git-19.304.35036-4798b3f)
Kernel Version
4.14.149

(But I don't think the architecture matters, since this bug has been reported & acknowledged as generic bug #2958 in all versions of mod_webdav (see below).)

Description:
https://redmine.lighttpd.net/issues/2958
lighttpd 1.4.54 segfaults on start in mod_webdav
2019-06-05

This bug has already been fixed; the fix just needs to migrate into OpenWrt.
```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by neheb** [comment]
ping @BKPepe your guys use this.

**Comment by BKPepe** [comment]
Should be fixed in lighttpd 1.4.55, which was released 10 days ago. I will try to update it and if everything goes well, I will send pull request today or tomorrow.
