### ISSUE TITLE
PF-RING not compiling with kernel >= 4.16

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10450]
Maintainer: @hbl0307106015
Environment: master

See: https://github.com/ntop/PF_RING/issues/454

**Comment by hbl0307106015** [comment]
The pfring package of openwrt/packages uses the released package from codeload, how about using the 7.4.0 branch ?
Did you test the latest 7.4.0 branch ?

**Comment by neheb** [comment]
Tested latest 7.4.0 branch. Still fails.

That (or those) patches need backporting.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/10513

**Comment by hbl0307106015** [comment]
ACK

**Comment by neheb** [comment]
This is fixed.
