### ISSUE TITLE
spice not compiling without deprecated OpenSSL APIs

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10451]
Maintainer: @yousong 
Environment:  master

Patch here: https://gitlab.freedesktop.org/spice/spice/merge_requests/8/commits

The first one is enough.

**Comment by yousong** [comment]
Apart from the gitlab site frequently refuses connection ;) I'd like to hold the change for a while until the upstream project accepts it.  Thanks for the time and efforts.

**Comment by neheb** [comment]
And I just realized the upstream commit is not quite the same as what is needed here. Patch incoming.
