### ISSUE TITLE
Python 3.8 not compiling on the buildbots (x86)

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10452]
Maintainer: @commodo @jefferyto 
Environment: master

https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/python3/compile.txt

**Comment by commodo** [comment]
will take a look

**Comment by commodo** [comment]
urgs... 
blast from the past
Ubuntu's multi-arch stuff that is still crap in Python 3.8;

PR on the way
