### ISSUE TITLE
mariadb not compiling with uClibc++

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10462]
Maintainer: @micmac1 
Environment: master

Can you look into this? uClibc++ seems to be a good idea as libstdcpp sizes have gone crazy with recent GCC versions.

**Comment by micmac1** [comment]
Nope. Not interested at all personally. mariadb-server is so big it doesn't matter one bit whether you can save a few bytes with uclibc++. If somebody else wants to assign this issue and gets a patch upstream go for it. Ping me to get the depends sorted for the package Makefile.

**Comment by micmac1** [comment]
lol, crazy package size of libstdcpp?

libstdcpp6_8.3.0-2_mips_24kc.ipk | 375.4 KB

That's nothing at all compared to mariadb-server. I think you won't find anybody who'll self-assign this issue, seriously. It'll just stay here forever. ;-)

Regards,
Seb

**Comment by neheb** [comment]
Point taken.

It seems uClibc++ first needs C++11 math to compile mariadb.
