### ISSUE TITLE
[1907]nfs-kernel-server: recursive dependency detected!

### ISSUE THREAD

**Issue by manjuprajna** [openwrt/packages#10490]
Maintainer: @tripolar 
Environment: OpenWrt 1907 rc1, build on ubuntu 1804

Description:
tmp/.config-package.in:104620:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:104620:  symbol PACKAGE_nfs-kernel-server depends on NFS_KERNEL_SERVER_V4
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
feeds/packages/net/nfs-kernel-server/Config.in:4:       symbol NFS_KERNEL_SERVER_V4 depends on PACKAGE_nfs-kernel-server

I already posted this issue on July when 1907 came out, but several monthes past, still same issue, seems no one care about it. now 1907 already in release candidate, still no fix for it?

**Comment by mans0n** [comment]
The dependency graph is `nfs-kernel-server -> libdevmapper -> kmod-dm -> kmod-dax -> LINUX_4_9`
The error message was first introduced by openwrt/openwrt@000d400baa. It seems removing all 4.9 targets causes this, but I don't know why.
Removing `!LINUX_4_9` dependencies on kmod-dm and kmod-dax will also fix it, but I'm not sure this is a fundamental solution.

**Comment by mans0n** [comment]
The fix patch is merged so this can be closed now.
