### ISSUE TITLE
pcre: remove unnecessary dependency on C++ lib [19.07]

### ISSUE THREAD

**Issue by Borromini** [openwrt/packages#10514]
This is a backport request for https://github.com/openwrt/packages/pull/9535/. Compilation of 19.07 HEAD breaks (tested 2019-11-09 on x86/64, which relies on libpcre as a dependency for the architecture). This patch fixes it.

Maintainer: @thess
Compile tested: x86/64

Description:
Add libpcrecpp to PKG_CONFIG_DEPENDS to properly trigger reconfiguration, avoiding a needless dependency.

This reverts commit 17090fe.
This reverts commit ec138f5.

**Comment by neheb** [comment]
Done

**Comment by BKPepe** [comment]
For completeness:
Commit: https://github.com/openwrt/packages/commit/39001de7b042cb4555e23abb8456c6fe5d060db7
