### ISSUE TITLE
jool: Remove ethtool dependency

### ISSUE THREAD

**Issue by ydahhrk** [openwrt/packages#10534]
Maintainer: @tiagogaspar8
Environment: Don't know

Description:

This is not really a bug; it's more of a quirk.

@jirutka noticed that ethtool is listed as a [dependency of Jool](https://github.com/openwrt/packages/blob/master/net/jool/Makefile#L91). I don't think this conflicts with anything, but is it really necessary?

To the best of my knowledge, Jool does not depend on ethtool in any way. Back in Jool 3, ethtool served as a GRO disabling tool, but even then it was considered accompanying software, not a dependency. GRO disabling has been rendered theoretically unnecessary as of Jool 4, and I haven't seen anyone doing it as of late. (I'm the upstream developer.)

**Comment by BKPepe** [comment]
Fixed by this commit https://github.com/openwrt/packages/commit/526b384503e217d428ca4bbe9b546e1653b7b117
