### ISSUE TITLE
Haproxy: Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/packages#10558]
gcc-9.2.0 and cmake-1.15.5
Haproxy Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by neheb** [comment]
ping @chris5560

**Comment by peterwillcn** [comment]
@neheb @chris5560 Sorry for that, It's my fault, haproxy crash was caused by my misconfiguration, now works fine.
