### ISSUE TITLE
acme: Fails with “Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555.”

### ISSUE THREAD

**Issue by andersk** [openwrt/packages#10563]
Maintainer: @tohojo
Environment: OpenWrt 19.07.0-rc1 on ath79 tl-wdr3600-v1

Description:

acme.sh 2.7.9, as shipped in OpenWrt 19.07.0-rc1, can no longer register new accounts with Let’s Encrypt due to the [ACMEv1 end-of-life plan](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1). I see that acme.sh was already upgraded in `master` (a1cd83307dad8bda158969c93e24557e90c6d2fb, 1653894091833a40125999025e4dbf60ed9bcb2f) and `openwrt-18.06` (9f4f78da15225a36e936d16af8ce2f7e6115a011) but not `openwrt-19.07` yet.

```
Sat Nov 16 18:27:44 2019 daemon.info run-acme[2338]: Registering account
Sat Nov 16 18:27:46 2019 daemon.err run-acme[2338]: Register account Error: {"type":"urn:acme:error:unauthorized","detail":"Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.","status": 403}
Sat Nov 16 18:27:46 2019 daemon.err run-acme[2338]: Please add '--debug' or '--log' to check more details.
Sat Nov 16 18:27:46 2019 daemon.err run-acme[2338]: See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by tohojo** [comment]
Cherry-picked the required commits, so ACME in the 19.07 branch is now up to date with master...
