### ISSUE TITLE
libperl.so: undefined reference to `__stack_chk_guard'

### ISSUE THREAD

**Issue by fuqiang03** [openwrt/packages#10569]
ubuntu 19.10
x68_x64 
OpenWrt master version
gcc 9.2
glibc 2.27
![QQ截图20191117213842](https://user-images.githubusercontent.com/26851715/69008193-baa51180-0982-11ea-8d88-13b63d793bf8.png)

**Comment by neheb** [comment]
Is this still an issue?

**Comment by fuqiang03** [comment]
@neheb 
Excuse me, do you have any idea

**Comment by neheb** [comment]
That issue is caused by using LD instead of CC for linking. Maybe the issue is specific to glibc.

**Comment by fuqiang03** [comment]
Other programs have made the same mistake, not just glibc

**Comment by fuqiang03** [comment]
I guess it's the tool chain

**Comment by mewsf** [comment]
I have the same issue when compiling openwrt x86 target with glibc. I edited compiler and linker flags to force perl not to compile with stack guard. There's also similar issue that says undefined xxx when compiling other packages, I don't remember the details because it was a few days ago. Using musl is ok so it has to be glibc which caused the problem.

**Comment by fuqiang03** [comment]
@mewsf 
Can you share specific changes
I changed the glibc version. The problem is still the same
Question the tool chain

**Comment by mewsf** [comment]
I edited `openwrt/feeds/packages/lang/perl/Makefile` and in the `define Build/Configure` section, I changed a line from

`	(cd $(PKG_BUILD_DIR) && ./Configure -S)`
to make it like this
`	(cd $(PKG_BUILD_DIR) && sed -i "s/-fstack-protector-strong/-fno-stack-protector/g" $(PKG_BUILD_DIR)/config.sh && sed -i "s/-fstack-protector/-fno-stack-protector/g" $(PKG_BUILD_DIR)/config.sh && ./Configure -S)`

It's a dirty way to change compiler flags. But I still hope if someone can really fix the problem with glibc. I'm not good at this.

**Comment by neheb** [comment]
proper solution is to change the linker from ld to gcc.

**Comment by fuqiang03** [comment]
thank you

**Comment by mewsf** [comment]
> 
> 
> proper solution is to change the linker from ld to gcc.

That's much beyond my ability, I can only wait for someone who can submit relevant code for that.

**Comment by mewsf** [comment]
> 
> 
> proper solution is to change the linker from ld to gcc.

I'm rebuilding openwrt now, and I checked config.sh of perl, there's a line says `ld='x86_64-openwrt-linux-gnu-gcc'`, I think it means that it has already used gcc as linker?

I added '-lssp' to LDFLAGS and it compiled successfully. It turns out that when using glibc to compile, some packages needs special linker flags like '-ldl' or '-lssp' to solve the library problem.

**Comment by fuqiang03** [comment]
@mewsf 
Thanks for your help

**Comment by fuqiang03** [comment]
@mewsf 
My build passes,They don't seem interested in glibc,
Because some programs cannot be built in glibc
For example, ksmbd tools

**Comment by mewsf** [comment]
> 
> 
> @mewsf
> My build passes,They don't seem interested in glibc,
> Because some programs cannot be built in glibc
> For example, ksmbd tools

I have never built that package. but maybe I can help with that if you paste build log here.

**Comment by fuqiang03** [comment]
It has been modified and passed
You can verify it for me
![20200223222105](https://user-images.githubusercontent.com/26851715/75113697-f3900900-568a-11ea-8283-87191d2c0218.png)

**Comment by mewsf** [comment]
> 
> 
> It has been modified and passed
> You can verify it for me
> ![20200223222105](https://user-images.githubusercontent.com/26851715/75113697-f3900900-568a-11ea-8283-87191d2c0218.png)

...原来是国人 你这是说编译通过了吗还是没有

**Comment by fuqiang03** [comment]
编译通过了
这沟通省事多了

**Comment by mewsf** [comment]
那我觉得可以关了这个issue了  openwrt本身主要还是侧重于嵌入式设备 所以官方也不太会有太多精力关注glibc的问题

**Comment by fuqiang03** [comment]
哎 只不过glibc用习惯了.官方不关注自己修改很麻烦只能有时间自己改改.
这个issue暂时留着,做个记录,问题都解决了,我自然就关闭了.
![QQ截图20200223224232](https://user-images.githubusercontent.com/26851715/75114123-62229600-568e-11ea-85a4-3fb98f339fb9.png)

**Comment by mewsf** [comment]
搜了一下 这个估计是Makefile本身加了类似`-Werror`的编译flag导致的

**Comment by fuqiang03** [comment]
看错误提示是这样的
makefile文件在编译的时候是生成的 源码里面没有这个文件
得要仔细的找找了
先一步一步的试试了

**Comment by fuqiang03** [comment]
实在受不了,需要改动的程序太多了.

**Comment by LitingLin** [comment]
in 'feeds/packages/lang/perl/files/libc.config' add ldflags variable in line 3 with '-lssp'
