### ISSUE TITLE
Support for https in packages/net/ddns-scripts/files/update_No-IP.com.sh 

### ISSUE THREAD

**Issue by Panderine** [openwrt/packages#1057]
Would It be possible to support secure IP updating?. Right now it's using plain text.

More info on how it is implemented server-side: http://www.noip.com/integrate/request

https://dynupdate.no-ip.com/nic/update

base64-encoded-auth-string should be the base64 encoding of username:password. Un-encoded strings are accepted as well.

GET /nic/update?hostname=mytest.testdomain.com&myip=1.2.3.4 HTTP/1.0
Host: dynupdate.no-ip.com
Authorization: Basic base64-encoded-auth-string
User-Agent: Bobs Update Client WindowsXP/1.2 bob@somedomain.com

**Comment by chris5560** [comment]
@Freemagenta
Secure HTTP is implemented inside ddns-scripts.
Have a look at http://wiki.openwrt.org/doc/howto/ddns.client 
and http://wiki.openwrt.org/doc/uci/ddns how to configure.
You need to install "wget" or "curl" packages and in addition "ca-certificates".
If using secure http there is no need to encode the authorization.
Base64 is no real security. You can encode and decode online i.e. at https://www.base64encode.org/
