### ISSUE TITLE
Closing openconnect VPN leaves openwrt with no default route

### ISSUE THREAD

**Issue by hansbogert** [openwrt/packages#1058]
I finally got my openconnect to work, however when the VPN is closed I have no working route table anymore when I want my traffic to go over my 'normal' WAN interface again.

Actually, in the first place, I don't want my VPN to be the default route, is this also possible?

**Comment by jow-** [comment]
Try the standard option `option defaultroute 0` in the openconnect interface section.

**Comment by nmav** [comment]
@hansbogert does theoption jow sugest works for you?

**Comment by hansbogert** [comment]
Sorry, for not replying earlier, the suggested above indeed does solve it for me.

Thanks.
