### ISSUE TITLE
Add 2 new packages

### ISSUE THREAD

**Issue by bogdik** [openwrt/packages#10618]
Please add https://github.com/bogdik/openwrt-linux-eoip
And https://github.com/bogdik/luci-app-eoip
I think many may need EoIP mikrotik compartable tunneling

**Comment by neheb** [comment]
Why not open pull requests for this?

**Comment by BKPepe** [comment]
As @neheb suggested, you can send us a pull request or you might want to ask on [OpenWrt forum](https://forum.openwrt.org/) to add these packages to this repository.
