### ISSUE TITLE
procps-ng-vmstat: Cannot install package 

### ISSUE THREAD

**Issue by fantom-x** [openwrt/packages#10649]
SNAPSHOT
Image Builder
Router: GL-B1300 (ipq40xx)

Getting this error when using the image builder.The package is probably not being built...

```
 * opkg_install_cmd: Cannot install package procps-ng-vmstat.
Makefile:153: recipe for target 'package_install' failed
make[2]: *** [package_install] Error 255
Makefile:112: recipe for target '_call_image' failed
make[1]: *** [_call_image] Error 2
Makefile:196: recipe for target 'image' failed
make: *** [image] Error 2

```

**Comment by micmac1** [comment]
Hello @fantom-x 

Please check now, vmstat should be available. I see the package in the [snapshot package directory for arm_cortex-a7_neon-vfpv4](https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/).

I never used the image builder myself, so I don't know if you need to refresh anything for the imagebuild to see the package.

Please give it a try and close this issue if it's OK now.

Thanks!
Seb
