### ISSUE TITLE
samba4: overwrites base package executable

### ISSUE THREAD

**Issue by micmac1** [openwrt/packages#10700]
Hello @neheb @Andy2244,

Please revert commit 226e0c6. It overwrites compile_et from e2fsprogs/host, which causes build failures for krb5, which in turn leads to failures for libmariadb, lighttpd, mariadb, pdns and php7-pecl-krb5.

Thanks!
Seb

**Comment by Andy2244** [comment]
ah damn, totally forgot about this interaction.

Will come up with a fix or revert asap!

**Comment by micmac1** [comment]
Thanks Andy, no rush.
