### ISSUE TITLE
ddns-scripts: old link to wiki.openwrt.org

### ISSUE THREAD

**Issue by tmo26** [openwrt/packages#10740]
The ddns-scripts still contain a link to the old wiki:
https://github.com/openwrt/packages/blob/cce63a697bbc086f19d7dcb14111bd17d66a5902/net/ddns-scripts/Makefile#L39

Old URL: http://wiki.openwrt.org/doc/howto/ddns.client
New URL: https://openwrt.org/docs/guide-user/services/ddns/client

Please update to the new URL.

**Comment by feckert** [comment]
I think we must cherry-pick this commit to openwrt-19.07 to fix this.
If so should this also go to the branch 18.06 (current stable) ?

**Comment by leonghui** [comment]
All done, PRs pending review.
