### ISSUE TITLE
ds-lite: old link to wiki.openwrt.org

### ISSUE THREAD

**Issue by tmo26** [openwrt/packages#10750]
@sbyx 

The ds-lite package still contains a link to the old wiki:

https://github.com/openwrt/openwrt/blob/487e0631d00c345b951cc31934e8e83a1e6e7cbe/package/network/ipv6/ds-lite/Makefile#L28

Old URL: http://wiki.openwrt.org/doc/uci/network
New URL: https://openwrt.org/docs/guide-user/base-system/basic-networking

Please update to the new URL.

**Comment by neheb** [comment]
This is the wrong place for this issue. Use https://bugs.openwrt.org/
