### ISSUE TITLE
Samba4 not compiling anymore

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10838]
Maintainer: @Andy2244 
Environment: master

example: https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/packages/samba4/compile.txt

That libpam thing used to be a race condition. Now it seems it's hitting it all the time.

edit: Those patches should also be refreshed.

**Comment by Andy2244** [comment]
yes i opted to not depend on those race condition libs anymore and will instead try to actually fix or at least upstream a issue in cases, where samba pulls them in and ignores its own configuration.

In the pam case, i'm not sure why the pam unbundle patch is not working anymore, need to investigate this.
