### ISSUE TITLE
h2o not compiling under uClibc-ng

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10833]
Maintainer: @James-TR 
Environment: master uClibc-ng

https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/h2o/compile.txt

**Comment by James-TR** [comment]
That looks like the glibc spoofing in uclibc causing issues again. I'll make a patch to fix it later today :)

**Comment by James-TR** [comment]
This should be fixed by #10845
