### ISSUE TITLE
rpcsvc-proto questions

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#10840]
Maintainer: @Andy2244 
Environment: master

https://github.com/openwrt/packages/blob/master/libs/rpcsvc-proto/Makefile#L45

What is this? Why are you installing a binary to InstallDev? It cannot be ran in InstallDev as it is a target binary.

The install section is most likely useless. HostBuild has its own.

Package/rpcsvc-proto can probably be set to BUILDONLY:=1 as it installs nothing to the target, just provides InstallDev stuff.

This is also failing on arc700: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/rpcsvc-proto/compile.txt

It needs nls.mk as well as the proper depends.

**Comment by Andy2244** [comment]
>  It cannot be ran in InstallDev as it is a target binary.

Not sure anymore, have to retest where samba4 looks for those via qemu and cross-execute, where it actually can use target dev bins.

> It needs nls.mk as well as the proper depends.

ok, will fix this next year.
