### ISSUE TITLE
apr: Remove --without-pic from ./configure

### ISSUE THREAD

**Issue by minfrin** [openwrt/packages#10884]
Maintainer @heil

Description:

In the following commit the --without-pic flag has been added to apr. This has memory footprint implications, and ideally should be removed.

https://github.com/openwrt/packages/commit/165f72234dfe8cbb5cfc45b49bf3af134ffa834e

CC: @neheb

**Comment by neheb** [comment]
Increase or reduce?

**Comment by minfrin** [comment]
Increases the memory footprint - I understand that a library compiled with position independent code can be loaded and shared amongst processes, while non PIC code has to have a dedicated copy loaded for each process.

On a tight footprint this will make a difference.

**Comment by neheb** [comment]
Note that without-pic is passed and $(FPIC) is added. -fPic Vs -fpic

**Comment by minfrin** [comment]
I went down an autoconf rabbithole trying to find if a mechanism exists to set -fpic instead of -fPIC, as the current configure script isn't ideal, and I came up with a blank. :(

**Comment by neheb** [comment]
I doubt there is one. -fpic vs -fPIC is for slimming down some binaries. -fPIC always works.

**Comment by micmac1** [comment]
I agree with @minfrin, there's no good reason for "without-pic". Also `TARGET_CFLAGS += $(FPIC)` should be removed. There's no apparent reason for it.

**Comment by minfrin** [comment]
Is the point behind doing ${FPIC} to try and replace -fPIC with -fpic?

**Comment by micmac1** [comment]
Nope. What is behind the "$FPIC" (-fPIC) or (-fpic) depends on the target devices.

I've seen this often used in OpenWrt (and I removed it where I could). I think it was used 'a looooong time ago' as a workaround for some build problems, maybe.

**Comment by micmac1** [comment]
In some places there is a good reason to add $(FPIC), for instance when upstream doesn't provide a Makefile for a source that is meant to be compiled as a shared object (for instance chan-lantiq, which is a plugin for asterisk). I guess it's possible that some mistook it as a good thing for everything else, too ;)
