### ISSUE TITLE
apache: Use --enable-layout instead of patching log directories

### ISSUE THREAD

**Issue by minfrin** [openwrt/packages#10883]
Maintainer @heil

Description:

Instead of patching the log directory in 003-logdir_fix.patch, use --enable-layout=OpenWRT instead.

- Review http://svn.apache.org/viewvc?view=revision&revision=1872036 and confirm the config layout is correct. Send any corrections to the dev@httpd.apache.org list.
- If the config layout is correct, confirm so that it can be backported to httpd v2.4.x.
- Once backported, remove the patch and add --enable-layout=OpenWRT to ./configure.

**Comment by neheb** [comment]
Fixed by https://github.com/openwrt/packages/issues/10883 I believe.
