### ISSUE TITLE
motion fails to start

### ISSUE THREAD

**Issue by jaro3** [openwrt/packages#10899]
cannot get this to start either streaming or webcontrol interface, no netstat binding to any port, this is not a tls neither localhost issue....

motion - 4.2.2-1

motion_startup: Motion running as daemon process
webu_start_strm: Starting all camera streams on port 8081
webu_start_strm: Unable to start stream for camera 0
webu_start_ctrl: Starting webcontrol on port 8080
webu_start_ctrl: Unable to start MHD

**Comment by neheb** [comment]
Is this on 19.07?

**Comment by jaro3** [comment]
trunk git-19.291.72323  r11254

**Comment by neheb** [comment]
Update your feeds. This was fixed.

**Comment by jaro3** [comment]
Thx, could you point me to the fix/patch ?

**Comment by neheb** [comment]
https://github.com/openwrt/packages/tree/master/multimedia/motion/patches

**Comment by jaro3** [comment]
works, fantastic!
