### ISSUE TITLE
alpine compiling error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#1090]
configure: loading site script /home/main/x86_64/include/site/x86_64
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-openwrt-linux-strip... x86_64-openwrt-linux-uclibc-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-openwrt-linux-gnu
configure: Configuring for alpine 2.20 (x86_64-openwrt-linux-gnu))
checking for x86_64-openwrt-linux-gcc... x86_64-openwrt-linux-uclibc-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-openwrt-linux-uclibc-gcc accepts -g... yes
checking for x86_64-openwrt-linux-uclibc-gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of x86_64-openwrt-linux-uclibc-gcc... gcc3
checking for x86_64-openwrt-linux-uclibc-gcc option to accept ISO C99... -std=gnu99
checking for x86_64-openwrt-linux-uclibc-gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking whether make sets $(MAKE)... (cached) yes
checking whether ln -s works... yes
checking for gawk... (cached) gawk
checking for x86_64-openwrt-linux-ranlib... x86_64-openwrt-linux-uclibc-gcc-ranlib
checking how to print strings... printf
checking for a sed that does not truncate output... /home/main/x86_64/staging_dir/host/bin/sed
checking for grep that handles long lines and -e... /home/main/x86_64/staging_dir/host/bin/grep
checking for egrep... /home/main/x86_64/staging_dir/host/bin/grep -E
checking for fgrep... /home/main/x86_64/staging_dir/host/bin/grep -F
checking for ld used by x86_64-openwrt-linux-uclibc-gcc -std=gnu99... x86_64-openwrt-linux-uclibc-ld
checking if the linker (x86_64-openwrt-linux-uclibc-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... x86_64-openwrt-linux-uclibc-gcc-nm
checking the name lister (x86_64-openwrt-linux-uclibc-gcc-nm) interface... BSD nm
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-openwrt-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for x86_64-openwrt-linux-uclibc-ld option to reload object files... -r
checking for x86_64-openwrt-linux-objdump... x86_64-openwrt-linux-uclibc-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-openwrt-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-openwrt-linux-ar... x86_64-openwrt-linux-uclibc-gcc-ar
checking for archiver @FILE support... @
checking for x86_64-openwrt-linux-strip... (cached) x86_64-openwrt-linux-uclibc-strip
checking for x86_64-openwrt-linux-ranlib... (cached) x86_64-openwrt-linux-uclibc-gcc-ranlib
checking command to parse x86_64-openwrt-linux-uclibc-gcc-nm output from x86_64-openwrt-linux-uclibc-gcc -std=gnu99 object... ok
checking for sysroot... no
checking for x86_64-openwrt-linux-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... x86_64-openwrt-linux-uclibc-gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-openwrt-linux-uclibc-gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for x86_64-openwrt-linux-uclibc-gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if x86_64-openwrt-linux-uclibc-gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if x86_64-openwrt-linux-uclibc-gcc -std=gnu99 static flag -static works... yes
checking if x86_64-openwrt-linux-uclibc-gcc -std=gnu99 supports -c -o file.o... yes
checking if x86_64-openwrt-linux-uclibc-gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the x86_64-openwrt-linux-uclibc-gcc -std=gnu99 linker (x86_64-openwrt-linux-uclibc-ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ar... /usr/bin/ar
checking for rm... /bin/rm
checking for cp... /home/main/x86_64/staging_dir/host/bin/cp
checking for ln... /bin/ln
checking for ls... /bin/ls
checking for sed... (cached) /home/main/x86_64/staging_dir/host/bin/sed
checking for make... /usr/bin/make
checking whether NLS is requested... no
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by GCC... x86_64-openwrt-linux-uclibc-ld -m elf_x86_64
checking if the linker (x86_64-openwrt-linux-uclibc-ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking whether to use NLS... no
checking option: dmalloc enabled... no
checking option: debugging is enabled... no
checking option: optimization is enabled... yes
checking option: mouse support enabled... no
checking option: quotas enabled... no
checking option: From changing enabled... yes
checking option: background post enabled... yes
checking option: keyboard lock enabled... yes
checking option: from encoding enabled... no
checking for sendmail... /usr/sbin/sendmail
checking for inews... no
checking for passwd... /usr/bin/passwd
checking for hunspell... no
checking for aspell... aspell
checking for aspell... /usr/bin/aspell
checking for hunspell... no
checking for aspell... aspell
checking for aspell... /usr/bin/aspell
configure: Excluding LDAP Support
configure: Excluding TCL Support, and thus Web Alpine Support
checking for setupterm in -ltinfo... no
checking for setupterm in -lncurses... yes
checking for library containing dlopen... -ldl
checking Openssl library version >= 1.0.1c... configure: WARNING: cross compiling: not checking
checking for library containing TLSv1_2_client_method... no
checking for library containing SSLeay... no
configure: error: crypto library NOT found
make[3]: *** [/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/alpine-ssl/alpine-2.20/.configured_yyyyyyyyn] Error 1
make[3]: Leaving directory `/home/main/x86_64/feeds/packages/mail/alpine'
make[2]: *** [package/feeds/packages/alpine/compile] Error 2
make[2]: Leaving directory `/home/main/x86_64'
make[1]: *** [/home/main/x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86_64'
make: *** [world] Error 2

**Comment by hnyman** [comment]
Old bug report, alpine compiles currently ok at the trunk buildbots.
