### ISSUE TITLE
micropython-lib compiling error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#1092]
cp: `./example_yield_coro.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example_yield_coro.py' are the same file
cp: `./uu.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/uu.py' are the same file
cp: `./json' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/json' are the same file
cp: `./functools.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/functools.py' are the same file
cp: `./asyncio_slow.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/asyncio_slow.py' are the same file
cp: `./getopt.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/getopt.py' are the same file
cp: `./hashlib' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/hashlib' are the same file
cp: `./shutil.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/shutil.py' are the same file
cp: `./os' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/os' are the same file
cp: `./re.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/re.py' are the same file
cp: `./fnmatch.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/fnmatch.py' are the same file
cp: `./datetime.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/datetime.py' are the same file
cp: `./getpass.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/getpass.py' are the same file
cp: `./html' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/html' are the same file
cp: `./upip.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/upip.py' are the same file
cp: `./timeit.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/timeit.py' are the same file
cp: `./tempfile.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/tempfile.py' are the same file
cp: `./cmd.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/cmd.py' are the same file
cp: `./example_sigint_ign.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example_sigint_ign.py' are the same file
cp: `./test' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/test' are the same file
cp: `./reprlib.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/reprlib.py' are the same file
cp: `./pprint.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/pprint.py' are the same file
cp: `./shelve.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/shelve.py' are the same file
cp: `./queue.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/queue.py' are the same file
cp: `./logging.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/logging.py' are the same file
cp: `./tests' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/tests' are the same file
cp: `./collections' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/collections' are the same file
cp: `./shlex.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/shlex.py' are the same file
cp: `./errno.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/errno.py' are the same file
cp: `./keyword.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/keyword.py' are the same file
cp: `./csv.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/csv.py' are the same file
cp: `./hmac.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/hmac.py' are the same file
cp: `./abc.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/abc.py' are the same file
cp: `./random.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/random.py' are the same file
cp: `./example-extract.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example-extract.py' are the same file
cp: `./dbm.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/dbm.py' are the same file
cp: `./http' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/http' are the same file
cp: `./contextlib.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/contextlib.py' are the same file
cp: `./binascii.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/binascii.py' are the same file
cp: `./quopri.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/quopri.py' are the same file
cp: `./bisect.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/bisect.py' are the same file
cp: `./optparse.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/optparse.py' are the same file
cp: `./calendar.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/calendar.py' are the same file
cp: `./string.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/string.py' are the same file
cp: `./itertools.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/itertools.py' are the same file
cp: `./uasyncio.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/uasyncio.py' are the same file
cp: `./mailbox.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/mailbox.py' are the same file
cp: `./warnings.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/warnings.py' are the same file
cp: `./email' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/email' are the same file
cp: `./socket.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/socket.py' are the same file
cp: `./pty.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/pty.py' are the same file
cp: `./ipaddress.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/ipaddress.py' are the same file
cp: `./sqlite3.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/sqlite3.py' are the same file
cp: `./copy.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/copy.py' are the same file
cp: `./fcntl.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/fcntl.py' are the same file
cp: `./unittest.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/unittest.py' are the same file
cp: `./tests.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/tests.py' are the same file
cp: `./example_strftime.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example_strftime.py' are the same file
cp: `./urllib.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/urllib.py' are the same file
cp: `./pickle.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/pickle.py' are the same file
cp: `./mimetypes.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/mimetypes.py' are the same file
cp: `./subprocess.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/subprocess.py' are the same file
cp: `./zipfile.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/zipfile.py' are the same file
cp: `./time.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/time.py' are the same file
cp: `./binhex.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/binhex.py' are the same file
cp: `./signal.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/signal.py' are the same file
cp: `./types.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/types.py' are the same file
cp: `./benchmark' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/benchmark' are the same file
cp: `./stat.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/stat.py' are the same file
cp: `./heapq.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/heapq.py' are the same file
cp: `./utarfile.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/utarfile.py' are the same file
cp: `./_libc.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/_libc.py' are the same file
cp: `./io.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/io.py' are the same file
cp: `./gzip.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/gzip.py' are the same file
cp: `./traceback.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/traceback.py' are the same file
cp: `./select.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/select.py' are the same file
cp: `./sched.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/sched.py' are the same file
cp: `./urllib' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/urllib' are the same file
cp: `./glob.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/glob.py' are the same file
cp: `./posixpath.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/posixpath.py' are the same file
cp: `./tarfile.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/tarfile.py' are the same file
cp: `./uasyncio' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/uasyncio' are the same file
cp: `./base64.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/base64.py' are the same file
cp: `./multiprocessing.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/multiprocessing.py' are the same file
cp: `./example_warn.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example_warn.py' are the same file
cp: `./example_getenv.py' and `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/_install_tmp/example_getenv.py' are the same file
make[4]: *** [install] Error 123
make[4]: Leaving directory `/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3'
make[3]: *** [/home/main/x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/micropython-lib-0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-654c7d288603f7dae09eb09b57fb67b38c7ac6c3/.built] Error 2
make[3]: Leaving directory `/home/main/x86_64/feeds/packages/lang/micropython-lib'
make[2]: *** [package/feeds/packages/micropython-lib/compile] Error 2
make[2]: Leaving directory `/home/main/x86_64'
make[1]: *** [/home/main/x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86_64'
make: *** [world] Error 2
main@bogon:~/x86_64$

**Comment by roger-** [comment]
Hmm... maybe you need to do a `make clean`?

This seems to build fine on the [buildbot](https://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/packages/micropython-lib_0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-1_x86_64.ipk).

**Comment by roger-** [comment]
@taeasy

Any updates on this issue?

**Comment by hnyman** [comment]
No action for a while, micropython-lib compiles ok in the trunk buildbots.
