### ISSUE TITLE
zip: package missing in 19.07 and master

### ISSUE THREAD

**Issue by 4k3or3et** [openwrt/packages#10985]
I would like report a bug where package zip is missing 19.07.0. While installing i get an output:

`Unknown package 'zip'.
Collected errors:
 * opkg_install_cmd: Cannot install package zip.`

Thank you.

**Comment by neheb** [comment]
It should be available. Which platform?

Note that you need to run opkg update first.

**Comment by 4k3or3et** [comment]
> It should be available. Which platform?
> 
> Note that you need to run opkg update first.

opkg update command had been ran before trying to install zip package. 

platform is ramips - mt7621. Router ZBT WE1326.

**Comment by hnyman** [comment]
Copied my response from forum:

Likely a bug.
I can't install it on master although the package Makefile is in the packages feed repo and looks normal at the first glance.

The peculiar part is that there is  no downloadable package, and no item in the package listing, but still there is no failure log at buildbot.

But I was able to compile it by myself and install that .ipk in my router quite normally. Strange.

18.06 has the buildbot downloadable package, but master and 19.07 do not.

**Comment by 4k3or3et** [comment]
Sorry guys but i am noob here. Is there anyone who can fix that?

**Comment by hnyman** [comment]
I believe that I figured out the reason: name conflict

@mkresin introduced zip as a main repo build tool a year ago with https://github.com/openwrt/openwrt/commit/ad8c2d6099a7da5192ee6e2c52a8303642271877
That is now both in 19.07 and master.

And that host tool is defined as a package, so it likely prevents the actual installable package from the packages feed to get compiled in buildbot.

**Comment by hnyman** [comment]
Well, there is not actual package definition in the host tool, so it is likely not a full package, and should not interfere.

But there is a commented out last line, the buildpackage eval call. Could that interfere in buildbot, even if there is no target package definition?

**Comment by neheb** [comment]
ping @jow-

**Comment by 4k3or3et** [comment]
Is there any other way i could encourage someone who can fix this? Thank you.

**Comment by hnyman** [comment]
> Is there any other way i could encourage someone who can fix this? Thank you.

You can build it by yourself.

It may be something in the buildbot specific package evaluation logic that prevents the package being compiled there.

**Comment by 4k3or3et** [comment]
> > Is there any other way i could encourage someone who can fix this? Thank you.
> 
> You can build it by yourself.
> 
> It may be something in the buildbot specific package evaluation logic that prevents the package being compiled there.

I am complete noob in Linux environment. Would you be that kind and tell me how do i start?

**Comment by hnyman** [comment]
https://openwrt.org/docs/guide-developer/build-system/start

**Comment by diizzyy** [comment]
Use bsdtar instead (libarchive)? :-)

**Comment by 4k3or3et** [comment]
> https://openwrt.org/docs/guide-developer/build-system/start

I thought it is about compiling only zip package from the source. It looks like the matter is to create entire OpenWRT image. I will be honest, that is bigger than me.

Do you think guys someone will eventually fix the missing zip package or that is just my wishful thinking?

**Comment by 4k3or3et** [comment]
> bsdtar

Thank you but the it has to be really zip as it has to work natively on Windows without any additional decompressing software...

**Comment by diizzyy** [comment]
bsdtar generates zip-files compatible with Windows
https://www.libarchive.org/

**Comment by neheb** [comment]
@hnyman That's probably accurate.

utils/zip has

```
$(eval $(call HostBuild))
$(eval $(call BuildPackage,zip))
```

tools/zip has

```
$(eval $(call HostBuild))
#$(eval $(call BuildPackage,zip))
```

I think the HostBuild is conflicting here. OTOH I have this commit:

https://github.com/openwrt/packages/commit/b61ca9d885fc323d6d3f0a5a08a6fe09e20e9ad2

I will make a draft PR to test this.

**Comment by diizzyy** [comment]
...or take the opportunity to get rid of something that hasn't been touched in over 10 years ;-)

**Comment by neheb** [comment]
:). I do agree that bsdtar is superior.

**Comment by hnyman** [comment]
I think that the host build could be removed from the target package.
It and been added in 2017 to provide zip for others.
Not needed for the package itself.
And now there is the host tool.

Host addition in 2017
https://github.com/openwrt/packages/commit/7313348033e1bc53f0d4346036b5f98562b9379d#diff-d4d5e2fde1a43c1e588625e656ddc9f8

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/11089

It's still not being built. I have no idea why.

**Comment by hnyman** [comment]
You should separate the luarocks commit from the PR and commit luarocks separately (as that change corresponds to the already existing zip host tool froim tools).

Then PR 11089 would be just about zip. Right the lua things pollute and expand the build logs quite much.

**Comment by neheb** [comment]
This is still a problem btw.

**Comment by 4k3or3et** [comment]
On OpenWrt 19.07.1 the problem is exactly the same. Any other fixes can be tried to resolve the issue?

**Comment by neheb** [comment]
I can backport my commit that had some bugfixes. But the problem would be the same. I have no idea how to fix.

I think bsdtar is the best solution here.

**Comment by hnyman** [comment]
I wonder if we should just rename this package feed zip to "infozip".
That should remove the name collision.

**Comment by BKPepe** [comment]
@hnyman can we close this?
