### ISSUE TITLE
ZBT WE1326. High latency when on 5GHz network.

### ISSUE THREAD

**Issue by 4k3or3et** [openwrt/packages#10991]
Hi Guys

i just updated my ZBT WE1326 to stable 19.07.0. When my clients are connected to 5GHz i have very high pings to local IP of the router. Pings are between 50ms to timeout. It looks very unstable i would say. When connected to 2.4GHz interface i get around 1ms all the time. Tried on few devices. Tried different channels for that interface. No luck.

EDIT:

I have notice that when i change channel width from 80MHz do 20MHz situation gets a little better. In that case ping are lower up to 250ms. Changing channel width back to 80MHz gives usually around 500ms to timeout. In both casses pings are lower than 100ms very rare.

Any clues how to resolve the issue?

Thank you.

**Comment by neheb** [comment]
This is not the right place to report. Either https://github.com/openwrt/mt76 or https://bugs.openwrt.org
