### ISSUE TITLE
bmx6 fails to compile (missing deps)

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1100]
make[6]: Entering directory `/home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/lib/bmx6_uci_config'
ccache_cc  -pedantic -Wall -W -Wno-unused-parameter -Os -g3 -std=gnu99 -DGIT_REV=\"6a6195e46bf15ed58d75bdec14c2941aca31fc3f\" -DDEBUG_MALLOC  -pedantic -Wall -W -Wno-unused-parameter -Os -g3 -std=gnu99 -DGIT_REV=\"6a6195e46bf15ed58d75bdec14c2941aca31fc3f\" -DDEBUG_MALLOC -fpic -I../../ -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -fpic -I. -I/home/buildbot/slave-local/ar71xx_generic/build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -DNO_DEBUG_ALL -DNO_DEBUG_DUMP -c uci_config.c -o uci_config.o
ccache_cc -shared -luci -L/home/buildbot/slave-local/ar71xx_generic/build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib  uci_config.o -o bmx6_config.so
/home/buildbot/slave-local/ar71xx_generic/build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libuci.so: warning: the use of `mktemp' is dangerous, better use `mkstemp'
ln -f -s /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/lib/bmx6_uci_config/bmx6_config.so /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/lib/bmx6_uci_config/../bmx6_config.so
make[6]: Leaving directory `/home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/lib/bmx6_uci_config'

make[5]: Leaving directory `/home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/lib'
make[4]: Leaving directory `/home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401'
rstrip.sh: /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/ipkg-ar71xx/bmx6/usr/sbin/bmx6: executable
Packaged contents of /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/ipkg-ar71xx/bmx6 into /home/buildbot/slave-local/ar71xx_generic/build/bin/ar71xx/packages/routing/bmx6_r2014112401-4_ar71xx.ipk
rstrip.sh: /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/ipkg-ar71xx/bmx6-uci-config/usr/lib/bmx6_config.so: shared object
Packaged contents of /home/buildbot/slave-local/ar71xx_generic/build/build_dir/target-mips_34kc_uClibc-0.9.33.2/bmx6-r2014112401/ipkg-ar71xx/bmx6-uci-config into /home/buildbot/slave-local/ar71xx_generic/build/bin/ar71xx/packages/routing/bmx6-uci-config_r2014112401-4_ar71xx.ipk
Package bmx6-json is missing dependencies for the following libraries:
libjson-c.so.2
make[3]: *** [/home/buildbot/slave-local/ar71xx_generic/build/bin/ar71xx/packages/routing/bmx6-json_r2014112401-4_ar71xx.ipk] Error 1

**Comment by sbyx** [comment]
Wrong repo => https://github.com/openwrt-routing/packages
