### ISSUE TITLE
Tor Lack of multithread support

### ISSUE THREAD

**Issue by y-alexey** [openwrt/packages#11014]
For mipsel_24kc architecture package tor (oblivious) make with one thread available. Or, may be, need some unpublished options to start multithread. That's lead to 
![_20200114_035740](https://user-images.githubusercontent.com/58744516/72304864-f7d80800-3682-11ea-8e14-f72ebcc76404.JPG)100% load of one core.
Is this can be solved anyway?

**Comment by neheb** [comment]
Does tor even support multithreading? I would think no.

**Comment by y-alexey** [comment]
> Does tor even support multithreading?
First Google link "tor multithread" is to tor bug tracker about this problem 10 year ago. And it was solved, as I can see.

**Comment by jefferyto** [comment]
I believe this is the ticket you are referring to: https://trac.torproject.org/projects/tor/ticket/1749

If the problem was "solved" then the ticket would have been marked "resolved".

It doesn't mention Ubuntu (or Debian) at all. How do you know it is multithreaded on Ubuntu?

**Comment by y-alexey** [comment]
Looked like you right. Work on the go. https://trac.torproject.org/projects/tor/ticket/26296
