### ISSUE TITLE
luci-app-adblock error after install

### ISSUE THREAD

**Issue by ifuchs** [openwrt/packages#11015]
The file '/usr/lib/lua/luci/controller/adblock.lua' contains an invalid module line.
Please verify whether the module name is set to 'luci.controller.adblock' - It must correspond to the file path!

The line in the .lua file looks like this:

module("luci.controller.adblock", package.seeall)

What exactly should it be?

**Comment by dibdot** [comment]
please close your LuCI session, reset your LuCI caches `rm -rf /tmp/luci-*` and try again ...

**Comment by ifuchs** [comment]
Thanks! That resolved the problem. I am not sure how many of the lists the NSLU2 can support but it has 80972 domains now.
