### ISSUE TITLE
adblock report command not found

### ISSUE THREAD

**Issue by ifuchs** [openwrt/packages#11016]
I'm looking for the adblock report command as described here: [https://github.com/openwrt/packages/tree/master/net/adblock/files]
However, when I try to issue the command I get:

> root@OpenWrt:~# /etc/init.d/adblock report
> Syntax: /etc/init.d/adblock [command]
> 
> Available commands:
> 	start	Start the service
> 	stop	Stop the service
> 	restart	Restart the service
> 	reload	Reload configuration files (or restart if service does not implement reload)
> 	enable	Enable service autostart
> 	disable	Disable service autostart
> 	suspend	Suspend adblock processing
> 	resume	Resume adblock processing
> 	query	<DOMAIN> Query active blocklists for specific domains
> 	status	Print runtime information

**Comment by dibdot** [comment]
adblock reporting has been introduced with release 3.6.x ...
