### ISSUE TITLE
luajit: switch to dynamic mode causes build failure on macos

### ISSUE THREAD

**Issue by ldir-EDB0** [openwrt/packages#11037]
https://github.com/openwrt/packages/commit/820d1e830facc0787817b3cdebe467d316ca9cca introduces a build failure on macos:

'
make package/luajit/compile V=s     
make[1]: Entering directory `/Users/kevin/wrt'
make[2]: Entering directory `/Users/kevin/wrt/package/libs/toolchain'
echo "libc" >> /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "librt" >> /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory `/Users/kevin/wrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.16#0.15#0.39
make[2]: Entering directory `/Users/kevin/wrt/feeds/packages/lang/luajit'
touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.prepared_0f43241069bfbfeeb01718d414b2ab48_6664517399ebbbc92a37c5bb081b5c53_check
. /Users/kevin/wrt/include/shell.sh; gzip -dc /Users/kevin/wrt/dl/LuaJIT-2.1.0-beta3.tar.gz | tar -C /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3

Applying ./patches/010-lua-path.patch using plaintext: 
patching file src/luaconf.h
touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.prepared_0f43241069bfbfeeb01718d414b2ab48_6664517399ebbbc92a37c5bb081b5c53
rm -f /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.configured_*
rm -f /Users/kevin/wrt/staging_dir/target-x86_64_musl/stamp/.luajit_installed
(cd /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/./; if [ -x ./configure ]; then find /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ -name config.guess | xargs -r chmod u+w; find /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ -name config.guess | xargs -r -n1 cp --remove-destination /Users/kevin/wrt/scripts/config.guess; find /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ -name config.sub | xargs -r chmod u+w; find /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ -name config.sub | xargs -r -n1 cp --remove-destination /Users/kevin/wrt/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="ccache_cc -c -O2 -pipe -march=btver2 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3=LuaJIT-2.1.0-beta3 -Wformat -Werror=format-security -fpic -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-O2 -pipe -march=btver2 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3=LuaJIT-2.1.0-beta3 -Wformat -Werror=format-security -fpic -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-O2 -pipe -march=btver2 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3=LuaJIT-2.1.0-beta3 -Wformat -Werror=format-security -fpic -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/Users/kevin/wrt/staging_dir/target-x86_64_musl/usr/include -I/Users/kevin/wrt/staging_dir/toolchain-x86_64_gcc-9.2.0_musl/usr/include -I/Users/kevin/wrt/staging_dir/toolchain-x86_64_gcc-9.2.0_musl/include/fortify -I/Users/kevin/wrt/staging_dir/toolchain-x86_64_gcc-9.2.0_musl/include " LDFLAGS="-L/Users/kevin/wrt/staging_dir/target-x86_64_musl/usr/lib -L/Users/kevin/wrt/staging_dir/target-x86_64_musl/lib -L/Users/kevin/wrt/staging_dir/toolchain-x86_64_gcc-9.2.0_musl/usr/lib -L/Users/kevin/wrt/staging_dir/toolchain-x86_64_gcc-9.2.0_musl/lib -fpic -specs=/Users/kevin/wrt/include/hardened-ld-pie.specs -znow -zrelro "   ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-apple-darwin19.2.0 --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built
touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built_check
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j1 -C /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3 HOST_CC="ccache gcc -O2 -I/Users/kevin/wrt/staging_dir/host/include -I/Users/kevin/wrt/staging_dir/hostpkg/include -I/Users/kevin/wrt/staging_dir/target-x86_64_musl/host/include " CROSS="x86_64-openwrt-linux-musl-" DPREFIX=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr PREFIX=/usr TARGET_SYS=Linux TARGET_CFLAGS="-O2 -pipe -march=btver2 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3=LuaJIT-2.1.0-beta3 -Wformat -Werror=format-security -fpic -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" BUILDMODE=dynamic
==== Building LuaJIT 2.1.0-beta3 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
CC        lj_strscan.o
CC        lj_strfmt.o
CC        lj_strfmt_num.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
CC        lj_opt_mem.o
BUILDVM   lj_folddef.h
CC        lj_opt_fold.o
CC        lj_opt_narrow.o
CC        lj_opt_dce.o
CC        lj_opt_loop.o
CC        lj_opt_split.o
CC        lj_opt_sink.o
CC        lj_mcode.o
CC        lj_snap.o
CC        lj_record.o
CC        lj_crecord.o
BUILDVM   lj_recdef.h
CC        lj_ffrecord.o
CC        lj_asm.o
CC        lj_trace.o
CC        lj_gdbjit.o
CC        lj_ctype.o
CC        lj_cdata.o
CC        lj_cconv.o
CC        lj_ccall.o
CC        lj_ccallback.o
CC        lj_carith.o
CC        lj_clib.o
CC        lj_cparse.o
CC        lj_lib.o
CC        lj_alloc.o
CC        lib_aux.o
BUILDVM   lj_libdef.h
CC        lib_base.o
CC        lib_math.o
CC        lib_bit.o
CC        lib_string.o
CC        lib_table.o
CC        lib_io.o
CC        lib_os.o
CC        lib_package.o
CC        lib_debug.o
CC        lib_jit.o
CC        lib_ffi.o
CC        lib_init.o
DYNLINK   libluajit.so
CC        luajit.o
BUILDVM   jit/vmdef.lua
LINK      luajit
OK        Successfully built LuaJIT
==== Successfully built LuaJIT 2.1.0-beta3 ====
rm -rf /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install
mkdir -p /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3 DPREFIX=/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr PREFIX=/usr TARGET_SYS=Linux install
==== Installing LuaJIT 2.1.0-beta3 to /usr ====
mkdir -p /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/bin /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/include/luajit-2.1 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/share/man/man1 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/pkgconfig /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/share/luajit-2.1.0-beta3/jit /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/share/lua/5.1 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/lua/5.1
cd src && install -m 0755 luajit /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/bin/luajit-2.1.0-beta3
cd src && test -f libluajit.a && install -m 0644 libluajit.a /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.a || :
rm -f /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so.2.1.0 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so.2
cd src && test -f libluajit.so && \
	  install -m 0755 libluajit.so /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so.2.1.0 && \
	  ldconfig -n /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib && \
	  ln -sf libluajit-5.1.so.2.1.0 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so && \
	  ln -sf libluajit-5.1.so.2.1.0 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/libluajit-5.1.so.2 || :
cd etc && install -m 0644 luajit.1 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/share/man/man1
cd etc && sed -e "s|^prefix=.*|prefix=/usr|" -e "s|^multilib=.*|multilib=lib|" luajit.pc > luajit.pc.tmp && \
	  install -m 0644 luajit.pc.tmp /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/pkgconfig/luajit.pc && \
	  rm -f luajit.pc.tmp
cd src && install -m 0644 lua.h lualib.h lauxlib.h luaconf.h lua.hpp luajit.h /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/include/luajit-2.1
cd src/jit && install -m 0644 bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua dis_mips64.lua dis_mips64el.lua vmdef.lua /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/share/luajit-2.1.0-beta3/jit
==== Successfully installed LuaJIT 2.1.0-beta3 to /usr ====

Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta3 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/bin/luajit

touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built
mkdir -p /Users/kevin/wrt/bin/targets/x86/64/packages /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/CONTROL /Users/kevin/wrt/staging_dir/target-x86_64_musl/pkginfo
install -d -m0755 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/lib/
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/*.so* /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/lib/
install -d -m0755 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/bin
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/bin/luajit-2.1.0-beta3 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/bin/luajit
find /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="x86_64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="x86_64-openwrt-linux-musl-nm" STRIP="x86_64-openwrt-linux-musl-strip --strip-all" STRIP_KMOD="/Users/kevin/wrt/scripts/strip-kmod.sh" PATCHELF="/Users/kevin/wrt/staging_dir/host/bin/patchelf" /Users/kevin/wrt/scripts/rstrip.sh /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit
rstrip.sh: /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/bin/luajit: executable
rstrip.sh: /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/usr/lib/libluajit-5.1.so.2.1.0: shared object
(cd /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -x "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -x "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /Users/kevin/wrt/bin/packages/x86_64/packages
/Users/kevin/wrt/scripts/ipkg-build -c -o 0 -g 0 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit /Users/kevin/wrt/bin/packages/x86_64/packages
Packaged contents of /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-x86_64/luajit into /Users/kevin/wrt/bin/packages/x86_64/packages/luajit_2.1.0-beta3-3_x86_64.ipk
rm -rf /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit.installed /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit
mkdir -p /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit
install -d -m0755 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit/usr/lib/
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/*.so* /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit/usr/lib/
install -d -m0755 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit/usr/bin
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/bin/luajit-2.1.0-beta3 /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit/usr/bin/luajit
touch /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.pkgdir/luajit.installed
rm -rf /Users/kevin/wrt/tmp/stage-luajit
mkdir -p /Users/kevin/wrt/tmp/stage-luajit/host /Users/kevin/wrt/staging_dir/target-x86_64_musl/packages /Users/kevin/wrt/staging_dir/host/packages
install -d -m0755 /Users/kevin/wrt/tmp/stage-luajit/usr/include/luajit-2.1
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/include/luajit-2.1/*.{h,hpp} /Users/kevin/wrt/tmp/stage-luajit/usr/include/luajit-2.1
install -d -m0755 /Users/kevin/wrt/tmp/stage-luajit/usr/lib
cp -fpR /Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/*.{a,so*} /Users/kevin/wrt/tmp/stage-luajit/usr/lib/
cp: cannot stat '/Users/kevin/wrt/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr/lib/*.a': No such file or directory
make[2]: *** [/Users/kevin/wrt/staging_dir/target-x86_64_musl/stamp/.luajit_installed] Error 1
make[2]: Leaving directory `/Users/kevin/wrt/feeds/packages/lang/luajit'
time: package/feeds/packages/luajit/compile#12.74#1.92#15.34
make[1]: *** [package/feeds/packages/luajit/compile] Error 2
make[1]: Leaving directory `/Users/kevin/wrt'
make: *** [package/luajit/compile] Error 2
'

**Comment by neheb** [comment]
https://github.com/openwrt/packages/commit/51de4b2e35607ab9561b58d581b832fcaa8978b5
