### ISSUE TITLE
<radicale-py3> Missing dependency python3-urllib in 19.07.0

### ISSUE THREAD

**Issue by ddast** [openwrt/packages#11062]
Maintainer: @jefferyto
Environment: OpenWrt 19.07.0 (TP-Link C2600)

Description:
Updated to 19.07.0 and installed radicale-py3. Radicale does not start since the module urllib is missing.  This can be fixed by installing python3-urllib.

It looks like this was already fixed in [master](https://github.com/openwrt/packages/blob/master/net/radicale/Makefile) in commit 9c5a97c31974096d7d2a6f482dc78971b9b578d0, however, [branch 19.07 ](https://github.com/openwrt/packages/blob/openwrt-19.07/net/radicale/Makefile)does not have python3-urllib as a dependecy.  Actually the mentioned commit replaces the dependency python3-email with python3-light and python3-urllib.

**Comment by jefferyto** [comment]
Thanks for the report - sounds like you know exactly what needs to be updated (replacing the python3-email dependency with python3-urllib should be enough). Do you want to open a PR with this change?

(As per the [Contributing Guidelines](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md), you'll also need to increment `PKG_RELEASE` and include a `Signed-off-by` tag in the commit message.)

**Comment by ddast** [comment]
Thanks for the fast reply.  I created PR #11078.

**Comment by jefferyto** [comment]
With #11078 merged, this should be fixed.
