### ISSUE TITLE
wget error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#1107]
i486-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/etc/wgetrc\" -DLOCALEDIR=\"/usr/share/locale\" -I.  -I../lib -I../lib -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include   -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -DNDEBUG -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -MT ftp-opie.o -MD -MP -MF .deps/ftp-opie.Tpo -c -o ftp-opie.o ftp-opie.c
mv -f .deps/ftp-opie.Tpo .deps/ftp-opie.Po
i486-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/etc/wgetrc\" -DLOCALEDIR=\"/usr/share/locale\" -I.  -I../lib -I../lib -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include   -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -DNDEBUG -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -MT openssl.o -MD -MP -MF .deps/openssl.Tpo -c -o openssl.o openssl.c
mv -f .deps/openssl.Tpo .deps/openssl.Po
i486-openwrt-linux-uclibc-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/etc/wgetrc\" -DLOCALEDIR=\"/usr/share/locale\" -I.  -I../lib -I../lib -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include   -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -DNDEBUG -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -MT http-ntlm.o -MD -MP -MF .deps/http-ntlm.Tpo -c -o http-ntlm.o http-ntlm.c
mv -f .deps/http-ntlm.Tpo .deps/http-ntlm.Po
i486-openwrt-linux-uclibc-gcc  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include  -DNDEBUG -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable   -L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/lib -L/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib  -o wget connect.o convert.o cookies.o ftp.o css_.o css-url.o ftp-basic.o ftp-ls.o hash.o host.o html-parse.o html-url.o http.o init.o log.o main.o netrc.o progress.o ptimer.o recur.o res.o retr.o spider.o url.o warc.o utils.o exits.o build_info.o  version.o ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a -L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -lpcre  /home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib/libssl.so /home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib/libcrypto.so -ldl -L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -lz   
utils.o: In function `touch':
utils.c:(.text+0x439): warning: the use of OBSOLESCENT `utime' is discouraged, use `utimes'
/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
make[7]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/src'
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/src'
Making all in doc
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/doc'
./texi2pod.pl -D VERSION="1.16.3" ./wget.texi wget.pod
/usr/bin/pod2man --center="GNU Wget" --release="GNU Wget 1.16.3" wget.pod > wget.1
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/doc'
Making all in po
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/po'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/po'
Making all in tests
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/tests'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/tests'
Making all in util
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/util'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/util'
Making all in testenv
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/testenv'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/testenv'
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3'
make[6]: Nothing to be done for `all-am'.
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3'
make[5]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3'
make[4]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3'
touch /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/.built
mkdir -p /home/main/x86/bin/x86/packages /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget/CONTROL /home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/pkginfo
install -d -m0755 /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget/usr/bin
install -m0755 /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/src/wget /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget/usr/bin/wget-ssl
find /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="i486-openwrt-linux-uclibc-" NO_RENAME=1 ; NM="i486-openwrt-linux-uclibc-nm" STRIP="/home/main/x86/staging_dir/host/bin/sstrip" STRIP_KMOD="/home/main/x86/scripts/strip-kmod.sh" PATCHELF="/home/main/x86/staging_dir/host/bin/patchelf" /home/main/x86/scripts/rstrip.sh /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget
rstrip.sh: /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget/usr/bin/wget-ssl: executable
(cd /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/wget-ssl/wget-1.16.3/ipkg-x86/wget/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_wget_postinst" > postinst-pkg; chmod 0755 postinst-pkg echo "$V_Package_wget_postrm" > postrm1;  )
chmod: cannot access `echo': No such file or directory
chmod: cannot access `#!/bin/sh\nrm ${IPKG_INSTROOT}/usr/bin/wget\n[ -x ${IPKG_INSTROOT}/usr/bin/wget-nossl ] && ln -s ./wget-nossl ${IPKG_INSTROOT}/usr/bin/wget || {\n  ln -s ../../bin/busybox ${IPKG_INSTROOT}/usr/bin/wget\n  ${IPKG_INSTROOT}/usr/bin/wget 2>&1 | grep \'applet not found\' > /dev/null 2>&1 && rm ${IPKG_INSTROOT}/usr/bin/wget\n}\nexit 0': No such file or directory
make[3]: *** [/home/main/x86/bin/x86/packages/packages/wget_1.16.3-1_x86.ipk] Error 1
make[3]: Leaving directory `/home/main/x86/feeds/packages/net/wget'
make[2]: *** [package/feeds/packages/wget/compile] Error 2
make[2]: Leaving directory `/home/main/x86'
make[1]: *** [/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86'
make: *** [world] Error 2

**Comment by hnyman** [comment]
>   chmod 0755 postinst-pkg echo "$V_Package_wget_postrm"

Like I commented in https://dev.openwrt.org/ticket/19380 : 

This looks like the same postinst/prerm command handling error that I just reported as #19381 at the Openwrt bug tracker. r45187 is probably missing a ";" causing trouble with postinst etc. commands. The problem should be fixed by r45193 and r45194.
The issue should be closed.
