### ISSUE TITLE
luci-app-acme not working for wildcard certs

### ISSUE THREAD

**Issue by northorsouth** [openwrt/packages#11095]
I'm trying to create a wildcard cert using the luci interface for acme.sh. The challenge fails. When I run run-acme.sh, I can see an error saying that the dns-01 challenge is required but the http-01 challenge is used (the dns challenge is required for wildcard certs). I have my cloudflare email and API key in the supplied fields, so the script should be able to use the dns challenge, not sure what's going wrong.

**Comment by neheb** [comment]
ping @tohojo

**Comment by tohojo** [comment]
Could you please post your config (without passwords, obviously), and the debug log output?

**Comment by northorsouth** [comment]
![FireShot Capture 002 - openwrt - ACME certs - LuCI - openwrt](https://user-images.githubusercontent.com/7483691/72921848-f02ff780-3d43-11ea-877b-ea44dad7cfec.png)

Let me know if you need more info

**Comment by northorsouth** [comment]
I'll post the output of run-acme in a sec

**Comment by northorsouth** [comment]
Here's the debug output of run-acme, pretty sure I removed keys and identifying info.
Error of interest: "The supported validation types are: dns-01 , but you specified: http-01"

`acme: Running pre checks for domain.tld.
acme: port80 listens: 20639/nginx.conf 
acme: Found nginx listening on port 80; trying to disable.
acme: Waiting for nginx to stop...
acme: v4 input_rule: Chain input_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 /* ACME */
acme: v6 input_rule: Chain input_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:80 /* ACME */
acme: Running ACME for domain.tld
acme: Using standalone mode
logger: unrecognized option: issue
BusyBox v1.28.4 () multi-call binary.

Usage: logger [OPTIONS] [MESSAGE]

Write MESSAGE (or stdin) to syslog

	-s	Log to stderr as well as the system log
	-t TAG	Log using the specified tag (defaults to user name)
	-p PRIO	Priority (numeric or facility.level pair)
Wildcard domain
Lets find script dir.
_SCRIPT_='/usr/lib/acme/acme.sh'
_script='/usr/lib/acme/acme.sh'
_script_home='/usr/lib/acme'
Using config home:/etc/acme
https://github.com/Neilpang/acme.sh
v2.8.3
Running cmd: issue
_main_domain='domain.tld'
_alt_domains='*.domain.tld'
Using config home:/etc/acme
ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
DOMAIN_PATH='/etc/acme/domain.tld'
Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
_init api for server: https://acme-v02.api.letsencrypt.org/directory
GET
url='https://acme-v02.api.letsencrypt.org/directory'
timeout=
_CURL='curl -L --silent --dump-header /etc/acme/http.header  -g '
ret='0'
ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
ACME_NEW_AUTHZ
ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
ACME_VERSION='2'
_on_before_issue
_chk_main_domain='domain.tld'
_chk_alt_domains='*.domain.tld'
Le_LocalAddress
d='domain.tld'
Check for domain='domain.tld'
_currentRoot='no'
Standalone mode.
_checkport='80'
_checkaddr
Using: netstat
d='*.domain.tld'
Check for domain='*.domain.tld'
_currentRoot='no'
Standalone mode.
_checkport='80'
_checkaddr
Using: netstat
d
_saved_account_key_hash is not changed, skip register account.
Read key length:
Creating domain key
Using config home:/etc/acme
ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
Use length 2048
Using RSA: 2048
The domain key is here: /etc/acme/domain.tld/domain.tld.key
_createcsr
Multi domain='DNS:domain.tld,DNS:*.domain.tld'
Getting domain auth token for each domain
d='*.domain.tld'
d
url='https://acme-v02.api.letsencrypt.org/acme/new-order'
payload='{"identifiers": [{"type":"dns","value":"domain.tld"},{"type":"dns","value":"*.domain.tld"}]}'
RSA key
HEAD
_post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
_CURL='curl -L --silent --dump-header /etc/acme/http.header  -g  -I  '
_ret='0'
POST
_post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
_CURL='curl -L --silent --dump-header /etc/acme/http.header  -g '
_ret='0'
code='201'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/76372347/2104313412'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/76372347/2104313412'
url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/2415620293'
payload
POST
_post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/2415620293'
_CURL='curl -L --silent --dump-header /etc/acme/http.header  -g '
_ret='0'
code='200'
url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/2415620294'
payload
POST
_post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/2415620294'
_CURL='curl -L --silent --dump-header /etc/acme/http.header  -g '
_ret='0'
code='200'
d='domain.tld'
Getting webroot for domain='domain.tld'
_w='no'
_currentRoot='no'
entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/2415620294/nzc30w","token":"somelongkey"'
token='somelongkey'
uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/2415620294/nzc30w'
keyauthorization='somelongkey.someotherlongkey'
dvlist='domain.tld#somelongkey.someotherlongkey#https://acme-v02.api.letsencrypt.org/acme/chall-v3/2415620294/nzc30w#http-01#no'
d='*.domain.tld'
Getting webroot for domain='*.domain.tld'
_w='no'
_currentRoot='no'
entry
Error, can not get domain token entry *.domain.tld
The supported validation types are: dns-01 , but you specified: http-01
pid
No need to restore nginx, skip.
_clearupdns
dns_entries
skip dns.
_on_issue_err
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2u  20 Dec 2019
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.12.2
built by gcc 7.3.0 (OpenWrt GCC 7.3.0 r7960-ab9d1bf608) 
built with OpenSSL 1.0.2u  20 Dec 2019
TLS SNI support enabled
configure arguments: --crossbuild=Linux::mipsel --prefix=/usr --conf-path=/etc/nginx/nginx.conf --add-module=/home/user/openwrt-18.06/build_dir/target-mipsel_24kc_musl/nginx-1.12.2/nginx-naxsi/naxsi_src --with-ipv6 --with-http_ssl_module --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc=mipsel-openwrt-linux-musl-gcc --with-cc-opt='-I/home/user/openwrt-18.06/staging_dir/target-mipsel_24kc_musl/usr/include -I/home/user/openwrt-18.06/staging_dir/target-mipsel_24kc_musl/include -I/home/user/openwrt-18.06/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/usr/include -I/home/user/openwrt-18.06/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify -I/home/user/openwrt-18.06/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/user/openwrt-18.06/build_dir/target-mipsel_24kc_musl/nginx-1.12.2:nginx-1.12.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fvisibility=hidden -ffunction-sections -fdata-sections -DNGX_LUA_NO_BY_LUA_BLOCK' --with-ld-opt='-L/home/user/openwrt-18.06/staging_dir/target-mipsel_24kc_musl/usr/lib -L/home/user/openwrt-18.06/staging_dir/target-mipsel_24kc_musl/lib -L/home/user/openwrt-18.06/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/usr/lib -L/home/user/openwrt-18.06/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/lib -znow -zrelro -Wl,--gc-sections' --without-http_upstream_zone_module
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]	groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>	groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>	groups=FD,SOCKET,RETRY,UNIX
      create:<filename>	groups=FD,REG,NAMED
      exec:<command-line>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>	groups=FD,SOCKET
      ip-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>	groups=FD,SOCKET,IP6
      open:<filename>	groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      pipe:<filename>	groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty	groups=FD,NAMED,TERMIOS,PTY
      sctp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>	groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]	groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>	groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>	groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
acme: Issuing cert for domain.tld failed. Moving state to /etc/acme/domain.tld.failed-1579717954
acme: Running post checks (cleanup).
Command failed: Not found
`

**Comment by tohojo** [comment]
northorsouth <notifications@github.com> writes:

> ![FireShot Capture 002 - openwrt - ACME certs - LuCI - openwrt](https://user-images.githubusercontent.com/7483691/72921848-f02ff780-3d43-11ea-877b-ea44dad7cfec.png)
>
> Let me know if you need more info

Hmm, it looks like your config is missing the field that sets which DNS
API to use? Maybe that's hiding under the '-- Addtional Field --'
dropdown?

**Comment by northorsouth** [comment]
Whoops, that's embarrassing. I assumed the "DNS API" field would just add another set of credentials fields.

Why isn't cloudflare on this list? Is it supported?
https://github.com/Neilpang/acme.sh/tree/master/dnsapi

**Comment by northorsouth** [comment]
Whoops, that's embarrassing. Got that now, and added the cloudflare script. There's a new error now:
"It seems that your api file is not correct, it must have a function named: dns_cf.sh_add"

**Comment by tohojo** [comment]
northorsouth <notifications@github.com> writes:

> Whoops, that's embarrassing. I assumed the "DNS API" field would just
> add another set of credentials fields.

Yeah, that is a bit obtuse, I'll admit; I added the field by default so
hopefully it should be more obvious...

> Why isn't cloudflare on this list? Is it supported?
> https://github.com/Neilpang/acme.sh/tree/master/dnsapi

Sure:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_cf.sh

**Comment by northorsouth** [comment]
Yeah sorry, I found the cf script and deleted that comment. See error above though.

**Comment by tohojo** [comment]
northorsouth <notifications@github.com> writes:

> Whoops, that's embarrassing. Got that now, and added the cloudflare script. There's a new error now:
> "It seems that your api file is not correct, it must have a function
> named: dns_cf.sh_add"

Lose the .sh :)

**Comment by northorsouth** [comment]
Sir, thank you for putting up with me

**Comment by tohojo** [comment]
northorsouth <notifications@github.com> writes:

> Sir, thank you for putting up with me

Haha, no worries! I guess it would be a bit friendlier to have a
dropdown box with the supported API types, but, well, nobody has
implemented that :)

**Comment by neheb** [comment]
Is this solved?

**Comment by tohojo** [comment]
I believe so, yeah...

**Comment by northorsouth** [comment]
yeah, solved. thanks guys
