### ISSUE TITLE
AdBlock: Whitelist not working?

### ISSUE THREAD

**Issue by forwardcomputers** [openwrt/packages#11125]
Maintainer: Dirk Brenken (dev@brenken.org)
Environment: (Netgear Nighthawk X4S R7800, OpenWrt 19.07.0 r10860-a3ffeb413b, Adblock: 3.8.14)

Description:

I added 'Bridge._hap._tcp.local' to the whitelist, but adblock keeps blocking it.

Config section minus blocklist
```
# cat /etc/config/adblock

config adblock 'global'
	option adb_basever '3.8'
	option adb_dns 'dnsmasq'
	option adb_dnsvariant 'nxdomain'
	option adb_fetchutil 'uclient-fetch'
	option adb_trigger 'wan'
	option adb_enabled '1'

config adblock 'extra'
	option adb_debug '0'
	option adb_report '1'
	option adb_backup '1'
	option adb_backupdir '/etc/adblock'
	option adb_backup_mode '1'
	option adb_nice '0'
	option adb_dnsfilereset 'false'
	option adb_repdir '/tmp'
	option adb_maxqueue '16'
	option adb_forcedns '1'
```

Whitelist file
```
# cat /etc/adblock/adblock.whitelist

Bridge._hap._tcp.local
logentries.com
```

Partial output from /tmp/adb_report
```
# grep '.local' /tmp/adb_report
2020-01-25	22:51:39	host.com	Bridge._hap._tcp.local	NX
2020-01-25	22:45:38	host.com	Bridge._hap._tcp.local	NX
2020-01-25	22:27:39	host.com	Bridge._hap._tcp.local	NX
2020-01-25	22:17:39	host.com	Bridge._hap._tcp.local	NX
```

**Comment by dibdot** [comment]
That's unrelated to adblock. Your dns backend simply can't resolve this local address (docker/home assistant related maybe!?). "NX" just means "**N**ot **E**xistant", it does not mean that adblock triggers this event. Please ask in the forum for further support.
