### ISSUE TITLE
ddns-scripts_no-ip_com: add no-ip.com support for ipv6

### ISSUE THREAD

**Issue by EmbeddedG** [openwrt/packages#11152]
Maintainer: @\chris5560
Environment: OpenWrt master

Description:
no-ip.com doesn't appear in the "DDNS Service provider [IPv6]" dropdown. I opened this issue after #8095 was closed because of wrong package reference in the subject.
I tested no-ip.com ipv6 update with a separate custom configuration for v6 by manually providing the update URL and it works. no-ip.com supports updating both v4 and v6 addresses together, or updating separately by using `myipv6` parameter for v6 instead of `myip`. Sending together is the method preferred by no-ip.com and they say that `myipv6` is for compatibility with clients that doesn't support updating both v4 and v6 addresses together ([see here](https://www.noip.com/integrate/request)).

**Comment by hnyman** [comment]
implemented by 33d6dc402 in late 2020...
