### ISSUE TITLE
ocserv - can not be compiled with enable seccomp

### ISSUE THREAD

**Issue by prowong** [openwrt/packages#11174]
After this commit: https://github.com/openwrt/packages/commit/072fcb5ce4938a962e2ec88d3e69dbd2b9f66e73 , ocserv can't be compiled with seccomp enabled .
  
`In file included from worker-privs.c:30:0:
worker-privs.c: In function 'disable_system_calls':
worker-privs.c:47:46: error: '__SNR_ppoll' undeclared (first use in this function); did you mean '__NR_ppoll'?
  ret = seccomp_rule_add(ctx, SCMP_ACT_ALLOW, SCMP_SYS(name), __VA_ARGS__); \
                                              ^
worker-privs.c:99:2: note: in expansion of macro 'ADD_SYSCALL'
  ADD_SYSCALL(ppoll, 0);
  ^~~~~~~~~~~
worker-privs.c:47:46: note: each undeclared identifier is reported only once for each function it appears in
  ret = seccomp_rule_add(ctx, SCMP_ACT_ALLOW, SCMP_SYS(name), __VA_ARGS__); \
                                              ^
worker-privs.c:99:2: note: in expansion of macro 'ADD_SYSCALL'
  ADD_SYSCALL(ppoll, 0);
  ^~~~~~~~~~~
worker-privs.c: At top level:
cc1: warning: unrecognized command line option '-Wno-stringop-truncation'
Makefile:1712: recipe for target 'worker-privs.o' failed
`
Thank you.

**Comment by prowong** [comment]
Delete this line `$(CP) $(PKG_INSTALL_DIR)/usr/include/seccomp-syscalls.h $(1)/usr/include/` in the Makefile of libseccomp can work. Maybe it should be made a switch in the file .

**Comment by neheb** [comment]
Sounds bogus.

**Comment by prowong** [comment]
Sorry for my poor english, but it's true.  The libseccomp is dependened by ocserv with seccomp enabled.

**Comment by neheb** [comment]
The solution is not correct. I don't know much about the package.

**Comment by prowong** [comment]
I found [this](https://github.com/openconnect/ocserv/commit/935818346d10f47fcea276b1243a6515257ef513). It works.  Update ocserv to the latest version may solve this problem.

**Comment by nmav** [comment]
The problem is a regression in libseccomp which was worked-arounded by ocserv. Thank you @prowong for identifying the issue.

**Comment by prowong** [comment]
Thanks for your great work, thank you very much.
________________________________
发件人: Nikos Mavrogiannopoulos <notifications@github.com>
发送时间: 2020年2月26日 5:11
收件人: openwrt/packages <packages@noreply.github.com>
抄送: prowong <drhzy@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [openwrt/packages] ocserv - can not be compiled with enable seccomp (#11174)


The problem is a regression in libseccomp which was worked-arounded by ocserv. Thank you @prowong<https://github.com/prowong> for identifying the issue.

―
