### ISSUE TITLE
[lighttpd] Selections not applied when compiling via SDK

### ISSUE THREAD

**Issue by yanosz** [openwrt/packages#1118]
Hello,

using 14.07's SDK on the master branch, I noticed that any selection for modules to include is not applied. 

For example: The systems tries to link against mysql, altough mysql-vhost is not selected.

@MikePetullo - as far as I see, the Makefiles is more ore less yours. Can you have a look, please?

Thanks, Jan
.config for SDK (lighttpd only), generated using <code>make menuconfig</code>

<pre>
#
# Web Servers/Proxies
#
CONFIG_PACKAGE_lighttpd=m
# CONFIG_LIGHTTPD_SSL is not set
# CONFIG_PACKAGE_lighttpd-mod-access is not set
# CONFIG_PACKAGE_lighttpd-mod-accesslog is not set
# CONFIG_PACKAGE_lighttpd-mod-alias is not set
# CONFIG_PACKAGE_lighttpd-mod-auth is not set
CONFIG_PACKAGE_lighttpd-mod-cgi=m
# CONFIG_PACKAGE_lighttpd-mod-cml is not set
# CONFIG_PACKAGE_lighttpd-mod-compress is not set
# CONFIG_PACKAGE_lighttpd-mod-evasive is not set
# CONFIG_PACKAGE_lighttpd-mod-evhost is not set
# CONFIG_PACKAGE_lighttpd-mod-expire is not set
# CONFIG_PACKAGE_lighttpd-mod-extforward is not set
# CONFIG_PACKAGE_lighttpd-mod-fastcgi is not set
# CONFIG_PACKAGE_lighttpd-mod-flv_streaming is not set
# CONFIG_PACKAGE_lighttpd-mod-magnet is not set
# CONFIG_PACKAGE_lighttpd-mod-mysql_vhost is not set
CONFIG_PACKAGE_lighttpd-mod-proxy=m
# CONFIG_PACKAGE_lighttpd-mod-redirect is not set
# CONFIG_PACKAGE_lighttpd-mod-rewrite is not set
# CONFIG_PACKAGE_lighttpd-mod-rrdtool is not set
# CONFIG_PACKAGE_lighttpd-mod-scgi is not set
# CONFIG_PACKAGE_lighttpd-mod-secdownload is not set
# CONFIG_PACKAGE_lighttpd-mod-setenv is not set
# CONFIG_PACKAGE_lighttpd-mod-simple_vhost is not set
# CONFIG_PACKAGE_lighttpd-mod-ssi is not set
# CONFIG_PACKAGE_lighttpd-mod-status is not set
# CONFIG_PACKAGE_lighttpd-mod-trigger_b4_dl is not set
# CONFIG_PACKAGE_lighttpd-mod-userdir is not set
# CONFIG_PACKAGE_lighttpd-mod-usertrack is not set
# CONFIG_PACKAGE_lighttpd-mod-webdav is not set
</pre>

Errors in shell:
Call: <code>$ make package/lighttpd/compile V=99
- libxml2 is needed but not declared:
  <pre>
  checking for XML... no
  configure: error: Package requirements (libxml-2.0) were not met:
  No package 'libxml-2.0' found
  Consider adjusting the PKG_CONFIG_PATH environment variable if you
  installed software in a non-standard prefix.
  Alternatively, you may set the environment variables XML_CFLAGS
  and XML_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  </pre>
- After installing libxml2 - sqlite3 is needed
  <pre>
  checking for SQLITE... no
  configure: error: Package requirements (sqlite3) were not met:
  No package 'sqlite3' found
  Consider adjusting the PKG_CONFIG_PATH environment variable if you
  installed software in a non-standard prefix.
  Alternatively, you may set the environment variables SQLITE_CFLAGS
  and SQLITE_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  </pre>
- When mysql was needed, I gave up -- since mysql didn't build for other reasons. 
  <pre>
  mv -f .deps/mod_mysql_vhost_la-mod_mysql_vhost.Tpo .deps/mod_mysql_vhost_la-mod_mysql_vhost.Plo
  /bin/bash ../libtool  --tag=CC   --mode=link ccache_cc  -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib  -o mod_mysql_vhost.la -rpath /usr/lib/lighttpd mod_mysql_vhost_la-mod_mysql_vhost.lo -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl  -lpthread
  OpenWrt-libtool: link: ccache_cc -shared  -fPIC -DPIC  .libs/mod_mysql_vhost_la-mod_mysql_vhost.o   -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lz -lm -lrt -ldl -lpthread  -Os -mno-branch-likely -mips32r2 -mtune=34kc -msoft-float -mips16 -minterlink-mips16   -Wl,-soname -Wl,mod_mysql_vhost.so -o .libs/mod_mysql_vhost.so
  /home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libmysqlclient.so when searching for -lmysqlclient
  /home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libmysqlclient.a when searching for -lmysqlclient
  /home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: cannot find -lmysqlclient
  collect2: error: ld returned 1 exit status
  make[6]: **\* [mod_mysql_vhost.la] Error 1
  make[6]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/src'
  make[5]: *** [all] Error 2
  make[5]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/src'
  Making all in doc
  make[5]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc'
  Making all in config
  make[6]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config'
  Making all in conf.d
  make[7]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config/conf.d'
  make[7]: Nothing to be done for`all'.
  make[7]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config/conf.d'
  Making all in vhosts.d
  make[7]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config/vhosts.d'
  make[7]: Nothing to be done for `all'.
  make[7]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config/vhosts.d'
  make[7]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config'
  make[7]: Nothing to be done for`all-am'.
  make[7]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config'
  make[6]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/config'
  Making all in scripts
  make[6]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/scripts'
  make[6]: Nothing to be done for`all'.
  make[6]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/scripts'
  Making all in initscripts
  make[6]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/initscripts'
  make[6]: Nothing to be done for `all'.
  make[6]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/initscripts'
  Making all in systemd
  make[6]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/systemd'
  make[6]: Nothing to be done for`all'.
  make[6]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/systemd'
  Making all in outdated
  make[6]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/outdated'
  make[6]: Nothing to be done for `all'.
  make[6]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc/outdated'
  make[6]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc'
  make[6]: Nothing to be done for`all-am'.
  make[6]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc'
  make[5]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/doc'
  Making all in tests
  make[5]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests'
  Making all in docroot
  make[6]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot'
  Making all in 123
  make[7]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/123'
  make[7]: Nothing to be done for`all'.
  make[7]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/123'
  Making all in www
  make[7]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www'
  Making all in go
  make[8]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/go'
  make[8]: Nothing to be done for`all'.
  make[8]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/go'
  Making all in indexfile
  make[8]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/indexfile'
  make[8]: Nothing to be done for `all'.
  make[8]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/indexfile'
  Making all in expire
  make[8]: Entering directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/expire'
  make[8]: Nothing to be done for`all'.
  make[8]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www/expire'
  make[8]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www'
  make[8]: Nothing to be done for `all-am'.
  make[8]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www'
  make[7]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot/www'
  make[7]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot'
  make[7]: Nothing to be done for `all-am'.
  make[7]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot'
  make[6]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests/docroot'
  make[6]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests'
  make[6]: Nothing to be done for `all-am'.
  make[6]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests'
  make[5]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/tests'
  make[5]: Entering directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35'
  make[5]: Nothing to be done for `all-am'.
  make[5]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35'
  make[4]: **\* [all-recursive] Error 1
  make[4]: Leaving directory `/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35'
  make[3]: *** [all] Error 2
  make[3]: Leaving directory`/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35'
  make[2]: **\* [/home/jan/freifunk/openwrt-ff-build/ar71xx-build/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/lighttpd-1.4.35/.built] Error 2
  make[2]: Leaving directory `/
  #(...) cropped
  </pre>

**Comment by yanosz** [comment]
P.S. 
When changing
<pre>
ifneq ($(SDK)$(CONFIG_PACKAGE_lighttpd-mod-mysql-vhost),)
  CONFIGURE_ARGS+= \
        --with-mysql
else
  CONFIGURE_ARGS+= \
        --without-mysql
endif
</pre>
To
<pre>
ifneq ($(SDK)$(CONFIG_PACKAGE_lighttpd-mod-mysql-vhost),)
  CONFIGURE_ARGS+= \
        --without-mysql
else
  CONFIGURE_ARGS+= \
        --without-mysql
endif
</pre> 
MySQL is not demaned anymore. 

I know, that this is not an option (since MySQL) is not used no matter what - But I guess there's something wrong with theses conditions.

**Comment by gstrauss** [comment]
@yanosz is this still an issue for you?

**Comment by diizzyy** [comment]
@hnyman @thess 
Please close, submitter timeout.
