### ISSUE TITLE
adblock package, dnscrypt-proxy support missing

### ISSUE THREAD

**Issue by makedir** [openwrt/packages#11205]
Why was dnscrypt-proxy removed as supported file output for the adblock package ( https://github.com/openwrt/packages/tree/master/net/adblock/files )? Please add it back, so the output file is in the format per line:

host.com

Is there a way to declare the output format too somewhere manually? the default output server=/host.com/ isnt compatible with dnscrypt-proxy.

**Comment by dibdot** [comment]
Just use dnsmasq to block ads (which is running in parallel anyway).

**Comment by makedir** [comment]
No it does not, because you use it for dnscrypt-proxy with

option localservice '0'
list server '127.0.0.53#53'

option serversfile '/tmp/adb_list.overall'
is ignored then.

**Comment by dibdot** [comment]
Then you can't use adblock for list generation unfortunately, I do not plan to bring back dnscrypt support.

**Comment by makedir** [comment]
And why is that? I am speaking about dnscrypt-proxy v2 (https://github.com/DNSCrypt/dnscrypt-proxy) not v1, which is in development. A support would just mean to alter a few lines in the script.

**Comment by dibdot** [comment]
Feel free to provide a PR for that ... it's much more than a "few lines" ... at least you have to make sure that all works with reporting, adblock query, suspend/resume etc.
