### ISSUE TITLE
Ransomware Tracker has been discontinued on Dec 8th, 2019

### ISSUE THREAD

**Issue by RonnyReporter** [openwrt/packages#11243]
Kept getting an error about parsing that list, opened up the url and it says its been discontinued. It might need to be removed and replaced by something else?

**Comment by dibdot** [comment]
This list has been already removed in adblock default.conf ... just install the package with the "force-maintainer" opkg option to overwrite your config.

![adblock](https://user-images.githubusercontent.com/8061346/73780069-16b35100-478e-11ea-8160-dd54ce103fc2.png)
