### ISSUE TITLE
Who can add CockroachDB to the master branch?

### ISSUE THREAD

**Issue by guo652917087** [openwrt/packages#11277]
Who can add CockroachDB to the master branch? URL: https://github.com/cockroachdb/cockroach

**Comment by neheb** [comment]
Many people. I doubt anyone is willing to.

I suggest reading up on go packages in this repository. I also assume @jefferyto would answer any questions you may have :).

**Comment by BKPepe** [comment]
I think you can try to ask on [OpenWrt forum](https://forum.openwrt.org/) to see if there's anyone who can add the package, which you want to this repository. For now, there is, for example, MariaDB.
