### ISSUE TITLE
intl:install icu-full-data but don't work.

### ISSUE THREAD

**Issue by xmlf** [openwrt/packages#11279]
Maintainer: @mhei 
Environment: X86_64

Description:
I install php7-mod-intl.
PHP version 7.4.1
intl ICU version 65.1

I need `Any-Latin;Latin-ASCII`, But icu only include:
```
Any-FCC
Any-FCD
Any-Hex
Any-Hex/C
Any-Hex/Java
Any-Hex/Perl
Any-Hex/Unicode
Any-Hex/XML
Any-Hex/XML10
Any-Lower
Any-Name
Any-NFC
Any-NFD
Any-NFKC
Any-NFKD
Any-Null
Any-Remove
Any-Title
Any-Upper
Hex-Any
Hex-Any/C
Hex-Any/Java
Hex-Any/Perl
Hex-Any/Unicode
Hex-Any/XML
Hex-Any/XML10
Name-Any
```
so the php page: `Warning: transliterator_transliterate(): Could not create transliterator with ID "Any-Latin; Latin-ASCII" (transliterator_create: unable to open ICU transliterator with id "Any-Latin; Latin-ASCII": U_INVALID_ID)`

I also install package 'icu-full-data'. 
`opkg install icu-full-data_65.1-2_x86_64.ipk`
But  it still not work.
What should I do?  Please help me, thank you.

**Comment by neheb** [comment]
ping @nxhack

**Comment by nxhack** [comment]
When I searched on Google, I found a lot. Please give me some time.

**Comment by nxhack** [comment]
Hi @xmlf 

Please let me know , is "CONFIG_PHP7_FULLICUDATA=y" set in build config?

**Comment by xmlf** [comment]
@nxhack 
What should I do to see this value?

**Comment by nxhack** [comment]
Perhaps you are using the package  (via opkg)?
Unfortunately, the packages published on OpenWrt site are not set to full-icu.
If you want to use full-icu, you need to build it yourself.

**Comment by xmlf** [comment]
YES.
I use the package  via opkg.
Many programs have detected intl extensions, it is believed that the icu transliteration device can work normally. But because there is no icu data, there are many warnings or errors.

**Comment by nxhack** [comment]
When we test the intl function, it looks like it works.

If you can, please give me a simple test script.

**Comment by xmlf** [comment]
```
            $transliterator = Transliterator::create('Any-Latin;Latin-ASCII');
            $slug           = $transliterator->transliterate($slug);
```

**Comment by nxhack** [comment]
```
root@OpenWrt:~# cat test.php
<?php
            $slug ='喜欢';
            $transliterator = Transliterator::create('Any-Latin;Latin-ASCII');
            $slug           = $transliterator->transliterate($slug);
	    echo $slug;
?>
root@OpenWrt:~# php-cli test.php 
xi huan
```

**Comment by xmlf** [comment]
The package installed by opkg does not contain transliterator id `Any-Latin;Latin-ASCII`.
How do you make it work correctly.

**Comment by nxhack** [comment]
Please show me icudt65l.dat size
```
ls -l /usr/share/icu/65.1/icudt65l.dat
```

**Comment by xmlf** [comment]
`
ls -l /usr/share/icu/65.1/icudt65l.dat
-rw-r--r-- 1 root root 27977584 2020-02-05 05:51 ./usr/share/icu/65.1/icudt65l.dat`

**Comment by nxhack** [comment]
hmm... Looks good

Are there any other logs when an error occurs?
```
logread
```

**Comment by xmlf** [comment]
I want to confirm whether my installation method is correct first:
1. opkg install php7-mod-intl
2. opkg install icu-full-data_65.1-2_x86_64.ipk

**Comment by nxhack** [comment]
OK Please wait until the environment is prepared.

**Comment by nxhack** [comment]
```
oot@OpenWrt:~# opkg install php7-mod-intl
Installing php7-mod-intl (7.4.2-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/php7-mod-intl_7.4.2-2_x86_64.ipk
Installing libxml2 (2.9.10-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/libxml2_2.9.10-1_x86_64.ipk
Installing php7 (7.4.2-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/php7_7.4.2-2_x86_64.ipk
Installing icu (65.1-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/icu_65.1-2_x86_64.ipk
Configuring libxml2.
Configuring php7.
Configuring icu.
Configuring php7-mod-intl.
root@OpenWrt:~# opkg install icu-full-data
Installing icu-full-data (65.1-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/icu-full-data_65.1-2_x86_64.ipk
Configuring icu-full-data.
root@OpenWrt:~# opkg install php7-cli
Installing php7-cli (7.4.2-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/php7-cli_7.4.2-2_x86_64.ipk
Configuring php7-cli.
root@OpenWrt:~# cat test.php 
<?php
            $slug ='武汉加油！中国加油！';
            $transliterator = Transliterator::create('Any-Latin;Latin-ASCII');
            $slug           = $transliterator->transliterate($slug);
	    echo $slug;
?>

root@OpenWrt:~# php-cli test.php 
wu han jia you! zhong guo jia you!
```

**Comment by xmlf** [comment]
I think I know what the problem is.
My opkg source from
http://bin.entware.net
I used Entware.
Entware does not have `icu-full-data`

**Comment by xmlf** [comment]
@nxhack 
@nxhack
山川异域，风月同天。
Thank you very much.I will close this and submit issu in entware。Thank you again.
