### ISSUE TITLE
nginx musl problem

### ISSUE THREAD

**Issue by lukas2511** [openwrt/packages#1129]
The nginx package doesn't build against musl, missing sys/sysctl.h and something about salts, no idea.

I found these patches and tried them (excluding the zlib patch since it wasn't required): https://github.com/mwcampbell/docker-nginx/tree/master/patches

Nginx does compile with those patches and seems to work completely fine.

**Comment by heil** [comment]
do you have more information? e.g what plattform, what revision etc.?

**Comment by lukas2511** [comment]
Building this with gcc 4.8.x linaro and musl for soc.allwinner.sunxi / Bananapi, but I don't think platform matters since this seems to be just a platform independent problem with nginx and musl.

I'm building the newest trunk version and nginx feed seems to come from this repository, checked out today.

**Comment by nekromant** [comment]
I can confirm this on Sunxi A20 Lamobo R1 board.

**Comment by heil** [comment]
Please send a dedicated PR that fixes building with musl.

**Comment by heil** [comment]
fixed via 9433d5ad285056c9476a899595df6d4785ec127e

**Comment by heil** [comment]
@lukas2511  are you fine with that?

**Comment by lukas2511** [comment]
didn't have time to test it yet, but looks about right

**Comment by nekromant** [comment]
@heil I've tested it yesterday night - nginx now compiles and even works! Thanks a lot! 

P.S. There's still what looks like a musl-related problem with etherwake with some struct redefined, I'll be investigating it today and maybe throw up a patch.

**Comment by Noltari** [comment]
@nekromant that's already fixed and waiting for maintainer: https://github.com/openwrt/packages/issues/1381

**Comment by nekromant** [comment]
@Noltari Oh, great! Thanks!

**Comment by karlp** [comment]
as far as I can tell, all issues reported here are now fixed, ==> closing this ticket.
