### ISSUE TITLE
Nginx-util error!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#11292]
![image](https://user-images.githubusercontent.com/45259624/74114663-58a52280-4be6-11ea-8003-d9145a369d89.png)

**Comment by peter-stadler** [comment]
Does `./scripts/feeds uninstall -a && ./scripts/feeds update -a && ./scripts/feeds install -a` helps?

**Comment by peter-stadler** [comment]
Thank you, I am about to [change it](https://github.com/openwrt/packages/pull/11294). Sorry that I did not see that before (I had `make menuconfig && make package/nginx-util/compile`) ...
