### ISSUE TITLE
frr: libreadline7 missing

### ISSUE THREAD

**Issue by scaci** [openwrt/packages#11304]
Maintainer: @lucize
Environment: (ARMv7 Processor rev 1 (v7l), Linksys WRT1200AC
, OpenWrt 19.07.1)

Description:

frr requires libreadline version 7, but openwrt 19.07.1 has version 8

workaround (seems to work): make 2 symlinks to library version 8:

libreadline.so.7 -> /usr/lib/libreadline.so.8
libreadline.so.7.0 -> /usr/lib/libreadline.so.8.0

**Comment by neheb** [comment]
Sounds like readline got bumped after frr. Meaning a rebuild is needed.

I think a PKG_RELEASE bump is all that's needed.

**Comment by diizzyy** [comment]
Probably, I don't follow 19.X branch at all however

**Comment by lucize** [comment]
frr I think is not on 19.x but it should have worked, please also update libyang

**Comment by neheb** [comment]
I cannot find this in the repositories for 19.07. Closing.
