### ISSUE TITLE
cups: cups_config missing

### ISSUE THREAD

**Issue by ElonH** [openwrt/packages#11317]
Maintainer: @luizluca 
Environment: (x86_64,  OpenWrt master)

Description:
https://github.com/openwrt/packages/blob/master/libs/libcups/Makefile#L87

cups_config should be installed in `$(1)/usr/bin/` and  `$(2)/bin` rather `$(2)/usr/bin`

``` bash
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/cups-config $(1)/usr/bin/

	$(INSTALL_DIR) $(2)/bin
	$(LN) $(STAGING_DIR)/usr/bin/cups-config $(2)/bin
```

reference:
https://github.com/openwrt/packages/blob/master/libs/pcre/Makefile#L75
lines: 75~78

**Comment by luizluca** [comment]
Done. Thanks @ElonH.
