### ISSUE TITLE
banip: Service automatically stopping

### ISSUE THREAD

**Issue by tdeeb** [openwrt/packages#11370]
Maintainer: @dibdot (find it by checking history of the package Makefile)
Environment: (Qualcomm Atheros IPQ8065, Netgear R7800 exploration, OpenWrt 19.07.1 r10911-c155900f66)

Version:
```
Linux version 4.14.167 (builder@buildhost) (gcc version 7.5.0 (OpenWrt GCC 7.5.0 r10911-c155900f66)) #0 SMP Wed Jan 29 16:05:35 2020
```

Package info:
```
Package: banip
Version: 0.3.11-1
Depends: libc, jshn, jsonfilter, ip, ipset, iptables, ca-bundle, logd
Status: install user installed
Section: net
Architecture: all

banip - 0.3.11-1
luci-app-banip - git-20.048.32085-85a6f07-1
```

Description: Whether I reload the banip service manually through SSH or the LuCI interface, the status changes from "running" to "enabled" very shortly after (roughly 5 seconds or less). I do not know how to keep it running, and the logs don't indicate why it's stopping. These are the only logs I have, with verbose debug logging:

```
banIP-0.3.11[26266]: f_bgserv ::: status: start, bg_pid: -, ban_realtime: 0, log_service: /etc/banip/banip.service
banIP-0.3.11[26266]: f_jsnup ::: status: enabled, setcnt: 2, cnt: 2
```
I'm using a vanilla banip config after having just installed the service and LuCI interface.

**Comment by dibdot** [comment]
"enabled" is the final state after "running", sounds OK.
