### ISSUE TITLE
coreutils-8.31 compiler error

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#11389]
![image](https://user-images.githubusercontent.com/45259624/74893123-877d7e80-53c6-11ea-9ea8-aa61d3ea3c41.png)

**Comment by zxlhhyccc** [comment]
gcc8.30 version also error

**Comment by garypang13** [comment]
https://github.com/openwrt/packages/issues/11384#issuecomment-588293018

**Comment by BlueMax** [comment]
Try [this](https://github.com/dslm4515/Musl-LFS/issues/4#issuecomment-526876214).
Works for me.

**Comment by snakwu** [comment]
> Try this. Works for me.
> https://lists.gnu.org/archive/html/bug-coreutils/2019-03/msg00028.html
> 
> thx to [dslm4515](https://github.com/dslm4515/Musl-LFS/issues/4#issuecomment-526876214)

Could you tell me how to patch it?thx
