### ISSUE TITLE
The firmware compiled by the latest master branch cannot be connected to the Internet, you must use other DNS resolution software to be normal!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#11392]
![image](https://user-images.githubusercontent.com/45259624/74929744-17e3af80-5417-11ea-9c24-e2bf238ddcd7.png)

**Comment by BKPepe** [comment]
No using provided issue template, no details. Just screenshots, which does not help. Title is too long. Closing.

This repository contains community maintained packages.
