### ISSUE TITLE
Unbound: trying to compile in ipset support, but ./configure does not find libmnl or libmnl.h

### ISSUE THREAD

**Issue by Borromini** [openwrt/packages#11402]
Maintainer: @EricLuehrsen 
Environment: master/ath79 (although target is probably not relevant)

Hi Eric! This is not a bug report but a request for help. I'm trying to include [ipset support](https://github.com/NLnetLabs/unbound/pull/28) into the OpenWrt package. From what I can see it should be as easy as adding `+libmnl` as a dependency (which I have added to both the library packages and the main unbound package) and adding `--enable-ipset` to the configure switches in the Makefile. However, a `make package/unbound/{clean,compile}` on master errors out with this error:

`Could not find libmnl, libmnl.h`

Libmnl is set as [m] in my .config so at least that should be OK. There's a `--with-libmnl=path` switch that Unbound configure supports but it seems to be wanting an absolute path, and I'm not sure how to approach that (given the path needs to be in the buildroot).

Can you help me out?

I can file a PR afterwards, I think ipset support would be neat to have both in the default `unbound-daemon` and in `unbound-daemon-heavy`.

If you'd like me to post this on the forum instead, let me know.

Thanks!

**Comment by EricLuehrsen** [comment]
Use the makefile staging directory symbol. Unbound flags in use have a few examples:
```
--with-ssl="$(STAGING_DIR)/usr"
```

**Comment by Borromini** [comment]
Thanks! That works. Will prep a PR, for unbound-heavy only then.
