### ISSUE TITLE
Eror build base-files openwrt 19.07.1 ath79. Help me 

### ISSUE THREAD

**Issue by server46** [openwrt/packages#11407]
`   rm -f /home/openwrt/openwrt/staging_dir/target-mips_24kc_musl/stamp/.base-files_installed
[ -s /home/openwrt/openwrt/key-build -a -s /home/openwrt/openwrt/key-build.pub ] || /home/openwrt/openwrt/staging_dir/host/bin/usign -G -s /home/openwrt/openwrt/key-build -p /home/openwrt/openwrt/key-build.pub -c "Local build key"
[ -s /home/openwrt/openwrt/key-build.ucert ] || /home/openwrt/openwrt/staging_dir/host/bin/ucert -I -c /home/openwrt/openwrt/key-build.ucert -p /home/openwrt/openwrt/key-build.pub -s /home/openwrt/openwrt/key-build
Makefile:216: recipe for target '/home/openwrt/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/base-files/.configured_b417930b1819b13738583790fe642133_8e081b74cf069e1e6800a5bbcbb282f0' failed
make[3]: *** [/home/openwrt/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/base-files/.configured_b417930b1819b13738583790fe642133_8e081b74cf069e1e6800a5bbcbb282f0] Error 255
make[3]: Leaving directory '/home/openwrt/openwrt/package/base-files'
time: package/base-files/compile#0.24#0.07#0.32
package/Makefile:111: recipe for target 'package/base-files/compile' failed
make[2]: *** [package/base-files/compile] Error 2
make[2]: Leaving directory '/home/openwrt/openwrt'
package/Makefile:107: recipe for target '/home/openwrt/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt'
/home/openwrt/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2  `

**Comment by BKPepe** [comment]
Base-files package comes from [OpenWrt main repository](https://github.com/openwrt/openwrt/blob/master/package/base-files/Makefile).

Closing.
