### ISSUE TITLE
xl2tpd: update package to upstream >=1.3.14

### ISSUE THREAD

**Issue by ugrufo** [openwrt/packages#11418]
There's a know issue in xl2tpd prior to version 1.3.14 which prevents a stable connection to Mikrotik endpoints.

The error seen in the log is
```
result_code_avp: avp is incorrect size. 8 < 10
```

The bug has been acknowledged and resolved upstream, see:
https://github.com/xelerance/xl2tpd/issues/90
https://github.com/xelerance/xl2tpd/issues/130
https://github.com/xelerance/xl2tpd/issues/156

Commit that should fix the issue
https://github.com/xelerance/xl2tpd/commit/9b939c0e1024c8a127ad2790440a3be7bc095932

Current openWRT version is 1.3.13

**Comment by neheb** [comment]
ping @yousong current version is 1.3.15: https://github.com/openwrt/packages/blob/master/net/xl2tpd/Makefile#L11

Unless you mean you want that backported.

**Comment by ugrufo** [comment]
> Unless you mean you want that backported.
 Updating it, unless it breaks something else, should be fine

**Comment by yousong** [comment]
Thanks for the report.  I will bump versions in both 19.07 and 18.06 to current 1.13.15.

xl2tpd as I see it these days only receives bug fixes plus some cleanups.  it should be fairly safe to do so.

**Comment by yousong** [comment]
The two backports were just merged.  Updated binaries should be available in the following 2 days.  Please test and post updates here.  Thanks again.

**Comment by yousong** [comment]
Binaries are now built for both 19.07 and 18.06 releases.  Thanks for the heads up
