### ISSUE TITLE
freeswitch error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#1142]
configure: loading site script /home/main/64/include/site/x86_64
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-openwrt-linux-gnu
checking target system type... x86_64-openwrt-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for working mkdir -p... yes
APR-util Version: 1.2.8
checking for chosen layout... apr-util
Applying apr-util hints file rules for x86_64-openwrt-linux-gnu
checking for APR... yes
  setting CPP to "/home/main/64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin/x86_64-openwrt-linux-uclibc-gcc -E"
  adding "-D_REENTRANT" to CPPFLAGS
  adding "-D_GNU_SOURCE" to CPPFLAGS
checking for x86_64-openwrt-linux-gcc... /home/main/64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin/x86_64-openwrt-linux-uclibc-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/main/64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin/x86_64-openwrt-linux-uclibc-gcc accepts -g... yes
checking for /home/main/64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin/x86_64-openwrt-linux-uclibc-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/main/64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin/x86_64-openwrt-linux-uclibc-gcc -E
checking for grep that handles long lines and -e... /home/main/64/staging_dir/host/bin/grep
checking for egrep... /home/main/64/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for ldap support...
checking for default DBM... sdbm (default)
checking for dbd/apr_dbd_mysql.c... configure: error: cannot check for file existence when cross compiling
configure: error: ./configure.gnu failed for libs/apr-util
make[2]: *** [/home/main/64/build_dir/target-x86_64_uClibc-0.9.33.2/freeswitch-1.5.14/.configured_yyyyyynnyynnnynnyynynnnyyynynyyyyyyyyyyyyynyynyyyyyyyyyyyyyyyyynyyyyyyynyynyyyynynynyyyynyyyyyyynnnnyyyyynnnynnyyyyynyyyyyyyyyyyyyyyyynyyyyyyyyynnnnnnyyyyyyynynyyyyyyyynynyyyyyyyyn] Error 1
make[2]: Leaving directory `/home/main/64/feeds/telephony/net/freeswitch'
make[1]: *** [package/feeds/telephony/freeswitch/compile] Error 2
make[1]: Leaving directory `/home/main/64'
make: *** [package/freeswitch/compile] Error 2
main@bogon:~/64$

**Comment by hnyman** [comment]
Freeswitch is not here in "packages", but in "telephony" repo. 
There is a separate bug tracker for that.
https://github.com/openwrt/telephony/issues
