### ISSUE TITLE
I would like to ask a few questions about the openwrt file system overlay, jffs2, ubifs, ext4

### ISSUE THREAD

**Issue by guo652917087** [openwrt/packages#11437]
Hello everyone, I recently encountered a problem with the file system on openwrt. I hope someone can help me.

**Question 1**: When using emmc, the overlay file system mounted in jffs2 format has exceeded 3G bytes. Is there any problem with this? Because when I look at the description of the jffs2 file system, the maximum file system is 128M bytes.

I tested writing a file of 1000M bytes, but the file system only consumed about 30M bytes, as shown in the figure:
![image](https://user-images.githubusercontent.com/17864680/75331921-78af3400-58be-11ea-9884-0361f5682378.png)

root@OpenWrt:/# mount
/dev/root on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/mtdblock4 on /overlay type jffs2 (rw,noatime)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
mountd(pid2298) on /tmp/run/blockd type autofs (rw,relatime,fd=7,pgrp=1,timeout=30,minproto=5,maxproto=5,indirect)
root@OpenWrt:/# 
root@OpenWrt:/# 
root@OpenWrt:/# df -hT
Filesystem           Type            Size      Used Available Use% Mounted on
/dev/root            squashfs       12.5M     12.5M         0 100% /rom
tmpfs                tmpfs         245.6M     38.1M    207.5M  16% /tmp
/dev/mtdblock4       jffs2           3.0G     50.5M      2.9G   2% /overlay
overlayfs:/overlay   overlay         3.0G     50.5M      2.9G   2% /
tmpfs                tmpfs         512.0K         0    512.0K   0% /dev
root@OpenWrt:/# 
root@OpenWrt:/# 
root@OpenWrt:/# dd if=/dev/zero of=/root/3 bs=1M count=1000
1000+0 records in
1000+0 records out
1048576000 bytes (1000.0MB) copied, 39.081873 seconds, 25.6MB/s
root@OpenWrt:/# 
root@OpenWrt:/# df -hT
Filesystem           Type            Size      Used Available Use% Mounted on
/dev/root            squashfs       12.5M     12.5M         0 100% /rom
tmpfs                tmpfs         245.6M     38.1M    207.5M  16% /tmp
/dev/mtdblock4       jffs2           3.0G     82.3M      2.9G   3% /overlay
overlayfs:/overlay   overlay         3.0G     82.3M      2.9G   3% /
tmpfs                tmpfs         512.0K         0    512.0K   0% /dev
root@OpenWrt:/# 
root@OpenWrt:/# 

**Question 2**. Should I use rootfstype = squashfs, ext4? But I changed the kernel startup command line parameter to rootfstype = squashfs, ext4, use squashfs.combined.bin，but the system does not recognize the file system

By the way, I have successfully run the board of nand flash, and I am currently testing the board of flash for emmc.

When using imx6, I have used the latest branch of openwrt to verify that the overlay supports rootfstype = squashfs, ubifs.here is logs:

[ 1.358530] Creating 5 MTD partitions on "gpmi-nand":
[ 1.363689] 0x000000000000-0x000000400000 : "uboot"
[ 1.381474] 0x000000400000-0x000000e00000 : "kernel"
[ 1.399690] 0x000000e00000-0x000000f00000 : "dtb"
[ 1.417313] 0x000000f00000-0x000002d00000 : "backup"
[ 1.436103] 0x000002d00000-0x000010000000 : "ubi"
[ 1.460574] gpmi-nand 1806000.gpmi-nand: driver registered.
[ 1.472067] spi_imx 2008000.ecspi: probed
[ 1.479211] spi_imx 200c000.ecspi: probed
[ 1.485365] libphy: Fixed MDIO Bus: probed
[ 1.491093] CAN device driver interface
[ 1.495671] 2090000.can supply xceiver not found, using dummy regulator
[ 1.505047] flexcan 2090000.can: device registered (reg_base=90a7c000, irq=28)
[ 1.512631] 2094000.can supply xceiver not found, using dummy regulator
[ 1.521722] flexcan 2094000.can: device registered (reg_base=90a84000, irq=29)
[ 1.532385] 20b4000.ethernet supply phy not found, using dummy regulator
[ 1.540289] pps pps0: new PPS source ptp0
[ 1.544775] fec 20b4000.ethernet eth1 (uninitialized): Invalid MAC address: 00:00:00:00:00:00
[ 1.553372] fec 20b4000.ethernet eth1 (uninitialized): Using random MAC address: ea:c9:dc:cd:9a:83
[ 1.563414] libphy: fec_enet_mii_bus: probed
[ 1.582302] fec 20b4000.ethernet eth1: registered PHC device 0
[ 1.590469] 2188000.ethernet supply phy not found, using dummy regulator
[ 1.598425] pps pps1: new PPS source ptp1
[ 1.605563] fec 2188000.ethernet eth0: registered PHC device 1
[ 1.613492] usbcore: registered new interface driver rtl8188eu
[ 1.619842] usbcore: registered new interface driver asix
[ 1.625602] usbcore: registered new interface driver ax88179_178a
[ 1.631907] usbcore: registered new interface driver cdc_ether
[ 1.638048] usbcore: registered new interface driver smsc95xx
[ 1.644038] usbcore: registered new interface driver net1080
[ 1.649858] usbcore: registered new interface driver cdc_subset
[ 1.656003] usbcore: registered new interface driver zaurus
[ 1.661786] usbcore: registered new interface driver cdc_ncm
[ 1.667674] usbcore: registered new interface driver huawei_cdc_ncm
[ 1.674039] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[ 1.680603] ehci-pci: EHCI PCI platform driver
[ 1.685289] ehci-mxc: Freescale On-Chip EHCI Host driver
[ 1.691280] usbcore: registered new interface driver cdc_wdm
[ 1.697407] usbcore: registered new interface driver usb-storage
[ 1.703849] usbcore: registered new interface driver usbserial
[ 1.709829] usbcore: registered new interface driver usbserial_generic
[ 1.716713] usbserial: USB Serial support registered for generic
[ 1.722884] usbcore: registered new interface driver ftdi_sio
[ 1.728866] usbserial: USB Serial support registered for FTDI USB Serial Device
[ 1.736393] usbcore: registered new interface driver option
[ 1.742100] usbserial: USB Serial support registered for GSM modem (1-port)
[ 1.749270] usbcore: registered new interface driver pl2303
[ 1.755041] usbserial: USB Serial support registered for pl2303
[ 1.761134] usbcore: registered new interface driver usb_ehset_test
[ 1.770557] 2184800.usbmisc supply vbus-wakeup not found, using dummy regulator
[ 1.780285] 2184000.usb supply vbus not found, using dummy regulator
[ 1.804448] 2184200.usb supply vbus not found, using dummy regulator
[ 1.814839] ci_hdrc ci_hdrc.1: EHCI Host Controller
[ 1.819837] ci_hdrc ci_hdrc.1: new USB bus registered, assigned bus number 1
[ 1.853735] ci_hdrc ci_hdrc.1: USB 2.0 started, EHCI 1.00
[ 1.861112] hub 1-0:1.0: USB hub found
[ 1.865130] hub 1-0:1.0: 1 port detected
[ 1.871856] mousedev: PS/2 mouse device common for all mice
[ 1.879771] input: 20cc000.snvs:snvs-powerkey as /devices/soc0/soc/2000000.aips-bus/20cc000.snvs/20cc000.snvs:snvs-powerkey/input/input0
[ 1.898422] snvs_rtc 20cc000.snvs:snvs-rtc-lp: rtc core: registered 20cc000.snvs:snvs-r as rtc0
[ 1.908098] i2c /dev entries driver
[ 1.912610] IR NEC protocol handler initialized
[ 1.917297] IR RC5(x/sz) protocol handler initialized
[ 1.922388] IR RC6 protocol handler initialized
[ 1.927003] IR JVC protocol handler initialized
[ 1.931571] IR Sony protocol handler initialized
[ 1.936266] IR SANYO protocol handler initialized
[ 1.941004] IR Sharp protocol handler initialized
[ 1.945785] IR MCE Keyboard/mouse protocol handler initialized
[ 1.951651] IR XMP protocol handler initialized
[ 1.959127] pxp-v4l2 pxp_v4l2: initialized
[ 1.968249] imx2-wdt 20bc000.wdog: timeout 60 sec (nowayout=0)
[ 1.975435] Bluetooth: HCI UART driver ver 2.3
[ 1.979945] Bluetooth: HCI UART protocol H4 registered
[ 1.985234] Bluetooth: HCI UART protocol BCSP registered
[ 1.990588] Bluetooth: HCI UART protocol ATH3K registered
[ 1.996307] usbcore: registered new interface driver bcm203x
[ 2.002200] usbcore: registered new interface driver btusb
[ 2.007991] usbcore: registered new interface driver ath3k
[ 2.015776] sdhci: Secure Digital Host Controller Interface driver
[ 2.022014] sdhci: Copyright(c) Pierre Ossman
[ 2.026517] sdhci-pltfm: SDHCI platform and OF driver helper
[ 2.034572] sdhci-esdhc-imx 2190000.usdhc: could not get ultra high speed state, work on normal mode
[ 2.103704] mmc0: SDHCI controller on 2190000.usdhc [2190000.usdhc] using ADMA
[ 2.125689] random: fast init done
[ 2.139740] usbcore: registered new interface driver usbhid
[ 2.145729] usbhid: USB HID core driver
[ 2.152039] 2198000.adc supply vref not found, using dummy regulator
[ 2.185147] NET: Registered protocol family 26
[ 2.191285] NET: Registered protocol family 10
[ 2.208969] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[ 2.219763] NET: Registered protocol family 17
[ 2.224589] usb 1-1: new high-speed USB device number 2 using ci_hdrc
[ 2.231569] can: controller area network core (rev 20120528 abi 9)
[ 2.238791] NET: Registered protocol family 29
[ 2.244536] can: raw protocol (rev 20120528)
[ 2.250071] can: broadcast manager protocol (rev 20161123 t)
[ 2.255919] can: netlink gateway (rev 20130117) max_hops=1
[ 2.262083] Bluetooth: RFCOMM TTY layer initialized
[ 2.267194] Bluetooth: RFCOMM socket layer initialized
[ 2.272418] Bluetooth: RFCOMM ver 1.11
[ 2.276394] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[ 2.281750] Bluetooth: BNEP filters: protocol multicast
[ 2.289272] Bluetooth: BNEP socket layer initialized
[ 2.294556] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[ 2.300543] Bluetooth: HIDP socket layer initialized
[ 2.305756] 8021q: 802.1Q VLAN Support v1.8
[ 2.310106] Key type dns_resolver registered
[ 2.324731] cpu cpu0: Registered imx6q-cpufreq
[ 2.393531] imx_thermal 2000000.aips-bus:tempmon: Industrial CPU temperature grade - max:105C critical:100C passive:95C
[ 2.405405] ubi0: default fastmap pool size: 80
[ 2.410234] ubi0: default fastmap WL pool size: 40
[ 2.417433] ubi0: attaching mtd4
[ 2.425315] hub 1-1:1.0: USB hub found
[ 2.430312] hub 1-1:1.0: 4 ports detected
[ 2.753680] usb 1-1.2: new high-speed USB device number 3 using ci_hdrc
[ 4.423456] random: crng init done
[ 4.522157] ubi0: scanning is finished
[ 4.545907] ubi0: attached mtd4 (name "ubi", size 211 MiB)
[ 4.551444] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[ 4.558473] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[ 4.565337] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[ 4.572325] ubi0: good PEBs: 1684, bad PEBs: 4, corrupted PEBs: 0
[ 4.578499] ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
[ 4.585789] ubi0: max/mean erase counter: 4/1, WL threshold: 4096, image sequence number: 1479956245
[ 4.595163] ubi0: available PEBs: 0, total reserved PEBs: 1684, PEBs reserved for bad PEB handling: 36
[ 4.604582] ubi0: background thread "ubi_bgt0d" started, PID 97
[ 4.622703] mtd: device 5 (rootfs) set to be root filesystem
[ 4.653811] block ubiblock0_0: created from ubi0:0(rootfs)
[ 4.659414] snvs_rtc 20cc000.snvs:snvs-rtc-lp: setting system clock to 1970-01-01 00:00:02 UTC (2)
[ 4.669251] ALSA device list:
[ 4.672253] No soundcards found.
[ 4.684842] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[ 4.694458] Freeing unused kernel memory: 1024K
[ 5.952310] init: Console is alive
[ 5.956426] init: - watchdog -
[ 6.884666] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[ 6.968703] gpio_button_hotplug: loading out-of-tree module taints kernel.
[ 6.980827] ehci-platform: EHCI generic platform driver
[ 6.991481] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[ 7.009594] init: - preinit -
[ 8.743994] SMSC LAN8710/LAN8720 20b4000.ethernet-1:00: attached PHY driver [SMSC LAN8710/LAN8720] (mii_bus:phy_addr=20b4000.ethernet-1:00, irq=-1)
[ 8.757727] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 12.236463] mount_root: loading kmods from internal overlay
[ 12.290281] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[ 12.303139] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[ 12.480005] blk_update_request: I/O error, dev mtdblock0, sector 0
[ 12.491117] blk_update_request: I/O error, dev mtdblock0, sector 0
[ 12.497334] Buffer I/O error on dev mtdblock0, logical block 0, async page read
[ 12.639636] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 146
[ 12.724932] UBIFS (ubi0:1): recovery needed
[ 13.110324] UBIFS (ubi0:1): recovery completed
[ 13.115110] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[ 13.123440] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[ 13.133557] UBIFS (ubi0:1): FS size: 163672064 bytes (156 MiB, 1289 LEBs), journal size 8253440 bytes (7 MiB, 65 LEBs)
[ 13.144329] UBIFS (ubi0:1): reserved for root: 4952683 bytes (4836 KiB)
[ 13.150970] UBIFS (ubi0:1): media format: w4/r0 (latest is w4/r0), UUID 190733BA-FF82-493C-B732-332B384253C4, small LPT model
[ 13.164384] UBIFS (ubi0:1): full atime support is enabled.
[ 13.170220] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[ 13.186836] block: extroot: not configured
[ 13.226008] UBIFS (ubi0:1): un-mount UBI device 0
[ 13.230780] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" stops
[ 13.249707] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 147
[ 13.418793] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[ 13.426759] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[ 13.436757] UBIFS (ubi0:1): FS size: 163672064 bytes (156 MiB, 1289 LEBs), journal size 8253440 bytes (7 MiB, 65 LEBs)
[ 13.447513] UBIFS (ubi0:1): reserved for root: 4952683 bytes (4836 KiB)
[ 13.454188] UBIFS (ubi0:1): media format: w4/r0 (latest is w4/r0), UUID 190733BA-FF82-493C-B732-332B384253C4, small LPT model
[ 13.468865] UBIFS (ubi0:1): full atime support is enabled.
[ 13.491164] blk_update_request: I/O error, dev mtdblock0, sector 0
[ 13.502288] blk_update_request: I/O error, dev mtdblock0, sector 0
[ 13.508506] Buffer I/O error on dev mtdblock0, logical block 0, async page read
[ 13.610149] ubi0 error: ubi_open_volume.part.0: cannot open device 0, volume 1, error -16
[ 13.638225] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[ 13.654566] block: extroot: not configured
[ 13.688114] mount_root: switching to ubifs overlay
[ 13.750669] urandom-seed: Seeding with /etc/urandom.seed
[ 13.917238] procd: - early -
[ 13.920346] procd: - watchdog -
[ 15.069737] procd: - watchdog -
[ 15.073401] procd: - ubus -
[ 15.328278] procd: - init -

**Comment by BKPepe** [comment]
This repository contains community maintained packages for OpenWrt. If you have questions about OpenWrt file system, they should be asked on [OpenWrt forum](https://forum.openwrt.org/).
