### ISSUE TITLE
mwan3: what is the dependency on luci-app-firewall for?

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#11458]
Maintainer: @feckert 
Environment: N/A
Description:

There seems to be a dependency on luci-app-firewall by luci-app-mwan3.  Why is the latter dependent on the former?  What if one want mwan3 but not firewall?  Every unwanted package uses up very valuable space in the firmware.

**Comment by brianjmurrell** [comment]
Looking further, this one seems a real shame since mwan3 doesn't actually depend on firewall.  It's just the Luci layer that is causing the unnecessary dependency.

**Comment by feckert** [comment]
I think that make no sense to use mwan3 without luci-app-firewall.

**Comment by brianjmurrell** [comment]
Can you expand on why you think this?

**Comment by brianjmurrell** [comment]
Fixed by openwrt/luci#3751.
