### ISSUE TITLE
KSMDB compiler error in 5.4 kernel！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#11478]
![image](https://user-images.githubusercontent.com/45259624/75645092-a3630900-5c7f-11ea-8d09-019feaa09a82.png)

**Comment by BKPepe** [comment]
Ping @Andy2244

**Comment by neheb** [comment]
Is fixed with latest version: https://github.com/cifsd-team/cifsd/commit/6f2da8438d37179ca82da9d506ff9a4e22e0578a

**Comment by neheb** [comment]
Latest master is fixed.
