### ISSUE TITLE
exfat-nofuse: Compilation failed on x86-64 kernel 5.4

### ISSUE THREAD

**Issue by DazzyWalkman** [openwrt/packages#11474]
Test compilation failed on current x86-64 snapshot with test kernel version 5.4 with error:
 > else if ((opts->errors == EXFAT_ERRORS_RO) && !(sb->s_flags & MS_RDONLY)) {
 >                                                               ^~~~~~~~~
>                                                                IS_RDONLY                                                            

A patch like this may be needed:
https://github.com/dorimanx/exfat-nofuse/issues/145
Would someone more experienced have a look?
Thanks.

**Comment by neheb** [comment]
Wonder if this package should be dropped.

Kernel 5.4 has an exfat driver in the staging directory.

**Comment by DazzyWalkman** [comment]
I think so.  It only depends on how difficult it would be to backport the exfat staging driver to older kernels for OpenWrt.

**Comment by neheb** [comment]
Next release is 5.4 only. So moot point.
