### ISSUE TITLE
Firmware compiled using master branch has network but can not be connected to the Internet!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#11488]
The K3 compiled with 19.07 branch and the soft routing firmware are normally connected to the Internet, but the master branch has network to the Internet，You must set up a fixed DNS or use another DNS resolution plug-in to work properly:
![M NNV%W%ZZYLLE13DCDR0E2](https://user-images.githubusercontent.com/45259624/75747303-800b8d00-5d57-11ea-9f43-d42ee44bf1c1.png)
![J3JHU)ZA}~W01O9C )B%GWB](https://user-images.githubusercontent.com/45259624/75747307-813cba00-5d57-11ea-862e-06e40c745f91.png)
![(V24DQ`H}DO`0EQTO{VW TA](https://user-images.githubusercontent.com/45259624/75747313-839f1400-5d57-11ea-963b-dd14fb99a180.png)

**Comment by BKPepe** [comment]
This is a repository for OpenWrt community maintained packages. You can ask for help on [OpenWrt forum](https://forum.openwrt.org/). Closing as invalid bug report.
