### ISSUE TITLE
adblock: consider not using rpz-passthru for kresd

### ISSUE THREAD

**Issue by lbschenkel** [openwrt/packages#11496]
Maintainer: @dibdot 
Environment: OpenWrt 18.06, 19.07, others

When `kresd` is configured to forward queries, a `rpz-passthru` rule used for whitelisting domains will result in `kresd` bypassing all other policies, including the forward (which is also a policy). In a network in which `kresd` is not able to perform the recursive queries itself and must use an upstream resolver, this results in all whitelisted domains being "broken" and failing lookup.

An alternative way would be to omit the blocking rule entirely for whitelisted domains, which is what is done for `dnsmasq`.

More background about this issue: https://gitlab.labs.nic.cz/knot/knot-resolver/issues/547

**Comment by dibdot** [comment]
Interesting corner case. In forthcoming adblock 4 I've exposed this option to LuCI:
![pass](https://user-images.githubusercontent.com/8061346/75819146-62abe280-5d9a-11ea-9a54-47d9727a25de.png)

To disable this in adblock 3.8.15 please edit line 159 in /usr/bin/adblock.sh and make the following change:

```
old:
adb_dnsallow="awk '{print \"\"\$0\" CNAME rpz-passthru.\\n*.\"\$0\" CNAME rpz-passthru.\"}'"

new:
adb_dnsallow=""
```
