### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by PavelSosin-320** [openwrt/packages#11556]
Please make sure that the issue subject starts with `<package-name>: `

SMB: can't open the folder from Windows 10

Also make sure that the package is maintained in this repository and not in base which should be submitted at https://bugs.openwrt.org or in the LuCI repository which should be submitted at https://github.com/openwrt/luci/issues.

Issues related to releases below 18.06 and forks are not supported or maintained and will be closed.

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

Description:

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by BKPepe** [comment]
Duplicate of https://github.com/openwrt/packages/issues/11557. Closing.
