### ISSUE TITLE
luci-proto-openconnect: user cert and key file naming error

### ISSUE THREAD

**Issue by DasTestament** [openwrt/packages#11584]
Maintainer: @nmav @jow- 
Environment: ramips, xiaomi r3g, 19.07.2

Description:
Steps to reproduce:
1. Create OpenConnect interface (if0)
2. Fill **User certificate** or **User key** or **CA certificate** field and save
3. Save and Apply
4. Go to **/etc/openconnect** and observe that related PEM file is named without **vpn-** before iface name:
```
ca-if0.pem
user-cert-if0.pem
user-key-if0.pem
```
but openconnect.sh requires PEM to be named with **vpn-** part like this:
```
ca-vpn-if0.pem
user-cert-vpn-if0.pem
user-key-vpn-if0.pem
```

**Comment by nmav** [comment]
Hi,
 Would you like to send a pull request to fix this?

**Comment by DasTestament** [comment]
@nmav Hello,

Sure, why not. Give me some time, I'm a bit busy atm.

**Comment by DasTestament** [comment]
@nmav I've provided a fix for this case in PR #3786

**Comment by nmav** [comment]
Addressed in luci.

**Comment by sunnyqeen** [comment]
@nmav @jow- 
Could you please merge it to 19.07 branch?
https://github.com/openwrt/luci/commit/adf0fb1879ffb6bd04984d257484fad0fba1d6a3
Thanks!
