### ISSUE TITLE
syncthing: "Unknown" version string

### ISSUE THREAD

**Issue by jefferyto** [openwrt/packages#11583]
Maintainer: @aparcar 
Environment: malta-be, qemu, 2020-03-11 snapshot

Description:
Installed syncthing (1.3.4-2) for testing - this is the output of `syncthing -version`:

```
syncthing unknown-dev "Fermium Flea" (go1.14 linux-mips) unknown@unknown 1970-01-01 00:00:00 UTC
```

**Comment by aparcar** [comment]
This is a real problem, it seem to stop devices from syncing... 
![image](https://user-images.githubusercontent.com/16000931/77377137-55897000-6d16-11ea-9573-b2af4cee6a79.png)

**Comment by aparcar** [comment]
@fantom-x Can you please have a look at this as well?

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/packages/pull/11653

**Comment by jefferyto** [comment]
Appears to be fixed, closing.
