### ISSUE TITLE
ddns-scripts: update IP via powerdns API

### ISSUE THREAD

**Issue by Syphdias** [openwrt/packages#11594]
Maintainer: apparently [none](https://github.com/openwrt/packages/blob/9d2d04211586659b8e0360117cf3af79281e3891/net/ddns-scripts/Makefile#L18)? (@neheb did the most recent commits it seems)
Environment: arm_cortex-a9_vfpv3, Linksys WRT1900ACv2, OpenWrt 19.07.1 r10911-c155900f66

This is basically a feature request or an offer to contribute some code, if the idea seems interesting.

I know you can use `nsupdate` with powerdns to update the RR but powerdns has a nice API that can also be used for that purpose. The call to update a RR is basically this one:
```
/usr/bin/curl -Ss -H "X-API-Key: $api_key" http://${pdns_server}:${port:-8081}/api/v1/servers/localhost/zones/${zone} -X PATCH --data '{"rrsets": [ {"name": "'${DOMAIN}'.", "type": "A", "ttl": 3600, "changetype": "REPLACE", "records": [ {"content": "'${LOCAL_IP}'", "disabled": false } ] } ] }'
```

Since it uses data and not just get parameters afaict it needs a custom script. I did this very quick and dirty by adding `"powerdns"	"update_powerdns.sh"` to the `/etc/services` and hardcoding the `curl` call. It's probably not hard to do this properly.

Is this something anyone is interested in?

**Comment by LecrisUT** [comment]
I am definitely interested in this, so I've wrote #16429. Are there any missing features? I am thinking something compatible with `PowerDNS-Admin` will also be useful if the API will eventually support a per-record ACL.
