### ISSUE TITLE
[libs/gnutls] Build error with NLS enabled

### ISSUE THREAD

**Issue by Wedmer** [openwrt/packages#1163]
I think "gettext-version" fixup should be used.
>Making all in po
make[5]: Entering directory `/media/dev/dev/openwrt/openwrt/build_dir/target-arm_cortex-a8+vfpv3_glibc-2.19_eabi/gnutls-3.4.0/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19
make[5]: *** [check-macro-version] Error 1

**Comment by nmav** [comment]
Should be solved now.
