### ISSUE TITLE
acme: Commits missing in 19.07 backport

### ISSUE THREAD

**Issue by scde** [openwrt/packages#11675]
Maintainer: @tohojo 
Environment: OpenWrt 19.07.2 r10947-65030d81f3

Description:
Hi, I am running 19.07.2 which should have the `2.8.5-1` version of `acme` but its missing two commits from the master branch which were made before the `2.8.5-1` release. You can compare [the 19.07 branch](https://github.com/openwrt/packages/commits/2c0a307eeb4b2c2f6aa34b54dc0bcac6037c185d/net/acme) and [the master branch](https://github.com/openwrt/packages/commits/ab6d05d366de9df7265523222c3614520de1bb7c/net/acme) and see commits c6b4d7f and 983cc99 are missing from the backport.

Thank you in advance, have a nice day and stay healthy =)

**Comment by tohojo** [comment]
Fixed in 9ba7b1799c2326d97157059f0888f33fc16f5721

**Comment by scde** [comment]
@tohojo Great, thanks.
