### ISSUE TITLE
sox: broken dependency: libffmpeg

### ISSUE THREAD

**Issue by drpo** [openwrt/packages#1167]
package name of `libffmpeg` now have VARIANT, `sox` should depend on `libffmpeg-full` or other variant, not just `libffmpeg`.

**Comment by thess** [comment]
Sox should work with any ffmpeg variant with audio codecs. Is there a specific problem you are seeing with builds or package installs?

**Comment by psycho-nico** [comment]
All libffmpeg-* variants provide a virtual libffmpeg package (PROVIDES= libffmpeg) inherited from Package/libffmpeg/Default.
