### ISSUE TITLE
wget/uclient issue, when using Basic Auth

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#11719]
- - [30/Mar/2020:19:32:17 +0200] "GET /file.php?mac=AA-BB-CC-DD-EE-FF HTTP/1.1" 401 681 "-" "uclient-fetch"
 - username [30/Mar/2020:19:32:17 +0200] "GET /file.php?mac=AA-BB-CC-DD-EE-FF HTTP/1.1" 200 227 "-" "uclient-fetch"

When using Basic Auth, wget/uclient-fetch first tries without credentials. This might trigger intrusion protection on the server. And is a waste of activity.

**Comment by neheb** [comment]
This should to go https://bugs.openwrt.org

uclient-fetch is not maintained here.
