### ISSUE TITLE
ntpclient: 'SIOCGSTAMP' undeclared with kernel 5.x

### ISSUE THREAD

**Issue by dl12345** [openwrt/packages#11767]
Platform: x86_64
Libc: glibc

```
ntpclient.c: In function 'get_packet_timestamp':
ntpclient.c:254:18: error: 'SIOCGSTAMP' undeclared (first use in this function); did you mean 'SIOCGARP'?
  254 |  if ( ioctl(usd, SIOCGSTAMP, &udp_arrival) < 0 ) {
      |                  ^~~~~~~~~~
      |                  SIOCGARP

```

The asm-generic/sockios.h header no longer defines SIOCGSTAMP. Instead it provides only SIOCGSTAMP_OLD.

The linux/sockios.h header now defines SIOCGSTAMP using either SIOCGSTAMP_OLD or SIOCGSTAMP_NEW. 

ntpclient.c needs to include <linux/sockios.h>

**Comment by neheb** [comment]
glibc you say. No wonder I couldn't reproduce on musl.
