### ISSUE TITLE
Hope for adblock and simple adblock

### ISSUE THREAD

**Issue by jkle112** [openwrt/packages#11762]
Used adblock and simple adblock in linksys wrt1900ac v1,but want to upgrade by myself ,and used  a mini PC to install openwrt x64,so hope adblock could add more Blocklist Sources in and simple adblock could add Backup Directory for Blocklist Sources data.
Thank you!

**Comment by dibdot** [comment]
It doesn't make sense to use both apps at the same time. Please ask in the forum if you miss features or blocklist sources etc.
