### ISSUE TITLE
python3-package.mk: typo

### ISSUE THREAD

**Issue by The-BB** [openwrt/packages#11790]
Maintainer: @commodo @jefferyto @cotequeiroz 
Environment: all
Description: typo

https://github.com/openwrt/packages/blob/master/lang/python/python3-package.mk#L129
```
PYTHON3_PKG_SETUP_GLOABL_ARGS ?=
```
```
PYTHON3_PKG_SETUP_GLOBAL_ARGS ?=
```

**Comment by commodo** [comment]
thanks for the find
will send PR now
