### ISSUE TITLE
compilation of my own package fails

### ISSUE THREAD

**Issue by RIMEH1** [openwrt/packages#1180]
I have a python script and I wrote my Makefile this my path for the Makefile  package/mypackage/Makefile
 and for my script I have other path /home/ri/Documents/src but I have this error en the compilation of my package 
KAM@KAM-PC:~/Bureau/opW$ make package/mypackage/compile V=99 |grep error
Makefile:34: *** Download/default is missing the FILE field..  Stop.
make[1]: *** [package/mypackage/compile] Error 2
make: *** [package/mypackage/compile] Error 2

And my Makefile I did:
include $(TOPDIR)/rules.mk

PKG_NAME:=mypackage
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_BUILD_DEPENDS:=python
PKG_SOURCE_URL:=file://$(TOPDIR)/../ri/Documents/src

include $(INCLUDE_DIR)/package.mk

define Package/mypackage
  SECTION:=net
  DEPENDS:= +python
  CATEGORY:=Network
  TITLE:=mypackage
  
endef
 
define Package/mypackage/description
package of my project 
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
    
endef

define Package/mypackage/install
	$(INSTALL_DIR) $(1)/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/mypackage $(1)/bin/
endef

$(eval $(call BuildPackage,mypackage,+python))

I need help please, 
thanks

**Comment by thess** [comment]
'/home/ri/Bureau/opW/src' obviously does not exist.

**Comment by RIMEH1** [comment]
@thess  you means that I should put my script in /opW 
opW it my folder openwrt

**Comment by thess** [comment]
You would be better served if you posted this request for help in the OpenWrt forums.
