### ISSUE TITLE
feature: docker-compose run in openwrt

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/packages#11855]
https://github.com/docker/compose/issues/7368

**Comment by peterwillcn** [comment]
https://github.com/openwrt/packages/pull/11363
https://github.com/openwrt/packages/pull/11364
https://github.com/openwrt/packages/pull/11365

**Comment by peterwillcn** [comment]
@ynezz  @jefferyto

**Comment by jmarcet** [comment]
Pinged!

I updated all the PR including all pending fixes.
