### ISSUE TITLE
<openssl-util> openssl s_client -connect 8.8.8.8:853 connect:errno=146

### ISSUE THREAD

**Issue by diegoph** [openwrt/packages#11949]
Maintainer: Eneas U de Queiroz
Environment: OpenWrt 19.07.2 r10947-65030d81f3 

Description:
Problem connecting to Google DNS via TLS

The error occurs when executing the following command: openssl s_client -connect 8.8.8.8:853

2013015684:error:02002092:system library:connect:reason(146):crypto/bio/b_sock2.c:110:
2013015684:error:2008A067:BIO routines:BIO_connect:connect error:crypto/bio/b_sock2.c:111:
connect:errno=146

Using the cloudflare DNS works perfectly.

**Comment by hnyman** [comment]
openssl is in the main repo, not here in the packages feed.

The correct place for possibl ebug reports is
https://bugs.openwrt.org
