### ISSUE TITLE
ruby module is missing deps

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1195]
build aborts with
Package ruby-psych is missing dependencies for the following libraries:
libyaml-0.so.2
make[3]: *** [/home/buildbot/slave-local/malta_le/build/bin/malta/packages/packages/ruby-psych_2.2.2-1_malta_mipsel.ipk] Error 1

**Comment by luizluca** [comment]
I'll take a look

**Comment by blogic** [comment]
i stumbled across this when building the package inside the SDK.

**Comment by luizluca** [comment]
I already identified the problem. libyaml is an optional dep for ruby. If not present, it uses a bundled one.
I'll use  +PACKAGE_libyaml:libyaml

**Comment by blogic** [comment]
please make it always use the external one in favour of the builtin one. the reason being that the resulting ipkg will always be the same and not depend on the content of the staging folder.
