### ISSUE TITLE
mwan3: Diagonistics page doesn't work with LuCI running through nginx

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/packages#11950]
Maintainer: @feckert 
Environment: 19.07.2 Linksys WRT3200ACM

Description:

I run LuCI through nginx/nginx-ssl and I get the nginx 504 gateway timeout error page served when using the diagnostics page as below.

![image](https://user-images.githubusercontent.com/8067792/80253867-01094580-8672-11ea-8a13-64cf44f8d9c3.png)

Not sure if this is a bug with LuCI or mwan3 though.

**Comment by lucize** [comment]
for me with latest in chrome, all is working (ipv4)

**Comment by jamesmacwhite** [comment]
@lucize Weird. Neither IPv4/IPv6 working for me, are you also running LuCI with nginx?

**Comment by lucize** [comment]
it seems that executing only ping for tracking ip will not show you the results, but also using ping the default gateway (or the same command twice) will give you all the results

**Comment by jamesmacwhite** [comment]
@lucize Indeed it does, clicking execute twice works. Potentially a bug then?

**Comment by dl12345** [comment]
I use luci with nginx on 19.07.2 and pinging the tracking ip works just fine for me even first time around

**Comment by jamesmacwhite** [comment]
@dl12345 Interesting. Not sure what could be different to cause that.

**Comment by peter-stadler** [comment]
Does it help setting `threads = 1` in `/etc/uwsgi/vassals/luci-webui.ini` (cf. #10134)?

**Comment by jamesmacwhite** [comment]
@peter-stadler Thanks for the suggestion. Setting threads to 1 and restarting nginx does seem to make the diagnostics page more reliable and behave normally.

**Comment by feckert** [comment]
@peter-stadler thanks for the help. Could we add this into the Wiki?
I think this is not only a luci-app-mwan3 problem.

**Comment by jamesmacwhite** [comment]
@feckert My apologies. I wasn't entirely sure if this was a mwan3 issue. I do remember having issues with other LuCI areas, mainly the firmware sys upgrade process, so I should have looked into the nginx more closely.

**Comment by peter-stadler** [comment]
I will make a PR until tomorrow …
