### ISSUE TITLE
snort is missing deps

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1196]
build aborts with 

Package snort-pgsql is missing dependencies for the following libraries:
liblzma.so.5
make[3]: *** [/home/buildbot/slave-local/malta_le/build/bin/malta/packages/packages/snort-pgsql_2.9.7.2-1_malta_mipsel.ipk] Error 1

this happens for all 3 variants
   ERROR: package/feeds/packages/snort failed to build (build variant: basic).
   ERROR: package/feeds/packages/snort failed to build (build variant: mysql).
   ERROR: package/feeds/packages/snort failed to build (build variant: pgsql).

**Comment by Wedmer** [comment]
There is workaround: https://github.com/openwrt/packages/issues/1182
I've just tested my fix, but I changed snort makefile to be one package with additional options without build variants (mysql,pgsql,lzma support are options for the one package).  
I'm working on version with each build variant has its own flag in menu to enable lzma support.
Also we can remove lzma support at all.
