### ISSUE TITLE
libmraa not building

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#11977]
Maintainer: @nxhack 
Environment: at least mips64: https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/libmraa/compile.txt

This seems like a node.js API discrepancy.

**Comment by neheb** [comment]
Related: https://github.com/eclipse/mraa/issues/969
https://github.com/swig/swig/issues/1520

I think we should disable building of swig. ping @jefferyto

**Comment by jefferyto** [comment]
I don't have a strong opinion on this, though swig/swig#1746 looks promising.
