### ISSUE TITLE
dovecot:  bad PKG_BUILD_DEPENDS line (libiconv vs libiconv-full)

### ISSUE THREAD

**Issue by dl12345** [openwrt/packages#11974]
dovecot has a build dependency on libiconv 

```
PKG_BUILD_DEPENDS:=libiconv
```

The package Makefile fails to check if the build is actually using libiconv-full instead, in which case the line should read

```
PKG_BUILD_DEPENDS:=libiconv-full
```
This error is present in both master and openwrt-19.07

**Comment by neheb** [comment]
Not correct. Look at include/nls.mk.
