### ISSUE TITLE
boost break on mips and maybe other architectures

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1197]
it seems that the package Makefile passes and compiler params. this leads to 

...failed updating 410 targets...
...skipped 342 targets...
...updated 11769 targets...
make[3]: *** [/home/buildbot/slave-local/malta_le/build/build_dir/target-mipsel_mips32_uClibc-0.9.33.2/boost_1_58_0/.built] Error 1

caused by lots of lines such as ->
 mipsel-openwrt-linux-gcc: error: unrecognized command line option '-m32'

**Comment by sbyx** [comment]
Just merged this earlier today: https://github.com/openwrt/packages/pull/1186
I think that should fix it.
