### ISSUE TITLE
ocserv fails to build due to missing headers

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1198]
build aborts with

sec-mod-auth.c:56:28: fatal error: gssapi/gssapi.h: No such file or directory
 # include <gssapi/gssapi.h>
                            ^
compilation terminated.

**Comment by sbyx** [comment]
Cannot reproduce this with current version.
https://github.com/openwrt/packages/commit/899724bd35ea190c81710e06d22dc30b7981416b
should fix this.

**Comment by blogic** [comment]
happens when building the feed inside the SDK using 1b3fcf7af32.

ocserv won't be in RC1 if the bug is not reproduced/fixed.

**Comment by sbyx** [comment]
hmm probably weird sdk-related failure since libgssapi is not in any active package feed. nevertheless i pushed: fa4365dd9b50a5bc032498d6f281daeefe02e49e so we can build RC1

@nmav hope that's okay with you

**Comment by nmav** [comment]
Indeed, I wouldn't expect that to happen. The solution looks fine to me (the library which provides gssapi should be called libkrb5 or so). Thanks.

**Comment by nmav** [comment]
Ok, it seems there is krb5 package, but I really doubt one would use Kerberos authentication for the VPN in an openwrt router. Let's leave it disabled by default unless someone asks for it.
