### ISSUE TITLE
Hope upgrade for mini PC

### ISSUE THREAD

**Issue by jkle112** [openwrt/packages#12000]
A mini PC used Intel CPU ,want to install openwrt x64.
Hope upgrade support big disk over 2GB.
Hope it is support wireless card:Intel ax200 /9260ac,and used WPA3.

Adblock will support more block rules like firefox extension:uBlock Origin,maybe I will add more in.
ClamAV will check all ports and all packets.
Need  a Intrusion-detection system and a Intrusion Prevention System，hope firewall will more powerful for security and privacy.

Thank you!

**Comment by diizzyy** [comment]
Closing, not an issue
