### ISSUE TITLE
compile classpath error,how to fix it ?

### ISSUE THREAD

**Issue by hyird** [openwrt/packages#12014]
checking for gmp.h... yes
checking jni_md.h support... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for mkdir... /bin/mkdir
checking for cp... /home/hyird/openwrt/staging_dir/host/bin/cp
checking for date... /bin/date
checking for find... /home/hyird/openwrt/staging_dir/host/bin/find
checking for zip... /home/hyird/openwrt/staging_dir/host/bin/zip
checking for a jar-like tool... trying fastjar, gjar and jar
checking for fastjar... /usr/bin/fastjar
checking whether to regenerate parsers with jay... no
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in include/config-int.h (assuming C99 compatible system)
checking for cacao... no
checking for jamvm... jamvm
checking for ecj... ecj -warn:-deprecation,serial,unusedImport
checking if ecj -warn:-deprecation,serial,unusedImport is a version of gcj... no
checking if ecj -warn:-deprecation,serial,unusedImport works... yes
checking for uudecode... yes
checking if uudecode can decode base 64 file... yes
checking if jamvm works... configure: error: The Java VM jamvm failed (see config.log, check the CLASSPATH?)
make[2]: *** [/home/hyird/openwrt/build_dir/target-x86_64_musl/classpath-0.99/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory `/home/hyird/openwrt/feeds/packages/libs/classpath'
time: package/feeds/packages/classpath/compile#2.58#1.68#8.01
make[1]: *** [package/feeds/packages/classpath/compile] Error 2
make[1]: Leaving directory `/home/hyird/openwrt'
make: *** [package/classpath/compile] Error 2

**Comment by hyird** [comment]
checking if jamvm works... configure: error: The Java VM jamvm failed (see config.log, check the CLASSPATH?)

**Comment by neheb** [comment]
This was removed in master.
