### ISSUE TITLE
avrdude error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#1206]
install -m0600 /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-install/etc/avrdude.conf /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-x86/avrdude/etc/
install -d -m0755 /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-x86/avrdude/usr/bin
install -m0755 /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-install/usr/bin/avrdude /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-x86/avrdude/usr/bin/
find /home/main/64/build_dir/target-i386_i486_uClibc-0.9.33.2/avrdude-6.1/ipkg-x86/avrdude -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package avrdude is missing dependencies for the following libraries:
libelf.so.1
make[2]: *** [/home/main/64/bin/x86/packages/packages/avrdude_6.1-1_x86.ipk] Error 1
make[2]: Leaving directory `/home/main/64/feeds/packages/utils/avrdude'
make[1]: *** [package/feeds/packages/avrdude/compile] Error 2
make[1]: Leaving directory `/home/main/64'
make: *** [package/avrdude/compile] Error 2
main@bogon:~/64$

**Comment by thess** [comment]
Fixed by 2bdf5147ccc6a771eeb8081916761f1741831a32
