### ISSUE TITLE
Compile linux-eoip for openwrt

### ISSUE THREAD

**Issue by deivisonmoraes** [openwrt/packages#1208]
I have a problem to compile the package that I created. I used the makefile described in "https://github.com/agustim/openwrt-linux-eoip". Worked to build part in the final part I have problems.

Below is the error that occurs:

https://gist.github.com/deivisonmoraes/aaeff62bd84bc017b8d3

**Comment by thess** [comment]
Not really a problem with a package in this repo. You should report this problem to the maintainer (@agustim) for a permanent fix.

However, that being said, you need only add

PKG_USE_MIPS16:=0

to the **Makefile** to solve this issue.
