### ISSUE TITLE
Where is luci-i18n-french

### ISSUE THREAD

**Issue by magatst** [openwrt/packages#12117]
Manually install package

The package luci-i18n-french is not available in any configured repository.

**Comment by castillofrancodamian** [comment]
To install a translation you have to follow this format `luci-i18n-base-fr`, `luci-i18n-ddns-fr`, `luci-i18n-firewall`, etc.

**Comment by neheb** [comment]
If this is still an issue, it belongs here: https://github.com/openwrt/luci/issues
