### ISSUE TITLE
ffmpeg needs wmv1 wmv2 decoders or else it will fail to link avcodec after new mips patch

### ISSUE THREAD

**Issue by jazzrz86** [openwrt/packages#12156]
minidlna for example will fail to configure libavcodec.so.58: undefined reference to `ff_wmv2dsp_init_mips'

this is due to mips patches that enabled the additional optimisations however, ffmpeg makefiles dont add the required functions for wmv2 after selecting vc1.

the dirty hack is to enable wmv2 (i also enabled wmv1 just incase):
```
@@ -138,6 +140,8 @@ FFMPEG_PATENTED_MINI_DECODERS:= \
 	h264 \
 	hevc \
 	vc1 \
+	wmv1 \
+	wmv2
```

**Comment by neheb** [comment]
A user privately contacted me with a similar issue. Turns out he was using glibc where it was failing.
