### ISSUE TITLE
[qemu] : package does not compile with --disable-ivp6

### ISSUE THREAD

**Issue by anonymous-one** [openwrt/packages#12194]
The qemu package refuses to compile when ipv6 is disable because the qemu configure script does not recognize --disable-ipv6.

--disable-ipv6 needs to be added to the filter in the /packages Makefile for qemu, after that it compiles out just fine.

**Comment by neheb** [comment]
ping @yousong

**Comment by yousong** [comment]
Thanks for the report.  The issue should now be fixed in master and openwrt-19.07 branch.
