### ISSUE TITLE
choova-chilli - missing parameters

### ISSUE THREAD

**Issue by obsy** [openwrt/packages#1221]
Coova-chilli's config defines option dhcpif. This parameter does not exists, because init script  parses option network, not dhcpif.

**Comment by teslamint** [comment]
option network just converts interface name(e.g. wan, lan) to interface name(ethx.x) and assigns to option dhcpif afaik.

**Comment by obsy** [comment]
In coova-chilli config, but not in /etc/config/chilli

**Comment by teslamint** [comment]
Well, if i set network option with bridge network interface(e.g: br-wifi) with multiple devices(wlanX.X), I got this:
```
Mon May 18 13:34:58 2015 local6.err coova-chilli[13843]: net.c: 80: 19 (No such device) ioctl(SIOCSIFFLAGS) failed on
Mon May 18 13:34:58 2015 local6.err coova-chilli[13843]: net.c: 57: 19 (No such device) ioctl(SIOCSIFFLAGS) failed
Mon May 18 13:34:58 2015 local6.err coova-chilli[13843]: net.c: 120: 19 (No such device) ioctl(SIOCSIFADDR) failed
Mon May 18 13:34:58 2015 local6.err coova-chilli[13843]: net.c: 1291: 19 (No such device) ioctl(d=5, request=35111) failed
Mon May 18 13:34:58 2015 local6.err coova-chilli[13843]: chilli.c: 7339: Failed to create dhcp listener on
```
so I think it's better use dhcpif option than network option in that case.

**Comment by obsy** [comment]
Strange, the script gets the physical interface from  network option. In coova config exists only dhpif.

**Comment by teslamint** [comment]
It would be OK if we use single physical interface(e.g. eth1.0, wlan0.1, etc.) on network option.
