### ISSUE TITLE
Python 3.8+ update

### ISSUE THREAD

**Issue by Mikami382** [openwrt/packages#12266]
Hey there! When would there be a update to Python 3.8+?

**Comment by neheb** [comment]
For 19.07?

**Comment by Mikami382** [comment]
Yes, OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.057.55219-13dd17f to be precise.

**Comment by neheb** [comment]
I don't think there is such a plan. ping @jefferyto

**Comment by jefferyto** [comment]
That's right - as a stable release, 19.07 will receive bug and security fixes only. Updating past 3.7 would be too big a jump.

@neheb Is there a page on the wiki that describes the support/release policy for releases? I don't remember seeing a page like that but it may help to have one.

**Comment by neheb** [comment]
I don’t think there’s an explicit policy. I think the goal is to have something like Debian or Ubuntu where a release stays with old packages that only get bug fixes.

**Comment by jefferyto** [comment]
I think whether the policy is strict or flexible can be discussed and decided by project members/contributors/etc., but I also think having something written down is good so that everyone (developers and users) know what to expect.

**Comment by neheb** [comment]
I personally would like to see the packages feed transition to rolling release, but that's beyond the scope of this Issue.

Bottom line: Python 3.8 will not be coming to 19.07.
