### ISSUE TITLE
luci-app-openvpn templates not showing in drop-down menu

### ISSUE THREAD

**Issue by firewire10000** [openwrt/packages#12276]
I have compiled OpenWrt v19.07.3 from GitHub and I have included luci-app-openvpn. On the web-GUI under `VPN > OpenVPN` the `Select template ...` box doesn't have anything listed in it. However, if I look under `/etc/config` I can see a file called `openvpn_recipes` that contains these templates. 

If I go to `System > Software` on the web-GUI, select the `Installed` tab and type `luci-app-openvpn` into the filter box, apparently it is not installed yet somehow I can reach the LuCI page for it as mentioned above.

**Comment by neheb** [comment]
Sounds like this belongs here: https://github.com/openwrt/luci/issues
