### ISSUE TITLE
YouTube Ads still paying but after ads video won't load for me

### ISSUE THREAD

**Issue by RajPatel0929** [openwrt/packages#12308]
`Adblock ` 

Maintainer: @dibdot 

Environment: 
```
Hostname	OpenWrt
Model	Linksys WRT3200ACM
Architecture	ARMv7 Processor rev 1 (v7l)
Firmware Version	OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.136.49537-fb2f363
Kernel Version	4.14.180

Status / Version	enabled / 4.0.5
Active Sources		adaway, adguard, bitcoin, disconnect, youtube, yoyo
```
Added a Blocklist Sources (packages/net/adblock/files/)
Installed youtube (M, youtube), Save & Apply then to be safe even rebooted router 

Description:
Youtube ad's still playing after ad's video won't play... only videos that are playing that does not start with ads, If video start with ads then won't play but it will play full ads and then just stay black screens.

**Comment by dibdot** [comment]
That's a known fact - you can't block youtube reliable via dns. Just install additional browser plugins which can block on element level.
