### ISSUE TITLE
uci fails to handle long values properly

### ISSUE THREAD

**Issue by sarumpaet** [openwrt/packages#1231]
uci does not seem to handle values longer than 4096 bytes properly. It fails to throw an error message on "uci set"; it puts the value into /tmp/.uci but does not show it in "uci changes"; it hangs on "uci revert".
```
# uci set test.test.test="$(head -c 4100 < /dev/zero|tr '\0' 'a')"
# uci changes
# uci revert test
(hangs)
```

**Comment by yousong** [comment]
UCI is part of the OpenWrt base packages, not in this packages feeds.  And a patch series was just posted in openwrt-devel [1].

[1] https://lists.openwrt.org/pipermail/openwrt-devel/2015-May/033230.html
