### ISSUE TITLE
[ddns-scripts] Make filtering of private IPs optiona

### ISSUE THREAD

**Issue by johnpatcher** [openwrt/packages#1233]
In its current form ddns-scripts considers private IPs to be invalid. This check is performed at [here](https://github.com/openwrt/packages/blob/master/net/ddns-scripts/files/dynamic_dns_functions.sh#L781). While this probably makes sense in most setups, this should be something that can be configured.

**Comment by chris5560** [comment]
Hi Karol,
you can disable Private IP filtering by config setting.
please have a look here: http://wiki.openwrt.org/doc/uci/ddns#section_ddns
Is this what you are looking for ?
Christian

**Comment by johnpatcher** [comment]
Yes, I must have missed this. Thanks for the support and sorry for the noise!
