### ISSUE TITLE
zmq missing dependency (buildbot)

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#1236]
```
Package libzmq is missing dependencies for the following libraries:
libsodium.so.13
```

reported by buildbot:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/zmq/compile.txt

**Comment by hnyman** [comment]
Mentioned also in https://github.com/openwrt/packages/pull/1199#issuecomment-97366978 , but so far no action from the maintainer.
@srdgame

**Comment by srdgame** [comment]
@hnyman Will fix it soon.

**Comment by srdgame** [comment]
The fixed has been merged already, is there anybody could help update this issue?

**Comment by thess** [comment]
I think I have a better solution for this issue
See pull-request #1257 
This issue can be closed if it is accepted.
