### ISSUE TITLE
[Request] add easylist FR list to default package

### ISSUE THREAD

**Issue by OhSoGood** [openwrt/packages#12366]
Hi

I have been manually adding since several versions the French version of Easylist, similar to all existing ones in openwrt's adblock:

> config source 'reg_fr'
> 	option enabled '1'
> 	option adb_src 'https://easylist-downloads.adblockplus.org/liste_fr.txt'
> 	option adb_src_rset 'BEGIN{FS=\"[|^]\"}\$0~/^\|\|([[:alnum:]_-]+\.){1,}[[:alpha:]]+\^("\\\$third-party")?$/{print tolower(\$3)}'
> 	option adb_src_desc 'focus on French ads plus generic easylist additions'
> 

With the latest version of adblock, it's less easier to add them manually (/etc/config/adblock has changed). Nervertheless, could it be added to the default package ?

Thank you very much for your time and effort on adblock for openwrt !

**Comment by dibdot** [comment]
No problem, will be included with the next update

**Comment by dibdot** [comment]
Included in https://github.com/openwrt/packages/commit/ab44d8146af2abcfd96f08aba99358e960049bd3

**Comment by OhSoGood** [comment]
Thank you!
