### ISSUE TITLE
[perlbase-cpan] missing dependency module Test2::Util 

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#12394]
Maintainer: @Naoir | @pprindeville 
Environment: all arch | treewide

Description: `install` implies test 

trying to install some module terminates with

`Can't locate Test2/Util.pm in @INC (you may need to install the Test2::Util module)`

that module https://metacpan.org/pod/Test2 is absent from the OpenWrt repo and without it `cpan` is basically useless as it creates a catch22 - the module cannot be installed via `cpan` and without the module installation of modules fails.

**Comment by dl12345** [comment]
It is there. Can't remember exactly which package though. The only way I could get perl to work reliably was to install every single perl package in the repo. There are so many interdependencies...

**Comment by n8v8R** [comment]
There is *perlbase-test* in the repo but that does not cover it.

*Test2* source code seems to be located here https://github.com/Test-More/test-more/ and I ran a search on the OpenWrt code base for that string `https://github.com/Test-More/test-more` as expecting such showing for `PKG_SOURCE_URL`. But that search comes up empty

**Comment by dl12345** [comment]
@pprindeville might be able to throw some light on it

**Comment by dl12345** [comment]
So, looking at the code it's actually there in the build tree: it's called Test-Simple: https://metacpan.org/release/Test-Simple, and it contains both Test which you refer to above and Test2.

Test2 is actually being built, but the perl makefiles install Test but don't install Test2, which are both located in the same part of the build tree.

So the package Makefile would need to be modified to install it. Also perl also isn't compiled by default with the test option checked under Configuration, which is required for installation of Test

**Comment by pprindeville** [comment]
Sounds like most of the work is done.

Do you have a PR for me? :smirk:
