### ISSUE TITLE
unbound-control: wants libevent

### ISSUE THREAD

**Issue by kirelagin** [openwrt/packages#12445]
Maintainer: @hansmi @EricLuehrsen
Environment: OpenWrt 19.07.3

`unbound-control` depends on `unbound-daemon`, which is provided by two packages: `unbound-daemon` (light) and `unbound-daemon-heavy`. The latter depends on `libevent`, the former does not.

I installed `unbound-daemon` (light) and `unbound-control`. Here is what I am getting:

```text
# /usr/lib/unbound/odhcpd.sh
Error loading shared library libevent-2.1.so.7: No such file or directory (needed by /usr/sbin/unbound-control)
```

So, it looks like, the way `unbound-control` is built, it is taken from the “heavy” variant and keeps the dependency on `libevent`.

**Comment by EricLuehrsen** [comment]
Heavy and light ready to eat binary packages are just not working and it is inefficient for the build bots. I plan to change Unbound to a single "fair default" binary and provide `menuconfig` up-select and down-select options. I don't know I can change 19.07 without causing current users grief, but i can fix master and future release branches. Also: https://github.com/openwrt/packages/issues/12470
