### ISSUE TITLE
unbound: option domain is lost on "apply changes"

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [openwrt/packages#12444]
Maintainer: Eric Luehrsen ericluehrsen@gmail.com
Environment: Fritzbox 4040, OpenWRT 19.07.3

Description:
1. configure unbound in parallel mode
2. insert [relevant "domain" keyword](https://github.com/openwrt/packages/commit/b6caafef46829922dade557d6b3082360053bf8f) for custom domain in /etc/config/unbound
`option domain 'yourdomain'`
3. in the GUI make a minor change, say TTL from 120 to 121, and apply changes
4. verify that the keyword domain has disappeared from the config
5. again in the GUI make another minor chage, say TTL back to 120, and apply changes
6. verify that resolv.conf now has a "search lan." line instead of "search yourdomain."

Basically, after two restarts, the keyword is gone from resolv.conf
Issue first discussed in the [forum](https://forum.openwrt.org/t/unbound-option-domain-is-lost/64987/12?u=aboaboit)

**Comment by EricLuehrsen** [comment]
This is a LuCI page, tab, and work-flow apply issue. Please close this issue and copy it to openwrt/luci repository. I have not dug deeply into it yet. It might be simple or not. This issue in the right place will help receive the right help if I need it.

**Comment by AndreaBorgia-Abo** [comment]
Done, thank you.
