### ISSUE TITLE
minizip not compiling

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#12471]
Maintainer: @dwmw2 
Environment: master

https://downloads.openwrt.org/snapshots/faillogs/powerpc_8540/packages/minizip/compile.txt

**Comment by uxgood** [comment]
`Package minizip is missing dependencies for the following libraries:
libbsd.so.0
`

**Comment by dwmw2** [comment]
Hm, it automatically finds libbsd if it happens to be in the staging_dir when minizip is built. Is there a standard way to prevent that from happening by hiding `libbsd.pc` from CMake? Or do I need to patch the minizip `CMakeLists.txt` to allow libbsd to be explicitly disabled?

**Comment by neheb** [comment]
There might be some cmake variable that can be set to off.
