### ISSUE TITLE
keepalived: syntax error in keyword generation

### ISSUE THREAD

**Issue by pgaufillet** [openwrt/packages#12487]
Maintainer: @scrpi @feckert
Environment: ath79, Openwrt r13405-02f08056bc

Description: when generating /tmp/keepalived.conf, `enabled_script_security` is added instead of the expected `enable_script_security` causing the messages below at keepalived launch. 

```
Keepalived: (Line 6) Unknown keyword 'enabled_script_security'
[...]
Keepalived_vrrp: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
```

It can be easily solved by removing the extra 'd' line 102 of `/etc/init.d/keepalived`.

**Comment by feckert** [comment]
@pgaufillet Thanks for your report.
Fixed with commit https://github.com/openwrt/packages/commit/a8a1fbfa0da2676583f0289e7ed2806a3191800c
