### ISSUE TITLE
dawn still failing on arm64

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#12488]
Maintainer: @PolynomialDivision 
Environment: aarch64

https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a72/packages/dawn/compile.txt

This looks like a different error.

**Comment by PolynomialDivision** [comment]
Could u look at this @dwmw2 ? :)

**Comment by dwmw2** [comment]
Mea culpa; sorry.
```
src/utils/dawn_uci.c:44:46: error: field precision specifier '.*' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
         snprintf(hostname, HOST_NAME_MAX, "%.*s", len, ptr.o->v.string);
                                            ~~^~   ~~~
```
That `len` wants to be a `size_t` instead of an `int`. Either change the variable and deal with any other issues, or just cast it in the line that causes the complaint. Will be at keyboard in an hour or so if you don't beat me to it.

**Comment by PolynomialDivision** [comment]
> Mea culpa; sorry.
> 
> ```
> src/utils/dawn_uci.c:44:46: error: field precision specifier '.*' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
>          snprintf(hostname, HOST_NAME_MAX, "%.*s", len, ptr.o->v.string);
>                                             ~~^~   ~~~
> ```
> 
> That `len` wants to be a `size_t` instead of an `int`. Either change the variable and deal with any other issues, or just cast it in the line that causes the complaint. Will be at keyboard in an hour or so if you don't beat me to it.

Yeah casting seems fine. I will do it by myself. thanks for looking at it.
