### ISSUE TITLE
<dnsmasq 2.81-3> on latest snapshot WRT1900ACS SNAPSHOT r13546-4f38063640

### ISSUE THREAD

**Issue by pesa1234** [openwrt/packages#12493]
Dears,
I have an issue with latest dnsmasq, the resolv file is in /tmp/resolv.conf.d/resolv.conf.auto. On old was on /tmp/resolv.conf.auto.

With openvpn I have script to prevent dns leak I have tried to change on right location but doesn't work.
Set up the dnsmasq to old location /tmp/resolv.conf.auto and now all the up and down script working, but, when I flash new firmware and I try to reload backup the setting of resolv file is not restored must be set again.

I hope that I was clear, let me know if you need more info and sorry if I was not accurate on bug report.

Thanks

**Comment by neheb** [comment]
Both dnsmasq and OpenVPN are part of the base feed, not the packages feed.

Please report at https://bugs.openwrt.org
