### ISSUE TITLE
[issue template] remove Maintainer: @\<github-user> (find it by checking history of the package Makefile)

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#12491]
Description: With https://github.com/openwrt/openwrt/commit/9ba09653ade1fa20d0d777390d522fb179c1088e there is no use in retaining that line in the issue template that wastes the reporting party's time looking for the mainainer

**Comment by karlp** [comment]
That commit only removes maintainers from _targets_ (in the core repo).  Maintainers are still very much applicable for packages.

**Comment by n8v8R** [comment]
slipped by me, pardon

**Comment by karlp** [comment]
No problem :)
