### ISSUE TITLE
libusb-1.0: can't install on trunk

### ISSUE THREAD

**Issue by JamesT42** [openwrt/packages#1262]
I cant install libusb-1.0 on trunk:

root@OpenWrt:~# opkg install libusb-1.0
Installing libusb-1.0 (1.0.19-1) to root...
Downloading http://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/base/libusb-1.0_1.0.19-1_ramips_24kec.ipk.
Configuring libusb-1.0.
grep: /usr/lib/opkg/info/libusb-1.control: No such file or directory
cat: can't open '/usr/lib/opkg/info/libusb-1.list': No such file or directory

CHAOS CALMER (Bleeding Edge, r45683)
Platform: ramips/mt7620

**Comment by thess** [comment]
Neither this package nor the helper functions in /lib/functions.sh are maintained in this repo.

Submitted bug report in: https://dev.openwrt.org/ticket/19668

**Comment by JamesT42** [comment]
Hi! Ok thanks, I thougt this was something wrong with the package itself.

**Comment by KanjiMonster** [comment]
This has been fixed in OpenWrt with r45702, thanks for reporting.
