### ISSUE TITLE
python3-pip: obsolete? 

### ISSUE THREAD

**Issue by mabachel** [openwrt/packages#12706]
Maintainer: @commodo @jefferyto
Hey I just installed python3-pip on Openwrt master and I received this warning upon use.
```
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Can we upgrade the python3-pip package to 20.1.1?

**Comment by BKPepe** [comment]
Similar to https://github.com/openwrt/packages/issues/11747#issuecomment-608634335
