### ISSUE TITLE
libpng: compile fail

### ISSUE THREAD

**Issue by anomeome** [openwrt/packages#12725]
libpng 1.6.37 compile issue with master:

```
make[6]: Entering directory '/home/dev/wrtpac/source/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/libpng-1.6.37'
[  1%] Generating pnglibconf.out
/home/dev/wrtpac/source/staging_dir/host/bin/ccache: invalid option -- 'E'
Usage:
```

@neheb is this from the push ~yesterday?

**Comment by neheb** [comment]
Indeed. How did you get this builds failure?

**Comment by anomeome** [comment]
mvebu multiple targets (all the wrtpac devices). I cleaned up (dirclean) and removed all relevant directories, but error persists. I assume that is to be handed through to GCC?

**Comment by anomeome** [comment]
PR resolves, thanks much.
