### ISSUE TITLE
Upgrade dnscrypt-proxy2 to >= 2.0.43

### ISSUE THREAD

**Issue by makedir** [openwrt/packages#12832]
dnscrypt-proxy2 is still 2.0.42. Could someone please upgrade it to at least 2.0.43 or newer. There is some "bug" in 2.0.42, where it causes memory to fill up until all memory is being used and the router crashes:

https://forum.openwrt.org/t/davidc502-wrt1200ac-wrt1900acx-wrt3200acm-wrt32x-builds/15839/5334?u=mfka8

This behavior was mostly fixed with 2.0.43:

https://github.com/DNSCrypt/dnscrypt-proxy/issues/1352#issuecomment-641180610

**Comment by BKPepe** [comment]
As always, pull requests are welcome.
