### ISSUE TITLE
ocserv - prevent unauthorized access

### ISSUE THREAD

**Issue by Gustavo-FS** [openwrt/packages#12875]
Hi, everyone 

I configure with sucess ocserv in my openwrt router but i am concerned about unauthorized access attempts, how can i protect the VPN service to some guidance on settings or other services to prevent brute force or how to configure second authentication factor.

**Comment by nmav** [comment]
There are several recipes that apply to openwrt as well at:
https://ocserv.gitlab.io/www/recipes.html

You can also check the manual for all the available settings:
https://ocserv.gitlab.io/www/manual.html

I'm closing this as this is not an issue of ocserv in openwrt.
