### ISSUE TITLE
aria2: verion 1.34.0-6 is very outdated

### ISSUE THREAD

**Issue by thesuperfatcat** [openwrt/packages#12887]
aria2 1.34.0-6 not supported the TLS 1.3

There are problems with various downloads because it doesn't support tls 1.3
Is it possible to update the opkg version to the latest (1.35.0)?

If it's a long process, how can I manually install the latest version?

Thank you so much!

**Comment by neheb** [comment]
Is this with 19.07?

**Comment by thesuperfatcat** [comment]
> 
> 
> Is this with 19.07?

![OpenWrt Project package aria2](https://user-images.githubusercontent.com/56415358/87996444-d573eb00-cafa-11ea-96c7-7fa7cbc904eb.png)

**Comment by neheb** [comment]
Pushed update. It should appear in the feeds tomorrow.
