### ISSUE TITLE
lxc: ERROR: Unable to fetch GPG key from keyserver

### ISSUE THREAD

**Issue by alex9434** [openwrt/packages#12905]
# Issue template (remove lines from top till here)

Maintainer: @ratkaj 
Environment: OpenWrt SNAPSHOT, r13902-5e86877f36 on arm64 (Raspberry Pi 4B, 4GB)

Description: unable to create lxc container
```
lxc-create -n test -t download
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: test: lxccontainer.c: create_run_template: 1626 Failed to create container from template
lxc-create: test: tools/lxc_create.c: main: 319 Failed to create container test
```
Dear @ratkaj , @cshoredaniel , @neheb , @xypron , @champtar , @antonlacon 
I suspect this might be more an issue with gnupg than lxc. I could not find the maintainer in the Makefile for gnupg and therefore have included the contributors. Apologies for the long distribution list!

Package gnupg seems to be unable to download keys from keyserver:
```
gpg -vvvv  --keyserver-options=debug  --keyserver "hkp://pool.sks-keyservers.net" --recv-keys "0xBAEFF88C22F6E216"
gpg: using character set `iso-8859-1'
gpg: directory `/root/.gnupg' created
gpg: can't open `/usr/share/gnupg/options.skel': No such file or directory
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 22F6E216 from hkp server pool.sks-keyservers.net
gpg: unable to execute program `/usr/lib/gnupg/gpgkeys_curl': No such file or directory
gpg: no handler for keyserver scheme `hkp'
gpg: keyserver receive failed: keyserver error
```

Just to make sure, this does not seem to be a network issue:
```
ping -c 3 pool.sks-keyservers.net
PING pool.sks-keyservers.net (192.146.137.141): 56 data bytes
64 bytes from 192.146.137.141: seq=0 ttl=50 time=185.379 ms
64 bytes from 192.146.137.141: seq=1 ttl=50 time=184.813 ms
64 bytes from 192.146.137.141: seq=2 ttl=50 time=184.804 ms

--- pool.sks-keyservers.net ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 184.804/184.998/185.379 ms
```
```
curl pool.sks-keyservers.net
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="OpenPGP Keyserver">

      <title>OpenPGP Keyserver</title>

[... lots of html...]
 </body>
</html>
```
Any idea how to fix this?

**Comment by xypron** [comment]
* Did you try installing the missing program /usr/lib/gnupg/gpgkeys_curl?
* hkp:// uses port 11371. Is this port allowed in your firewall?

You could download the key from https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbaeff88c22f6e216.

**Comment by alex9434** [comment]
Dear all,

I have solved the issue. gpgkeys_curl is included in Package/gnupg-utils, that is by default not included in gnupg and needs to be installed separately. It might make sense to include the depencence on gnupg-utils in the Makefile for lxc-create so that this can be installed automatically.

Thank you,
Alex
