### ISSUE TITLE
Error minidlNA is compiled with GCC10 under the master branch, gCC9 is compiled normally!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#12921]
![image](https://user-images.githubusercontent.com/45259624/88447607-a09fc500-ce67-11ea-8e37-b7d29e86a338.png)

**Comment by neheb** [comment]
https://github.com/wongsyrone/packages-1/commit/56d9bc75b4b7f4006c28417d066f46900016eb9a
https://github.com/wongsyrone/packages-1/commit/17ac8ab0bb7b77d87f9090d29860756477647764

**Comment by neheb** [comment]
Patch is merged.
