### ISSUE TITLE
shadowsocks-libev: Allow bind to local IPv4/v6 addresses

### ISSUE THREAD

**Issue by wyf88** [openwrt/packages#12931]
Maintainer: @yousong 
Environment: any

Description:

Dear developer, 

Is it possible to allow bind to both IPv4/v6 addresses? The configs are `local_ipv4_address` and `local_ipv6_address`. See also
https://github.com/shadowsocks/shadowsocks-libev/commit/4a42da641b6e0039497998614e84c94205939c24

Thanks a lot!

**Comment by yousong** [comment]
Hi @wyf88 , please consider giving #12945 a try and see if it works for you.

**Comment by yousong** [comment]
Merged both pull requests for shadowsocks-libev and luci-app-shadowsocks-libev.  Should appear in the downloads site in the following days.
