### ISSUE TITLE
Master branch libJPEG deleted after a lot of source packages need to rely on!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#12990]
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg', which does not exist
WARNING: Makefile 'package/feeds/packages/graphicsmagick/Makefile' has a build dependency on 'libjpeg', which does not exist

**Comment by Andy2244** [comment]
Its removed because of #11017 and #10090, basically the new "faster" libjpeg-turbo replaces libjpeg. The package also is a drop-in replacement since it has `PROVIDES:=libjpeg`.

So are your sure you have the latest feeds and installed the package?
`./scripts/feeds install -a`

**Comment by verofin** [comment]
Sorry to report the problem still exist in a fresh clone I just did
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg', which does not exist
WARNING: Makefile 'package/feeds/packages/graphicsmagick/Makefile' has a build dependency on 'libjpeg', which does not exist

**Comment by Andy2244** [comment]
When do you get those warnings, at the feeds update stage or later at the menuconfig or make?

**Comment by verofin** [comment]
Git clone -> then feeds update -> error

**Comment by verofin** [comment]
Hi Andy, I deleted the openWrt directory and cloned it afresh.
I ran the feed update -a command
Then I ran the feeds install -a command that gave me some warnings including the two mentioned.
At the end I run this same install command a second time and then only get the 2 warnings for libjpeg

**Comment by neheb** [comment]
I fixed the second. The first will remain for a while.

**Comment by verofin** [comment]
Great that seems to do the trick guys!! Both the warnings are resolved

Regards

**Comment by micmac1** [comment]
> I fixed the second. The first will remain for a while.

telephony repo fast. Already pushed update :)
