### ISSUE TITLE
unbound: awk: /tmp/resolv.conf.auto: No such file or directory

### ISSUE THREAD

**Issue by cwbsw** [openwrt/packages#13007]
Maintainer: @EricLuehrsen 
Environment: OpenWrt snapshot

Description:

```
bundle_resolv_conf_servers() {
  local resolvers=$( awk '/nameserver/ { print $2 }' /tmp/resolv.conf.auto )
  UB_LIST_ZONE_SERVERS="$UB_LIST_ZONE_SERVERS $resolvers"
}
```
`unbound.sh` need to be updated because `resolv.conf.auto` has been moved to `/tmp/resolv.conf.d/resolv.conf.auto`.

**Comment by ja-pa** [comment]
Related commit https://github.com/openwrt/openwrt/commit/cd48d8d3420dd4df03daaa548227ceb487ba7104

**Comment by EricLuehrsen** [comment]
You would think moving a key piece of infrastructure would receive a bit more spot light. As is classic OpenWrt culture, the documentation was not updated either https://openwrt.org/docs/guide-user/base-system/dhcp. :frowning_face:

**Comment by jow-** [comment]
> documentation was not updated either

Thanks for the heads-up. I modified the page accordingly.
