### ISSUE TITLE
Squid isnt working on x86 geode alix (chaos clamer RC1 15.05)

### ISSUE THREAD

**Issue by imyashvinder** [openwrt/packages#1301]
Here are the logs..............................................................
root@OpenWrt:/etc/config# squid -d4
2015/05/23 14:00:05| storeDirWriteCleanLogs: Starting...
2015/05/23 14:00:05| Finished. Wrote 0 entries.
2015/05/23 14:00:05| Took 0.00 seconds ( 0.00 entries/sec).
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cfmetadata.shm): (13) Permission denied

**Comment by taeasy** [comment]
add line "chmod 0777 /dev/shm"  to /etc/init.d/squid function start_service. it's will working

**Comment by imyashvinder** [comment]
Thanks
Its working now...
