### ISSUE TITLE
luci + cron integration

### ISSUE THREAD

**Issue by porjo** [openwrt/packages#1305]
I created a scheduled task via the Luci web interface, but found that it wasn't being run. I then realised that cron service had not been enabled!? It would be good if the schedule task page made it clear what the current state of cron is (enabled or disabled) to avoid confusion, or at the very least included a note telling the user to check the status of cron via the 'Startup' page.

LuCI Trunk (0.12+svn-r10530) OpenWrt Barrier Breaker 14.07

**Comment by hnyman** [comment]
> at the very least included a note telling the user to check the status of cron via the 'Startup' page.

The cron service init script only starts the service if there is a crontab file. If there was no file at boot time, the service is not started and any later crontab editing goes unnoticed.
I added a note to LuCI master with https://github.com/openwrt/luci/commit/1970c21e3bbd70adc991cf6baf153129a1356c9b
