### ISSUE TITLE
luci-web Chaos Calmer 15.05-rc1 no Wifi-AC (Archer C5 v1.2)

### ISSUE THREAD

**Issue by kaiomatico** [openwrt/packages#1309]
Hello everyone. On OpenWrt  14.07 stable on my TP-Link Archer C5 Hardware Version 1.2 I'm able to configure Wifi-AC via the luci-web. On 15.05 only Wifi-A/B/G/N is configurable. If I should provide any logs like if the hardware is not detected properly, just send me the command and I will send the logs.

**Comment by oneru** [comment]
@kaiomatico there is probably a driver for the ac card that isn't in the 15.05 image. In the C7, i had to install the ath10k drivers to get AC working.
