### ISSUE TITLE
squid is not autostarting on boot

### ISSUE THREAD

**Issue by imyashvinder** [openwrt/packages#1310]
I already did /etc/init.d/squid enable
but it doesnt start automatically during boot
I am on chaos clamer RC1 15.05

**Comment by kim0** [comment]
I think it's not starting at all! I try to run it manually and it crashes like so:

# squid -d1
2015/08/08 22:19:08| storeDirWriteCleanLogs: Starting...
2015/08/08 22:19:08|   Finished.  Wrote 0 entries.
2015/08/08 22:19:08|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (13) Permission denied

@lperkov is this bug tracked somewhere else ?

PS .. I'm still on rc2 .. maybe this got resolved in rc3 ?!
