### ISSUE TITLE
ddns-scripts  dinamic dns for sitelutions.com update URL changed

### ISSUE THREAD

**Issue by u4david** [openwrt/packages#13101]
Please change   the updater URL link for sitelutions.com ddns provider.

it changed from :
http://www.sitelutions.com

to:
https://dnsup.sitelutions.com

If left unchanged logs will report errors like :
ERROR : uclient-fetch Error: '8'
or
Failed to redirect to /dnsup?

ddns-scripts	2.7.8-13
Powered by LuCI openwrt-19.07 branch (git-20.136.49537-fb2f363) / OpenWrt 19.07.3 r11063-85e04e9f46

**Comment by neheb** [comment]
the currect URL is:

```
http://www.sitelutions.com/dnsup?user=[USERNAME]&pass=[PASSWORD]&id=[DOMAIN]&ip=[IP]
```

you're saying to change to

```
https://dnsup.sitelutions.com/dnsup?user=[USERNAME]&pass=[PASSWORD]&id=[DOMAIN]&ip=[IP]
```

?

**Comment by u4david** [comment]
Yes the domain is changed to this: https://dnsup.sitelutions.com/

Thx, David V.

**Comment by neheb** [comment]
So changing the line I quoted in /etc/ddns/services works?

**Comment by feckert** [comment]
I am working on a ddns-scripts rework.
Could we change this after I have merged my[ P/R](https://github.com/openwrt/packages/pull/13402)?

**Comment by u4david** [comment]
Right now i have work around by using "custom" provider and:

Https://dnsup.sitelutions.com/dnsup.........
Not sure what P/R is but this change is  not urgent.

**Comment by Ansuel** [comment]
@feckert can you do this change?

**Comment by feckert** [comment]
@Ansuel done
@u4david I have no account for this so please verify if this works for you.
