### ISSUE TITLE
Boost: please update to 1.74.0

### ISSUE THREAD

**Issue by wongsyrone** [openwrt/packages#13148]
Maintainer: @ClaymorePT

Description:

1.74.0 is released, please update the package.

**Comment by ClaymorePT** [comment]
@wongsyrone  I'm aware of this. Thanks anyway for the heads-up.

**Comment by neheb** [comment]
Curious what's so special about 1.74.

**Comment by ClaymorePT** [comment]
@neheb On a first look, 1.74 does not need current patch `003-beast-coroutines.patch` for beast. Fix is already included. The others are still needed and they will need to be re-created.

It also seems that the libraries which are being more actively maintained, have introduced updates to be build with C++20.

Then, there's a bunch of fixes and improvements for most libraries. Boost.ASIO seems to contain a bunch of important fixes according to their log.

I'll be providing an update when I can.

**Comment by wongsyrone** [comment]
002-outcome-assert.patch and 003-beast-coroutines.patch can be removed, BTW, I'm a heavy user of Boost.asio

**Comment by ClaymorePT** [comment]
@wongsyrone  Yep `002-outcome-assert.patch` is also not needed. In truth, it was never needed. I don't really remember why it was added in the first place, since it was only adding a comment.

**Comment by wongsyrone** [comment]
It's from https://www.boost.org/users/history/version_1_73_0.html, it removes an assertion as well.

**Comment by ClaymorePT** [comment]
@wongsyrone ah, yes, you're right. There's two of them. Well, with this update, I'm also adding support to build Boost with C++20.

**Comment by ClaymorePT** [comment]
@wongsyrone  @neheb 

-> https://github.com/openwrt/packages/pull/13160
