### ISSUE TITLE
libs/boost 1.74 patch failed.

### ISSUE THREAD

**Issue by kongfl888** [openwrt/packages#13167]
Helllo, thank you for update. @ClaymorePT @neheb 

Please have a look [libs/boost/patches](https://github.com/openwrt/packages/tree/master/libs/boost/patches).

If they are unneeded, can you remove them and patch for them. 

thank you.

**Comment by ClaymorePT** [comment]
@kongfl888 I Forgot to add the deletion to the commit....

**Comment by ClaymorePT** [comment]
@kongfl888 Here it is: https://github.com/openwrt/packages/pull/13168

**Comment by kongfl888** [comment]
thank you
