### ISSUE TITLE
LVM2: raid1: Required device-mapper target(s) not detected in your kernel.

### ISSUE THREAD

**Issue by Yamakasi** [openwrt/packages#13189]
I encountered the issue that if you want to make a LVM Type raid1 LV you get the following error:

`raid1: Required device-mapper target(s) not detected in your kernel.`

The following command is what I used:

`lvcreate --type raid1 --mirrors 0 -L 5G --nosync -n data vg-01`

I wanted to start a degraded raid1 set on one disk and add my other disk later, it doesn't complain about the kernel module not being available for `--type mirror` but that requires the second disk directly.

Or it is the only way to go mdadm + LVM instead of LVM with mdadm under the hood ?

**Comment by neheb** [comment]
maybe kmod-dm-raid actually.

**Comment by neheb** [comment]
Any update?

**Comment by Yamakasi** [comment]
> 
> 
> Any update?

No, not really. It seems that, what I want, Raid1 for Extroot, is not really possible because of the start-up-scripts

**Comment by neheb** [comment]
Is this with master or 19.07?

**Comment by Yamakasi** [comment]
> 
> 
> Is this with master or 19.07?

Yes on 19.07

**Comment by neheb** [comment]
Did you try installing kmod-dm-raid?

**Comment by Yamakasi** [comment]
> 
> 
> Did you try installing kmod-dm-raid?

Yes all is installed.

I now do it the traditional way...

**Comment by Livy-Inverse** [comment]
Same issue on OpenWrt 22.03.0 rc1. Installing 'kmod-dm-raid' fixes the problem. This issue should be closed.

**Comment by Hansb1987** [comment]
I had this issue for quiet some times, however I found the solution to it today
Solution: 
#dnf install -y device-mapper 
#dnf install -y kmod 
#reboot now

However it creates another where it disables nmcli and have zero connection to WIFI. 
![VDO solution](https://github.com/user-attachments/assets/bd78a002-630b-40a6-8840-9a91469e6e34)
