### ISSUE TITLE
vips again not build (error)

### ISSUE THREAD

**Issue by build000** [openwrt/packages#1323]
(...)
OpenWrt-libtool: link: mips-openwrt-linux-uclibc-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -fstack-protector -D_FORTIFY_SOURCE=2 -Wl,-z -Wl,now -Wl,-z -Wl,relro -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libiconv-full/include -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libintl-full/include -Wl,-rpath-link=/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -Wl,-rpath-link=/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -o .libs/vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/glib-2.0/include -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include/libxml2 -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include/libpng12 -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include/glib-2.0 -I/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -Wl,--export-dynamic -pthread  -L/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/projekty/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/projekty/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib -L/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libiconv-full/lib -L/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libintl-full/lib ../libvips/.libs/libvips.so -lpng12 -ljpeg -lgmodule-2.0 -lxml2 -lgobject-2.0 -lglib-2.0 -lintl -lexif -lm -pthread
/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libglib-2.0.so: warning: the use of OBSOLESCENT `utime' is discouraged, use `utimes'
/projekty/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: warning: libiconv.so.2, needed by /projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libgmodule-2.0.so, not found (try using -rpath or -rpath-link)
/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libglib-2.0.so: undefined reference to `libiconv'
/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libglib-2.0.so: undefined reference to `libiconv_close'
/projekty/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libglib-2.0.so: undefined reference to `libiconv_open'
collect2: error: ld returned 1 exit status
Makefile:585: recipe for target 'vips' failed
make[5]: *** [vips] Error 1
make[5]: Leaving directory '/projekty/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/vips-7.42.1/tools'
Makefile:629: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/projekty/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/vips-7.42.1'
Makefile:534: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/projekty/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/vips-7.42.1'
Makefile:82: recipe for target '/projekty/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/vips-7.42.1/.built' failed
make[2]: *** [/projekty/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/vips-7.42.1/.built] Error 2
make[2]: Leaving directory '/projekty/openwrt/trunk/feeds/packages/libs/vips'
package/Makefile:187: recipe for target 'package/feeds/packages/vips/compile' failed
make[1]: *** [package/feeds/packages/vips/compile] Error 2
make[1]: Leaving directory '/projekty/openwrt/trunk'
/projekty/openwrt/trunk/include/toplevel.mk:181: polecenia dla obiektu 'package/vips/compile' nie powiodły się
make: *** [package/vips/compile] Błąd 2
slawek@slawek-ubuntu:/projekty/openwrt/trunk$

**Comment by hnyman** [comment]
vips builds currently ok at buildbots.
