### ISSUE TITLE
'curl': feature request: add verbose mode to compile option.

### ISSUE THREAD

**Issue by rezad1393** [openwrt/packages#13244]
Maintainer: @kaloz 

Environment:
armv7 linksys1200ac 19.0.7

Description:
can you add verbose mode to curl compile option so that when the user runs curl with '-v' option on openwrt it outputs verbose info? 
like on desktop version.

I think this the option : CONFIG_LIBCURL_VERBOSE
is configuring to ignore the global option and using verbose mode add a lot of size to the created package?
if not can it be added so that it is more useful network tool instead of being like wget?

**Comment by neheb** [comment]
This is already supported if compiling your own builds. It will not be turned on by default for size reasons.
