### ISSUE TITLE
imagebuilder : “following packages conflict with busybox” 

### ISSUE THREAD

**Issue by sinancetinkaya** [openwrt/packages#13245]
Supply the following if possible:
- Device problem occurs on
unielec_u7621-06-16m

- Software versions of OpenWrt/LEDE release, packages, etc.
latest snapshots

- Steps to reproduce
```
sinan@sinan-VirtualBox:~$ make image PROFILE=unielec_u7621-06-16m PACKAGES="luci block-mount kmod-fs-ext4 wpad-mini nano htop kmod-mt76 kmod-mt76-core kmod-mt76x2 luci-app-sqm sqm-scripts kmod-usb-storage-uas kmod-usb3"
......................
......................
......................
Collected errors:
 * check_conflicts_for: The following packages conflict with busybox:
 * check_conflicts_for: 	busybox-selinux * 
 * opkg_install_cmd: Cannot install package busybox.
Makefile:154: recipe for target 'package_install' failed
make[2]: *** [package_install] Error 255
Makefile:112: recipe for target '_call_image' failed
make[1]: *** [_call_image] Error 2
Makefile:207: recipe for target 'image' failed
make: *** [image] Error 2
```

**Comment by coolermister** [comment]
+1
Reproduced it too, even when building from sources. If you add some package that provide the same tool which already included in busybox, for example ifenslave, ifup/ifdown, and so on, build says "trying to install smth, but that provided by package busybox".
I used to think that it's normal behaviour)

**Comment by sinancetinkaya** [comment]
Builds still have it. What's the root cause of this problem?

**Comment by dangowrt** [comment]
Apparently what happens is that `procd-selinux` is somehow preferred over `procd` as it `PROVIDES:=procd`.
Can you try building an ImageBuilder from source and try adding `PROVIDES:=procd` in package/system/procd/Makefile also to the procd package? Same for busybox I suppose.

**Comment by sinancetinkaya** [comment]
@dangowrt 

> try building an ImageBuilder from source
How? My linux knowledge is very limited.

**Comment by aparcar** [comment]
@sinancetinkaya I'll give it a test :)

**Comment by aparcar** [comment]
Have you tried other targets? I'm trying to reproduce it on x86/64 and I don't see a problem

**Comment by sinancetinkaya** [comment]
> Have you tried other targets? I'm trying to reproduce it on x86/64 and I don't see a problem

I wrote the build command I used in the first post. Can you try the exact command?

**Comment by neheb** [comment]
Closing as this belongs in https://bugs.openwrt.org
