### ISSUE TITLE
net/adblock 4.0.6 does not block domains in selected blocklists 

### ISSUE THREAD

**Issue by nikolajsheller** [openwrt/packages#13305]
Incorrect arguments are passed to BusyBox sort, causing downloaded blocklists to be lost, instead of sorted.

Tho problem starts here, in 'adblock.sh:433':
adb_srtopts="--temporary-directory=${adb_tmpdir} --compress-program=gzip --batch-size=32 --parallel=${cores}"

These options are passed to sort on e.g.: 'adblock.sh:1320", causing sort to fail and the resulting file of sorted domains to be empty:
sort ${adb_srtopts} -u "${src_tmpsort}" 2>/dev/null > "${src_tmpfile}"

The options seem to be correct for GNU coreutils sort, but not for BusyBox sort, which my OpenWRT is running.

The problem can be fixed by setting:
adb_srtopts="-T ${adb_tmpdir}"

**Comment by dibdot** [comment]
adblock package depends on coreutils-sort, cause busybox sort is much slower and doesn't support merge sorts  - bottomline fix your installation.

**Comment by nikolajsheller** [comment]
This is for anybody else seeing this or similar problems:
opkg reported 'coreutils-sort' as being installed, but 'sort' pointed to BusyBox sort.
Removing and reinstalling 'coreutils-sort' fixed 'sort' so it is now the expected coreutils sort, fixing the cause of this issue.
