### ISSUE TITLE
Continuous building

### ISSUE THREAD

**Issue by coolermister** [openwrt/packages#13322]
Guys, maintainers. If you interested in continuous building, for example for most common arch as x86 or atheros and so on, i can provide one of my own servers. For example it can be 2x opteron 6172 + 64 gb ram and ssd intel 1tb. If we always will automatically build master for example, we will see what have been gone wrong quicker

**Comment by neheb** [comment]
I would talk to @jow- about this. He doesn't really read his GitHub emails, so it's best to catch him on IRC.

Currently on https://downloads.openwrt.org , packages are rebuilt mostly every day. I have no idea what the underlying hardware is.

**Comment by hnyman** [comment]
Not really a packages issue.
Currently there is automatic CI PR (and in any case, the buildbot has always built packages continuously)
