### ISSUE TITLE
strongswan: 5.3.0 regression - ipsec won't start when build with CONFIG_USE_STRIP=y

### ISSUE THREAD

**Issue by damiankaczkowski** [openwrt/packages#1332]
Since 5.3.0 I got error like this when issuing `ipsec start`:

`/usr/lib/ipsec/starter: can't load library 'libstrongswan.so.0'`

Seems that strongswan doesn't search `/usr/lib/ipsec/` for libraries and this is the cause of an error.

I have been always using `CONFIG_USE_STRIP=y` with 5.0, 5.1, 5.2 and never came across this problem.

Could you please look into this?

**Comment by damian-kaczkowski** [comment]
Maybe related to this commit(?):
https://dev.openwrt.org/changeset/44377

**Comment by damian-kaczkowski** [comment]
I have opened a ticket on openwrt trac too:
https://dev.openwrt.org/ticket/19771

**Comment by diizzyy** [comment]
@stintel 
Ping

**Comment by stintel** [comment]
After reading the trac ticket, I conclude this isn't a problem in strongswan. Additionally, it works for me on LEDE master.
