### ISSUE TITLE
OpenWrt 19.07.3 r11063-85e04e9f46 - Archer C7 v2 - wlan0 and wlan1 fail to enable after sometime of running

### ISSUE THREAD

**Issue by isrizil** [openwrt/packages#13339]
Hello,
after I enabled the Wlan0 and Wlan1 interfaces it run for several hours and than get into cycle of -disable, enable, disable, enable

attached log from the system log

Thanks
using - OpenWrt 19.07.3 r11063-85e04e9f46

[openwrt_archer_c7_v2.txt](https://github.com/openwrt/packages/files/5187916/openwrt_archer_c7_v2.txt)

**Comment by BKPepe** [comment]
This repository contains community packages for OpenWrt. And thus it does not help you with wlan issues. Therefore to such issues, there is a [OpenWrt forum](https://forum.openwrt.org/), [OpenWrt bug tracker](https://openwrt.org/bugs).
