### ISSUE TITLE
net/nut: nut-server initscript does not treat underscores in override/default cfg options correctly (patch)

### ISSUE THREAD

**Issue by Schneehuhn** [openwrt/packages#13359]
[nut-server.init.txt](https://github.com/openwrt/packages/files/5205195/nut-server.init.txt)

When the nut-server initscript generates the config file for the driver from the nut_server uci configuration, override/default configuration options are not treated correctly. Underscores in the option name should be replaced by dots; this is not done.

nut_server uci config file: 

`config driver 'ups'`
`        option driver 'usbhid-ups'`
`        option port 'auto'`
`        list override input_transfer_low`

`config override 'override_input_transfer_low'`
`        option value 96`

generated ups.conf driver config file:
`driver = usbhid-ups`
`port = auto`
`override.input_transfer_low = 96`

Expected result:
`driver = usbhid-ups`
`port = auto`
`override.input.transfer.low = 96`

The attached patch fixes the issue.

**Comment by neheb** [comment]
Pushed to master.
