### ISSUE TITLE
Udev and eudev

### ISSUE THREAD

**Issue by predators46** [openwrt/packages#13408]
whether eudev is udev whose name was changed, and whether the function is the same as udev

**Comment by neheb** [comment]
currently, there is libudev-fbsd in here, which is mostly a stub library based on older udev. There's work on introducing a better one: https://github.com/openwrt/packages/issues/12844

In any case, udev or eudev will not be coming here.

**Comment by predators46** [comment]
> saat ini, ada libudev-fbsd di sini, yang sebagian besar merupakan pustaka rintisan berdasarkan udev lama. Ada upaya untuk memperkenalkan yang lebih baik: [# 12844](https://github.com/openwrt/packages/issues/12844)
> 
> Bagaimanapun, udev atau eudev tidak akan datang ke sini.

but I managed to make it in the master branch

**Comment by predators46** [comment]
> currently, there is libudev-fbsd in here, which is mostly a stub library based on older udev. There's work on introducing a better one: #12844
> 
> In any case, udev or eudev will not be coming here.

but I managed to make it in the master branch
