### ISSUE TITLE
BUG? select pogopro but dts compiled is series v3 which without pcie binding? 

### ISSUE THREAD

**Issue by youxiaojie** [openwrt/packages#13425]
I select pogo pro with pcie, but I see 
`openwrt/build_dir/target-arm_mpcore_musl_eabi/linux-oxnas_ox820/linux-5.4.65/arch/arm/boot/dts/ox820-cloudengines-pogoplug-series-3.dtb
`
where is no pcie binding in dts, is it a bug?

**Comment by neheb** [comment]
this belongs in https://bugs.openwrt.org
