### ISSUE TITLE
mdnsresponder is build in engineering mode

### ISSUE THREAD

**Issue by mehlis** [openwrt/packages#1342]
the package net/mdnsresponder is build as 
```
mDNSResponder (Engineering Build) (May 28 2015 14:44:28) starting
```

this is not what I expect as default mode for a package

**Comment by sbyx** [comment]
There is no real "Engineering Build" the text is just printed since the version number is for some reason not passed correctly during make. If it bothers you, feel free to track it down and do a pull-request.
