### ISSUE TITLE
ocserv: package contents of ocserv 1.1.1-1 is inconsistent/broken

### ISSUE THREAD

**Issue by aburdukov** [openwrt/packages#13465]
The ocserv package of OpenWrt 19.07 was updated recently (on Sep 22, 2020) from version 1.0.1 to version 1.1.1.

Since version 1.1.0 ocserv introduced ocserv-worker application (see changelog here: https://ocserv.gitlab.io/www/changelog.html).

The updated package does not include ocserv-worker application and as the result ocserv does not work anymore with the following error in the logs on attempt to connect a client:

Tue Sep 22 03:50:28 2020 daemon.err ocserv[7965]: main: main.c:1220: exec /usr/sbin/ocserv-worker failed No such file or directory
Tue Sep 22 03:50:28 2020 daemon.err ocserv[1401]: socket failed Protocol not supported

**Comment by nmav** [comment]
Thank you, I've updated the package to include it. Sorry for that.
