### ISSUE TITLE
zeromq is missing dependencies

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#1346]
find /home/buildbot/slave-local/adm5120_rb1xx/build/build_dir/target-mipsel_mips32_uClibc-0.9.33.2/zeromq-4.0.5/ipkg-adm5120_mipsel/libzmq -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libzmq is missing dependencies for the following libraries:
libsodium.so.13
make[2]: *** [/home/buildbot/slave-local/adm5120_rb1xx/build/bin/adm5120/packages/packages/libzmq_4.0.5-1_adm5120_mipsel.ipk] Error 1
make[2]: Leaving directory `/home/buildbot/slave-local/adm5120_rb1xx/build/feeds/packages/libs/zmq'
make[1]: *** [package/feeds/packages/zmq/compile] Error 2
make[1]: Leaving directory `/home/buildbot/slave-local/adm5120_rb1xx/build'
make: *** [package/zmq/compile] Error 2

**Comment by thess** [comment]
@blogic - I think you wanted to mention this was for-15.05 since it was fixed on the trunk a few weeks ago. I could submit a PR for the merge or you could just cherry-pick it straight away.

@srdgame - fyi
