### ISSUE TITLE
openconnect: pkgdata is inaccurate

### ISSUE THREAD

**Issue by dlenski** [openwrt/packages#13471]
Maintainer: @nmav
Environment: N/A

Description:

The description field show in the package data at https://openwrt.org/packages/pkgdata/openconnect is obsolete and doesn't fully reflect the supported protocols as of v8.09 (includes PAN GlobalProtect as well as truly native support for Pulse):

> A VPN client compatible with Cisco's AnyConnect SSL VPN, ocserv and Juniper (Pulse secure).\\ \\ OpenConnect is a client that follows the Cisco's AnyConnect SSL VPN protocol,\\ which is supported by IOS 12.4(9)T or later on Cisco SR500, 870, 880, 1800,\\ 2800, 3800, 7200 Series and Cisco 7301 Routers, as well as the OpenConnect\\ VPN server. It has later been ported to support the Juniper SSL VPN which\\ is now known as Pulse Connect Secure.\\ \\

This is causing some confusion among OpenConnect users on OpenWRT.

I would suggest adopting the updated description fields used by Debian packaging for recent versions of OpenConnect, from https://salsa.debian.org/mtmiller/openconnect/-/commit/d1d5b7cb8ffe9070f8ef37d670e96bbff14541b3:

> OpenConnect is an SSL VPN client initially created to support Cisco's
> AnyConnect SSL VPN. It has since been extended to support the Pulse Connect
> Secure VPN (formerly known as Juniper Network Connect or Junos Pulse) and
> the Palo Alto Networks GlobalProtect SSL VPN.
>
> A corresponding OpenConnect VPN server implementation can be found in the
> ocserv package.

**Comment by nmav** [comment]
Thank you. I've updated the description to reflect the status quo.
