### ISSUE TITLE
Unable to save contents: Unexpected reply data format

### ISSUE THREAD

**Issue by smalldickman** [openwrt/packages#13488]
In fact, the content has been successfully saved and can be used normally
![Capture](https://user-images.githubusercontent.com/31898637/94216023-e7b24100-ff10-11ea-91ed-c2371895f81f.JPG)
This problem has occurred since 5.4.66

**Comment by brackenhill-mob** [comment]
This occurs for me too when editing my custom Firewall rules.

Last working version for me is r14439 (but I don't update every snapshot so there might be a latter version that works)

**Comment by kongfl888** [comment]
The latest openwrt snapshot has fixed it. See https://github.com/openwrt/openwrt/commit/2a90d308c73f3f254e93fe3c55d4e40eaabc06e3
