### ISSUE TITLE
mwan3: It's seems to Bandwidth cannot be superimposed

### ISSUE THREAD

**Issue by logernLee** [openwrt/packages#13489]
Using MWAN3, I can see Interface Live Status is green,When I get the public IP, it also changes，but the bandwidth is not superimposed.could you tell me how can I set to suoerimpose the bandwidth.
fallow is my default set:
/etc/config/mwan3:
config member 'wan_m1_w3'
	option interface '4g'
	option metric '1'
	option weight '1'

config member 'wanb_m1_w2'
	option interface '4g2'
	option weight '1'
	option metric '1'

config interface '4g'
	option enabled '1'
	list track_ip '8.8.4.4'
	list track_ip '8.8.8.8'
	list track_ip '208.67.222.222'
	list track_ip '208.67.220.220'
	option family 'ipv4'
	option reliability '2'
	option count '1'
	option timeout '2'
	option failure_latency '1000'
	option recovery_latency '500'
	option failure_loss '20'
	option recovery_loss '5'
	option interval '5'
	option down '3'
	option up '8'

config interface '4g2'
	option enabled '1'
	list track_ip '8.8.4.4'
	list track_ip '8.8.8.8'
	list track_ip '208.67.222.222'
	list track_ip '208.67.220.220'
	option family 'ipv4'
	option reliability '1'
	option count '1'
	option timeout '2'
	option failure_latency '1000'
	option recovery_latency '500'
	option failure_loss '20'
	option recovery_loss '5'
	option interval '5'
	option down '3'
	option up '3'

config policy 'balanced'
	option last_resort 'default'
	list use_member 'wan_m1_w3'
	list use_member 'wanb_m1_w2'

config globals 'globals'
	option mmx_mask '0x3F00'
	option rtmon_interval '5'

config rule 'default_rule_v4'
	option dest_ip '0.0.0.0/0'
	option use_policy 'balanced'
	option family 'ipv4'
	option proto 'all'
	option sticky '0'

/etc/config/network
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd59:99b4:0332::/48'

config interface '4g'
	option metric '12'
	option proto 'dhcp'
	option ifname 'eth1'
	option dns '114.114.114.114'

config interface '4g2'
	option metric '13'
	option proto 'dhcp'
	option ifname 'eth2'
	option dns '114.114.114.114'

config interface 'lan'
	option force_link '1'
	option macaddr '8c:88:2b:00:07:16'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.8.1'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option ifname 'eth0'

config interface 'wan'
	option metric '10'
	option force_link '2'
	option macaddr '8c:88:2b:00:07:14'
	option proto 'dhcp'

config interface 'wan6'
	option proto 'dhcpv6'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '0'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '1 2 3 4 6t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option ports '0 6t'

config interface 'wwan'
	option metric '11'
	option proto 'dhcp'
	option ifname 'apcli0'

Looking forward to your reply, thank you.

**Comment by feckert** [comment]
Please contact the openwrt forum with such questions.
https://forum.openwrt.org/
