### ISSUE TITLE
ddns-scripts: DDNS Service provider is not available

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/packages#13495]
LuCI Master git-20.267.53658-b17ec09
    ddns-scripts	2.8.0-24	
    luci-app-ddns	git-20.250.44589-809d085	

![Screen Shot 2020-09-26 at 7 31 37 AM](https://user-images.githubusercontent.com/323794/94324240-91ee9f00-ffcb-11ea-82e7-fb54a27ea4f3.png)

**Comment by snakwu** [comment]
@feckert
me to！！！

Collected errors:                                                               
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for ddns-
scripts_nsupdate:                                                               
 *      bind-client                                                             
 * opkg_install_cmd: Cannot install package ddns-scripts_nsupdate.              
 * check_data_file_clashes: Package ddns-scripts_service wants to install file /
home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64_musl/root-x86/usr/sha
re/ddns/services/cnkuai.cn.json                                                 
        But that file is already provided by package  * ddns-scripts_cnkuai_cn  
 * check_data_file_clashes: Package ddns-scripts_service wants to install file /
home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64_musl/root-x86/usr/sha
re/ddns/services/freedns.42.pl.json                                             
        But that file is already provided by package  * ddns-scripts_freedns_42_
pl                                                                              
 * check_data_file_clashes: Package ddns-scripts_service wants to install file /
home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64_musl/root-x86/usr/sha
re/ddns/services/route53-v1.json                                                
        But that file is already provided by package  * ddns-scripts_route53-v1 
 * opkg_install_cmd: Cannot install package ddns-scripts_service.               
make[2]: *** [package/Makefile:68: package/install] Error 255                   
make[2]: Leaving directory '/home/snakwu/openwrt-master/openwrt'                
make[1]: *** [package/Makefile:108: /home/snakwu/openwrt-master/openwrt/staging_
dir/target-x86_64_musl/stamp/.package_install] Error 2                          
make[1]: Leaving directory '/home/snakwu/openwrt-master/openwrt'                
make: *** [/home/snakwu/openwrt-master/openwrt/include/toplevel.mk:236: world] E
rror 2

**Comment by Ansuel** [comment]
@peterwillcn the app needs to be updated... Can you test the wip pr?

**Comment by Ansuel** [comment]
@snakwu we need to fix a bug in the makefile... sorry for the mess

**Comment by snakwu** [comment]
> @snakwu we need to fix a bug in the makefile... sorry for the mess

Thank you very much

**Comment by snakwu** [comment]
@Ansuel 

Brother, when can I fix it? Thank you

**Comment by Ansuel** [comment]
Tomorrow we should push a fix ;)

**Comment by snakwu** [comment]
> Tomorrow we should push a fix ;)

ok，；）

**Comment by ShayBox** [comment]
How do I apply this fix? A bit new to openwrt, but having the same problem.

**Comment by Ansuel** [comment]
if you use the snapshot image just wait for the buildbot to push a new image...

**Comment by Ansuel** [comment]
News on this?

**Comment by peterwillcn** [comment]
@Ansuel I'll test it soon. Just a moment, please.

**Comment by peterwillcn** [comment]
@Ansuel @feckert configuring bug

**Comment by Ansuel** [comment]
Can you post your ddns configuration with private data omitted?

**Comment by peterwillcn** [comment]
It work,but a little bug.
![Screen Shot 2020-10-04 at 1 43 06 PM](https://user-images.githubusercontent.com/323794/95007927-ac69ed80-0647-11eb-9fed-f9fa4d1e52b6.png)

**Comment by feckert** [comment]
@peterwillcn In my view, this has nothing to do with the last change. That is a different problem.
If it is one at all. The original problem has been fixed

**Comment by peterwillcn** [comment]
@feckert I think Package/ ddNs-scripts DEPENDS on :=+ ddNs-scripts-services is not necessary, so it can be set as optional, which will reduce the installation volume.

**Comment by Ansuel** [comment]
The complains was exactly about that.... (ddns installs only the core script but not the services)

**Comment by peterwillcn** [comment]
Yes, ddNs-scripts-core(ddNs-scripts) and ddNs-scripts-services(optional)

**Comment by peterwillcn** [comment]
> The complains was exactly about that.... (ddns installs only the core script but not the services)

Yes, ddNs-scripts-core(ddNs-scripts) and ddNs-scripts-services(optional)
