### ISSUE TITLE
nginx lua missing

### ISSUE THREAD

**Issue by silent-mobius** [openwrt/packages#1350]
Hi ,
i have been trying to make Luci run on nginx. every time i start nginx (after configuration) it gets me lua script that suppose to start Luci. I checked the log  of nginx errors and access and it seems 
I saw at http://wiki.nginx.org/HttpLuaModule that they do support lua_embedded in their webserver, how ever there is need to compile it from source  and include the LuaJIT path in it.
I am compiling at the moment, but i am new to this and it takes me a lot of time to get things to work properly. 
Could you recompile as well and upload in to 14.07repo?
thanks in advance

**Comment by jow-** [comment]
Sorry, but Nginx does not support CGI, so it cannot run LuCI. You might investigate the use of a fastcgi-wrapper to execute LuCI.
