### ISSUE TITLE
gstreamer1-utils builds unusable binaries due to build options

### ISSUE THREAD

**Issue by arkanoid87** [openwrt/packages#13531]
Maintainer: @flyn-org @thess 

```
cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.4'
DISTRIB_REVISION='r11208-ce6496d796'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.4 r11208-ce6496d796'
DISTRIB_TAINTS=''
```

Description:

This packages list
`"gstreamer1-utils gst1-mod-rtp gst1-mod-rtsp gst1-mod-mpegpsmux"`

should be sufficient to run:
`gst-launch-1.0 rtspsrc location=... ! fakesink`

but gst-launch-1.0 is not finding any element due to disabled registry, moreover disabling cmd parsing leads to the impossibility to load plugins/element manually in /usr/lib/gstreamer-1.0

gst-inspect-1.0 prints:
```
staticelements:  bin: Generic bin
staticelements:  pipeline: Pipeline object

Total count: 1 plugin, 2 features
```

and /usr/lib/gstreamer-1.0/gst-plugin-scanner exits with code 1 without printing anything

how I am supposed to use gst-launch-1.0 with the provided build?

**Comment by flyn-org** [comment]
We need to backport this to 19.07. See https://github.com/openwrt/packages/pull/13532.

**Comment by neheb** [comment]
Backported.

**Comment by arkanoid87** [comment]
now command parsing and registry works

thanks
