### ISSUE TITLE
gst1-plugins-bad mpegtsmux/demux missing

### ISSUE THREAD

**Issue by arkanoid87** [openwrt/packages#13545]
Maintainer: @flyn-org @thess 

```
cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.4'
DISTRIB_REVISION='r11208-ce6496d796'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.4 r11208-ce6496d796'
DISTRIB_TAINTS=''
```
Description:

elements mpegtsmux and mpegtsdemux are missing in build
I guess is is due to commented in Makefile:
https://github.com/openwrt/packages/blob/19866ad4f243ef9ffce6676737e359e6a4c030a7/multimedia/gst1-plugins-bad/Makefile#L383

I'd like to ask if there's an issue in delivering this valid tool into the build.

MpegTS is a valid muxer/demuxer option in an embedded scenario.
In a context where encoding/decoding is impossible/discouraged, mpegts can help in moving and storing live streams

**Comment by micmac1** [comment]
It was disabled here: https://github.com/openwrt/packages/commit/e35d46becfdc8026fee3c7cdf5a91049bab0d482

Simply enabling it again isn't enough:

```
Package gst1-mod-mpegtsdemux is missing dependencies for the following libraries:
libgstcodecparsers-1.0.so.0
libgstmpegts-1.0.so.0
```

These libs are part of gst-plugins-bad. So what would need to  be done is add these libs as packages. That means somebody would need to be interested enough to do the work :)

Regards,
Seb

**Comment by arkanoid87** [comment]
sadly I don't have the skill set to solve this, but maybe I could help somehow if you would expose some general steps to reproduce the build environment

Thanks

**Comment by arkanoid87** [comment]
thanks!
