### ISSUE TITLE
Master branch libupNP in GCC10 compile error!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#13587]
![image](https://user-images.githubusercontent.com/45259624/95214193-3a013500-0822-11eb-8c7d-a491f9cb91e8.png)

**Comment by neheb** [comment]
That's quite strange... I don't get this error on CentOS 7 or Fedora 32.

Which package of yours needs libupnp?

**Comment by zxlhhyccc** [comment]
> That's quite strange... I don't get this error on CentOS 7 or Fedora 32.
> 
> Which package of yours needs libupnp?

aMule.....

**Comment by neheb** [comment]
which is not in here.

I don't think your issue is with GCC10. Try adding PKG_FIXUP:=autoreconf
