### ISSUE TITLE
CShark in Openwrt 19.07

### ISSUE THREAD

**Issue by lelguea** [openwrt/packages#13597]
'cshark'

Description: When i try to use, many error are in system log
Wed Oct  7 21:08:04 2020 daemon.emerg cshark[13893]: cshark: invalid SSL certificate
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: /usr/lib/lua/luci/controller/cshark.lua:108: module 'uci' not found:
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no field package.preload['uci']
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file './uci.lua'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/share/lua/uci.lua'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/share/lua/uci/init.lua'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/lib/lua/uci.lua'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/lib/lua/uci/init.lua'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file './uci.so'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/lib/lua/uci.so'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	no file '/usr/lib/lua/loadall.so'
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: stack traceback:
Wed Oct  7 21:08:07 2020 daemon.err uhttpd[1801]: 	[C]: in function 'require'

**Comment by hnyman** [comment]
19.07 is EoL
