### ISSUE TITLE
python-ciso8601: recursive dependency

### ISSUE THREAD

**Issue by The-BB** [openwrt/packages#13747]
Maintainer: @BKPepe 
Environment: all
Description: recursive dependency

https://github.com/openwrt/packages/blob/master/lang/python/python-ciso8601/Makefile#L40
and
https://github.com/openwrt/packages/blob/master/lang/python/python-ciso8601/Makefile#L41
```$(eval $(call BuildPackage,python3-ciso8601-src))```

**Comment by BKPepe** [comment]
I see. Thank you for reporting. Going to fix this!
