### ISSUE TITLE
Youku yk1

### ISSUE THREAD

**Issue by predators46** [openwrt/packages#13784]
i looked at the youku yk1 support wiki. is youku yk1di wifi supported on openwrt and can be used?

[ https://openwrt.org/toh/hwdata/youku/youku_yk1 ](url)

**Comment by ysc3839** [comment]
You should ask such questions on [OpenWrt Forum](https://forum.openwrt.org/).

**Comment by neheb** [comment]
It is supported yes. But that is unrelated here.
