### ISSUE TITLE
openssh-client (7.7p1-1) missing libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by modemmike** [openwrt/packages#13811]
Environment: OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.196.56128-9112198)
GL.iNet GL-AR300M

Description:

Seems the reference to crypto is wrong:

Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/bin/ssh)

I see: /usr/lib/libcrypto.so.1.1 is installed, maybe I need a different image?

Continuing with the errors:

Error relocating /usr/bin/ssh: X509_new: symbol not found
Error relocating /usr/bin/ssh: EVP_MD_block_size: symbol not found
Error relocating /usr/bin/ssh: DSA_do_sign: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_new_by_curve_name: symbol not found
Error relocating /usr/bin/ssh: BIO_s_mem: symbol not found
Error relocating /usr/bin/ssh: EVP_MD_CTX_cleanup: symbol not found
Error relocating /usr/bin/ssh: ECDH_compute_key: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_new: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_free: symbol not found
Error relocating /usr/bin/ssh: BN_clear_free: symbol not found
Error relocating /usr/bin/ssh: BIO_write: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_key_length: symbol not found
Error relocating /usr/bin/ssh: BN_div: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_cmp: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_set_group: symbol not found
Error relocating /usr/bin/ssh: ENGINE_load_builtin_engines: symbol not found
Error relocating /usr/bin/ssh: PEM_read_bio_PrivateKey: symbol not found
Error relocating /usr/bin/ssh: ERR_load_crypto_strings: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_get_degree: symbol not found
Error relocating /usr/bin/ssh: RSA_sign: symbol not found
Error relocating /usr/bin/ssh: ERR_get_error: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_set_key_length: symbol not found
Error relocating /usr/bin/ssh: PEM_write_bio_ECPrivateKey: symbol not found
Error relocating /usr/bin/ssh: EVP_MD_CTX_md: symbol not found
Error relocating /usr/bin/ssh: SSLeay_version: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_is_at_infinity: symbol not found
Error relocating /usr/bin/ssh: d2i_X509: symbol not found
Error relocating /usr/bin/ssh: DSA_generate_key: symbol not found
Error relocating /usr/bin/ssh: BN_cmp: symbol not found
Error relocating /usr/bin/ssh: X509_free: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_free: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_new: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_cbc: symbol not found
Error relocating /usr/bin/ssh: DH_size: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_get_curve_name: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_ctrl: symbol not found
Error relocating /usr/bin/ssh: PEM_write_bio_RSAPrivateKey: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_point2oct: symbol not found
Error relocating /usr/bin/ssh: RSA_new: symbol not found
Error relocating /usr/bin/ssh: BN_bn2bin: symbol not found
Error relocating /usr/bin/ssh: EVP_Digest: symbol not found
Error relocating /usr/bin/ssh: AES_encrypt: symbol not found
Error relocating /usr/bin/ssh: DH_generate_key: symbol not found
Error relocating /usr/bin/ssh: DH_compute_key: symbol not found
Error relocating /usr/bin/ssh: PEM_write_bio_DSAPrivateKey: symbol not found
Error relocating /usr/bin/ssh: EVP_MD_CTX_init: symbol not found
Error relocating /usr/bin/ssh: EC_METHOD_get_field_type: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_method_of: symbol not found
Error relocating /usr/bin/ssh: BIO_free: symbol not found
Error relocating /usr/bin/ssh: BIO_ctrl: symbol not found
Error relocating /usr/bin/ssh: BIO_new: symbol not found
Error relocating /usr/bin/ssh: DSA_generate_parameters_ex: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_set_asn1_flag: symbol not found
Error relocating /usr/bin/ssh: EVP_PKEY_get1_RSA: symbol not found
Error relocating /usr/bin/ssh: RSA_public_decrypt: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_get0_group: symbol not found
Error relocating /usr/bin/ssh: EVP_DigestUpdate: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_cmp: symbol not found
Error relocating /usr/bin/ssh: DH_free: symbol not found
Error relocating /usr/bin/ssh: BN_CTX_new: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_iv_length: symbol not found
Error relocating /usr/bin/ssh: EVP_MD_CTX_copy_ex: symbol not found
Error relocating /usr/bin/ssh: SSLeay: symbol not found
Error relocating /usr/bin/ssh: ENGINE_register_all_complete: symbol not found
Error relocating /usr/bin/ssh: X509_get_pubkey: symbol not found
Error relocating /usr/bin/ssh: DSA_do_verify: symbol not found
Error relocating /usr/bin/ssh: ECDSA_do_sign: symbol not found
Error relocating /usr/bin/ssh: BN_print_fp: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_new_by_curve_name: symbol not found
Error relocating /usr/bin/ssh: BN_copy: symbol not found
Error relocating /usr/bin/ssh: RSA_blinding_on: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_set_private_key: symbol not found
Error relocating /usr/bin/ssh: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating /usr/bin/ssh: ECDSA_SIG_new: symbol not found
Error relocating /usr/bin/ssh: EVP_CIPHER_CTX_free: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_generate_key: symbol not found
Error relocating /usr/bin/ssh: BN_free: symbol not found
Error relocating /usr/bin/ssh: DSA_SIG_free: symbol not found
Error relocating /usr/bin/ssh: DH_new: symbol not found
Error relocating /usr/bin/ssh: BN_is_bit_set: symbol not found
Error relocating /usr/bin/ssh: EVP_DigestInit_ex: symbol not found
Error relocating /usr/bin/ssh: RSAPublicKey_dup: symbol not found
Error relocating /usr/bin/ssh: BN_dup: symbol not found
Error relocating /usr/bin/ssh: BN_init: symbol not found
Error relocating /usr/bin/ssh: BN_CTX_start: symbol not found
Error relocating /usr/bin/ssh: DSA_free: symbol not found
Error relocating /usr/bin/ssh: ECDSA_SIG_free: symbol not found
Error relocating /usr/bin/ssh: EVP_rc4: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_get_order: symbol not found
Error relocating /usr/bin/ssh: BN_CTX_free: symbol not found
Error relocating /usr/bin/ssh: RSA_get_default_method: symbol not found
Error relocating /usr/bin/ssh: EVP_PKEY_get1_EC_KEY: symbol not found
Error relocating /usr/bin/ssh: EVP_Cipher: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_oct2point: symbol not found
Error relocating /usr/bin/ssh: EVP_PKEY_free: symbol not found
Error relocating /usr/bin/ssh: RSA_set_method: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_get_affine_coordinates_GFp: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_get0_private_key: symbol not found
Error relocating /usr/bin/ssh: BN_sub: symbol not found
Error relocating /usr/bin/ssh: RSA_free: symbol not found
Error relocating /usr/bin/ssh: RAND_bytes: symbol not found
Error relocating /usr/bin/ssh: BN_bin2bn: symbol not found
Error relocating /usr/bin/ssh: DSA_SIG_new: symbol not found
Error relocating /usr/bin/ssh: BN_num_bits: symbol not found
Error relocating /usr/bin/ssh: AES_set_encrypt_key: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_get0_public_key: symbol not found
Error relocating /usr/bin/ssh: RSA_set_ex_data: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_mul: symbol not found
Error relocating /usr/bin/ssh: RSA_size: symbol not found
Error relocating /usr/bin/ssh: RSA_generate_key_ex: symbol not found
Error relocating /usr/bin/ssh: BN_new: symbol not found
Error relocating /usr/bin/ssh: DSA_new: symbol not found
Error relocating /usr/bin/ssh: EC_POINT_clear_free: symbol not found
Error relocating /usr/bin/ssh: EVP_DigestFinal_ex: symbol not found
Error relocating /usr/bin/ssh: EVP_PKEY_get1_DSA: symbol not found
Error relocating /usr/bin/ssh: ECDSA_do_verify: symbol not found
Error relocating /usr/bin/ssh: ERR_peek_error: symbol not found
Error relocating /usr/bin/ssh: RSA_get_ex_data: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_free: symbol not found
Error relocating /usr/bin/ssh: OPENSSL_config: symbol not found
Error relocating /usr/bin/ssh: BN_set_word: symbol not found
Error relocating /usr/bin/ssh: ERR_peek_last_error: symbol not found
Error relocating /usr/bin/ssh: EVP_CipherInit: symbol not found
Error relocating /usr/bin/ssh: BN_CTX_get: symbol not found
Error relocating /usr/bin/ssh: BN_value_one: symbol not found
Error relocating /usr/bin/ssh: EC_KEY_set_public_key: symbol not found
Error relocating /usr/bin/ssh: BN_hex2bn: symbol not found
Error relocating /usr/bin/ssh: RAND_status: symbol not found
Error relocating /usr/bin/ssh: EC_GROUP_set_asn1_flag: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_gcm: symbol not found
Error relocating /usr/bin/ssh: EVP_md5: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha512: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_192_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha1: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_192_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_gcm: symbol not found
Error relocating /usr/bin/ssh: EVP_des_ede3_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha384: symbol not found
Error relocating /usr/bin/ssh: EVP_sha256: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_gcm: symbol not found
Error relocating /usr/bin/ssh: EVP_md5: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha512: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_192_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha1: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_192_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_128_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_ctr: symbol not found
Error relocating /usr/bin/ssh: EVP_aes_256_gcm: symbol not found
Error relocating /usr/bin/ssh: EVP_des_ede3_cbc: symbol not found
Error relocating /usr/bin/ssh: EVP_sha384: symbol not found
Error relocating /usr/bin/ssh: EVP_sha256: symbol not found

**Comment by neheb** [comment]
18.06 uses OpenSSL 1.0.2. Why do you have 1.1 installed?

**Comment by modemmike** [comment]
@neheb thanks for the response, the answer is, I dunno, thats what installs when I install libopenssl as referenced here: https://openwrt.org/packages/pkgdata_owrt18_6/openssh-client  opkg apparently does not have method for specifying a version and I'm def a newb with Linux. I even tried symlinking the old to the new but that resulted in more errors.

**Comment by modemmike** [comment]
Package libopenssl (1.1.1d-2) installed in root is up to date.

**Comment by neheb** [comment]
That's...not right. 1.1.1 is not supposed to be installed in 18.06. I assume you're using custom feeds?

**Comment by modemmike** [comment]
Nope, OEM firmware from https://dl.gl-inet.com/firmware/ar300m/ and I haven't changed anything, this is a fresh install. I will try some other images.

**Comment by neheb** [comment]
And there we go. This issue should be taken with them.
