### ISSUE TITLE
mwan3: can't determine gateway of openvpn tap interface

### ISSUE THREAD

**Issue by kghost** [openwrt/packages#13823]
OpenWrt 19.07.4, r11208-ce6496d796

interface information is empty for openvpn tap device

```
root@OpenWrt:~# ubus call network.interface dump

                {
                        "interface": "vpn",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 503,
                        "l3_device": "tap0",
                        "proto": "none",
                        "device": "tap0",
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [

                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
```

Here is my openvpn configure to set the gateway:

```
route-nopull
route 0.0.0.0 0.0.0.0 vpn_gateway 30
```

My tap device
```
369: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xxx.xxx.xxx.xxx/24 brd xxx.xxx.xxx.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 xxxx/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 xxxx/64 scope link 
       valid_lft forever preferred_lft forever
```

And route table

```
default via xxx.xxx.xxx.1 dev tap0 metric 30 
xxx.xxx.xxx.0/24 dev tap0 proto kernel scope link src xxx.xxx.xxx.xxx
```

It maybe hard to get the gateway of the tap device, is there any alternative way to manually set or override the information for mwan3 ?

**Comment by aaronjg** [comment]
The issue is that openvpn does not use the `netifd` subsystem, so the gateway and IP address are not available in ubus. 

Can you try the latest version of mwan3 from snapshot? I recently changed the route tables to get all of the routes from the main routing table, rather than trying to figure out the default route from the netifd data.

The latest version is not available in 19.07, so please install it manually for your device from here:
https://downloads.openwrt.org/snapshots/packages/

**Comment by ptpt52** [comment]
This should not work with openvpn, mwan3 rely on the hotplug iface event, where depends on the netifd.

maybe we could change, let the iface event generates from mwan3rtmon, where we could deteminate the events from the route table changes

**Comment by kghost** [comment]
Is there any workaround to let me manually set the gateway ? Either through netif or mwan3

**Comment by aaronjg** [comment]
> This should not work with openvpn, mwan3 rely on the hotplug iface event, where depends on the netifd.

Mwan3 will start the tracker when it starts. It may not work as smoothly as it does with a supported netifd protocol, but I have used mwan3 with openvpn, and it works well enough.

> Is there any workaround to let me manually set the gateway ? Either through netif or mwan3

Please try with the snapshot version, and report any issues.

**Comment by kghost** [comment]
Tried snapshot version `mwan3 - 2.10.1-1`, works like a charm.

**Comment by kghost** [comment]
The snapshot version report all my interfaces are offline

```
config interface 'wan'              
        option enabled '1'          
        option initial_state 'online'
        option family 'ipv4'  
```

```
root@OpenWrt:~# mwan3 interfaces
Interface status:
 interface wan is offline 00h:00m:00s, uptime 00h:17m:15s and tracking is not enabled
```

But the `wan` connection is active

**Comment by kghost** [comment]
It looks like there are problems with tracking disabled. I manually deleted the while loop in `mwan3track` then it works

**Comment by aaronjg** [comment]
Yes, there was a bug in mwan3track. Could you please try these commits rather than deleting the while loop?

https://github.com/openwrt/packages/commit/94a25dbd92adcf070e10a508f5103d6914449f2a
https://github.com/openwrt/packages/commit/81e6a8fd3be57cba3b5bcbeb40fbbef52779f70b
