### ISSUE TITLE
banip: dependency on logd breaks syslog-ng installation

### ISSUE THREAD

**Issue by boecko** [openwrt/packages#13820]
Hi,

Building an image fails, when syslog-ng and banip is selected, because banip depends on logd.

logd and syslog-ng both want to provide /sbin/logread

### Solution
depend on logd OR syslog-ng

**Comment by dibdot** [comment]
If you've tested banIP with both logger variants feel free to open a PR.

**Comment by boecko** [comment]
I did. logread from syslog-ng is compatible.
Should i remove the dependency ```logd```?
Is there way to make an 'OR' dependency on that in the Makefile?

**Comment by dibdot** [comment]
Thanks for testing & confirmation. Currently I'm working on a bigger update. If you don't mind I'll remove the dependency with this update, too. Of course, this will take some time ... if it's urgent for you, open a PR with the dependency removal.

**Comment by ja-pa** [comment]
> I did. logread from syslog-ng is compatible.
> Should i remove the dependency `logd`?
> Is there way to make an 'OR' dependency on that in the Makefile?

Offtopic: It is possible to use OR, etc see **Dependency Types** section https://openwrt.org/docs/guide-developer/packages

**Comment by boecko** [comment]
> Offtopic: It is possible to use OR, etc see **Dependency Types** section https://openwrt.org/docs/guide-developer/packages

I tried different lines .. all but one ended in a syntax error 
This one managee to compile 
``` @(PACKAGE_logd||PACKAGE_syslog-ng)```
But it seems wrong for me.

Something like dpkg Provides would solve that in a more elegant way.
```Provides: logread```

**Comment by dibdot** [comment]
@boecko I've removed the logd dependency. Thanks for bringing this up.
