### ISSUE TITLE
mwan3: load balancing displayed offline in multi-dial state

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#13865]
![image](https://user-images.githubusercontent.com/45259624/98373965-fb59d700-207a-11eb-87bb-8b352b55442e.png)

**Comment by feckert** [comment]
You'll have to give us a little more information!
I can't do anything with that.

**Comment by zxlhhyccc** [comment]
> You'll have to give us a little more information!
> I can't do anything with that.

I set up a single line multi-dial, multi-dial all successful online, but the load balancing display interface is: offline

**Comment by zxlhhyccc** [comment]
Instead of the 19.07 branch mWAN3, it will display normally: online.
![image](https://user-images.githubusercontent.com/45259624/98378890-99e93680-2081-11eb-87c5-5fc66214120b.png)

**Comment by feckert** [comment]
Did test the latest master branch?
If so could try this https://github.com/openwrt/packages/pull/13853

**Comment by aaronjg** [comment]
Can you report the output of 

`mwan3 interfaces`

This will help determine if it is a `luci-app-mwan3` bug or an issue in `mwan3`

**Comment by zxlhhyccc** [comment]
> mwan3

Error caused by MWAN3

**Comment by aaronjg** [comment]
Please ssh to your router post the output of the command I asked for. I can not reproduce and need additional information to determine which package needs to be updated.

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/98445307-f4ea5e80-2151-11eb-8a48-e7d1149dc52e.png)

**Comment by aaronjg** [comment]
Thanks. Looks like mwan3 did not start. Can you run ‘mwan3 start’ and then ‘logread -e mwan3’ and share the output?

**Comment by zxlhhyccc** [comment]
> Thanks. Looks like mwan3 did not start. Can you run ‘mwan3 start’ and then ‘logread -e mwan3’ and share the output?

After running MWAN3 Start, the routing will be down and the routing will have to be restarted before the load balancing can work properly!
![Uploading image.png…]()

**Comment by zxlhhyccc** [comment]
> Did test the latest master branch?
> If so could try this #13853
Use #13853 for the same problem

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/98449848-6df9ae00-2172-11eb-95db-be0aa455031a.png)

**Comment by aaronjg** [comment]
What is `mwan3helper`? I don't see it in any of the official feeds. It looks like that may be causing some problems.

Can you share the output of `ipset list`

`opkg list-installed` and `ip route list table all`

Also, if you do a fixed-width block with "\`\`\` \n \<command output\> \n  \`\`\` , rather than pasting images, it will be easier to see what is going on.

**Comment by zxlhhyccc** [comment]
> What is `mwan3helper`? I don't see it in any of the official feeds. It looks like that may be causing some problems.
> 
> Can you share the output of `ipset list`
> 
> `opkg list-installed` and `ip route list table all`
> 
> Also, if you do a fixed-width block with "``` \n <command output> \n ``` , rather than pasting images, it will be easier to see what is going on.
ipset list:
`````
Name: mwan3_connected
Type: list:set
Revision: 3
Header: size 8
Size in memory: 184
References: 0
Number of entries: 6
Members:
mwan3_dynamic_v4
mwan3_dynamic_v6
mwan3_custom_v4
mwan3_custom_v6
mwan3_connected_v4
mwan3_connected_v6

Name: mwan3_sticky_https
Type: list:set
Revision: 3
Header: size 8
Size in memory: 88
References: 0
Number of entries: 2
Members:
mwan3_sticky_v4_https
mwan3_sticky_v6_https
````
opkg list-installed
```````
6in4 - 26
AdGuardHome - 0.104.0-1
adbyby-ram_edition - 2.7-20200315
amule - 2.3.2-5
antileech - 2.3.2-1
appfilter - 3.0-1
autocore-arm - 1-28
automount - 2-30
base-files - 235-r14869-9867d08e07
bash - 5.0-4
bc - 1.06.95-1
bind-host - 9.16.8-1
bind-libs - 9.16.8-1
block-mount - 2020-10-16-f25ab8a8-1
boost - 1.74.0-6
boost-chrono - 1.74.0-6
boost-date_time - 1.74.0-6
boost-program_options - 1.74.0-6
boost-random - 1.74.0-6
boost-system - 1.74.0-6
brcmfmac-firmware-usb - 20201022-1
brook - 20200909-1
busybox - 1.31.1-5
ca-bundle - 20200601-1
ca-certificates - 20200601-1
cgi-io - 2020-10-11-d2907bd1-19
chinadns-ng - 1.0-beta.22-4
coremark - 2020-09-17-41537ea3-15
coreutils - 8.32-5
coreutils-base64 - 8.32-5
coreutils-nohup - 8.32-5
coreutils-od - 8.32-5
curl - 7.72.0-2
ddns-scripts - 2.8.2-3
ddns-scripts-services - 2.8.2-3
ddns-scripts_aliyun - 1.0.3-1
ddns-scripts_dnspod - 1.0.3-4
default-settings - 1.1-56
dns2socks - 2.1-20200218
dnsmasq-full - 2.82-8
dropbear - 2020.80-4
etherwake - 1.09-5
firewall - 2020-09-05-8c2f9fad-1
frpc - 0.34.2-1
fstools - 2020-10-16-f25ab8a8-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2020-10-25-9ef88681-1
haproxy - 2.2.4-2
hostapd-common - 2020-06-08-5a8b3662-14
https-dns-proxy - 2020-04-09-3
icu - 67.1-2
ip-full - 5.8.0-1
ip6tables - 1.8.4-2
ip6tables-mod-fullconenat - 2020-05-09-a36b9b54-1
ip6tables-mod-nat - 1.8.4-2
ipset - 7.6-1
ipt2socks - 1.1.3-1
iptables - 1.8.4-2
iptables-mod-conntrack-extra - 1.8.4-2
iptables-mod-extra - 1.8.4-2
iptables-mod-filter - 1.8.4-2
iptables-mod-fullconenat - 2020-05-09-a36b9b54-1
iptables-mod-ipopt - 1.8.4-2
iptables-mod-nat-extra - 1.8.4-2
iptables-mod-tproxy - 1.8.4-2
iputils-arping - 20200821-1
ipv6helper - 1.0-2
iw - 5.8-1
iwinfo - 2020-06-03-2faa20e5-1
jq - 1.6-1
jshn - 2020-08-06-9e52171d-1
jsonfilter - 2018-02-04-c7e938d6-1
k3wifi - 1-2
kcptun-client - 20201010-1
kernel - 5.4.74-1-6337afcb973e916e8b6ed419115449de
kmod-brcmfmac - 5.4.74+5.8-1-2
kmod-brcmutil - 5.4.74+5.8-1-2
kmod-cfg80211 - 5.4.74+5.8-1-2
kmod-crypto-aead - 5.4.74-1
kmod-crypto-arc4 - 5.4.74-1
kmod-crypto-ccm - 5.4.74-1
kmod-crypto-cmac - 5.4.74-1
kmod-crypto-crc32c - 5.4.74-1
kmod-crypto-ctr - 5.4.74-1
kmod-crypto-des - 5.4.74-1
kmod-crypto-ecb - 5.4.74-1
kmod-crypto-gcm - 5.4.74-1
kmod-crypto-gf128 - 5.4.74-1
kmod-crypto-ghash - 5.4.74-1
kmod-crypto-hash - 5.4.74-1
kmod-crypto-hmac - 5.4.74-1
kmod-crypto-manager - 5.4.74-1
kmod-crypto-md4 - 5.4.74-1
kmod-crypto-md5 - 5.4.74-1
kmod-crypto-null - 5.4.74-1
kmod-crypto-pcompress - 5.4.74-1
kmod-crypto-rng - 5.4.74-1
kmod-crypto-seqiv - 5.4.74-1
kmod-crypto-sha256 - 5.4.74-1
kmod-crypto-sha512 - 5.4.74-1
kmod-fs-exfat - 5.4.74+5.8.7-1
kmod-fs-ext4 - 5.4.74-1
kmod-fs-vfat - 5.4.74-1
kmod-fuse - 5.4.74-1
kmod-gpio-button-hotplug - 5.4.74-3
kmod-ifb - 5.4.74-1
kmod-ip6tables - 5.4.74-1
kmod-ipt-conntrack - 5.4.74-1
kmod-ipt-conntrack-extra - 5.4.74-1
kmod-ipt-core - 5.4.74-1
kmod-ipt-extra - 5.4.74-1
kmod-ipt-filter - 5.4.74-1
kmod-ipt-fullconenat - 5.4.74+2020-05-09-a36b9b54-1
kmod-ipt-ipopt - 5.4.74-1
kmod-ipt-ipset - 5.4.74-1
kmod-ipt-nat - 5.4.74-1
kmod-ipt-nat-extra - 5.4.74-1
kmod-ipt-nat6 - 5.4.74-1
kmod-ipt-offload - 5.4.74-1
kmod-ipt-raw - 5.4.74-1
kmod-ipt-tproxy - 5.4.74-1
kmod-iptunnel - 5.4.74-1
kmod-iptunnel4 - 5.4.74-1
kmod-leds-gpio - 5.4.74-1
kmod-ledtrig-default-on - 5.4.74-1
kmod-ledtrig-heartbeat - 5.4.74-1
kmod-ledtrig-netdev - 5.4.74-1
kmod-ledtrig-timer - 5.4.74-1
kmod-lib-crc-ccitt - 5.4.74-1
kmod-lib-crc16 - 5.4.74-1
kmod-lib-textsearch - 5.4.74-1
kmod-macvlan - 5.4.74-1
kmod-nf-conntrack - 5.4.74-1
kmod-nf-conntrack-netlink - 5.4.74-1
kmod-nf-conntrack6 - 5.4.74-1
kmod-nf-flow - 5.4.74-1
kmod-nf-ipt - 5.4.74-1
kmod-nf-ipt6 - 5.4.74-1
kmod-nf-nat - 5.4.74-1
kmod-nf-nat6 - 5.4.74-1
kmod-nf-reject - 5.4.74-1
kmod-nf-reject6 - 5.4.74-1
kmod-nfnetlink - 5.4.74-1
kmod-nls-base - 5.4.74-1
kmod-nls-cp437 - 5.4.74-1
kmod-nls-iso8859-1 - 5.4.74-1
kmod-nls-utf8 - 5.4.74-1
kmod-oaf - 5.4.74+3.0-1
kmod-phy-bcm-ns-usb2 - 5.4.74-1
kmod-phy-bcm-ns-usb3 - 5.4.74-1
kmod-ppp - 5.4.74-1
kmod-pppoe - 5.4.74-1
kmod-pppox - 5.4.74-1
kmod-sched-cake - 5.4.74-1
kmod-sched-core - 5.4.74-1
kmod-scsi-core - 5.4.74-1
kmod-sit - 5.4.74-1
kmod-slhc - 5.4.74-1
kmod-tcp-bbr - 5.4.74-1
kmod-tcp-bbr-nanqinlang-5.4 - 5.4.74-1
kmod-tun - 5.4.74-1
kmod-usb-bcma - 5.4.74-1
kmod-usb-core - 5.4.74-1
kmod-usb-ehci - 5.4.74-1
kmod-usb-ledtrig-usbport - 5.4.74-1
kmod-usb-ohci - 5.4.74-1
kmod-usb-storage - 5.4.74-1
kmod-usb-storage-extras - 5.4.74-1
kmod-usb-storage-uas - 5.4.74-1
kmod-usb2 - 5.4.74-1
kmod-usb3 - 5.4.74-1
libatomic1 - 10.2.0-2
libbfd - 2.34-1
libblobmsg-json - 2020-08-06-9e52171d-1
libbz2-1.0 - 1.0.8-1
libc - 1.1.24-2
libcap - 2.43-1
libcap-bin - 2.43-1
libcap-ng - 0.8-1
libcares - 1.16.1-2
libcryptopp - 8.2.0-1
libcurl4 - 7.72.0-2
libdb47 - 4.7.25.4.NC-5
libdouble-conversion - 3.1.5-3
libelf1 - 0.179-1
libev - 4.31-1
libevent2-7 - 2.1.11-2
libexpat - 2.2.10-1
libffi - 3.3-2
libgcc1 - 10.2.0-2
libgdbm - 1.18.1-2
libgmp10 - 6.1.2-2
libip4tc2 - 1.8.4-2
libip6tc2 - 1.8.4-2
libipset13 - 7.6-1
libiwinfo-lua - 2020-06-03-2faa20e5-1
libiwinfo20200105 - 2020-06-03-2faa20e5-1
libjson-c5 - 0.15-1
libjson-script - 2020-08-06-9e52171d-1
libltdl7 - 2.4.6-2
liblua5.1.5 - 5.1.5-7
liblua5.3-5.3 - 5.3.5-4
liblucihttp-lua - 2019-07-05-a34a17d5-1
liblucihttp0 - 2019-07-05-a34a17d5-1
liblzma - 5.2.5-1
liblzo2 - 2.10-4
libmbedtls12 - 2.16.8-1
libmnl0 - 1.0.4-2
libncurses6 - 6.2-1
libnetfilter-conntrack3 - 2018-05-01-3ccae9f5-2
libnettle7 - 3.5.1-2
libnfnetlink0 - 1.0.1-3
libnl-core200 - 3.5.0-1
libnl-genl200 - 3.5.0-1
libnl-tiny - 2019-10-29-0219008c-1
libnss - 3.58-1
libopenssl-conf - 1.1.1h-1
libopenssl1.1 - 1.1.1h-1
libpcap1 - 1.9.1-2
libpcre - 8.44-2
libpcre2-16 - 10.35-2
libpng - 1.6.37-7
libpthread - 1.1.24-2
libreadline8 - 8.0-1
librt - 1.1.24-2
libsodium - 1.0.18-3
libsqlite3-0 - 3330000-1
libstdcpp6 - 10.2.0-2
libtorrent-rasterbar - 1.2.10-1
libubox20191228 - 2020-08-06-9e52171d-1
libubus-lua - 2020-10-25-ad0cd117-1
libubus20191227 - 2020-10-25-ad0cd117-1
libuci-lua - 2020-10-06-52bbc99f-3
libuci20130104 - 2020-10-06-52bbc99f-3
libuclient20160123 - 2020-06-17-c6609861-1
libudns - 0.4-1
libupnp - 1.14.0-1
libustream-openssl20200215 - 2020-03-13-5e1bc342-1
libuuid1 - 2.36-2
libuv1 - 1.40.0-1
libwebsockets-full - 3.1.0-2
libwolfssl24 - 4.5.0-stable-2
libwxbase - 2.8.12-1
libxml2 - 2.9.10-2
libxtables12 - 1.8.4-2
libzstd - 1.4.5-2
logd - 2020-10-25-9ef88681-1
lua - 5.1.5-7
luci - git-20.281.27806-e06c7b6
luci-app-accesscontrol - 1
luci-app-adbyby-plus-ram_edition - 2.7-9
luci-app-adguardhome - 15
luci-app-aliddns - 0.3.0
luci-app-amule - git-20.284.52112-8dbd467
luci-app-arpbind - 1
luci-app-autorebootschedule - 1.3
luci-app-control-guest-wifi - 1.1
luci-app-control-koolproxyR - 3.8.5-1-20201009
luci-app-control-openvpn-server - 2.3-2
luci-app-control-weburl - 1.7
luci-app-ddns - git-20.281.27806-e06c7b6
luci-app-dnspod - 1.15
luci-app-firewall - git-20.275.75166-43dc420
luci-app-flowoffload - 1.0
luci-app-frpc - 1.2
luci-app-k3screenctrl-ctcgfw - 1.1.0
luci-app-k3usb - 1.1.0-1
luci-app-kcptun - 1.5.3
luci-app-mwan3 - git-20.311.23819-1c482dd
luci-app-mwan3helper - 1
luci-app-nlbwmon - git-20.281.27806-e06c7b6
luci-app-nps - 1.1
luci-app-oaf - 3.0
luci-app-openclash - 0.40.15-beta
luci-app-opkg - git-20.281.27806-e06c7b6
luci-app-passwall - 3.9-73
luci-app-qbittorrent - git-20.304.51323-b8cd4d4
luci-app-ramfree - 1.0
luci-app-serverchan - 1.79-8
luci-app-serverchand - 2.00-6
luci-app-smartdns - 1
luci-app-socat - git-20.250.49691-2e8619a
luci-app-sqm - git-20.299.49596-5a6037a
luci-app-ssocksd - 1.0
luci-app-ssr-plus - 181
luci-app-syncdial - 2.0
luci-app-ttyd - git-20.281.27806-e06c7b6
luci-app-unblockneteasemusic-mini - 1.2
luci-app-upnp - git-20.306.04092-b01a394
luci-app-vlmcsd - 1.0
luci-app-vsftpd - 1.0
luci-app-webadmin - 1.0
luci-app-wol - git-20.281.27806-e06c7b6
luci-app-wrtbwmon - 1.0
luci-base - git-20.311.85590-5c5b134
luci-compat - git-20.298.62343-4775d1a
luci-i18n-accesscontrol-zh-cn - git-20.060.28785-314a7cb
luci-i18n-aliddns-zh-cn - git-20.103.74116-38ec016
luci-i18n-amule-zh-cn - git-20.060.28785-314a7cb
luci-i18n-arpbind-zh-cn - git-20.233.64353-af2cb90
luci-i18n-autorebootschedule-zh-cn - git-20.270.47440-b6f1aba
luci-i18n-base-zh-cn - git-20.310.71574-2894ca6
luci-i18n-control-guest-wifi-zh-cn - git-20.270.47567-f688126
luci-i18n-control-weburl-zh-cn - git-20.283.47613-c8fce8c
luci-i18n-ddns-zh-cn - git-20.310.71574-2894ca6
luci-i18n-dnspod-zh-cn - git-20.060.28785-314a7cb
luci-i18n-firewall-zh-cn - git-20.306.45394-45da039
luci-i18n-flowoffload-zh-cn - git-20.060.28785-314a7cb
luci-i18n-frpc-zh-cn - git-20.162.61395-2c1f3ee
luci-i18n-k3screenctrl-ctcgfw-zh-cn - git-20.238.61371-cdc8f0a
luci-i18n-kcptun-zh-cn - git-20.110.31544-d5abe06
luci-i18n-mwan3-zh-cn - git-20.310.71574-2894ca6
luci-i18n-mwan3helper-zh-cn - git-20.113.60512-a934a29
luci-i18n-nlbwmon-zh-cn - git-20.308.22927-855e724
luci-i18n-nps-zh-cn - git-20.271.19735-1490e78
luci-i18n-oaf-zh-cn - git-20.168.37620-6e2901f
luci-i18n-opkg-zh-cn - git-20.300.67438-a759402
luci-i18n-qbittorrent-zh-cn - git-20.303.68986-05798c9
luci-i18n-ramfree-zh-cn - git-20.060.28785-314a7cb
luci-i18n-smartdns-zh-cn - git-20.211.56518-52067de
luci-i18n-socat-zh-cn - git-20.250.49691-2e8619a
luci-i18n-sqm-zh-cn - git-20.300.73983-fc93fa6
luci-i18n-ssocksd-zh-cn - git-20.251.60907-ba6972a
luci-i18n-ssr-plus-zh-cn - git-20.311.45519-3a64329
luci-i18n-ttyd-zh-cn - git-20.308.22927-855e724
luci-i18n-upnp-zh-cn - git-20.306.45394-45da039
luci-i18n-vlmcsd-zh-cn - git-20.066.18239-fa08f87
luci-i18n-vsftpd-zh-cn - git-20.181.59607-b693865
luci-i18n-webadmin-zh-cn - git-20.182.50740-5a54469
luci-i18n-wol-zh-cn - git-20.291.62968-5724756
luci-i18n-wrtbwmon-zh-cn - git-20.060.28785-314a7cb
luci-lib-base - git-20.232.39649-1f6dc29
luci-lib-ip - git-20.281.27806-e06c7b6
luci-lib-ipkg - git-20.281.27806-e06c7b6
luci-lib-jsonc - git-20.281.27806-e06c7b6
luci-lib-nixio - git-20.281.27806-e06c7b6
luci-mod-admin-full - git-20.281.27806-e06c7b6
luci-mod-network - git-20.306.65046-83c9127
luci-mod-status - git-20.304.74791-ef94c52
luci-mod-system - git-20.281.27806-e06c7b6
luci-proto-ipv6 - git-20.281.27806-e06c7b6
luci-proto-ppp - git-20.281.27806-e06c7b6
luci-proto-relay - git-20.281.27806-e06c7b6
luci-theme-argon-master - 2.2.5
luci-theme-bootstrap - git-20.281.27806-e06c7b6
luci-theme-material - git-20.304.74050-01cefed
microsocks - 1.0-1
miniupnpd - 2.1.20200510-5
mtd - 26
mwan3 - 2.10.1-1
naiveproxy - 86.0.4240.75-1-1
netifd - 2020-10-22-24ce1eab-1
nlbwmon - 2020-04-11.1-34a18876-3
npc - 0.26.9-1
nspr - 4.29-1
ntfs-3g - 2017.3.23-3-fuseint
nvram - 10
odhcp6c - 2020-03-28-f575351c-16
odhcpd-ipv6only - 2020-11-01-735c7836-4
openclash - v1.2.0-14-g87e4d94
openssl-util - 1.1.1h-1
openvpn-easy-rsa-whisky - 3.0.6-2
openvpn-openssl - 2.4.9-5
openwrt-keyring - 2019-07-25-8080ef34-1
opkg - 2020-11-03-da9746aa-2
osafeloader - 1
oseama - 1
otrx - 1
pdnsd-alt - 1.2.9b-par-a8e46ccba7b0fa2230d6c42ab6dcd92926f6c21d
phicomm-k3screenctrl-ctcgfw - 1.0-2
ppp - 2.4.8.git-2020-10-03-2
ppp-mod-pppoe - 2.4.8.git-2020-10-03-2
procd - 2020-11-06-b0de8948-1
proxychains-ng - 4.14-2
python3 - 3.9.0-1
python3-asyncio - 3.9.0-1
python3-base - 3.9.0-1
python3-cgi - 3.9.0-1
python3-cgitb - 3.9.0-1
python3-codecs - 3.9.0-1
python3-ctypes - 3.9.0-1
python3-dbm - 3.9.0-1
python3-decimal - 3.9.0-1
python3-distutils - 3.9.0-1
python3-email - 3.9.0-1
python3-gdbm - 3.9.0-1
python3-light - 3.9.0-1
python3-logging - 3.9.0-1
python3-lzma - 3.9.0-1
python3-multiprocessing - 3.9.0-1
python3-ncurses - 3.9.0-1
python3-openssl - 3.9.0-1
python3-pydoc - 3.9.0-1
python3-sqlite3 - 3.9.0-1
python3-unittest - 3.9.0-1
python3-urllib - 3.9.0-1
python3-xml - 3.9.0-1
qbittorrent - 4.3.0.1-1
qt5-core - 5.15.1-1
qt5-network - 5.15.1-1
qt5-xml - 5.15.1-1
qtbase - 5.15.1-1
redsocks2 - 0.67-5
relayd - 2020-04-25-f4d759be-1
resolveip - 2
rpcd - 2020-09-18-3fea6559-2
rpcd-mod-file - 2020-09-18-3fea6559-2
rpcd-mod-iwinfo - 2020-09-18-3fea6559-2
rpcd-mod-luci - 20191114
rpcd-mod-rrdns - 20170710
shadowsocks-libev-config - 3.3.5-1
shadowsocks-libev-ss-local - 3.3.5-1
shadowsocks-libev-ss-redir - 3.3.5-1
shadowsocks-libev-ss-server - 3.3.5-1
shadowsocksr-libev-alt - 2.5.6-6
shadowsocksr-libev-server - 2.5.6-6
shadowsocksr-libev-ssr-local - 2.5.6-6
simple-obfs - 0.0.5-5
smartdns - 9.2020.29-1
socat - 1.7.3.4-1
sqm-scripts - 1.4.0-9
ssocks - 0.0.14-1
ssocksd - 0.0.14-1
swconfig - 12
tc - 5.8.0-1
tcping - 0.3-1
terminfo - 6.2-1
trojan - 1.16.0-1
trojan-go - 0.8.2-1
trojan-plus - 10.0.3-1
ttyd - 1.6.1-3
ubi-utils - 2.1.2-1
ubox - 2020-10-25-9ef88681-1
ubus - 2020-10-25-ad0cd117-1
ubusd - 2020-10-25-ad0cd117-1
uci - 2020-10-06-52bbc99f-3
uclient-fetch - 2020-06-17-c6609861-1
uhttpd - 2020-10-04-14a3cb42-2
uhttpd-mod-ubus - 2020-10-04-14a3cb42-2
unzip - 6.0-8
urandom-seed - 2
urngd - 2020-01-21-c7f7b6b6-1
usign - 2020-05-23-f1f65026-1
v2ray - 4.32.1-2
v2ray-plugin - 1.7.0-1
vlmcsd - svn1113-1
vsftpd-alt - 3.0.3-7
wget - 1.20.3-4
wireless-regdb - 2020.04.29-1
wireless-tools - 29-6
wpad-mesh-wolfssl - 2020-06-08-5a8b3662-14
wsdd2 - 2020-05-06-671d040c-6
zlib - 1.2.11-3
```````
ip route list table all
```````
111.77.196.1 dev pppoe-vwan2 table 1 proto kernel scope link src 111.77.196.123
182.99.216.1 dev pppoe-vwan1 table 1 proto kernel scope link src 182.99.217.124
192.168.10.0/24 dev br-lan table 1 proto kernel scope link src 192.168.10.1
default via 111.77.196.1 dev pppoe-vwan2 proto static
111.77.196.1 dev pppoe-vwan2 proto kernel scope link src 111.77.196.123
182.99.216.1 dev pppoe-vwan1 proto kernel scope link src 182.99.217.124
192.168.10.0/24 dev br-lan proto kernel scope link src 192.168.10.1
local 111.77.196.123 dev pppoe-vwan2 table local proto kernel scope host src 111.77.196.123
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
local 182.99.217.124 dev pppoe-vwan1 table local proto kernel scope host src 182.99.217.124
broadcast 192.168.10.0 dev br-lan table local proto kernel scope link src 192.168.10.1
local 192.168.10.1 dev br-lan table local proto kernel scope host src 192.168.10.1
broadcast 192.168.10.255 dev br-lan table local proto kernel scope link src 192.168.10.1
fd6f:41d4:480c::/64 dev br-lan proto static metric 1024 pref medium
unreachable fd6f:41d4:480c::/48 dev lo proto static metric 2147483647 pref medium
fe80::/64 dev devguest proto kernel metric 256 pref medium
fe80::/64 dev eth0.2 proto kernel metric 256 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev br-lan proto kernel metric 256 pref medium
fe80::/64 dev wlan0 proto kernel metric 256 pref medium
fe80::/64 dev wlan1 proto kernel metric 256 pref medium
fe80::/64 dev macvlan1 proto kernel metric 256 pref medium
fe80::/64 dev macvlan2 proto kernel metric 256 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
anycast fd6f:41d4:480c:: dev br-lan table local proto kernel metric 0 pref medium
local fd6f:41d4:480c::1 dev br-lan table local proto kernel metric 0 pref medium
anycast fe80:: dev devguest table local proto kernel metric 0 pref medium
anycast fe80:: dev eth0.2 table local proto kernel metric 0 pref medium
anycast fe80:: dev eth0 table local proto kernel metric 0 pref medium
anycast fe80:: dev br-lan table local proto kernel metric 0 pref medium
anycast fe80:: dev wlan1 table local proto kernel metric 0 pref medium
anycast fe80:: dev wlan0 table local proto kernel metric 0 pref medium
anycast fe80:: dev macvlan1 table local proto kernel metric 0 pref medium
anycast fe80:: dev macvlan2 table local proto kernel metric 0 pref medium
local fe80::22cd:59ff:feab:bb8e dev macvlan1 table local proto kernel metric 0 pref medium
local fe80::6a01:6bff:fe96:2e36 dev macvlan2 table local proto kernel metric 0 pref medium
local fe80::767d:24ff:fed3:6e5a dev eth0 table local proto kernel metric 0 pref medium
local fe80::767d:24ff:fed3:6e5a dev br-lan table local proto kernel metric 0 pref medium
local fe80::767d:24ff:fed3:6e5b dev eth0.2 table local proto kernel metric 0 pref medium
local fe80::767d:24ff:fed3:6e5b dev wlan0 table local proto kernel metric 0 pref medium
local fe80::767d:24ff:fed3:6e5c dev wlan1 table local proto kernel metric 0 pref medium
local fe80::f05a:45ff:fec2:2cd0 dev devguest table local proto kernel metric 0 pref medium
ff00::/8 dev devguest table local metric 256 pref medium
ff00::/8 dev br-lan table local metric 256 pref medium
ff00::/8 dev eth0.2 table local metric 256 pref medium
ff00::/8 dev eth0 table local metric 256 pref medium
ff00::/8 dev wlan0 table local metric 256 pref medium
ff00::/8 dev wlan1 table local metric 256 pref medium
ff00::/8 dev macvlan1 table local metric 256 pref medium
ff00::/8 dev macvlan2 table local metric 256 pref medium
````````

**Comment by aaronjg** [comment]
1) What is mwan3helper? I don't see it in any of the official feeds. It looks like that may be causing some problems.

2) You seem to be missing a default route for pppoe-vwan1 - please set a metric for all interfaces, according to the setup instructions here: https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3.

3) Could you try the branch here: https://github.com/openwrt/packages/pull/13853 - it looks like you are still on mwan3 2.10.1. Even if you tried it before, please try again, since some new commits have been added (https://github.com/openwrt/packages/pull/13853/commits/94a25dbd92adcf070e10a508f5103d6914449f2a)

**Comment by zxlhhyccc** [comment]
With MWAN3Helper removed and updated to 2.10.2, the result of the junction load balancing remains offline. But load balancing is displayed online without overdialing!
At the same time, using MWAN3 Start can start and run, but the network has been connected but cannot access the Internet, you must manually retain and apply the relevant interface in load balancing to access the Internet normally!!
![image](https://user-images.githubusercontent.com/45259624/98470148-daca8200-221e-11eb-9692-526d50a84517.png)
![image](https://user-images.githubusercontent.com/45259624/98470172-eddd5200-221e-11eb-9ac1-770b1714f428.png)
![image](https://user-images.githubusercontent.com/45259624/98470201-1bc29680-221f-11eb-9b9e-8da2116500e8.png)
![image](https://user-images.githubusercontent.com/45259624/98470222-3dbc1900-221f-11eb-8e6b-077ebb04bb04.png)

**Comment by aaronjg** [comment]
> With MWAN3Helper removed and updated to 2.10.2, the result of the junction load balancing remains offline. But load balancing is displayed online without overdialing!
At the same time, using MWAN3 Start can start and run, but the network has been connected but cannot access the Internet, you must manually retain and apply the relevant interface in load balancing to access the Internet normally!!

I’m not following some of the terms you are using. Perhaps an issue with machine translation?

What do you mean by “junction” load balancing, “overdialing”, and “manually retain and apply?”

One issue I see is that you do not have a metric associated with the WANs, which will cause some problems. Please see point 2 from before.
