### ISSUE TITLE
<kmod-rt2800-usb> - Module libs in the wrong "/lib/modules" folder

### ISSUE THREAD

**Issue by pafontai** [openwrt/packages#13912]
4.14.180+4.19.120-1-1 - 

Also make sure that the package is maintained in this repository and not in base which should be submitted at https://bugs.openwrt.org or in the LuCI repository which should be submitted at https://github.com/openwrt/luci/issues.

Issues related to releases below 18.06 and forks are not supported or maintained and will be closed.

# Issue template (remove lines from top till here)
Maintainer:  @nbd168 

Environment:
- arch : x86_64
- kernel : Linux marbeline 4.14.195 #0 SMP Sun Sep 6 16:19:39 2020 x86_64 GNU/Linux
- OpenWrt version : 19.07.04 (fresh install)

Description:
I've installed kmod-rt2800-usb and kmod-rt28XX-usb.
The modules were not loding at startup and not found by the OS.
The were installed into the folder **/lib/modules/4.14.180** whereas my kernel is **4.14.195**
After creating symbolic links, into the /lib/modules/4.14.195/ folder, the driver is launched properly.

Is there able to directly install the 'ko' files into the right kernel folder ?

```
xxx@xxxxx:/lib/modules/4.14.180# ls -l rt*
-rw-r--r--    1 root     root        148704 May 16 20:32 rt2800lib.ko
-rw-r--r--    1 root     root         28896 May 16 20:32 rt2800usb.ko
-rw-r--r--    1 root     root         57568 May 16 20:32 rt2x00lib.ko
-rw-r--r--    1 root     root         16696 May 16 20:32 rt2x00usb.ko

xxx@xxxxx:/lib/modules/4.14.195# ls -l rt*
lrwxrwxrwx    1 root     root            34 Nov 11 22:30 rt2800lib.ko -> /lib/modules/4.14.180/rt2800lib.ko
lrwxrwxrwx    1 root     root            34 Nov 11 22:30 rt2800usb.ko -> /lib/modules/4.14.180/rt2800usb.ko
lrwxrwxrwx    1 root     root            34 Nov 11 22:30 rt2x00lib.ko -> /lib/modules/4.14.180/rt2x00lib.ko
lrwxrwxrwx    1 root     root            34 Nov 11 22:31 rt2x00usb.ko -> /lib/modules/4.14.180/rt2x00usb.ko
```

**Comment by neheb** [comment]
This belongs at https://bugs.openwrt.org
