### ISSUE TITLE
resolve_conffiles: Existing conffile [ sstp-client]

### ISSUE THREAD

**Issue by predators46** [openwrt/packages#13910]
sstp-client cannot be installed

`   * resolve_conffiles: Existing conffile /home/azurevps46/sp/sp/build_dir/target-mipsel_24kc_musl/root-ramips/etc/ppp/chap-secrets is different from the conffile in the new package. The new conffile will be placed at /home/azurevps46/sp/sp/build_dir/target-mipsel_24kc_musl/root-ramips/etc/ppp/chap-secrets-opkg. `

**Comment by neheb** [comment]
That's a warning not an error. It's also expected.
