### ISSUE TITLE
rng-tools fails to build with musl and not argp-standalone

### ISSUE THREAD

**Issue by nwf** [openwrt/packages#1396]
rng-tools should be made to depend on glibc OR uclibc OR (musl AND argp-standalone), I think.

**Comment by hnyman** [comment]
hmm. currently there is build requirement of uclibc + argp_standalone.
I guess that the original intention might have been "uclibc while not eglibc/glibc" + argp_standalone.

I will test with (uclibc or musl) + argp_standalone   build dependency
