### ISSUE TITLE
Slow network connection internet on mt7621at, totolink a7000r

### ISSUE THREAD

**Issue by MrAdi25** [openwrt/packages#13980]
Internet speed is 170Mb/s but my internet conection is 300mb/s on full fresh updated openwrt (OpenWrt SNAPSHOT r15003-b19a684f46 / LuCI Master git-20.311.85590-5c5b134). i recover my stock firmware and work perfect. This problem only occurs on wan-lan. On lan-lan works perfect 1gb/s

**Comment by neheb** [comment]
You can enable flow offload to try and fix. Anyway, this is for https://bugs.openwrt.org
