### ISSUE TITLE
strongswan: add x.509 certificate based authentication

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#14027]
Maintainer: @stintel 
Environment: x86_64, generic, 359a4b4

Description:

Add X.509 certificates in addition to PSKs (pre-shared keys, i.e. passwords).

**Comment by stintel** [comment]
> Add X.509 certificates instead of PSKs (pre-shared keys, i.e. passwords).

Do you really mean "instead"?

**Comment by pprindeville** [comment]
Changed "instead of" to "in addition to"

**Comment by pprindeville** [comment]
Fixed via PR #14708.
