### ISSUE TITLE
gpsd build broken

### ISSUE THREAD

**Issue by borkra** [openwrt/packages#14040]
Commit https://github.com/openwrt/openwrt/commit/e52d0487e88c3c8c57e1310d1a02b18eae0d142e broke gpsd build
Verified that reverting commit fixes the problem.

scons: Building targets ...
arm-openwrt-linux-muslgnueabi-gcc -o cgps -Wl,-z,now -Wl,-z,relro -pthread cgps.o -L. -L/home/boris/devel/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-9.3.0_musl_eabi/usr/lib -L/home/boris/devel/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-9.3.0_musl_eabi/lib -L/home/boris/devel/openwrt/staging_dir/hostpkg/lib -L/home/boris/devel/openwrt/staging_dir/host/lib -lgps_static -lm -lrt -lncurses
/home/boris/devel/openwrt/staging_dir/toolchain-arm_cortex-a9+neon_gcc-9.3.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/9.3.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: /home/boris/devel/openwrt/staging_dir/hostpkg/lib/libncurses.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
scons: *** [cgps] Error 1

**Comment by borkra** [comment]
Adding, sysroot=$(STAGING) into SCONS_CONF in gpsd makefile fixes it too.

**Comment by neheb** [comment]
ping @ynezz

**Comment by ynezz** [comment]
https://github.com/openwrt/openwrt/commit/e52d0487e88c3c8c57e1310d1a02b18eae0d142e#commitcomment-44602909

**Comment by neheb** [comment]
Is this still an issue?

**Comment by borkra** [comment]
Yes, it is still an issue, there were no changes to gpsd

**Comment by borkra** [comment]
One can apply this patch to fix this issue:

```
diff --git a/utils/gpsd/Makefile b/utils/gpsd/Makefile
index 53428613c..3177d809c 100644
--- a/utils/gpsd/Makefile
+++ b/utils/gpsd/Makefile
@@ -104,6 +104,7 @@ SCONS_OPTIONS += \
        implicit_link=no \
        chrpath=no \
        manbuild=no \
+       sysroot="$(STAGING_DIR)" \
        target="$(TARGET_CROSS:-=)"
 
 define Build/InstallDev
```

**Comment by neheb** [comment]
Hmm I can't replicate the issue. Maybe https://github.com/openwrt/packages/pull/14081 fixes it.

**Comment by borkra** [comment]
#14081 is about libpam, it does not fix it, I am not even building libpam. There are no user accounts, or need in Pluggable Authentication Modules.

The patch I provided came from buildroot, that is how they handle gpsd.
https://github.com/buildroot/buildroot/blob/master/package/gpsd/gpsd.mk

**Comment by neheb** [comment]
Right. My confusion is why it's not failing on my end.

**Comment by borkra** [comment]
Maybe the problem is Ubuntu 20.10 special, that is what my host is.

**Comment by neheb** [comment]
Doubt it. The buildbots which use Debian 10 also fail: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/gpsd/compile.txt

My hosts are Fedora 32 and CentOS 7.

**Comment by borkra** [comment]
Anyway setting sysroot fixes it.

**Comment by neheb** [comment]
I merged a bunch of fixes for several packages. If the buildbots still complain after a day, I'll look into this.

**Comment by borkra** [comment]
I looked into the logs a bit more. It looks like gpsd fails only on 'arc' and 'arm32' platforms. On all other platforms it compiles just fine. That would explain why you could not reproduce it.

**Comment by pprindeville** [comment]
This is clearly wrong on a target-build: `-L/home/boris/devel/openwrt/staging_dir/hostpkg/lib`

**Comment by neheb** [comment]
This is fixed.
