### ISSUE TITLE
Package not deleted on adblock and banip

### ISSUE THREAD

**Issue by Ansuel** [openwrt/packages#14075]
@dibdot I know i should just make a fix and propose a pr but I notice (and this is for a long time now) that for some reason, the downloaded zip for your package are not deleted on extraction. This happen both on adblock and banip. Is this intended?

**Comment by dibdot** [comment]
Do you mean a Makefile tweak during opkg package installation?

**Comment by Ansuel** [comment]
Think I explained this bad...
The zip downloaded by the package (the block list for example) are stored in /tmp but never deleted when extracted and used. So we have these zip file wasting useful ram. Shouldn't they be removed on script termination?

I notice that there is actually a clean function in the script but in some case, the function is not called.

If you want I can provide config and a screen of the package. But it's mainly the zip the script download for the blocklist and I'm using a very basic config with a few list selected and using aria2c as a download daemon

**Comment by dibdot** [comment]
I can't reproduce that. The used temp folder is deleted after adblock processing.

**Comment by Ansuel** [comment]
I added my config... Do you have some way to backtrack this. I'm using master I can't be the only one experiencing this.

```

config adblock 'global'
	option adb_enabled '1'
	option adb_debug '0'
	option adb_forcedns '0'
	option adb_safesearch '0'
	option adb_dnsfilereset '0'
	option adb_mail '0'
	option adb_report '0'
	option adb_backup '1'
	option adb_maxqueue '4'
	list adb_sources 'adaway'
	list adb_sources 'adguard'
	list adb_sources 'disconnect'
	list adb_sources 'yoyo'
	option adb_dns 'unbound'
	option adb_fetchutil 'aria2c'
	option adb_trigger 'wan'


```

![Immagine 2020-11-29 164714](https://user-images.githubusercontent.com/20289090/100546605-8edd8c80-3262-11eb-9f02-41963755f2ed.png)

**Comment by dibdot** [comment]
Ah OK, you mean the generated gz archives ... that's the pre-generated/sorted backup files during processing, controlled by this flag:

![backup](https://user-images.githubusercontent.com/8061346/100546935-5b9bfd00-3264-11eb-8db7-30076703fb73.png)

**Comment by Ansuel** [comment]
Oh didn't notice that. So it's intended and enabled by default. Can you consider placing them in a dedicated directory in a future version?

**Comment by dibdot** [comment]
Well, /tmp is the default (and available on every openwrt device) ... and you can change that in LuCI right under the above listed option. Of course, I could put them in a "better" subdir - noted! ;-)

**Comment by Ansuel** [comment]
Yep i mean something like /tmp/adblock_backup :D 
Looks a stupid question but something like me can open another issue thinking it's a bug that there are random zip in the /tmp folder.
