### ISSUE TITLE
strongswan: pivot from ipsec- to swanctl-based configs from UCI

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#14088]
Maintainer: @stintel 
Environment: x86_64, generic, HEAD (b0cb3052)

Description:

Generate `swanctl.conf`-based config files and use `swanctl` to manage tunnel state.

**Comment by pprindeville** [comment]
@dedeckeh Don't know if you already have some work done on this or not; I'll assume not unless I hear otherwise, so will be starting from scratch...

**Comment by dedeckeh** [comment]
@pprindeville No; I don't have the time atm to work on this due to my paid job and other stuff

**Comment by pprindeville** [comment]
> No; I don't have the time atm to work on this due to my paid job and other stuff

@dedeckeh Would you have time to review it or test it?  Or is that not possible either?

**Comment by dedeckeh** [comment]
@pprindeville I won't be able to test it as i don't have access anymore to devices in IPSec test setups

**Comment by pprindeville** [comment]
I have a couple of KVM servers that have room for a dozen or so simultaneous VM's if you don't mind using x86 or amd64 images...

**Comment by pprindeville** [comment]
Fixed via PR #14708.
