### ISSUE TITLE
mvebu: kexec-tools gcc10 compile fix

### ISSUE THREAD

**Issue by ByteEnable** [openwrt/packages#14130]
kexec-tools fails to compile when building latest master from git and using GCC 10. Multiple definitions and one declaration of a debug variable named my_debug for PPC64 that spills over into arm. 

```
--- a/kexec/fs2dt.h
+++ b/kexec/fs2dt.h
@@ -30,7 +30,7 @@ extern struct bootblock bb[1];
 
 /* Used for enabling printing message from purgatory code
  * Only has implemented for PPC64 */
-int my_debug;
+extern int my_debug;
 extern int dt_no_old_root;
 
 void reserve(unsigned long long where, unsigned long long length);
```

**Comment by neheb** [comment]
This is for https://bugs.openwrt.org

Fix available here: http://patchwork.ozlabs.org/project/openwrt/patch/20200901215008.90451-1-rosenp@gmail.com/
