### ISSUE TITLE
haproxy: miss dependency of 'liblua5.3'

### ISSUE THREAD

**Issue by douo** [openwrt/packages#14182]
Maintainer: @gladiac1337
Environment:  openwrt 19.07

Description:

Haproxy: miss dependency of 'liblua5.3' 

https://github.com/openwrt/packages/blob/5e7a9a32bd0bb70427c0c83478d0ec7907c87845/net/haproxy/Makefile#L49

**Comment by gladiac1337** [comment]
@douo openwrt-19.07 does not have a liblua5.3 package. Therefore, the dependency does not exist and we decided to build lua5.3 ourselfs as part of the haproxy build process and statically link it to the haproxy binary. However, "master" does have that liblua5.3 package and therefore, we make use of it there.

It seems like you tried to use the Makefile from "master" on openwrt-19.07 which fails for the mentioned reasons.
