### ISSUE TITLE
libreswan: not compiling under buildbots

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#14207]
ping @lucize 

https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/libreswan/compile.txt

Seems like some header problem

**Comment by lucize** [comment]
maybe adding kmod-xfrm-interface as a dependency https://github.com/libreswan/libreswan/issues/378  ?

**Comment by lucize** [comment]
https://github.com/openwrt/packages/pull/14210
