### ISSUE TITLE
snmpd.conf written to wrong directory

### ISSUE THREAD

**Issue by kampfflunder** [openwrt/packages#1422]
in /etc/init.d/snmpd, snmpd.conf gets written to /var/run/snmpd.conf:

    RUN_D=/var/run
    RUN_C=$RUN_D/snmpd.conf

but snmpd searches for its config file in `/etc/snmp:/usr/share/snmp:/usr/lib/snmp:/root/.snmp`
Solution: Either set RUN_C correct or add "-c /var/run/snmpd.conf" to /etc/default/snmpd

BARRIER BREAKER (14.07, r42625), snmpd - 5.4.4-1

**Comment by karlp** [comment]
I presume you haven't actually _tried_ this?

```
# ls -l /etc/snmp/
lrwxrwxrwx    1 root     root            19 Jun 16 10:26 snmpd.conf -> /var/run/snmpd.conf
#
```

See https://github.com/openwrt/packages/blob/master/net/net-snmp/Makefile#L241
