### ISSUE TITLE
adblock: youtube list is non-functional

### ISSUE THREAD

**Issue by kousu** [openwrt/packages#14245]
Maintainer: @dibdot 
Environment:

```
root@router:~# cat /usr/lib/os-release 
NAME="OpenWrt"
VERSION="19.07.4"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 19.07.4"
VERSION_ID="19.07.4"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r11208-ce6496d796"
OPENWRT_BOARD="ramips/mt76x8"
OPENWRT_ARCH="mipsel_24kc"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 19.07.4 r11208-ce6496d796"
```

Description:

adblock [recommends](https://github.com/openwrt/packages/blob/d36fd57/net/adblock/files/README.md) a youtube blocklist, this one: https://github.com/kboghdady/youTube_ads_4_pi-hole. But that list isn't working reliably anymore. It's sometimes blocking ads, sometimes not, while causing intermittent youtube failures that make people complain that the net is "slow" (https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/80, https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/77, https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/75, https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/68).

**Comment by dibdot** [comment]
If this list is not working for you than don't use it. Bottomline you can't block youtube ads by dns blocking ... use browser plugins or buy youtube premium.
