### ISSUE TITLE
<kernel> Marvell 88W8964 8012.11bgn - hostapd: wlan1: AP-STA-DISCONNECTED

### ISSUE THREAD

**Issue by wVio** [openwrt/packages#14273]
LuCI openwrt-19.07 branch (git-20.341.57626-51f55b5) / OpenWrt 19.07.5 r11257-5090152ae3 installed on both routers (same day).

Any RaspberryPi on 2.4GHz cannot establish a connection (dhcp does not succeed) with
Linksys WRT3200ACM only on Marvell 88W8964 802.11bgn (radio1) interface.

RaspberryPi devices on 2.4GHz with TP-Link TL-WR902AC **v3 / MediaTek** MT76x8 802.11bgn, works fine. 

Both routers configured with WPA2-PSK / Chiper auto, other options on default values.

I was tested more than five (zeroW, 3B, 4B), same conclusion. On 5GHz, there is no such issue.

Sat Dec 19 10:40:43 2020 daemon.info hostapd: wlan1: STA b8:27:eb:d6:15:fd IEEE 802.11: associated (aid 5)
Sat Dec 19 10:40:43 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED b8:27:eb:d6:15:fd
Sat Dec 19 10:40:43 2020 daemon.info hostapd: wlan1: STA b8:27:eb:d6:15:fd WPA: pairwise key handshake completed (RSN)
Sat Dec 19 10:40:51 2020 daemon.info hostapd: wlan1: STA b8:27:eb:d6:15:fd IEEE 802.11: authenticated
Sat Dec 19 10:41:54 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED b8:27:eb:d6:15:fd
Sat Dec 19 10:41:54 2020 daemon.info hostapd: wlan1: STA b8:27:eb:d6:15:fd IEEE 802.11: disassociated
Sat Dec 19 10:41:54 2020 kern.debug kernel: [295390.976562] ieee80211 phy1: staid 5 deleted
Sat Dec 19 10:41:55 2020 daemon.info hostapd: wlan1: STA b8:27:eb:d6:15:fd IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

**Comment by neheb** [comment]
This is for https://bugs.openwrt.org , not here.

There's little chance to fix your issue though. The driver is mostly abandoned at this point. Marvell laid off the people working on the driver.
