### ISSUE TITLE
openconnect: Token Script Overwrites First Password in /var/etc/

### ISSUE THREAD

**Issue by FrederickGeek8** [openwrt/packages#14287]
Maintainer: @nmav 
Environment: OpenWRT SNAPSHOT r15237-fca0eb2d92

Description: When using a token script for a second password, the original password gets overwritten in `/var/etc/openconnect-$config.passwd`. If this is indeed a bug the fix is simple and below.

Relevant line: https://github.com/openwrt/packages/blob/master/net/openconnect/files/openconnect.sh#L117 should be changed to `$token_script >> "$pwfile" 2> /dev/null || {`. For context:
```bash
[ -n "$password" ] || [ "$token_mode" = "script" ] && {
    umask 077
    mkdir -p /var/etc
    pwfile="/var/etc/openconnect-$config.passwd"
    [ -n "$password" ] && {
        echo "$password" > "$pwfile"
        [ -n "$password2" ] && echo "$password2" >> "$pwfile"
    }
    [ "$token_mode" = "script" ] && {
        $token_script > "$pwfile" 2> /dev/null || {
            logger -t openconenct "Cannot get password from script '$token_script'"
            proto_setup_failed "$config"
        }
    }
    append_args --passwd-on-stdin
}
```
should be changed to
```bash
[ -n "$password" ] || [ "$token_mode" = "script" ] && {
    umask 077
    mkdir -p /var/etc
    pwfile="/var/etc/openconnect-$config.passwd"
    [ -n "$password" ] && {
        echo "$password" > "$pwfile"
        [ -n "$password2" ] && echo "$password2" >> "$pwfile"
    }
    [ "$token_mode" = "script" ] && {
        $token_script >> "$pwfile" 2> /dev/null || {
            logger -t openconenct "Cannot get password from script '$token_script'"
            proto_setup_failed "$config"
        }
    }
    append_args --passwd-on-stdin
}
```

**Comment by nmav** [comment]
Thank you. Would you like to send a pull request?

**Comment by FrederickGeek8** [comment]
@nmav I don't have the ability to test my fix right now, so I can't truthfully fill out the PR template. 

In my environment, I am currently using a workaround to this which just involves first outputting my primary password in my secondary password generation script.

**Comment by nmav** [comment]
Please open a pull request when you can test it.
