### ISSUE TITLE
net-snmp won't build with musl

### ISSUE THREAD

**Issue by maz-1** [openwrt/packages#1435]
In file included from ieee802dot11.c:28:0:
ieee802dot11.h:109:1: warning: useless storage class specifier in empty declaration [enabled by default]
 };
 ^
In file included from ieee802dot11.c:29:0:
iwlib.h:90:2: error: #error "Your kernel/libc combination is not supported"
 #error "Your kernel/libc combination is not supported"
  ^
ieee802dot11.c: In function 'addList':
ieee802dot11.c:4705:8: warning: assignment from incompatible pointer type [enabled by default]
   list = ( LIST_HEAD ( , avNode ) * ) l;            // NOTE: don't know how to get 
        ^
ieee802dot11.c: In function 'flushList':
ieee802dot11.c:4789:8: warning: assignment from incompatible pointer type [enabled by default]
   list = ( LIST_HEAD ( , avNode ) * ) l;    // NOTE: don't know how to get 
        ^
make[6]: *** [ieee802dot11.lo] Error 1
make[6]: Leaving directory `/mnt/EXT/openwrt-cc-wndr4300/openwrt/build_dir/target-mips_34kc_musl-1.1.10/net-snmp-5.4.4/agent/mibgroup'

**Comment by karlp** [comment]
I believe this was fixed in fdde98152234dbd771b47136be40342ca5b8c76c (June 25) at least, it builds in trunk with musl today.
