### ISSUE TITLE
hwinfo not compiling under glibc

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#14385]
Maintainer: @bobafetthotmail 
Environment: glibc

https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/hwinfo/compile.txt

**Comment by bobafetthotmail** [comment]
cool, that architecture isn't in the define list in this upstream file so of course it blows up later saying it's undefined https://github.com/openSUSE/hwinfo/blob/master/src/hd/hd.c#L103

Is this the ARC architecture right?  (so it's just "arc" name)

I'll prepare another patch to add it and see if there are other compile problems. But of course I can't run test it as I have no device with arc architecture
