### ISSUE TITLE
ddns-scripts  cURL Error！！

### ISSUE THREAD

**Issue by snakwu** [openwrt/packages#14408]
175334       : #> /usr/bin/curl -RsS -o /var/run/ddns/xxxx.dat --stderr /var/run/ddns/xxxx.err --noproxy '*' --header 'X-Auth-Email: xxx@xxxx.com'  --header 'X-Auth-Key: ***PW***'  --header 'Content-Type: application/json'  --request GET 'https://api.cloudflare.com/client/v4/zones?name=xxxx.com'
 175334 ERROR : cURL Error: '127'
 175334       : 
 175334  WARN : Transfer failed - retry

**Comment by dibdot** [comment]
RC 127 means usually "command not found" ... just install curl.

**Comment by snakwu** [comment]
curl has been installed!

**Comment by dibdot** [comment]
Than it might be a path issue. What's the output of `command -v curl`

**Comment by snakwu** [comment]
/usr/bin/curl

**Comment by dibdot** [comment]
Sorry I don't use ddns. Anyway, I'm quite confident that your curl installation is somewhat broken. Does a curl download work manually in the CLI?

**Comment by snakwu** [comment]
Directly select crul and then compile

**Comment by dibdot** [comment]
I don't know what you mean by that. Please test curl manually in the CLI, e.g. start `curl -Iv http://connectivity-check.ubuntu.com` in a ssh session.

**Comment by snakwu** [comment]
ok.thx!

**Comment by opz20** [comment]
It is actually very easy to solve, just install libwolfssl with opkg
![Emage](https://user-images.githubusercontent.com/47137779/106698780-74d27880-661c-11eb-9e3e-3cdc4191f315.png)

**Comment by davemunneke** [comment]
Also needed `opkg install libcurl4` for me to get curl to work

**Comment by davemunneke** [comment]
Also needed `opkg install libcurl4` for me to  work.
