### ISSUE TITLE
utils/collectd: WriteThreads setting

### ISSUE THREAD

**Issue by f00b4r0** [openwrt/packages#14414]
Maintainer: @hnyman 
Environment: ramips 19.07

*Feature request.*

Description:
By default collectd uses 5 read and 5 write threads (see [here](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#readthreads_num)). Setting `ReadThreads` to 2 as is currently done in the default uci config helps reduce memory/cpu pressure, but it makes little sense to still have 5 write threads active, especially when the only write output plugin is typically the local rrd database.

I'd suggest either matching the number of write threads with the read threads settings, or even better: making it a separable uci tunable.

I was able to lower collectd's memory usage by about 0.7MB by setting `WriteThreads` to 1.

HTH

**Comment by mstorchak** [comment]
Fixed by #14424 in 8ab9fd7fff6f7ba432b6cf9bcaa0c58519aa399a

**Comment by f00b4r0** [comment]
Thanks!
