### ISSUE TITLE
utils/fritz-tools: wrong results returned, when two keys with same starting chars exist (with FIX)

### ISSUE THREAD

**Issue by kestrel1974** [openwrt/packages#14420]
Maintainer: @\<github-user> no maintainer in makefile
Environment: (mips_24kc, fritzbox, OpenWrt current trunk and all former versions)

Description:
On my device there are two keys, macwlan and macwlan2. The current commited implementation always returns macwlan with the following command: fritz_tffs -n macwlan2 -i /dev/mtd3

The reason is the following line of code in function show_matching_key_value of both fritz_tffs_read.c and fritz_tffs_nand_read.c which only compares the length of the defined key and not the key asked for:
```
if (strncmp(name, name_filter, strlen(name)) == 0) {
```
The problem is fixed by replacing the line above with:
```
if (strcmp(name, name_filter) == 0 {
```
Thanks.

**Comment by neheb** [comment]
you fixed this: https://github.com/openwrt/openwrt/commit/12564c5b860f9849c9a2fb7026c2c11150b9a4fc
