### ISSUE TITLE
nmap - Is the new license compatible with OpenWRT?

### ISSUE THREAD

**Issue by Strykar** [openwrt/packages#14459]
@nunojpg Red Hat has declared the new Nmap license to be incompatible.
The current version that is shipped with Openwrt is 7.80 and is not affected by the new license, however, 7.90 is.

Some of the offered suggestions are to simply backport, if feasable, and stick to 7.80
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972216
https://bugzilla.redhat.com/show_bug.cgi?id=1914445

**Comment by nunojpg** [comment]
Let's wait a few weeks to the outcome of upstream discussion

https://github.com/nmap/nmap/issues/2199

**Comment by rockdrilla** [comment]
https://github.com/nmap/nmap/issues/2199#issuecomment-792048244

**Comment by BKPepe** [comment]
Closing as this is solved in mention issues.
