### ISSUE TITLE
<mlwifi> WiFi without internet on WRT1900AC (19.07.6)

### ISSUE THREAD

**Issue by tRamboli** [openwrt/packages#14533]
I just upgraded my WRT1900AC from version 19.07.4 to 19.04.6 without removing preferences. After that, all my WiFi clients connected to my WiFi but without access to the internet. I figured out that I can't access the LuCi GUI from all the WiFi clients.

I downgraded to 19.07.5 and now the issue is gone, but now the connection speed through WiFi 5g is poor and I need to re-establish the connection to restore the normal speed.

What happened to a great firmware on the WRT1900AC (v1)? It used to work perfectly.

Thanks

**Comment by BKPepe** [comment]
This is a packages repository and for generic questions, please use [OpenWrt forum](https://forum.openwrt.org/) and follow [Bugs reporting](https://openwrt.org/bugs).
