### ISSUE TITLE
iw not building

### ISSUE THREAD

**Issue by thagabe** [openwrt/packages#1456]
make[3]: Entering directory '/media/thagabe/MyLinux/openwrt/package/network/utils/iw'
. /media/thagabe/MyLinux/openwrt/include/shell.sh; xzcat /media/thagabe/MyLinux/openwrt/dl/iw-3.17.tar.xz | tar -C /media/thagabe/MyLinux/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.10_eabi/iw-3.17/.. -xf - 
xzcat: /media/thagabe/MyLinux/openwrt/dl/iw-3.17.tar.xz: File format not recognized
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Makefile:57: recipe for target '/media/thagabe/MyLinux/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.10_eabi/iw-3.17/.prepared_735e5c2b15ff12335e511c4db8765075' failed

tried building just now (3:54 p.m. PST) and the build would not continue. I tried make and make -j1 V=99

**Comment by jow-** [comment]
This is the wrong location for a bug report, iw is part of core openwrt. Also the above looks like a transient download issue. Delete dl/iw-3.17.tar.cz and retry.
