### ISSUE TITLE
adblock: add Edit Blocklist tab

### ISSUE THREAD

**Issue by komawoyo** [openwrt/packages#14563]
Hello. In the old adblock we had the option to edit the source right from the browser. The latest adblock only allows you to edit blocklist and whitelist. I would like to avoid having to scp into the router every time I want to add to my block list.

**Comment by dibdot** [comment]
Just look in the online readme and set 'adb_srcarc' to reference your own source file variant ... I do not plan to build a luci based json editor for blocklist sources.
