### ISSUE TITLE
iconv-full from latest trunk (musl) not build (enable full language suport)

### ISSUE THREAD

**Issue by build000** [openwrt/packages#1457]
make[3]: Entering directory '/magazyn/Pliki/openwrt/trunk/package/libs/libiconv-full'
make -C /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1 CC="mips-openwrt-linux-musl-gcc" DESTDIR="/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install" install
make[4]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
cd libcharset && make install prefix='/usr' exec_prefix='/usr' libdir='/usr/lib'
make[5]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/libcharset'
cd lib && make install prefix='/usr' exec_prefix='/usr' libdir='/usr/lib'
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/libcharset/lib'
/bin/sh ../build-aux/mkinstalldirs /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib
/bin/sh ../libtool --mode=install /usr/bin/install -c -m 644 libcharset.la /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.la
/usr/bin/install -c -m 644 .libs/libcharset.so.1.0.0 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.so.1.0.0
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib && { ln -s -f libcharset.so.1.0.0 libcharset.so.1 || { rm -f libcharset.so.1 && ln -s libcharset.so.1.0.0 libcharset.so.1; }; })
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib && { ln -s -f libcharset.so.1.0.0 libcharset.so || { rm -f libcharset.so && ln -s libcharset.so.1.0.0 libcharset.so; }; })
/usr/bin/install -c -m 644 .libs/libcharset.lai /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.la
/usr/bin/install -c -m 644 .libs/libcharset.a /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.a
chmod 644 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.a
mips-openwrt-linux-musl-gcc-ranlib /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libcharset.a
OpenWrt-libtool-patched-1.5: install: warning: remember to run `libtool --finish /usr/lib'
if test -f /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/charset.alias; then \
  sed -f ref-add.sed /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/charset.alias > /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias; \
  /usr/bin/install -c -m 644 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/charset.alias; \
  rm -f /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias; \
else \
  if test no = no; then \
    sed -f ref-add.sed charset.alias > /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias; \
    /usr/bin/install -c -m 644 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/charset.alias; \
    rm -f /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/t-charset.alias; \
  fi ; \
fi
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/libcharset/lib'
/bin/sh ./build-aux/mkinstalldirs /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/include
/usr/bin/install -c -m 644 include/libcharset.h /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/include/libcharset.h
/usr/bin/install -c -m 644 include/localcharset.h.inst /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/include/localcharset.h
make[5]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/libcharset'
cd lib && make install prefix='/usr' exec_prefix='/usr' libdir='/usr/lib'
make[5]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/lib'
if [ ! -d /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr ] ; then /bin/sh ../build-aux/mkinstalldirs /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr ; fi
if [ ! -d /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr ] ; then /bin/sh ../build-aux/mkinstalldirs /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr ; fi
if [ ! -d /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib ] ; then /bin/sh ../build-aux/mkinstalldirs /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib ; fi
/bin/sh ../libtool --mode=install /usr/bin/install -c -m 644 libiconv.la /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.la
/usr/bin/install -c -m 644 .libs/libiconv.so.2.4.0 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.so.2.4.0
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib && { ln -s -f libiconv.so.2.4.0 libiconv.so.2 || { rm -f libiconv.so.2 && ln -s libiconv.so.2.4.0 libiconv.so.2; }; })
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib && { ln -s -f libiconv.so.2.4.0 libiconv.so || { rm -f libiconv.so && ln -s libiconv.so.2.4.0 libiconv.so; }; })
/usr/bin/install -c -m 644 .libs/libiconv.lai /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.la
/usr/bin/install -c -m 644 .libs/libiconv.a /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.a
chmod 644 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.a
mips-openwrt-linux-musl-gcc-ranlib /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/libiconv.a
OpenWrt-libtool-patched-1.5: install: warning: remember to run `libtool --finish /usr/lib'
if test -n "preloadable_libiconv.so"; then /usr/bin/install -c -m 644 preloadable_libiconv.so /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/preloadable_libiconv.so.new && mv /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/preloadable_libiconv.so.new /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/ipkg-install/usr/lib/preloadable_libiconv.so ; fi
make[5]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/lib'
cd srclib && make install prefix='/usr' exec_prefix='/usr' libdir='/usr/lib'
make[5]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/srclib'
cd .. && make  am--refresh
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[6]: Nothing to be done for 'am--refresh'.
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[6]: Nothing to be done for 'am--refresh'.
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
cd .. && make  am--refresh
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[6]: Nothing to be done for 'am--refresh'.
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make  install-am
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/srclib'
cd .. && make  am--refresh
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[7]: Nothing to be done for 'am--refresh'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[7]: Nothing to be done for 'am--refresh'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
cd .. && make  am--refresh
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
make[7]: Nothing to be done for 'am--refresh'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
mips-openwrt-linux-musl-gcc -DEXEEXT=\"\" -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1 -DHAVE_CONFIG_H -I. -I. -I.. -I../lib -I. -I.  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include   -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -fpic -DUSE_DOS  -c allocsa.c
In file included from /magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:26:0,
                 from allocsa.h:24,
                 from allocsa.c:24:
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:34:13: error: 'realpath' undeclared here (not in a function)
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
             ^
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/fortify-headers.h:20:40: note: in definition of macro '_FORTIFY_ORIG'
 #define _FORTIFY_ORIG(p,fn) __typeof__(fn) __orig_##fn __asm__(_FORTIFY_STR(p) #fn)
                                        ^
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:34:1: note: in expansion of macro '_FORTIFY_FN'
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
 ^
In file included from allocsa.h:24:0,
                 from allocsa.c:24:
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h: In function 'realpath':
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:47:24: error: called object '__orig_realpath' is not a function or function pointer
  return __orig_realpath(__p, __r);
                        ^
In file included from /magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:26:0,
                 from allocsa.h:24,
                 from allocsa.c:24:
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/fortify-headers.h:20:44: note: declared here
 #define _FORTIFY_ORIG(p,fn) __typeof__(fn) __orig_##fn __asm__(_FORTIFY_STR(p) #fn)
                                            ^
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/fortify-headers.h:21:25: note: in expansion of macro '_FORTIFY_ORIG'
 #define _FORTIFY_FN(fn) _FORTIFY_ORIG(__USER_LABEL_PREFIX__,fn); \
                         ^
/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include/fortify/stdlib.h:34:1: note: in expansion of macro '_FORTIFY_FN'
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
 ^
Makefile:426: recipe for target 'allocsa.o' failed
make[6]: *** [allocsa.o] Error 1
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/srclib'
Makefile:525: recipe for target 'install' failed
make[5]: *** [install] Error 2
make[5]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/srclib'
Makefile:51: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1'
Makefile:91: recipe for target '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/.built' failed
make[3]: *** [/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/libiconv-1.11.1/.built] Error 2
make[3]: Leaving directory '/magazyn/Pliki/openwrt/trunk/package/libs/libiconv-full'
package/Makefile:191: recipe for target 'package/libs/libiconv-full/compile' failed
make[2]: *** [package/libs/libiconv-full/compile] Error 2
make[2]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
package/Makefile:188: recipe for target '/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/stamp/.package_compile' failed
make[1]: *** [/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
/magazyn/Pliki/openwrt/trunk/include/toplevel.mk:181: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2
[05:09:32] slawek@slawek-ubuntu:/magazyn/Pliki/openwrt/trunk$ ~~~

latest https://dev.openwrt.org/changeset/46117 conflicting from build libiconv-full

**Comment by jow-** [comment]
libiconv-full is not part of this repository
