### ISSUE TITLE
openssh-sftp-server explicit_bzero: symbol not found

### ISSUE THREAD

**Issue by timnis** [openwrt/packages#14570]
Maintainer: @tripolar  
Environment: mips_24kc, Teltonika TRB255, OpenWrt 19.07.4 r11208-ce6496d796

Description:

I trying to use SFTP with Teltonika TRB255 (mips_24kc)  and with latest firmware (which is OpenWRT 19.07) but it won't work anymore. It have worked on previous firmware which is based on OpenWRT 18.06.

Steps what I have done.
1. installed openssh-sftp-server (opkg install openssh-sftp-server)
2. tried to connect with SFTP client, but failed (WinSCP gives error "Cannot initialize SFTP protocol. Is the host running an SFTP server?")

One thing what I noticed, if I try to run command sftp-server on router I get following error
```
BusyBox v1.30.1 () built-in shell (ash)

   ____        _    ___  ____
  |  _ \ _   _| |_ / _ \/ ___|
  | |_) | | | | __| | | \___ \
  |  _ <| |_| | |_| |_| |___) |
  |_| \_\\__,_|\__|\___/|____/

 ---------------------------------
   Teltonika TRB2 series 2021
 ---------------------------------
root@Teltonika-TRB255:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.4'
DISTRIB_REVISION='r11208-ce6496d796'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.4 r11208-ce6496d796'
DISTRIB_TAINTS='no-all busybox'
root@Teltonika-TRB255:~#
root@Teltonika-TRB255:~#
root@Teltonika-TRB255:~# /usr/libexec/sftp-server
Error relocating /usr/libexec/sftp-server: explicit_bzero: symbol not found
root@Teltonika-TRB255:~#
```
Other user is asked same from Teltonikas forum, but they don't support 3rd packages
https://community.teltonika-networks.com/27122/rutx11-fw-rutx_r_00-02-06-openssh-sftp-server-not-working

Also I have same problem with another Teltonikas device RUTX11
```
BusyBox v1.30.1 () built-in shell (ash)

   ____        _    ___  ____
  |  _ \ _   _| |_ / _ \/ ___|
  | |_) | | | | __| | | \___ \
  |  _ <| |_| | |_| |_| |___) |
  |_| \_\\__,_|\__|\___/|____/

 ---------------------------------
   Teltonika RUTX series 2021
 ---------------------------------
root@Teltonika-RUTX11:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.4'
DISTRIB_REVISION='r11208-ce6496d796'
DISTRIB_TARGET='ipq40xx/generic'
DISTRIB_ARCH='arm_cortex-a7_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt 19.07.4 r11208-ce6496d796'
DISTRIB_TAINTS='no-all busybox'
root@Teltonika-RUTX11:~#
root@Teltonika-RUTX11:~#
root@Teltonika-RUTX11:~# /usr/libexec/sftp-server
Error relocating /usr/libexec/sftp-server: explicit_bzero: symbol not found
root@Teltonika-RUTX11:~#
```
Any ideas what is the problem?

**Comment by plntyk** [comment]
Vanilla (unmodified) OpenWrt itself does not support these devices (until now)

Teltonika has a custom OpenWrt fork and many devices are not added to unmodified OpenWrt

explizit_bzero is used by OpenSSH in various parts

analyzing [Teltonika GPL drop](https://wiki.teltonika-networks.com/view/GPL): musl 1.1.19 is used, it does not provide explicit_bzero 
(commit: http://git.musl-libc.org/cgit/musl/commit/?id=05ac345f895098657cf44d419b5d572161ebaf43 introduced it); musl 1.1.20 does provide it (if BSD_Source)

compilation/linking of that package is problematic (explicit_bzero detection / fixing varies between packages)
some entries in logs/ in Teltonika drop suggest its detected and some state its not available

Suggested fixes:
- add Teltonika support to vanilla OpenWrt and use it OpenWrt images
- compile openssh-sftp-server with the [Teltonika supplied SDK](https://wiki.teltonika-networks.com/view/GPL) package (GPL drop)
- explicit_bzero can be provided by libbsd0 package dunno if installing it will fix it

ref: issue in teltonic forum ["no support for 3rd party"](https://community.teltonika-networks.com/27122/rutx11-fw-rutx_r_00-02-06-openssh-sftp-server-not-working)
