### ISSUE TITLE
mtr no longer compiles after update (musl)

### ISSUE THREAD

**Issue by Himan2001** [openwrt/packages#1459]
mtr does no longer compile after the last change with musl.
I have problems to compile musl with DISABLED ipv6 on openwrt
there is a problem in net.c with some variables sockaddr_in6

**Comment by Himan2001** [comment]
Can you revert the last commit ? the old 0.78 version still works with musl

**Comment by jow-** [comment]
Already fixed with 54e6887881080011febf19ae3677cd0fbec18eb8
