### ISSUE TITLE
kmod-mmc_4.14.180-1 on vocore2(ramips-mt76x8) with openwrt 19.07.3 don't read micro sd card

### ISSUE THREAD

**Issue by QSDDS** [openwrt/packages#14615]
kmod-mmc_4.14.180-1_mipsel_24kc.ipk
https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt76x8/packages/kmod-mmc_4.14.180-1_mipsel_24kc.ipk

# vocore2 - ramips - mt76x8 - mipsel_24kc - firmware version openwrt 19.07.3 based
Don't read micro sd card.

**Comment by BKPepe** [comment]
This issue does not belongs to packages repository. if you would like to get help, you should use [OpenWrt forum](https://forum.openwrt.org/).
