### ISSUE TITLE
zmq: multiple issues

### ISSUE THREAD

**Issue by jow-** [openwrt/packages#1465]
Commit 3ff4d6dda5072985817fc3df8c689a4cf6e53cfd updated the zeromq version in zmq/Makefile without adjusting the md5sum.

Furthermore that commit introduced the following change in the Makefile:

    ifneq ($(CONFIG_PACKAGE_libsodium),)
      CONFIGURE_ARGS+= --with-libsodium
    else
      CONFIGURE_ARGS+= --without-libsodium
    endif

This is a no-go as it leads to non-deterministic build results. Either unconditionally depend on `+libsodium` and always pass `--with-libsodium` or uncodnitionally disable it with `--without-libsodium` but do not alter the configure args depending on the package selection.

**Comment by jow-** [comment]
@srdgame @thess

**Comment by thess** [comment]
@srdgame - package doesn't build after fixing md5sum.
If you want to have libsodium be optional, we could make 2 variants.

**Comment by srdgame** [comment]
@thess What should I do if i want to keep libsodium as optional?  Is it possible change the condition to detect the selection of "LIBZMQ_CURVEZMQ"?

**Comment by thess** [comment]
I think 2 variant packages would be the best solution. It would be easier for people installing individual pre-built packages rather than forcing someone to do a custom build to choose one over the other.

**Comment by thess** [comment]
See PR #1538 for proposed solution to these issues.

**Comment by thess** [comment]
Closed by #1538
