### ISSUE TITLE
odhcpd: doesn't set M flag nor O flag in router advertisment when using isc-dhcp-server-ipv6

### ISSUE THREAD

**Issue by eltorio** [openwrt/packages#14675]
Hi,
On OpenWRT 19.07.6
I 'd like to use isc bind9 and dhcp server for both ipv4 and ipv6 (for having advanced features) in replacement of dnsmasq/odhcpd
I remove dnsmasq but let odhcpd because radvd is not available in current version
 I config my /etc/config/dhcp like this
```
config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option ra 'server'
        option ra_mininterval '1'
        option ra_maxinterval '20'
        option ra_management '2'
```

but odhcpd does not set M flag nor O flag
I tried to add option ignore '1' without success
This is a Wireshark capture
![Capture d’écran 2021-02-06 185047](https://user-images.githubusercontent.com/6966689/107125841-6dc19980-68ac-11eb-94b9-bc932244974c.jpg)

**Comment by PolynomialDivision** [comment]
I think odhpcd is part of the core and not the packages feed. You should bug report here: https://bugs.openwrt.org/

**Comment by eltorio** [comment]
> I think odhpcd is part of the core and not the packages feed. You should bug report here: https://bugs.openwrt.org/

Thanks for your help, you're probably right so I create a new task in the base system:
[https://bugs.openwrt.org/index.php?do=details&task_id=3609](url)
