### ISSUE TITLE
gcc: missing link from gcc to cc

### ISSUE THREAD

**Issue by flyn-org** [openwrt/packages#14755]
Maintainer: @noblepepper 
Environment: x86_64 master

Description:
The gcc package does not create a symbolic link from /usr/bin/gcc to /usr/bin/cc. This breaks some Makefiles that use $(CC), as GNU make sets CC to cc by default. I think POSIX required the presence of cc as some point.

**Comment by pprindeville** [comment]
Why not just pass `CC=gcc make ...` into those packages?

**Comment by plntyk** [comment]
for reference: 

[CC in Single Unix v2](https://pubs.opengroup.org/onlinepubs/7908799/xcu/cc.html) - marked Legacy
[C99 in Single Unix v4](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html) - no CC

via [stackexchange](https://unix.stackexchange.com/questions/378890/does-posix-mention-cc-or-only-c99)

with CC: Debian, Arch; FreeBSD
no CC: Fedora

personally I dont use gcc on OpenWrt anyway - feel free to reject

**Comment by flyn-org** [comment]
@pprindeville, `CC=gcc make` would work, but requires an explicit action. I use OpenWrt to host a build service of sorts, and my use case benefits from the cc symbolic link. Symbolic links are cheap, so I thought this would be an acceptable change. I agree with @plntyk that it is unclear if cc is actually required by POSIX or The Single Unix Specification (does the legacy designation mean that C < C99 is legacy or the requirement for cc is legacy?). Moreover, I am not sure OpenWrt presumes to implement either (e.g., does busybox drop some requirements?). All of that said, the make we ship sets CC to cc, so I think our gcc package should provide the same.
