### ISSUE TITLE
Tor 0.4.5.6 won't build without OpenSSL engine support.

### ISSUE THREAD

**Issue by rsalvaterra** [openwrt/packages#14827]
$subj. Applies to both variants, of course. Tested on master. Let me know if additional info is needed.

**Comment by BKPepe** [comment]
@ja-pa can you take a look? :)

**Comment by ja-pa** [comment]
There is experimental support of NSS. So I can try to add it to custom build.

**Comment by rsalvaterra** [comment]
Well, that depends… If we depend from OpenSSL for other reasons, Tor + NSS will probably increase the size more than compiling OpenSSL with engine support, right?

**Comment by The-BB** [comment]
```
ifneq ($(OPENSSL_ENGINE),y)
TARGET_CFLAGS += -DDISABLE_ENGINES
endif
```

**Comment by rsalvaterra** [comment]
> ```
> ifneq ($(OPENSSL_ENGINE),y)
> TARGET_CFLAGS += -DDISABLE_ENGINES
> endif
> ```

This does indeed fix it. @BKPepe, mind if I send a pull?
