### ISSUE TITLE
[19.07]https-dns-proxy and mwan3 have compatibility issues, and DNS forwarding cannot be resolved!

### ISSUE THREAD

**Issue by openwrt-diy** [openwrt/packages#14840]
@feckert @aaronjg @jamesmacwhite @brianjmurrell @stangri @aparcar

Environment: x86
openwrt version: 19.07.7
mwan3 version: 2.8.15-1
https-dns-proxy: 2021-01-17-1

Description:
When mwan3 or https-dns-proxy is used separately, the routing network is normal!

When using https-dns-proxy and mwan3 at the same time, when the router WAN and other interfaces are normally online, the LAN interface (including PPPoE dial-up terminal) can access the Internet normally!

When the WAN interface is disconnected, the other WANB, WANC, and WAND interfaces are all online normally! At this time, all users under all LAN interfaces (including PPPoE dial-up terminals) cannot access the Internet! The browser web page prompts that DNS resolution cannot be obtained

**Comment by stangri** [comment]
Is https (port 443) traffic allowed under WANB/WANC/WAND?

If you want more qualified help (from others, this is the extent of what I can suggest), you need to post configs for both packages, as well as dhcp/network/firewall configs.

**Comment by openwrt-diy** [comment]
**The following is a screenshot of the online network**

![001MWAN Interfaces](https://user-images.githubusercontent.com/57249132/108806316-3878a500-7556-11eb-8af2-4beef4ddd6d1.png)
![003MWAN - Rules](https://user-images.githubusercontent.com/57249132/108806330-429aa380-7556-11eb-8e00-c2c70d915aa7.png)
![002DNS HTTPS Proxy](https://user-images.githubusercontent.com/57249132/108806344-4af2de80-7556-11eb-916c-37f253803451.png)
![004Firewall - Port Forwards](https://user-images.githubusercontent.com/57249132/108806350-4fb79280-7556-11eb-9030-5fe91784688f.png)

**Comment by openwrt-diy** [comment]
The following is a screenshot of the network DNS forwarding failure after the WAN interface is offline.

![005MWAN Interfaces](https://user-images.githubusercontent.com/57249132/108807407-32d08e80-7559-11eb-9831-22eba9365798.png)

**Comment by openwrt-diy** [comment]
/$ uci show https-dns-proxy
https-dns-proxy.config=main
https-dns-proxy.config.update_dnsmasq_config='-'
https-dns-proxy.@https-dns-proxy[0]=https-dns-proxy
https-dns-proxy.@https-dns-proxy[0].bootstrap_dns='223.5.5.5,223.6.6.6,2400:3200::1,2400:3200:baba::1'
https-dns-proxy.@https-dns-proxy[0].resolver_url='https://dns.alidns.com/dns-query'
https-dns-proxy.@https-dns-proxy[0].listen_addr='0.0.0.0'
https-dns-proxy.@https-dns-proxy[0].listen_port='5053'
https-dns-proxy.@https-dns-proxy[1]=https-dns-proxy
https-dns-proxy.@https-dns-proxy[1].bootstrap_dns='119.29.29.29,119.28.28.28'
https-dns-proxy.@https-dns-proxy[1].resolver_url='https://doh.pub/dns-query'
https-dns-proxy.@https-dns-proxy[1].listen_addr='0.0.0.0'
https-dns-proxy.@https-dns-proxy[1].listen_port='5054'
https-dns-proxy.@https-dns-proxy[2]=https-dns-proxy
https-dns-proxy.@https-dns-proxy[2].bootstrap_dns='1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001'
https-dns-proxy.@https-dns-proxy[2].resolver_url='https://cloudflare-dns.com/dns-query'
https-dns-proxy.@https-dns-proxy[2].listen_addr='0.0.0.0'
https-dns-proxy.@https-dns-proxy[2].listen_port='5055'
https-dns-proxy.@https-dns-proxy[3]=https-dns-proxy
https-dns-proxy.@https-dns-proxy[3].bootstrap_dns='8.8.8.8,8.8.4.4'
https-dns-proxy.@https-dns-proxy[3].resolver_url='https://dns.google/dns-query'
https-dns-proxy.@https-dns-proxy[3].listen_addr='0.0.0.0'
https-dns-proxy.@https-dns-proxy[3].listen_port='5056'



/$ uci show firewall
firewall.@defaults[0]=defaults
firewall.@defaults[0].synflood_protect='1'
firewall.@defaults[0].input='ACCEPT'
firewall.@defaults[0].output='ACCEPT'
firewall.@defaults[0].forward='REJECT'
firewall.@zone[0]=zone
firewall.@zone[0].name='lan'
firewall.@zone[0].network='lan'
firewall.@zone[0].input='ACCEPT'
firewall.@zone[0].output='ACCEPT'
firewall.@zone[0].forward='ACCEPT'
firewall.@zone[0].device='ppp0' 'ppp1' 'ppp2' 'ppp3' 'ppp4' 'ppp5' 'ppp6' 'ppp7' 'ppp8' 'ppp9' 'ppp10' 'ppp11' 'ppp12' 'ppp13' 'ppp14' 'ppp15' 'ppp16' 'ppp17' 'ppp18' 'ppp19' 'ppp20' 'ppp21' 'ppp22' 'ppp23' 'ppp24' 'ppp25' 'ppp26' 'ppp27' 'ppp28' 'ppp29' 'ppp30' 'ppp31' 

'ppp32' 'ppp33' 'ppp34' 'ppp35' 'ppp36' 'ppp37' 'ppp38' 'ppp39' 'ppp40' 'ppp41' 'ppp42' 'ppp43' 'ppp44' 'ppp45' 'ppp46' 'ppp47' 'ppp48' 'ppp49' 'ppp50' 'ppp51' 'ppp52' 'ppp53' 'ppp54' 'ppp55' 'ppp56' 'ppp57' 'ppp58' 'ppp59' 'ppp60' 'ppp61' 'ppp62' 'ppp63' 'ppp64' 'ppp65' 

'ppp66' 'ppp67' 'ppp68' 'ppp69' 'ppp70' 'ppp71' 'ppp72' 'ppp73' 'ppp74' 'ppp75' 'ppp76' 'ppp77' 'ppp78' 'ppp79' 'ppp80' 'ppp81' 'ppp82' 'ppp83' 'ppp84' 'ppp85' 'ppp86' 'ppp87' 'ppp88' 'ppp89' 'ppp90' 'ppp91' 'ppp92' 'ppp93' 'ppp94' 'ppp95' 'ppp96' 'ppp97' 'ppp98' 'ppp99' 

'ppp100' 'ppp101' 'ppp102' 'ppp103' 'ppp104' 'ppp105' 'ppp106' 'ppp107' 'ppp108' 'ppp109' 'ppp110' 'ppp111' 'ppp112' 'ppp113' 'ppp114' 'ppp115' 'ppp116' 'ppp117' 'ppp118' 'ppp119' 'ppp120' 'ppp121' 'ppp122' 'ppp123' 'ppp124' 'ppp125' 'ppp126' 'ppp127' 'ppp128' 'ppp129' 

'ppp130' 'ppp131' 'ppp132' 'ppp133' 'ppp134' 'ppp135' 'ppp136' 'ppp137' 'ppp138' 'ppp139' 'ppp140' 'ppp141' 'ppp142' 'ppp143' 'ppp144' 'ppp145' 'ppp146' 'ppp147' 'ppp148' 'ppp149' 'ppp150' 'ppp151' 'ppp152' 'ppp153' 'ppp154' 'ppp155' 'ppp156' 'ppp157' 'ppp158' 'ppp159' 

'ppp160' 'ppp161' 'ppp162' 'ppp163' 'ppp164' 'ppp165' 'ppp166' 'ppp167' 'ppp168' 'ppp169' 'ppp170' 'ppp171' 'ppp172' 'ppp173' 'ppp174' 'ppp175' 'ppp176' 'ppp177' 'ppp178' 'ppp179' 'ppp180' 'ppp181' 'ppp182' 'ppp183' 'ppp184' 'ppp185' 'ppp186' 'ppp187' 'ppp188' 'ppp189' 

'ppp190' 'ppp191' 'ppp192' 'ppp193' 'ppp194' 'ppp195' 'ppp196' 'ppp197' 'ppp198' 'ppp199' 'ppp200' 'ppp201' 'ppp202' 'ppp203' 'ppp204' 'ppp205' 'ppp206' 'ppp207' 'ppp208' 'ppp209' 'ppp210' 'ppp211' 'ppp212' 'ppp213' 'ppp214' 'ppp215' 'ppp216' 'ppp217' 'ppp218' 'ppp219' 

'ppp220' 'ppp221' 'ppp222' 'ppp223' 'ppp224' 'ppp225' 'ppp226' 'ppp227' 'ppp228' 'ppp229' 'ppp230' 'ppp231' 'ppp232' 'ppp233' 'ppp234' 'ppp235' 'ppp236' 'ppp237' 'ppp238' 'ppp239' 'ppp240' 'ppp241' 'ppp242' 'ppp243' 'ppp244' 'ppp245' 'ppp246' 'ppp247' 'ppp248' 'ppp249' 

'ppp250' 'ppp251' 'ppp252' 'ppp253' 'ppp254'
firewall.@zone[1]=zone
firewall.@zone[1].name='wan'
firewall.@zone[1].network='wan' 'wanb' 'wanc' 'wand'
firewall.@zone[1].input='REJECT'
firewall.@zone[1].output='ACCEPT'
firewall.@zone[1].forward='REJECT'
firewall.@zone[1].masq='1'
firewall.@zone[1].mtu_fix='1'
firewall.@forwarding[0]=forwarding
firewall.@forwarding[0].src='lan'
firewall.@forwarding[0].dest='wan'
firewall.@rule[0]=rule
firewall.@rule[0].name='Allow-DHCP-Renew'
firewall.@rule[0].src='wan'
firewall.@rule[0].proto='udp'
firewall.@rule[0].dest_port='68'
firewall.@rule[0].target='ACCEPT'
firewall.@rule[0].family='ipv4'
firewall.@rule[1]=rule
firewall.@rule[1].name='Allow-Ping'
firewall.@rule[1].src='*'
firewall.@rule[1].proto='icmp'
firewall.@rule[1].icmp_type='echo-request'
firewall.@rule[1].family='ipv4'
firewall.@rule[1].target='DROP'
firewall.@rule[2]=rule
firewall.@rule[2].name='Allow-IGMP'
firewall.@rule[2].src='wan'
firewall.@rule[2].proto='igmp'
firewall.@rule[2].family='ipv4'
firewall.@rule[2].target='ACCEPT'
firewall.@rule[3]=rule
firewall.@rule[3].name='Allow-DHCPv6'
firewall.@rule[3].src='wan'
firewall.@rule[3].proto='udp'
firewall.@rule[3].src_ip='fc00::/6'
firewall.@rule[3].dest_ip='fc00::/6'
firewall.@rule[3].dest_port='546'
firewall.@rule[3].family='ipv6'
firewall.@rule[3].target='ACCEPT'
firewall.@rule[4]=rule
firewall.@rule[4].name='Allow-MLD'
firewall.@rule[4].src='wan'
firewall.@rule[4].proto='icmp'
firewall.@rule[4].src_ip='fe80::/10'
firewall.@rule[4].family='ipv6'
firewall.@rule[4].target='ACCEPT'
firewall.@rule[5]=rule
firewall.@rule[5].name='Allow-ICMPv6-Input'
firewall.@rule[5].src='wan'
firewall.@rule[5].proto='icmp'
firewall.@rule[5].icmp_type='destination-unreachable' 'echo-reply' 'echo-request' 'neighbour-advertisement' 'neighbour-solicitation' 'packet-too-big' 'router-advertisement' 'router-solicitation' 'time-exceeded'
firewall.@rule[5].limit='1000/sec'
firewall.@rule[5].family='ipv6'
firewall.@rule[5].target='ACCEPT'
firewall.@rule[6]=rule
firewall.@rule[6].name='Allow-ICMPv6-Forward'
firewall.@rule[6].src='wan'
firewall.@rule[6].dest='*'
firewall.@rule[6].proto='icmp'
firewall.@rule[6].icmp_type='destination-unreachable' 'echo-reply' 'echo-request' 'packet-too-big' 'time-exceeded'
firewall.@rule[6].limit='1000/sec'
firewall.@rule[6].family='ipv6'
firewall.@rule[6].target='ACCEPT'
firewall.@rule[7]=rule
firewall.@rule[7].name='Allow-IPSec-ESP'
firewall.@rule[7].src='wan'
firewall.@rule[7].dest='lan'
firewall.@rule[7].proto='esp'
firewall.@rule[7].target='ACCEPT'
firewall.@rule[8]=rule
firewall.@rule[8].name='Allow-ISAKMP'
firewall.@rule[8].src='wan'
firewall.@rule[8].dest='lan'
firewall.@rule[8].dest_port='500'
firewall.@rule[8].proto='udp'
firewall.@rule[8].target='ACCEPT'
firewall.@rule[9]=rule
firewall.@rule[9].name='Support-UDP-Traceroute'
firewall.@rule[9].src='wan'
firewall.@rule[9].dest_port='33434-33689'
firewall.@rule[9].proto='udp'
firewall.@rule[9].family='ipv4'
firewall.@rule[9].target='REJECT'
firewall.@include[0]=include
firewall.@include[0].path='/etc/firewall.user'
firewall.@redirect[0]=redirect
firewall.@redirect[0].name='WAN-DNS'
firewall.@redirect[0].proto='tcp' 'udp'
firewall.@redirect[0].src='lan'
firewall.@redirect[0].src_ip='10.0.1.0/26'
firewall.@redirect[0].src_dport='53'
firewall.@redirect[0].dest='lan'
firewall.@redirect[0].dest_port='5053'
firewall.@redirect[0].target='DNAT'
firewall.@redirect[0].enabled='1'
firewall.@redirect[1]=redirect
firewall.@redirect[1].name='WANB-DNS'
firewall.@redirect[1].proto='tcp' 'udp'
firewall.@redirect[1].src='lan'
firewall.@redirect[1].src_ip='10.0.1.64/26'
firewall.@redirect[1].src_dport='53'
firewall.@redirect[1].dest='lan'
firewall.@redirect[1].dest_port='5054'
firewall.@redirect[1].target='DNAT'
firewall.@redirect[1].enabled='1'
firewall.@redirect[2]=redirect
firewall.@redirect[2].name='WANC-DNS'
firewall.@redirect[2].proto='tcp' 'udp'
firewall.@redirect[2].src='lan'
firewall.@redirect[2].src_ip='10.0.1.128/26'
firewall.@redirect[2].src_dport='53'
firewall.@redirect[2].dest='lan'
firewall.@redirect[2].dest_port='5055'
firewall.@redirect[2].target='DNAT'
firewall.@redirect[2].enabled='1'
firewall.@redirect[3]=redirect
firewall.@redirect[3].name='WAND-DNS'
firewall.@redirect[3].proto='tcp' 'udp'
firewall.@redirect[3].src='lan'
firewall.@redirect[3].src_ip='10.0.1.192/26'
firewall.@redirect[3].src_dport='53'
firewall.@redirect[3].dest='lan'
firewall.@redirect[3].dest_port='5056'
firewall.@redirect[3].target='DNAT'
firewall.@redirect[3].enabled='1'
firewall.@rule[10]=rule
firewall.@rule[10].name='Allow-ZeroTier-Inbound'
firewall.@rule[10].src='*'
firewall.@rule[10].proto='udp'
firewall.@rule[10].dest_port='9993'
firewall.@rule[10].target='ACCEPT'
firewall.@rule[11]=rule
firewall.@rule[11].name='Disable-Access-Gateway'
firewall.@rule[11].proto='tcp' 'udp'
firewall.@rule[11].src='lan'
firewall.@rule[11].src_ip='10.0.1.0/24'
firewall.@rule[11].dest_port='22 80 89 443 8090 2019'
firewall.@rule[11].target='DROP'
firewall.@rule[11].enabled='0'



/$ uci show mwan3
mwan3.globals=globals
mwan3.globals.mmx_mask='0x3F00'
mwan3.globals.rtmon_interval='5'
mwan3.wan=interface
mwan3.wan.enabled='1'
mwan3.wan.initial_state='online'
mwan3.wan.family='ipv4'
mwan3.wan.track_ip='1.1.1.1' '8.8.8.8' '180.76.76.76' '119.29.29.29'
mwan3.wan.track_method='ping'
mwan3.wan.reliability='2'
mwan3.wan.count='2'
mwan3.wan.size='56'
mwan3.wan.max_ttl='60'
mwan3.wan.check_quality='0'
mwan3.wan.timeout='2'
mwan3.wan.interval='5'
mwan3.wan.failure_interval='5'
mwan3.wan.recovery_interval='5'
mwan3.wan.down='3'
mwan3.wan.up='3'
mwan3.wanb=interface
mwan3.wanb.enabled='1'
mwan3.wanb.initial_state='online'
mwan3.wanb.family='ipv4'
mwan3.wanb.track_ip='223.5.5.5' '119.29.29.29' '180.76.76.76' '114.114.114.114'
mwan3.wanb.track_method='ping'
mwan3.wanb.reliability='2'
mwan3.wanb.count='2'
mwan3.wanb.size='56'
mwan3.wanb.max_ttl='60'
mwan3.wanb.check_quality='0'
mwan3.wanb.timeout='2'
mwan3.wanb.interval='5'
mwan3.wanb.failure_interval='5'
mwan3.wanb.recovery_interval='5'
mwan3.wanb.down='3'
mwan3.wanb.up='3'
mwan3.wanc=interface
mwan3.wanc.enabled='1'
mwan3.wanc.initial_state='online'
mwan3.wanc.family='ipv4'
mwan3.wanc.track_ip='223.5.5.5' '119.29.29.29' '180.76.76.76' '114.114.114.114'
mwan3.wanc.track_method='ping'
mwan3.wanc.reliability='2'
mwan3.wanc.count='2'
mwan3.wanc.size='56'
mwan3.wanc.max_ttl='60'
mwan3.wanc.check_quality='0'
mwan3.wanc.timeout='2'
mwan3.wanc.interval='5'
mwan3.wanc.failure_interval='5'
mwan3.wanc.recovery_interval='5'
mwan3.wanc.down='3'
mwan3.wanc.up='3'
mwan3.wand=interface
mwan3.wand.enabled='1'
mwan3.wand.initial_state='online'
mwan3.wand.family='ipv4'
mwan3.wand.track_ip='208.67.222.222' '119.29.29.29' '45.90.28.127' '8.8.8.8' '1.1.1.1' '180.76.76.76'
mwan3.wand.track_method='ping'
mwan3.wand.reliability='2'
mwan3.wand.count='2'
mwan3.wand.size='56'
mwan3.wand.max_ttl='60'
mwan3.wand.check_quality='0'
mwan3.wand.timeout='2'
mwan3.wand.interval='5'
mwan3.wand.failure_interval='5'
mwan3.wand.recovery_interval='5'
mwan3.wand.down='3'
mwan3.wand.up='3'
mwan3.wan6=interface
mwan3.wan6.enabled='0'
mwan3.wan6.initial_state='online'
mwan3.wan6.family='ipv6'
mwan3.wan6.track_ip='2400:3200::1' '2400:3200:baba::1' '2400:da00::6666' 'ipv6.ustb.edu.cn'
mwan3.wan6.track_method='ping'
mwan3.wan6.reliability='2'
mwan3.wan6.count='2'
mwan3.wan6.size='56'
mwan3.wan6.max_ttl='60'
mwan3.wan6.check_quality='0'
mwan3.wan6.timeout='2'
mwan3.wan6.interval='5'
mwan3.wan6.failure_interval='5'
mwan3.wan6.recovery_interval='5'
mwan3.wan6.down='3'
mwan3.wan6.up='3'
mwan3.wanb6=interface
mwan3.wanb6.enabled='0'
mwan3.wanb6.initial_state='online'
mwan3.wanb6.family='ipv6'
mwan3.wanb6.track_ip='2400:3200::1' '2400:3200:baba::1' '2400:da00::6666' 'ipv6.ustb.edu.cn'
mwan3.wanb6.track_method='ping'
mwan3.wanb6.reliability='2'
mwan3.wanb6.count='2'
mwan3.wanb6.size='56'
mwan3.wanb6.max_ttl='60'
mwan3.wanb6.check_quality='0'
mwan3.wanb6.timeout='2'
mwan3.wanb6.interval='5'
mwan3.wanb6.failure_interval='5'
mwan3.wanb6.recovery_interval='5'
mwan3.wanb6.down='3'
mwan3.wanb6.up='3'
mwan3.wanc6=interface
mwan3.wanc6.enabled='0'
mwan3.wanc6.initial_state='online'
mwan3.wanc6.family='ipv6'
mwan3.wanc6.track_ip='2400:3200::1' '2400:3200:baba::1' '2400:da00::6666' 'ipv6.ustb.edu.cn'
mwan3.wanc6.track_method='ping'
mwan3.wanc6.reliability='2'
mwan3.wanc6.count='2'
mwan3.wanc6.size='56'
mwan3.wanc6.max_ttl='60'
mwan3.wanc6.check_quality='0'
mwan3.wanc6.timeout='2'
mwan3.wanc6.interval='5'
mwan3.wanc6.failure_interval='5'
mwan3.wanc6.recovery_interval='5'
mwan3.wanc6.down='3'
mwan3.wanc6.up='3'
mwan3.wand6=interface
mwan3.wand6.enabled='0'
mwan3.wand6.initial_state='online'
mwan3.wand6.family='ipv6'
mwan3.wand6.track_ip='2001:4860:4860::8844' '2001:4860:4860::8888' '2620:0:ccd::2' '2620:0:ccc::2'
mwan3.wand6.track_method='ping'
mwan3.wand6.reliability='2'
mwan3.wand6.count='2'
mwan3.wand6.size='56'
mwan3.wand6.max_ttl='60'
mwan3.wand6.check_quality='0'
mwan3.wand6.timeout='2'
mwan3.wand6.interval='5'
mwan3.wand6.failure_interval='5'
mwan3.wand6.recovery_interval='5'
mwan3.wand6.down='3'
mwan3.wand6.up='3'
mwan3.wan_m1_w9=member
mwan3.wan_m1_w9.interface='wan'
mwan3.wan_m1_w9.metric='1'
mwan3.wan_m1_w9.weight='9'
mwan3.wan_m2_w9=member
mwan3.wan_m2_w9.interface='wan'
mwan3.wan_m2_w9.metric='2'
mwan3.wan_m2_w9.weight='9'
mwan3.wan_m3_w1=member
mwan3.wan_m3_w1.interface='wan'
mwan3.wan_m3_w1.metric='3'
mwan3.wan_m3_w1.weight='1'
mwan3.wanb_m1_w8=member
mwan3.wanb_m1_w8.interface='wanb'
mwan3.wanb_m1_w8.metric='1'
mwan3.wanb_m1_w8.weight='8'
mwan3.wanb_m2_w8=member
mwan3.wanb_m2_w8.interface='wanb'
mwan3.wanb_m2_w8.metric='2'
mwan3.wanb_m2_w8.weight='8'
mwan3.wanb_m3_w1=member
mwan3.wanb_m3_w1.interface='wanb'
mwan3.wanb_m3_w1.metric='3'
mwan3.wanb_m3_w1.weight='1'
mwan3.wanc_m1_w7=member
mwan3.wanc_m1_w7.interface='wanc'
mwan3.wanc_m1_w7.metric='1'
mwan3.wanc_m1_w7.weight='7'
mwan3.wanc_m2_w7=member
mwan3.wanc_m2_w7.interface='wanc'
mwan3.wanc_m2_w7.metric='2'
mwan3.wanc_m2_w7.weight='7'
mwan3.wanc_m3_w1=member
mwan3.wanc_m3_w1.interface='wanc'
mwan3.wanc_m3_w1.metric='3'
mwan3.wanc_m3_w1.weight='1'
mwan3.wand_m1_w6=member
mwan3.wand_m1_w6.interface='wand'
mwan3.wand_m1_w6.metric='1'
mwan3.wand_m1_w6.weight='6'
mwan3.wand_m2_w6=member
mwan3.wand_m2_w6.interface='wand'
mwan3.wand_m2_w6.metric='2'
mwan3.wand_m2_w6.weight='6'
mwan3.wand_m3_w1=member
mwan3.wand_m3_w1.interface='wand'
mwan3.wand_m3_w1.metric='3'
mwan3.wand_m3_w1.weight='1'
mwan3.wan6_m1_w9=member
mwan3.wan6_m1_w9.interface='wan6'
mwan3.wan6_m1_w9.metric='1'
mwan3.wan6_m1_w9.weight='9'
mwan3.wan6_m2_w9=member
mwan3.wan6_m2_w9.interface='wan6'
mwan3.wan6_m2_w9.metric='2'
mwan3.wan6_m2_w9.weight='9'
mwan3.wan6_m3_w1=member
mwan3.wan6_m3_w1.interface='wan6'
mwan3.wan6_m3_w1.metric='3'
mwan3.wan6_m3_w1.weight='1'
mwan3.wanb6_m1_w8=member
mwan3.wanb6_m1_w8.interface='wanb6'
mwan3.wanb6_m1_w8.metric='1'
mwan3.wanb6_m1_w8.weight='8'
mwan3.wanb6_m2_w8=member
mwan3.wanb6_m2_w8.interface='wanb6'
mwan3.wanb6_m2_w8.metric='2'
mwan3.wanb6_m2_w8.weight='8'
mwan3.wanb6_m3_w1=member
mwan3.wanb6_m3_w1.interface='wanb6'
mwan3.wanb6_m3_w1.metric='3'
mwan3.wanb6_m3_w1.weight='1'
mwan3.wanc6_m1_w7=member
mwan3.wanc6_m1_w7.interface='wanc6'
mwan3.wanc6_m1_w7.metric='1'
mwan3.wanc6_m1_w7.weight='7'
mwan3.wanc6_m2_w7=member
mwan3.wanc6_m2_w7.interface='wanc6'
mwan3.wanc6_m2_w7.metric='2'
mwan3.wanc6_m2_w7.weight='7'
mwan3.wanc6_m3_w1=member
mwan3.wanc6_m3_w1.interface='wanc6'
mwan3.wanc6_m3_w1.metric='3'
mwan3.wanc6_m3_w1.weight='1'
mwan3.wand6_m1_w6=member
mwan3.wand6_m1_w6.interface='wand6'
mwan3.wand6_m1_w6.metric='1'
mwan3.wand6_m1_w6.weight='6'
mwan3.wand6_m2_w6=member
mwan3.wand6_m2_w6.interface='wand6'
mwan3.wand6_m2_w6.metric='2'
mwan3.wand6_m2_w6.weight='6'
mwan3.wand6_m3_w1=member
mwan3.wand6_m3_w1.interface='wand6'
mwan3.wand6_m3_w1.metric='3'
mwan3.wand6_m3_w1.weight='1'
mwan3.wan_only=policy
mwan3.wan_only.use_member='wan_m1_w9' 'wan6_m1_w9'
mwan3.wan_only.last_resort='unreachable'
mwan3.wanb_only=policy
mwan3.wanb_only.use_member='wanb_m1_w8' 'wanb6_m1_w8'
mwan3.wanb_only.last_resort='unreachable'
mwan3.wanc_only=policy
mwan3.wanc_only.use_member='wanc_m1_w7' 'wanc6_m1_w7'
mwan3.wanc_only.last_resort='unreachable'
mwan3.wand_only=policy
mwan3.wand_only.use_member='wand_m1_w6' 'wand6_m1_w6'
mwan3.wand_only.last_resort='unreachable'
mwan3.wan_wanb=policy
mwan3.wan_wanb.use_member='wan_m1_w9' 'wanb_m2_w8' 'wan6_m1_w9' 'wanb6_m2_w8'
mwan3.wan_wanb.last_resort='unreachable'
mwan3.wan_wanc=policy
mwan3.wan_wanc.use_member='wan_m1_w9' 'wanc_m2_w7' 'wan6_m1_w9' 'wanc6_m2_w7'
mwan3.wan_wanc.last_resort='unreachable'
mwan3.wan_wand=policy
mwan3.wan_wand.use_member='wan_m1_w9' 'wand_m2_w6' 'wan6_m1_w9' 'wand6_m2_w6'
mwan3.wan_wand.last_resort='unreachable'
mwan3.wanb_wan=policy
mwan3.wanb_wan.use_member='wanb_m1_w8' 'wan_m2_w9' 'wanb6_m1_w8' 'wan6_m2_w9'
mwan3.wanb_wan.last_resort='unreachable'
mwan3.wanb_wanc=policy
mwan3.wanb_wanc.use_member='wanb_m1_w8' 'wanc_m2_w7' 'wanb6_m1_w8' 'wanc6_m2_w7'
mwan3.wanb_wanc.last_resort='unreachable'
mwan3.wanb_wand=policy
mwan3.wanb_wand.use_member='wanb_m1_w8' 'wand_m2_w6' 'wanb6_m1_w8' 'wand6_m2_w6'
mwan3.wanb_wand.last_resort='unreachable'
mwan3.wanc_wan=policy
mwan3.wanc_wan.use_member='wanc_m1_w7' 'wan_m2_w9' 'wanc6_m1_w7' 'wan6_m2_w9'
mwan3.wanc_wan.last_resort='unreachable'
mwan3.wanc_wanb=policy
mwan3.wanc_wanb.use_member='wanc_m1_w7' 'wanb_m2_w8' 'wanc6_m1_w7' 'wanb6_m2_w8'
mwan3.wanc_wanb.last_resort='unreachable'
mwan3.wanc_wand=policy
mwan3.wanc_wand.use_member='wanc_m1_w7' 'wand_m2_w6' 'wanc6_m1_w7' 'wand6_m2_w6'
mwan3.wanc_wand.last_resort='unreachable'
mwan3.wand_wan=policy
mwan3.wand_wan.use_member='wand_m1_w6' 'wan_m2_w9' 'wand6_m1_w6' 'wan6_m2_w9'
mwan3.wand_wan.last_resort='unreachable'
mwan3.wand_wanb=policy
mwan3.wand_wanb.use_member='wand_m1_w6' 'wanb_m2_w8' 'wand6_m1_w6' 'wanb6_m2_w8'
mwan3.wand_wanb.last_resort='unreachable'
mwan3.wand_wanc=policy
mwan3.wand_wanc.use_member='wand_m1_w6' 'wanc_m2_w7' 'wand6_m1_w6' 'wanc6_m2_w7'
mwan3.wand_wanc.last_resort='unreachable'
mwan3.ip_1_62=rule
mwan3.ip_1_62.proto='all'
mwan3.ip_1_62.src_ip='10.0.1.0/26'
mwan3.ip_1_62.sticky='1'
mwan3.ip_1_62.use_policy='wan_only'
mwan3.ip_65_126=rule
mwan3.ip_65_126.proto='all'
mwan3.ip_65_126.src_ip='10.0.1.64/26'
mwan3.ip_65_126.sticky='1'
mwan3.ip_65_126.use_policy='wanb_only'
mwan3.ip_129_190=rule
mwan3.ip_129_190.proto='all'
mwan3.ip_129_190.src_ip='10.0.1.128/26'
mwan3.ip_129_190.sticky='1'
mwan3.ip_129_190.use_policy='wanc_only'
mwan3.ip_193_254=rule
mwan3.ip_193_254.proto='all'
mwan3.ip_193_254.src_ip='10.0.1.192/26'
mwan3.ip_193_254.sticky='1'
mwan3.ip_193_254.use_policy='wand_only'
