### ISSUE TITLE
Question about PKG_RELEASE

### ISSUE THREAD

**Issue by thess** [openwrt/packages#149]
I think I understand the "rules" for changing the PKG_RELEASE var in the package Makefile. Here is what I am using as of now:
- Increment PKG_RELEASE if the OpenWRT package Makefile is modified (build/install changes) but the upstream (PKG_VERSION) is not.
- Do not increment PKG_RELEASE if only changing non-build related stuff (Copyright, license, etc.)
- Reset PKG_RELEASE to 1 when upgrading the component version (PKG_VERSION).

My question is - Is there any other package changes that should cause the PKG_VERSION to be incremented? For example: Changes to additional "files" or patches?

**Comment by efahl** [comment]
Nothing like posting on 100-year-old issues, but...

I made this addition to https://openwrt.org/docs/guide-developer/packages#buildpackage_variables a while back, not knowing about this issue.  Sound ok to all?

* ''PKG_RELEASE''     - The version of this package Makefile.  Should be initially set to 1, and reset to 1 whenever the ''PKG_VERSION'' is changed.  Increment it when ''PKG_VERSION'' stays the same, but when there are functional changes to the installed artifacts.

**Comment by thess** [comment]
AFAIK
