### ISSUE TITLE
strongswan: gmpdh can't be built with static flags

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#14921]
Maintainer: @stintel 
Environment: x86_64, generic, HEAD

Description:

Strongswan won't build in CI/CD because `gmpdh` is being built with "baked-in" flags rather than `libstrongswan_gmpdh_la_LDFLAGS` inheriting from the global settings.

`$TARGET_CFLAGS` and `$TARGET_LDFLAGS` need to go into `gmpdh`'s recipe, or it will not be built as `CONFIG_PKG_CHECK_FORMAT_SECURITY`, etc. (see `include/hardening.mk`) dictate, including `-fPIC` and `-fstack-protector`.

`src/libstrongswan/plugins/gmpdh/Makefile.am` will either need to be synthesized, or expand variables passed in externally (like `$TARGET_LDFLAGS`).

**Comment by pprindeville** [comment]
@brainsucker-na @micmac1 Did I forget anything?

**Comment by cotequeiroz** [comment]
I think I've found the problem and a solution for this.

The problem is that gmp C sources are turned into PIC code, but their asm sources are not.  They need `-DPIC` in `CFLAGS` to enable PIC code.  I've sent a patch to the ML fixing gmp, but it will benefit from further testing.

**Comment by pprindeville** [comment]
Per my email, can we just add `-DPIC` to `$(FPIC)` in `rules.mk`?

**Comment by pprindeville** [comment]
See PR #4006 in openwrt.

**Comment by pprindeville** [comment]
Fixed via https://github.com/openwrt/openwrt/pull/4006
