### ISSUE TITLE
squid: new version available and possible bug in initscript

### ISSUE THREAD

**Issue by doverride** [openwrt/packages#14944]
@ratkaj 
Snapshot, Any

Description:
Stable 4.14 was released on 08 Feb 2021

Also I noticed that coredump_dir, config_dir and ssldb dir are chowned nobody:nogroup in /etc/init.d/squid whilst squid runs with squid:squid. I suspect that ownership of these directories should instead be set to squid:root so that squid can maintain the ssldb, dump core, and use the config_dir to store cache and log files

**Comment by BKPepe** [comment]
Squid was updated in these two commits:
- master: https://github.com/openwrt/packages/commit/682aebbaea976bee8aa5cc6e2d5818364256b33f
- openwrt 21.02: https://github.com/openwrt/packages/commit/989d3320c1762e13e770f9e77c55ecd54015944c

~ Closing.
