### ISSUE TITLE
xray-core: bump git commit version to latest to avoid KDF panic

### ISSUE THREAD

**Issue by hathlife** [openwrt/packages#14972]
Maintainer: @1715173329 
Environment: (put here arch, model, OpenWrt version)
all arch of master / openwrt-21.02 branch
Description:
https://github.com/XTLS/Xray-core/issues/322
https://github.com/XTLS/Xray-core/commit/d22c2d034cc29bf553566d3483f3bf761d2225ab

**Comment by 1715173329** [comment]
I'm waiting for the new version which will be released these days.
