### ISSUE TITLE
node: Can we please make CONFIG_NODEJS_ICU_SMALL=y the default?

### ISSUE THREAD

**Issue by raintonr** [openwrt/packages#14983]
Looks like node package has no internationalisation support by default.

Is it possible that we can get the ICU small flag set by default? Surely this adds little overhead (and it's not that anyone running node JS should be doing so on a resource limited system anyhow).

Thx

**Comment by BKPepe** [comment]
Fixed in https://github.com/openwrt/packages/pull/15392
