### ISSUE TITLE
Very slow WiFi speed with kmod-rt2800-* packages

### ISSUE THREAD

**Issue by EagletUSSR** [openwrt/packages#15024]
kmod-rt2800-*

Very slow WiFi speed with kmod-rt2800-* packages: download speed is 15-20 Mbit/sec, upload speed is 50-70 Mbit. This very strange situation with this drivers for my device with MT7620A chipset (Youku-L1C). This situation about very poor code for TX module in this drivers.
Developers, please fix this problem. This problem since with 2017 year, after since kmod drivers for mt76** chipsets. 
Very strange, this situation not fix above 4 years!!!
Why are you deleting this message of mine about this problem? You have nothing to answer constructively? Or do you consider it beneath your dignity to communicate with ordinary users?

**Comment by dangowrt** [comment]
This is the OpenWrt **packages** repository. Ie. see the packages listed in this repository and realized that nothing regarding `rt2x00` or `mt7620` can be found here. Hence it's the wrong place to report this issue.
The correct place to file a bug for the OpenWrt **base** package `kmod-rt2000-soc` would be here on [bugs.openwrt.org](https://bugs.openwrt.org).
And somebody has already reported the issue with the Yukon device there as well, apparently, see:
https://bugs.openwrt.org/index.php?do=details&task_id=2717

As the `rt2x00` driver is part of the Linux kernel, the main discussion about development is going on the `linux-wireless` mailing list.
https://wireless.wiki.kernel.org/en/developers/MailingLists


There has been some research and discussion going on regarding performance on MT7620, see here
https://github.com/teixeluis/openwrt-perf-tests/

You are very welcome to join into the discussion there.

You can help by running the vendor driver and comparing the register assignment sequences with what `rt2x00` is doing, like @teixeluis has started doing and already found some problem, apparently.

```
git clone https://gitlab.com/Ntemis/wive-ng-mt
# edit MediaTek/Ralink driver in this to be very verbose about writing registers, compile and run on device
```


There are also obvious parts (TSSI, ...) still missing in `rt2x00` and it's just work to implement them and as this hardware is not exactly recent, there has not been so much interest in that lately. OpenWrt is an Free Open Source Software project, we are not a company providing a service or anything like that. So progress always depends on contributions from developers, all of them have limited time. I tried to get paid by the community for starting to sort out the mt7620/rt2x00 mess:
https://www.kickstarter.com/projects/1327597961/better-support-for-mt7620a-n-in-openwrt-lede
As you can see, things have been even worse...

When I started working on ePA hardware I had for testing (ZBT APE522II) ended up with smoking voltage regulator on the board, I gave up on it and went on doing other things.
After all, I ended up doing two months of work for very little compensation and had people insulting me publicly as a result, as they were believing that for the $3 they had pledged on kickstarter they are now entitled to a premium service provided by me. Honestly, there are more rewarding things in life to do.

All that being said, I'm still open to keep hacking on that in my spare time, given that someone provides **decent** hardware for testing. I've seen well-made MT7620A hardware with iPA, and performance there is pretty ok.
