### ISSUE TITLE
meson: Meson-based builds do not use changed options on reconfigure

### ISSUE THREAD

**Issue by NeoRaider** [openwrt/packages#15032]
Maintainer: @dhewg
Environment: (host build, 19.07 branch, newer versions likely affected as well)

Description:

When changing the options of a package (e.g. via menuconfig) and the package sets PKG_CONFIG_DEPENDS correctly, all build steps starting with `Configure` are repeated with the new settings. For Meson-based builds (observed with the `fastd` package), this doesn't have any effect, because `meson setup` ignores new passed options when it has already been configured and `--reconfigure` is not passed. When `--reconfigure` is passed, the passed options are handled as expected (but only when a configured build directory already exists - otherwise passing `--reconfigure` will make the setup fail).

Unfortunately, this solution isn't perfect either: While `meson setup` updates the build config using the flags passed in `MESON_ARGS`, options that were in `MESON_ARGS` in a previous build, but have disappeared now, are not reverted to their default values, which seems very fragile to me. Not even the `--wipe` option reverts to default settings.

I haven't found any option in the docs to "revert everything to the defaults, then apply the passed options". Should we just remove the whole build directory for the package at the start of `Configure`? This might lead to more rebuilds than necessary, but at least there won't be any surprises.

Just deleting `meson-*` seems to have the desired effect as well, and doesn't require a full rebuild afterwards, but it feels more like a hack than a proper solution...

**Comment by dhewg** [comment]
[0001-meson-reconfigure.patch.gz](https://github.com/openwrt/packages/files/6107342/0001-meson-reconfigure.patch.gz)
I don't really like it, but maybe like this?

**Comment by NeoRaider** [comment]
As I wrote, this is not sufficient. It will not revert options to the default that are not in MESON_ARGS anymore.

**Comment by dhewg** [comment]
Yeah, but is that a problem? As far as packages are concerned they always pass `-Dfeature=$(enabled or disabled)`, so the arg set is the same, the values may change. That fixes toggling a config value, which is the important user facing issue.

It's obviously a problem if we as package maintainers add/remove options and then try to build incremental. But I don't see a nice solution either, but since it's not a user facing issue I'd rather not add that rm hack.
