### ISSUE TITLE
mwan3: ifdown does not affect the selection of the default gateway.

### ISSUE THREAD

**Issue by DaniilMir** [openwrt/packages#15041]
Maintainer: @feckert, @aaronjg
Environment: 
Model	                Netgear Nighthawk X4S R7800
Firmware Version	OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.044.30835-34e0d65
Kernel Version  	4.14.221
mwan3 Version 	2.8.15-1

Description:
I installed and configured an USB LTE Modem for a backup link. Successfully tested it by disabling the wired connection.
After that I installed and configured the mwan3 package including the Luci interface module.
Scope is to failover on 4G link while wired connection is down and failback on wired connection state changed to Up. 
It works pretty well when I manually disable and enable connection from the Lucy UI. 
Tracert command is showing that mobile operator's gateway is in use while wired connection is down. 
I started testing the ping check mechanism of the mwan3 and if is not changing anything. 
I used an IP address which does not respond on ICMP as a Tracking IP for wired connection. 
UI is showing : 

```
Interface: wan
Status: Offline
```

But routing is still going trough the wired connection gateway. 
I also tried to keep the gateway IP address and increase option reliability value to simulate the link failure. 
It gave me the same results. 

**Expected behavior :** 
Once interface changed status to "offline" on the load balancing page it should redirect all the traffic to a backup interface 
regardless of physical status of the link or default gateway ping. 

**Configuration :** 

```
cat /etc/config/mwan3
config member 'WAN'
        option interface 'wan'
        option metric '1'
        option weight '10'

config member 'LTE'
        option interface '4G'
        option metric '250'
        option weight '1'        

config globals 'globals'
        option rtmon_interval '3'
        option logging '1'
        option loglevel 'debug'
        option mmx_mask '0xf0'

config interface 'wan'
        option enabled '1'
        option family 'ipv4'
        option track_method 'ping'
        option count '4'
        option size '56'
        option max_ttl '60'
        option check_quality '0'
        option failure_interval '5'
        option recovery_interval '5'
        option down '3'
        option up '3'
        option initial_state 'offline'
        list track_ip '%default gateway address%'
        option timeout '1'
        option interval '1'
        option reliability '2'

config interface '4G'
        option enabled '1'
        option family 'ipv4'
        list track_ip '8.8.8.8'
        option track_method 'ping'
        option reliability '1'
        option count '4'
        option size '56'
        option max_ttl '60'
        option check_quality '0'
        option failure_interval '5'
        option recovery_interval '5'
        option down '3'
        option up '3'
        option initial_state 'offline'
        option timeout '1'
        option interval '1'

config policy 'Both_UP'
        list use_member 'WAN'
        list use_member 'LTE'
        option last_resort 'unreachable'

config policy 'Wan_Only'
        list use_member 'WAN'
        option last_resort 'unreachable'

config policy 'LTE_Only'
        list use_member 'LTE'
        option last_resort 'unreachable'

```

`

Software-Version
-------------------------------------------------
OpenWrt - OpenWrt 19.07.7 r11306-c4a6851c72
LuCI - git-21.062.76689-a607f9c

Output of "ip a show"
-------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 44:a5:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 44:a5:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
5: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0c:5b:8f:27:9a:64 brd ff:ff:ff:ff:ff:ff
    inet 192.168.8.100/24 brd 192.168.8.255 scope global eth2
       valid_lft forever preferred_lft forever
8: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 44:a5:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 brd 192.168.0.255 scope global br-lan
       valid_lft forever preferred_lft forever
9: eth1.1@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP group default qlen 1000
    link/ether 44:a5:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
10: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 44:a5:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.204/24 brd XX.XX.XX.255 scope global eth0.2
       valid_lft forever preferred_lft forever
11: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP group default qlen 1000
    link/ether 44:a5:6e:47:83:1f brd ff:ff:ff:ff:ff:ff
12: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP group default qlen 1000
    link/ether 44:a5:6e:47:83:1e brd ff:ff:ff:ff:ff:ff

Output of "ip route show"
-------------------------------------------------
default via XX.XX.XX.1 dev eth0.2 proto static src XX.XX.XX.204 metric 1 
default via 192.168.8.1 dev eth2 proto static src 192.168.8.100 metric 20 
XX.XX.XX.0/24 dev eth0.2 proto static scope link metric 1 
192.168.0.0/24 dev br-lan proto kernel scope link src 192.168.0.1 
192.168.8.0/24 dev eth2 proto static scope link metric 20

Output of "ip rule show"
-------------------------------------------------
0:	from all lookup local 
1001:	from all iif eth0.2 lookup 1 
1002:	from all iif eth2 lookup 2 
2001:	from all fwmark 0x10/0xf0 lookup 1 
2002:	from all fwmark 0x20/0xf0 lookup 2 
2013:	from all fwmark 0xd0/0xf0 blackhole
2014:	from all fwmark 0xe0/0xf0 unreachable
32766:	from all lookup main 
32767:	from all lookup default

Output of "ip route list table 1-250"
-------------------------------------------------
Table 1: default via XX.XX.XX.1 dev eth0.2 metric 1 
XX.XX.XX.0/24 dev eth0.2 proto static scope link metric 1 
192.168.0.0/24 dev br-lan proto kernel scope link src 192.168.0.1 
192.168.8.0/24 dev eth2 proto static scope link metric 20
Table 2: default via 192.168.8.1 dev eth2 metric 20 
XX.XX.XX.0/24 dev eth0.2 proto static scope link metric 1 
192.168.0.0/24 dev br-lan proto kernel scope link src 192.168.0.1 
192.168.8.0/24 dev eth2 proto static scope link metric 20

Output of "iptables -L -t mangle -v -n"
-------------------------------------------------
Chain PREROUTING (policy ACCEPT 21197 packets, 8577K bytes)
 pkts bytes target     prot opt in     out     source               destination         
25518 9771K mwan3_hook  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 3491 packets, 328K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 16342 packets, 8036K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  100  5696 TCPMSS     tcp  --  *      eth0.2  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
   99  5600 TCPMSS     tcp  --  eth0.2 *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
   80  4160 TCPMSS     tcp  --  *      eth2    0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
   83  4316 TCPMSS     tcp  --  eth2   *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU

Chain OUTPUT (policy ACCEPT 3526 packets, 1213K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 5771 2925K mwan3_hook  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 19832 packets, 9247K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain mwan3_connected (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 7913 5890K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected dst MARK or 0xf0

Chain mwan3_hook (2 references)
 pkts bytes target     prot opt in     out     source               destination         
31289   13M CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0            CONNMARK restore mask 0xf0
 3361  472K mwan3_ifaces_in  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0
 2655  394K mwan3_connected  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0
  783  131K mwan3_rules  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0
31289   13M CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0            CONNMARK save mask 0xf0
10746 6427K mwan3_connected  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0xf0/0xf0

Chain mwan3_iface_in_4G (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  eth2   *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected src mark match 0x0/0xf0 /* default */ MARK or 0xf0
  126 10584 MARK       all  --  eth2   *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* 4G */ MARK xset 0x20/0xf0

Chain mwan3_iface_in_wan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   16  2376 MARK       all  --  eth0.2 *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected src mark match 0x0/0xf0 /* default */ MARK or 0xf0
  455 51524 MARK       all  --  eth0.2 *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* wan */ MARK xset 0x10/0xf0

Chain mwan3_ifaces_in (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 3053  428K mwan3_iface_in_4G  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0
 2767  402K mwan3_iface_in_wan  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0

Chain mwan3_policy_Both_UP (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* 4G 1 1 */ MARK xset 0x20/0xf0

Chain mwan3_policy_LTE_Only (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* 4G 1 1 */ MARK xset 0x20/0xf0

Chain mwan3_policy_Wan_Only (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      eth0.2  0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* out wan eth0.2 */ MARK or 0xf0
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0xf0 /* unreachable */ MARK xset 0xe0/0xf0

Chain mwan3_rules (1 references)
 pkts bytes target     prot opt in     out     source               destination
`

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by feckert** [comment]
I can not see a rule in your configuration? https://github.com/openwrt/packages/blob/master/net/mwan3/files/etc/config/mwan3#L115

**Comment by DaniilMir** [comment]
@feckert Thanks you very much for your advise!!!
After adding a default rule it started working as expected. 
I also mentioned a weird behavior of tracert command in windows. 
When I was simulating "link down" on wan connection my steps were : 

- trace route to address say google.com
- check if it is using wan connection 
- change Tracking reliability value to make wan link fail.
- trace route to google.com again.

Second trace was still using wan link (it was not down physically)
But when I changed the address to say microsoft.com - it used the LTE link. 
Exactly after this check I was checking again trace route google.com and it still was using the wan link) 
Pingplotter was able to track the routing change without any issues.

Offtopic : 
Also I tried to use default state "offline" for both links. And it was hanging on failback change 
WAN->LTE ok LTE->WAN hang. Luci UI was showing both interfaces as "disabled" on Status -> Load Balancing page.
When I tried to click on "detail" tab UI became irresponsible. Console was OK no memory leaks detected.
Only a full restart helped to recover this state. I was able to reproduce it twice, but didn't capture the logs. 
After I switched both interface to have default state "online" - it started working without any issues.

**Comment by feckert** [comment]
> I also mentioned a weird behavior of tracert command in windows.
> When I was simulating "link down" on wan connection my steps were :
> 
>     * trace route to address say google.com
> 
>     * check if it is using wan connection
> 
>     * change Tracking reliability value to make wan link fail.
> 
>     * trace route to google.com again.
> 
> 
> Second trace was still using the wan link (it was not down physically)
> But when I changed the address to say microsoft.com - it used the LTE link.
> Exactly after this check I was checking again trace route google.com and it still was using the wan link)
> Pingplotter was able to track the routing change without any issues.

I think this has to do with conntrack. You have to add the option `list flush_conntrack '<value>'` to your interface section.
The value could be connectd, disconnected, ifup or ifdown. This value flushes the iptables connctrack on interfaces events.

> Offtopic :
> Also I tried to use default state "offline" for both links. And it was hanging on failback change
> WAN->LTE ok LTE->WAN hang. Luci UI was showing both interfaces as "disabled" on Status -> Load Balancing page.
> When I tried to click on "detail" tab UI became irresponsible. Console was OK no memory leaks detected.
> Only a full restart helped to recover this state. I was able to reproduce it twice, but didn't capture the logs.
> After I switched both interface to have default state "online" - it started working without any issues.

That's news to me. I use exactly this setup and it works for me.

**Comment by DaniilMir** [comment]
I enabled all options on both interfaces for the "Flush conntrack table" setting. 
Switched interfaces back to default "online" option and it works stable right now. 
Don't know what caused this issue. Sometimes even a DBA can break everything like QA does ) 
Thank you again for your help. 
I'm new to openwrt, but more I use it - more I like it.
