### ISSUE TITLE
acme, nginex: acme can't stop nginex instance

### ISSUE THREAD

**Issue by majkrzak** [openwrt/packages#15071]
Maintainer: acme: @tohojo  nginx: @neheb, @peter-stadler 
Environment: OpenWrt SNAPSHOT r16142-12dbad1a86 / LuCI Master git-21.060.51374-cd06e70

Description:
---------------

Acme is not able to restart nginex server, because it is not getting properly detected.

```
port80 listens: 2868/uci.conf 2868/uci.conf
Cannot run in standalone mode; another daemon is listening on port 80.
```

In `netstat -nptl` command (used by acme to determinate what service is listening) command it is decribed as:

```
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2868/uci.conf -g da
```

in `ps` it figgures as:

```
nginx: master process /usr/sbin/nginx -c /etc/nginx/uci.conf -g daemon off;
```

**Comment by yangfl** [comment]
acme maintainer is not me but tohojo

**Comment by majkrzak** [comment]
Sorry,  package Makefile history tricked me.

**Comment by tohojo** [comment]
Piotr Majkrzak ***@***.***> writes:

> Maintainer: acme: @tohojo  nginx: @neheb, @peter-stadler 
> Environment: OpenWrt SNAPSHOT r16142-12dbad1a86 / LuCI Master git-21.060.51374-cd06e70
>
> Description:
> ---------------
>
> Acme is not able to restart nginex server, because it is not getting properly detected.
>
> ```
> port80 listens: 2868/uci.conf 2868/uci.conf
> Cannot run in standalone mode; another daemon is listening on port 80.
> ```
>
> In `netstat -nptl` command (used by acme to determinate what service is listening) command it is decribed as:
>
> ```
> tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2868/uci.conf -g da
> ```

Huh, that's odd. Where is your 'netstat' coming from? (i.e., what's the
output of `which netstat` and `netstat --version`?)

**Comment by majkrzak** [comment]
It is busybox builtin,

```
root@circle:~# opkg info busybox
Package: busybox
Version: 1.33.0-1
Depends: libc
Conflicts: busybox-selinux
Status: install user installed
Section: base
Essential: yes
Architecture: arm_cortex-a15_neon-vfpv4
Size: 235551
Filename: busybox_1.33.0-1_arm_cortex-a15_neon-vfpv4.ipk
Description: The Swiss Army Knife of embedded Linux.
 It slices, it dices, it makes Julian Fries.
Installed-Time: 1615196766
```

**Comment by tohojo** [comment]
So why is it not just output'ing the binary name? Is this a recent change?

**Comment by majkrzak** [comment]
It looks like it got truncated in weird way. `/proc/../cmdline` contains proper value. And it is how I fixed it on my local.

**Comment by tohojo** [comment]
Could you please test if that PR fixes it? :)
