### ISSUE TITLE
ndpi-netfilter ?

### ISSUE THREAD

**Issue by kong156** [openwrt/packages#1507]
Does openwrt include ndpi-netfilter? If not this would be interesting to have for capable devices such as UBNT ERL. 
I'm testing ndpi-netfilter ability to recon the L7 protos and the results looks very promising. So, looking at betolj/ndpi-netfilter fork, i think that it worth your attention.

**Comment by AndrewMargarit** [comment]
Did you get anywhere with this?

**Comment by bittorf** [comment]
@kong156 can you provide a makefile as RFC?

**Comment by kong156** [comment]
No, I didn't. Meanwhile, I lost my interest on openwrt.
