### ISSUE TITLE
mwlwifi-firmware-88w8964: opkg_install_cmd: Cannot install package mwlwifi-firmware-88w8964

### ISSUE THREAD

**Issue by saybeking** [openwrt/packages#15278]
Hello,I use a imagebuilder ( https://downloads.openwrt.org/releases/19.07.7/targets/mvebu/cortexa9/openwrt-imagebuilder-19.07.7-mvebu-cortexa9.Linux-x86_64.tar.xz ) to run " make image PROFILE=linksys_wrt32x  "

result is :

Collected errors:
 * opkg_install_cmd: Cannot install package mwlwifi-firmware-88w8964.
make[2]: *** [Makefile:158: package_install] Error 255
make[1]: *** [Makefile:118: _call_image] Error 2
make: *** [Makefile:208: image] Error 2

sorry my english is so poor .

**Comment by BKPepe** [comment]
Hello,

We don't have this package in our repository, you should follow [Reporting bugs](https://openwrt.org/bugs) for OpenWrt main repository.
