### ISSUE TITLE
Treating unmaintained packages / stepping down as a maintainer

### ISSUE THREAD

**Issue by KanjiMonster** [openwrt/packages#153]
This is mostly a discussion topic for everyone. Currently we have quite clear rules on how to become a maintainer, but what's missing is how does one stop being one, and what should happen with the package.

For now we just removed the package instantly, but maybe we want to keep it a while - having no maintainer does not instantly make a package bad. Leaving it in for a while will also prevent tickets about packages going missing from snapshot builds.

My first Idea would be:

As the maintainer stepping down:
1. remove yourself as maintainer (pull request/commit)
2. open an issue about $pkg having no maintainer/requiring one (probably a "help wanted" ticket).

Then after some time (e.g. one month, or latest before the next release), if until then nobody wanted to take over, we actually remove it.

**Comment by dibdot** [comment]
reference current discussion #6584 and close this one.
