### ISSUE TITLE
has a dependency on 'kmod-crypto-arc4

### ISSUE THREAD

**Issue by coLATin** [openwrt/packages#15308]
Please make sure that the issue subject starts with `<package-name>: `

Also make sure that the package is maintained in this repository and not in base which should be submitted at https://bugs.openwrt.org or in the LuCI repository which should be submitted at https://github.com/openwrt/luci/issues.

Issues related to releases below 18.06 and forks are not supported or maintained and will be closed.

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

Description:
system: ubuntu 20.10
tag: 19.07

```
Formating code blocks by wrapping them with pairs of ```
```
default setting, but noticed :  "has a dependency on 'kmod-crypto-arc4"

![image](https://user-images.githubusercontent.com/749762/112939463-18905e80-915e-11eb-9165-e800b1f7cc9e.png)

**Comment by BKPepe** [comment]
You will need to modify your `feeds.conf` for `packages` feed to changed it to this commit https://github.com/openwrt/packages/commit/feb1a188e51191a8088596d503599d5f5f268d8b or to the latest `openwrt-19.07` branch, that's up to you.
