### ISSUE TITLE
Ocserv configuration item under master branch is not working!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#15313]
![image](https://user-images.githubusercontent.com/45259624/112999871-e4d72800-91a1-11eb-80f3-23b6806fc308.png)

**Comment by ptpt52** [comment]
same issue report here.

**Comment by ptpt52** [comment]
fixup by:
```
diff --git a/libs/libseccomp/Makefile b/libs/libseccomp/Makefile
index 355841df4..e82ec751b 100644
--- a/libs/libseccomp/Makefile
+++ b/libs/libseccomp/Makefile
@@ -56,7 +56,6 @@ endef
 define Package/libseccomp
 $(call Package/libseccomp/Default)
   TITLE+= (library)
-  DEPENDS+= @!arc
 endef
 
 define Package/scmp_sys_resolver


```

**Comment by ptpt52** [comment]
@dangowrt  this changes https://github.com/openwrt/packages/commit/b29e609701987072fbd991a9ffc203103f99b943

**Comment by dangowrt** [comment]
https://github.com/openwrt/packages/commit/b29e609701987072fbd991a9ffc203103f99b943 reflects the reality that libseccomp doesn't build on arc and is hence not available. Complicating this more with additionally depending on `@!arm||BROKEN` would probably not make things better.

Please try this:
```diff
diff --git a/net/ocserv/Config.in b/net/ocserv/Config.in
index b6460cd8e..cf86bef17 100644
--- a/net/ocserv/Config.in
+++ b/net/ocserv/Config.in
@@ -9,6 +9,7 @@ config OCSERV_PAM
 
 config OCSERV_SECCOMP
 	bool "enable seccomp"
+	depends on !arc
 	default n
 
 config OCSERV_RADIUS
```

**Comment by zxlhhyccc** [comment]
> [b29e609](https://github.com/openwrt/packages/commit/b29e609701987072fbd991a9ffc203103f99b943) reflects the reality that libseccomp doesn't build on arc and is hence not available. Complicating this more with additionally depending on `@!arm||BROKEN` would probably not make things better.
> 
> Please try this:
> 
> ```diff
> diff --git a/net/ocserv/Config.in b/net/ocserv/Config.in
> index b6460cd8e..cf86bef17 100644
> --- a/net/ocserv/Config.in
> +++ b/net/ocserv/Config.in
> @@ -9,6 +9,7 @@ config OCSERV_PAM
>  
>  config OCSERV_SECCOMP
>  	bool "enable seccomp"
> +	depends on !arc
>  	default n
>  
>  config OCSERV_RADIUS
> ```

Trying this method is still the same problem
