### ISSUE TITLE
kmod-usb-net-rtl8152: poor download speed on 19.07.7 working fine on 19.07.3 stable

### ISSUE THREAD

**Issue by ClaudioOpenwrt** [openwrt/packages#15321]
Maintainer: @\OPENRT Team 
Environment: (OPENWRT 19.07.7 X86_64)

Description:

Download speed caped to 50/60 Mbps on a 300 Mbps connection
device TP-Link U300 10/100/1000  USB LAN Adapter chipset RTL8152
same adapter working as expected on stable release 19.07.3

same problem building last snapshot

**Comment by diizzyy** [comment]
Wrong repo, this bug report should be created here: https://bugs.openwrt.org
