### ISSUE TITLE
StrongSwan missing dependency under master branch!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#15376]
![image](https://user-images.githubusercontent.com/45259624/114189754-1fe51280-997d-11eb-9158-722cc584a209.png)

**Comment by zxlhhyccc** [comment]
define Package/strongswan-libnttfft
$(call Package/strongswan/Default)
  TITLE+= nttfft library
  DEPENDS:= +strongswan
endef
Should be modified to：
define Package/strongswan-libnttfft
$(call Package/strongswan/Default)
  TITLE+= nttfft library
  DEPENDS:= +strongswan
endef

**Comment by pprindeville** [comment]
Fixed with PR #15382.
