### ISSUE TITLE
strongswan: handle chacha20poly1305 as AEAD algorithm

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#15397]
Maintainer: me, @Thermi
Environment: all, all, master

Description:

No hash algorithm is permitted in a crypto-proposal when using AEAD ciphers.

**Comment by Thermi** [comment]
*no hash algorithm is permitted

Am April 11, 2021 11:06:36 PM UTC schrieb Philip Prindeville ***@***.***>:
>Maintainer: me, @Thermi
>Environment: all, all, master
>
>Description:
>
>No hash algorithm is required in a crypto-proposal when using AEAD
>ciphers.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/packages/issues/15397

-- 
Sent from mobile

**Comment by pprindeville** [comment]
Resolved with PR #15406.
