### ISSUE TITLE
Change memcached and nfs-utils dependency?

### ISSUE THREAD

**Issue by maz-1** [openwrt/packages#1542]
Why are these two package depending on libevent instead of libevent2?
Seems that nfs-utils and memcached works well with libevent >= 2.0 in most linux distos.Don't understand why these two packages are still depending on legacy libevent.
Having both libevent and libevent2 enabled will cause libevent2 headers being overridden, some packages that depends on libevent2 only like tmux won't build.

**Comment by KanjiMonster** [comment]
meh, looks like only one assignee possible ... @heil @tripolar

**Comment by heil** [comment]
should be fixed with 6cc0ad6ecd78763fbf53a2730a28afb912db1249. thx for reporting.
