### ISSUE TITLE
jool: backport to 19.07

### ISSUE THREAD

**Issue by treysis** [openwrt/packages#15426]
Can we backport Jool 4.1.5 (https://github.com/openwrt/packages/pull/15340) to OpenWrt 19.07? It has some serious performance improvements. And Jool 3.x is several years old.

The downside: Jool 4.x uses a new syntax. However, I believe most people that use Jool know what they are doing.

**Comment by ja-pa** [comment]
I don't want to be against your request, but is it really necessary taking into account the forthcoming release to OpenWrt 21.x?

**Comment by neheb** [comment]
Not really possible. The update has to be timed with a new release of 19.07 which has been tricky in the past.
