### ISSUE TITLE
intel 7265 can't open ap mode

### ISSUE THREAD

**Issue by styfstr** [openwrt/packages#15448]
openwrt version 19.07

![image](https://user-images.githubusercontent.com/44523785/115211926-9e3a7500-a132-11eb-8646-eb758757f7f2.png)

when i open wifi  ap mode, and kernel log

![image](https://user-images.githubusercontent.com/44523785/115212007-aeeaeb00-a132-11eb-898b-65fac8b4a06d.png)

**Comment by BKPepe** [comment]
This is wrong repository to report this issue. You should provide more details about your issue and  so on. However, you should report it to core repository. Follow: https://openwrt.org/bugs
