### ISSUE TITLE
python-psycopg2 not available for x86 21.02

### ISSUE THREAD

**Issue by HikariWS** [openwrt/packages#15475]
python-psycopg2 is used for Python to connect on Postgres. It's available on 19.07, but not on 21.02.

Will it still be published, or won't it be available on the new version?

Is there any tutorial teaching how to download the source, compile and install packages?

**Comment by BKPepe** [comment]
The package, which you are looking for was removed for a while in this repositoy as it was missing Python3 support and as it was added after branch-off, then it was missing in OpenWrt 21.02 as it is not a good idea to have regression or even a gap when the package is available in OpenWrt 19.07 and OpenWrt master, so it should not be missing in OpenWrt 21.02.

Cherry-picked: https://github.com/openwrt/packages/commit/ed645bce9cd1390782d63d5879dc23bf2b14a6ec

It will be available to install within a few hours.
