### ISSUE TITLE
dockerd cannot start container

### ISSUE THREAD

**Issue by qiuzi** [openwrt/packages#15497]
After running the container manually, the server prompts an error
`ERRO[2021-04-22T10:34:11.795451690Z] copy shim log    error="read /proc/self/fd/14: file already closed"`
@G-M0N3Y-2503

**Comment by G-M0N3Y-2503** [comment]
I just tested and running `docker run -it alpine cat /etc/*-release` with `Docker version 20.10.5, build 55c4c88` and `Docker version 20.10.6, build 370c289` worked fine on openwrt/openwrt@2ce89a35788fcd768a4a872d3d4f5a3a131b1d43 and openwrt/openwrt@17576b1b2aeacf0a23bb9a911d675bd324754745 respectively.
