### ISSUE TITLE
samba4: /etc/init.d/samba4 bogus io_uring check

### ISSUE THREAD

**Issue by Hello71** [openwrt/packages#15512]
#14463 causes a file "2" to be created every time `/etc/init.d/samba4 start` (or restart) is run. however, this check is bogus in the first place. openwrt/lede releases are built with CONFIG_KERNEL_KALLSYMS=n, so /proc/kallsyms doesn't even exist.

**Comment by Hello71** [comment]
@Andy2244, @hnyman

**Comment by Andy2244** [comment]
Ah thanks missed that it does not work on `SMALL_FLASH`, which cant install samba4 anyway because of its size? Not sure if extroot works on small devices?
```
config KERNEL_KALLSYMS
	bool "Compile the kernel with symbol table information"
	default y if !SMALL_FLASH
```
So normal devices can use `/proc/kallsyms` which i was testing with.

Yes the `>>2` is a actual error and will be fixed in the next version.

**Comment by Hello71** [comment]
it is `!SMALL_FLASH`, but also buildbot sets CONFIG_KERNEL_KALLSYMS=n.

**Comment by Andy2244** [comment]
> buildbot sets CONFIG_KERNEL_KALLSYMS=n

@hnyman Why is buildbot doing this? This way my own local dev builds, do not match what is "released" via buildbot?

**Comment by hnyman** [comment]
Note that the final release configs are different (smaller) than the development snapshots config in buildbot.

To my knowledge, the KALLSYMS are normally set (for development snapshots and private builds), but the release config has them removed in order to optimize the final release images, which are not meant for detailed debugging.

**Comment by Andy2244** [comment]
> but the release config has them removed in order to optimize the final release images, which are not meant for detailed debugging.

Have to test myself, how much bytes `CONFIG_KERNEL_KALLSYMS=n` actually saves, but guess i have no way to runtime detect the kernel feature than and need to rely on the static data or just try&error at startup.
