### ISSUE TITLE
mwan3 track interface with TOR

### ISSUE THREAD

**Issue by perachemarc** [openwrt/packages#15541]
Dear all, 

I want to track an interface connected to TOR network. On TOR, there is no support for ICMP packets; thus we need a tracking method using TCP only. It is possible to use curl for example. Do it makes sense to add a new tracking method based on curl. For example curl -s --interface   [interface] [tracking IP].

Best,
Marc

**Comment by feckert** [comment]
We already support other tracking methods. Have a look at the [source](https://github.com/openwrt/packages/blob/master/net/mwan3/files/usr/sbin/mwan3track#L67).
However, these only work reliably in the master or owrt-21.02 branch, as we have a c wrapper for [interface pinning](https://github.com/openwrt/packages/blob/master/net/mwan3/src/sockopt_wrap.c) handling here.

**Comment by perachemarc** [comment]
I'm currently using 21.02_rc1. I'll try asap with the master.

**Comment by HikariWS** [comment]
I haven't tested yet but mwan3 supports httping, which runs over HTTP/S and works as ping counting the latency to receive the HTTP/s response. Doesn't it work for u?

**Comment by perachemarc** [comment]
I tried httping, but I was not able to select a tun* interface.

**Comment by perachemarc** [comment]
With this small modification in mwan3track file, 
@@ -50,6 +50,12 @@
 				return 1
 			}
 			;;
+		curl)                                                                                              
+                        which curl 1>/dev/null 2>&1 || {                                                             
+                                $LOG warn "Missing curl. Please install curl package."                              
+                                return 1                                                                              
+                        }                                                                                             
+                        ;;  
 		*)
 			$LOG warn "Unsupported tracking method: $track_method"
 			return 2
@@ -178,7 +184,10 @@
 					;;
 					nping-arp)
 						result=$(nping -e $DEVICE -c $count $track_ip --arp | grep Lost | awk '{print $12}')
-					;;
+					;;                                                                                                                                   
+                                        curl)                                                                                                                                  
+                                                curl -s --interface $DEVICE $track_ip &> /dev/null                                                                
+                                                result=$?
 				esac
 				if [ $check_quality -eq 0 ]; then
 					if [ $result -eq 0 ]; then

I was able to use curl and my problem is solved with a modified mwan3_2.8.16-1

**Comment by feckert** [comment]
Issue was fixed by modifying the mwan3 source by @perachemarc.
