### ISSUE TITLE
adblock: setting DNS Directory and then clearing does not reset /etc/config/dhcp entry

### ISSUE THREAD

**Issue by khimaros** [openwrt/packages#15573]
Maintainer: @dibdot
Environment: `(Turris Omnia, OpenWrt 19.07.7 r11306-c4a6851c72)`

## reproduction steps

1) enable the adblock service in LuCI for dnsmasq
2) refresh adblock, all works well
3) set the `DNS Directory` to a bad path eg. `/etc/adblock`
4) refresh adblock, it will fail and dnsmasq will crash
5) clear the `DNS Directory` path
6) refresh adblock, still does not work
7) edit `/etc/config/dhcp` and change `confdir` to `/tmp/dnsmasq.d`
8) refresh adblock, issue resolved

## suggested fix

i suspect this is difficult to fix without causing other problems but wanted to mention this as it took me some time to figure out the root cause and fix. here are a few possibilities:

1. show the current value of confdir in LuCI
2. warn the user when the confdir is set to something other than `/tmp/dnsmasq.d` despite `DNS Directory` being empty.
3. surface the dnsmasq failures in the adb log in LuCI

**Comment by dibdot** [comment]
The used dns directory is listed under "DNS backend" in the adblock status (CLI & LuCI), e.g.:

![dns_1](https://user-images.githubusercontent.com/8061346/117096076-4c1b6580-ad68-11eb-9cda-397e4b79ab0a.png)

You've changed a parameter on the "Advanced DNS Settings" tab in LuCI and the given value will be listed, too (if you're leaving the defaults), e.g.:
![dns_2](https://user-images.githubusercontent.com/8061346/117096123-6e14e800-ad68-11eb-931b-9e53c88135f5.png)

To get unfiltered log messages go to Status => System Log in LuCI or just use logread in CLI. As always ... we could improve the help text in LuCI. My best advice: If you're unsure to change advanced parameters, ask in the forum before.
