### ISSUE TITLE
comgt: in file ncm.sh problem manufacturer detection

### ISSUE THREAD

**Issue by stramoslab** [openwrt/packages#15614]
Maintainer: Felix Fietkau <nbd@nbd.name>
Environment: check on youku YK-L1c, modem huawei E3276, OpenWrt 19.07.5 r11257-5090152ae3

Description:

Some modems put to console messages what start from ^ symbol. while script try to get manufacturer name, it can get one of this:

^RSSI:21

^LTERSRP:-102,-15

^RSSI:21

^LTERSRP:-102,-14

Script must remove strings what start from ^ symbol.
To do this need change in file ncm.sh string

``` manufacturer=`gcom -d "$device" -s /etc/gcom/getcardinfo.gcom | awk 'NF && $0 !~ /AT\+CGMI/ { sub(/\+CGMI: /,""); print tolower($1); exit; }'` ```

to 

``` manufacturer=`gcom -d "$device" -s /etc/gcom/getcardinfo.gcom | awk 'NF && $0 !~ /^\^|AT\+CGMI/ { sub(/\+CGMI: /,""); print tolower($1); exit; }'` ```

As i can see, this bug in all versions.

**Comment by feckert** [comment]
The package [comgt](https://github.com/openwrt/openwrt/blob/master/package/network/utils/comgt/Makefile) is maintained in openwrt core.
Please open a pullrequest with your request changes there.
