### ISSUE TITLE
kmod-rtl8812au-ct:  Unable to use wifi AP capabilities... 

### ISSUE THREAD

**Issue by M0E-lnx** [openwrt/packages#15628]
Maintainer: @Ben Greear <greearb@candelatech.com>
Environment: openwrt 21.02-RC1 on aarch64 raspberrypi3 (bcm27xx_bcm2710)

Description:
The device seems to work fine for connecting as a wifi client, but not as an AP.  Someone in #openwrt IRC suggested this may not have AP mode enabled.

The luci network -> wireless interface lists the radio as `` Generic 802.11abg`` and says ``Wireless is not associated``

I have had success with this same devices on debian based OS's by building the driver from https://github.com/morrownr/8812au and https://github.com/gnab/rtl8812au and have been trying to compile one of those in openwrt, but it is proving difficult for me.

Any help on this would be appreciated.

**Comment by BKPepe** [comment]
@M0E-lnx This is not right place to report issues related to [the core repository](https://github.com/openwrt/openwrt).  Take a look at [reporting bugs](https://openwrt.org/bugs).

In any case, I see that there are some attemps to get alternative drives for RTL8812AU:
https://github.com/openwrt/openwrt/pull/4229
https://github.com/openwrt/openwrt/pull/4230 

Closing as this is not related to this repository.
