### ISSUE TITLE
20.2.0 rc1 WPA3

### ISSUE THREAD

**Issue by hello1hello2** [openwrt/packages#15689]
Please be patient with me as im new to this

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (ARMv7 Processor rev 1 (v7l), Linksys WRT1900ACS, OpenWrt 21.02.0-rc1 )

Description: WPA3 does not work on 2.4ghz. It will not start with WPA3 selected and cant connect at all.
WPA3 on 5ghz drops out here and there but will start ok and can connec to it

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by jamesmacwhite** [comment]
Probably should be reported to: https://bugs.openwrt.org/ as it's part of the OpenWrt core.

**Comment by BKPepe** [comment]
As @jamesmacwhite said. This issue does not belong here.
