### ISSUE TITLE
syncthing: no ppc port

### ISSUE THREAD

**Issue by Chris56** [openwrt/packages#15691]
Maintainer: @aparcar 
Environment: ppc, 19.07.7

Description:
I would like to use syncthing for the powerpc processor (powerpc_464fp in my case ...).
However there doesn't seem to be a port for it.
Any reason why?

Also the package is quite big for embedded systems. Have all symbols been stripped? Or is it just that the linked-in libraries are quite big?

Chris

**Comment by aparcar** [comment]
Not sure if golang works on ppc, can you check that?

Binaries are stripped via sstrip, maybe additional optimizing is done (or needed) for Go, no idea. 

Maybe @jefferyto knows answers to both questions

**Comment by Chris56** [comment]
Well, I just use a machine which requires powerpc_464fp and I found out syncthing doen't support it.

Therefore, I don't have the development environment and cannot try build it.
But someone must have the environment running ...

**Comment by Chris56** [comment]
I just had a look at: https://golang.org
It says, supported is ppc64, ppc64le
Which is 64 bit powerpc!
powerpc_464fp is 32 bit ...

**Comment by aparcar** [comment]
So it's an "upstream" issue which we can't fix within OpenWrt. Sorry for that.
