### ISSUE TITLE
Error compiling libjpeg-turbo on master branch!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#15766]
![image](https://user-images.githubusercontent.com/45259624/120657347-006af180-c4b7-11eb-8631-673848502302.png)

**Comment by BKPepe** [comment]
Hello,

Would it be possible for the next time to use copy&paste instead of doing screenshots?

**Comment by neheb** [comment]
This is already fixed. https://github.com/openwrt/packages/commit/730c582d291960e4d9fde5c381fea5d0db9de756
