### ISSUE TITLE
NGINX stops for "504 Gateway Time-out" when HTTPS-DNS-PROXY service is ON and WAN is OFF  (at boot time or reboot)

### ISSUE THREAD

**Issue by desigabri** [openwrt/packages#15783]
NGINX Maintainer: Thomas Heil heil@terminal-consulting.de, Ansuel Smith ansuelsmth@gmail.com
NGINX-UTIL Maintainer: Peter Stadler peter.stadler@student.uibk.ac.at

Environment: Qualcomm Atheros IPQ806X, Archer C2600 v1,
OpenWrt 21.02-SNAPSHOT r16130-1b27d89d40 
OpenWrt 21.02-SNAPSHOT r16132-00d7a459f3

Description:

THIS TROUBLE HAPPENS FOR nginx IF HTTP-DNS-Proxy PACKAGE IS INSTALLED AND ABILITATED

If the router isn't connected to internet (or to WAN?) nginx try starting but then FAILS showing **"504 Gateway Time-out"**

The troble can be solved just connecting the WAN cable (connected to internet) and  then disabling HTTP-DNS-PROXY service. Doing this the router become accessible also if WAN is disconnected.

This is way I'm going to open a ticket to HTTP-DNS-PROXY  asking to disable the service for defautl settings.
I'll open  a ticket also to NGINX  package because may be this is a trouble of NGINX that isn't able to bypass the lack of WAN.

**Comment by BKPepe** [comment]
Related to #15784, closing. There is no need to have two opened issues for one issue.

**Comment by desigabri** [comment]
I opened two tickets because I don't know if the problem come from NGINX or from HTTP-DNS-PROXY and the rules ask to refer the ticket to a defined package

**Comment by desigabri** [comment]
Finally I had two problems at the same time that comfused me: HTTPS-DNS-PROXY solved the problems by itself (#16252) and About NGINX I found the FIX in #14465
