### ISSUE TITLE
dropbear: irritating restriction of interface setting

### ISSUE THREAD

**Issue by phqzgunsfjror** [openwrt/packages#15841]
Maintainer: @dedeckeh 
Environment:
Fritzbox 4040
LuCI openwrt-19.07 branch (git-21.044.30835-34e0d65) 
OpenWrt 19.07.7 r11306-c4a6851c72 

Description:
I created a new network called `whatever`. It is neither part of `lan` nor `br-lan`.
In dropbear I restricted 
→ System → Administration → SSH Access → Interface: "lan" (Listen only on the given interface or, if unspecified, on all)
 (saved and rebootet)

I would assume that only devices from network `lan` can reach OpenWrt via SSH but also the network `whatever` can reach it. Is my assumption incorrect?  
In the end I restricted it with firewall rules but for me this setting is irritating.

I also tried to use `br-lan` but that is not selectable via Luci and via ssh it gives an error...
```
vi /etc/config/dropbear
config dropbear
        option Port '22'
        option Interface 'br-lan'
        option PasswordAuth 'off'

/etc/init.d/dropbear restart
```
error: `interface br-lan has no physdev or physdev has no suitable ip`

**Comment by neheb** [comment]
This belongs at https://bugs.openwrt.org
