### ISSUE TITLE
nginx-all-module: does not meet dependencies for luci-ssl-nginx

### ISSUE THREAD

**Issue by rguerrab** [openwrt/packages#15859]
Tried to run LuCI off nginx with SSL on my box running:
OpenWrt 19.07.5 r11257-5090152ae3 / LuCI friendlywrt-v19.07.5 branch git-20.358.36252-85ff2c9
but can't install luci-ssl-nginx after first installing nginx-all-module because opkg wants to install nginx-ssl as a dependency to luci-ssl-nginx: which should already be provided by nginx-all-module.

**Comment by CodeFetch** [comment]
That's strange, because nginx-all-module provides nginx-ssl...
@peter-stadler Can you have a look?

**Comment by peter-stadler** [comment]
I will take a look at the weekend. Thanks for the notification :-)

**Comment by peter-stadler** [comment]
In the 19.07 it provides only nginx not nginx-ssl, made a PR now.

**Comment by rguerrab** [comment]
Awesome, thanks so much.

**Comment by hnyman** [comment]
Fixed by #16036 in September 2021.
