### ISSUE TITLE
python3: build failure when building custom firmware with python package

### ISSUE THREAD

**Issue by anyuta1166** [openwrt/packages#15871]
Maintainer: @commodo @jefferyto
Environment: x86-64, r16955-946019637e

Description:

I’m unable to build a custom firmware with python3-light package enabled.

I’m encountering the build failure:

```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libpython3--3.9 for python3-base
 * pkg_hash_fetch_best_installation_candidate: Packages for python3-base found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package python3-base.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for python3-light:
 *      libpython3--3.9
 * opkg_install_cmd: Cannot install package python3-light.
make[2]: *** [package/Makefile:70: package/install] Error 255
```

There is some dependency issue. The libpython3 package is built as libpython3-3.9, but python3-base wants libpython3–3.9 (note the two dashes).

I'm not sure where to post this issue (here or to bugs.openwrt.org) because after some investigation I've found that the build is broken after this commit: f6a03bff5bccdbf9165087bccbb35095903d05c6 build: prepend ABI suffixes with a dash if package name ends with digit
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=f6a03bff5bccdbf9165087bccbb35095903d05c6

Reverting this commit allows to successfully build the firmware.

I don't see anything wrong in python package makefile. So I really don't know is this a base system issue or a package issue.

**Comment by commodo** [comment]
@jow-    ping

is this with a clean checkout?
i will try a build now;
but, the issue is not Python directly, but more with some OpenWrt core logic

**Comment by anyuta1166** [comment]
> is this with a clean checkout?

Yes.

**Comment by jow-** [comment]
Will look into it.

**Comment by jow-** [comment]
Fix pushed.

**Comment by commodo** [comment]
> Fix pushed.

works for me

@anyuta1166 ?

**Comment by anyuta1166** [comment]
Works for me too.
