### ISSUE TITLE
tessdata: takes forever to build because of single-threaded steps

### ISSUE THREAD

**Issue by zorun** [openwrt/packages#16002]
Maintainer: @vk496 @neheb 

Description:

tessdata takes forever to build, even on a multi-core machine with -jXX.

Looking at the build, there are lots of single-threaded steps doing `gzip -d` / `gzip` one after the other. Each gzip takes about 5 seconds, and the total is several minutes.

I suspected this is related to the `foreach LANG,$(ALLTESSERACTLANG)` that builds sequentially.

**Comment by neheb** [comment]
Most likely. Patches welcome.

**Comment by zorun** [comment]
Right, the main issue is that we uncompress 130 times the same big tarball... (638 MB)

I didn't find how to parallelize package creation, but fixing this uncompress issue already improved things a lot.

PR here: #16003

**Comment by vk496** [comment]
Thank you!

It was the first time I created a complex package in OpenWrt repos.

30 jun. 2021 14:19:29 zorun ***@***.***>:

**Comment by zorun** [comment]
On the buildbots, before the change: `time: package/feeds/packages/tessdata/compile#4607.45#481.64#5370.20`

After: `time: package/feeds/packages/tessdata/compile#179.02#35.19#343.18`

This is user/system/realtime, so we went from 5370s to 343s, not bad :)
