### ISSUE TITLE
mwan3: ubus/luci status shows online while CLI shows error

### ISSUE THREAD

**Issue by luizluca** [openwrt/packages#16026]
Maintainer: @feckert 
Environment: 19.07.6 x86_64

Description:

When mwan3 chain is removed, "mwan3 status" will correctly return "error" for every interface. However,
ubus status (and luci mwan3 status, as it uses ubus) will still report all interfaces as online. status should not only consider $MWAN3TRACK_STATUS_DIR/${iface}/STATUS but also the same checks used by mwan3

```
        elif [ -n "$($IP rule | awk '$1 == "'$(($id+1000)):'"')" ] || \
                [ -n "$($IP rule | awk '$1 == "'$(($id+2000)):'"')" ] || \
                [ -n "$($IPT -S mwan3_iface_in_$1 2> /dev/null)" ] || \
                [ -n "$($IP route list table $id default dev $device 2> /dev/null)" ]; then
                result="error"
```

**Comment by feckert** [comment]
19.07 is EOL please verify if the issue is still present on 21.01 or 22.03
