### ISSUE TITLE
gitolite installation manual needs a rework

### ISSUE THREAD

**Issue by sla-te** [openwrt/packages#16032]
If one follows https://openwrt.org/docs/guide-user/services/gitolite precisely he will first get connection refused and then has to manually edit etc/ssh/sshd_config and comment out the explicit authorized_keys dir. Then he will be able to connect but will be asked for a password (which doesnt exist for the git user) on ssh'ing via git@192.168.x.x, which is the final result of the whole setup.

Probably also relevant: https://github.com/openwrt/packages/issues/16031

**Comment by BKPepe** [comment]
This repository does not contain the ``gitolite`` package. Feel free to request changes to documentation on [OpenWrt forum](https://forum.openwrt.org/) or rather try to do those changes yourself. 

Closing. This is not a good way to ask to update documentation as this repository contains community packages.
