### ISSUE TITLE
librt missing from ath79/nand in openWRT v21.02.0-rc3

### ISSUE THREAD

**Issue by Psilovybin** [openwrt/packages#16048]
not a crazy big deal, and not a show stopper but librt is missing

**Comment by karlp** [comment]
Probably the same as whatever is causing: https://github.com/openwrt/packages/issues/16001

**Comment by Psilovybin** [comment]
> Probably the same as whatever is causing: #16001

worked perfectly, thank you

**Comment by karlp** [comment]
what worked perfectly? having to go and fetch the files manually from /generic?
