### ISSUE TITLE
yggdrasil: Please, update this package

### ISSUE THREAD

**Issue by strannik-j** [openwrt/packages#16064]
Please, update yggdrasil package to 0.4.0.
Old versions are not compatible with new release.

**Comment by StudioMaX** [comment]
I doubt that yggdrasil even be updated in 19.07, but I hope that at least in 21.02-rc. Now the presence of version 0.3.x only complicates the situation.

**Comment by strannik-j** [comment]
I have compiled the Yggdrasil binaries for several platforms, I can share them.

**Comment by r4sas** [comment]
@neheb, can package be updated in stable releases due to breaking changes in yggdrasil, which make old versions incompatible with new one? (requesting it like Stable Release Update in Ubuntu)

**Comment by neheb** [comment]
Backported to 21.02 and 19.07. Hopefully nothing breaks.
