### ISSUE TITLE
mwan3: iface 15 exit sooner when disabled

### ISSUE THREAD

**Issue by wulfy23** [openwrt/packages#16129]
Maintainer: @feckert @aaronjg 
Environment: na
Description: is it possible to exit a little sooner (when mwan3 is off) prior to sourcing all the functions>procd_lock>mwan3_init? carried this local 'quick' fix for a while... 
(you may need some other meta-data handling here on 'just-disabled/stop confition'?)

```
if ! /etc/init.d/mwan3 running && ! /etc/init.d/mwan3 enabled; then
    exit 0
fi

. /lib/functions.sh
...
init ...
```

**Comment by feckert** [comment]
You could check if the tracker for the interface has been started.
However, this only works if a tracker is configured and is also enabled.
`ubus call service list "{'name':'mwan3', 'verbose': true}"`

The way you do it doesn't work with this [line](https://github.com/openwrt/packages/blob/master/net/mwan3/files/etc/hotplug.d/iface/15-mwan3#L26) I think.

What do you need that for?

**Comment by wulfy23** [comment]
Thanks for the tip...

Just minimising code loading/parsing when disabled (overall system minimalism)

Afaik, there are no negative effects letting the following events to proceed... Seemed it could be a little lighter is all...

**Comment by feckert** [comment]
Ok let's close this. From my point of view, this is done or not relevant and not an issue.
