### ISSUE TITLE
kamailio: incorrect -march specified for compile.

### ISSUE THREAD

**Issue by ByteEnable** [openwrt/packages#16135]
Maintainer:  jiri@slachta.eu

Environment:  ARMv7-A (cortex-a9), WRT3200ACM,  r17127-99a22d48f2

Description: kamailio compile is selecting the incorrect arm architecture for the compile.
```
cc1: warning: switch '-mcpu=cortex-a9' conflicts with '-march=armv5t' switch
```
PKG_NAME:=kamailio
PKG_VERSION:=5.5.0
PKG_RELEASE:=1

PKG_SOURCE_URL:=https://www.kamailio.org/pub/kamailio/$(PKG_VERSION)/src
PKG_SOURCE:=kamailio-$(PKG_VERSION)_src.tar.gz
PKG_HASH:=d51cc08d20338fbb41f17d4fd2e4c4b67508c74f44613f0bd0c65269ff3557a3
PKG_USE_MIPS16:=0

PKG_LICENSE:=GPL-2.0+
PKG_LICENSE_FILES:=COPYING
PKG_MAINTAINER:=Jiri Slachta <jiri@slachta.eu>

**Comment by neheb** [comment]
This belongs in the telephony repo. Anyway, There's a linked PR fixing your issue.
