### ISSUE TITLE
adblock for multiple dnsmasq instances.

### ISSUE THREAD

**Issue by professor-jonny** [openwrt/packages#16204]
Can adblock be upgraded to read the option confidir from config\dhcp in stead of overwriting curent confdir settings?

Currnetly adblock generates a blocklist and places it in option confdir as defined in the luci settings page.
When it does this it overwrites the option config dir setting in config\dhcp overwriting my custom settings it would be nice if it could read this setting from config\dhcp and place the blocklist there by me picking an instance to apply the settings to.

I'm trying to use adblock to generate black and white lists across different dnsmasq interfaces but it tends to be hard to do as 
 I have to type in the confdir manually each time and no where in luci does it actually show the configdir option in luci for dnsmasq.

I understand this is so it auto enables and operates with minimal user intevention but it makes it hard to make maunal changes or to manually make a config for a specific instance as it is very easy to misspell something and then overwriting settings in an interface unintentianally.

Ultimatly it would be best to have adblock settings for each instance of dnsmasq straight from luci, I currnetly do this manually  by stopping the service change the settings and then restart the service for each instance.

**Comment by dibdot** [comment]
I've already answered this in the forum. Always change the pair of parameters: 'adb_dnsdir' and 'adb_dnsinstance' in your different configs. Adblock doesn't support multiple instances internally and I don't plan to support such complex setups.
