### ISSUE TITLE
luci-app-attendedsysupgrade: Seeking better error message if no upgrade available

### ISSUE THREAD

**Issue by richb-hanover** [openwrt/packages#16214]
Maintainer: @aparcar  
Environment: Using OpenWrt 21.02.0-rc3 on Netgear WNDR3800. (See the full git hash in the screen shot)

Description:

I had installed 21.02.0-rc3 and luci-app-attendedsysupgrade. I then went to see what would happen if I tried to sysupgrade. It did the "right thing" (since the device was up to date), but I have these two comments:

1. It would be better to say something like, "You are using the most recent version available - 21.02.0-rc3"

2. The dropdown goes a bit outside the modal window on a narrow screen.

![image](https://user-images.githubusercontent.com/1094930/126867796-cc03a9d2-f541-4ebe-b399-49cfe3cfd890.png)

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/luci/commit/7f5becc69e004f831c9dc09e0859c179b439c7d2
