### ISSUE TITLE
boost: fails to build on mpc85xx + uClibc

### ISSUE THREAD

**Issue by sairon** [openwrt/packages#1621]
It seems that boost is not available for mpc85xx architecture, while it's available for other ones. After some searching, I found out that problem might be the same as reported in Buildroot few months ago: https://patchwork.ozlabs.org/patch/472878/

@ClaymorePT, can you decide what to do - whether to disable failing libraries for mpc85xx or to include the proposed patch?

Also, can anyone tell me (maybe @jow-, @sbyx or @thess), where can I find what package builds are currently failing? It seems to me that buildbot broken packages page (e.g. http://buildbot.openwrt.org:8010/broken_packages/mpc85xx/) contains only results for openwrt trunk + latest packages, where boost builds fine, probably because there's musl instead of uClibc.

**Comment by ClaymorePT** [comment]
I will look into it ASAP.

On 27 July 2015 at 14:18, Jan Čermák <notifications@github.com> wrote:

> It seems that boost is not available for mpc85xx architecture, while it's
> available for other ones. After some searching, I found out that problem
> might be the same as reported in Buildroot few months ago:
> https://patchwork.ozlabs.org/patch/472878/
>
> @ClaymorePT <https://github.com/ClaymorePT>, can you decide what to do -
> whether to disable failing libraries for mpc85xx or to include the proposed
> patch?
>
> Also, can anyone tell me (maybe @jow- <https://github.com/jow->, @sbyx
> <https://github.com/sbyx> or @thess <https://github.com/thess>), where
> can I find what package builds are currently failing? It seems to me that
> buildbot broken packages page (e.g.
> http://buildbot.openwrt.org:8010/broken_packages/mpc85xx/) contains only
> results for openwrt trunk + latest packages, where boost builds fine,
> probably because there's musl instead of uClibc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openwrt/packages/issues/1621>.
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Comment by ClaymorePT** [comment]
BTW, did you try to compile Boost.Log using the regular glibc for that
target?
The report mentions a build attempt using uclibc. Does it build when using
glibc?
I would hate to disable that target due to incompatibility with uclibc.

On 27 July 2015 at 15:20, Carlos Ferreira <carlosmf.pt@gmail.com> wrote:

> I will look into it ASAP.
>
> On 27 July 2015 at 14:18, Jan Čermák <notifications@github.com> wrote:
>
>> It seems that boost is not available for mpc85xx architecture, while it's
>> available for other ones. After some searching, I found out that problem
>> might be the same as reported in Buildroot few months ago:
>> https://patchwork.ozlabs.org/patch/472878/
>>
>> @ClaymorePT <https://github.com/ClaymorePT>, can you decide what to do -
>> whether to disable failing libraries for mpc85xx or to include the proposed
>> patch?
>>
>> Also, can anyone tell me (maybe @jow- <https://github.com/jow->, @sbyx
>> <https://github.com/sbyx> or @thess <https://github.com/thess>), where
>> can I find what package builds are currently failing? It seems to me that
>> buildbot broken packages page (e.g.
>> http://buildbot.openwrt.org:8010/broken_packages/mpc85xx/) contains only
>> results for openwrt trunk + latest packages, where boost builds fine,
>> probably because there's musl instead of uClibc.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openwrt/packages/issues/1621>.
>>
>
>
>
> --
>
> Carlos Miguel Ferreira
> Researcher at Telecommunications Institute
> Aveiro - Portugal
> Work E-mail - cmf@av.it.pt
> Skype & GTalk -> carlosmf.pt@gmail.com
> LinkedIn -> http://www.linkedin.com/in/carlosmferreira
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Comment by sairon** [comment]
I did not - but according to all the clues (OK with musl, OK on other architectures, plus the linked issue), it should be OK with anything else than the specific combination of uClibc + PPC target. The patch sent by Romain Naour fixes the issue but I can't decide whether it is an acceptable solution or just a hack.

You may also disable the problematic library only on the specific target but it'd require some refactoring of DefineBoostLibrary macro (because it does add all the libraries to the boost metapackage anyway).

**Comment by ClaymorePT** [comment]
I'm more inclined to disable the package for that specific combination (target + uclibc).

That patch messes with the code itself so i'm reluctant in accepting it without the approval of the Boost devs. Since uclibc is an outdated lib and no longer maintained, it should be avoided whenever possible.

**Comment by ClaymorePT** [comment]
FYY
https://github.com/openwrt/packages/pull/1628

**Comment by sairon** [comment]
Great, thanks. It think it should be also backported to for-15.05 branch to make boost available on mpc85xx.

And I'm still hoping to receive an answer for my question if/where I can check for failing builds of CC packages.

**Comment by sbyx** [comment]
@sairon release builds are done manually and usually someone will come around and open a ticket if a package is failing.

**Comment by sairon** [comment]
Thanks @sbyx, so it seems that boost on mpc85xx dropped off the radar...

**Comment by ClaymorePT** [comment]
Yes @sairon. Its a matter of bug reporting, when someone hits a problem. In this specific case, it was the combination of target and uclibc.
I myself, don't use uclibc any more, due to incompatibilities with Python. Since the embedded devices to which I develop, have more than 100MB in storage, I opted to use glibc.

**Comment by ClaymorePT** [comment]
FYY
https://github.com/openwrt/packages/pull/1991

**Comment by ClaymorePT** [comment]
@thess this issue can be closed. Can you do it please?

**Comment by thess** [comment]
@sairon - Issue is over 1 yr old and uClibc no longer supported. Closing this.

If there is still any issues with the current version and target support, please open a new issue. Better yet, submit a new PR to solve the problem.
