### ISSUE TITLE
HTTPS-DNS-PROXY doesn't let router works if WAN is disconnected

### ISSUE THREAD

**Issue by desigabri** [openwrt/packages#16222]
Maintainer: @stangri

Environment: Qualcomm Atheros IPQ806X, Archer C2600 v1, "21.02, Master

Description:

 I found the trouble was https-dns-proxy and not of others packages. I had to uninstall it to have my routers working well back and after that remove the package from firmware images.

 The problem shows itself when there isn't connection at the WAN port.  The router becomes inacessible from LAN.
 I tried just disabling the service but anyway it is enabled at boot by default. So the only way I had to solve this trouble was to forget this package. In the paste, because I couldn't understand if it was due to any kind of incompatibility issue with nginx service I opened tickets for all two in the past. Now I can say that the matter is https-dns-proxy.

**Comment by stangri** [comment]
Thanks for your feedback. Could you please elaborate on:

> The router becomes inacessible from LAN.

Please describe in detail what's happening. Does it not provide IP via DHCP, does it not reply to SSH/WebUI request, how are you accessing it (name or IP address)?

> The problem shows itself when there isn't connection at the WAN port.

Have you installed `https-dns-proxy` on the router which permanently does not have WAN access? Is your WAN access flakey or do you manually bring WAN interface down every now and then?

> I tried just disabling the service but anyway it is enabled at boot by default.

I've just tested on OpenWrt 21.02.0-rc3 and `service <servicename> disable` or `/etc/init.d/servicename disable` doesn't actually disable any services. However `chmod -x /etc/init.d/servicename` seems to work. This issue doesn't seem to be `https-dns-proxy` exclusive.

**Comment by desigabri** [comment]
Thanks for your feedback. Could you please elaborate on:

    _The router becomes inacessible from LAN._

**Please describe in detail what's happening. Does it not provide IP via DHCP, does it not reply to SSH/WebUI request, how are you accessing it (name or IP address)?**

1) BOOT with WAN cable disconnected:
It provides IP
Login page OK but after login it becomes stuck (web access)
It is possible acces by SSH

2)Connect Cable to WAN:
 it starts working after less then 1 minute

3) disconnect cable from WAN
it loose web access after some time 1 minute or little more.

4) BOOT with WAN cable connected 
all goes right

    _The problem shows itself when there isn't connection at the WAN port._

**Have you installed https-dns-proxy on the router which permanently does not have WAN access? Is your WAN access flakey or do you manually bring WAN interface down every now and then?**

I use routers connected to WAN but I test firmwares with router alone and disconnected (I don't want lose internet access if firmware has problems). I use also router portable to connect to AP sharing internet on LAN and wifi and I can't access it and configure it without WAN. it's frustrating

    _I tried just disabling the service but anyway it is enabled at boot by default._

**I've just tested on OpenWrt 21.02.0-rc3 and service <servicename> disable or /etc/init.d/servicename disable doesn't actually disable any services. However chmod -x /etc/init.d/servicename seems to work. This issue doesn't seem to be https-dns-proxy exclusive.**

I'm able to disable the service if the router is already connected to WAN but I used to try the firmwares onto alone routers before installing the firmware onto working ones.

**Comment by stangri** [comment]
I can't reproduce, I pulled the WAN cable out of my router, waited a minute or so and could still access WebUI just fine. I'll try to find the time to experiment with the WAN cable being disconnected for more than a few minutes sometime later this week.

**Comment by stangri** [comment]
@desigabri Do you know how to use SDK to build an individual package? If I were to build one for you, do you know how to download and install it on your router?

**Comment by desigabri** [comment]
I think I'll be able to install It if you give me the package. I never used
SDK but I compiled packages with the firmware. Will It Be different if
compiled trought SDK?

Il gio 29 lug 2021, 22:01 Stan Grishin ***@***.***> ha
scritto:

**Comment by desigabri** [comment]
hi stangri, I just compiled firmware and  now I can connect to the modem also without WAN connected, thanks
