### ISSUE TITLE
znc: Add znc-push module

### ISSUE THREAD

**Issue by hethhhhh** [openwrt/packages#16243]
Maintainer: @KanjiMonster
Environment: any

Description:
Add znc-mod-znc-push package for module: https://github.com/jreese/znc-push
the znc-push module is really what's missing for ZNC/IRC and this module supports a lot of protocols and is opensource, and pretty stable.
compiling on OpenWRT is not really possible due to low ram and storage limitations / missing packages

Thank you!

**Comment by BKPepe** [comment]
It seems that no one is interested in adding this package to this repository. 

You can try to request it on [OpenWrt forum](https://forum.openwrt.org/) or try to compile the package yourself based on [the documentation](https://openwrt.org/docs/guide-developer/toolchain/single.package) and then add it here.

Closing.
