### ISSUE TITLE
libubox: build fail, @Raspberry pi 4 model b @ Ubuntu Server 21.04

### ISSUE THREAD

**Issue by stupid0319** [openwrt/packages#16241]
Raspberry pi 4 model b @ Ubuntu Server 21.04

Linux ubuntu 5.11.0-1015-raspi #16-Ubuntu SMP PREEMPT Wed Jul 14 11:04:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

libubox Already up to date.
--- get a build error ---
root@ubuntu:/home/gk/util/libubox/build# make ubox
[  6%] Building C object CMakeFiles/ubox.dir/blobmsg.c.o
In file included from /usr/include/string.h:519,
                 from /home/gk/util/libubox/blob.h:25,
                 from /home/gk/util/libubox/blobmsg.h:20,
                 from /home/gk/util/libubox/blobmsg.c:16:
In function ‘strcpy’,
    inlined from ‘blobmsg_new’ at /home/gk/util/libubox/blobmsg.c:187:2:
/usr/include/aarch64-linux-gnu/bits/string_fortified.h:79:10: error: ‘__builtin_strcpy’ offset 6 from the object at ‘attr’ is out of the bounds of referenced subobject ‘name’ with type ‘uint8_t[]’ {aka ‘unsigned char[]’} at offset 6 [-Werror=array-bounds]
   79 |   return __builtin___strcpy_chk (__dest, __src, __glibc_objsize (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/gk/util/libubox/blobmsg.c:16:
/home/gk/util/libubox/blobmsg.c: In function ‘blobmsg_new’:
/home/gk/util/libubox/blobmsg.h:41:10: note: subobject ‘name’ declared here
   41 |  uint8_t name[];
      |          ^~~~
cc1: all warnings being treated as errors
make[3]: *** [CMakeFiles/ubox.dir/build.make:121: CMakeFiles/ubox.dir/blobmsg.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:231: CMakeFiles/ubox.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:238: CMakeFiles/ubox.dir/rule] Error 2
make: *** [Makefile:235: ubox] Error 2

**Comment by neheb** [comment]
This belongs at https://bugs.openwrt.org
