### ISSUE TITLE
Missing mini-snmpd on github maintained

### ISSUE THREAD

**Issue by Himan2001** [openwrt/packages#1625]
I miss since long time the package "mini-snmpd" in the list of actual packages on github.

In case of routers with small flash, this package is the only way, to have a basic snmp support.
the regulary snmp package is still to large to fit many 4MB flash requierements on some routers.

Can someone please maintain and import this package and add this nice working
older 64bit-patch from this ticket:

https://dev.openwrt.org/ticket/13597

This solves the counter-problems by reaching 4GB on every interface and does his job
perfectly since a few years in my case on different platforms.

**Comment by hnyman** [comment]
the package has been imported by https://github.com/openwrt/packages/commit/92a5a13aa05ae495ac94a081fe8f745a21919761 and can be found at https://github.com/openwrt/packages/tree/master/net/mini_snmpd
