### ISSUE TITLE
gpsd: GPSD time will jump back 1024 weeks at after week=2180 (23-October-2021)

### ISSUE THREAD

**Issue by micmac1** [openwrt/packages#16272]
Maintainer: @psidhu 
Environment: all

Description:

Hi all,

Seems like there is a bug in gpsd 3.20, 3.21 and 3.22. OpenWrt packages has:

master: 3.21
openwrt-21.03: 3.21

Other branches have older releases. It seems that upstream will release 3.23 shortly.

[Announcement on gpsd-users](https://lists.nongnu.org/archive/html/gpsd-users/2021-07/msg00066.html)
[Gitlab issue](https://gitlab.com/gpsd/gpsd/-/issues/144)

Kind regards,
Seb

**Comment by tofurky** [comment]
@psidhu gpsd 3.23 was released yesterday which fixes this

**Comment by micmac1** [comment]
gpsd updated in master and 21.02. Closing.
