### ISSUE TITLE
strongswan: install error with the new eap-tls module

### ISSUE THREAD

**Issue by sbach** [openwrt/packages#1629]
It seems we cannot compile strongswan-default anymore after 9298d1d4.
The install target will try to copy the 'libtls.so.*' files generated but those exists only if the strongswan-eap-tls module is enabled. As this is not a dependency of the default package the file can be missing.

```
$(CP) $(PKG_INSTALL_DIR)/usr/lib/ipsec/{libtls.so.*,libstrongswan.so.*,libhydra.so.*} $(1)/usr/lib/ipsec/
```

**Comment by sbyx** [comment]
https://github.com/openwrt/packages/pull/1680 should have fixed this.
