### ISSUE TITLE
ddns-script: njalla support

### ISSUE THREAD

**Issue by himekifee** [openwrt/packages#16311]
Maintainer: @chris5560 (find it by checking history of the package Makefile)
Environment: x86_64, VM, 21.02-rc3

Description:

[Njalla](https://njal.la/) is a privacy-aware domain service. It provides DDNS functionality, which can be found [here](https://njal.la/docs/ddns/). It would be great if this ddns can be supported since it is a perfect domain service for privacy.

**Comment by tobiaspc** [comment]
See https://github.com/openwrt/packages/pull/20467
