### ISSUE TITLE
opencv fails to build (buildbot) - probably cmake or toolchain bug

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#1633]
saw this locally and on 
buildbot on different arch/compiler versions (4.8,4.6):

musl+gcc4.8:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/opencv/compile.txt
http://buildbot.openwrt.org:8010/broken_packages/brcm2708/opencv/compile.txt

uclibc+gcc4.6:
http://buildbot.openwrt.org:8010/broken_packages/octeon/opencv/compile.txt

```

arm-openwrt-linux-muslgnueabi/lib/crt1.o: In function `_start':
(.text+0x38): undefined reference to `main'

/libc/sysdeps/linux/mips/crt1.S:95: undefined reference to `main'
collect2: ld returned 1 exit status
```

A native build on alpine linux with 
musl libc, gcc 4.9.2 and cmake 3.2.2 is successful

**Comment by plntyk** [comment]
building OpenWrt with a tools/cmake 3.3.0 results in the same error

**Comment by plntyk** [comment]
http://paste.debian.net/288353/ non-working vs. working

**Comment by KanjiMonster** [comment]
@dmrlsn
