### ISSUE TITLE
jq: Current version 1.6 is awfully slow

### ISSUE THREAD

**Issue by Fanfwe** [openwrt/packages#16353]
Maintainer: @ratkaj
Environment: any

Description:
jq in its version 1.6 has got a change which gives it a very bad performance. This is especially visible in the OpenWRT world as the target platforms often feature low end CPUs.

As an example, running this basic command:
`
echo '{}' | jq
`
On my ATH79 based device takes over a second (!) when it literally was instant with the previous 1.5 version.

jq upstream is aware of the problem, has acknowledged it and even fixed it. See https://github.com/stedolan/jq/issues/1826

Problem is this is only fixed in master but there hasn't been any new release, although the fix has been there for over two years now.

So I'm writing this ticket because I'm willing to submit a pull request in order to get this fixed in OpenWRT, but I'd like to know what approach would be preferred.

I can think of two ways:

- Changing the Makefile so that it pulls a version from a more recent commit instead of the 1.6 tag. This means we will no longer have a true 1.6 but something newer instead. For reference, this is the approach that has been taken by buildroot: https://github.com/buildroot/buildroot/commit/b640c6d4cff5b6fd8480aeebc630443b6ca09b2a
- Leaving the Makefile as is, but instead backport the fix (and just that) into a patch file

Let me know what you think

**Comment by BKPepe** [comment]
Hi,

I think backporting the fix into a patch file sounds good until `jq` will release a new version.
