### ISSUE TITLE
Remove outdated "release" tag

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#16386]
Hi, there is a very outdated release tag for 14.07, never followed by anything else. Anyone mind I remove that or should we start tagging releases here?

https://github.com/openwrt/packages/releases

**Comment by feckert** [comment]
From my point of view, we have branches for the individual releases, so we don't need that.

**Comment by BKPepe** [comment]
The same is related to [LuCI repository](https://github.com/openwrt/luci) as well. If @jow- agrees with it, then we can remove it or the mirroring from [git-web](https://git.openwrt.org/) can be improved to mirror tags.
