### ISSUE TITLE
why the  lasts acme.sh timeout 求大佬指路

### ISSUE THREAD

**Issue by honghuzhi** [openwrt/packages#16467]
安装了最新的脚本，好像自动申请 zerossl，但一直超时，请问是一定要额外去注册zerossl的账户才行吗？

root@hong:~# acme.sh --issue --dns dns_namesilo --dnssleep 900 -d xxxx.xyz -d *.xxxx.xyz
[Thu 26 Aug 2021 07:06:56 PM CST] Using CA: https://acme.zerossl.com/v2/DV90
[Thu 26 Aug 2021 07:06:57 PM CST] Create account key ok.
[Thu 26 Aug 2021 07:06:57 PM CST] No EAB credentials found for ZeroSSL, let's get one
[Thu 26 Aug 2021 07:06:58 PM CST] Registering account: https://acme.zerossl.com/v2/DV90
[Thu 26 Aug 2021 07:07:00 PM CST] Registered
[Thu 26 Aug 2021 07:07:00 PM CST] ACCOUNT_THUMBPRINT='IxOjgIpk2D60Vbx8sHQhYLFq_bL4YpFfXiGiUTE_'
[Thu 26 Aug 2021 07:07:00 PM CST] Creating domain key
[Thu 26 Aug 2021 07:07:00 PM CST] The domain key is here: /root/.acme.sh/xxxx.xyz/xxxx.xyz.key
[Thu 26 Aug 2021 07:07:00 PM CST] Multi domain='DNS:xxxx.xyz,DNS:*.xxxx.xyz'
[Thu 26 Aug 2021 07:07:00 PM CST] Getting domain auth token for each domain
[Thu 26 Aug 2021 07:07:02 PM CST] Getting webroot for domain='xxxx.xyz'
[Thu 26 Aug 2021 07:07:02 PM CST] Getting webroot for domain='*.xxxx.xyz'
[Thu 26 Aug 2021 07:07:02 PM CST] Adding txt value: hF1lbJ8r-mrc3qsH99_ZT0AAG88Hhug_mZfKxqsZ for domain:  _acme-challenge.xxxx.xyz
[Thu 26 Aug 2021 07:07:04 PM CST] Successfully added TXT record, ready for validation.
[Thu 26 Aug 2021 07:07:04 PM CST] The txt record is added: Success.
[Thu 26 Aug 2021 07:07:04 PM CST] Adding txt value: -JY6NBJEJBvP8ZMLxAO5xtbA7161-MQw9sw for domain:  _acme-challenge.xxxx.xyz
[Thu 26 Aug 2021 07:07:05 PM CST] Successfully added TXT record, ready for validation.
[Thu 26 Aug 2021 07:07:05 PM CST] The txt record is added: Success.
[Thu 26 Aug 2021 07:07:05 PM CST] Sleep 900 seconds for the txt records to take effect
[Thu 26 Aug 2021 07:22:11 PM CST] Verifying: xxxx.xyz
[Thu 26 Aug 2021 07:22:12 PM CST] The replay Nonce is not valid, let's get a new one, Sleeping 1 seconds.
[Thu 26 Aug 2021 07:22:15 PM CST] Processing, The CA is processing your order, please just wait. (1/30)
[Thu 26 Aug 2021 07:22:18 PM CST] Processing, The CA is processing your order, please just wait. (2/30)
[Thu 26 Aug 2021 07:22:21 PM CST] Processing, The CA is processing your order, please just wait. (3/30)
[Thu 26 Aug 2021 07:22:23 PM CST] Processing, The CA is processing your order, please just wait. (4/30)
[Thu 26 Aug 2021 07:22:26 PM CST] Processing, The CA is processing your order, please just wait. (5/30)
[Thu 26 Aug 2021 07:22:29 PM CST] Processing, The CA is processing your order, please just wait. (6/30)
[Thu 26 Aug 2021 07:22:31 PM CST] Processing, The CA is processing your order, please just wait. (7/30)
[Thu 26 Aug 2021 07:22:34 PM CST] Processing, The CA is processing your order, please just wait. (8/30)
[Thu 26 Aug 2021 07:22:37 PM CST] Processing, The CA is processing your order, please just wait. (9/30)
[Thu 26 Aug 2021 07:22:39 PM CST] Processing, The CA is processing your order, please just wait. (10/30)
[Thu 26 Aug 2021 07:22:42 PM CST] Processing, The CA is processing your order, please just wait. (11/30)
[Thu 26 Aug 2021 07:22:45 PM CST] Processing, The CA is processing your order, please just wait. (12/30)
[Thu 26 Aug 2021 07:22:47 PM CST] Processing, The CA is processing your order, please just wait. (13/30)
[Thu 26 Aug 2021 07:22:50 PM CST] Processing, The CA is processing your order, please just wait. (14/30)
[Thu 26 Aug 2021 07:22:53 PM CST] Processing, The CA is processing your order, please just wait. (15/30)
[Thu 26 Aug 2021 07:22:56 PM CST] Processing, The CA is processing your order, please just wait. (16/30)
[Thu 26 Aug 2021 07:22:58 PM CST] Processing, The CA is processing your order, please just wait. (17/30)
[Thu 26 Aug 2021 07:23:01 PM CST] Processing, The CA is processing your order, please just wait. (18/30)
[Thu 26 Aug 2021 07:23:04 PM CST] Processing, The CA is processing your order, please just wait. (19/30)
[Thu 26 Aug 2021 07:23:06 PM CST] Processing, The CA is processing your order, please just wait. (20/30)
[Thu 26 Aug 2021 07:23:09 PM CST] Processing, The CA is processing your order, please just wait. (21/30)
[Thu 26 Aug 2021 07:23:12 PM CST] Processing, The CA is processing your order, please just wait. (22/30)
[Thu 26 Aug 2021 07:23:14 PM CST] Processing, The CA is processing your order, please just wait. (23/30)
[Thu 26 Aug 2021 07:23:17 PM CST] Processing, The CA is processing your order, please just wait. (24/30)
[Thu 26 Aug 2021 07:23:19 PM CST] Processing, The CA is processing your order, please just wait. (25/30)
[Thu 26 Aug 2021 07:23:22 PM CST] Processing, The CA is processing your order, please just wait. (26/30)
[Thu 26 Aug 2021 07:23:24 PM CST] Processing, The CA is processing your order, please just wait. (27/30)
[Thu 26 Aug 2021 07:23:27 PM CST] Processing, The CA is processing your order, please just wait. (28/30)
[Thu 26 Aug 2021 07:23:29 PM CST] Processing, The CA is processing your order, please just wait. (29/30)
[Thu 26 Aug 2021 07:23:32 PM CST] xxxx.xyz:Timeout
[Thu 26 Aug 2021 07:23:32 PM CST] Removing DNS records.
[Thu 26 Aug 2021 07:23:32 PM CST] Removing txt: hF1lbJ8r-mrc3qsH99_ZT0AAG88Hhug_mZfKxqsZMVw for domain: _acme-challenge.xxxx.xyz
[Thu 26 Aug 2021 07:23:33 PM CST] Successfully retrieved the record id for ACME challenge.
[Thu 26 Aug 2021 07:23:34 PM CST] Successfully removed the TXT record.
[Thu 26 Aug 2021 07:23:34 PM CST] Removed: Success
[Thu 26 Aug 2021 07:23:34 PM CST] Removing txt: -JY6NBJEJBvP8ZMLxAO5xtbA7161-MQw9syUwDxDZ-w for domain: _acme-challenge.xxxx.xyz
[Thu 26 Aug 2021 07:23:35 PM CST] Successfully retrieved the record id for ACME challenge.
[Thu 26 Aug 2021 07:23:36 PM CST] Successfully removed the TXT record.
[Thu 26 Aug 2021 07:23:36 PM CST] Removed: Success
[Thu 26 Aug 2021 07:23:36 PM CST] Please add '--debug' or '--log' to check more details.
[Thu 26 Aug 2021 07:23:36 PM CST] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

**Comment by BKPepe** [comment]
There isn't respond from OP and it seems that it was related to the DNS server, which time outed. Closing.
