### ISSUE TITLE
libstdcpp6 missing 

### ISSUE THREAD

**Issue by dirk99** [openwrt/packages#16487]
Hi folks,

i wan't to install php7-cli, but libstdcpp6 is missing. 

Thanks

**Comment by feckert** [comment]
There is only the package libstdcpp.
I think it's the ABI version. https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/package/libs/toolchain/Makefile#L90
What exactly does your error message look like?

**Comment by vlna** [comment]
Similar here, OpenWrt 21.02.0, r16279-5cc0535800 and I want to install _zerotier_ package

![2021-09-19 22 46 19 192 168 128 1 6c141d54ec68](https://user-images.githubusercontent.com/8721731/133942604-3860d13d-3947-419f-9121-e114e34325fc.png)

**Comment by vlna** [comment]
Solution/workaroud:
```
cd /tmp
wget https://downloads.openwrt.org/releases/21.02.0/targets/ath79/generic/packages/libstdcpp6_8.4.0-3_mips_24kc.ipk
opkg install libstdcpp6_8.4.0-3_mips_24kc.ipk
```
After this I was able to install _zerotier_ package

**Comment by Rygle** [comment]
I did a similar workaround to @vlna, but I believe there are different versions of the package, so be careful!
Another version is here - https://downloads.openwrt.org/releases/21.02.0/targets/ipq806x/generic/packages/libstdcpp6_8.4.0-3_arm_cortex-a15_neon-vfpv4.ipk

**Comment by hnyman** [comment]
Related to old version.
The package seems to be in the 21.02.5 (and 21.02.0) download directory.
