### ISSUE TITLE
ieee8021xclient: wpad only dependency limitation

### ISSUE THREAD

**Issue by wulfy23** [openwrt/packages#16525]
Maintainer: @yangfl
Environment: recent master all

Description: ieee8021xclient has a singular dependency on wpad ... this creates a conflict when other fully featured wpad bundles/hostapd are selected which afaik would also support the featureset...

```
define Package/ieee8021xclient
  SECTION:=net
  CATEGORY:=Network
  MAINTAINER:=David Yang <mmyangfl@gmail.com>
  TITLE:=Wired 802.1x client config support
  DEPENDS:=+wpad
  PKGARCH:=all
endef
```

**Comment by dangowrt** [comment]
Imho `ieee8021xclient` should depend on `wpa_supplicant` which is provided by all variants of `wpa_supplicant` and `wpad`.

**Comment by ptpt52** [comment]
@wulfy23 @neheb @yangfl 
```
WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
```

**Comment by azgh** [comment]
> @wulfy23 @neheb @yangfl
> 
> ```
> WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
> ```

I had the same problem.
