### ISSUE TITLE
`uqmi` missing in 21.02 (LTE usb dongle driver)

### ISSUE THREAD

**Issue by cybermaus** [openwrt/packages#16534]
Its still there in 19

On 21.02 (on a TP-Link C7 v2), trying to install package luci-proto-qmi it it tells me "Required dependency package uqmi is not available in any repository." And indeed, `uqmi` cannot be found.

I tried 21.02 rc4 first, and then realised final is out and tried 21.02 final too. `uqmi` is missing in both.

**Comment by feckert** [comment]
I have not tried it, but a search on the download page shows me, that uqmi package is available for download.
https://downloads.openwrt.org/releases/21.02.0-rc4/targets/ath79/generic/packages/
By the way this is a core package. If you still have the issue please open a bug ticket on https://bugs.openwrt.org/
