### ISSUE TITLE
tinyproxy DisableViaHeader option

### ISSUE THREAD

**Issue by gthreepw00d** [openwrt/packages#1656]
The option is not processed in /etc/init.d/tinyproxy

**Comment by gthreepw00d** [comment]
AddHeader too

**Comment by gthreepw00d** [comment]
Probably convenient to simply append /etc/tinyproxy_custom.conf

**Comment by diizzyy** [comment]
@gthreepw00d 
Can you provide a pull request?

**Comment by diizzyy** [comment]
Closing due to timeout
