### ISSUE TITLE
lighttpd: 1.4.36 regression: uploading 4 MiB+ files results in 413 - Request Entity Too Large

### ISSUE THREAD

**Issue by rmilecki** [openwrt/packages#1658]
Starting with Michael commit:
https://github.com/openwrt/packages/commit/1e2bf20acf9e4f9a89fb43697c28fd5627c79985
OpenWrt uses lighttpd 1.4.36.

Unfortunately there is some upstream issue breaking upload of files bigger than 4 MiB. For the upstream report please see:
http://article.gmane.org/gmane.comp.web.lighttpd/5370

This can be workarounded by bumping server.max-fds to some higher value than the default 1024. More details about a proper fix aren't know yet.

We may consider changing default lighttpd config (to include a proper server.max-fds setting) or backporting a fix if it appears. I'm not sure how safe is it to downgrade lighttpd, it's probably not the best idea.

**Comment by Zajec** [comment]
Upstream bug has been fixed: http://redmine.lighttpd.net/issues/2660

Patch was backported and posted on the openwrt-devel mailing list: https://lists.openwrt.org/pipermail/openwrt-devel/2015-August/035137.html
