### ISSUE TITLE
adguardhome: panic: qtls.ClientHelloInfo doesn't match

### ISSUE THREAD

**Issue by foxcris** [openwrt/packages#16594]
Maintainer: @dobo90
Environment: 
Openwrt Version: OpenWrt 21.02.0, r16279-5cc0535800
Hardware: fritzbox 4040

Description:
adguardhome is listed as started but no adguardhome proess is running

Executing the AdGuardHome binary manually gives the following error
```
root@owrt1:/etc/openvpn# /usr/bin/AdGuardHome --help
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x168
```

**Comment by derterz** [comment]
Same here after upgrading from an old nightly 21.02 build to 21.02.0 r16279-5cc0535800 on my Linksys MR8300 (Dallas) [ARMv7 Processor rev 5 (v7l)].

Manually downloading and running the latest version works fine: https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.106.3/AdGuardHome_linux_armv7.tar.gz

**Comment by BKPepe** [comment]
I cherry-picked all the updates related to adguardhome from the ``master`` branch into ``openwrt-21.02``. Hopefully, it will solve your issues. If yes, then please close it. If not, feel free to discuss it with the maintainer.

**Comment by predators46** [comment]
hmm. i tried on lede 17.01.x it runs fine

![Screenshot_2021-09-12_162401](https://user-images.githubusercontent.com/31931530/133251862-e547e1d9-e954-41c6-b604-935684cf8532.jpg)

**Comment by BKPepe** [comment]
LEDE 17.01.x is not supported. Supported versions are OpenWrt 19.07 and OpenWrt 21.02.

**Comment by predators46** [comment]
> LEDE 17.01.x tidak didukung. Versi yang didukung adalah OpenWrt 19.07 dan OpenWrt 21.02.



> LEDE 17.01.x is not supported. Supported versions are OpenWrt 19.07 and OpenWrt 21.02.

Yes, I know

**Comment by HinataKato** [comment]
Same, I was able to use it at 21.02.0-rc4, after upgrading to 21.02.0 it doesn't work

**Comment by foxcris** [comment]
@BKPepe how am i able to perform a test? Till now there is no updated package available via opkg. Do just have to wait a bit?

**Comment by foxcris** [comment]
The new package is now available. Unfortunately it does not resolve the issue:
````
root@owrt1:~# /usr/bin/AdGuardHome --help
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
        github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x1e0
````

**Comment by EdiTurn** [comment]
Also got this issue in master. 
Currently I change the version to 0.107.0-b.11 in Makefile, and it works well.

**Comment by Nadias-jp** [comment]
I overwrote AdguardHome and it worked.
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.106.3

```
panic: qtls.CertificateRequestInfo doesn't match
 
goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
        github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x248
```
