### ISSUE TITLE
auc: sort list of package upgrades

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#16600]
These lists are often long and so it's hard to find a package if it's not sorted. Please sort the list before printing.

![image](https://user-images.githubusercontent.com/16000931/132751462-ef635c02-39b4-4bf0-8a2d-98a127109999.png)

**Comment by aparcar** [comment]
@dangowrt ping

**Comment by dangowrt** [comment]
You really think alphabetic re-ordering is worth buffering the result in a data-structure which would have to be made just for that...? Right now the packages are simply processed in the order they are returned by `ubus call rpc-sys packagelist`...

**Comment by aparcar** [comment]
I guess it's fine without
