### ISSUE TITLE
OpenSSL 3.0.0 is out

### ISSUE THREAD

**Issue by Neustradamus** [openwrt/packages#16619]
Dear all,

The new OpenSSL generation is here: 3.0.0.

1.1.1* -> 3.0.0.

**Comment by BKPepe** [comment]
Closing as the package OpenSSL is not present in this packages repository. 

Feel free to submit pull request if you want to have it updated in the base repository here:
https://github.com/openwrt/openwrt/blob/master/package/libs/openssl/Makefile
