### ISSUE TITLE
qemu failure on x86

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#16650]
Maintainer: @yousong 
Environment: x86

ping @vooon 

https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/qemu/compile.txt

```
Package qemu-nbd is missing dependencies for the following libraries:
libfuse3.so.3
```

**Comment by vooon** [comment]
@neheb i suppose we need to add `--disable-fuse` or `+libfuse3`
```
                   FUSE exports: YES
```

**Comment by yousong** [comment]
> @neheb i suppose we need to add `--disable-fuse` or `+libfuse3`
> 
> ```
>                    FUSE exports: YES
> ```

The current Makefile `--disable-xx` such features initially and only make them available until people came and requested otherwise.

**Comment by 1715173329** [comment]
The error still remains... Any plan to fix it?
