### ISSUE TITLE
libqmi: 1.28.2 not works in openwrt 21.02

### ISSUE THREAD

**Issue by zokl** [openwrt/packages#16677]
Maintainer: @nickberry17 
Environment: (x86_64, OpenWrt 21.02)

Description:

The final release of the network infrastructure in openwrt 21.02 (https://github.com/openwrt/openwrt/tree/openwrt-21.02) is not compatible with libqmi 1.28.2. Modemmanager 1.16.2 and newer is not able to use QMI interface anymore. Next version 1.28.6 and newer works fine. Please add it to packages branch 21.02.

This issue leads to the behaviour described in #16370.

**Comment by BKPepe** [comment]
I cherry-picked related changes from `master` branch into `openwrt-21.02` branch. The packages should be compiled within 24-48 hours. Please, let me know if it works for you.

**Comment by zokl** [comment]
Thank you, now it works fine!
