### ISSUE TITLE
dropbear: Early exit: Bad buf_getptr

### ISSUE THREAD

**Issue by trazom21** [openwrt/packages#16693]
Hi,
I recently updated to 21.02 on an Archer C7 V5. Dropbear crashes at startup with these errors in system log:

Thu Sep 23 21:54:54 2021 authpriv.info dropbear[8043]: Early exit: Bad buf_getptr
Thu Sep 23 21:54:59 2021 authpriv.info dropbear[8071]: Early exit: Bad buf_getptr
Thu Sep 23 21:55:04 2021 authpriv.info dropbear[8072]: Early exit: Bad buf_getptr
Thu Sep 23 21:55:09 2021 authpriv.info dropbear[8073]: Early exit: Bad buf_getptr
Thu Sep 23 21:55:14 2021 authpriv.info dropbear[8074]: Early exit: Bad buf_getptr
Thu Sep 23 21:55:19 2021 authpriv.info dropbear[8079]: Early exit: Bad buf_getptr
Thu Sep 23 21:55:19 2021 daemon.info procd: Instance dropbear::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

So no access to ssh server. Is this issue has already been reported ? 
Thanks

**Comment by BKPepe** [comment]
Closing. Package ```dropbear``` is not present in this repository. It can be found in [the main repository](https://github.com/openwrt/openwrt/blob/master/package/network/services/dropbear/Makefile). Please follow this documentation: https://openwrt.org/bugs#reporting_bugs to take a look how you need to report bugs and where.
