### ISSUE TITLE
ieee8021xclient howto use

### ISSUE THREAD

**Issue by openips** [openwrt/packages#16759]
cloud anyone give me an example
thks

**Comment by BKPepe** [comment]
ping maintainer: @yangfl

**Comment by yangfl** [comment]
```
option proto ieee8021xclient
option identity xxxxx
option password xxxxx
```

**Comment by openips** [comment]
thks a lot

**Comment by feckert** [comment]
@yangfl could you please add a wiki entry like in https://openwrt.org/docs/guide-user/network/tunneling_interface_protocols ?
