### ISSUE TITLE
mwan3 bug with pppoe re in PKG_VERSION:=2.10.12

### ISSUE THREAD

**Issue by openips** [openwrt/packages#16837]
hello guys
I use mwan3 with commit 3d824ea with openwrt master under x64 find a  serious bug
my router have 3 pppoe wans， two of three are assigned intranet ip，one  are assigned internet ip.
the ISP will automatically connect to the terminal every 48 hours.
After the interruption, the automatic dialing succeeds. mwan3 detects that the port status is normal but with some error, and the port cannot be used to access the Internet. 
I ping -I with the automatic dialing port ,all is ok.
after I redialing by hand ,all are ok.

some log below:
**port status**
pppoe-cmcc_wan Link encap:Point-to-Point Protocol
          inet addr:10.240.88.210  P-t-P:10.240.64.1  Mask:255.255.255.255
          inet6 addr: ********:2734:35b1:4a1b:e9d5:2249/64 Scope:Global
          inet6 addr: fe80::35b1:4a1b:e9d5:2249/128 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:267223628 errors:0 dropped:439 overruns:0 frame:0
          TX packets:439167229 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:103552903030 (96.4 GiB)  TX bytes:518720349356 (483.0 GiB)

pppoe-ct_wan Link encap:Point-to-Point Protocol
          inet addr:10.16.0.233  P-t-P:10.16.0.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:106973178 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54245875 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:47359681937 (44.1 GiB)  TX bytes:20442171747 (19.0 GiB)

pppoe-cu_wan Link encap:Point-to-Point Protocol
          inet addr 123.56.187.146  P-t-P:123.56.176.1  Mask:255.255.255.255
          inet6 addr: fe80::6e28:597e:f537:adf4/128 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:16443 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3028 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:844398 (824.6 KiB)  TX bytes:253912 (247.9 KiB)

**my mwan3 file** 
cat /etc/config/mwan3

config rule 'cu_cdn'
        option proto 'all'
        option sticky '0'
        option use_policy 'cu_only'
        option family 'ipv4'
        option src_ip '192.168.1.41,192.168.1.46'

config rule 'ct_cdn'
        option family 'ipv4'
        option proto 'all'
        option sticky '0'
        option use_policy 'ct_only'
        option src_ip '192.168.1.42,192.168.1.47'

config rule 'cmcc_cdn'
        option family 'ipv4'
        option proto 'all'
        option sticky '0'
        option use_policy 'cmcc_only'
        option src_ip '192.168.1.43,192.168.1.48'

config rule 'cu_net'
        option family 'ipv4'
        option proto 'all'
        option sticky '0'
        option use_policy 'cu_only'
        option ipset 'unicom'

config rule 'ct_net'
        option family 'ipv4'
        option proto 'all'
        option use_policy 'ct_only'
        option sticky '0'
        option ipset 'chinanet'

config rule 'cmcc_net'
        option family 'ipv4'
        option proto 'all'
        option ipset 'cmcc'
        option use_policy 'cmcc_only'
        option sticky '0'

config rule 'web'
        option proto 'tcp'
        option sticky '1'
        option use_policy 'balanced'
        option family 'ipv4'
        option dest_port '80,443'
        option timeout '6000'

config rule 'load_balaced'
        option proto 'all'
        option sticky '0'
        option use_policy 'balanced'

config rule 'default_rule_v4'
        option dest_ip '0.0.0.0/0'
        option use_policy 'balanced'
        option family 'ipv4'

config rule 'default_wan'
        option family 'ipv4'
        option proto 'all'
        option sticky '0'
        option use_policy 'cu_only'

config member 'cu_m10_w3'
        option interface 'cu_wan'
        option weight '3'
        option metric '10'

config member 'ct_m20_w3'
        option interface 'ct_wan'
        option metric '20'
        option weight '5'

config member 'cmcc_m30_w3'
        option interface 'cmcc_wan'
        option metric '30'
        option weight '3'

config policy 'balanced'
        option last_resort 'unreachable'
        list use_member 'cmcc_m30_w3'
        list use_member 'ct_m20_w3'
        list use_member 'cu_m10_w3'

config policy 'cmcc_only'
        option last_resort 'unreachable'
        list use_member 'cmcc_m30_w3'

config policy 'ct_only'
        option last_resort 'unreachable'
        list use_member 'ct_m20_w3'

config policy 'cu_only'
        option last_resort 'unreachable'
        list use_member 'cu_m10_w3'

config globals 'globals'
        option mmx_mask '0x3F00'
        list rt_table_lookup '220'

config interface 'cmcc_wan'
        option enabled '1'
        option initial_state 'online'
        option family 'ipv4'
        list track_ip '114.114.114.114'
        list track_ip '223.5.5.5'
        list track_ip '8.8.8.8'
        option track_method 'ping'
        option reliability '1'
        option count '1'
        option size '56'
        option max_ttl '60'
        option check_quality '0'
        option timeout '4'
        option interval '10'
        option failure_interval '5'
        option recovery_interval '5'
        option down '5'
        option up '5'
        option keep_failure_interval '1'

config interface 'ct_wan'
        option enabled '1'
        option initial_state 'online'
        option family 'ipv4'
        list track_ip '114.114.114.114'
        list track_ip '223.5.5.5'
        list track_ip '8.8.8.8'
        option track_method 'ping'
        option reliability '1'
        option count '1'
        option size '56'
        option max_ttl '60'
        option check_quality '0'
        option timeout '4'
        option interval '10'
        option failure_interval '5'
        option recovery_interval '5'
        option down '5'
        option up '5'
        option keep_failure_interval '1'

config interface 'cu_wan'
        option initial_state 'online'
        option family 'ipv4'
        list track_ip '114.114.114.114'
        list track_ip '223.5.5.5'
        list track_ip '8.8.8.8'
        option track_method 'ping'
        option reliability '1'
        option count '1'
        option size '56'
        option max_ttl '60'
        option check_quality '0'
        option timeout '4'
        option interval '10'
        option failure_interval '5'
        option recovery_interval '5'
        option down '5'
        option up '5'
        option enabled '1'
        option keep_failure_interval '1'

**MultiWAN status**
Interface status:
 interface cmcc_wan is online 00h:26m:37s, uptime 48h:32m:45s and tracking is active
 interface ct_wan is online 00h:26m:37s, uptime 48h:32m:44s and tracking is active
 interface cu_wan is error (16) and tracking is active

Current ipv4 policies:
balanced:
 cu_wan (100%)
cmcc_only:
 cmcc_wan (100%)
ct_only:
 ct_wan (100%)
cu_only:
 cu_wan (100%)

Current ipv6 policies:
balanced:
 unreachable
cmcc_only:
 unreachable
ct_only:
 unreachable
cu_only:
 unreachable

Directly connected ipv4 networks:
123.56.187.146
192.168.100.0/24
224.0.0.0/3
192.168.200.0/24
10.16.0.1
10.240.88.210
10.240.64.1
192.168.150.0/24
10.0.0.0/24
127.0.0.0/8
123.56.176.1
192.168.1.0/24
10.16.0.233

Directly connected ipv6 networks:
fe80::4e09:b4ff:fefc:a690
fe80::6e28:597e:f537:adf4
fe80::35b1:4a1b:e9d5:2249
fe80::/64
fe80::f22f:a7ff:fe02:350a

Active ipv4 user rules:
39041 4452K - cu_only  all  --  *      *       192.168.1.41         0.0.0.0/0            
    0     0 - cu_only  all  --  *      *       192.168.1.46         0.0.0.0/0            
 3448  267K - ct_only  all  --  *      *       192.168.1.42         0.0.0.0/0            
    0     0 - ct_only  all  --  *      *       192.168.1.47         0.0.0.0/0            
11324 1380K - cmcc_only  all  --  *      *       192.168.1.43         0.0.0.0/0            
    0     0 - cmcc_only  all  --  *      *       192.168.1.48         0.0.0.0/0            
 6146  429K - cu_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set unicom dst 
 3235  206K - ct_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set chinanet dst 
 2242  149K - cmcc_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set cmcc dst 
26365 1553K S web  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443 
 8473  903K - balanced  all  --  *      *       0.0.0.0/0            0.0.0.0/0            
    0     0 - balanced  all  --  *      *       0.0.0.0/0            0.0.0.0/0            
    0     0 - cu_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            

Active ipv6 user rules:
 1103  289K - balanced  all      *      *       ::/0                 ::/0                 

Software-Version
-------------------------------------------------
OpenWrt - SNAPSHOT

Output of "ip -4 a show"
-------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.100.2/24 brd 192.168.100.255 scope global eth1
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.150.2/24 brd 192.168.150.255 scope global eth2
       valid_lft forever preferred_lft forever
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.200.2/24 brd 192.168.200.255 scope global eth3
       valid_lft forever preferred_lft forever
7: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
10: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.0.0.1/24 brd 10.0.0.255 scope global wg0
       valid_lft forever preferred_lft forever
12: pppoe-ct_wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 3
    inet 10.16.0.233 peer 10.16.0.1/32 scope global pppoe-ct_wan
       valid_lft forever preferred_lft forever
14: pppoe-cmcc_wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 3
    inet 10.240.88.210 peer 10.240.64.1/32 scope global pppoe-cmcc_wan
       valid_lft forever preferred_lft forever
17: pppoe-cu_wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 3
    inet 123.56.187.146 peer 123.56.176.1/32 scope global pppoe-cu_wan
       valid_lft forever preferred_lft forever

Output of "ip -4 route show"
-------------------------------------------------
default via 10.16.0.1 dev pppoe-ct_wan proto static metric 20 
default via 10.240.64.1 dev pppoe-cmcc_wan proto static metric 30 
10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.1 
10.0.0.2 dev wg0 proto static scope link 
10.0.0.3 dev wg0 proto static scope link 
10.0.0.5 dev wg0 proto static scope link 
10.16.0.1 dev pppoe-ct_wan proto kernel scope link src 10.16.0.233 
10.240.64.1 dev pppoe-cmcc_wan proto kernel scope link src 10.240.88.210 
123.56.176.1 dev pppoe-cu_wan proto kernel scope link src 123.56.187.146 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.100.0/24 dev eth1 proto kernel scope link src 192.168.100.2 
192.168.150.0/24 dev eth2 proto kernel scope link src 192.168.150.2 
192.168.200.0/24 dev eth3 proto kernel scope link src 192.168.200.2 

Output of "ip -4 rule show"
-------------------------------------------------
0:	from all lookup local
1001:	from all iif pppoe-cmcc_wan lookup 1
1002:	from all iif pppoe-ct_wan lookup 2
1003:	from all iif pppoe-cu_wan lookup 3
2001:	from all fwmark 0x100/0x3f00 lookup 1
2002:	from all fwmark 0x200/0x3f00 lookup 2
2003:	from all fwmark 0x300/0x3f00 lookup 3
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
3001:	from all fwmark 0x100/0x3f00 unreachable
3002:	from all fwmark 0x200/0x3f00 unreachable
3003:	from all fwmark 0x300/0x3f00 unreachable
32766:	from all lookup main
32767:	from all lookup default

Output of "ip -4 route list table 1-250"
-------------------------------------------------
Routing table 1:
default via 10.240.64.1 dev pppoe-cmcc_wan proto static metric 30 
10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.1 
10.0.0.2 dev wg0 proto static scope link 
10.0.0.3 dev wg0 proto static scope link 
10.0.0.5 dev wg0 proto static scope link 
10.240.64.1 dev pppoe-cmcc_wan proto kernel scope link src 10.240.88.210 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.100.0/24 dev eth1 proto kernel scope link src 192.168.100.2 
192.168.150.0/24 dev eth2 proto kernel scope link src 192.168.150.2 
192.168.200.0/24 dev eth3 proto kernel scope link src 192.168.200.2 

Routing table 2:
default via 10.16.0.1 dev pppoe-ct_wan proto static metric 20 
10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.1 
10.0.0.2 dev wg0 proto static scope link 
10.0.0.3 dev wg0 proto static scope link 
10.0.0.5 dev wg0 proto static scope link 
10.16.0.1 dev pppoe-ct_wan proto kernel scope link src 10.16.0.233 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.100.0/24 dev eth1 proto kernel scope link src 192.168.100.2 
192.168.150.0/24 dev eth2 proto kernel scope link src 192.168.150.2 
192.168.200.0/24 dev eth3 proto kernel scope link src 192.168.200.2 

Routing table 3:
10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.1 
10.0.0.2 dev wg0 proto static scope link 
10.0.0.3 dev wg0 proto static scope link 
10.0.0.5 dev wg0 proto static scope link 
123.56.176.1 dev pppoe-cu_wan proto kernel scope link src 123.56.187.146 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.100.0/24 dev eth1 proto kernel scope link src 192.168.100.2 
192.168.150.0/24 dev eth2 proto kernel scope link src 192.168.150.2 
192.168.200.0/24 dev eth3 proto kernel scope link src 192.168.200.2 

Output of "iptables -t mangle -w -L -v -n"
-------------------------------------------------
Chain PREROUTING (policy ACCEPT 6408K packets, 5310M bytes)
 pkts bytes target     prot opt in     out     source               destination         
6408K 5310M mwan3_hook  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 399K packets, 373M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 5958K packets, 4931M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 TCPMSS     tcp  --  *      eth3    0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  eth3   *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
45485 2729K TCPMSS     tcp  --  *      pppoe-cmcc_wan  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
42836 2383K TCPMSS     tcp  --  pppoe-cmcc_wan *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  *      eth2    0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  eth2   *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
31124 1865K TCPMSS     tcp  --  *      pppoe-ct_wan  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
26175 1550K TCPMSS     tcp  --  pppoe-ct_wan *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  *      eth1    0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  eth1   *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
    0     0 TCPMSS     tcp  --  *      pppoe-cu_wan  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
   44  1840 TCPMSS     tcp  --  pppoe-cu_wan *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU

Chain OUTPUT (policy ACCEPT 369K packets, 365M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 369K  365M mwan3_hook  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 6298K packets, 5294M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain mwan3_connected (2 references)
 pkts bytes target     prot opt in     out     source               destination         
4259K 3636M MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected dst MARK or 0x3f00

Chain mwan3_hook (2 references)
 pkts bytes target     prot opt in     out     source               destination         
6621K 5450M CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 CONNMARK restore mask 0x3f00
 142K   13M mwan3_ifaces_in  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
 136K   12M mwan3_connected  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
 105K   10M mwan3_rules  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
6777K 5675M CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0            CONNMARK save mask 0x3f00
6335K 5189M mwan3_connected  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0x3f00/0x3f00

Chain mwan3_iface_in_cmcc_wan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  pppoe-cmcc_wan *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected src mark match 0x0/0x3f00 /* default */ MARK or 0x3f00
 3668  391K MARK       all  --  pppoe-cmcc_wan *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* cmcc_wan */ MARK xset 0x100/0x3f00

Chain mwan3_iface_in_ct_wan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  pppoe-ct_wan *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected src mark match 0x0/0x3f00 /* default */ MARK or 0x3f00
 2265  374K MARK       all  --  pppoe-ct_wan *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* ct_wan */ MARK xset 0x200/0x3f00

Chain mwan3_iface_in_cu_wan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  pppoe-cu_wan *       0.0.0.0/0            0.0.0.0/0            match-set mwan3_connected src mark match 0x0/0x3f00 /* default */ MARK or 0x3f00
  554 24257 MARK       all  --  pppoe-cu_wan *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* cu_wan */ MARK xset 0x300/0x3f00

Chain mwan3_ifaces_in (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 142K   13M mwan3_iface_in_cmcc_wan  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
 138K   13M mwan3_iface_in_cu_wan  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
 138K   13M mwan3_iface_in_ct_wan  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00

Chain mwan3_policy_balanced (3 references)
 pkts bytes target     prot opt in     out     source               destination         
 8990  939K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* cu_wan 3 3 */ MARK xset 0x300/0x3f00

Chain mwan3_policy_cmcc_only (3 references)
 pkts bytes target     prot opt in     out     source               destination         
14004 1580K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* cmcc_wan 3 3 */ MARK xset 0x100/0x3f00

Chain mwan3_policy_ct_only (3 references)
 pkts bytes target     prot opt in     out     source               destination         
 7091  499K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* ct_wan 5 5 */ MARK xset 0x200/0x3f00

Chain mwan3_policy_cu_only (4 references)
 pkts bytes target     prot opt in     out     source               destination         
47639 5399K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 /* cu_wan 3 3 */ MARK xset 0x300/0x3f00

Chain mwan3_rule_web (1 references)
 pkts bytes target     prot opt in     out     source               destination         
27424 1615K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00 MARK xset 0x300/0x3f00
   50  2968 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x300/0x3f00 ! match-set mwan3_sticky_web src,src MARK and 0xffffc0ff
   50  2968 mwan3_policy_balanced  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
27424 1615K SET        all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0xfc00/0xfc00 del-set mwan3_sticky_web src,src
27424 1615K SET        all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0xfc00/0xfc00 add-set mwan3_sticky_web src,src

Chain mwan3_rules (1 references)
 pkts bytes target     prot opt in     out     source               destination         
41187 4948K mwan3_policy_cu_only  all  --  *      *       192.168.1.41         0.0.0.0/0            mark match 0x0/0x3f00
    0     0 mwan3_policy_cu_only  all  --  *      *       192.168.1.46         0.0.0.0/0            mark match 0x0/0x3f00
 3594  276K mwan3_policy_ct_only  all  --  *      *       192.168.1.42         0.0.0.0/0            mark match 0x0/0x3f00
    0     0 mwan3_policy_ct_only  all  --  *      *       192.168.1.47         0.0.0.0/0            mark match 0x0/0x3f00
11712 1428K mwan3_policy_cmcc_only  all  --  *      *       192.168.1.43         0.0.0.0/0            mark match 0x0/0x3f00
    0     0 mwan3_policy_cmcc_only  all  --  *      *       192.168.1.48         0.0.0.0/0            mark match 0x0/0x3f00
 6452  451K mwan3_policy_cu_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set unicom dst mark match 0x0/0x3f00
 3497  222K mwan3_policy_ct_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set chinanet dst mark match 0x0/0x3f00
 2292  152K mwan3_policy_cmcc_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set cmcc dst mark match 0x0/0x3f00
27424 1615K mwan3_rule_web  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443 mark match 0x0/0x3f00
 8940  936K mwan3_policy_balanced  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
    0     0 mwan3_policy_balanced  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00
    0     0 mwan3_policy_cu_only  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x0/0x3f00

Please check and fix bugs 
thk a lot

**Comment by feckert** [comment]
In the output I see [error (16)](https://github.com/openwrt/packages/blob/master/net/mwan3/files/lib/mwan3/mwan3.sh#L1055) which means this routing table no longer has a default route set?
Also in the status dump I don't see this default route for routeing table 3.

Could this be your problem?

**Comment by feckert** [comment]
@openips What was the problem?
