### ISSUE TITLE
python-pip and python-setuptools are missing their (PKG_)MAINTAINER entries

### ISSUE THREAD

**Issue by KanjiMonster** [openwrt/packages#1683]
Packages python-pip python-setuptools do not have any assigned maintainer.

@commodo since the pull requests for them were yours, please add yourself as the maintainer.

**Comment by commodo** [comment]
Created PRs https://github.com/openwrt/packages/pull/1690 and https://github.com/openwrt/packages/pull/1691
Sorry about that [forgetting]

**Comment by KanjiMonster** [comment]
Thanks for the quick response. Merged both. :)
