### ISSUE TITLE
transmission has wrong maintainer

### ISSUE THREAD

**Issue by KanjiMonster** [openwrt/packages#1685]
net/transmission still has the maintainer from the old packages feed, which does not match the pull request initiator.

@mstorchak since you added the package, please change the maintainer to yourself.

**Comment by karlp** [comment]
@mstorchak any response?

**Comment by mstorchak** [comment]
Hm. I forgot that was me :).
Sure, I'll add myself as a maintainer unless someone else would like to take over.
@dangowrt @nmav @obsy @karlp  ?

**Comment by obsy** [comment]
@mstorchak if you want - take it.

**Comment by karlp** [comment]
Not my party, I was just going over tickets looking for ones that could be closed :)

**Comment by yousong** [comment]
Hi, @mstorchak , please open a PR to resolve this
