### ISSUE TITLE
zabbit-proxy: add sqlite3 support

### ISSUE THREAD

**Issue by arkanoid87** [openwrt/packages#16868]
Maintainer: @champtar 

Once upon a time in 18.06 zabbit-proxy was made to use a local sqlite3 database, but now it requires a mysql or pgsql that are rarely used in embedded.

See https://openwrt.org/packages/pkgdata_owrt18_6/zabbix-proxy vs https://openwrt.org/packages/pkgdata/zabbix-proxy

Is this a problem or a deliberate decision?

**Comment by champtar** [comment]
Zabbix removed the support for SQLite if I remember correctly

**Comment by arkanoid87** [comment]
Is it?

https://openwrt.org/packages/pkgdata/libsqlite3-0

just tried this on a 19.07 openwrt box:
```
# opkg update
# opkg install sqlite3-cli
# sqlite3 test.db
```
and I got a sqlite3 db.

**Comment by champtar** [comment]
I said Zabbix removed support, OpenWrt still has SQLite yes but that's not enough

**Comment by arkanoid87** [comment]
I'm using pre-built images and image builder to bundle everything, but I'm ok with building ad-hoc packages too for testing.

**Comment by mbargo23** [comment]
Anything new with this issue?

**Comment by feckert** [comment]
Merged with commit https://github.com/openwrt/packages/pull/19605/files
