### ISSUE TITLE
dnsmasq-full install in readme line does not work on openwrt 20.02

### ISSUE THREAD

**Issue by beatstick** [openwrt/packages#16877]
Just a heads up:

opkg update; opkg remove dnsmasq; opkg install dnsmasq-full;

removing dnsmasq before installing dnsmasq-full will make it impossible to download packages. Also the dns-resolver failed to work on my router afterwards.

This line works for me:

> opkg install dnsmasq-full --download-only && opkg remove dnsmasq && opkg install dnsmasq-full --cache . && rm *.ipk

Maybe the readme should be edited as this is a lot of hassle if it goes wrong. 

A workaround if things have already gone wrong I found is this:

> You could edit /etc/resolv.conf and add nameserver 1.1.1.1 so you can resolve the openwrt.org 7 address

**Comment by stangri** [comment]
I suspected you may have meant one of my packages, so I've checked and updated all READMEs when I saw this issue. Thanks again for bringing it up!
