### ISSUE TITLE
php5 has conflicting maintainer info

### ISSUE THREAD

**Issue by KanjiMonster** [openwrt/packages#1688]
lang/php5 has @MikePetullo as the PKG_MAINTAINER but @mhei as the individual php5 packages' MAINTAINER.

Please unify the maintainer entries so we have only either PKG_MAINTAINER or MAINTAINER. Having both of you is fine.

**Comment by mhei** [comment]
Hehe, yes, historical reasons :smile:  Is comma separated list ok to list both of us?
