### ISSUE TITLE
alsa-lib has conflicting maintainer info

### ISSUE THREAD

**Issue by KanjiMonster** [openwrt/packages#1689]
libs/alsa-lib has @thess as the PKG_MAINTAINER but @tripolar  as the alsa-lib MAINTAINER.

Please unify the maintainer entries so we have only either PKG_MAINTAINER or MAINTAINER. Having both of you is fine.

**Comment by thess** [comment]
Combined package maintainers (for now) - 0f4e1326fec6af3fa6009318756c8e559c443a23
@tripolar - either of us is OK if you want to change
