### ISSUE TITLE
node: fails to build on arm_cortex-a7_neon-vfpv4

### ISSUE THREAD

**Issue by PolynomialDivision** [openwrt/packages#17074]
@nxhack

```
In file included from /usr/include/c++/8/memory:62,
                 from ../deps/v8/src/libplatform/default-foreground-task-runner.h:8,
                 from ../deps/v8/src/libplatform/default-foreground-task-runner.cc:5:
/usr/include/c++/8/bits/stl_algobase.h:59:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a7_neon-vfpv4/packages/node/compile.txt

**Comment by PolynomialDivision** [comment]
https://github.com/openwrt/packages/pull/17076

**Comment by nxhack** [comment]
@PolynomialDivision 

```
  *** The following preparations must be made on the host side. ***
      1. gcc 8.3 or higher is required.
      2. To build a 32-bit target, gcc-multilib, g++-multilib are required.
      3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.)
     ex) sudo apt-get install gcc-multilib g++-multilib
```

**Comment by PolynomialDivision** [comment]
@nxhack Thanks already saw it. Just looked how I can also tell that buildbot. ;) I'm just playing around so it will not appear anymore in faillogs.

**Comment by nxhack** [comment]
@PolynomialDivision 
It seems to be the policy of the buildbot administrator, and the same goes for CI. I can't do anything about it.

**Comment by PolynomialDivision** [comment]
@nxhack I thought for such things we can require hosts dependencies? I am not experienced in it so I need some time to find a working solution. Did you already try and it was not working?

**Comment by nxhack** [comment]
@PolynomialDivision 
Read the source code of Openwrt's build system; OS package dependencies are not supported.

https://github.com/openwrt/openwrt/blob/master/include/package-dumpinfo.mk
https://github.com/openwrt/openwrt/blob/master/scripts/metadata.pm

**Comment by PolynomialDivision** [comment]
You mean there is no way to not fail this package in buildbot?

@aparcar @neheb ?

**Comment by neheb** [comment]
Nope. Upstream does not want to add GCC-multilib

**Comment by PolynomialDivision** [comment]
But why does [luajit](https://github.com/openwrt/packages/blob/master/lang/luajit/Makefile) not fail? [Here](https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu) it is written that it also depends on gcc-multilib.

**Comment by PolynomialDivision** [comment]
Is that here the "magic"?
https://github.com/openwrt/packages/blob/79a9549940193d7b641cfd160fc22ff08dec8d4c/lang/luajit/Makefile#L30-L37

**Comment by BKPepe** [comment]
> But why does [luajit](https://github.com/openwrt/packages/blob/master/lang/luajit/Makefile) not fail? [Here](https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu) it is written that it also depends on gcc-multilib.

Because I fixed it. https://github.com/openwrt/packages/pull/17076#issuecomment-961734023
