### ISSUE TITLE
BIND 9.17 unstable branch in openwrt 21.02.1

### ISSUE THREAD

**Issue by damocles-dev** [openwrt/packages#17080]
Maintainer: frodo@morgul.net
Environment: mipsel_24kc, ramips/mt7621, openwrt 21.02.1

I did a fresh installation of openwrt and installed "bind" from the package repository, but it installs Bind 9.17 which is quite unstable and causes multiple random errors and timeouts like: 

```
04-Nov-2021 14:48:41.841 info: client @0x154a798 10.20.30.10#39992 (aa.google.com): query failed (timed out) for aa.google.com/IN/A at query.c:7659
04-Nov-2021 16:21:39.453 info: client @0x156b4d8 10.20.30.10#50216 (www.mozilla.org): query failed (timed out) for www.mozilla.org/IN/A at query.c:7659
04-Nov-2021 16:49:09.790 info: client @0x15660a8 10.20.30.7#52377 (api.waqi.info): query failed (timed out) for api.waqi.info/IN/A at query.c:7659
04-Nov-2021 18:10:30.452 info: client @0x157a438 10.20.30.10#39451 (www.msn.com): query failed (timed out) for www.msn.com/IN/A at query.c:7659
```
I have used "bind" for years, but these branch is unusable. 

Bind Version 9.17 appears in the repository of 21.02.1:
```
https://downloads.openwrt.org/releases/21.02.1/packages/mips_24kc/packages/bind-libs_9.17.19-1_mips_24kc.ipk
https://downloads.openwrt.org/releases/21.02.1/packages/mips_24kc/packages/bind-server-filter-aaaa_9.17.19-1_mips_24kc.ipk
https://downloads.openwrt.org/releases/21.02.1/packages/mips_24kc/packages/bind-server_9.17.19-1_mips_24kc.ipk
```

Is there any way to use version 9.16 in 21.02.1? 

```
root@ap-01:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.1'
DISTRIB_REVISION='r16325-88151b8303'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 21.02.1 r16325-88151b8303'
DISTRIB_TAINTS=''
root@ap-01:~#
root@ap-01:~# opkg info bind-server
Package: bind-server
Version: 9.17.19-1
Depends: libc, bind-libs
Status: install user installed
Section: net
Architecture: mipsel_24kc
Size: 140742
Filename: bind-server_9.17.19-1_mipsel_24kc.ipk
Conffiles:
 /etc/bind/db.0 d0a22a75c93fca4679f7c28610189f236a1d5b2e312131dc0aafb9cf6fbfcba6
 /etc/bind/db.127 8fbcbf85bf111f015d61f76136d350f49e435d3da780ed5318e6bd9d27c491e5
 /etc/bind/db.255 d0a22a75c93fca4679f7c28610189f236a1d5b2e312131dc0aafb9cf6fbfcba6
 /etc/bind/db.local 00a8e0a36707badb884cc048346555fc91834fc6b03e8b68e48cfd115ab766b9
 /etc/bind/db.root b4f0c32018f76e34aeadeae9063d34453ead220985f92b90eed35c3ed3c3ce6c
 /etc/bind/named.conf 9ec3eda49b635db23c43761c52a9d75eed6150ebcdf1f92ae7854d46e84b2fc3
Description: bind DNS server
Installed-Time: 1635761711
```

**Comment by brada4** [comment]
The log entry just says it did not get answer in 2 seconds and uses next upstream server for max 30s, it is just too verbose logging, not indicative of client timeouts.

**Comment by damocles-dev** [comment]
ok, some examples: 

```

**Comment by damocles-dev** [comment]
some background:

I was running openwrt 19.07 with bind <= 9.16 with zero dns related problems also if I install bind 9.16.x in my pc all works without errors.

Bind 9.17.x is declared __experimental branch__ by ISC's words:

https://www.mail-archive.com/bind-announce@lists.isc.org/msg00605.html
```
New BIND releases are available: 9.11.31, 9.16.15, and 9.17.12
[...]
A summary of significant changes in the new releases can be found in their 
release notes:

current supported stable branches:
 9.11.31  - https://downloads.isc.org/isc/bind9/9.11.31/RELEASE-NOTES-bind-9.11.31.html
 9.16.15  - https://downloads.isc.org/isc/bind9/9.16.15/doc/arm/html/notes.html

experimental development branch:
 9.17.12  - https://downloads.isc.org/isc/bind9/9.17.12/doc/arm/html/notes.html
``` 

and as all __experimental branches__ strange problems are expected.

with my experimental bind version I can see that query responses are received:

timeout log:
```
04-Nov-2021 14:48:41.841 info: client @0x154a798 10.20.30.10#39992 (aa.google.com): query failed (timed out) for aa.google.com/IN/A at query.c:7659
04-Nov-2021 14:48:41.841 debug 4: fetch completed at resolver.c:9488 for aa.google.com/A in 1.204021: timed out/success [domain:.,referral:0,restart:1,qrysent:1,timeout:1,lame:0,quota:0,neterr:0,badresp:0,adberr:0,findfail:0,valfail:0]
```
network trace:

```
 1966 2021-11-04 14:48:40.542800   10.20.30.1 → 87.216.1.66  DNS 96 Standard query 0xfbfb A aa.google.com OPT
 1967 2021-11-04 14:48:40.543155   10.20.30.1 → 87.216.1.66  DNS 96 Standard query 0x7dde AAAA aa.google.com OPT
 1968 2021-11-04 14:48:40.604376  87.216.1.66 → 10.20.30.1   DNS 125 Standard query response 0xfbfb A aa.google.com CNAME www3.l.google.com A 142.250.200.110 OPT
 1969 2021-11-04 14:48:40.604784  87.216.1.66 → 10.20.30.1   DNS 137 Standard query response 0x7dde AAAA aa.google.com CNAME www3.l.google.com AAAA 2a00:1450:4003:80e::200e OPT
```


timeout log:
```
04-Nov-2021 16:21:39.453 info: client @0x156b4d8 10.20.30.10#50216 (www.mozilla.org): query failed (timed out) for www.mozilla.org/IN/AAAA at query.c:7659
04-Nov-2021 16:21:39.453 debug 4: fetch completed at resolver.c:9488 for www.mozilla.org.cdn.cloudflare.net/AAAA in 1.204021: timed out/success [domain:.,referral:0,restart:1,qrysent:1,timeout:1,lame:0,quota:0,neterr:0,badresp:0,adberr:0,findfail:0,valfail:0]
```

network trace: 
```
 3754 2021-11-04 16:21:38.204486   10.20.30.1 → 87.216.1.66  DNS 98 Standard query 0x92a1 A www.mozilla.org OPT
 3755 2021-11-04 16:21:38.204856   10.20.30.1 → 87.216.1.66  DNS 98 Standard query 0x360f AAAA www.mozilla.org OPT
 3756 2021-11-04 16:21:38.253791  87.216.1.66 → 10.20.30.1   DNS 280 Standard query response 0x92a1 A www.mozilla.org CNAME www.mozilla.org.cdn.cloudflare.net A 104.18.165.34 A 104.18.164.34 RRSIG OPT
 3757 2021-11-04 16:21:38.254222  87.216.1.66 → 10.20.30.1   DNS 304 Standard query response 0x360f AAAA www.mozilla.org CNAME www.mozilla.org.cdn.cloudflare.net AAAA 2606:4700::6812:a422 AAAA 2606:4700::6812:a522 RRSIG OPT
```
so, why run an experimental branch instead of an stable and vaild one?

**Comment by damocles-dev** [comment]
I can confirm that downgrading from 9.17 to 9.16.22 (custom build) no longer produces strange timeout errors.

**Comment by brada4** [comment]
Yes, it has longer timeout. Still the problem of unstable version remains.

**Comment by damocles-dev** [comment]
do the programs use the same timeout by default? 

the question is why an unstable version is installed in the stable branch of openwrt, I would expect it to be installed in the snapshots

**Comment by brada4** [comment]
Both are 10s indeed.  So no really valid reason to time out.

**Comment by micmac1** [comment]
> Maintainer: [frodo@morgul.net](mailto:frodo@morgul.net)

Not sure maintainer gets notified when you put the mail address. Maintainer is @nmeyerhans

**Comment by damocles-dev** [comment]
@nmeyerhans

**Comment by damocles-dev** [comment]
Thanks, I did not put the correct one 

@nmeyerhans

**Comment by nmeyerhans** [comment]
> the question is why an unstable version is installed in the stable branch of openwrt, I would expect it to be installed in the snapshots

First, I'm well aware of the bind 9.17 status with ISC. In my judgement and experience, bind 9.17 is sufficiently stable for our needs. OpenWRT does not sync its release schedule to ISC's, nor should it. As maintainers, we need to evaluate the options available and make a decision about what is supportable in the long-term. When bind 9.17 stabilizes as 9.18 or whatever it ends up being, the OpenWRT branches that contain 9.17 will sync to it, but they will not downgrade at any time.

I have not experienced the issues you're describing with bind 9.17.x, so it'll be challenging to debug. I'll try running in an emulated mipsel environment in case it's architecture related...

**Comment by brada4** [comment]
There is an easy fix - in accordance of first sentence of packaging guide make a version 9.17.99999-orly-9.16.23 - the incompatibility is on par of minor 9.17 point releases' incompatible changes.

**Comment by nmeyerhans** [comment]
That is not the point at all. It doesn't matter what version you give it, that would be a downgrade. Bind will not switch to a different upstream release branch from what's in master at the time of the packages stable branch except to pin to the stable upstream branch that's based on the one previously in stable.

That's a lot of words to say bind in the 21.02 branch will not switch from 9.17 to anything other than 9.18 when it's eventually released (assuming that's what ISC ends up calling it).

**Comment by brada4** [comment]
Then you are running late for security fixes in 9.17.20

**Comment by nmeyerhans** [comment]
Bind 9.17.20 was released yesterday and lists no security fixes in its changelog.

It will be packaged when the maintainer has some time. PRs would be welcomed.

**Comment by nmeyerhans** [comment]
With the release of bind 9.18.0, the 21.02 has switched to that release series as of #17774
