### ISSUE TITLE
sftp-server error

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [openwrt/packages#17135]
Mon Nov 15 15:49:32 2021 authpriv.info dropbear[30553]: Child connection from 192.168.2.11:49814
Mon Nov 15 15:49:35 2021 authpriv.notice dropbear[30553]: Password auth succeeded for 'root' from 192.168.2.11:49814
Mon Nov 15 15:49:35 2021 authpriv.info dropbear[30561]: Child connection from 192.168.2.11:49820
Mon Nov 15 15:49:35 2021 authpriv.notice dropbear[30561]: Password auth succeeded for 'root' from 192.168.2.11:49820
Mon Nov 15 15:49:36 2021 kern.info kernel: [ 6012.431797] sftp-server[30573]: segfault at 53ed8070 ip 000055ae96d0a711 sp 00007ffe375ee9f8 error 6 in sftp-server[55ae96d0a000+11000]
Mon Nov 15 15:49:36 2021 kern.info kernel: [ 6012.442995] Code: c4 88 04 00 00 5b 5d 41 5c 41 5d 41 5e 41 5f c3 8b 15 73 a9 01 00 48 63 c7 89 3d 6a a9 01 00 48 6b c0 38 48 03 05 57 ab 01 00 00 00 00 00 00 89 50 30 c3 31 c0 85 ff 78 1d 3b 3d 39 ab 01 00
Mon Nov 15 15:49:37 2021 authpriv.info dropbear[30561]: Exit (root) from <192.168.2.11:49820>: Exited normally
Mon Nov 15 15:49:37 2021 authpriv.info dropbear[30611]: Child connection from 192.168.2.11:49821
Mon Nov 15 15:54:37 2021 authpriv.info dropbear[30611]: Exit before auth from <192.168.2.11:49821>: Timeout before auth

**Comment by diizzyy** [comment]
OS? Arch? Device? Did you compile it? Changes to source/settings? Also wrong repo as this is in openwrt/openwrt (on GitHub)
