### ISSUE TITLE
procd-ujail: makes dnsmasq refuse to answer dns queries

### ISSUE THREAD

**Issue by wwortel** [openwrt/packages#17185]
22/11/2021 compile for ramips device Ubiquiti EdgeRouter X sfp ; snapshot: r18166-e2c4998f6d
Choosing TARGET_ramips_mt7621_DEVICE_ubnt_edgerouter-x-sfp selects default the inclusion of procd-ujail .
This has the effect of dnsmasq being put in a jail.
The device can still make dns queries to upstream. But, depite dnsmasq listening on all interfaces, any incoming queries get the reply 'REFUSED'. Easily tested on the device itself e.g. with the command \'nslookup \<some fqdn\> localhost\'
This leaves any devices downstream in the dark that via dhcp got the news to fetch their dns information from this jailed dnsmasq.
Exactly same configuration compile, but with procd-ujail manually removed, restores complete functionality of dnsmasq.

**Comment by feckert** [comment]
Wrong repository. The package `procd-ujail` is maintained in [openwrt-base.](https://github.com/openwrt/openwrt) Please open a bug report at https://bugs.openwrt.org/
