### ISSUE TITLE
the lua-cjson crash on my ar71xx board

### ISSUE THREAD

**Issue by mythay** [openwrt/packages#1719]
when I use latest lua-cjson_2.1.0-2_ar71xx.ipk from snapshort, it crush like below.

> require'cjson'
> Segmentation fault

---

but the original lua-cjson_2.1.0-1_ar71xx.ipk from CC is OK

**Comment by yousong** [comment]
ping lua-cjson's current maintainer @srdgame

**Comment by diizzyy** [comment]
@mythay 
Is this still not working?

**Comment by yousong** [comment]
Just installed and run-tested on QEMU malta with LEDE bleeding edge, the issue should have already been fixed.
