### ISSUE TITLE
mosquitto-nossl missing hashed password support

### ISSUE THREAD

**Issue by vertuxt** [openwrt/packages#17294]
Maintainer: @karlp 
Environment: mip24kc ath79 OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d

Description:
The mosquitto-nossl package seems lacking support for hashed passwords. After updating to 21.02, mosquitto was rejecting correct authentication with "Not Authorized". After changing the Password format to plaintext it worked. As it is a test-System I did not jet analyzed further. 

PS: Also mosquitto_passwd is missing.

**Comment by karlp** [comment]
Correct. This is what you get when you try to remove security from the security part... You can try and file it upstream if you like, see also https://github.com/openwrt/packages/issues/16232
