### ISSUE TITLE
mwan3: flush_conntrack broken

### ISSUE THREAD

**Issue by champtar** [openwrt/packages#17402]
Maintainer: @feckert @aaronjg 
Environment: 21.02

Description:
mwan3_flush_conntrack call was moved in 39f58789e603fd31b763887282fc6b042a4d9d54 and logic was inverted,
it's called only when mwan3 is globally disabled so right now flush_conntrack is broken

**Comment by feckert** [comment]
You are absolutely right! Thanks for the hint, I'll have a look at it asap. 
Can you move the line from
https://github.com/openwrt/packages/blob/master/net/mwan3/files/etc/hotplug.d/iface/15-mwan3#L29
after line
https://github.com/openwrt/packages/blob/master/net/mwan3/files/etc/hotplug.d/iface/15-mwan3#L87
does this fix the issue on your use case?

**Comment by champtar** [comment]
Doing your change conntrack is now flushed:
```
Mon Dec 20 17:10:45 2021 user.info mwan3-hotplug[6167]: Connection tracking flushed for interface 'wancamp1' on action 'connected'
```

**Comment by feckert** [comment]
@champtar Pushed to stable branch with commit https://github.com/openwrt/packages/commit/7a15a271a6c6682cb170b1a410b1c77b6bfb666e
