### ISSUE TITLE
miniupnpd multiwan awareness mwan3

### ISSUE THREAD

**Issue by professor-jonny** [openwrt/packages#17412]
Can Miniupnpd be made aware of multiwan enviroments ?
I'm using Mwan3 and upon failover it would be nice if the rules shifted over to the other wan interface.

**Comment by feckert** [comment]
I can't help you there without dealing with the subject. Why don't you ask in the forum? Maybe someone has a setup?
https://forum.openwrt.org/

**Comment by stintel** [comment]
This is an issue tracker, not a support channel. As suggested, use the forum, or alternative channels as documented [here](https://openwrt.org/contact).
