### ISSUE TITLE
HOSTAPD_START_FAILED after updating to hostapd-common - 2020-06-08-5a8b3662-38 & wpad-basic-wolfssl - 2020-06-08-5a8b3662-38

### ISSUE THREAD

**Issue by jsilva-iii** [openwrt/packages#17443]
HOSTAPD_START_FAILED after updating to hostapd-common - 2020-06-08-5a8b3662-38 & wpad-basic-wolfssl - 2020-06-08-5a8b3662-38

Router :
Linksys WRT3200ACM
running OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.357.58218-b3cd473

I updated the above packages and no wifi  in log : 

Mon Dec 27 10:35:13 2021 daemon.err hostapd: Line 46: unknown configuration item 'snoop_iface'
Mon Dec 27 10:35:13 2021 daemon.err hostapd: Line 53: unknown configuration item 'vlan_no_bridge'
Mon Dec 27 10:35:13 2021 daemon.err hostapd: Line 55: unknown configuration item 'qos_map_set'
Mon Dec 27 10:35:13 2021 daemon.err hostapd: 3 errors found in configuration file '/var/run/hostapd-phy0.conf'
Mon Dec 27 10:35:13 2021 daemon.err hostapd: Failed to set up interface with /var/run/hostapd-phy0.conf
Mon Dec 27 10:35:13 2021 daemon.notice netifd: radio0 (17393): Command failed: Invalid argument
Mon Dec 27 10:35:13 2021 daemon.notice netifd: radio0 (17393): Device setup failed: HOSTAPD_START_FAILED

**Comment by BKPepe** [comment]
This issue does not belong here. You reported this to packages repository. There is no hostapd, netifd, etc. You should report it to base repository. Take a look at how to report bugs at OpenWrt.
