### ISSUE TITLE
ddns-scripts: whatismyipaddress.com/api is gone so it needs to be replaced

### ISSUE THREAD

**Issue by rezad1393** [openwrt/packages#17529]
Maintainer:
@feckert 
Environment:
21.02.1 

the whatismyipaddress.com/api  like bot.whatismyipaddress.com are disabled.

"Public IP Address
As of November 10, 2021 we are no longer providing this API due to massive abuse."

scripts that rely on that for public IP don't work.
for example duckdns.

it needs to be replaced with a new public IP api.

**Comment by Loader009** [comment]
suggestion: wtfismyip.com

**Comment by feckert** [comment]
Please make a suggestion and modify the code and open a pull request.
I don't know all the providers for ddns and don't have the time to maintain everything.
