### ISSUE TITLE
bluez: snapshot failed to compile on arc targets

### ISSUE THREAD

**Issue by MoetaYuko** [openwrt/packages#17530]
Maintainer: @neheb
Environment: arc770/generic, layerscape/armv8_64b, snapshot

Description:

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/bluez/compile.txt

**Comment by neheb** [comment]
curious. Do you have any arc hardware?

**Comment by MoetaYuko** [comment]
nope, but I run a CI to build packages for all platforms including arc and it's broken today.

**Comment by neheb** [comment]
hmm looks like a glibc update is causing this.
