### ISSUE TITLE
PERL USB Support is missing

### ISSUE THREAD

**Issue by DittelHome** [openwrt/packages#1759]
Is it possible to add PERL USB Support (USB.pm) ?
Tried to build, but cpan is not working properly...

**Comment by Naoir** [comment]
I don't see any problems getting USB support in.

Device::USB is currently broken though. I'm working on getting things running, but this might take moment or two.

**Comment by DittelHome** [comment]
@Naoir 
Thanks !! Good News ...

**Comment by Naoir** [comment]
I've just pushed Device::USB(in perl-device-usb) to master. If anything doesn't work as intended, please open another bug report.

Hope everything goes well though ;)

**Comment by DittelHome** [comment]
Thanks a lot, it's working perfect ...
