### ISSUE TITLE
mariadb - Uses sudo without having dependency to install it

### ISSUE THREAD

**Issue by najdanovicivan** [openwrt/packages#17602]
Maintainer: @miska 
Environment: x86_64 

Description:

Init script uses sudo when upgrading mysql.  Usage of sudo should be removed or sudo should be added as dependency

https://github.com/openwrt/packages/blob/dafb96c14837bf133e5215cf65fc7ed1439a375a/utils/mariadb/files/mysqld.init#L156

**Comment by miska** [comment]
Fixed and merged
