### ISSUE TITLE
opencv 3.0 needs eigen

### ISSUE THREAD

**Issue by Hallo32** [openwrt/packages#1767]
The current package needs eigen to build.

This can be fixed with  the following change to the Makefile.

CMAKE_OPTIONS += -DBUILD_opencv_gpu:BOOL=OFF \
	-DWITH_EIGEN:BOOL=OFF \
...

**Comment by champtar** [comment]
Hi @Hallo32,

Please send a PR

**Comment by Hallo32** [comment]
Hi,

opencv needs Eigen only on the host to build the package.

I close the ticket.
