### ISSUE TITLE
Hardware flow offloading fails on the new fw4

### ISSUE THREAD

**Issue by zcy85611** [openwrt/packages#17693]
I've noticed recently the firewall has upgraded from fw3 to fw4

under fw4, the option Hardware flow offloading is no longer working, after enable the rule and start the firewall

it gives the following

/proc/self/fd/0:9:12-13: Error: Could not process rule: Not supported

/proc/self/fd/0:54:29-44: Error: Could not process rule: No such file or directory

I don't know if it's firewall or the Hardware flow offloading's problem, could someone help to look at this please? thank you

**Comment by champtar** [comment]
Hi @zcy85611 
For now bug for core packages need to be reported at https://bugs.openwrt.org/ (it might move to GitHub openwrt/openwrt in a near future)
@jow- fyi
