### ISSUE TITLE
freeradius2 - radiusd won't start at boot

### ISSUE THREAD

**Issue by czakey** [openwrt/packages#1769]
It seems that radiusd is not starting at boot. This bug been there for a long time. Init script seems to be oldish too.

Log indicates:
`Sat Sep 12 20:59:41 2015 user.emerg syslog: radiusd: Invalid IP Address or hostname "-p"`

Looking into /etc/init.d/radiusd there is
`IPADDR=$(ifconfig br-lan | sed -n 's/.*dr:\(.*\)Bc.*/\1/p')`
and then
`radiusd -i $IPADDR -p 1812,1813 $OPTIONS`

It seems that there is no valid IP address output from ifconfig. Changing `IPADDR=$(ifconfig br-lan | sed -n 's/.*dr:\(.*\)Bc.*/\1/p')` to something like `IPADDR=$(uci get network.lan.ipaddr)` solves the problem.

**Comment by haa-zee** [comment]
I'm using Chaos Calmer and I experienced the same.
opkg update && opkg list-upgradable output is empty...
Status is closed. Hm...

**Comment by dangowrt** [comment]
We don't provide snapshot package builds for Chaos Calmer. You can use the SDK to re-compile the updated package and then update it on your device.
