### ISSUE TITLE
samba4: newer versions are available.

### ISSUE THREAD

**Issue by SiNONiMiTY** [openwrt/packages#17697]
Maintainer: Andy Walsh @Andy2244
Environment: ARMv8 | OpenWrt SNAPSHOT, r18609-266b5c83c3

If possible, can the newer versions be integrated on the snapshot builds? Currently, we are sitting at 4.14.7, the latest released is at 4.15.4.

The difference is already months ago and there are several security issues that were patched in between.

**Comment by Andy2244** [comment]
Will see what i can do, have not much time atm so probably will just bump to the latest 4.14.x for now, since 4.15.x requires more work and tests.

**Comment by SiNONiMiTY** [comment]
@Andy2244 thank you for your hard work on this package.

**Comment by tapper82** [comment]
Updated to 4.14.12 
      https://github.com/openwrt/packages/commit/1fa70d6a3c68bc49bdeae4d505f2e41ff3a0b906

**Comment by SiNONiMiTY** [comment]
Closing this one as we are already up to date with the 4.14.x branch.

@Andy2244 if you have spare time, a 4.15.x catch-up release would be awesome. Thanks :)
