### ISSUE TITLE
uacme: ualpn binary missing from the package

### ISSUE THREAD

**Issue by blackie333** [openwrt/packages#17837]
Maintainer: Lucian Cristian <lucian.cristian@gmail.com>
Environment: Lantiq/XRX200 target OpenWrt 21.02.1 r16325-88151b8303

Description: ualpn files (binary + script) are missing from the uacme package. 
Are required for tls-alpn-01 challenge mode (on port 443).
uacme developer suggests to include the files to the package:
https://forum.openwrt.org/t/new-lightweight-lets-encrypt-client/36192/23
Need a challenge working on port 443 (port 80 blocked by ISP). Thanks a lot in advance.

# ualpn
-ash: ualpn: not found

#  opkg files uacme
Package uacme (1.6-1) is installed on root and has the following files:
/etc/config/acme
/usr/sbin/uacme
/usr/share/uacme/uacme.sh
/usr/share/uacme/run-uacme
/lib/upgrade/keep.d/uacme

+ related script: /usr/share/uacme/ualpn.sh

**Comment by lucize** [comment]
I'll try to look into it

**Comment by lucize** [comment]
no such binary, but I guess we need a config option to enable it ?

**Comment by lucize** [comment]
@blackie333 so there is not proper way to have this available by default because libcurl defaults to wolfssl and that is not supported by ualpn, so you'll have to build your image with libcurl-gnutls or libcurl-openssl for this to work
#17884
