### ISSUE TITLE
sudo in CC 15.05 does not preserve configuration files in /etc/sudoers.d/

### ISSUE THREAD

**Issue by TimMillerDyck** [openwrt/packages#1783]
Hello, sudo supports a conf.d custom configuration file directory in /etc/sudoers.d/. However, this directory is not marked to be preserved in a system upgrade, resulting in these files being lost when OpenWrt is upgraded (and the possible inability to become root as before).

Fix:
- Create a text file /lib/upgrade/keep.d/sudo

- Contents of the file are the file and directory to preserve on a sysupgrade:

/etc/sudoers
/etc/sudoers.d/

Thanks,
Tim Miller Dyck

**Comment by jow-** [comment]
Fixed via 12b1f4fab82935ba5db581afd5ff74079facd73e

**Comment by TimMillerDyck** [comment]
Awesome. Thanks jow! -Tim
