### ISSUE TITLE
Request: Help building Elixir package

### ISSUE THREAD

**Issue by kevinold** [openwrt/packages#1786]
I would like to build a package for Elixir for OpenWRT.

It's Makefile is here: https://github.com/elixir-lang/elixir/blob/master/Makefile

I need help getting started with building this package.

**Comment by kevinold** [comment]
@psycho-nico I see you compiled the erlang package for OpenWRT.  Would you have any guidance for building the Elixir package?

**Comment by thesabbir** [comment]
@kevinold have you made the package?
