### ISSUE TITLE
error build tvheadend if global setings "full language support"

### ISSUE THREAD

**Issue by build000** [openwrt/packages#1787]
(...)
make[3]: Entering directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/multimedia/tvheadend'
mkdir -p /magazyn/Pliki/openwrt/trunk/dl
echo "Checking out files from the git repository..."; mkdir -p /magazyn/Pliki/openwrt/trunk/tmp/dl && cd /magazyn/Pliki/openwrt/trunk/tmp/dl && rm -rf tvheadend && [ \! -d tvheadend ] && git clone https://github.com/tvheadend/tvheadend.git tvheadend --recursive && (cd tvheadend && git checkout v4.0.5 && git submodule update) && echo "Packing checkout..." && rm -rf tvheadend/.git && 	tar czf /magazyn/Pliki/openwrt/trunk/tmp/dl/tvheadend-v4.0.5.tar.gz tvheadend && mv /magazyn/Pliki/openwrt/trunk/tmp/dl/tvheadend-v4.0.5.tar.gz /magazyn/Pliki/openwrt/trunk/dl/ && rm -rf tvheadend; 
Checking out files from the git repository...
Cloning into 'tvheadend'...
remote: Counting objects: 50991, done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 50991 (delta 114), reused 1 (delta 1), pack-reused 50784
Receiving objects: 100% (50991/50991), 30.57 MiB | 158.00 KiB/s, done.
Resolving deltas: 100% (37056/37056), done.
Checking connectivity... done.
Note: checking out 'v4.0.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ffc3ff1... channels: tags are saves as strings (uuid)
Packing checkout...
. /magazyn/Pliki/openwrt/trunk/include/shell.sh; gzip -dc /magazyn/Pliki/openwrt/trunk/dl/tvheadend-v4.0.5.tar.gz | tar -C /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/.. -xf - 
echo 'Tvheadend 4.0.5~openwrt2' > /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/debian/changelog
touch /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/.prepared_6b599935f15ec68f6c5c78958f242a92
rm -f /magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.tvheadend_installed
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend; rm -f aclocal.m4; if [ -f ./configure.ac ] || [ -f ./configure.in ]; then [ -d ./autom4te.cache ] && rm -rf autom4te.cache; [ -e ./config.rpath ] || ln -s /magazyn/Pliki/openwrt/trunk/scripts/config.rpath ./config.rpath; touch NEWS AUTHORS COPYING ABOUT-NLS ChangeLog; AUTOM4TE=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/autom4te AUTOCONF=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/autoconf AUTOMAKE=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/automake ACLOCAL=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/aclocal AUTOHEADER=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/autoheader LIBTOOLIZE=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/libtoolize LIBTOOL=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/libtool M4=/magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/m4 AUTOPOINT=true /magazyn/Pliki/openwrt/trunk/staging_dir/host/bin/autoreconf -v -f -i -s -B /magazyn/Pliki/openwrt/trunk/staging_dir/host/share/aclocal -I /magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/host/share/aclocal -I /magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/share/aclocal -I m4 -I . . || true; fi; );
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/./; if [ -x ./configure ]; then find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ -name config.guess | xargs -r chmod u+w; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ -name config.guess | xargs -r -n1 cp --remove-destination /magazyn/Pliki/openwrt/trunk/scripts/config.guess; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ -name config.sub | xargs -r chmod u+w; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ -name config.sub | xargs -r -n1 cp --remove-destination /magazyn/Pliki/openwrt/trunk/scripts/config.sub; AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/include" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/include " CPPFLAGS="-I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/include " LDFLAGS="-L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/lib -Wl,-rpath-link=/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/lib -Wl,-rpath-link=/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/lib "   ./configure --target=mips-openwrt-linux --host=mips-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info    --disable-avahi --arch=mips --disable-dbus_1 --disable-libav --enable-bundle ; fi; )
Checking support/features
  checking for cc execinfo.h ...                    fail
  checking for cc -mmmx ...                         fail
  checking for cc -msse2 ...                        fail
  checking for cc getloadavg ...                    ok
  checking for cc atomic64 ...                      fail
  checking for cc lockowner ...                     fail
  checking for cc qsort_r ...                       fail
  checking for cc stime ...                         ok
  checking for cc recvmmsg ...                      ok
  checking for cc sendmmsg ...                      ok
  checking for cc libiconv ...                      ok
  checking for cc libdvben50221 ...                 fail
  checking for py module gzip ...                   ok
  checking for gzip ...                             ok
  checking for bzip2 ...                            ok
  checking for pkg openssl  ...                     ok (detected 1.0.2d)
  checking for cc linux/dvb/version.h ...           ok
  checking for cc libhdhomerun/hdhomerun.h ...      fail
  checking for pkg zlib  ...                        ok (detected 1.2.8)
  checking for pkg liburiparser  ...                fail (detected <none>)
  checking for cc sys/inotify.h ...                 ok
  fetching dvb-scan files ...                       ok

Compiler:
  Using C compiler:                        mips-openwrt-linux-musl-gcc
  Using C flags:                           -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/include 
  Using LD flags:                          -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/lib -Wl,-rpath-link=/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/lib -Wl,-rpath-link=/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libintl-full/lib 
  Build for arch:                          mips

Binaries:
  Using PYTHON:                            python
  Using GZIP:                              gzip
  Using BZIP2:                             bzip2

Options:
  cwc                                      yes
  capmt                                    yes
  constcw                                  yes
  linuxdvb                                 yes
  satip_server                             yes
  satip_client                             yes
  hdhomerun_client                         no
  hdhomerun_static                         no
  iptv                                     yes
  tsfile                                   yes
  dvbscan                                  yes
  timeshift                                yes
  trace                                    yes
  imagecache                               yes
  avahi                                    no
  zlib                                     yes
  libav                                    no
  libffmpeg_static                         no
  libffmpeg_static_x264                    yes
  inotify                                  yes
  epoll                                    yes
  uriparser                                no
  ccache                                   no
  tvhcsa                                   yes
  bundle                                   yes
  dvbcsa                                   no
  dvben50221                               no
  kqueue                                   no
  dbus_1                                   no
  android                                  no
  tsdebug                                  no
  gtimer_check                             no
  getloadavg                               yes
  stime                                    yes
  recvmmsg                                 yes
  sendmmsg                                 yes
  libiconv                                 yes
  py_gzip                                  yes
  bin_gzip                                 yes
  bin_bzip2                                yes
  ssl                                      yes
  linuxdvbapi                              yes
  upnp                                     yes
  inotify_h                                yes
  mpegts                                   yes
  mpegts_dvb                               yes

Packages:
  openssl                                  1.0.2d
  zlib                                     1.2.8

Installation paths:
  Prefix:                                  /usr
  Binaries:                                /usr/bin
  Libraries:                               ${prefix}/lib
  Data files:                              /usr/share
  Man pages:                               /usr/man

Final Binary:
  /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/build.linux/tvheadend

Tvheadend Data Directory:
  /usr/share/tvheadend
(...)
touch /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/.built
mkdir -p /magazyn/Pliki/openwrt/trunk/bin/ar71xx/packages /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/CONTROL /magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/pkginfo
install -d -m0755 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/etc/init.d
install -m0755 ./files/tvheadend.init /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/etc/init.d/tvheadend
install -d -m0755 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/etc/config
install -m0600 ./files/tvheadend.config /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/etc/config/tvheadend
install -d -m0755 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/usr/bin
install -m0755 /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/build.linux/tvheadend /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend/usr/bin/
find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/tvheadend/ipkg-ar71xx/tvheadend -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package tvheadend is missing dependencies for the following libraries:
libiconv.so.2
Makefile:98: recipe for target '/magazyn/Pliki/openwrt/trunk/bin/ar71xx/packages/packages/tvheadend_4.0.5-2_ar71xx.ipk' failed
make[3]: *** [/magazyn/Pliki/openwrt/trunk/bin/ar71xx/packages/packages/tvheadend_4.0.5-2_ar71xx.ipk] Error 1
make[3]: Leaving directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/multimedia/tvheadend'
package/Makefile:191: recipe for target 'package/feeds/packages/tvheadend/compile' failed
make[2]: *** [package/feeds/packages/tvheadend/compile] Error 2
make[2]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
package/Makefile:188: recipe for target '/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile' failed
make[1]: *** [/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile] Error 2
make[1]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
/magazyn/Pliki/openwrt/trunk/include/toplevel.mk:179: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2

a full log of this part of the compilation http://wklej.org/id/1799270/

**Comment by sairon** [comment]
Should be fixed by 2849864c1ec62121c96701ca2566d17025297d03.

**Comment by thess** [comment]
Yes, it is.
