### ISSUE TITLE
vnstat: see ticket #16986 - Request backport and cherry pick pull request #16950 from vnstat2

### ISSUE THREAD

**Issue by kayfab3** [openwrt/packages#17890]
Maintainer: @janh @jow
Environment: mvebu, OpenWrt 21.02.x, vnstat2 2.7-1, vnstat 1.18-2

Description: As of OpenWrt 21.02 vnstat and vnstat2 packages do not respect user defined configuration of interfaces. Database configuration does not survive a router reboot.  After each router reboot, configuration of interfaces set either manually or configured by /etc/config/vnstat and /etc/vnstat.conf is not honored, the previous database config is purged, and reloaded from some unspecified default.

To clarify, this bug effects packages vnstat and vnstat2 since Openwrt 21.02.  

A pull request was created by @janh and committed to master on Oct 28, 2021 but was never backported to 21.02 branch.

See:

https://github.com/openwrt/packages/issues/16986

Vnstat2 pull request:

https://github.com/openwrt/packages/issues/16986#ref-pullrequest-1032978996  
https://github.com/openwrt/packages/pull/16950

jow per our irc discussion please backport and cherry pick the vnstat2 pull request to vnstat

> \<jow> you can try create a ticket, as for cherry picking 63aa37de85a5dc983db54694e15bd0bc80adaa70 and 2ca14d78befc243e7296e1ff12033bce59c7081e to openwrt-21.02

**Comment by BKPepe** [comment]
Done.

Commits:
- https://github.com/openwrt/packages/commit/f8820d2aeb650d215035e87fd59acc0020bbe12c
- https://github.com/openwrt/packages/commit/42f35cdda75ea3322e0f41996e71918b53def1bb
