### ISSUE TITLE
unbound: /var/lib/unbound/unbound.conf differs from /etc/config/unbound

### ISSUE THREAD

**Issue by it-jonas** [openwrt/packages#17927]
Maintainer: @EricLuehrsen
Environment: AMD GX-412TC SOC  OpenWrt 21.02.0, r16279-5cc0535800

Description:
The content of the config which was set within luci differs from the generated config. 
![Screenshot from 2022-02-23 15-00-42](https://user-images.githubusercontent.com/20993035/155358571-9ba4bcbb-2724-4061-961b-5dd1fe6a2984.png)
![Screenshot from 2022-02-23 15-00-56](https://user-images.githubusercontent.com/20993035/155358084-3f57bd77-a074-4ff4-a02b-5363d0d8e3ae.png)

**Comment by brada4** [comment]
I assume it maintains focus on embedded systems, multi-thread option is there for testing its stability while most systems will be saturated by default anyway.
https://github.com/openwrt/packages/blob/94858ece3120a866da97e0b891f313fd032c7bc6/net/unbound/files/unbound.sh#L706
You can edit that uci script and measure throughput (cached), it needs no iptables and multiqueue netcard to jump above 10k rps on normal systems.

**Comment by it-jonas** [comment]
thank you for your answer. my report was about the options not matching when i set them. 
are you telling me that setting this option is not implemented at all??

**Comment by brada4** [comment]
Script limits unbound to TWO threads no matter what you have/set. You can get more by editing that script on your system. 
and two more likely bottlenecks before measuring multiprocessor performance:
* multiqueue netcard
* iptables --ports 53 -j NOTRACK

**Comment by EricLuehrsen** [comment]
`num_threads` can have caveats on different hardware and requires configuring memory slabs correctly. It can be complicated. One slab and two threads works well on MVEBU for example. UCI is limited to reliable and easy configuration. If something more is desired, then it would be better to use the manual configuration mode.

**Comment by it-jonas** [comment]
Thanks for you replies. Seems like I need to dig way more deeper more into the documentation.
