### ISSUE TITLE
auc :  Segmentation fault when trying to update Linksys WRT1200 AC

### ISSUE THREAD

**Issue by notthinkingtinker** [openwrt/packages#17971]
Maintainer: @aparcar  (find it by checking history of the package Makefile)
Environment: Openwrt 21.02.1

Description:
root@Openwrt~# auc
auc (0.2.4-4)
Server:    chef.libremesh.org
Running:   21.02.1 r16325-88151b8303 on mvebu/cortexa9 (linksys,wrt1200ac)
Segmentation fault

**Comment by notthinkingtinker** [comment]
@aparcar  Please help with this issue .

**Comment by dangowrt** [comment]
I guess you manage to crash it by using only a hostname instead of URL ie. protocol+hostname. Try setting url in `/etc/config/attendedsysupgrade` to `https://sysupgrade.openwrt.org`.
