### ISSUE TITLE
OpenWrt 22.03 has branched!!

### ISSUE THREAD

**Issue by hnyman** [openwrt/packages#17997]
OpenWrt will likely branch for the new 22.0x release in late March.

Packages/features/fixes to be included in the 22.0x branch (likely 22.03) should be merged well in advance of the branching.
Stuff that is merged after the branching will need to be backported to the new release branch.

PRs containing experimental stuff would preferably be merged to master **after the branching**, so that the new 22.0x release branch is as stable as possible.

See release related advice in:
* https://github.com/openwrt/openwrt/issues/9394
* https://lists.openwrt.org/pipermail/openwrt-devel/2022-February/038037.html
* https://lists.openwrt.org/pipermail/openwrt-devel/2022-March/038170.html

**Comment by predators46** [comment]
@hnyman 

https://github.com/openwrt/openwrt/issues/9365

**Comment by hnyman** [comment]
OpenWrt 22.03 has been branched today.

22.03 is now the current stable branch, 
21.02 is the old stable branch, and 
19.07 is supposed to be declared End-of-life soon.

**Comment by predators46** [comment]
I didn't see the release 22.03

https://downloads.openwrt.org/releases/

**Comment by nickberry17** [comment]
Can we get new supported devices into 22.03 or is it already in feature freeze?  i.e.: https://github.com/openwrt/openwrt/commit/7ea2f3d6e22b506d137cf255ae73ae498c176d1c

**Comment by nickberry17** [comment]
> I didn't see the release 22.03
> 
> https://downloads.openwrt.org/releases/

See https://github.com/openwrt/openwrt/issues/9394 
>March 20th is not the release date of 22.0x, after the branch we'll give it more time to stabilize.

**Comment by predators46** [comment]
> > I didn't see the release 22.03
> > https://downloads.openwrt.org/releases/
> 
> See [openwrt/openwrt#9394](https://github.com/openwrt/openwrt/issues/9394)
> 
> > March 20th is not the release date of 22.0x, after the branch we'll give it more time to stabilize.

Thanks

**Comment by openwrtfirmwarecostum** [comment]
Nice

https://downloads.openwrt.org/releases/packages-22.03/

**Comment by neheb** [comment]
Should this be unpinned?
