### ISSUE TITLE
 `<adblock>: `  Start priority

### ISSUE THREAD

**Issue by przemekp1** [openwrt/packages#18072]
I propose to change the default startup priority for adblock to e.g. 90
so that the services are started in order:
modemmanager 70
https-dns-proxy 80
adblock 90

I propose this solution because I have a USB-LTE modem running with modemmanager and it seems logical
to run this service at the end.

**Comment by dibdot** [comment]
Nope, on boot the adblock init doesn't start the adblock service itself, but registers only a network reload trigger (e.g. for wan interface) right after the network stack comes up - to make sure to receive/catch all ubus interface events. This trigger starts adblock. If your hardware setup needs more time you can change/raise the "Trigger Delay" in adblock (default are 2 seconds).
