### ISSUE TITLE
update golang to 1.18

### ISSUE THREAD

**Issue by yaof2** [openwrt/packages#18150]
new Golang Stable versions is 1.18.plaese update it。https://go.dev/dl/ 。thanks。

**Comment by Beginner-Go** [comment]
already in pr

**Comment by yaof2** [comment]
ok

**Comment by jefferyto** [comment]
Whether Go will be updated to 1.18 depends on which branch you are referring to:

* master: The PR is #18147.
* openwrt-22.03: Depends on how quickly the release will happen. I'm going to wait at least several weeks before backporting the update. If 22.03 is released earlier then it will stay on 1.17.
* openwrt-21.02: As the current stable branch, it will stay on 1.17.
