### ISSUE TITLE
dbus: broken since 1.9.20 update

### ISSUE THREAD

**Issue by Noltari** [openwrt/packages#1821]
Looks like config files were moved from /etc/dbus-1 to /usr/share/dbus-1 in 1.9.18:
http://cgit.freedesktop.org/dbus/dbus/commit/?id=b2c61ca6ea2dd9ba62ebddc98fa295ee84ab3949
This is causing the following failure: Failed to open "/usr/share/dbus-1/system.conf": No such file or directory
Reverting https://github.com/openwrt/packages/commit/917c1fbe59a067789d37ef525cdb92faa36d1c91 fixes it

**Comment by sbyx** [comment]
should be fixed
