### ISSUE TITLE
FRPC>FRPC can't save new settings 

### ISSUE THREAD

**Issue by Beaverfffan** [openwrt/packages#18239]
when i save new settings at frpc，message following will show out。

go to: Service → Interfaces → frp client
set new frpc link
Save & Apply
4.Save error
An error occurred while saving the form:

RPC call to uci/delete failed with ubus code 4: Resource not found
at ClassConstructor.handleCallReply (http://192.168.0.1/luci-static/resources/rpc.js?v=git-22.090.69956-24ed48d:15:3

Additional Information:
OpenWrt version information from system

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='master'
DISTRIB_REVISION='all'
DISTRIB_TARGET='all'
DISTRIB_ARCH='all'

**Comment by feckert** [comment]
Duplicate https://github.com/openwrt/luci/issues/5758
