### ISSUE TITLE
TravelMate: Manage additional devices

### ISSUE THREAD

**Issue by Massimo-B** [openwrt/packages#18278]
I'm running travelmate for Wifi. For areas without Wifi I have another LTE network device via usb using kmod-usb-net-cdc-ether which just works like another ethernet device.

As the mobile LTE connection is going to be payed, I would like to favour available Wifis. Please add an option to have a fallback device that is enabled if no Wifi is available and disabled as soon as a Wiifi is available.

**Comment by dibdot** [comment]
Just give the travelmate interface a higher gateway metric than the LTE interface ... other than that this is out of scope (at least for me).
