### ISSUE TITLE
zerotier: segmentation fault

### ISSUE THREAD

**Issue by LGA1150** [openwrt/packages#18321]
Maintainer: @mwarning 
Environment: OpenWrt master, WRT1900AC v2 (ARM Cortex-A9)

Description:
ZeroTier version 1.8.6 no longer works on ARM (Segmenation fault). Version 1.8.4 ipk on 22.03-SNAPSHOT seems fine.

**Comment by jamesmacwhite** [comment]
FYI https://github.com/openwrt/packages/pull/18300

**Comment by jamesmacwhite** [comment]
This should be fixed now, the issue can be closed.
