### ISSUE TITLE
fwknop: dated source 

### ISSUE THREAD

**Issue by DazzyWalkman** [openwrt/packages#18330]
Maintainer: @jp-bennett 
The tarball on https://www.cipherdyne.org/fwknop/download/ is dated. 
The github repo https://github.com/mrash/fwknop/ 
seems to be more recent even though it only contains 2-3 more functional fixes. 
These changes, including a buffer size change, may have security implicaions and may worth upgrade.

**Comment by Ran-Xing** [comment]
t think so, and then fwknop not runing

**Comment by Ran-Xing** [comment]
please read /etc/init.d/fwknopd

**Comment by DazzyWalkman** [comment]
close with acc4d9058e98254b1c8dbd9a86347242dfc9912c
