### ISSUE TITLE
grep does not filter with 2 brackets together

### ISSUE THREAD

**Issue by Jeronimo17** [openwrt/packages#18349]
Maintainer: @Zokormazo (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)
OpenWrt 21.02.3, r16554-1d4dea6d4f  MediaTek MT7621 ver:1 eco:3 Newifi-D2
Description:

`echo Rocío | grep "Roc[ií][oó]" -E`
No result
`echo Rocío | grep "R[oó]cí[oó]" -E`
Rocío

**Comment by micmac1** [comment]
Hi!

The grep you're using is from busybox I reckon. In that case the packages repo is the wrong place for this issue.

On Debian I see the same behavior.

```
deb@deb:~$ echo Rocío | busybox grep "Roc[ií][oó]" -E
deb@deb:~$ echo Rocío | busybox grep "R[oó]cí[oó]" -E
Rocío
deb@deb:~$
```
In my humble opinion this is not an OpenWrt issue and should be reported to [busybox upstream]([busybox.net](https://busybox.net/)).

**Comment by Jeronimo17** [comment]
Yes it is busybox

Thank you
