### ISSUE TITLE
shadowsocks-libev: fail to start

### ISSUE THREAD

**Issue by zhanhb** [openwrt/packages#18393]
Maintainer: @yousong (find it by checking history of the package Makefile)
Environment: 22.03, master

Description:

```
ucode: unrecognized option: i
Syntax error: Expecting expression
In line 1, byte 2:

 `{%`
   ^-- Near here


Syntax error: Expecting expression
In line 6, byte 2:

 ``
  ^-- Near here


Syntax error: Unexpected token
Expecting '}'
In line 8, byte 2:

 ``
  ^-- Near here
```
See also:
- https://github.com/openwrt/openwrt/commit/23170c6f4ed01d5e2d838986e618564250b2cd8d
- https://github.com/jow-/ucode/compare/a29bad9454edcc285f7f37410b6822affede44d1..e14b0993b101839d2d40b5c4f184e6b0c2083b65

**Comment by yousong** [comment]
Hi, thank you for the detailed report.  I pushed a fix to the master branch here.  Please see if it fixes the issue for you.

**Comment by zhanhb** [comment]
Thans for the fixing. It works as expected for me.
