### ISSUE TITLE
Travelmate - Removing access points

### ISSUE THREAD

**Issue by RChadwick7** [openwrt/packages#18397]
I'm connecting Travelmate to two different access points, with the idea that when one gets flaky, it switches to the other one. It seems to work fine, except when the access points get flaky, they get permanently deactivated, and the Internet connection goes down. This is especially unfortunate when I'm trying to access it remotely.

**Comment by dibdot** [comment]
Just raise the overall connection/retry limit and/or set the "Connection End Expiry" for that connection.
