### ISSUE TITLE
miniupnpd: Luci-app doesnt show active redirects

### ISSUE THREAD

**Issue by Damian-208** [openwrt/packages#18451]
Maintainer: common packages maintainers
Environment: (MediaTek MT7628AN ver:1 eco:2, TP-Link TL-WR840N v4, OpenWrt 22.03.0-rc1 r19302-df622768da)

Description:

```
   .At the moment Luci-app-UPnP doesn't show the active redirects opened by the package. I know the package works because I can see the redirects when I check firewall(nftables) in Luci but I think the problem is because the code for the miniupnpd package is tied to iptables. It's a very minor issue so please can this be resolved? 🙏🏽🙏🏽
```
![Screenshot 2022-05-05 072401](https://user-images.githubusercontent.com/81205164/166863469-3c339743-aa99-4066-b741-701ad81887c5.png)
![Screenshot 2022-05-05 072429](https://user-images.githubusercontent.com/81205164/166863481-9470c0de-be1c-4de8-878c-4223da828800.png)

**Comment by kode54** [comment]
Here, try this diff/revision patch, or replacement, for `/usr/libexec/rpcd/luci.upnp` that correctly handles the display, but I'm not exactly sure if the deletion works properly.

https://gist.github.com/kode54/ae329a98df2ebdfd22f7a31ded20311d/revisions

**Comment by kode54** [comment]
Okay, I've since fixed both description reading and deletion. It appears to be fully working with firewall4 now.

**Comment by Ansuel** [comment]
Can you create a pr? You also tested the deletion right?

**Comment by kode54** [comment]
I verified deletion works. Where do I file the PR?

**Comment by firewire10000** [comment]
I have tried the **luci.upnp** file under **/usr/libexec/rpcd/luci.upnp** but I'm still seeing a blank table.
