### ISSUE TITLE
openvpn possibly fail to connect because of wrong order of remote_cert_tls and remote_cert_ku (remote_cert_eku)

### ISSUE THREAD

**Issue by beelze** [openwrt/packages#1846]
There is unable to use openvpn option 'remote-cert-tls client|server' and set non-default remote_cert_ku _after_ it, because of:
1. man openvpn says: «The --remote-cert-tls server option is equivalent to --remote-cert-ku a0 88 --remote-cert-eku "TLS Web Server Authentication"». Seems that it simply expanded to these 2 options, so it overrides remote_cert_ku options.
2. openvpn initscript enumerates options in alphabetical order, so remote-cert-tls will always be after remote-cert-{ku,eku}, overriding them.

Usecase for this problem is setting in «plain» config 'remote-cert-tls server' (which eliminates the need to use OID for TLS Web Client Authentication, and «fix» remote-cert-ku _after_ it. In current initscript it can't be done. 

fix is simple – to place remote-cert-{ku,eku} after remote-cert-tls in initscript.

**Comment by dibdot** [comment]
openvpn is not in the package repo.
