### ISSUE TITLE
vpnc: Update vpnc to support additional IKE DH groups

### ISSUE THREAD

**Issue by xelan** [openwrt/packages#18477]
Maintainer: @lipnitsk
Environment: All architectures,  OpenWRT 21

Description:
Rebuild vpnc using [the new upstream version](https://github.com/streambinder/vpnc) to support [the additional IKE DH Groups dh14/dh15/dh16/dh17/dh18](https://github.com/streambinder/vpnc/issues/27).

If you want, I can create a PR for this feature. Which target branch should be used so the new version lands in all supported versions?

**Comment by xelan** [comment]
See #18565

**Comment by Neustradamus** [comment]
@xelan: Linked to:
- https://github.com/openwrt/packages/pull/18602
- https://github.com/openwrt/packages/pull/18603
- https://github.com/openwrt/packages/pull/18565
