### ISSUE TITLE
Travelmate: interface 'trm_wwan' does not appear on ubus

### ISSUE THREAD

**Issue by Massimo-B** [openwrt/packages#18491]
Coming from https://forum.openwrt.org/t/travelmate-support-thread/5155/683?u=mssm

I did an upgrade from 19.07.3 to 21.02.2 without cleaning config. Generally everything is working fine, just in Travelmate I had the feeling that it does not connect to networks as expected. So I deleted the interface trm_wwan.
Is trm_wwan exclusively required for Travelmate? However I tried to re-create it by the button, but this fails. Here is what logs say:

`Thu May 5 11:36:39 2022 user.info trm-2.0.7[9046]: travelmate interface 'trm_wwan' does not appear on ubus, please check your network setup`

**Comment by dibdot** [comment]
Than start with a fresh config, it's a bad idea to keep the configuration during version updates.
