### ISSUE TITLE
openconnect: sed: bad option in substitution expression

### ISSUE THREAD

**Issue by mmokrejs** [openwrt/packages#18589]
Maintainer: @nmav
Environment: OpenWrt 21.02.0 r16279-5cc0535800 / LuCI openwrt-21.02 branch git-22.119.37126-a993714

Description: `sed` should use a different separator instead of a forward slash to delineate network number. It uses `#` for other arguments. Here is the problematic part:

```
"-e", "s/|IPV4ADDR|/192.168.2.0/24/g"
```

Here is remainder of the commandline as reported by `strace -s 1024 -v -f /etc/init.d/ocserv start` where `#` signs are already used as a delimiter:
```
, "-e", "s/|NETMASK|/255.255.255.0/g", "-e", "s#|IPV6ADDR|##g", "-e", "s/|ENABLE_IPV6|/#/g", "/etc/ocserv/ocserv.conf.template"]
```

Due to the above the daemon does not start:

`/etc/init.d/ocserv start`

![Screenshot 2022-05-21 at 22-26-06-Server Settings-LuCI](https://user-images.githubusercontent.com/3297852/169667955-4e8170b2-1f51-431f-9b1b-690f023b7dfb.png)

BTW, the help text is confusing. Should teh netmask be indeed 255.255.255.0. of the zero be replaced with 192 if the address range should span 62 addresses?

**Comment by nmav** [comment]
Thanks, would you like to propose a fix with a PR?

**Comment by mmokrejs** [comment]
No, sorry, I do not want t study structure of the project. I just have no time.
