### ISSUE TITLE
aria2: sending SIGSEGV to aria2c for invalid read access from 000XXXX

### ISSUE THREAD

**Issue by AdorableJiang** [openwrt/packages#18635]
Maintainer: @kaloz 
Environment: 
```
arch:MediaTek MT7621 ver:1 eco:3
model:HiWiFi HC5962
OpenWrt version: OpenWrt SNAPSHOT r19734-89562924b0 / LuCI Master git-22.137.71281-d6dbedd
```
Description:
P2P downloads (magnets&torrents) leads to Aria2 crash, while http links works fine.
```
Mon May 30 20:50:56 2022 kern.info kernel: [  997.832446] do_page_fault(): sending SIGSEGV to aria2c for invalid read access from 0008c79b
Mon May 30 20:50:56 2022 kern.info kernel: [  997.840925] epc = 77e10e08 in libc.so[77d92000+a9000]
Mon May 30 20:50:56 2022 kern.info kernel: [  997.845985] ra  = 77e12b5c in libc.so[77d92000+a9000]
```
[system.log](https://github.com/openwrt/packages/files/8798254/system.log)
[kernel.log](https://github.com/openwrt/packages/files/8798256/kernel.log)

-----
## Update Jun. 18, 2022
The problem exists in the to be released version `OpenWrt 22.03.0-rc4 r19426-2b1941e47d / LuCI openwrt-22.03 branch git-22.140.66268-ef99568`.

```
Sat Jun 18 18:53:25 2022 kern.info kernel: [ 1029.514712] do_page_fault(): sending SIGSEGV to aria2c for invalid read access from 0002e4ce
Sat Jun 18 18:53:25 2022 kern.info kernel: [ 1029.523211] epc = 77e9ce08 in libc.so[77e1e000+a9000]
Sat Jun 18 18:53:25 2022 kern.info kernel: [ 1029.528592] ra  = 77e9eb5c in libc.so[77e1e000+a9000]
Sat Jun 18 18:53:30 2022 daemon.err aria2c[22859]: Could not open /dev/crypto: Permission denied
```

**Comment by neheb** [comment]
I bet this has to do with 64-bit time_t...

**Comment by AdorableJiang** [comment]
> I bet this has to do with 64-bit time_t...

May I ask you to explain more?

**Comment by neheb** [comment]
I've seen a lot of PRs fixing problems with bad format strings that don't give enough space for 64-bit time_t. I would compile aria2 with -Werror=format=2 and see what issues pop up.

**Comment by AdorableJiang** [comment]
I downgrade openwrt to `OpenWrt 21.02.3 r16554-1d4dea6d4f / LuCI openwrt-21.02 branch git-22.083.69138-0a0ce2a`. The aria2 works fine and stable.

**Comment by AdorableJiang** [comment]
This is solved by clean (`rm /etc/config/aria2`) and re-configure aria2.
