### ISSUE TITLE
[netdata] package version 1.30.1-2 is outdated

### ISSUE THREAD

**Issue by cmonty14** [openwrt/packages#18779]
Maintainer: @\BKPepe, @\diizzyy
Environment: OpenWrt-21.02.0 

Description:
Package `netdata` is installed in version 1.30.1-2.
However this is an outdated version.

Can you please provide the latest version?

And why is netdata cloud disabled in [Makefile](https://github.com/openwrt/packages/blob/master/admin/netdata/Makefile#L68)?

**Comment by diizzyy** [comment]
We rarely do backports, if you want bleeding edge use master branch instead and 22.03 is just around the corner so might want to wait on that (1.33.1)

Cloud support is disabled becasue it pulls in a lot of extra dependencies and there's little to no support in maintaining it (feel free to submit a patch to master branch)
