### ISSUE TITLE
Can we have v2ray package

### ISSUE THREAD

**Issue by garysdevil** [openwrt/packages#18822]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/41293784/175822725-bc89760a-64e8-4ece-8a6d-025025dcd5eb.png">

**Comment by Mitsuhaxy** [comment]
You can use xray instead of v2ray, the configuration is fully compatible
`opkg install xray-core`

**Comment by 1715173329** [comment]
your device is even not officially supported, so how can "we" do that?

**Comment by garysdevil** [comment]
> your device is even not officially supported, so how can "we" do that?

I bought the device "GL_SFT1200", I can use "glinet" app to operate my router. Are you kidding me, it is not official?

**Comment by 1715173329** [comment]
> Are you kidding me, it is not official?

That depends on how you define "official". For OpenWrt, it's unofficial and unsupported.

**Comment by BKPepe** [comment]
You might want to reach [the OpenWrt community on the forum](https://forum.openwrt.org/) to request it. There is at least a GUI: https://github.com/openwrt/packages/blob/6544b67f1f2cb8fe806c67ef7e1a69a3ed138546/net/v2raya/Makefile
