### ISSUE TITLE
ddns-scripts: support for variomedia.de

### ISSUE THREAD

**Issue by w-oertl** [openwrt/packages#1884]
Hi! The following line makes the dyndns service of variomedia.de available for me. You might want to include it. It uses the DynDNS protocol over HTTPS. Manual installation of curl/wget and ca-certificates is needed (I use curl).

"variomedia.de"	"https://[USERNAME]:[PASSWORD]@dyndns.variomedia.de/nic/update?hostname=[DOMAIN]"

**Comment by chris5560** [comment]
IPv6 support ?
I'll implement in the next rollup. Thanks

Christian

**Comment by w-oertl** [comment]
Good point. Here are the updated lines for IPv4 and IPv6. Note the different hostname, dyndns4.variomedia.de vs. dyndns6.variomedia.de. The host dyndns.variomedia.de has both A and AAAA records, the others only one, with less potential for confusion.

"variomedia.de" "https://[USERNAME]:[PASSWORD]@dyndns4.variomedia.de/nic/update?hostname=[DOMAIN]&myip=[IP]"

"variomedia.de" "https://[USERNAME]:[PASSWORD]@dyndns6.variomedia.de/nic/update?hostname=[DOMAIN]&myip=[IP]"

**Comment by yousong** [comment]
Close this as the issue was resolved by ddns-scripts maintainer ;)
