### ISSUE TITLE
ser2net: Service starts to early during bootup?

### ISSUE THREAD

**Issue by ihrapsa** [openwrt/packages#18872]
Maintainer: @mhei 
Environment: mips mt7688an, OpenWrt SNAPSHOT, r19972-cf2c9c0e42, k5.10.125
Compiled: Wed Jun 29 16:01:58 2022

**Description:**
I'm using a mips device as a bridge between a serial device and a computer on my network. I've noticed that the `ser2net` service/program fails to establish the  connection to the serial device path when it first boots up (even though the process is running under `top`).

I've noticed that the `ser2net` service is set with a  `START=75` and I assumed that it might be starting to early. Changing it to `START=99` or the `rc.d` symlink to `S99ser2net` fixed my issue and I can successfully telnet to the device immediately after a cold boot without the need for a service restart.

Is there a specific reason why is it set to 75? Would it be possible to start it up a bit later during init sequence?

Thank you very much!

**Comment by mhei** [comment]
I don't remember why the value is 75. Since I guess, that no other process on the system itself directly depends on ser2net, I think, this should be no problem. I'll prepare a patch.

**Comment by ihrapsa** [comment]
> I don't remember why the value is 75. Since I guess, that no other process on the system itself directly depends on ser2net, I think, this should be no problem. I'll prepare a patch.

Thank you very much, sir! 🙂
