### ISSUE TITLE
ZNC service is broken 

### ISSUE THREAD

**Issue by tojestzart** [openwrt/packages#18894]
`<znc>: `

# Issue template (remove lines from top till here)

Maintainer: @\<Jonas Gorski/@KanjiMonster> (find it by checking history of the package Makefile)
Environment: (ANY)

Description:
https://github.com/openwrt/packages/blob/master/net/znc/files/znc.init

that whole service is an mistake and it should be removed or rewritten by someone with coding skills, thank you.
it should MOSTLY or ONLY rely on znc.conf file itself

Theres no trace how that shit haves on 'logread' except
"Sat Jul  9 10:18:34 2022 daemon.info procd: Instance znc::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
"
 wiki saying minimum requirement is to ``` A minimum configuration looks like this:

config 'znc'
	list 'listener'	'192.168.1.1 1234'  ```
WHICH IT overides orginal znc conffile itself (AND doesnt work xD)

ps. for me service is required only in case of powerloss or crash thats for service should be, not to change settings of powerfull package

**Comment by BKPepe** [comment]
> that whole service is an mistake and it should be removed or rewritten by someone with coding skills, thank you.

Thanks for sharing the feedback with us. We appreciate your kindness, and hopefully, you will be able to fix it and share with us how it should look according to the skilled professional developer. Any pull requests are welcome.
