### ISSUE TITLE
15.05 ar71xx: nodogsplash doesn't start at boot

### ISSUE THREAD

**Issue by nitr0man** [openwrt/packages#1893]
Configured nodogsplash doesn't start at boot, generated config is blank:

```
Tue Oct 27 11:35:14 2015 user.emerg syslog: nodogsplash: cfg0221da can not find ifname for network 'lan'
Tue Oct 27 11:35:14 2015 daemon.err nodogsplash: cfg0221da can not find ifname for network 'lan'
Tue Oct 27 11:35:14 2015 user.emerg syslog:  Testing required modules
Tue Oct 27 11:35:14 2015 user.emerg syslog:   Testing module ipt_mac 
Tue Oct 27 11:35:14 2015 user.emerg syslog:    ipt_mac is working
Tue Oct 27 11:35:14 2015 user.emerg syslog:   Testing module ipt_mark 
Tue Oct 27 11:35:14 2015 user.emerg syslog:    ipt_mark is working
Tue Oct 27 11:35:15 2015 user.emerg syslog: setting up led WAN
Tue Oct 27 11:35:15 2015 user.emerg syslog: setting up led LAN1
Tue Oct 27 11:35:15 2015 user.emerg syslog: setting up led LAN2
Tue Oct 27 11:35:15 2015 user.emerg syslog: setting up led LAN3
Tue Oct 27 11:35:15 2015 user.emerg syslog: setting up led LAN4
Tue Oct 27 11:35:15 2015 daemon.notice nodogsplash[921]: Reading and validating configuration file /tmp/etc/nodogsplash_cfg0221da.conf
Tue Oct 27 11:35:15 2015 daemon.err nodogsplash[921]: GatewayInterface is not set
Tue Oct 27 11:35:15 2015 daemon.err nodogsplash[921]: Configuration is not complete, exiting...
```

When I run it by '/etc/init.d/nodogsplash start' - all is OK.

Image: openwrt-15.05-ar71xx-generic-tl-wr841n-v9-squashfs-factory.bin

Config:

```
root@OpenWrt:~# uci show nodogsplash
nodogsplash.@instance[0]=instance
nodogsplash.@instance[0].network='lan'
nodogsplash.@instance[0].idletimeout='1200'
nodogsplash.@instance[0].preauthenticated_users='allow tcp port 53' 'allow udp port 53' 'allow tcp port 22'
nodogsplash.@instance[0].users_to_router='allow tcp port 22' 'allow tcp port 23' 'allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 80' 'allow tcp port 443'
nodogsplash.@instance[0].enabled='1'
nodogsplash.@instance[0].maxclients='30'
nodogsplash.@instance[0].authenticated_users='allow tcp port 53' 'allow udp port 53' 'allow tcp port 22' 'block to 192.168.0.0/16' 'block to 10.0.0.0/8' 'allow tcp port 80' 'allow tcp port 443' 'allow tcp port 143' 'allow tcp port 110' 'allow tcp port 3349' 'allow udp port 3349' 'allow tcp port 1723' 'allow tcp port 5222' 'allow tcp port 5223'
nodogsplash.@instance[0].gatewayname='Free HotSpot'

```

It happens when wlan0 is lan interface; when lan is bridge that includes wlan0 - all is ok.

**Comment by mathiashro** [comment]
I confirm the issue. Furthermore this issue does not happen when I do a config change via Luci/UCI and apply the config. Looks like a special race condition. See also:
https://dev.opennet-initiative.de/ticket/136

Test via:
(. /lib/functions/network.sh; network_get_device ifname <your-interface-name>; echo $ifname)

When this test does return valid data nodogsplash will be successfully started, if not nodogsplash will fail.

**Comment by yousong** [comment]
I cannot find `nodogsplash` in this repo.  Where is it maintained and who is the current maintainer?

BTW. it looks like that the issue was just that `wlan0` as the `lan` interface was just not ready at the time that script was running.  If that was the case, it should possibly be workarounded with 3 choices

- Add procd interface trigger
- Add a hotplug script for wlan0
- Rename the package's init script with a `99-` prefix

**Comment by diizzyy** [comment]
@hnyman @thess 
Out of tree/repo package, please close this.

**Comment by hnyman** [comment]
The package is in the routing repo, that is the correct place.
https://github.com/openwrt-routing/packages
