### ISSUE TITLE
/usr/lib/unbound/odhcpd.sh found TYPO

### ISSUE THREAD

**Issue by 1d01t** [openwrt/packages#18944]
Maintainer: @\EricLuehrsen
Environment: OpenWrt 21.02.3

Description:

I installed unbound and odhcpd at my OpenWrt, which runs on RPI3 B+.
The script /usr/lib/unbound/odhcpd.sh to load DNS names of clients dynamically into unbound has a little typo.

It tries to fill its variables with:
```
  local dhcp_link=$( uci_get unbound.@unbound[0].dhcp_link )
  local dhcp4_slaac6=$( uci_get unbound.@unbound[0].dhcp4_slaac6 )
  local dhcp_domain=$( uci_get unbound.@unbound[0].domain )
  local dhcp_origin=$( uci_get dhcp.@odhcpd[0].leasefile )
```
But it should look like this (with whitespace instead of underscore between "uci" and "get"):
```
  local dhcp_link=$( uci get unbound.@unbound[0].dhcp_link )
  local dhcp4_slaac6=$( uci get unbound.@unbound[0].dhcp4_slaac6 )
  local dhcp_domain=$( uci get unbound.@unbound[0].domain )
  local dhcp_origin=$( uci get dhcp.@odhcpd[0].leasefile )
```

Also i think it could be a good idea to give a note on installation, 
to tell the admin, that he should run the script to see, if everything is property setup in unbound config :)

Beside this the script does an awesome job. Thanks a lot for this :D

**Comment by jow-** [comment]
1) The function `uci_get()` is declared by `/lib/config/uci.sh` which is sourced by `/lib/functions.sh`
2) `/usr/lib/unbound/odhcpd.sh` is not supposed to be executed by the user directly, [it runs as lease trigger script invoked by odhcpd](https://github.com/openwrt/packages/tree/master/net/unbound/files#unbound-and-odhcpd)
