### ISSUE TITLE
irqbalance: build failure

### ISSUE THREAD

**Issue by anomeome** [openwrt/packages#18943]
@neheb the libiconv push? on  master build

`/home/kc/wrtpac/source/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-12.1.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/12.1.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: cannot find -liconv
`

**Comment by anomeome** [comment]
hmm, older PR 18733

**Comment by neheb** [comment]
I have a PR that fixes this, yes. Still unmerged.

**Comment by rmandrad** [comment]
> I have a PR that fixes this, yes. Still unmerged.

do you have the PR i am now unable to compile irqbalance

@anomeome  can't find PR  18733 ... pls share the link thx

**Comment by dhewg** [comment]
No clue if this breaks iconv-full, but my local hack gets this built at least:
```
diff --git a/utils/irqbalance/Makefile b/utils/irqbalance/Makefile
index 6347ee153..fc791f1be 100644
--- a/utils/irqbalance/Makefile
+++ b/utils/irqbalance/Makefile
@@ -62,7 +62,7 @@ endif
 
 CONFIGURE_VARS += \
    GLIB2_LIBS="$(GLIB2_LIBS) \
-       $(ICONV_LDFLAGS) -liconv"
+       $(ICONV_LDFLAGS)"
 
 define Package/irqbalance/conffiles
 /etc/config/irqbalance
```

**Comment by rmandrad** [comment]
it just been merged :) thx
