### ISSUE TITLE
dns over https proxy stopped working in master.

### ISSUE THREAD

**Issue by tapper82** [openwrt/packages#19003]
Fresh build of master. 
TappersRouter
Model Netgear Nighthawk X4S R7800
Architecture ARMv7 Processor rev 0 (v7l)
Target Platform ipq806x/generic
Firmware Version OpenWrt SNAPSHOT r20146-bc43ad88ed / LuCI Master git-22.189.49133-e193259
Kernel Version 5.15.53

I built dns over https proxy in to my build.
This is with fresh configs.
When I click the start button on the dns over https proxy page it kills DNS.

This is with the proxy off.

/etc/config/https-dns-proxy

config main 'config'
	option force_dns '1'
	list force_dns_port '53'
	list force_dns_port '853'
	option update_dnsmasq_config '0'

config https-dns-proxy
	option listen_addr '127.0.0.1'
	option listen_port '5054'
	option user 'nobody'
	option group 'nogroup'
	option bootstrap_dns '1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001'
	option resolver_url 'https://cloudflare-dns.com/dns-query'

/etc/config/dhcp

config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'
	option ednspacket_max '1232'
	list server '/use-application-dns.net/'
	option confdir '/tmp/dnsmasq.d'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	option ra_slaac '1'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

/etc/config/firewall

config defaults
	option syn_flood	1
	option input		ACCEPT
	option output		ACCEPT
	option forward		REJECT
# Uncomment this line to disable ipv6 rules
#	option disable_ipv6	1

config zone
	option name		lan
	list   network		'lan'
	option input		ACCEPT
	option output		ACCEPT
	option forward		ACCEPT

config zone
	option name		wan
	list   network		'wan'
	list   network		'wan6'
	option input		REJECT
	option output		ACCEPT
	option forward		REJECT
	option masq		1
	option mtu_fix		1

config forwarding
	option src		lan
	option dest		wan

# We need to accept udp packets on port 68,
# see https://dev.openwrt.org/ticket/4108
config rule
	option name		Allow-DHCP-Renew
	option src		wan
	option proto		udp
	option dest_port	68
	option target		ACCEPT
	option family		ipv4

# Allow IPv4 ping
config rule
	option name		Allow-Ping
	option src		wan
	option proto		icmp
	option icmp_type	echo-request
	option family		ipv4
	option target		ACCEPT

config rule
	option name		Allow-IGMP
	option src		wan
	option proto		igmp
	option family		ipv4
	option target		ACCEPT

# Allow DHCPv6 replies
# see https://github.com/openwrt/openwrt/issues/5066
config rule
	option name		Allow-DHCPv6
	option src		wan
	option proto		udp
	option dest_port	546
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-MLD
	option src		wan
	option proto		icmp
	option src_ip		fe80::/10
	list icmp_type		'130/0'
	list icmp_type		'131/0'
	list icmp_type		'132/0'
	list icmp_type		'143/0'
	option family		ipv6
	option target		ACCEPT

# Allow essential incoming IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Input
	option src		wan
	option proto	icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	list icmp_type		router-solicitation
	list icmp_type		neighbour-solicitation
	list icmp_type		router-advertisement
	list icmp_type		neighbour-advertisement
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

# Allow essential forwarded IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Forward
	option src		wan
	option dest		*
	option proto		icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-IPSec-ESP
	option src		wan
	option dest		lan
	option proto		esp
	option target		ACCEPT

config rule
	option name		Allow-ISAKMP
	option src		wan
	option dest		lan
	option dest_port	500
	option proto		udp
	option target		ACCEPT

config rule
	option name 'Block-Outbound-TFTP'
	option src 'lan'
	option dest 'wan'
	option dest_port '69'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-Syslog'
	option src 'lan'
	option dest 'wan'
	option dest_port '514'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-SNMP'
	option src 'lan'
	option dest 'wan'
	option dest_port '161 162'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-SMB'
	option src 'lan'
	option dest 'wan'
	option dest_port '135 137 138 139 445'
	option proto 'tcpudp'
	option family 'any'
	option target 'REJECT'

config rule
	option proto 'tcp'
	option dest_port '22'
	option name 'Block SSH from lan2'
	option family 'ipv4'
	option src 'lan2'
	option dest 'wan'
	option target 'REJECT'

This is the info when the proxy is on. All I am going to do is click the start botton in the https proxy page witch will kill all dns for me.

/etc/config/dhcp

config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'
	option ednspacket_max '1232'
	list server '/use-application-dns.net/'
	list server '127.0.0.1#5054'
	option confdir '/tmp/dnsmasq.d'
	option noresolv '1'
	option doh_backup_noresolv '-1'
	list doh_backup_server '/use-application-dns.net/'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	option ra_slaac '1'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

/etc/config/firewall

config defaults
	option syn_flood	1
	option input		ACCEPT
	option output		ACCEPT
	option forward		REJECT
# Uncomment this line to disable ipv6 rules
#	option disable_ipv6	1

config zone
	option name		lan
	list   network		'lan'
	option input		ACCEPT
	option output		ACCEPT
	option forward		ACCEPT

config zone
	option name		wan
	list   network		'wan'
	list   network		'wan6'
	option input		REJECT
	option output		ACCEPT
	option forward		REJECT
	option masq		1
	option mtu_fix		1

config forwarding
	option src		lan
	option dest		wan

# We need to accept udp packets on port 68,
# see https://dev.openwrt.org/ticket/4108
config rule
	option name		Allow-DHCP-Renew
	option src		wan
	option proto		udp
	option dest_port	68
	option target		ACCEPT
	option family		ipv4

# Allow IPv4 ping
config rule
	option name		Allow-Ping
	option src		wan
	option proto		icmp
	option icmp_type	echo-request
	option family		ipv4
	option target		ACCEPT

config rule
	option name		Allow-IGMP
	option src		wan
	option proto		igmp
	option family		ipv4
	option target		ACCEPT

# Allow DHCPv6 replies
# see https://github.com/openwrt/openwrt/issues/5066
config rule
	option name		Allow-DHCPv6
	option src		wan
	option proto		udp
	option dest_port	546
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-MLD
	option src		wan
	option proto		icmp
	option src_ip		fe80::/10
	list icmp_type		'130/0'
	list icmp_type		'131/0'
	list icmp_type		'132/0'
	list icmp_type		'143/0'
	option family		ipv6
	option target		ACCEPT

# Allow essential incoming IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Input
	option src		wan
	option proto	icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	list icmp_type		router-solicitation
	list icmp_type		neighbour-solicitation
	list icmp_type		router-advertisement
	list icmp_type		neighbour-advertisement
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

# Allow essential forwarded IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Forward
	option src		wan
	option dest		*
	option proto		icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-IPSec-ESP
	option src		wan
	option dest		lan
	option proto		esp
	option target		ACCEPT

config rule
	option name		Allow-ISAKMP
	option src		wan
	option dest		lan
	option dest_port	500
	option proto		udp
	option target		ACCEPT

config rule
	option name 'Block-Outbound-TFTP'
	option src 'lan'
	option dest 'wan'
	option dest_port '69'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-Syslog'
	option src 'lan'
	option dest 'wan'
	option dest_port '514'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-SNMP'
	option src 'lan'
	option dest 'wan'
	option dest_port '161 162'
	option proto 'udp'
	option family 'any'
	option target 'REJECT'

config rule
	option name 'Block-Outbound-SMB'
	option src 'lan'
	option dest 'wan'
	option dest_port '135 137 138 139 445'
	option proto 'tcpudp'
	option family 'any'
	option target 'REJECT'

config rule
	option proto 'tcp'
	option dest_port '22'
	option name 'Block SSH from lan2'
	option family 'ipv4'
	option src 'lan2'
	option dest 'wan'
	option target 'REJECT'

/etc/config/https-dns-proxy

config main 'config'
	option force_dns '1'
	list force_dns_port '53'
	list force_dns_port '853'
	option update_dnsmasq_config '0'

config https-dns-proxy
	option listen_addr '127.0.0.1'
	option listen_port '5054'
	option user 'nobody'
	option group 'nogroup'
	option bootstrap_dns '1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001'
	option resolver_url 'https://cloudflare-dns.com/dns-query'

**Comment by tapper82** [comment]
Here is what I get in my logs.


Thu Jul 21 20:40:40 2022 daemon.info https-dns-proxy[22352]: [F]    92232.1658432440 (null):631144 79B1: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:40:46 2022 daemon.info https-dns-proxy[22441]: [F]    92232.1658432446 (null):637200 79B1: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:40:51 2022 daemon.info https-dns-proxy[22442]: [F]    92232.1658432451 (null):841949 79B1: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:40:56 2022 daemon.info https-dns-proxy[22443]: [F]    92232.1658432456 (null):941003 3E66: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:41:02 2022 daemon.info https-dns-proxy[22444]: [F]    92232.1658432462 (null):21621 3E66: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:41:07 2022 daemon.info https-dns-proxy[22449]: [F]    92232.1658432467 (null):70491 3E66: CURLOPT_SSLVERSION error 4: Error
Thu Jul 21 20:41:07 2022 daemon.info procd: Instance https-dns-proxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Jul 21 20:41:54 2022 daemon.warn dnsmasq[1]: Maximum number of concurrent DNS queries reached (max: 150)
Thu Jul 21 20:41:57 2022 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Thu Jul 21 20:42:00 2022 user.notice https-dns-proxy: Stopping service ✓
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: started, version 2.86 cachesize 150
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: DNS service limited to local subnets
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-cryptohash no-DNSSEC no-ID loop-detect inotify dumpfile
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for test
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for local
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for adz.co.zw
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for trust.zone
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using 70553 more local addresses
Thu Jul 21 20:42:00 2022 daemon.err uhttpd[721]: sh: curl: not found
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using nameserver 194.168.4.100#53
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using nameserver 194.168.8.100#53
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for test
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for local
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for adz.co.zw
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using only locally-known addresses for trust.zone
Thu Jul 21 20:42:00 2022 daemon.info dnsmasq[1]: using 70553 more local addresses
Thu Jul 21 20:42:01 2022 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Thu Jul 21 20:42:01 2022 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Thu Jul 21 20:42:01 2022 daemon.info dnsmasq[1]: read /tmp/hosts/odhcpd - 3 addresses
Thu Jul 21 20:42:01 2022 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses

**Comment by tapper82** [comment]
@stangri

**Comment by stangri** [comment]
Check if you have curl/libcurl installed.

**Comment by tapper82** [comment]
List of installed packages.

adblock - 4.1.3-9
ath10k-board-qca9984 - 20220708-1
ath10k-firmware-qca9984-ct - 2020-11-08-1
attr - 2.5.1-1
avahi-dbus-daemon - 0.8-7
base-files - 1491-r20151-a0b7fef0ff
block-mount - 2022-07-17-ebf7e902-1
blockd - 2022-07-17-ebf7e902-1
busybox - 1.35.0-3
ca-bundle - 20211016-1
cgi-io - 2021-09-08-98cef9dd-20
coreutils - 9.1-1
coreutils-sort - 9.1-1
curl - 7.83.1-2
dbus - 1.13.18-12
dnsmasq - 2.86-14
dropbear - 2022.82-2
e2fsprogs - 1.46.5-1
firewall4 - 2022-06-17-15c38317-1
fstools - 2022-07-17-ebf7e902-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2022-07-17-46a33b8b-1
hostapd-common - 2022-06-02-4383528e-11
https-dns-proxy - 2021-11-22-3
irqbalance - 1.9.0-6
iw - 5.19-1
iwinfo - 2022-04-26-dc6847eb-1
jansson5 - 2.14-2
jshn - 2022-05-15-d2223ef9-1
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.15.53-1-b74d1c5fc794ff68fd474ac2015d8349
kmod-ata-ahci - 5.15.53-1
kmod-ata-ahci-platform - 5.15.53-1
kmod-ata-core - 5.15.53-1
kmod-ath - 5.15.53+5.15.33-1-1
kmod-ath10k-ct - 5.15.53+2022-05-13-f808496f-1
kmod-cfg80211 - 5.15.53+5.15.33-1-1
kmod-crypto-acompress - 5.15.53-1
kmod-crypto-aead - 5.15.53-1
kmod-crypto-ccm - 5.15.53-1
kmod-crypto-cmac - 5.15.53-1
kmod-crypto-crc32c - 5.15.53-1
kmod-crypto-ctr - 5.15.53-1
kmod-crypto-gcm - 5.15.53-1
kmod-crypto-gf128 - 5.15.53-1
kmod-crypto-ghash - 5.15.53-1
kmod-crypto-hash - 5.15.53-1
kmod-crypto-hmac - 5.15.53-1
kmod-crypto-manager - 5.15.53-1
kmod-crypto-null - 5.15.53-1
kmod-crypto-rng - 5.15.53-1
kmod-crypto-seqiv - 5.15.53-1
kmod-crypto-sha256 - 5.15.53-1
kmod-fs-autofs4 - 5.15.53-1
kmod-fs-exfat - 5.15.53-1
kmod-gpio-button-hotplug - 5.15.53-3
kmod-hwmon-core - 5.15.53-1
kmod-leds-gpio - 5.15.53-1
kmod-lib-crc-ccitt - 5.15.53-1
kmod-lib-crc32c - 5.15.53-1
kmod-lib-lzo - 5.15.53-1
kmod-mac80211 - 5.15.53+5.15.33-1-1
kmod-nf-conntrack - 5.15.53-1
kmod-nf-conntrack6 - 5.15.53-1
kmod-nf-flow - 5.15.53-1
kmod-nf-log - 5.15.53-1
kmod-nf-log6 - 5.15.53-1
kmod-nf-nat - 5.15.53-1
kmod-nf-nat6 - 5.15.53-1
kmod-nf-reject - 5.15.53-1
kmod-nf-reject6 - 5.15.53-1
kmod-nfnetlink - 5.15.53-1
kmod-nft-core - 5.15.53-1
kmod-nft-fib - 5.15.53-1
kmod-nft-nat - 5.15.53-1
kmod-nft-nat6 - 5.15.53-1
kmod-nft-offload - 5.15.53-1
kmod-nls-base - 5.15.53-1
kmod-phy-qcom-ipq806x-usb - 5.15.53-1
kmod-ppp - 5.15.53-1
kmod-pppoe - 5.15.53-1
kmod-pppox - 5.15.53-1
kmod-pstore - 5.15.53-1
kmod-ramoops - 5.15.53-1
kmod-reed-solomon - 5.15.53-1
kmod-scsi-core - 5.15.53-1
kmod-slhc - 5.15.53-1
kmod-usb-core - 5.15.53-1
kmod-usb-dwc3 - 5.15.53-1
kmod-usb-dwc3-qcom - 5.15.53-1
kmod-usb-ehci - 5.15.53-1
kmod-usb-ledtrig-usbport - 5.15.53-1
kmod-usb-ohci - 5.15.53-1
kmod-usb-storage - 5.15.53-1
kmod-usb-xhci-hcd - 5.15.53-1
kmod-usb2 - 5.15.53-1
kmod-usb3 - 5.15.53-1
libatomic1 - 11.3.0-4
libattr - 2.5.1-1
libavahi-client - 0.8-7
libavahi-dbus-support - 0.8-7
libblkid1 - 2.38-2
libblobmsg-json20220515 - 2022-05-15-d2223ef9-1
libc - 1.2.3-4
libcap - 2.63-1
libcares - 1.18.1-1
libcomerr0 - 1.46.5-1
libcurl4 - 7.83.1-2
libdaemon - 0.14-5
libdbus - 1.13.18-12
libev - 4.33-1
libexpat - 2.4.7-2
libext2fs2 - 1.46.5-1
libgcc1 - 11.3.0-4
libgmp10 - 6.2.1-1
libgnutls - 3.7.6-3
libiwinfo-data - 2022-04-26-dc6847eb-1
libiwinfo-lua - 2022-04-26-dc6847eb-1
libiwinfo20210430 - 2022-04-26-dc6847eb-1
libjson-c5 - 0.16-2
libjson-script20220515 - 2022-05-15-d2223ef9-1
liblua5.1.5 - 5.1.5-10
liblucihttp-lua - 2022-07-08-6e68a106-1
liblucihttp0 - 2022-07-08-6e68a106-1
libmnl0 - 1.0.5-1
libncurses6 - 6.3-1
libnettle8 - 3.8-1
libnftnl11 - 1.2.2-1
libnghttp2-14 - 1.44.0-1
libnl-tiny2022-05-17 - 2022-05-17-b5b2ba09-1
libopenssl1.1 - 1.1.1q-1
libpcap1 - 1.10.1-3
libpopt0 - 1.16-2
libpthread - 1.2.3-4
libreadline8 - 8.1-1
librt - 1.2.3-4
libss2 - 1.46.5-1
libtasn1 - 4.16.0-2
libtirpc - 1.3.2-3
libubox20220515 - 2022-05-15-d2223ef9-1
libubus-lua - 2022-06-01-2bebf93c-1
libubus20220601 - 2022-06-01-2bebf93c-1
libuci20130104 - 2021-10-22-f84f49f0-6
libuclient20201210 - 2021-05-14-6a6011df-1
libucode20220322 - 2022-06-01-b211ca0e-1
liburing - 2.2-1
libustream-wolfssl20201210 - 2022-01-16-868fd881-1
libuuid1 - 2.38-2
libwolfssl5.4.0.e624513f - 5.4.0-stable-2
logd - 2022-07-17-46a33b8b-1
lua - 5.1.5-10
luci - git-20.074.84698-ead5e81
luci-app-adblock - git-22.069.45071-abbff0f
luci-app-firewall - git-22.089.67453-0eb3aeb
luci-app-https-dns-proxy - 2021-09-27-3
luci-app-opkg - git-22.154.41762-b84791b
luci-app-samba4 - git-21.223.80587-f533f9d
luci-base - git-22.189.49133-e193259
luci-compat - git-22.069.45071-03bb0e2
luci-lib-base - git-20.232.39649-1f6dc29
luci-lib-ip - git-20.250.76529-62505bd
luci-lib-jsonc - git-22.079.54693-45f411b
luci-lib-nixio - git-20.234.06894-c4a4e43
luci-mod-admin-full - git-19.253.48496-3f93650
luci-mod-network - git-22.193.51150-ef7fe79
luci-mod-status - git-22.186.43238-88c62fe
luci-mod-system - git-22.125.76098-24ac5a2
luci-proto-ipv6 - git-21.148.48881-79947af
luci-proto-ppp - git-21.158.38888-88b9d84
luci-ssl - git-20.244.36115-e10f954
luci-theme-bootstrap - git-22.175.85350-d4c4afe
mtd - 26
netifd - 2022-06-01-39ef9fe1-1
nftables-json - 1.0.4-1
odhcp6c - 2021-12-05-39b584bc-18
odhcpd-ipv6only - 2022-03-22-860ca900-1
openwrt-keyring - 2022-03-25-62471e69-2
opkg - 2022-02-24-d038e5b6-1
ppp - 2.4.9.git-2021-01-04-3
ppp-mod-pppoe - 2.4.9.git-2021-01-04-3
procd - 2022-07-17-ef5d3e36-1
procd-seccomp - 2022-07-17-ef5d3e36-1
procd-ujail - 2022-07-17-ef5d3e36-1
px5g-wolfssl - 4
rpcd - 2022-05-31-1c482573-1
rpcd-mod-file - 2022-05-31-1c482573-1
rpcd-mod-iwinfo - 2022-05-31-1c482573-1
rpcd-mod-luci - 20210614
rpcd-mod-rrdns - 20170710
samba4-libs - 4.14.12-5
samba4-server - 4.14.12-5
swconfig - 12
tcpdump - 4.99.1-1
terminfo - 6.3-1
ubi-utils - 2.1.4-1
uboot-envtools - 2022.01-38
ubox - 2022-07-17-46a33b8b-1
ubus - 2022-06-01-2bebf93c-1
ubusd - 2022-06-01-2bebf93c-1
uci - 2021-10-22-f84f49f0-6
uclient-fetch - 2021-05-14-6a6011df-1
ucode - 2022-06-01-b211ca0e-1
ucode-mod-fs - 2022-06-01-b211ca0e-1
ucode-mod-ubus - 2022-06-01-b211ca0e-1
ucode-mod-uci - 2022-06-01-b211ca0e-1
uhttpd - 2022-06-01-d59d732a-1
uhttpd-mod-ubus - 2022-06-01-d59d732a-1
urandom-seed - 3
urngd - 2020-01-21-c7f7b6b6-1
usign - 2020-05-23-f1f65026-1
wireless-regdb - 2022.06.06-1
wpad-basic-wolfssl - 2022-06-02-4383528e-11
wsdd2 - 2021-10-22-9831daf2-3
zlib - 1.2.12-2

**Comment by tapper82** [comment]
@stangri I am sorry to have mest you about, but it started working for me. I don't know what I did or how I fixt it. Thanks for looking.

**Comment by tapper82** [comment]
If it messes upagain I will reopen this with as mutch info as I can get for you.
