### ISSUE TITLE
kmod-rtw88: Realtek RTL8822BE WiFi adapter not functional.

### ISSUE THREAD

**Issue by developer422** [openwrt/packages#19026]
Maintainer: @nbd168
Environment: bcm27xx/bcm2711 OpenWrt 22.03.0-rc5

Description: When I try to setup a Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter on a Raspberry Pi CM4 board, I get the following errors in the system log:
```
root@OpenWrt:~# dmesg | grep rtw
[    7.602012] rtw_8822be 0000:03:00.0: enabling device (0000 -> 0002)
[    7.608355] rtw_8822be 0000:03:00.0: failed to allocate tx ring
[    7.614292] rtw_8822be 0000:03:00.0: failed to allocate pci resources
[    7.620895] rtw_8822be 0000:03:00.0: failed to setup pci resources
[    7.629636] rtw_8822be 0000:03:00.0: Firmware version 27.2.0, H2C version 13
[    7.631335] rtw_8822be: probe of 0000:03:00.0 failed with error -12
```
The adapter is not functional.

I started by building OpenWrt 22.03.0-rc5 with the following packages enabled (make menuconfig): **kmod-rtw88** and **rtl8822be-firmware**, followed by flashing the image onto an RPi CM4 board via the LuCi web interface.

**Comment by BKPepe** [comment]
This package is not in this repository. I suggest opening your issue in [the main repository](https://github.com/openwrt/openwrt/issues). I am not able to transfer the issue there since I don't have permission overthere.
