### ISSUE TITLE
openwrt davfs2 does not write to a remote disk.

### ISSUE THREAD

**Issue by youpla** [openwrt/packages#1907]
Hi,
Writing a small text file (10 kb) to a owncloud 8.1 server from davfs2 running on openwrt fails.
If  "use_lock  is set to 1" you end up with a 0 byte file on the owncloud server
If  "use_lock is set to 0" you end up with no file on the owncloud server. The file is displayed on openwrt and stored in the local cache.

It's been reported here:
https://dev.openwrt.org/ticket/18053#no1

Someone wrote this workaround here:
https://dev.openwrt.org/ticket/20770

Thanks

**Comment by yousong** [comment]
Should be fixed by #2102
