### ISSUE TITLE
mosquitto package lacks mosquitto_passwd utility

### ISSUE THREAD

**Issue by eduperez** [openwrt/packages#1909]
Neither mosquitto nor mosquitto_nossl packages contain utility mosquitto_passwd; this utility is necessary to create users for mosquitto.

**Comment by karlp** [comment]
Fair enough, I'll add it in.  I don't use it myself, so never bothered packaging it.

**Comment by mhei** [comment]
Hi @karlp, could you please have a look on this patch. It's only compile tested.

**Comment by karlp** [comment]
Yep, sorry, I was off on holidays all december, will merge this and update mosquitto this week I expect

**Comment by karlp** [comment]
What do you think about just https://github.com/remakeelectric/owrt_pub_feeds/commit/472ed6c5a93bda2385e8a0e2ecb3550c49938b12

I'm bumping up to the newest release too, just have to get a CC build tested.

**Comment by mhei** [comment]
Actually, I do not use this package at all, I only looked over all tickets to see where I could help to reduce the backlog... so I'm far away from knowing whether your patch would be the better approach.

My patch introduced a new package because I simply don't like packages which vary depending on config symbols, and in this case we already have the ssl/nossl stuff for this source package.
But this is my personal feeling and you are the maintainer :smile: I can live with every decision you will make :+1:

**Comment by karlp** [comment]
Fixed in both CC and trunk, along with updates to newest.  Sorry about the delay!

**Comment by ronyboss** [comment]
I am getting error while making openwrt with mosquitto_password utility.

make[3]: Entering directory '/home/rony/linuxBuild/openwrt_rpi/openwrt/feeds/packages/net/mosquitto'
Makefile:196: *** missing separator.  Stop.

Any idea what is missing in makefile of mosquitto?

**Comment by ronyboss** [comment]
I did tried the recipe of @mhei , and it worked for me. But newly added makefile of you Mr. @karlp . Didn't worked for me somehow. Would you like to check the issue @karlp ? And let me know if I am doing anything wrong.

Thanks in advance.

**Comment by karlp** [comment]
make sure you don't have some remnant of both makefiles?

**Comment by ronyboss** [comment]
No I don't. I used your makefile, and having error. Then I totally replaced the makefile of your with mhei's one. And that worked.

**Comment by jow-** [comment]
Separator error fixed with 6d20db9138156e2acc189cb05a2948fbae8b2d07

**Comment by karlp** [comment]
Oh damnit, now I see what had happened.  This got munched moving from my local branch to the commit branch :(  Thanks @jow-  for fixing my mistakes :(

**Comment by ronyboss** [comment]
Thanks @jow-  It worked. @karlp It is resolved now.

**Comment by ortegafernando** [comment]
Hi, sorry yo reopen it but I have openwrt 17.04 version an after installing mosquitto package I can't run mosquitto_passwd utility. It can't find it.
Thanks.

**Comment by ortegafernando** [comment]
ok, thanks and sorry
