### ISSUE TITLE
strongswan: version 5.9.6 introduced new plugin (kdf), new subpackage strongswan-mod-kdf is needed

### ISSUE THREAD

**Issue by GitArUs** [openwrt/packages#19115]
Changelog: https://github.com/strongswan/strongswan/releases/tag/5.9.6

libstrongswan-kdf.so is compiled, but not packaged.

Problems with ikev2 were introduced most likely because of missing kdf plugin:

[IKE] KDF_PRF with PRF_UNDEFINED not supported
[IKE] key derivation failed

**Comment by pprindeville** [comment]
@Thermi Do you have time to look into this?

**Comment by Neustradamus** [comment]
@GitArUs: A PR for 5.9.7 version here:
- https://github.com/openwrt/packages/pull/19128

**Comment by GitArUs** [comment]
PR #19128 looks good to me. Presence of kdf plugin indeed fixes issue with ikev2. Thanks.

**Comment by Neustradamus** [comment]
@pprindeville has needed testers, can you reply on the PR?

**Comment by Thermi** [comment]
We're not yet done with this because the botan, openssl. and wolfssl plugins for example also provides KDFs, so the kdf plugin is actually optional.

**Comment by pprindeville** [comment]
Doh.  Saw @Thermi's comment too late for PR #19128.

**Comment by Thermi** [comment]
don't mind, we'll do it better next time.

**Comment by pprindeville** [comment]
Want to take a stab at it?

**Comment by Thermi** [comment]
This should be a reasonable implementation of that: https://github.com/openwrt/packages/pull/19145

**Comment by Thermi** [comment]
done

**Comment by GitArUs** [comment]
Works for me. Thank You. I'm closing this.
