### ISSUE TITLE
sslh in 22.03 - Upgrade to version 1.22c needed

### ISSUE THREAD

**Issue by timothyh** [openwrt/packages#19122]
sslh:
Maintainer: @\jmccrohan
Environment: all
Description:

Sslh version 1.21c currently included with 22.03 is broken due to incompatibility with libconfig 1.7.3.
Sslh verion 1.22c, currently in snapshots, works fine.

Thanks

**Comment by BKPepe** [comment]
Fixed by https://github.com/openwrt/packages/commit/cd36b6eb8b8d4082373b7feae702c9abc1881acc
