### ISSUE TITLE
dnscrypt-proxy2: update to v2.1.2

### ISSUE THREAD

**Issue by elgatov** [openwrt/packages#19149]
Maintainer: @BKPepe 
Environment: `OpenWrt 21.02.0, r16279-5cc0535800`

Description:

`dnscrypt-proxy2` has been [recently updated](https://github.com/dnscrypt/dnscrypt-proxy/releases/tag/2.1.2) with an important fix:

> In previous versions, memory usage kept growing due to channels not being properly closed, causing goroutines to pile up. This was fixed, resulting in an important reduction of memory usage. Thanks to @lifenjoiner for investigating and fixing this!

Sometimes, when the device was running out of memory (around 80%), it would trigger oom-reaper and kill the `dnscrypt-proxy2` process, which in turn would start the cycle again.

**Comment by BKPepe** [comment]
Someone reached me a few days ago at my email address to update it. Wasn't it you? If you would like to be faster, please create a pull request.

**Comment by elgatov** [comment]
> Someone reached me a few days ago at my email address to update it. Wasn't it you? If you would like to be faster, please create a pull request.

Hi!

No it wasn't me, I did not know you were already noticed about this. I can close the issue if you want, then.

**Comment by dynasticorpheus** [comment]
See #19180
