### ISSUE TITLE
pciutils: compilation error

### ISSUE THREAD

**Issue by herve-elter** [openwrt/packages#19227]
Maintainer: @lucize
Environment: EspressoBin-NonECC, mvebu/cortexa53, OpenWrt 21.03

Description:

Since recently update, while running build, I noticed that the package pciutils-3.8.0 can not be compiled

Errors:
{standard input}:7: Error: multiple versions [`pci_filter_init@@LIBPCI_3.8'|`pci_filter_init@LIBPCI_3.3'] for symbol `pci_filter_init_v38'
{standard input}:9: Error: multiple versions [`pci_filter_parse_slot@@LIBPCI_3.8'|`pci_filter_parse_slot@LIBPCI_3.3'] for symbol `pci_filter_parse_slot_v38'
{standard input}:11: Error: multiple versions [`pci_filter_parse_id@@LIBPCI_3.8'|`pci_filter_parse_id@LIBPCI_3.3'] for symbol `pci_filter_parse_id_v38'
{standard input}:13: Error: multiple versions [`pci_filter_match@@LIBPCI_3.8'|`pci_filter_match@LIBPCI_3.3'] for symbol `pci_filter_match_v38'

After commenting the following lines in filter.c  ... it builds and works.
SYMBOL_VERSION(pci_filter_init_v38, pci_filter_init@LIBPCI_3.3);
SYMBOL_VERSION(pci_filter_parse_slot_v38, pci_filter_parse_slot@LIBPCI_3.3);
SYMBOL_VERSION(pci_filter_parse_id_v38, pci_filter_parse_id@LIBPCI_3.3);
SYMBOL_VERSION(pci_filter_match_v38, pci_filter_match@LIBPCI_3.3);

Toolchain toolchain-aarch64_cortex-a53_gcc-8.4.0_musl (platform default)

Regards,

**Comment by BKPepe** [comment]
Fixed by https://github.com/openwrt/packages/pull/19215
