### ISSUE TITLE
libpci: no where to be found in official repo

### ISSUE THREAD

**Issue by sigeryang** [openwrt/packages#19249]
Recently I was trying to customize using image builder (21.02.3). It could install "dnsdist" several days ago but it is now broken.

```
 * pkg_hash_check_unresolved: cannot find dependency libpci for libnetsnmp
 * pkg_hash_fetch_best_installation_candidate: Packages for libnetsnmp found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for dnsdist:
 *      libpci
```

`libpci` is nowhere to be found in [packages index (21.02.3)](https://archive.openwrt.org/releases/21.02.3/packages/mipsel_24kc/packages/Packages), and it still serves as dependencies of many packages.
Also not found in 21.02.2 index but the package file exists: https://archive.openwrt.org/releases/21.02.2/packages/mipsel_24kc/packages/libpci_3.7.0-2_mipsel_24kc.ipk

Wondering what happened to this.

**Comment by BKPepe** [comment]
Related to https://github.com/openwrt/packages/issues/19227, you willl need to wait until new build for ``mipsel_24kc`` will show up. I see that https://downloads.openwrt.org/releases/21.02.3/packages/mips_24kc/packages/ it was compiled 2 days ago.  You can check it on faillogs: https://downloads.openwrt.org/releases/faillogs-21.02/mipsel_24kc/packages/pciutils/compile.txt
