### ISSUE TITLE
uacme: Missing dependency on `libev` (for some configurations) in 22.03.

### ISSUE THREAD

**Issue by dreirund** [openwrt/packages#19260]
### Maintainer:

@lucize

### Environment:

* OpenWrt git branch `openwrt-22.03`, latest `git pull && ./scripts/feeds update -a && ./scripts/feeds install -a` on 2022-08-25, ca. 08:00 UTC
* Configuration: [&rarr;&hairsp;`.config`](http://ix.io/48CY)
* `grep -i uacme .config | grep -v 'luci-i18n'`:  
  ```
  CONFIG_PACKAGE_uacme=m
  CONFIG_PACKAGE_uacme-ualpn=m
  ```
* `grep -i libev .config | grep -v 'luci-i18n'`:  
  ```
  CONFIG_PACKAGE_libunbound_libevent=y
  # CONFIG_GETDNS_BUILD_LIBEVENT2 is not set
  CONFIG_PACKAGE_libev=m
  CONFIG_PACKAGE_libevdev=y
  CONFIG_PACKAGE_libevent2=y
  CONFIG_PACKAGE_libevent2-core=y
  # CONFIG_PACKAGE_libevent2-extra is not set
  # CONFIG_PACKAGE_libevent2-openssl is not set
  CONFIG_PACKAGE_libevent2-pthreads=m
  CONFIG_PACKAGE_luci-app-shadowsocks-libev=m
  CONFIG_PACKAGE_shadowsocks-libev-config=m
  CONFIG_PACKAGE_shadowsocks-libev-ss-local=m
  CONFIG_PACKAGE_shadowsocks-libev-ss-redir=m
  CONFIG_PACKAGE_shadowsocks-libev-ss-rules=m
  CONFIG_PACKAGE_shadowsocks-libev-ss-server=m
  CONFIG_PACKAGE_shadowsocks-libev-ss-tunnel=m
  ```

### Description:

In the above configuration, currently `uacme` fails to build due to missing dependencies in the actual `openwrt-22.03` branch.

Output of `make -j1 V=sc package/feeds/packages/uacme/compile`:  
```
[...]
Package uacme-ualpn is missing dependencies for the following libraries:
libev.so.4
[...]
```

[&rarr;&hairsp;Complete second-run `make -j1 V=sc package/feeds/packages/uacme/compile` output](http://ix.io/48Fu).

So it seems that some dependencies are not defined in the `Makefile`.

Manually adding ` +libev` to the `DEPENDS:=`-line in the `Package/uacme` section in `package/feeds/packages/uacme/Makefile` does mitigate the problem:

```
--- Makefile.org	2022-08-26 10:45:12.669953214 +0200
+++ Makefile	2022-08-26 11:02:03.149921606 +0200
@@ -45,9 +45,9 @@
 define Package/uacme
   $(call Package/uacme/Default)
   SECTION:=net
   CATEGORY:=Network
-  DEPENDS:=+libcurl +LIBCURL_WOLFSSL:libmbedtls
+  DEPENDS:=+libcurl +LIBCURL_WOLFSSL:libmbedtls +libev
   TITLE:=lightweight client for ACMEv2
   Menu:=1
 endef

```

I am not sure if `libev` should be a general dependency or only if some other config options are set. @lucize/others, you know the package better than me, please check and if appropriate add a conditional dependency on `libopenldap`.

Regards!

**Comment by neheb** [comment]
Fixed: https://github.com/openwrt/packages/commit/dfaa4bad501df8ebc116f26a3681a920b1e1df0f
