### ISSUE TITLE
mwan3: Default balanced policy is 60%/40% not 50%/50%

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/packages#19343]
Maintainer: @feckert
Environment: N/A

Description:

The default mwan3 configuration with it's member and policy configuration provides a balanced policy, this policy isn't technically equally balanced instead it is calculated by mwan3 routing as 60% and 40%, rather than equal routing as 50%/50%.

The metrics and weight need to be the same. A 50% balanced would be require member policies of the same metric and weight value. Currently the weight value being one different means the connection will not ever be equal

A 50/50 balanced policy

```sh
config policy 'balanced'
	list use_member 'wan_m1_w3'
	list use_member 'wanb_m1_w3'
	list use_member 'wan6_m1_w3'
	list use_member 'wanb6_m1_w3'
```

Whether or not this is really a problem given it has been like this for a long time, but given the policy is labelled as "balanced" I'd potentially suggest it should be equally balanced?

**Comment by feckert** [comment]
@jamesmacwhite thanks for reporting.
Fixed with commit https://github.com/openwrt/packages/commit/0ed8450d2fdb39df5b6ea2e587e6554cadcfd0dc

**Comment by jamesmacwhite** [comment]
Thank you!
