### ISSUE TITLE
SIGILL when running node.js (MIPS, AR9331)

### ISSUE THREAD

**Issue by schmist** [openwrt/packages#1937]
Running node returns `Illegal Instruction`. Enabling FPU emulation resolves the issue. It seems that the V8 version for the packaged node (0.12.7) does not support soft floats anymore.

**Comment by yaseenox** [comment]
I have the same problem, did you figure it out ?

**Comment by yaseenox** [comment]
How can I enable FPU emulation ?

**Comment by karlp** [comment]
Duplicate of https://github.com/openwrt/packages/issues/2633

**Comment by hnyman** [comment]
closing as duplicate
