### ISSUE TITLE
ModemManager for x86_64 Images not found in packages 22.03.0

### ISSUE THREAD

**Issue by m7mdcc** [openwrt/packages#19397]
Hello , when i upgrdae to [22.03.0](https://downloads.openwrt.org/releases/22.03.0/) there is no modemmanager in repo 

https://downloads.openwrt.org/releases/22.03.0/packages/x86_64/packages/

but its there in 21.02.2 

https://downloads.openwrt.org/releases/21.02.2/packages/x86_64/packages/

**Comment by feckert** [comment]
The problem no longer exists.
Package was build again by the buildsystem https://downloads.openwrt.org/releases/22.03.0/packages/x86_64/packages/modemmanager_1.18.6-2_x86_64.ipk
