### ISSUE TITLE
python-psycopg2 build (install) error - probably latest changes/upgrade python-setuptools

### ISSUE THREAD

**Issue by build000** [openwrt/packages#1945]
make[3]: Entering directory '/home/openwrt/trunk/feeds/packages/lang/python-psycopg2'
install -d -m0755 /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages
(	export PYTHONPATH="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/python2.7:/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11//usr/lib/python2.7/site-packages:/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages"; export PYTHONOPTIMIZE=""; export PYTHONDONTWRITEBYTECODE=1; export _python_sysroot="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11"; export _python_prefix="/usr"; export _python_exec_prefix="/usr";  cd /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/.; CC="mips-openwrt-linux-musl-gcc" CCSHARED="mips-openwrt-linux-musl-gcc -fpic" CXX="mips-openwrt-linux-musl-g++" LD="mips-openwrt-linux-musl-gcc" LDSHARED="mips-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mno-mips16 -mno-interlink-mips16" CPPFLAGS="-I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include/python2.7" LDFLAGS="-L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -lpython2.7" _PYTHON_HOST_PLATFORM=linux2 __PYVENV_LAUNCHER__="/usr/bin/python2.7"   /home/openwrt/trunk/staging_dir/host/bin/python2  ./setup.py build_py ; )
running build_py
warning: build_py: byte-compiling is disabled, skipping.

find /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install -name "*\.pyc" -o -name "*\.pyo" | xargs rm -f
install -d -m0755 /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages
(	export PYTHONPATH="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/python2.7:/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11//usr/lib/python2.7/site-packages:/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages"; export PYTHONOPTIMIZE=""; export PYTHONDONTWRITEBYTECODE=1; export _python_sysroot="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11"; export _python_prefix="/usr"; export _python_exec_prefix="/usr";  cd /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/; CC="mips-openwrt-linux-musl-gcc" CCSHARED="mips-openwrt-linux-musl-gcc -fpic" CXX="mips-openwrt-linux-musl-g++" LD="mips-openwrt-linux-musl-gcc" LDSHARED="mips-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mno-mips16 -mno-interlink-mips16" CPPFLAGS="-I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include/python2.7" LDFLAGS="-L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -lpython2.7" _PYTHON_HOST_PLATFORM=linux2 __PYVENV_LAUNCHER__="/usr/bin/python2.7"   /home/openwrt/trunk/staging_dir/host/bin/python2  ./setup.py build_ext --pg-config="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/bin/pg_config" ; )
running build_ext
find /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install -name "*\.pyc" -o -name "*\.pyo" | xargs rm -f
install -d -m0755 /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages
(	export PYTHONPATH="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/python2.7:/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11//usr/lib/python2.7/site-packages:/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install//usr/lib/python2.7/site-packages"; export PYTHONOPTIMIZE=""; export PYTHONDONTWRITEBYTECODE=1; export _python_sysroot="/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11"; export _python_prefix="/usr"; export _python_exec_prefix="/usr";  cd /home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/.; CC="mips-openwrt-linux-musl-gcc" CCSHARED="mips-openwrt-linux-musl-gcc -fpic" CXX="mips-openwrt-linux-musl-g++" LD="mips-openwrt-linux-musl-gcc" LDSHARED="mips-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mno-mips16 -mno-interlink-mips16" CPPFLAGS="-I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include -I/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include/python2.7" LDFLAGS="-L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/home/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -lpython2.7" _PYTHON_HOST_PLATFORM=linux2 __PYVENV_LAUNCHER__="/usr/bin/python2.7"   /home/openwrt/trunk/staging_dir/host/bin/python2  ./setup.py install --prefix=/usr --root=/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/ipkg-install ; )
running install
running build
running build_py
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.
Makefile:55: recipe for target '/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/.built' failed
make[3]: *** [/home/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/psycopg2-2.6.1/.built] Error 1
make[3]: Leaving directory '/home/openwrt/trunk/feeds/packages/lang/python-psycopg2'
package/Makefile:191: recipe for target 'package/feeds/packages/python-psycopg2/compile' failed
make[2]: *** [package/feeds/packages/python-psycopg2/compile] Error 2
make[2]: Leaving directory '/home/openwrt/trunk'
package/Makefile:188: recipe for target '/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/trunk'
/home/openwrt/trunk/include/toplevel.mk:177: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2

**Comment by hnyman** [comment]
Reopened. 
Discussion at #2061
