### ISSUE TITLE
curl: update to 7.85.0 breaks build due to typo in github source url

### ISSUE THREAD

**Issue by spapadim** [openwrt/packages#19456]
Maintainer: @stangri @BKPepe
Environment: ath79-generic-tplink_archer-c7-v2 / master

Description:
Commit 03a32717bc15d8dd0c99e200dd64ae0bbd558c35 which, while updating version, also adds github to package source URLs 
has that URL wrong.

Specifically, since github replaces `.` with `_` in the URL (e.g., `7.85.0` to `7_85_0`), the `Makefile` attempts to do this in the definition of `PKG_SOURCE_URL`, but using `patsubst` (in shorthand form) which only works for string suffix substitutions (not all occurences of match). Thus, during build, `curl` call in `download.pl` fails with a 404 error. Not idea why it does not proceed with URLs further down the list of sources. However, I believe line 15 should be changed
```diff
-PKG_SOURCE_URL:=https://github.com/curl/curl/releases/download/curl-$(PKG_VERSION:.=_)/ \
+PKG_SOURCE_URL:=https://github.com/curl/curl/releases/download/curl-$(subst .,_,$(PKG_VERSION))/ \
```

PS (FWIW). Also, oddly, I built an image for a different arch just two days ago (again from `master` at time) but *that* build didn't fail. Double-checked, my config there also includes `curl` and it's Makefile was also updated (i.e., I didn't forget to update feeds :). Not sure why *that* build did not fail, the only reason I can think is that it wasn't a clean build (maybe I had tarball already in `dl`s---although I doubt it, since last time I touched that build was mid-Aug or so)

**Comment by stangri** [comment]
@spapadim thank you for the report/patch!
