### ISSUE TITLE
DDNS script service wont auto start even though DDNS service itself starts

### ISSUE THREAD

**Issue by alirz1** [openwrt/packages#19524]
DDNS package version:2.8.2-12
Router info:

Hostname | GL-AXT1800
Model | GL Technologies, Inc. AXT1800
Architecture | ARMv7 Processor rev 4 (v7l)
Target Platform | ipq807x/ipq60xx
Firmware Version | OpenWrt 21.02-SNAPSHOT r16399+157-c67509efd7 / LuCI openwrt-22.03 branch git-21.284.67084-e4d24f0
Kernel Version | 4.4.60

```
While the DDNS service itself auto starts, the script i've configured wont auto start. If i start it manually, i first get a XHR timeout but after sometime the script start.
As a workarounf i've found that if i stop the DDNS service altogether from auto starting, i can put the following in the local startup and that way my script starts fine. 
As per https://forum.openwrt.org/t/ddns-not-starting-xhr-request-time-out/94888
```

**Comment by feckert** [comment]
Related issue on the forum is marked is resolved
