### ISSUE TITLE
php7-mod-hash is now an Unknown package

### ISSUE THREAD

**Issue by Action-Red** [openwrt/packages#19602]
Maintainer: @\<Michael Heimpold>
Environment: (OpenWrt 21.02.1)

Description:

```opkg install php7-mod-hash```
results in:
```Unknown package 'php7-mod-hash'.
   Collected errors:
    * opkg_install_cmd: Cannot install package php7-mod-hash.```

**Comment by paper42** [comment]
That is correct, this commit removed it: 0f10c8c84135eb222b26f0c6dfe561c0b4cefb94

> php7-mod-hash: this extension is now part of the core binary and cannot be built as an extension module anymore
