### ISSUE TITLE
adblock:  In report there is no way to change top value from 10 to bigger number

### ISSUE THREAD

**Issue by anasoid** [openwrt/packages#19622]
Maintainer: @dibdot 
Environment: 22.03

Description:
This is not an issues it's an improvement.

In report ad block there is no way to change statistic top from 10 to bigger value (may be 50 as maximum will be  ).

In statistics i found always known domain as only 10 are displayed, may be with bigger value it will be helpfull to see other domain name to be blocked.

**Comment by dibdot** [comment]
@anasoid good idea, the backend stuff is already implemented with the linked PR - the LuCI changes will follow. Thanks!

**Comment by anasoid** [comment]
@dibdot many thanks
