### ISSUE TITLE
Squid: Inconsistent build

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#1964]
Trying to build package squid without support for SSL, to save some space, after editing the Makefile, fails:

install -m0755 /etc/openwrt_Xia/build_dir/target-mipsel_24kec+dsp_musl-1.1.11/squid-3.5.9/ipkg-install/usr/lib/squid/ssl_crtd /etc/openwrt_Xia/build_ dir/target-mipsel_24kec+dsp_musl-1.1.11/squid-3.5.9/ipkg-ramips_24kec/squid/usr/lib/squid
install: cannot stat '/etc/openwrt_Xia/build_dir/target-mipsel_24kec+dsp_musl-1.1.11/squid-3.5.9/ipkg-install/usr/lib/squid/ssl_crtd': No such file o r directory
make[3]: * etc/openwrt_Xia/bin/ramips/packages/packages/squid_3.5.9-1_ramips_24kec.ipk Error 1

Excerpt from Makefile:
CONFIGURE_ARGS += \

    --config-cache \
    --datadir=/usr/share/squid \
    --libexecdir=/usr/lib/squid \
    --sysconfdir=/etc/squid \
    --enable-shared \
    --disable-static \
    --enable-icmp \
    --enable-delay-pools \
    --enable-icap-client \
    --enable-kill-parent-hack \
    --disable-snmp \
    --enable-cache-digests \
    --enable-linux-netfilter \
    --disable-unlinkd \
    --enable-x-accelerator-vary \
    --disable-translation \
    --disable-auto-locale \
    --with-dl \
    --with-pthreads \
    --without-expat \
    --without-libxml2 \
    --without-gnutls \
    --without-nettle \
    --enable-epoll \
    --with-maxfd=4096 \
    --disable-external-acl-helpers \
    --disable-auth-negotiate \
    --disable-auth-ntlm \
    --disable-auth-digest \
    --disable-auth-basic \
    --disable-arch-native \
    --with-krb5-config=no \
    --without-libcap \
    --without-netfilter-conntrack

It might be a good idea, to create a special option in "Make menuconfig" for squid to be built without SSL.

**Comment by hnyman** [comment]
> It might be a good idea, to create a special option in "Make menuconfig" for squid to be built without SSL.

Feel free to author such a variant and then submit a pull request...

But your own error is due to the fact that you have edited Makefile to disable ssl components, but you have not removed the one ssl-related line from Makefile's installation section. And that line naturally fails due to the missing binary.

    $(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/lib/squid/ssl_crtd $(1)/usr/lib/squid
