### ISSUE TITLE
shadowsocks-libev: "No file descriptors available" occasionally

### ISSUE THREAD

**Issue by ShadowOfTheDay** [openwrt/packages#19719]
Maintainer: @yousong
Environment: x86-64, OpenWrt 21.02, shadowsocks-libev 3.3.5

Description:
When shadowsocks-libev is run for several days, sometimes the system log will be flooded by thousands of such error:
```
Wed Oct 26 20:55:05 2022 daemon.err /usr/bin/ss-tunnel[21674]: accept: No file descriptors available
```
The network will be stuck for a minute or so with very high CPU usage. 

With some google search, it seems to be caused by the system limit of open files, and could be solved by increasing the `nofile` limit. 

This was reported for similar packages, for example, see #18701 

I was wondering if this could be solved by adding something like `procd_set_param limits nofile="100000 100000"` in the init script, similar to #18705

**Comment by ShadowOfTheDay** [comment]
I just want to provide some updated information. I haven't encountered the error of "No file descriptors available" for two months after adding `procd_set_param limits nofile="100000 100000"` in the init script. So for anyone who have the same problem, you may want to try it by yourself.

**Comment by villivateur** [comment]
> I just want to provide some updated information. I haven't encountered the error of "No file descriptors available" for two months after adding `procd_set_param limits nofile="100000 100000"` in the init script. So for anyone who have the same problem, you may want to try it by yourself.

Thank you.

And for anyone who wonder where to add this config, it is in file `/etc/init.d/shadowsocks-libev`, function `ss_xxx()`, between line `procd_open_instance` and `procd_close_instance`.
