### ISSUE TITLE
Zoneinfo-all package is missing

### ISSUE THREAD

**Issue by BKPepe** [openwrt/packages#19734]
Maintainer: @Wedmer
Environment: I noticed that it happens in OpenWrt 21.02 release, but it is also present in OpenWrt master branch, thus OpenWrt 22.03 is affected, too.

Description:

While compiling zoneinfo package, I noticed that there is such warning:
```
Makefile:260: WARNING: skipping zoneinfo-all -- package has no install section
```

**Comment by Wedmer** [comment]
This package is a meta package and wasn't added by me. I'll redo it to work without warnings.

**Comment by BKPepe** [comment]
Oh, I see! It was added in this commit https://github.com/openwrt/packages/commit/6787f5c6a0e5eff50a41996a5b63941c8cd2aad7 by @rmilecki
