### ISSUE TITLE
atlas-probe 2.4.1-1/atlas-sw-probe 5040-1: path /home/atlas used in busybox and scripts but does not exists

### ISSUE THREAD

**Issue by KsmoinO** [openwrt/packages#19740]
Maintainer: @ja-pa 
Environment: ath79, dlink_dir-842-c3, 22.03.2

Description:

/usr/libexec/atlas-probe/bin/busybox, /usr/libexec/atlas-probe-scripts/bin/ATLAS and /usr/libexec/atlas-probe-scripts/bin/common-pre.sh use /home/atlas but it does not exists

A workaround could be to create a symlink (/home/atlas -> /var/ripe_atlas_probe/)

Remark : Are the atlas user and group necessary?

**Comment by Ansuel** [comment]
internally that path is replaced with the correct one....

**Comment by KsmoinO** [comment]
not in /usr/libexec/atlas-probe-scripts/bin/ATLAS lines 138, 142 (and maybe 38)

**Comment by Ansuel** [comment]
again from what i notice they modified cron and their custom eperd to replace that path with the base dir and stuff is correctly passed and sent with no error

**Comment by KsmoinO** [comment]
Oh, sorry. You're right, removing the symlink does not seems to impact stuff
