### ISSUE TITLE
XRay-Core min flash storage

### ISSUE THREAD

**Issue by hawshemi** [openwrt/packages#19766]
I have an archer c20v5 which has 8MB flash storage.
When I install the latest OpenWRT, it says it has 1.8 MB flash storage. Thus, I cannot install X-ray or V2ray.
How much space is good enough for flash storage on the router for these packages?
Is 16MB enough? or more is needed?

**Comment by 1715173329** [comment]
> Is 16MB enough? or more is needed?

At least 32 MB, 128 MB is recommended.

**Comment by 1715173329** [comment]
Closed due to stale.
