### ISSUE TITLE
mwan3: "use" runs a subprocess instead of doing "exec"

### ISSUE THREAD

**Issue by patrakov** [openwrt/packages#20001]
Maintainer:  @feckert @aaronjg
Environment: OpenWRT 22.03.2 on aarch64, Linksys E8450 (UBI)

Description:

The end of the `use()` function looks like this:

```
	echo "Running '$*' with DEVICE=$device SRCIP=$src_ip FWMARK=$MMX_DEFAULT FAMILY=$family"
	# shellcheck disable=SC2048
	FAMILY=$family DEVICE=$device SRCIP=$src_ip FWMARK=$MMX_DEFAULT LD_PRELOAD=/lib/mwan3/libwrap_mwan3_sockopt.so.1.0 $*
```

Note that there is no `exec`. This means that the command runs as a subprocess, and `mwan3` does not pass any signals to it. This is bad, if `mwan3 use lte` is used as a wrapper for some program that runs under procd - the `TERM` signal is then delivered to mwan3, but not to the process that constitutes the service's payload.

Also `$*` means that there is no way to embed arguments with a space. Please reconsider your stance about `SC2048`.

**Comment by feckert** [comment]
@patrakov Please open a pullrequest to fix this issue.
