### ISSUE TITLE
atlas-probe: version 2.4.1-2 "do_page_fault(): sending SIGSEGV to perd for invalid read access from XXXXXXXX"

### ISSUE THREAD

**Issue by KsmoinO** [openwrt/packages#20008]
Maintainer: @ja-pa 
Environment: ath79, dlink_dir-842-c3, 22.03.2

Description:
About once a day and up to 5 times a day, perd is killed with following kernel message "do_page_fault(): sending SIGSEGV to perd for invalid read access from XXXXXXXX"

As workaround I schedule this script every minutes to restart atlas each time perd is killed :
```
#!/bin/sh
pgrep /usr/libexec/atlas-probe/bin/perd
if [ $? -ne 0 ] ; then
  /etc/init.d/atlas restart
fi
```

**Comment by Ansuel** [comment]
This should be fixed in later release... pls upgrade

**Comment by BKPepe** [comment]
Wasn't this related to https://github.com/openwrt/packages/issues/19739 or it happens one more time?

**Comment by KsmoinO** [comment]
> This should be fixed in later release... pls upgrade

I'm already at latest atlas-probe version (2.4.1-2) available on latest openwrt stable release (22.03.2)

> Wasn't this related to #19739 or it happens one more time?

No this time, it's not 'eperd' but 'perd' which is killed

**Comment by Ansuel** [comment]
@BKPepe both were fixed so this sounds strange to me

**Comment by KsmoinO** [comment]
I do not use atlas on this device anymore and do not have this issue on the new one
