### ISSUE TITLE
 luci-app-pbx:  Missing dependency asterisk18-chan-gtalk

### ISSUE THREAD

**Issue by hari-rangarajan** [openwrt/packages#2004]
Installing luci-app-pbx (git-15.248.30277-3836b45-1) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/packages/luci/luci-app-pbx_git-15.248.30277-3836b45-1_all.ipk.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-pbx:
 * 	asterisk18-chan-gtalk * 
 * opkg_install_cmd: Cannot install package luci-app-pbx.

**Comment by hnyman** [comment]
The Luci app depended on an outdated asterisk version. I marked the Luci app broken in trunk, until it is refreshed to match currently available Asterisk versions.
