### ISSUE TITLE
wireguard: WireGuard shows `Error: Network device is not present` on LuCi

### ISSUE THREAD

**Issue by marek22k** [openwrt/packages#20044]
Maintainer: Jason A. Donenfeld <Jason@zx2c4.com> / Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>
@zx2c4 @ldir-EDB0 @nbd168 @hauke @diizzyy @notgood 

Environment: MediaTek MT7628AN ver:1 eco:2 / GL-MT300N-V2 / OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.339.35241-4ca7a8d

Description:

Hello,

I want to build a WireGuard tunnel over the Yggdrasil overlay network. The Yggdrasil network is provided by the package `yggdrasil`. Yggdrasil successfully establishes its connection to the network over a WiFi Adhoc network. My endpoint is `218:4feb:a509:9db2:2b34:6e7e:e071:5dee`. I have a route to this endpoint and I can ping it. The WireGuard tunnel works when the device is connected to the Internet via WAN. However, if I disconnect the WAN, the message `Error: Network device is not present` appears and it does not even try to establish the WG tunnel, although it is possible because the endpoint is reachable.

My expected behavior is that OpenWrt always tries to reach the endpoint if there is a route to it in the kernel routing table.

```
# ip r g 218:4feb:a509:9db2:2b34:6e7e:e071:5dee
218:4feb:a509:9db2:2b34:6e7e:e071:5dee from :: dev ygg0  src 21e:295a:a561:adb1:f834:9e20:1757:183a  metric 256 
# ping 218:4feb:a509:9db2:2b34:6e7e:e071:5dee
PING 218:4feb:a509:9db2:2b34:6e7e:e071:5dee (218:4feb:a509:9db2:2b34:6e7e:e071:5dee): 56 data bytes
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=0 ttl=64 time=1347.156 ms
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=1 ttl=64 time=384.689 ms
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=2 ttl=64 time=72.068 ms
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=3 ttl=64 time=69.410 ms
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=4 ttl=64 time=69.935 ms
64 bytes from 218:4feb:a509:9db2:2b34:6e7e:e071:5dee: seq=5 ttl=64 time=69.803 ms
^C
--- 218:4feb:a509:9db2:2b34:6e7e:e071:5dee ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 69.410/335.510/1347.156 ms
```
The command `wg` does not output anything.

![Screenshot at 2022-12-08 23-34-00](https://user-images.githubusercontent.com/46723399/206581928-61a39433-ca7b-49ff-9da5-c5922d8bcd49.png)
![Screenshot at 2022-12-08 23-36-36](https://user-images.githubusercontent.com/46723399/206582247-c0c65ed8-3afe-47fd-a34a-c64cab8faec3.png)
![Screenshot at 2022-12-08 23-37-10](https://user-images.githubusercontent.com/46723399/206582324-d61163e3-0588-4a28-a2e3-c2024ac2e387.png)

```
config wireguard_crxn_p2pnodeygg
	list allowed_ips '::/0'
	option route_allowed_ips '1'
	option endpoint_host '218:4feb:a509:9db2:2b34:6e7e:e071:5dee'
	option endpoint_port 'XXXXX'
	option persistent_keepalive '20'
	option public_key 'XXXXXXXXXXXXXXXXXXXXXXXXXXx'
	option preshared_key 'XXXXXXXXXXXXXXXXXXXXXXXXXXx'
```
```
config interface 'yggdrasil'
	option device 'ygg0'
	option proto 'none'
```

**Comment by diizzyy** [comment]
Closing as it's not a package issue and wireguard maintained in this repo, you're probably better off trying IRC or the forums.

**Comment by marek22k** [comment]
This is OpenWrt specific and not WireGuard specific.
Since `wg` did not output anything, no configuration was ever delivered to WireGuard. Therefore WireGuard did not even try to establish a connection. If OpenWrt does not pass the configuration to WireGuard, this is a bug in OpenWrt and not in WireGuard.
Furthermore, the error message "Network device not presend" is OpenWrt specific and not WireGuard specific.
@diizzyy So I would like to ask you to reopen this issue.

**Comment by marek22k** [comment]
This is OpenWrt specific and not WireGuard specific.
Since `wg` did not output anything, no configuration was ever delivered to WireGuard. Therefore WireGuard did not even try to establish a connection. If OpenWrt does not pass the configuration to WireGuard, this is a bug in OpenWrt and not in WireGuard.
Furthermore, the error message "Network device not presend" is [OpenWrt specific](https://github.com/openwrt/luci/blob/master/modules/luci-base/htdocs/luci-static/resources/network.js#L15) and not WireGuard specific.
@diizzyy So I would like to ask you to reopen this issue.

**Comment by diizzyy** [comment]
It's the wrong repository

**Comment by marek22k** [comment]
Which one is the right one?
