### ISSUE TITLE
adblock canot manage to whitelist twitter links: t.co 

### ISSUE THREAD

**Issue by daliagachc** [openwrt/packages#20096]
Hi, 
after enabling adblock with defaults settings i cannot follow links from twitter (t.co). I have tried to whitelist them by including 
https://t.co/
t.co/
https://t.co
t.co

in the whitelist entry but i still cannot follow twitter links

**Comment by dibdot** [comment]
Please use only domain names ("t.co") in your withelist and than reload adblock to make use of your changes. It works here as expected:
```
before whitelisting:
nslookup t.co 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find t.co: NXDOMAIN

after whitelisting:
nslookup t.co 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	t.co
Address: 104.244.42.133
Name:	t.co
Address: 104.244.42.69
Name:	t.co
Address: 104.244.42.5
Name:	t.co
Address: 104.244.42.197


```
