### ISSUE TITLE
AdguardTeam: latest version by git or 107.20 to resolve a bug

### ISSUE THREAD

**Issue by Concubine** [openwrt/packages#20142]
Please make sure that the issue subject starts with 

Maintainer: @dobo90
https://github.com/AdguardTeam/AdGuardHome
Environment: not sure, I use : 21.02.5 r16688-fa9a932fdb

Description:
Based on [https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268444 4](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268444)

There is a known issue with adguardhome which has been rectified in later verison, current supported (https://openwrt.org/packages/pkgdata/adguardhome) version 107.6 has this flaw and I am unable to start AdGuard on my openwrt install:

details:
|Model|Linksys WRT3200ACM|
|Architecture|ARMv7 Processor rev 1 (v7l)|
|Target Platform|mvebu/cortexa9|
|Firmware Version|OpenWrt 21.02.5 r16688-fa9a932fdb / LuCI openwrt-21.02 branch git-22.245.77575-63bfee6|

Please update AdGuardHome to latest 107.20 to resolve this issue

**Comment by 1715173329** [comment]
can you try if #20168 works?

**Comment by Concubine** [comment]
Currently its working with what I set it up by manually installing with curl which is 107.21 while I didn't check with the opkg official it is working with that version; if you merged it to the official openwrt package I think we can close this one.
