### ISSUE TITLE
mwan3_2.0-0: ipv6 dependencies not checked and provide a way to disable ipv6 support

### ISSUE THREAD

**Issue by braveheartleo** [openwrt/packages#2020]
I noticed that mwan3 was upgraded to `2.0-0`. Unfortunately, this version bump did not check for ipv6 dependencies, thus when I upgraded mwan3 from `1.6-3` in my custom Designated Driver build where ipv6 support is disabled and packages not included, mwan3 failed to start.

The package needs to be modified so that ipv6 dependencies are checked before installation.

I would like to request that mwan3 provide workarounds to turn off ipv6 for non-ipv6 setups.

**Comment by Adze1502** [comment]
Thank you for noticing, will get back soon with update

**Comment by diizzyy** [comment]
@Adze1502 
Fixed?

**Comment by feckert** [comment]
@hnyman i think we could close this issue.
Its very old.

**Comment by feckert** [comment]
@hnyman thanks
