### ISSUE TITLE
travelmate: DHCP renew triggers reload/restart

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#20207]
Environment: ath79 22.03.2

Description:
When Travelmate's interface renews it's DHCP lease, Travelmate seems to trigger some very heavy-handed restart/reload processes.  I.e.
18:03:42 netifd trm_wwan (7978): udhcpc: sending renew to server 10.75.22.247
18:03:43 netifd trm_wwan (7978): udhcpc: lease of 10.75.22.210 obtained from 10.75.22.247, lease time 21599
18:03:44 firewall Reloading firewall due to ifupdate of trm_wwan (wlan1)
18:03:50 adblock-4.1.5 adblock instance started ::: action: start, priority: 0, pid: 19817
18:03:57 unbound [3547:0] info: service stopped (unbound 1.17.0).
18:03:58 unbound [3547:0] info: server stats for thread 0: 15164 queries, 10807 answers from cache, 4357 recursions, 0 prefetch, 0 rejected by ip ratelimiting
18:03:58 unbound [3547:0] info: server stats for thread 0: requestlist max 42 avg 1.5669 exceeded 0 jostled 0
18:03:58 unbound [3547:0] info: average recursion processing time 0.122104 sec
18:03:58 unbound [3547:0] info: histogram of recursion processing times
18:03:58 unbound [3547:0] info: [25%]=0.0365392 median[50%]=0.0654167 [75%]=0.142319
18:03:58 unbound [3547:0] info: lower(secs) upper(secs) recursions
18:03:58 unbound [3547:0] info:    0.000000    0.000001 428
18:03:58 unbound [3547:0] info:    0.000512    0.001024 1
18:03:58 unbound [3547:0] info:    0.002048    0.004096 89
18:03:58 unbound [3547:0] info:    0.004096    0.008192 42
18:03:58 unbound [3547:0] info:    0.008192    0.016384 5
18:03:58 unbound [3547:0] info:    0.016384    0.032768 382
18:03:58 unbound [3547:0] info:    0.032768    0.065536 1236
18:03:58 unbound [3547:0] info:    0.065536    0.131072 1027
18:03:58 unbound [3547:0] info:    0.131072    0.262144 673
18:03:58 unbound [3547:0] info:    0.262144    0.524288 340
18:03:58 unbound [3547:0] info:    0.524288    1.000000 95
18:03:58 unbound [3547:0] info:    1.000000    2.000000 38
18:03:58 unbound [3547:0] info:    2.000000    4.000000 1
18:04:01 unbound [20168:0] notice: init module 0: iterator
18:04:01 unbound [20168:0] info: start of service (unbound 1.17.0).
18:04:38 unbound [20168:0] info: service stopped (unbound 1.17.0).
18:04:38 unbound [20168:0] info: server stats for thread 0: 26 queries, 12 answers from cache, 14 recursions, 0 prefetch, 0 rejected by ip ratelimiting
18:04:38 unbound [20168:0] info: server stats for thread 0: requestlist max 6 avg 1.71429 exceeded 0 jostled 0
18:04:38 unbound [20168:0] info: average recursion processing time 1.122707 sec
18:04:38 unbound [20168:0] info: histogram of recursion processing times
18:04:38 unbound [20168:0] info: [25%]=0.057344 median[50%]=0.262144 [75%]=2.5
18:04:38 unbound [20168:0] info: lower(secs) upper(secs) recursions
18:04:38 unbound [20168:0] info:    0.004096    0.008192 1
18:04:38 unbound [20168:0] info:    0.016384    0.032768 1
18:04:38 unbound [20168:0] info:    0.032768    0.065536 2
18:04:38 unbound [20168:0] info:    0.065536    0.131072 1
18:04:38 unbound [20168:0] info:    0.131072    0.262144 2
18:04:38 unbound [20168:0] info:    0.262144    0.524288 2
18:04:38 unbound [20168:0] info:    0.524288    1.000000 1
18:04:38 unbound [20168:0] info:    2.000000    4.000000 2
18:04:38 unbound [20168:0] info:    4.000000    8.000000 2
18:04:43 unbound [20520:0] notice: init module 0: iterator
18:04:43 unbound [20520:0] info: start of service (unbound 1.17.0).
18:04:48 adblock-4.1.5 blocklist with overall 51467 blocked domains loaded successfully (TP-Link Archer C7 v2, OpenWrt 22.03.2 r19803-9a599fee93)```
```

Renewing a DHCP lease really ought not to throw away the entire cache of a resolver.for example, and it also ought not cause a DNS outage as restarting the resovler will for those with unfortunate timing.

As bad as this on my network where the DHCP lease is lots of hours, I cannot imagine how troublesome this would be on a Starlink network where DHCP leases are only 5 minutes!  And no, 5 minutes is not really a reasonable DHCP lease time, but users have little control of the craziness of their ISPs.

But regardless of reason DHCP lease renewals really should not cause anywhere near this amount of system churn.  They should be practically transparent other than the DHCP client as it indeed is just a keeping of the _status quo_, not effecting any kind of change on the system.

**Comment by dibdot** [comment]
That's the usual ifup interface event. If you don't want any reloads just of unbound/adblock, just remove trm_wwan as a trigger interface.
