### ISSUE TITLE
adguardhome: upgrade to latest version on openwrt 22.03

### ISSUE THREAD

**Issue by fredericve** [openwrt/packages#20211]
Maintainer: @dobo90
Environment: OpenWrt 22.03.1, r19777-2853b6d652

Description:
Similar to #20142 adguardhome fails to start on openwrt 22.03. Can it be updated to at least version 0.107.21 as well?

**Comment by BKPepe** [comment]
Done in https://github.com/openwrt/packages/commit/27db10b96029373dbc910d3bf05b28ef1caf2231
