### ISSUE TITLE
please reconfigure "shadowsocks-libev"

### ISSUE THREAD

**Issue by mzhboy** [openwrt/packages#2026]
@aa65535  please reconfigure `shadowsocks-libev`, we need `ss-local` and `ss-server`.

**Comment by yousong** [comment]
@mzhboy , please consider opening a pull request.  I also made a package of shadowsocks-libev myself and I think it's worth a try.

**Comment by yousong** [comment]
Close this one as it seems that the issue is not going to receive any further responses.  If you are still interested in it, I would suggest contacting directly with the current maintainer.
