### ISSUE TITLE
nmap: ncat proxy mode broken in 7.91, needs update

### ISSUE THREAD

**Issue by ValdikSS** [openwrt/packages#20266]
Maintainer: @rockdrilla, @diizzyy, @nunojpg, @BKPepe 
Environment: all

Description:
ncat utility from nmap package has a bug in 7.90 and 7.91 version which prevent it from working via proxy.
This seem to be fixed in 7.92 and later.
https://github.com/nmap/nmap/issues/2149

Current version in openwrt 22.03.3 — 7.91

**Comment by BKPepe** [comment]
I am not the maintainer, so feel free to submit pull request.

**Comment by rockdrilla** [comment]
Feel free to cherry-pick https://github.com/rockdrilla/fork.openwrt.packages/tree/nmap-7.92.

**Comment by ValdikSS** [comment]
Made another pull request for 22.03

https://github.com/openwrt/packages/pull/21387
