### ISSUE TITLE
vpn-policy-routing: missing in repo since 22.03.3

### ISSUE THREAD

**Issue by ekjf0943vc** [openwrt/packages#20282]
Hi,

the package vpn-policy-routing seems to be unavailable in the repo since the update to openWRT 22.03.3. The expected behavior is for it to be available.

Best

**Comment by stangri** [comment]
Was replaced by `pbr` package.

**Comment by ekjf0943vc** [comment]
I missed that. Thank you!

**Comment by ekjf0943vc** [comment]
Cloose Issue
