### ISSUE TITLE
atlas-sw-probe missing scripts

### ISSUE THREAD

**Issue by ooonea** [openwrt/packages#20338]
Maintainer: @neheb
Environment: arm_cortex-a9_vfpv3-d16, Turris Omnia, Turris OS 6.2.2 (OpenWrt 21.02.05)
Description: Update to version 5080-1, all scripts in the folder /usr/libexec/atlas-probe-scripts/bin/ are missing. The solution was to copy them manually from GitHub.

```
Jan 16 14:43:04 turris ATLAS[15180]: /usr/libexec/atlas-probe-scripts/bin/ATLAS: source: line 23: can't open '/usr/libexec/atlas-probe-scripts/bin/support.lib.sh': No such file or directory
```

**Comment by neheb** [comment]
ping @BKPepe

**Comment by maurice-w** [comment]
Thanks @BKPepe, 5080-2 works fine on x86-64!
