### ISSUE TITLE
uvol: handle integral free sizes in autopart

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#20343]
Maintainer: @dangowrt 
Environment: x86_64, generic, HEAD (0a35d3f992)

Description:

In the case of `sfdisk` returning an integral number of megabytes, the `case` statement will never match. Example:

```
root@pigpen:~# sfdisk -q -F /dev/vda 
 Start     End Sectors  Size
505856 1009667  503812  246M
root@pigpen:~# 
```

Also, the `end` sector is the *last* sector, so `size` should be computed as `$((end - start + 1))` ... or simply use `$sectors`.

**Comment by dangowrt** [comment]
Should be fixed by https://github.com/openwrt/packages/commit/b1edbe349f9e70c72c4a48565a4fd37c94f20a0a and subsequent https://github.com/openwrt/packages/commit/adce04d840ea0dee718455a51a576122c7a460a7. Please re-open if not.
