### ISSUE TITLE
perl IO Socket problem

### ISSUE THREAD

**Issue by RussellSenior** [openwrt/packages#2044]
I am seeing a message in logread:

Bareword "Errno::EINVAL" not allowed while "strict subs" in use at /usr/lib/perl5/5.22/IO/Socket.pm line 129

This seems to be related to gcc-5.2, see:

  http://www.nntp.perl.org/group/perl.perl5.porters/2015/09/msg230796.html

@Naoir

**Comment by RussellSenior** [comment]
With
CONFIG_GCC_VERSION="4.8-linaro"
no error.

**Comment by Naoir** [comment]
This all boils down to the configuration system not setting 'gccversion' correctly, which Errno uses to adapt to GCC5's behaviour. It'll then silently fail to parse the error code definitions, resulting in Errno::EINVAL(and friends) not being defined as described by you.

I'll push a fix to master shortly.

Thank you a lot!
