### ISSUE TITLE
borgbackup: missing modules on Linksys WRT1200AC (armv7l) with OpenWrt 22.03.0

### ISSUE THREAD

**Issue by snpz** [openwrt/packages#20441]
Maintainer: @julienmalik 
Environment: armv7l, Linksys WRT1200AC, openwrt 22.03.0

Description:
I've installed the package borgbackup via Luci on my router, but when I run the borg command afterwards I'm receiving the following errors:

```
root@router:~# borg
Traceback (most recent call last):
  File "/usr/bin/borg", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 6, in <module>
ModuleNotFoundError: No module named 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 15, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Any suggestions what I need to do to make it work?

Thanks in advance!

**Comment by julienmalik** [comment]
The package is probably simply missing some dependencies. And I probably did not notice since the system on which I test already have them installed.

From your logs you can first try :
- `python3-email`
- `python3-pkg-resources`

**Comment by snpz** [comment]
I just tried your suggestions, but there wasn't enough free space on my router for the installation. I reflashed without my usual additional packages, taking just the suggested ones in firmware selector to test it.

Both packages you mentioned were needed and additionally `python3-packaging`. When running the `borg` command I'm now getting the expected help output. (did not test any further)

Thanks for your help, unfortunately I will have to switch to something else because of my free space limitations. (probably restic)

**Comment by julienmalik** [comment]
I tested on a x86 docker and after installing the package, had to install :
- `python3-email`
- `python3-urllib`
- `python3-packaging`
- `python3-uuid`
- `python3-unittest`

some of them clearly miss from the package dependency list and I should fix this, but the first two look like missing dependencies when using the importlib package.
