### ISSUE TITLE
miniupnp doesn't work

### ISSUE THREAD

**Issue by PeakGymnast** [openwrt/packages#20465]
luci-app-upnp package version：git-22.250.64651-a61c041
Openwrt version：OpenWrt 22.03.3 r20028-43d71ad93e
Device：phicomm k2p

### Miniupnp log
![image](https://user-images.githubusercontent.com/85560713/217440955-0f55f0d6-0d2f-4811-99fd-71f59cdfccfc.png)

### upnp config
_root@OpenWrt:~# cat /etc/config/upnpd

config upnpd 'config'
        option download '1024'
        option upload '512'
        option internal_iface 'lan'
        option port '5000'
        option upnp_lease_file '/var/run/miniupnpd.leases'
        option igdv1 '1'
        option enabled '1'
        option uuid '199cc7dd-ad45-43dc-9324-bc7b097a73ce'
        option presentation_url 'http://192.168.1.1'
        option force_forwarding '1'
        option use_stun '1'
        option stun_host 'stun.miwifi.com'
        option stun_port '3478'
        option log_output '1'

config perm_rule
        option action 'allow'
        option ext_ports '1024-65535'
        option int_addr '0.0.0.0/0'
        option int_ports '1024-65535'
        option comment 'Allow high ports'

config perm_rule
        option action 'deny'
        option ext_ports '0-65535'
        option int_addr '0.0.0.0/0'
        option int_ports '0-65535'
        option comment 'Default deny'_

### i am confused that the nat type turns into OPEN on my xbox one x game console, but it won't take the effect with other magnet download program such as utorrent and BitComet, also no active redirects on upnp panel. i have tried to reinstall another firmware [PADAVAN](https://opt.cn2qq.com/padavan/), the modified firmware won‘t suffer this issue 
![image](https://user-images.githubusercontent.com/85560713/217439940-d1f5a340-efcf-4884-9cd2-a9fd3fbde87c.png)
![image](https://user-images.githubusercontent.com/85560713/217440151-44fbbfd1-7397-4d73-87af-3416fa0631c7.png)

**Comment by stintel** [comment]
You are behind CGNAT. This is not something we can fix. Request your ISP to assign you a public IP instead.

**Comment by EkkoG** [comment]
> You are behind CGNAT. This is not something we can fix. Request your ISP to assign you a public IP instead. Also, please don't post logs as screenshots. As for the Xbox showing Open NAT while there is no working port-forward ... Microsoft at its best. I can confirm I am seeing the same on my Xbox Series X. I have tested miniupnpd with upnpc and this works fine, rules are added, and forwarding works. Doing the NAT test in the Xbox settings doesn't create any rules, yet the thing claims open NAT. I have contacted Microsoft about UPnP issues at some point, but my query was completely ignored. So the only advice I can give: stop sending money to Microsoft.

@stintel with [natmap](https://github.com/heiher/natmap) UPnP will work fine when CGNAT type is full-cone

**Comment by stintel** [comment]
> @stintel with [natmap](https://github.com/heiher/natmap) UPnP will work fine when CGNAT type is full-cone

Feel free to contribute it. I'm not behind CGNAT so I will not spend time on it.
