### ISSUE TITLE
PHP8 - Timezone database is corrupt

### ISSUE THREAD

**Issue by Kreten8** [openwrt/packages#20471]
NETGEAR WAX202, OpenWrt 22.03.3
`echo strtotime('2023-02-09');`
`Fatal error: Uncaught Error: Timezone database is corrupt. Please file a bug report as this should never happen in /www/index.php:35 Stack trace: #0 /www/index.php(35): strtotime('2023-02-09') #1 {main} thrown in /www/index.php on line 35`

**Comment by mhei** [comment]
Works for me. Which zoneinfo packages do you have installed?

**Comment by mhei** [comment]
No feedback, so closing for now. Please re-open in case new information is available.
