### ISSUE TITLE
The erlang package does not include the no_dot_erlang.boot file

### ISSUE THREAD

**Issue by helloyan** [openwrt/packages#20587]
Maintainer: @cretingame
Environment: (put here arch, model, OpenWrt version)
OpenWrt R23.2.14 / LuCI Master (git-23.061.09355-88ea4f3)

Description:

```
The file /usr/lib/erlang/bin/no_dot_erlang.boot is not present
```

**Comment by Neustradamus** [comment]
@antonlacon, @yousong, @champtar, @neheb, @ja-pa, @peterwillcn, @micmac1, @lipnitsk, @svlobanov, @dhewg, @paulfertser, @aparcar: Have you seen this ticket?

**Comment by cretingame** [comment]
Sorry, I'm not maintaining this package anymore. I cannot help you.
