### ISSUE TITLE
samba4: failing to compile on arm_cortex-a9_vfpv3-d16

### ISSUE THREAD

**Issue by PalebloodSky** [openwrt/packages#20589]
Samba4 has been failing to compile on snapshots recently for cortex-a9_vfpv3-d16.

Fail logs are here, use ctrl+F for "a9+vfpv3-d16", errors appear in all files:
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3-d16/packages/

This _just_ started happening and don't think it's GCC 12, because my last good build from 2/23/23 used GCC 12.2 and Samba worked great. Sadly on my WRT32X using Samba daily so I need it back.

Please fix compiling.

(As an aside, it might be a good time to bump the Samba4 version, 4.17.5 has CVE fixes listed on their website, and Samba 4.18 says to have 3x performance improvement in path based ops.)

**Comment by PalebloodSky** [comment]
Dirty work-around: a hopefully short term solution is by installing samba4 from the 22.03.3 release. (The irony is that this wasn't even released for mvebu but the packages carry over.)

In /etc/opkg.conf, commented out the signature check.
In /etc/opkg/customfeeds.conf added:
src/gz openwrt_packages2 https://downloads.openwrt.org/releases/22.03.3/packages/arm_cortex-a9_vfpv3-d16/packages/
src/gz openwrt_base2 https://downloads.openwrt.org/releases/22.03.3/packages/arm_cortex-a9_vfpv3-d16/base/

Then used opkg to install luci-app-samba4, server, etc. from 22.03 feed. Ok it's an older version filled with CVEs compared to Samba 4.17.x in master branch, but at least it installs and works.

**Comment by 1715173329** [comment]
looks like the package builds again

**Comment by PalebloodSky** [comment]
Ah you're right. Not sure how it fixed, I'll check if builds again tomorrow to make sure it's not a fluke then close this issue.

**Comment by PalebloodSky** [comment]
Well after about a week of this not compiling it's been compiling again for last 2 days. I'll go ahead and close this.
