### ISSUE TITLE
multiple issues with mpd init script.

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#2066]
grep ^playlist_directory /etc/mpd.conf  | cut -d "\"" -f 2 | sed "s/~/\/root/g" replaces ~ with /root. this does not work when the user is different than root.

also, mpd fails when a few files are missing. from my testing, the files log and database are required. the arch linux wiki suggests using touch to initialize the files.

**Comment by thess** [comment]
The mpd.conf file is just an example/template. There are several settings which most likely will have to be tailored to your particular environment.

Closing this request
