### ISSUE TITLE
how to setup ipsec/vpn with strongswan

### ISSUE THREAD

**Issue by ptpt52** [openwrt/packages#20707]
Here are some VPN types:
 - L2TP/IPSec PSK
 - L2TP/IPSec RSA
 - IPSec Xauth PSK
 - IPSec Xauth RSA
 - IPSec Hybrid RSA
 - IKEv2/IPSec MSCHAPv2
 - IKEv2/IPSec PSK
 - IKEv2/IPSec RSA
 
How can each of these VPN types be deployed and configured on an OpenWRT server? Could you provide specific examples?

**Comment by ptpt52** [comment]
need some help. ping @pprindeville @stintel @ynezz

**Comment by stintel** [comment]
This is an issue tracker, for support: https://openwrt.org/contact.
