### ISSUE TITLE
pbr: impossible to add port forward rules while pbr is installed. 

### ISSUE THREAD

**Issue by m4ri0g** [openwrt/packages#20713]
Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment:

OpenWrt version
r19803-9a599fee93

OpenWrt target/subtarget
mvebu/cortexa9

Device
Linksys WRT3200ACM

Description:

While pbr is installed. it is not possible to add a port forwarding rule in network > firewall > port forwards 
as soon as the changes are saved and applied. the port forward dissapear and the following is displayed on the logs. 

```
Sun Mar 19 15:14:22 2023 user.notice pbr: Reloading pbr due to includes of firewall
Sun Mar 19 15:14:23 2023 user.notice pbr: Activating traffic killswitch [✓]
Sun Mar 19 15:14:23 2023 user.notice pbr: Setting up routing for 'wan/x.x.x.x [✓]
Sun Mar 19 15:14:23 2023 user.notice pbr: Setting up routing for 'wg0/x.x.x.x' [✓]
Sun Mar 19 15:14:23 2023 user.notice pbr: Routing 'synology' via wan [✓]
Sun Mar 19 15:14:24 2023 user.notice pbr: Deactivating traffic killswitch [✓]
Sun Mar 19 15:14:24 2023 user.notice pbr: service monitoring interfaces: wan wg0
```
removing pbr package allows the port forwards to be saved. 
reinstalling pbr keeps the port forwards 
consequent port forwards are possible.

**Comment by stangri** [comment]
If it's about the luci app this bug report should be in openwrt/luci, not openwrt/packages.

You may want to include screenshots of the "port forward" before you click save & apply.
