### ISSUE TITLE
<fdm> [Bug] A UAF bug in connect.c 

### ISSUE THREAD

**Issue by ShangzhiXu** [openwrt/packages#20773]
**Maintainer:** Dmitry V. Zimin <pfzim@mail.ru>
**Environment:** 22.3

**Description:**

In this file, at line 553-554, it looks like this
```
	xfree(line);
	xasprintf(cause, "unexpected data: %s", line);
```
the `line` is freed, but then used in the next line, it may lead to output unexpected content or even lead to crash

**Suggestion:**
This bug has been fixed in the fdm-master on github yesterday.

**Comment by neheb** [comment]
Fix was merged.
