### ISSUE TITLE
mwan3: status shows wrong elapsed time when interfeace is offline

### ISSUE THREAD

**Issue by humaita-github** [openwrt/packages#20829]
Hi,

I am running mwan3 2.11.4-1 on a TP-Link Archer C7 v5 with OpenWrt 22.03.4. Everything seems to be working fine.

I am only seeing one small issue: when an interface goes offline, then status will stay at zero, i.e. status stays at "interface wan is offline 00h:00m:00s" instead of showing the actual elapsed time.

I am not an expert, but it seems to me that /lib/mwan3/common.sh is only checking the timestamp of <$MWAN3TRACK_STATUS_DIR/${iface}/ONLINE>. But when the interface is offline, it should actually be checking the OFFLINE file.

Maintainer: @feckert

**Comment by feckert** [comment]
Offline time should not actually be displayed. This is an error in the evaluation of the status. I have therefore created a [pullrequest](https://github.com/openwrt/packages/pull/22158) that reworks the entire status evaluation. Unfortunately, I am not sure yet if I can apply this to the owrt-22.03 easily.

Please try this and see if it fixes the problem in owrt-23.05 or master. I will only merge this change to master and owrt-23.05 for now.
If you try this, please update this issue and report back. Regardless, I am closing the issue for now.
