### ISSUE TITLE
strongswan: "running with no instances"

### ISSUE THREAD

**Issue by lowjoel** [openwrt/packages#20848]
Maintainer: @pprindeville 
Environment: aarch64 Linksys E8450, OpenWrt 22.03.4

Description:

I've noticed that when I specify `ipsec.interface` on `/etc/config/ipsec`, occasionally Charon doesn't actually listen for connections. `/etc/init.d/swanctl status` says `running with no instances`.

I tried to dig through the code and my main suspect is: https://github.com/openwrt/packages/blob/8686e69765d2e2886c7819eacb55bbd7bebe170e/net/strongswan/files/swanctl.init#L715

I believe that's a problem when swanctl-init runs before the interfaces are actually registered (maybe a race with interface bringup?)

I'm not sure where this problem originated, but maybe the fix is to provide a default /etc/hotplug.d/iface script that reloads the service every time an interface change is detected? If that seems to be the fix I'll be happy to provide a patch.

**Comment by aleks-mariusz** [comment]
@lowjoel i'd be curious to see what this patch looks like.. 

at the moment i have put this in my rc.local as a hacky workaround:

```
(  /etc/init.d/swanctl stop; sleep 10; /etc/init.d/swanctl start ) &
```

**Comment by pprindeville** [comment]
> I'm not sure where this problem originated, but maybe the fix is to provide a default /etc/hotplug.d/iface script that reloads the service every time an interface change is detected? If that seems to be the fix I'll be happy to provide a patch.

Alternately, we could add an interface trigger.  Maybe something like:

```
service_triggers() {
        procd_add_reload_interface_trigger wan

        ...
}
```

**Comment by lowjoel** [comment]
@aleks-mariusz yeah, that in a hotplug.d/iface script would probably be more predictable. But that's essentially what @pprindeville's patch using `prod_add_reload` does, which would be the better fix. Maybe in /etc/init.d/swanctl:

```bash
service_triggers() {
    config_foreach service_trigger_ipsec ipsec

    ...
}

service_trigger_ipsec() {
    local interface
    local interface_list
    config_list_foreach "$1" interface append_var interface_list
    for interface in $interface_list; do
        procd_add_reload_interface_trigger $interface
    done
}
```

(hacked together with zero testing, maybe you can think of a better solution)

**Comment by pprindeville** [comment]
> @aleks-mariusz yeah, that in a hotplug.d/iface script would probably be more predictable. But that's essentially what @pprindeville's patch using `prod_add_reload` does, which would be the better fix. Maybe in /etc/init.d/swanctl:
> 
> ```shell
> service_triggers() {
>     config_foreach service_trigger_ipsec ipsec
> 
>     ...
> }
> 
> service_trigger_ipsec() {
>     local interface
>     local interface_list
>     config_list_foreach "$1" interface append_var interface_list
>     for interface in $interface_list; do
>         procd_add_reload_interface_trigger $interface
>     done
> }
> ```
> 
> (hacked together with zero testing, maybe you can think of a better solution)

I'm not sure there's any value to adding triggers to LAN interfaces...  Though I can see the need for supporting multiple WAN devices if someone is multi-homed and using `mwan3`, for instance.

Please provide a tested patch and I'll review it.

Also, I'd put as many variables on a single `local` line as will fit for compactness.

**Comment by lowjoel** [comment]
I've applied that [patch](https://github.com/openwrt/packages/issues/20848#issuecomment-1775379577) in /etc/init.d/swanctl after upgrading my routers to 5.9.11 -- it's hard to verify, but it does feel like the likelihood of "running with no instances" seem to have dropped drastically. I am indeed using `mwan3`.

I can combine the locals in the same line, but the question is -- even if there's no interface specified, we should be reloading the config every time a network interface changes? In my case:

```
 config ipsec
        list interface 'wan'
        list interface 'wanb'
```
Makes sense, but if no interfaces are specified, no changing config (even with mwan3) would cause a reload. Any ideas?
