### ISSUE TITLE
<Nftables>:seems to have serious Performance flaws. for IPQ40XX

### ISSUE THREAD

**Issue by 57382** [openwrt/packages#20854]
Maintainer: @aparcar 
Environment: IPQ40XX, R619AC, OpenWrt 22.0.3.4

Description:

![image](https://user-images.githubusercontent.com/81396211/233527688-7839b81a-a006-468e-ad17-20b90e0fd6e3.png)
iptables/firewall3

=================================

![image](https://user-images.githubusercontent.com/81396211/233527797-a83cfd2b-0a48-4f4b-b82d-d7331e70dc34.png)
nftables/firewall4
I was able to reproduce the problem exactly. Tested many times
https://github.com/openwrt/openwrt/issues/12429

**Comment by brada4** [comment]
It is base system component already reported as per issue you linked.

**Comment by aparcar** [comment]
Hey I'm not the maintainer and please don't open issues twice. If it already exists in `openwrt.git` please don't open another one here.
