### ISSUE TITLE
golang: GO_PKG_GCFLAGS could be improved

### ISSUE THREAD

**Issue by hgl** [openwrt/packages#20911]
Maintainer: @jefferyto 
Environment: (put here arch, model, OpenWrt version)

Description:
Since Go 1.10, `-gcflags` accepts `[pattern=]arg list`. WIthout the pattern, the flags only applies to the current package. `GO_PKG_GCFLAGS` currently supports the pattern in a fragile way, like if you specify `GO_PKG_GCFLAGS='pkg.foo='-a -b'` and also enable spectre, it's going to be applied to `pkg.foo`, and multi-pattern is totally unsupported.

A few thoughts regarding the fix:

1. One of the most common usage for gcflags is probably disabling optimization to test binary on OpenWrt, should something like `GO_PKG_DISABLE_OPTIMIZATION` be introduced, which adds a separate `-gcflags all='-N -l'`?
2. To specify multiple patterns, multiple `-gcflags` has to be used. This makes it impossible to specify such values in a single make variable, e.g.,`GO_PKG_GCFLAGS := foo='-a -b' bar='-c -d'` won't work because of the spaces. The only solution I can think of is to introduce a make variable that can add flags directly in the command line, e.g., `GO_PKG_ARGS := -gcflags foo='-a -b' -gcflags bar='-c -d'`
3. Given that currently no packages in the repo use `GO_PKG_GCFLAGS`, maybe we could simply make it add its value after the `all=` pattern? It should address 80% of the use cases, and `GO_PKG_GCFLAGS:=-N -l` can work as expected. This is a breaking change though, could potentially affect packages not living here.

Thoughts?

**Comment by hgl** [comment]
@jefferyto ping

**Comment by jefferyto** [comment]
Apologies for the late response - do you have a specific use-case/issue with `GO_PKG_GCFLAGS`? As you mentioned, there are no packages in this repo that set gcflags, and I would prefer not to expand this functionality without a concrete purpose.
