### ISSUE TITLE
[utils/coreutils] please update to 9.3 to solve bug for openwrt run in lxc containers

### ISSUE THREAD

**Issue by Arunmor1510** [openwrt/packages#20933]
Environment: openwrt x86_64 built with lastest git version, run in unprivileged lxc container

Description: With `coreutils 9.2`, when using utilities like `cp`,`mv`, they will fail. [bug report on gnu.org](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62404)

**Comment by stangri** [comment]
Tagging last committer and maintainer @httpstorm @jow.

**Comment by httpstorm** [comment]
@Arunmor1510 @stangri 
coreutils: update to 9.3 https://github.com/openwrt/packages/pull/20965

**Comment by 1715173329** [comment]
i guess this issue can be closed ;)

**Comment by httpstorm** [comment]
@1715173329 
Thanks! I'm curious why does it say `Unverified`, considering I have added `Signed-off-by:`?

**Comment by 1715173329** [comment]
ahhh i enabled [vigilant mode](https://docs.github.com/github/authenticating-to-github/displaying-verification-statuses-for-all-of-your-commits).
i cannot sign it when using rebase merging provided by github web. it's not a big issue, just ignore it
