### ISSUE TITLE
libwebsockets: fails to build with gcc-13

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/packages#20949]
but adding `TARGET_CFLAGS += -Wno-error=enum-int-mismatch` to Makefile allows building..

```
...
PKG_BUILD_DEPENDS:=libubox

CMAKE_INSTALL:=1

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

TARGET_CFLAGS += -Wno-error=enum-int-mismatch

CMAKE_OPTIONS += -DLWS_IPV6=$(if $(CONFIG_IPV6),ON,OFF)
CMAKE_OPTIONS += -DISABLE_WERROR=ON
CMAKE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
CMAKE_OPTIONS += -DLWS_WITH_EXTERNAL_POLL=ON
CMAKE_OPTIONS += -DLWS_WITH_ULOOP=ON

...
```

**Comment by oskarirauta** [comment]
@blogic

**Comment by karlp** [comment]
Please track upstream's fixes for this as well, looks like https://github.com/warmcat/libwebsockets/pull/2824 is the path they're taking.

**Comment by oskarirauta** [comment]
FYI

https://github.com/openwrt/packages/issues/20961#issuecomment-1538111054

similar issue fixed like this.
But surely libwebsockets comes up with a new release with proposed fix soon..

**Comment by oskarirauta** [comment]
@karlp warm cat/libwebsockets#2824 is not sufficient. I tried it. It works on no-ssl variant, but fails on mbedtls variant. Probably with openssl as well.

**Comment by oskarirauta** [comment]
PR #21206 is available

**Comment by karlp** [comment]
closed as superseded
