### ISSUE TITLE
ttyd: failure to link libwebsockets and libssl with gcc 13

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/packages#20987]
Work-around, add this to package's Makefile:

```
TARGET_LDFLAGS += -lssl -lcrypto -lwebsockets
```

Quick and dirty, proper solution would be better but this works for now for those who want to _build it all_..

**Comment by 1715173329** [comment]
ttyd in tree is pretty old, can you try to bump it to recent version?

**Comment by oskarirauta** [comment]
@1715173329

If I remember correctly, I tried some time ago and failed for some reason - but maybe I could give it a shot..

**Comment by oskarirauta** [comment]
@1715173329 

PR #21092
