### ISSUE TITLE
<ocserv> liboath and otp support

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [openwrt/packages#21001]
Maintainer: @nmav
Environment: -

Description:

The `ocserv` package is not linked to liboath and does not support otp:
https://gitlab.com/openconnect/ocserv/-/issues/508#note_1388900513

It would be great if otp support could be added as described above.

**Comment by nmav** [comment]
Given that liboath is not in openwrt and this looks something like nice to have, I'm inclined to close this as wontfix.

**Comment by varunpalekar** [comment]
I am also looking to this feature, anyone solve it?

**Comment by varunpalekar** [comment]
Looks like it has the option, we just need to rebuild it https://github.com/openwrt/packages/blob/openwrt-23.05/net/ocserv/Config.in
