### ISSUE TITLE
acl build failed

### ISSUE THREAD

**Issue by shanpo** [openwrt/packages#21051]
x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I./include  -I./include -I./include -DLOCALEDIR=\"/usr/share/locale\" -I/home/jwd/src/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/include -I/home/jwd/src/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include/fortify -I/home/jwd/src/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include  -DNDEBUG  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/jwd/src/openwrt/build_dir/target-x86_64_musl/acl-2.3.1=acl-2.3.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -fvisibility=hidden -c -o tools/chacl.o tools/chacl.c
tools/chacl.c: In function 'walk_dir':
tools/chacl.c:335:21: warning: implicit declaration of function 'readdir64'; did you mean 'readdir_r'? [-Wimplicit-function-declaration]
  335 |         while ((d = readdir64(dir)) != NULL) {
      |                     ^~~~~~~~~
      |                     readdir_r
tools/chacl.c:335:19: warning: assignment to 'struct dirent64 *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  335 |         while ((d = readdir64(dir)) != NULL) {
      |                   ^
tools/chacl.c:337:29: error: invalid use of undefined type 'struct dirent64'
  337 |                 if (strcmp(d->d_name, ".") == 0 || strcmp(d->d_name, "..") == 0)
      |                             ^~
tools/chacl.c:337:60: error: invalid use of undefined type 'struct dirent64'
  337 |                 if (strcmp(d->d_name, ".") == 0 || strcmp(d->d_name, "..") == 0)
      |                                                            ^~
tools/chacl.c:340:55: error: invalid use of undefined type 'struct dirent64'
  340 |                 name = malloc(strlen(fname) + strlen(d->d_name) + 2);
      |                                                       ^~
tools/chacl.c:346:48: error: invalid use of undefined type 'struct dirent64'
  346 |                 sprintf(name, "%s/%s", fname, d->d_name);
      |                                                ^~
make[4]: *** [Makefile:1282: tools/chacl.o] Error 1
make[4]: Leaving directory '/home/jwd/src/openwrt/build_dir/target-x86_64_musl/acl-2.3.1'
make[3]: *** [Makefile:87: /home/jwd/src/openwrt/build_dir/target-x86_64_musl/acl-2.3.1/.built] Error 2
make[3]: Leaving directory '/home/jwd/src/openwrt/feeds/packages/utils/acl'
time: package/feeds/packages/acl/compile#0.25#0.13#0.35
    ERROR: package/feeds/packages/acl failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/acl/compile] Error 1
make[2]: Leaving directory '/home/jwd/src/openwrt'
make[1]: *** [package/Makefile:114: /home/jwd/src/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jwd/src/openwrt'
make: *** [/home/jwd/src/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by hmh** [comment]
This is currently happening on the openwrt-23.05 branch, the fix for master works as well (bumping the contents of utils/acl in opentwrt-23.05 to match what is in master).
