### ISSUE TITLE
python packages: Build failure

### ISSUE THREAD

**Issue by jefferyto** [openwrt/packages#21162]
Maintainer: me
Environment: all probably

Description:
All Python packages have failed to build on buildbots for aarch64-generic. For instance https://downloads.openwrt.org/snapshots/faillogs/aarch64_generic/packages/python-attrs/compile.txt:

```
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/python3.11'

ERROR Backend operation failed: FileNotFoundError(2, 'No such file or directory')
make[3]: *** [Makefile:47: /builder/shared-workdir/build/sdk/build_dir/target-aarch64_generic_musl/pypi/attrs-23.1.0/.built] Error 1
time: package/feeds/packages/python-attrs/compile#0.45#0.26#0.89
```

Also confirmed by @nxhack (https://github.com/openwrt/packages/commit/2445fe9fb25e6d9eed28aa9ad237bd250d1600d1#commitcomment-114742991) and @datahost (https://github.com/openwrt/packages/issues/21155#issuecomment-1561361939).

**Comment by ptpt52** [comment]
related: https://github.com/openwrt/packages/issues/21164
