### ISSUE TITLE
[adblock] Do not store pcap files on reports directory, use /tmp

### ISSUE THREAD

**Issue by schuettecarsten** [openwrt/packages#21307]
Adblock allows to specify a "Report Directory".
This directory should be used for calculated report data, not for the the tcpdump pcap files.

**Comment by dibdot** [comment]
Sounds weird - the default is on /tmp and you do not provide any reasoning. Closing this.

**Comment by schuettecarsten** [comment]
Sorry for long delay @debdot.

Problem is that you can move the directory to your attached USB device or somewhere else. That might be useful to persist the report results. But in this case, the pcap files are also moved to the USB device. And that's not a good idea. I suggest to separate the reports result folder and the temp data folder into two different settings.

**Comment by dibdot** [comment]
Moving this (incl. the pcap files) is useful to save RAM on the limited router.
