### ISSUE TITLE
xray-core: New version available

### ISSUE THREAD

**Issue by ttc0419** [openwrt/packages#21407]
Maintainer: @1715173329 
Environment: OpenWrt 22.03

**Description:**
Xray-core just released [1.8.3](https://github.com/XTLS/Xray-core/releases/tag/v1.8.3).

**Comment by 1715173329** [comment]
Feel free to create a PR for it

**Comment by 1715173329** [comment]
c912e2bcedfcfb50c1ee02d0fa120f0b0025ac2c
