### ISSUE TITLE
could not open lease file: /var/upnp.leases

### ISSUE THREAD

**Issue by Yumega** [openwrt/packages#21414]
Please make sure that the issue subject starts with `<package-name>: `

Also make sure that the package is maintained in this repository and not in base which should be submitted at https://bugs.openwrt.org or in the LuCI repository which should be submitted at https://github.com/openwrt/luci/issues.

Issues related to releases below 18.06 and forks are not supported or maintained and will be closed.

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)
x86_64, OpenWrt R23.1.1
Description:
UPNP doesn't work
```
Format code blocks by wrapping them with pairs of ```
```
Tue Jun 20 14:35:55 2023 daemon.err miniupnpd[28421]: could not open lease file: /var/upnp.leases
Tue Jun 20 14:35:55 2023 daemon.notice miniupnpd[28421]: HTTP listening on port 5000

**Comment by rmilecki** [comment]
This report is mostly an unfilled template with just 2 extra log messages and no description of actual problem at all. Closing for now. Feel free to update it and provide a proper problem description if there is one.
