### ISSUE TITLE
v2raya: should not be forced to depend on `xray-core` now

### ISSUE THREAD

**Issue by SpriteOvO** [openwrt/packages#21450]
Maintainer: @1715173329 

Description:

Since `v2ray-core` package has been added in PR #19327, and both `v2ray-core` and `xray-core` can be used as a dependency of `v2raya`, for now, I think `v2raya` should not be forced to depend on `xray-core`.

I'm not sure if `opkg` has a mechanism for optional dependencies, however, I think there should be a way to let users to determine which `-core` package to be installed only and used.

BTW, [the blue notice in the doc](https://v2raya.org/docs/prologue/installation/openwrt/#%E9%80%9A%E8%BF%87-openwrt-%E5%AE%98%E6%96%B9%E8%BD%AF%E4%BB%B6%E6%BA%90%E5%AE%89%E8%A3%85) of `v2raya` is outdated and need to be updated as well.

**Comment by 1715173329** [comment]
i've updated that doc, let's close it for now
