### ISSUE TITLE
seafile depends on Django 1.5 which has multiple CVE's and is EOL

### ISSUE THREAD

**Issue by dfc-d** [openwrt/packages#2151]
I'm going to do a series of issue reports with seafile in case someone cares to fix the issues which led to my issuing a PR to move seafile to packages-abandonded.

For this issue:

seafile depends on unpatched Django 1.5 which has multiple CVE's against it and has been EOL for some time.

**Comment by hnyman** [comment]
seafile has been udpated by #2651
