### ISSUE TITLE
seafile does not properly cross compile (builds various binaries against host arch instead of target)

### ISSUE THREAD

**Issue by ghost** [openwrt/packages#2152]
I'm going to do a series of issue reports with seafile in case someone cares to fix the issues which led to my issuing a PR to move seafile to packages-abandonded.

For this issue:

seafile builds a number of binaries for the host arch instead of target arch, when host arch does not match target arch (i.e. x86 cross-compiling for ar71xx).

This occurs for both seafile-server and seafile-seahub because of the way in which the Python builds are invoked.

For seafile-seahub the primary offender I am aware of PIL which is pulled in through easy_install of Djblets and would actually require patches (on PIL) to properly cross-compile.

**Comment by kissg1988** [comment]
This has been fixed by properly packaging all the python dependencies.

See https://github.com/openwrt/packages/pull/2651

**Comment by cshoredaniel** [comment]
This should be closed

**Comment by thess** [comment]
OK by me
