### ISSUE TITLE
install zerotier BUG-X86_64 for 23.05.0-rc2

### ISSUE THREAD

**Issue by dlcy** [openwrt/packages#21636]
opkg install zerotier
Installing zerotier (1.10.4-1)
check data file clashes: Package libnl-tinu2023-07-01 wants to install file /usr/lib/libnl-tiny.so
But that file is already provided by package
*libnl-tiny2023-04-02
*opkg_install_cmd: Cannot install package zerotier.
--------------------------------------------
BUT don't down  libnl-tiny2023-07-01 2023-07-01-d433990c-1x8664.ipk

**Comment by brada4** [comment]
https://github.com/openwrt/openwrt/issues/13082 wait for next rc3 or build snapshot

**Comment by jow-** [comment]
Duplicate of https://github.com/openwrt/openwrt/issues/13082
