### ISSUE TITLE
Is there any plan to support perl for riscv architecture ?

### ISSUE THREAD

**Issue by cyqtmxk** [openwrt/packages#21684]
Description:
I find the the file Config.in in the lang/perl/ doesn't support riscv64, how to setup the riscv64.config file correctly in (https://github.com/openwrt/packages/tree/master/lang/perl/files) ？
thanks in advance!
![image](https://github.com/openwrt/packages/assets/10682818/4ed2d853-c513-473c-aacc-1656b09a3bc5)

**Comment by BKPepe** [comment]
Done in https://github.com/openwrt/packages/commit/cf59047d3c3f07baed76751e19f06db9c6541800
