### ISSUE TITLE
Unable to connect with network after installing cache-domains-openssl

### ISSUE THREAD

**Issue by naveen1hot** [openwrt/packages#21682]
Hello team,
After installing cache-domains-openssl unable to connect with network while restarting router.
Kindly check..

**Comment by maheruf** [comment]
same issue

**Comment by naveen1hot** [comment]
With latest firmware issue got resolved..

**Comment by maheruf** [comment]
Well it doesn't connect to network if used with mwan3.

**Comment by maheruf** [comment]
> With latest firmware issue got resolved..

I do use mwan3 for combining 2 ISP into one. But my internet doesn't work if i install cache-domains-openssl even with latest firmware
