### ISSUE TITLE
i2pd: request to backport a package to previous releases

### ISSUE THREAD

**Issue by r4sas** [openwrt/packages#21741]
Maintainer: @yangfl

Hi.
Our application is updated every 3 months, and with each release, bugs are fixed that can affect both usability, performance, and user security. For this reason, I ask that you backport the latest versions of the i2pd package (recent: https://github.com/openwrt/packages/pull/21733) to branches of previous releases up to 19.07 (if possible).

Thank you.

**Comment by 1715173329** [comment]
It has been backported to 23.05 and 22.03 branch. For 21.02 and lower version, they're EoL and no longer maintained.

**Comment by feckert** [comment]
Done

**Comment by r4sas** [comment]
Thank you, everyone!
