### ISSUE TITLE
tang: check dependency for bash

### ISSUE THREAD

**Issue by coelner** [openwrt/packages#21799]
Maintainer: @nmav 
Environment: master branch

Description:
there should no need for the bash package. It could save about 300kB space.
- tangd
- tangd-rotate-keys
- tangd-keygen
working with busybox shell.

**Comment by nmav** [comment]
There was a reason for bash being present. Maybe it is not there any more, I do not know. If there isn't could you submit a pull request and test tang without bash?

**Comment by coelner** [comment]
pull request is not possible due the `signed-by {real name}` policy.
related to this issue: https://github.com/openwrt/packages/issues/15592#issuecomment-1636914237
