### ISSUE TITLE
strongswan-mod-nonce is absent in 23.05.0-rc2

### ISSUE THREAD

**Issue by epiniguin** [openwrt/packages#21825]
Maintainer: @pprindeville @Thermi
Environment: (put here arch, model, OpenWrt version 23.05.0-rc2, snapshot)

Description:
The package strongswan-mod-nonce is absent in 23.05.0-rc2 and in a snapshot.

**Comment by Pristavkin** [comment]
As well as the rest of strongswan packages. For exapmple status page for main strongswan package: https://openwrt.org/packages/pkgdata/strongswan

**Comment by BKPepe** [comment]
It's because https://github.com/openwrt/packages/commit/e67eb58312b5b86fc1e10d8b7d1168cd64c16f6d.
