### ISSUE TITLE
adguardhome 0.107.21-1 doesn't wait for ip6 address and fails to start after reboot

### ISSUE THREAD

**Issue by iljah** [openwrt/packages#21868]
Environment: 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.5'
DISTRIB_REVISION='r20134-5f15225c1e'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'

Description:

adguardhome doesn't start after reboot: `[fatal] couldn't start forwarding DNS server: listening to udp socket: list en udp [fda3:ca1f:2ac2::1]:53: bind: cannot assign requested address`

Moving adguard init from S25 to S97 doesn't help. Adding respawn 300 3 3 doesn't help giving same result several times. Starting manually after logging in with ssh works. Above address is bridge interface, does it not get created fast enough? It's using static ip4 but I don't see any options for ip6 when editing it in web ui.

**Comment by iljah** [comment]
@jamesmacwhite seemed to active previously: https://github.com/openwrt/packages/issues/18585

**Comment by CallMeR** [comment]
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.36

The official latest version of Adguard Home is already ahead of the OpenWRT's repository .

**Comment by iljah** [comment]
Is this issue fixed there?
