### ISSUE TITLE
sshtunnel, openssh-client: "/etc/init.d/sshtunnel stop" kills processes unsuccessfully

### ISSUE THREAD

**Issue by jchia** [openwrt/packages#2187]
Chaos Calmer (15.05 r46767)
sshtunnel_3-3_ar71xx.ipk
openssh-client_6.8p1-1_ar71xx.ipk

"/etc/init.d/sshtunnel stop" issues `kill` commands on two sshtunnel-related processes but they refuse to die. The `kill` command does not specify which signal to use:

```
while read pid
do
       kill "$pid"     # kill mother process first

        [ -f "${PIDFILE}_${pid}.pid" ] && { # if ssh was running, kill it also (mother process could be in retry wait)
                start-stop-daemon -K -p "${PIDFILE}_${pid}.pid"
                rm "${PIDFILE}_${pid}.pid"
        }

        logger -p daemon.info -t "sshtunnel[$pid]" "tunnel stopped"

done < "${PIDFILE}.pids"
```

If I add `-9` to `kill` and `-s9` to start-stop-daemon, stopping seems to works, although I don't know whether this is the fault of sshtunnel or openssh-client (SSH refuses to die.)

**Comment by yousong** [comment]
Strace the relevant processes before doing stop may reveal if they actually received the signal and what were the reactions.

`sshtunnel` in `master` branch has turned to procd for service management.  You may want to give that a try.
