### ISSUE TITLE
[patch] ZNC FTBFS due to ICU dep

### ISSUE THREAD

**Issue by bastien-roucaries** [openwrt/packages#2193]
znc is FTBFS due to libicu not found.

using ICU is not an option due to huge size.

Better is to disable ICU by passing --disable-charset as configure flag.

Bastien

**Comment by srdjanrosic** [comment]
PKG_MAINTAINER:=Jonas Gorski <jogo@openwrt.org>
  aka.
KanjiMonster

**Comment by KanjiMonster** [comment]
Sorry for the late fix, was knocked out by a cold. In the future, please prefix my nick with @ so I get a notification for being mentioned.

**Comment by bastien-roucaries** [comment]
@KanjiMonster Still FTBFS see http://buildbot.openwrt.org:8010/broken_packages/ar71xx/znc/compile.txt should you do something on trunk (refresh ?)

**Comment by KanjiMonster** [comment]
I pushed an update to 1.6.2 at the same time. The build failure is with 1.6.1, so this build was started before the fix. You'll need to wait until the next build iteration.
