### ISSUE TITLE
banip: Dependency on logd breaks syslog-ng installation (again)

### ISSUE THREAD

**Issue by kesslerm** [openwrt/packages#21932]
Maintainer: @dibdot 

Since commit 82a491bac8 the `banip` package depends on `logd` again. This dependency was previously removed in PR https://github.com/openwrt/packages/pull/13848 after some discussion on issue https://github.com/openwrt/packages/issues/13820.

Is this simply an oversight, or is there some new functionality that can only be supported with `logd` but not `syslog-ng`?

**Comment by kuretru** [comment]
@kesslerm Hi, did your banip with syslog-ng working now? I test it, but banIP seems could not parse logs correctly.

**Comment by kesslerm** [comment]
I have only compile tested, using the turris-omnia toolchain (hbd branch).

**Comment by brada4** [comment]
logread is used only for asterisk as per script. Rest should be totally compatible down to removing logread as dependency even having it in scripts.

**Comment by dibdot** [comment]
Nope, the log detection depends on logread ATM and is not compatible with other log systems.

**Comment by kesslerm** [comment]
What about `logread` compatibility layers such as the [one provided](https://github.com/openwrt/packages/blob/master/admin/syslog-ng/files/logread) by `syslog-ng`?

**Comment by dibdot** [comment]
That does not work - I'll provide a suitable wrapper in a future update.
