### ISSUE TITLE
ddns-scripts-nsupdate: Zone support missing

### ISSUE THREAD

**Issue by LorbusChris** [openwrt/packages#22135]
Maintainer: @feckert @chris5560
Environment: any

Description:

RFC2136/nsupdate-capable servers support zoning. This e.g. allows for multi-tenant use of the DNS server, with each user only having edit-access to records in specific zones.

From https://linux.die.net/man/8/nsupdate:
> **zone zonename**
>     Specifies that all updates are to be made to the zone zonename. If no zone statement is provided, nsupdate will attempt determine the correct zone to update based on the rest of the input. 

Example command file:
```
zone myzone.example.com
update delete host.myzone.example.com. A
update add host.myzone.example.com. 600 A 203.0.113.0
```

Support for zones is currently missing from the ddns-scripts-nsupdate package.

**Comment by brada4** [comment]
nsupdate splits off domain and does proper request to dns server.
users are distinguished by authentication keys nowadays.
If you inted to use dots in hostnames where current nsupdate would fail feel free to submit PR

**Comment by LorbusChris** [comment]
Thanks, removing the zone statement does indeed work for me with current nsupdate.

I'll close this one.

RFE for keyfile support is https://github.com/openwrt/packages/issues/22136
