### ISSUE TITLE
msmtp: v1.8.19 missing set_msgid_header setting

### ISSUE THREAD

**Issue by brackenhill-mob** [openwrt/packages#22143]
Maintainer: @BKPepe 
Environment: OpenWrt 22.03.5
Description:

v1.8.19 is over 2 years old and missing the new set_msgid_header setting

The current version fails to insert the messageID header in any email sent. This header is checked by many spam filters and big mail providers (ie GMX) and any mail without it is immediately flagged as spam.

Please can this package be updated to the latest version (v1.8.24) which contains this setting.

Thanks

**Comment by BKPepe** [comment]
Hello,

I am still getting email notifications to my Gmail address from my routers, when they were updated, when they want to be restarted, etc. I haven't heard any complain about it since msmtp is installed on every Turris routers, but Turris is using their own mail server for that. @ljelinek-cznic am I corrrect?

Btw I am pretty sure that @mmtj in the past was using GMX for his email. Not sure, if he is using it anymore together with Turris. Maybe, he will be able to provide more details or confirm your findings.

In any case, for sure it can be updated to its the latest version available, but let me test it first. If everything goes well, I will send PR.

**Comment by mmtj** [comment]
Hi,

> Btw I am pretty sure that @mmtj in the past was using GMX for his email. Not sure, if he is using it anymore together with Turris. Maybe, he will be able to provide more details or confirm your findings.

I still use GMX email account and email notifications from my Turris routers (updates, restarts and so on) are passing through into my inbox just fine.

But note that I am using the default turris email relay. So if msmtp is really not adding this header to the original email, perhaps turris mail server is adding all the necessary headers and it works fine in the end.

**Comment by BKPepe** [comment]
Hey @mmtj thanks for the comment! Very appreciated.

**Comment by brackenhill-mob** [comment]
@BKPepe Thank you so much for creating the update. I'll try it out tomorrow when I'm in the office. This is a life saver for us as all our critical systems messaging passes through our OpenWrt router to GMX.

**Comment by ljelinek-cznic** [comment]
> Hi,
> 
> > Btw I am pretty sure that @mmtj in the past was using GMX for his email. Not sure, if he is using it anymore together with Turris. Maybe, he will be able to provide more details or confirm your findings.
> 
> I still use GMX email account and email notifications from my Turris routers (updates, restarts and so on) are passing through into my inbox just fine.
> 
> But note that I am using the default turris email relay. So if msmtp is really not adding this header to the original email, perhaps turris mail server is adding all the necessary headers and it works fine in the end.

Postfix (that is used for our notification mail server) adds the `Message-Id` header if it's missing. It applies for `Date` as well. But other headers like `From` are added only if conditions defined by `local_header_rewrite_clients` are matched or if `always_add_missing_headers` is enabled. (Older versions of Postfix than 2.6 added all missing headers.)

**Comment by BKPepe** [comment]
Package ``msmtp`` was updated in all branches including OpenWrt 21.02, which is still being used on my router as Turris OS 7.0 (based on OpenWrt 22.03) was not released so far.
