### ISSUE TITLE
ddns-scripts-services: New ddns provider to add

### ISSUE THREAD

**Issue by IgorBai** [openwrt/packages#22210]
Maintainer: @feckert
Environment: OpenWrt 21.02.3 r16554-1d4dea6d4f

Description:
I've found a new DDNS provider. Its simple control page is here https://www.ipnodns.ru/panel.html  
I've added the following code into ipnodns.ru.json file and all seems to work well:
```
{
	"name": "ipnodns.ru",
	"ipv4": {
		"url": "https://ipnodns.ru/cgi-bin/dyndns.cgi?login=[USERNAME]&secret=[PASSWORD]",
		"answer": "ok"
	}
}
```
If possible, please add this provider into the further updates.

**Comment by BKPepe** [comment]
Feel free to create pull request, where you will add it. You can not ask others to do it for you because it would mean that whoever will add it, will be responsible if it does not work and as well, he will need to test it on his side.

**Comment by BKPepe** [comment]
Also, keep in mind that OpenWrt 21.02 is already end of life, thus not supported anymore.
