### ISSUE TITLE
tang: doesn't work

### ISSUE THREAD

**Issue by hadmut** [openwrt/packages#22239]
Maintainer: @tiboris 
Environment: GL.iNet GL-AX1800 4.4.6
Description: Tang doesn't work

I installed the openwrt tang package on a GL.iNET router

# opkg info tang
Package: tang
Version: 7-1
Depends: libc, libhttp-parser, xinetd, jose, bash
Status: install user installed
Section: utils
Architecture: arm_cortex-a7
Size: 8620
Filename: tang_7-1_arm_cortex-a7.ipk
Conffiles:
 /etc/xinetd.d/tangdx c0390bc765d7d1dbce787abcc7b1cc480bdb3f172cb479a0fef0cd128c240d74
Description: Tang is a small daemon for binding data to the presence of a third party.
Installed-Time: 1695892903

and restarted the router. 

xinetd correctly launches tang, but tang itself doesn't work

The tang protocol says (see https://github.com/latchset/tang ) that the API is that on /adv the server must advertise it's list of keys. And this works with normal tang servers, running e.g. on ubuntu. 

But the openwrt version (listening on port 8888) just responds with 404 not found, and even writes into the logfile  /var/log/tangd.log 

```
==================================
Thu Sep 28 12:38:21 EEST 2023:
<unknown> GET /adv => 404 (src/tangd.c:70)
```

possibly /usr/libexec/tangd-keygen has not been run during installation. But when I try to run it manually, I don't know which is the path used by openwrt to store. And I did not find any documentation at all.

**Comment by kirdesde** [comment]
1. GL.iNet GL-AX1800 is not supported by OpenWrt
2. you are using an outdated version, tang isn't  using xinetd nor /usr/libexec/tangd-keygen anymore.
