### ISSUE TITLE
`pymysql`  Recursive dependency！

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#22250]
@commodo
````
Collecting package info: done
tmp/.config-package.in:36491:error: recursive dependency detected!
tmp/.config-package.in:36491:	symbol PACKAGE_python3-pymysql depends on PYTHON3_PYMYSQL_SHA_PASSWORD_SUPPORT
feeds/packages/lang/python/pymysql/Config.in:4:	symbol PYTHON3_PYMYSQL_SHA_PASSWORD_SUPPORT depends on PACKAGE_python3-pymysql
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
````

**Comment by BKPepe** [comment]
Again reported twice? Please, try to wait for a while before screaming and shouting everywhere. That should help you to be more patient. You already it reported in https://github.com/openwrt/packages/commit/9fdff3ea94662653188c3902840e97c35e9f138f#commitcomment-128680904, which is not good place to report such things. You need to create issue, if you want to get resolved (this one you did today) and as well keep the issue template to be able to reproduce (need to be done).
