### ISSUE TITLE
travelmate: Long delay between adding and connecting to an open STA

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#22288]
Maintainer: @dibdot
Environment: OpenWRT 22.03.05

Description:
It takes a number of minutes between adding an open STA and actually connecting to it.

I guess this happens because finding and adding a new open STA and connecting to any available STAs happen separately.

I wonder if right after adding a new open STA if Travelmate should jump right to connecting to that STA rather than waiting for the subsequent processing loop to see it available and then connect to it as a matter of regular processing of all STAs.

**Comment by dibdot** [comment]
Closed with https://github.com/openwrt/packages/commit/81658c58236a050b22dbf08309b637576db1a5c9
