### ISSUE TITLE
travelmate: travelmate shuts VPN interfaces down instead of setting them up

### ISSUE THREAD

**Issue by IeP4nieF** [openwrt/packages#22357]
Maintainer: @\<dibdot>
Environment: (Mediatek MT7628AN ver. 1 eco. 2, TP-Link TL-WR902AC v3, OpenWrt 22.03.5)

Description:

As described [here](https://forum.openwrt.org/t/travelmate-support-thread/5155/761) I set up travelmate on OpenWRT with a wireguard uplink. I set up every travelmate uplink to handle the wireguard-interface. But travelmate does not bring the interface up.

As a workaround I switched of VPN support in travelmate completly and let openwrt bring up the wireguard interface at boot. This works perfect. Now travelmate brings up the uplink interface and everything from LAN is tunneld through wireguard. But this bug should be fixed nevertheless. Let me know what kind of information you need for debugging.
```
Sun Oct  8 23:11:44 2023 daemon.notice netifd: Interface 'WG0' is setting up now
Sun Oct  8 23:11:45 2023 daemon.notice netifd: Interface 'WG0' is now up
Sun Oct  8 23:11:45 2023 daemon.notice netifd: Network device 'WG0' link is up
Sun Oct  8 23:11:46 2023 user.notice firewall: Reloading firewall due to ifup of WG0 (WG0)
Sun Oct  8 23:11:53 2023 user.debug trm-2.1.0[8510]: f_getvpn  ::: iface: WG0, proto: wireguard, device: -, ifacelist: -, infolist: WG0
Sun Oct  8 23:11:53 2023 user.debug trm-2.1.0[8510]: f_getvpn  ::: iface: trm_wwan, proto: dhcp, device: -, ifacelist: -, infolist: WG0
Sun Oct  8 23:12:01 2023 user.debug trm-2.1.0[8510]: f_getval  ::: option: vpniface, result: WG0, uplink_config: @uplink[0]
Sun Oct  8 23:12:01 2023 user.info trm-2.1.0[8510]: take down vpn interface 'WG0/-' (initial)
Sun Oct  8 23:12:02 2023 daemon.notice netifd: Network device 'WG0' link is down
Sun Oct  8 23:12:02 2023 daemon.notice netifd: Interface 'WG0' is now down
```
This config was used before disabling VPN support global:
```
config travelmate 'global'
	option trm_captive '1'
	option trm_proactive '1'
	option trm_netcheck '0'
	option trm_autoadd '0'
	option trm_iface 'trm_wwan'
	option trm_radio 'radio1 radio0'
	option trm_vpn '1'
	option trm_randomize '0'
	option trm_enabled '1'
	option trm_debug '1'
	list trm_vpnifacelist 'WG0'
	option trm_mail '0'

config uplink
	option device 'radio0'
	option ssid '<ssid1>'
	option con_start_expiry '0'
	option con_end_expiry '0'
	option enabled '1'
	option vpn '1'
	option vpnservice 'wireguard'
	option vpniface 'WG0'

config uplink
	option device 'radio1'
	option ssid '<ssid2>'
	option con_start_expiry '0'
	option con_end_expiry '0'
	option vpn '1'
	option vpnservice 'wireguard'
	option vpniface 'WG0'
	option enabled '0'

config uplink
	option enabled '1'
	option device 'radio1'
	option ssid '<ssid3>'
	option con_start_expiry '0'
	option con_end_expiry '0'
	option vpn '1'
	option vpnservice 'wireguard'
	option vpniface 'WG0'
```

**Comment by fire-burner** [comment]
I can confirm the same on a test -Link DIR-859 A3 with 23.05.0-rc4. It also doesn't make any difference, if "Limit VPN processing" is set to wireguard.

`Thu Oct 12 00:59:33 2023 user.info trm-2.1.0[22711]: take down vpn interface 'wireguard/-' (initial)
Thu Oct 12 00:59:33 2023 daemon.notice netifd: Network device 'wireguard' link is down
Thu Oct 12 00:59:33 2023 daemon.notice netifd: Interface 'wireguard' is now down`
