### ISSUE TITLE
nginx-mod-luci: Building image for NanoPi R2S using imagebuilder yields error

### ISSUE THREAD

**Issue by SiNONiMiTY** [openwrt/packages#22378]
![image](https://github.com/openwrt/packages/assets/9588282/08455310-f372-4c3f-a6e7-af6d2f20f4b4)

Trying to update the OpenWRT Snapshot on my NanoPi R2S but I am hit with this error.

It seems there is a package manifest configuration issue for nginx-mod-luci/uwsgi.

**Comment by Ansuel** [comment]
no error just wait a few days... there was a problem with uwsgi compilation caused by a python change.
