### ISSUE TITLE
lm-sensors or luci-app-statistics doesn't show CPU temp

### ISSUE THREAD

**Issue by rdeftery** [openwrt/packages#22461]
Environment: Asus rt-ac58u OpenWrt 23.05.0, r23497-6637af95aa

Description:
I try show temp.
I successfully installed lm-sensors and luci-app-statistics, and no one of them doesn't show temp

```
root@OpenWrt:~# sensors
ath10k_hwmon-isa-a000000
Adapter: ISA adapter
temp1:            N/A

ath10k_hwmon-isa-a800000
Adapter: ISA adapter
temp1:            N/A
```

**Comment by rdeftery** [comment]
I erase config and reinstall openwrt (OpenWrt 23.05.0, r23497-6637af95aa).
I successfully installed luci-app-statistics (from https://openwrt.org/docs/guide-user/luci/luci_app_statistics), but nothing has changed. I still can't see the CPU temperature.

![image](https://github.com/openwrt/packages/assets/126885966/c74aeada-7b34-46d6-bfeb-7fb5012d638e)
![image](https://github.com/openwrt/packages/assets/126885966/ec6bf58f-b809-431f-b92a-342cd6a2b008)

**Comment by brada4** [comment]
You can try running sensors-detect to get non-functional sensors off the list. Seems particular ath10k shows NA in place of temperature number.

**Comment by rdeftery** [comment]
Good day. 
My bad.
I tried reading the temperature sensorы with the wifi turned off.
If the Wi-Fi is turned off, the sensors also do not transmit temperature readings.
After turning on the Wi-Fi, the temperature is read correctly.
![image](https://github.com/openwrt/packages/assets/126885966/d6a91c12-989a-4d52-aaae-b2ee6af57b6b)
