### ISSUE TITLE
snmpd: memory leak on 23.05.0

### ISSUE THREAD

**Issue by yusuka** [openwrt/packages#22467]
Maintainer: @Ansuel
Environment: Openwrt 23.05.0, netgear WAX206, GL.iNet GL-MT1300, Buffalo wsr1166dhp

Description:
After upgrading to 23.05.0 from 22.03.5, snmpd begin to eat lot of memory.
```
CPU:  15% usr  11% sys   0% nic  71% idle   0% io   0% irq   2% sirq
Load average: 0.06 0.02 0.00 3/91 27022
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
16083     1 root     R     147m  60%  27% /usr/sbin/snmpd -Lf /dev/null -f -r
27022 26960 root     R     1392   1%   2% top
```

**Comment by brada4** [comment]
5.9.1-7 fixes the bug. Wait and close the issue in either order.
https://github.com/openwrt/packages/issues/22455

**Comment by yusuka** [comment]
Thank you.
