### ISSUE TITLE
wsdd2: interface selection bug

### ISSUE THREAD

**Issue by levshutov** [openwrt/packages#22520]
Maintainer: @Andy2244, @neheb
Environment: ARMv8, mediatek/mt7622, Linksys E8450, 23.05.0

Description:
Discovery stops working after any interface changes its state when running in single interface mode with -i key.
Solution is here https://github.com/Netgear/wsdd2/pull/46

**Comment by BKPepe** [comment]
What we should do about it, when upstream developers did not take care of your pull request for ~6 months? You can not expect that we will maintain this patch forever.

Try to convince them to look at it or feel free to create pull request.

Nothing else what we can do here. Closing.
