### ISSUE TITLE
tcpdump:kernel 6.1 error on mediatek target

### ISSUE THREAD

**Issue by Gingernut1978** [openwrt/packages#22573]
Maintainer: Felix Fietkau <nbd@nbd.name>
Environment: aarch64 mt7622/mt7986 latest SNAPSHOT

Description: tcpdump not working

```
root@Asus:~# tcpdump
Error relocating /usr/bin/tcpdump: pcap_open: symbol not found
Error relocating /usr/bin/tcpdump: pcap_findalldevs_ex: symbol not found
```

```
root@Asus:~# opkg list-installed libpcap*
libpcap1 - 1.10.4-1
root@Asus:~# opkg list-installed libc
libc - 1.2.4-4
```

**Comment by brada4** [comment]
most likely you installed tcpdump from different release like 23.05.0. They are all 3 base packages, always built together try auc in few days and problem will fade away.

**Comment by Gingernut1978** [comment]
Makes sense. Thanks.
