### ISSUE TITLE
nmap: 22.03 build failed

### ISSUE THREAD

**Issue by muink** [openwrt/packages#22585]
Maintainer: @nunojpg
Environment: Openwrt 22.03

Description:

nmap build failed https://downloads.openwrt.org/releases/faillogs-22.03/x86_64/packages/nmap/

**Comment by BKPepe** [comment]
You will need to wait 24 hours or even maybe 48 hours and it will be fixed for x86_x64, I can see that it is already compiled for mipsel_24kc.
