### ISSUE TITLE
Upgrading NUT to 2.8.1 version in OpenWrt

### ISSUE THREAD

**Issue by Voidstranger** [openwrt/packages#22595]
NUT 2.8.1 is released and it has some pretty nice improvements (for me, especially, because it has feature to pick "subdriver" for UPS manually. It is very helpful for plenty UPSs with messy PID and VID).

Are there some plans to update NUT package for OpenWrt?

**Comment by BKPepe** [comment]
Feel free to create pull request. This seems like feature request for me. You might want to reach OpenWrt community on forum to help you to create PR.
