### ISSUE TITLE
vsftpd: error start to boot system

### ISSUE THREAD

**Issue by build000** [openwrt/packages#2271]
1) error start (boot system), when restart system from LuCI
2) no error start (boot system), when restart system from console
3) this situations is any time, probably any version (test to CC and trunk-DD)
4) generally: vsftpd-3.0.3

**Comment by yousong** [comment]
ping maintainer of vsftpd @obsy ;)

**Comment by obsy** [comment]
Sorry, need more data. What kind of error, what platform? Show configuration file.

**Comment by hnyman** [comment]
old and vague. vsftpd works for me after a reboot from Luci. 
closing. (if the issues is still present, please file more detailed report)
