### ISSUE TITLE
"git pull --rebase" reported "'sh-i18n--envsubst' is not a git command"

### ISSUE THREAD

**Issue by clarkwang** [openwrt/packages#2278]
See following example (tested with openwrt `15.05`):

    root@newifi:~# git pull --rebase
    git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.
    git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.
    root@newifi:~#

The problem is that there's no `git-sh-i18n--envsubst` under `/usr/lib/git-core/`. Seems like a build or packaging problem.

**Comment by clarkwang** [comment]
I'm using `15.05`.

**Comment by tripolar** [comment]
should be fixed with df95e9a5932c8e2e0af97f4bed774ebc6534a390
