### ISSUE TITLE
Sync the main branch today (2023-12-06), make menueconfig error: recursive dependency detected!

### ISSUE THREAD

**Issue by andersling** [openwrt/packages#22837]
### Describe the bug

openwrt_2312$ make menuconfig 
tmp/.config-package.in:138254:error: recursive dependency detected!
tmp/.config-package.in:138254:	symbol PACKAGE_prometheus-node-exporter-ucode depends on PACKAGE_ucode
tmp/.config-package.in:38903:	symbol PACKAGE_ucode is selected by PACKAGE_uspotfilter
tmp/.config-package.in:124625:	symbol PACKAGE_uspotfilter is selected by PACKAGE_uspot
tmp/.config-package.in:94297:	symbol PACKAGE_uspot depends on PACKAGE_uhttpd
tmp/.config-package.in:116814:	symbol PACKAGE_uhttpd is selected by PACKAGE_prometheus-node-exporter-ucode
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

please fix it ,guys, thanks!

### OpenWrt version

r23966-6bf8193b25

### OpenWrt release

 20231206 latest

### OpenWrt target/subtarget

master

### Device

Raspberry Pi Compute Module 4 Rev 1.0

### Image kind

Self-built image

### Steps to reproduce

just do a sync feed, and make menuconfig ,and the message will show:

openwrt_2312$ make menuconfig 
tmp/.config-package.in:138254:error: recursive dependency detected!
tmp/.config-package.in:138254:	symbol PACKAGE_prometheus-node-exporter-ucode depends on PACKAGE_ucode
tmp/.config-package.in:38903:	symbol PACKAGE_ucode is selected by PACKAGE_uspotfilter
tmp/.config-package.in:124625:	symbol PACKAGE_uspotfilter is selected by PACKAGE_uspot
tmp/.config-package.in:94297:	symbol PACKAGE_uspot depends on PACKAGE_uhttpd
tmp/.config-package.in:116814:	symbol PACKAGE_uhttpd is selected by PACKAGE_prometheus-node-exporter-ucode
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by f00b4r0** [comment]
@dhewg 

> https://github.com/openwrt/packages/blob/33512191380328512aea0e9f787456b3be18686b/utils/prometheus-node-exporter-ucode/Makefile#L56
> 
> 
> try changing `DEPENDS:=$(PKG_NAME) $(3)` to `DEPENDS:=+$(PKG_NAME) $(3)`

**Comment by dhewg** [comment]
No, that's not wanted. The additional collectors should only be select-able if the main package is selected. And that also prevents useless .config spam.

The issue seems related to `ucode-mod-*` as those have `ucode` as hard dependency. I have selects on some of those mods, but no direct ucode dependency nor select, but you do. Removing the two `+ucode` entries from uspot seems to solve this. Those shouldn't be needed anyway, as any ucode-mod-* drags it in already.

**Comment by f00b4r0** [comment]
@jow- what do you think?
