### ISSUE TITLE
PPPD 2.4.9 cannot send PADT message when disconnected

### ISSUE THREAD

**Issue by KuoEuran** [openwrt/packages#22913]
Hi,
I found that PPPD 2.4.9 delete sendPADT.patch and add conn->discoverySocket=-1 in discovery() function, but after I recover the patch, it also cannot sendPADT message when disconneced pppoe-wan.
PS: 1. it can send PADT message in PPPD 2.4.7.
2. PADR AND PADI message successfully sent when connected to pppoe wan.

**Comment by BKPepe** [comment]
This is wrong repository to report that. Closing as invalid. You should take a look where pppd is located/present in the repository. Thats not packages repository. I am so sorry.
