### ISSUE TITLE
mosquitto-ssl - Segmentation fault on subscribe

### ISSUE THREAD

**Issue by ASerbinski** [openwrt/packages#22977]
The following config works perfectly on mosquitto 1.6.15 (Rocky Linux 8) and mosquitto 2.0.14 (Fedora), but results in frequent Segmentation fault on OpenWRT 23.05.2;

```
max_inflight_messages 1

listener 8883
cafile /etc/mosquitto/ca.crt
certfile /etc/mosquitto/dom.crt
keyfile /etc/mosquitto/dom.key

require_certificate true

log_dest syslog

log_type error
log_type warning
log_type notice
log_type information
log_type all

allow_anonymous false
password_file /etc/mosquitto/pwfile
```

The segfault seems to always happen when the client sends a SUBSCRIBE;

```
Sat Dec 23 14:14:19 2023 daemon.debug mosquitto[12688]: 1703358859: Received SUBSCRIBE from {redacted}
Sat Dec 23 14:14:19 2023 daemon.debug mosquitto[12688]: 1703358859: 	prop1/thermostat/furnace/log-ac1/$format (QoS 1)
```

The SUBSCRIBES are sent while the client is connecting. It does some wildcard and recursive subscriptions, and somewhere in the process it often crashes.

I'm not sure how to debug this, since segmentation fault doesn't really give much to go on. Its also not going to be an upstream bug since the same configuration works on other machines without the segmentation fault.

**Comment by brada4** [comment]
backtrace or at least a kernel message of the crash?

**Comment by brada4** [comment]
(and which architecture, and versions of all packages in backtrace)

**Comment by ASerbinski** [comment]
I'll need instructions on how to collect those. Nothing is appearing in the kernel or system logs with respect to the crash, and if I start it from terminal, it outputs simply "Segmentation fault".

**Comment by brada4** [comment]
kernel log via dmesg command shows segfaults, including disk file and offset in file it happened.

**Comment by ASerbinski** [comment]
Nothing there.
And wouldn't that normally be just for crashes within the kernel?

**Comment by brada4** [comment]
qualcommax/ipq807x
Dynalink DL-WRX36

did you install package from default repos? Like opkg
`opkg list-installed` will show versions.

**Comment by ASerbinski** [comment]
Everything is from default repos.

**Comment by brada4** [comment]
Looks sane, like all currentoackages intact.

**Comment by ASerbinski** [comment]
Exactly. So where do I go from here? Any way you know of to coerce it into handing over a trace?

**Comment by brada4** [comment]
strace, gdb, check wiki.

**Comment by ASerbinski** [comment]
Hmm. It may have been an issue with mosquitto 2.0.17. I installed 2.0.18 from the snapshot repository and I'm having a hard time reproducing the problem now.

**Comment by brada4** [comment]
ping @neheb

**Comment by neheb** [comment]
You want it back ported?

**Comment by ASerbinski** [comment]
It would probably make a lot of sense. I've been trying for over an hour to reproduce the crash with 2.0.18 and have failed. With 2.0.17, I could make it happen within 3 tries over maybe 30 seconds.

**Comment by neheb** [comment]
done.

**Comment by BKPepe** [comment]
Btw, why are you trying to post something or everything, where there isnt anything related to mosquitto? You can see it even yourself that it was not helpful.

Backported even to OpenWrt 22.03. 

Closing as I think 4 days was enough to reproduce it and test the version 2.0.18 on the stable branches.
