### ISSUE TITLE
avahi: Warning about nss-mdns

### ISSUE THREAD

**Issue by cherinyy** [openwrt/packages#22980]
Maintainer: @thess
Environment: OpenWrt 23.05.2 on mediatek/filogic

Description:

I noticed a warning in the logs:

```
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
```

`nss-mdns` does not appear to be present in the OpenWrt packages feed now.

So maybe consider disabling this warning for OpenWrt until `nss-mdns` is supported?

**Comment by predators46** [comment]
@cherinyy 

can you try this and build it

https://github.com/predators46/nss-mdns

**Comment by cherinyy** [comment]
No response was received for a long time.

**Comment by Vitaliy86** [comment]
Problem not solved

**Comment by luxflow** [comment]
as i know nss-mdns cannot be used because of musl which openwrt depends on
https://wiki.musl-libc.org/future-ideas.html#mDNS_and_alternate_hostname_database_backends
