### ISSUE TITLE
Oskari Rauta: Support for ZBT WE-826 ?

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#2305]
Hi, I received this info:
 OpenWrt <openwrt-devel@lists.openwrt.org>
CC openwrt-tickets@lists.openwrt.org
Jan 23 um 2:58 PM
#19996: Add support for ZBT WE-826
-----------------------------+--------------------------------
  Reporter:  oskari.rauta@…  |      Owner:  developers
      Type:  enhancement    |    Status:  reopened
  Priority:  highest        |  Milestone:  Chaos Calmer 15.05
Component:  base system    |    Version:  Trunk
Resolution:                  |  Keywords:  zbt,we
-----------------------------+--------------------------------
Changes (by v.kalachikhin@…):

* status:  closed => reopened
* resolution:  not_a_bug =>

--
Ticket URL: <https://dev.openwrt.org/ticket/19996#comment:25>
OpenWrt <http://openwrt.org>
Opensource Wireless Router Technology
-------

Are you working in this one ? If yes, may be, I can help a bit, as I am using the WE-826:
I received a complete build-root (src; r45826) from ZBT. And I can compile working image from it.
Only problem so far: sysupgrade does not work.

**Comment by yousong** [comment]
Discussion about support of new devices should be posted to mailing lists for timely responses.  I am going to close this one.
