### ISSUE TITLE
ksmbd-server: Shared files/directories are not visible in root folder of the share

### ISSUE THREAD

**Issue by sppmasterspp** [openwrt/packages#23088]
Ksmbd-server Version 3.4.8-1

Maintainer: @\common packages maintainers

```
ubus call system board
{
        "kernel": "6.1.71",
        "hostname": "QNAP",
        "system": "ARMv8 Processor rev 4",
        "model": "QNAP 301w",
        "board_name": "qnap,301w",
        "rootfs_type": "squashfs",
        "release": {
                "distribution": "OpenWrt",
                "version": "SNAPSHOT",
                "revision": "r24887+2-c43e96d28f",
                "target": "qualcommax/ipq807x",
                "description": "OpenWrt SNAPSHOT r24887+2-c43e96d28f"
        }
}

```

Description:
I saw there were a lot of ksmbd changes (commits) in [kernel 6.1.71](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.71).
Having compiled a new build with 6.1.71 I cannot access the root directory of shared disk. Actually it opens but is shown as empty on all devices.
![981f66beb39846b25ae20ff56cb1f3593ff2c532](https://github.com/openwrt/packages/assets/46223847/08001e22-8a59-409a-b925-1c85d59c2a65)

The files are still there
![420b7c0b6ee21f0938f6cf1988fb0a6c3646068f_2_689x408](https://github.com/openwrt/packages/assets/46223847/1a83ae9c-e30b-4311-b930-31f7b90212b6)

but not visible in file explorers on different devices.
Writing to the root shared folder is not possible either. I can write to the down directories if I access them directly via address bar.
It worked normally with kernel 6.1.69.
I can view and access the mounted device directories with `cd` and `ls` commands via router SSH console and I can open some shared directories down the root directory from Windows File Explorer typing the address in the address bar.

The [discussion on OpenWrt forum](https://forum.openwrt.org/t/ksmbd-samba3-4-alternative-ex-cifsd-smbd-package-support-thread/51695/329?u=sppmaster).

**Comment by sppmasterspp** [comment]
The developer said this was known issue resolved in newer versions.

**Comment by egc112** [comment]
New kernel version is out and avalaible : https://github.com/openwrt/openwrt/pull/14383 
Maybe this solves your problem?

**Comment by sppmasterspp** [comment]
Yes, recompiled this morning with latest changes and all is OK.
The issue is fixed with https://github.com/openwrt/packages/pull/23095. Thanks a lot guys.

**Comment by sppmasterspp** [comment]
Fixed.
