### ISSUE TITLE
Travelmate - How can i control OpenVPN, when its L2 Interface is bridging?

### ISSUE THREAD

**Issue by velainur** [openwrt/packages#23119]
Hi,

Is there any way to control the OpenVPN L2 tap interface when the travelmante becomes "connected"?
Which interface must i configure inside the "VPN Processing" option? must i add "lan"? (lan is allways on, since its a bridge interface with wifi, xe)

Regards,

**Comment by brada4** [comment]
it is a forum question, not bug

**Comment by dibdot** [comment]
Check the online readme and ask in the forum.
