### ISSUE TITLE
`<block-mount>: ` on r8000 - Packages for block-mount found, but incompatible with the architectures configured

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/packages#23175]
![Screenshot_select-area_20240127125518](https://github.com/openwrt/packages/assets/12752816/93f868fe-4f3b-490e-afc9-bc6a3d11ac33)

**Comment by BKPepe** [comment]
You removed issue template without that, we can not help you.

**Comment by Mile-Lile** [comment]
I apologize, didn't know what is the right place to post...
