### ISSUE TITLE
mosquitto:  persistence database is not saved

### ISSUE THREAD

**Issue by myokaski** [openwrt/packages#23187]
Maintainer: @karlp @neheb
Environment: OpenWrt 23.05.2

Description:
mosquitto 2.0.18. Even if enabled in config via ```persistence true```, persistence database file is not created.

I guess this is because of ```-DWITH_PERSISTENCE=OFF``` flag introduced by this commit: 
https://github.com/openwrt/packages/commit/aa89f847c673343af0cde4dbd9535a63272f7f14

Is there a good reason for that?

**Comment by neheb** [comment]
No. It needs to be reenabled.

**Comment by myokaski** [comment]
@neheb What can I do for that to happen?

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/22686

**Comment by neheb** [comment]
backported to 23.05.

**Comment by karlp** [comment]
Note my other comments on that commit https://github.com/openwrt/packages/pull/22686#discussion_r1439082115 I tried telling you about this earlier.
