### ISSUE TITLE
Problem on compiling wxbase library on trunk, MVEBU platform

### ISSUE THREAD

**Issue by mattheweli** [openwrt/packages#2330]
When I was trying to compile aMule for the trunk version of OpenWRT, I faced the following error regarding wxBase library:

`./include/wx/debug.h:233:38: note: in expansion of macro 'wxCHECK2_MSG'
 #define wxCHECK_RET(cond, msg)       wxCHECK2_MSG(cond, return, msg)
                                      ^
./include/wx/module.h:71:9: note: in expansion of macro 'wxCHECK_RET'
         wxCHECK_RET( dep, wxT("NULL module dependency") );
         ^
/home/matteo/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.2.0_musl-1.1.12_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/5.2.0/../../../../arm-openwrt-linux-muslgnueabi/lib/crt1.o: In function ``_start_c':
/home/matteo/openwrt/build_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.2.0_musl-1.1.12_eabi/musl-1.1.12/crt/crt1.c:17: undefined reference to ``main'
collect2: error: ld returned 1 exit status
make[3]: *** [.pch/wxprec_basedll/wx/wxprec.h.gch] Error 1
make[3]: Leaving directory ``/home/matteo/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.12_eabi/wxGTK-2.8.12'
make[2]: *** [/home/matteo/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.12_eabi/wxGTK-2.8.12/.built] Error 2
make[2]: Leaving directory ``/home/matteo/openwrt/feeds/oldpackages/libs/wxbase'
make[1]: *** [package/feeds/oldpackages/wxbase/compile] Error 2
make[1]: Leaving directory ``/home/matteo/openwrt'
make: *** [package/amule/compile] Errore 2`

I think this could be related to MUSL toolchain; already discussed in the forum:
​https://forum.openwrt.org/viewtopic.php?id=62342

**Comment by yousong** [comment]
`wxbase` is part of oldpackages, so it's currently in un-maintained state.  I am closing this one.
