### ISSUE TITLE
dawn: Crashes because of outdated version

### ISSUE THREAD

**Issue by nj-banks** [openwrt/packages#23326]
Maintainer: @PolynomialDivision 
Environment: Official 23.05.2, BPi-R3

Description:

Dawn is crashing with segmentation fault on 23.05.2 because the package version is out of date. Please update Dawn to the latest version.

The following commits are on the master branch but not on openwrt-23.05:

https://github.com/openwrt/packages/commit/6c5c99d206e62b44de1bbe60b66deba459396508
https://github.com/openwrt/packages/commit/d9acb54dc49b63ea3b473d72543c76c02e93eb2d

Related: https://github.com/berlin-open-wireless-lab/DAWN/issues/235

**Comment by BKPepe** [comment]
https://github.com/openwrt/packages/commit/a062c2a510459c01c67f725333d7623f2b1c39ed
https://github.com/openwrt/packages/commit/f83e01a4be8cdad225c6621a06c02c6755a845b9
