### ISSUE TITLE
Openconnect: camouflage + non 443 port. Incorrect executing

### ISSUE THREAD

**Issue by itdoginfo** [openwrt/packages#23364]
Maintainer: @neheb @vgaetera @dhewg @rsalvaterra (Sorry guys, you're the people who have been committing for the last year)

Environment: OpenWrt 23.05, OpenWrt SNAPSHOT r25115-7181eb9f81 (11.02.2024)

Description:
I use openconnect server with camouflage and 8443 port. And running a client on openwrt.

Config client:
```
config interface 'vpn0'
	option proto 'openconnect'
	option server 'test.com/?NUqVl3YLuX'
	option port '8443'
	option username 'test'
	option password 'uxNCieYKh6'
```

Log:
```
Sun Feb 11 09:12:25 2024 user.notice openconnect: executing 'openconnect 'test.com/?NUqVl3YLuX:8443' '-i' 'vpn-vpn0' '--non-inter' '--syslog' '--script' '/lib/netifd/vpnc-script' '-u' 'test' '--passwd-on-stdin''
```

As you can see, the port is substituted after the URI. And in this case, there is no connection.
I tested this on the last stable and dev version.

It's good working on port 443.

Thanks.

**Comment by nmav** [comment]
Adding anything beyond the server in the server option will not work. We will need to change the openconnect scripts and possibly to the lua interface for this to work.

An option that is backwards compatible is to allow an https URI on the server field and if found to skip the server:port construction.

**Comment by nmav** [comment]
@itdoginfo does https://github.com/openwrt/packages/pull/24109 work for you?

**Comment by root149** [comment]
24.10  option uri 'test.com:8433/?NUqVl3YLuX' 
notwork
