### ISSUE TITLE
mariadb missing libfmt dependency

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/packages#23413]
I came up with a strange issue with mariadb, build failed on the beginning due to missing libfmt. I checked and even re-built my libfmt, and still it wasn't able to find it. To solve the issue, I made it to use bundled libfmt.

Not sure, but might be related to this: https://jira.mariadb.org/browse/MDEV-27965

Maintainer: @mhei @neheb
Environment: x86_64, latest git

**Comment by oskarirauta** [comment]
well, that fixed it on my end; but don't we want to utilise system's libfmt instead? Can't help with that, since I didn't see clear reason why it didn't work, but current package tries to use libfmt from system.

**Comment by neheb** [comment]
I started failing after libfmt was updated. seems mariadb doesn't work with newer fmt.

**Comment by oskarirauta** [comment]
Okay.. Maybe I'll then PR it, unless you already did..

**Comment by krant** [comment]
It seems https://github.com/fmtlib/fmt/issues/3835 is the reason

**Comment by mhei** [comment]
AS noted, I think we can close this since #23380 was merged. Please re-open if issue still persists.
