### ISSUE TITLE
Prosody 0.9.9 cannot write /dev/urandom

### ISSUE THREAD

**Issue by dzavy** [openwrt/packages#2342]
This is a known issue (https://prosody.im/issues/issue/585), should be fixed in 0.9.10.

root@00E0C561182D:~# /etc/init.d/prosody start
lua: /usr/lib/prosody/util/uuid.lua:27: Unable to obtain a secure random number generator, please see https://prosody.im/doc/random (/dev/urandom: Permission denied)
stack traceback:
        [C]: in function 'error'
        /usr/lib/prosody/util/uuid.lua:27: in function 'uuid_gen'
        /usr/lib/prosody/core/hostmanager.lua:77: in function 'activate'
        /usr/lib/prosody/core/hostmanager.lua:44: in function '?'
        /usr/lib/prosody/util/events.lua:67: in function 'fire_event'
        /usr/lib/prosody/../../bin/prosody:337: in function 'prepare_to_start'
        /usr/lib/prosody/../../bin/prosody:403: in main chunk
        [C]: ?

**Comment by MikePetullo** [comment]
This should be fixed, as prosody 0.9.10 no longer opens /dev/urandom for writing, only reading.

**Comment by diizzyy** [comment]
@dzavy 
Still an issue?
