### ISSUE TITLE
Openthread-br: luci app not found

### ISSUE THREAD

**Issue by kaizirlewagen** [openwrt/packages#23435]
I build with the latest master and try to test openthread-br. For me the build, the system settings with a nordic device works fine. But i dont't find the LuCI app for openthread-br through the webinterface. There will be no item Thread under Network.

I find the comment in Readme.md 

LuCI
Creating a network in LuCI appears to be broken for the moment.

So, i don't find any informations about the problem. Can someone post whats the problem with?

I try to test and debug but i am new with LuCI packages, so i don't find some errors at my device.

Thx.

**Comment by brada4** [comment]
There is no such luci app in existence.

**Comment by kaizirlewagen** [comment]
For me.... the luci-app-openthread from the Makefile is not wordking anymore or do you know whats wrong with this package?

**Comment by kaizirlewagen** [comment]
So, i don't see the Thread entry under Network. I build the firmware from the master by myself. So, i wonder that no webgui for thread is visible. Is something missing in my build?

The package must be visible or is this also an error of the package?

**Comment by brada4** [comment]
https://github.com/openwrt/packages/tree/master/net/openthread-br
it is the interface protocol like dhcp vs static.

**Comment by kaizirlewagen** [comment]
That is clear, i can compile the package, and i can choose it via make menuconfig. I choose also the luci-app-openthread. I can compile with make.

But if i connect to the web gui i don't see Threads under Network menu.

**Comment by kaizirlewagen** [comment]
The problem was that i have missing dependencies while building the firmware. At make menuconfig some "lua" packages were not selected.
