### ISSUE TITLE
lrzsz: not building

### ISSUE THREAD

**Issue by feamsr00** [openwrt/packages#23468]
https://openwrt.org/packages/pkgdata/lrzsz
https://github.com/openwrt/packages/tree/openwrt-22.03/utils/lrzsz
Maintainer: @dhewg
Environment: mipsel_24kc, 22.03

Description:
Hello! Went to go use the imagebuilder today and noticed it died on a missing package in my config: lrzsz. Dug a bit and noticed that it wasn't in the [openwrt download repo](https://downloads.openwrt.org/releases/22.03.6/packages/mipsel_24kc/packages/) because of what looked like a build error. 
https://downloads.openwrt.org/releases/faillogs-22.03/mipsel_24kc/packages/lrzsz/

Not sure how long its been broken: found this https://github.com/openwrt/openwrt/issues/13836 (but I think my build worked in Dec, maybe)

Tried to see if I could find an old prebuilt package, but the whole tree, even back to 22.0 (and beyond), has a [build date of today](https://downloads.openwrt.org/releases/22.03.0/packages/mipsel_24kc/packages/)?

**Comment by sbwml** [comment]
yep, I had the same problem building x86_64 and aarch64 (it happened occasionally, it didn't error on every build) until I replaced it with the 0.12.20 version and never had the problem again.

**Comment by BKPepe** [comment]
Fail log is not available anymore, closing.

**Comment by ynezz** [comment]
Probably related https://github.com/openwrt/packages/issues/25543
