### ISSUE TITLE
ksmbd-utils missing

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/packages#23471]
Maintainer: @neheb @Andy2244 
Environment: (ARM/bcm53xx/generic, R8000, OpenWrt SNAPSHOT r25222)

Description:
no ksmbd-utils 

```
root@R8000:~# opkg install ksmbd-utils
Unknown package 'ksmbd-utils'.
Collected errors:
 * opkg_install_cmd: Cannot install package ksmbd-utils.

```

**Comment by kouhei-ioroi** [comment]
Hello @Mile-Lile .

I was in the same situation. (Environment: (x86/64, OpenWrt 23.05.2 r23630-842932a63d))
Apparently, ksmbd-utils has been merged into ksmbd-server.
![image](https://github.com/openwrt/packages/assets/25764819/10bb4a8d-e5b8-4b47-810b-aaa285bdb557)
When I try to install ksmbd-utils_3.4.5-4_x86_64.ipk I get a conflict warning with ksmbd-server.

I hope this helps. thank you.
