### ISSUE TITLE
luci-app-mwan3 spamming syslog

### ISSUE THREAD

**Issue by psyborg55** [openwrt/packages#2349]
the number of mwan3 configured interfaces equals to number of error messages each 5 seconds. it happens on main page and mwan overview page so I guess it has something to do with MWAN Interface Live Status

more info: https://dev.openwrt.org/ticket/19419

**Comment by hnyman** [comment]
cc to maintainers of luci-app-mwan3 and mwan3
@arfett @Adze1502

**Comment by arfett** [comment]
I'll look at this. Eventually.

**Comment by psyborg55** [comment]
replacing all "uci -p" with "uci -q -p" in mwan3.lua silences output of these messages to syslog. is there any better solution to the problem that would affect script efficiency?

**Comment by arfett** [comment]
@psyborg55, If you can allow me SSH to your router I can take a look. E-mail me ch i p d ank ly at gm ail.co m

**Comment by psyborg55** [comment]
found a solution meanwhile and opened PR https://github.com/openwrt/packages/pull/3986
