### ISSUE TITLE
dnsproxy update?

### ISSUE THREAD

**Issue by PerkelSimon** [openwrt/packages#23534]
Maintainer: @1715173329 
Environment: (arm_cortex-a9_vfpv3-d16, model, OpenWrt master, 23.05)

Description:
the new version dnsproxy_0.65.0-1 is up, it would be great to update it
thanks

**Comment by brada4** [comment]
release notes show requirement bump only.  which part of that is "great"?

https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.65.0

**Comment by 1715173329** [comment]
And even we don't have Go 1.21.7 in tree.

**Comment by BKPepe** [comment]
Related to https://github.com/openwrt/packages/issues/23541
