### ISSUE TITLE
tor: Version 4.7.10 in 22.03 is considered insecure by the network

### ISSUE THREAD

**Issue by peci1** [openwrt/packages#23546]
Maintainer: @rsalvaterra @BKPepe @neheb 
Environment: Turris Omnia, Turris OS 7.0.0 beta based on OpenWRT 22.03, Tor 0.4.7.10 from standard openwrt repo

Description: I received this email from eol-relays@torproject.org:

> You are running a Tor relay, which is great

> However, that relay's Tor version is obsolete, and because of old bugs, we will soon cut relays and bridges running that version out of the network. Please consider upgrading!

Can I ask for backporting a version that is not considered insecure by the network?

**Comment by BKPepe** [comment]
Sure, I will look into it. Thanks for reporting. Just ask Turris guys to run a new build for you and release it into HBT branch.

**Comment by peci1** [comment]
Thanks! 

> Just ask Turris guys to run a new build

When should I ask them? After you do the release? Or now?

**Comment by BKPepe** [comment]
Backported. Hopefully, it would be enough.
You can see it here: https://github.com/openwrt/packages/commits/openwrt-22.03/?since=2024-02-27&until=2024-02-27

Tor is now synced with all OpenWrt stable releases (OpenWrt 22.03, OpenWrt 23.05 and OpenWrt master).

**Comment by peci1** [comment]
Great, that was lightning-fast! Thanks a lot.

**Comment by BKPepe** [comment]
You are welcome. I am ready to help, if I can and if there is time.
