### ISSUE TITLE
travelmate: Tries to connect to wireless when wired is connected

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#23623]
Maintainer: @dibdot

If I have a router with a wan port defined and that port is plugged in to the local network and has link and an IP address, etc. should travelmate still be trying to connect using a WiFi SSID?

If not, what is supposed to suppress that as I have a (23.05) installation here that seems to be trying to connect to wireless even though it has a connection on it's Ethernet wan port.

**Comment by dibdot** [comment]
Please discuss such questions in the forum.
