### ISSUE TITLE
VPN flapping

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#23643]
I am experiencing constant VPN flapping.  It seems to be caused by this line:

https://github.com/openwrt/packages/blob/5ecbe07978f788535a55b15778e1c86a55bb6a8e/net/travelmate/files/travelmate.sh#L238

My experience is that this causes the VPN to flap because the next time this function is called, the file is missing and so the following block is run: https://github.com/openwrt/packages/blob/5ecbe07978f788535a55b15778e1c86a55bb6a8e/net/travelmate/files/travelmate.sh#L205-L220
which causes the VPN to taken down for no useful reason.

It would seem that we only want to remove that file when `rc==1` (i.e. the VPN was taken down) in either of these cases:
https://github.com/openwrt/packages/blob/5ecbe07978f788535a55b15778e1c86a55bb6a8e/net/travelmate/files/travelmate.sh#L225-L235
wouldn't we?

**Comment by dibdot** [comment]
Thanks, fixed with https://github.com/openwrt/packages/commit/b8c47eae98929ea61d124af0e554daad8cc4feae
