### ISSUE TITLE
Missing content in vpnc-scripts-Package

### ISSUE THREAD

**Issue by toxic-tonic** [openwrt/packages#2367]
Hi,

I tried zu install a VPNC enabled Router on a r48648 (todays snapshot). Unfortunatelly the vpnc-scripts -package seams to have no vpnc-script in it. on the old (stable) release the script was in there (when uncompressed on ordinary linux/windows) but not extracted (without any errors) on openwrt (nither while installing with opkg nor when uncompressing manualy with tar).

Thanks for checking!  :)

Best regards

Toxic

**Comment by nmav** [comment]
Not sure how I can help you with the information you provide. You'd better check your build process and see why the file is not included.
