### ISSUE TITLE
Https-dns-proxy Adding DeCloudUs DNS servers

### ISSUE THREAD

**Issue by PerkelSimon** [openwrt/packages#23703]
@stangri 

It would be great to add these servers, some are free to use and pretty good.
DoH, no log, dnssec, filter. Degoogled.
Thanks

**Comment by stangri** [comment]
First of all, the predefined providers are part of the luci-app-https-dns-proxy, not the principal package, so I'll be closing this.

Secondly, you can do that easily, all the providers are defined in the json files: https://github.com/openwrt/luci/tree/master/applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers
