### ISSUE TITLE
Lighttpd directory listening bug in 1.4.74-1 version

### ISSUE THREAD

**Issue by Loafter** [openwrt/packages#23707]
Looks like we have bug with directory listening feature 
it fixed in next version
https://redmine.lighttpd.net/issues/3242

**Comment by BKPepe** [comment]
Which OpenWrt version do you have? It is unclear from your post. There was issue template, which you completely removed. We do have Lighttpd version 1.4.75 in the master branch.

**Comment by Loafter** [comment]
OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-24.073.29889-cd7e519
![изображение](https://github.com/openwrt/packages/assets/10071077/43405368-8bb5-42e6-abfc-aa6306cf257f)

**Comment by Loafter** [comment]
![изображение](https://github.com/openwrt/packages/assets/10071077/b2da1e2a-eb9b-4863-9289-c44adad40b11)

**Comment by Loafter** [comment]
> Which OpenWrt version do you have? It is unclear from your post. There was issue template, which you completely removed. We do have Lighttpd version 1.4.75 in the master branch.

![изображение](https://github.com/openwrt/packages/assets/10071077/1e6c4a74-0bf0-4442-98f4-4b3bd0289938)

**Comment by gstrauss** [comment]
Sorry for the regression.  #23724 and #23725 filed for backports.

**Comment by BKPepe** [comment]
- OpenWrt 23.05: ed3cba66e18632197e862b94c04ea2fe21fbc24f
- OpenWrt 22.03: 5a20abc059c72e4c2c27e1a5ef2a1225559e19f8

**Comment by gstrauss** [comment]
@BKPepe Thank you for the correction.
