### ISSUE TITLE
htop: compiling with support for cpu temp does not add libsensors5 as a dep

### ISSUE THREAD

**Issue by graysky2** [openwrt/packages#23700]
Maintainer: @champtar 
Environment: flogic/glinet_gl-mt6000, latest snapshot

Description:  Building `htop` with `Compile Htop with lm-sensors support` does not add a dependency of `libsensors5` which is needed to get the functionality.

**Comment by brada4** [comment]
Existing behaviour is documented upstream.

**Comment by BKPepe** [comment]
@brada4 Maybe, it would be great if you add reference to it, so we dont need to look at it and waste our time to find that information on the Internet.

**Comment by graysky2** [comment]
I think I figured out the syntax to add a depends with a conditional.  See https://github.com/openwrt/packages/pull/23704

Closing this.

**Comment by brada4** [comment]
Reference : sensors support opens sensors lib if that is installed on target. Additional dependency is excessive.
https://github.com/htop-dev/htop?tab=readme-ov-file#linux
