### ISSUE TITLE
nano: ucode syntax highlighting works only for template files

### ISSUE THREAD

**Issue by eric-j-ason** [openwrt/packages#23761]
Maintainer: @hnyman
Environment: master

Description:

The current syntax highlighting rules are applied to file extensions `uc` (scripts) and `ut` (templates):

https://github.com/openwrt/packages/blob/d8a574f7f0eb2f5970119a2b0527048583054180/utils/nano/files/ucode.nanorc#L3

However, the actual rules are correct only for template files, as they include things like template string expressions, and thus break the highlighting for scripts.

**Comment by jow-** [comment]
Start the `.uc` script with `#!ucode` or `#!/usr/bin/env ucode` and it should work correct.

**Comment by eric-j-ason** [comment]
Here is an example:

```
#!/usr/bin/env ucode

print("Hello, world!\n");
```
<img width="338" alt="bild" src="https://github.com/openwrt/packages/assets/75301977/68bd987f-d092-4548-b9c1-1b5b97d45983">

An example [in the wild](https://github.com/openwrt/openwrt/blob/d4a40827baf010763a1bf60a6435a5ca7da7ea62/package/network/config/wifi-scripts/files/usr/share/hostap/wdev.uc) looks like this:

<img width="792" alt="bild" src="https://github.com/openwrt/packages/assets/75301977/f01dd822-7a6a-4549-b477-7d0bec4bea9c">

**Comment by hnyman** [comment]
> can't reproduce a problem from the given description. Can you provide an example file and a screenshot?

@jow- 
I can reproduce it with up-to-date master build: 

Of the 5 .uc files in `/usr/share/hostap/` three get syntax highlighted just fine, but two do not. The failing ones are those with shebang: `wdev.uc` and `wifi-detect.uc`
Removing (or commenting out) the shebang from the .uc file enables syntax highlighting. 
The shebang doesn't even need to be a full shebang, but just having "#!" there prevents highlighting.

```
root@router6000:/usr/share/nano# ls -1 /usr/share/hostap/*uc
/usr/share/hostap/common.uc
/usr/share/hostap/hostapd.uc
/usr/share/hostap/wdev.uc
/usr/share/hostap/wifi-detect.uc
/usr/share/hostap/wpa_supplicant.uc
```

Ok:
![image](https://github.com/openwrt/packages/assets/7926856/654491e8-0a33-4cb8-944b-18ea1cc031e8)

Failing file wdev,uc
![image](https://github.com/openwrt/packages/assets/7926856/2aa4f8ca-90eb-480b-a28d-c7747a6e66dd)

Removed shebang:
![image](https://github.com/openwrt/packages/assets/7926856/370c3a9c-5564-4c29-a36a-c79901b02749)

Extra # in shebang to invalidate it:
![image](https://github.com/openwrt/packages/assets/7926856/b3cc9122-34da-4206-9ef7-942133140cfb)


The behaviour seems strange, as the filename based syntax should be the primary selection criteria and header just a fallback.

I didn't figure out what is wrong with the header def.

**Comment by jow-** [comment]
This should fix it:

```diff
diff --git a/utils/nano/files/ucode.nanorc b/utils/nano/files/ucode.nanorc
index 96c7848e2..647f21d85 100644
--- a/utils/nano/files/ucode.nanorc
+++ b/utils/nano/files/ucode.nanorc
@@ -43,7 +43,7 @@ color ,green "[[:space:]]+$"
 
 # Text outside template directives
 color slate start="[}%#]\}" end="\{[{%#]"
-color slate start="^#!" end="\{[{%#]"
+color slate start="^#!.*(\<utpl\>|[[:space:]]-[[:alnum:]]*T[[:alnum:]]*\>)" end="\{[{%#]"
 color slate "^([^{%#}]|\{[^{%#]|[%#}][^}])+\{[{%#]"
 
 # Template tags
```

**Comment by eric-j-ason** [comment]
> This should fix it:

A quick test indicates that this works. At least keywords and strings get highlighted.

<img width="997" alt="bild" src="https://github.com/openwrt/packages/assets/75301977/de6ae586-267e-47e7-ae7c-0f9093938d01">
