### ISSUE TITLE
new package request: SoftEtherVPN

### ISSUE THREAD

**Issue by build000** [openwrt/packages#2376]
As the topic.
The project worthy of attention, because it gets better transfers, despite the identical encryption as openvpn. Openvn is just one of many types of vpn which supports the assumption softether.
https://github.com/SoftEtherVPN/SoftEtherVPN/

**Comment by plntyk** [comment]
please make a pull request or ask if they can create an OpenWrt package

**Comment by yousong** [comment]
Close this as softethervpn is now in this repo, apart from the fact that solving libreadline host requirement is still on the way...
