### ISSUE TITLE
snort3: does not appear in .config in 23.05.x

### ISSUE THREAD

**Issue by efahl** [openwrt/packages#23861]
Reported https://forum.openwrt.org/t/snort-on-openwrt-23-05-3/194225 from the symptom that the `snort3` package has never built properly in 23.05.x.

When running `make menuconfig` with v23.05.x, the `snort3` package does not appear in the proper package tree.  It does appear with v22.x and when on main, this is solely a 23.05 issue.

@hnyman chased the issue down to the backport https://github.com/openwrt/packages/pull/23532, which references the HAS_LUAJIT_ARCH symbol, but that is undefined in the 23.05 branch.  I suspect the symbol was inadvertently included from the upstream version of the Makefile, and probably shouldn't be there.

When I remove that symbol from snort3/Makefile, then both defconfig and menuconfig handle snort3 package as expected, showing in both the menus and resulting .config file.

But, then things get hairy due to issues noted in https://github.com/openwrt/packages/issues/20994 and when I try to build, I get missing symbols:
```
FAILED: src/main/CMakeFiles/main.dir/oops_handler.cc.o
/home/efahlgren/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/bin/x86_64-openwrt-linux-musl-g++ -DHAVE_CONFIG_H -Dinline=inline -Drestrict=__restrict -I/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/network_inspectors -I/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src -I/home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/usr/include/luajit-2.1 -I/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0 -I/home/efahlgren/openwrt/openwrt/staging_dir/host/include -I/home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/usr/include/hs -I/home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/usr/include/uuid -I/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0=snort3-3.1.81.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/usr/include/daq3 -I/home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/usr/include/tirpc  -fvisibility=hidden   -DNDEBUG  -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -DNDEBUG -std=c++17 -MD -MT src/main/CMakeFiles/main.dir/oops_handler.cc.o -MF src/main/CMakeFiles/main.dir/oops_handler.cc.o.d -o src/main/CMakeFiles/main.dir/oops_handler.cc.o -c /home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc: In member function 'void OopsHandler::set_current_message(DAQ_Msg_h, snort::SFDAQInstance*)':
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc:61:9: error: 'DIOCTL_GetPrivDataLen' was not declared in this scope
   61 |         DIOCTL_GetPrivDataLen ioctl_data = {cur_msg,  0};
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc:62:48: error: 'DIOCTL_GET_PRIV_DATA_LEN' was not declared in this scope
   62 |         if (DAQ_SUCCESS == daq_instance->ioctl(DIOCTL_GET_PRIV_DATA_LEN, &ioctl_data, sizeof(ioctl_data)))
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc:62:75: error: 'ioctl_data' was not declared in this scope
   62 |         if (DAQ_SUCCESS == daq_instance->ioctl(DIOCTL_GET_PRIV_DATA_LEN, &ioctl_data, sizeof(ioctl_data)))
      |                                                                           ^~~~~~~~~~
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc: In member function 'void OopsHandler::eternalize(int)':
/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/snort3-3.1.81.0/src/main/oops_handler.cc:97:27: error: 'daq_msg_get_priv_data' was not declared in this scope; did you mean 'daq_msg_get_data'?
   97 |         memcpy(priv_data, daq_msg_get_priv_data(msg), std::min<size_t>(priv_data_len, sizeof(priv_data)));
      |                           ^~~~~~~~~~~~~~~~~~~~~
      |                           daq_msg_get_data
ninja: build stopped: subcommand failed.
```

Maintainer: @flyn-org @graysky2 
Environment: 23.05.3, x86/64

**Comment by efahl** [comment]
I did a local backport of libs/libdaq3 to the 3.0.14 version from main to v23.05.3 and this allowed snort3 to build without issue.  I have no confidence that this is a proper fix for the second set of issues above, as I don't know what else might depend on libdaq, so someone with more knowledge of this will have to take a look at it.

Summary of my test changes in 23.05.3:
1) Removed `@HAS_LUAJIT_ARCH` from `net/snort3/Makefile`.
2) Updated `PKG_VERSION` and `PKG_HASH` in `libs/libdaq3/Makefile` to correspond to those in master.

**Comment by graysky2** [comment]
I tested it building from master. Haven’t tried the backport branch.

**Comment by hnyman** [comment]
@graysky2 

> tested it building from master. Haven’t tried the backport branch.

If you author complex backport PRs with dependency changes, then please also test in the specific branch. Untested backports can easily break things, especially if they are not simple version upgrades.

This time your untested backport caused snort3 to completely disappear from 23.05, as your PR defined a dependency for a symbol that didn't exist there.

**Comment by graysky2** [comment]
Ah, sorry about that. Is the correct fix in this case to drop the depends or to add the missing symbol?  I haven't yet dug into the scope of this.

**Comment by efahl** [comment]
It looked to me like adding HAS_LUAJIT_ARCH (and all the baggage attached to it in main) to 23.05 would have other implications and you'd need to deal with those, so my suggestion would be to just delete it from the snort3/Makefile as it is not present anywhere else in the 23.05 packages.

**Comment by graysky2** [comment]
Thanks @efahl - I removed the symbol.  Let's see if it builds.

**Comment by BKPepe** [comment]
Fixed by https://github.com/openwrt/packages/pull/23871, closing. It will take up to 48 hours to be propagated to the build bots.
