### ISSUE TITLE
Package gcc is not compiling on trunk

### ISSUE THREAD

**Issue by Hallo32** [openwrt/packages#2387]
Hi,

the gcc package is not compiling with the trunk version of gcc.
Also an update to the same gcc version as the trunk may be useful.

**Comment by plntyk** [comment]
likely duplicate of #2244

**Comment by Hallo32** [comment]
../.././libgcc/config/mips/mips16.S: Assembler messages:
../.././libgcc/config/mips/mips16.S:202: Error: opcode not supported on this processor: mips1 (mips1) `mtc1 $4,$f12'
...

http://pastebin.com/KCJcTqQG

**Comment by hnyman** [comment]
gcc has been updated to 5.4.0 and seems to compile ok in buildbots
