### ISSUE TITLE
Blacklist format for adblock software

### ISSUE THREAD

**Issue by iconoclasthero** [openwrt/packages#23923]
I've spent quite a bit of time looking for this and it is nowhere to be found in the documentation.

**What is the format for manually adding sites to the blacklist?**  

**Where is this documented?**

"Please note: add only one domain per line. Comments introduced with '#' are allowed - ip addresses, wildcards and regex are not." is not an example that shows whether or not a loopback address is used...

Also, once these are changed, what are the exact steps required to make sure they're live?  There are a bunch of buttons on the interface that don't appear to do anything...or sometimes do something if you check the log?

**Comment by brada4** [comment]
Where is the bug?
In what software?
Is openwrt involved?
You need to fill in issue template to get any help.

**Comment by dibdot** [comment]
@iconoclasthero What is unclear in the sentence quoted from LuCI/adblock? Domains only, one per line ... and not loopback addresses ... anyway, ask such questions in the forum.
