### ISSUE TITLE
update Xray-core

### ISSUE THREAD

**Issue by mgmoghaddam** [openwrt/packages#24020]
Hi,

please update xray-core to 1.8.10 in 23.05 version

thanks

**Comment by brada4** [comment]
Current is latest supporting go compiler in v23,  if you know which change you need you can submit backport.

**Comment by 1715173329** [comment]
Xray has raised minimum go version to 1.22 since v1.8.8, however the code is still compatible with 1.21, imo it's worth to add a patch for it.

**Comment by brada4** [comment]
You need to revert dependabot dependencies that are not compatoble with v23 go.

**Comment by 1715173329** [comment]
updated.

**Comment by brada4** [comment]
@1715173329 :+1: for courage
