### ISSUE TITLE
keepalived: notify script handling is broken or undocumented

### ISSUE THREAD

**Issue by stintel** [openwrt/packages#24021]
@feckert 

The notify options in [the default keepalived UCI config](https://github.com/openwrt/packages/blob/master/net/keepalived/files/keepalived.config#L81-L84) suggest you can put a path to a script. This is misleading, as they are handled by hotplug-call, which is handled by /etc/hotplug.d/keepalived/01-user, which only calls /etc/keepalived.user. If you configure a path to e.g. /etc/keepalived/notify.sh in UCI, this script is never called. This leads to completely broken failover scenarios that are non-trivial to debug.

**Comment by feckert** [comment]
@stintel Thanks for the hint.
As far as I can tell, however, this has never worked!

I have opend a [PR](https://github.com/openwrt/packages/pull/24037) to remove the uci notify script options.
If the script should be called, it must be placed into `/etc/hotplug.d/keepalived`.
