### ISSUE TITLE
cups is missing doc and ipptool folders

### ISSUE THREAD

**Issue by futurechild** [openwrt/packages#2407]
cups is missing the following folders:
-doc containing cups.css, index.html etc.
-ipptool containing a few testfiles.

The below changes to the Makefile solve this.

changing this:

```
    $(INSTALL_DIR) $(1)/opt/share/cups
    $(CP) $(PKG_INSTALL_DIR)/opt/share/cups/templates \
        $(1)/opt/share/cups/
```

into this:
```

    $(INSTALL_DIR) $(1)/opt/share/cups
    $(CP) $(PKG_INSTALL_DIR)/opt/share/cups/templates \
        $(1)/opt/share/cups/
    $(CP) $(PKG_INSTALL_DIR)/opt/share/cups/ipptool \
        $(1)/opt/share/cups/
    $(INSTALL_DIR) $(1)/opt/share/doc
    $(CP) $(PKG_INSTALL_DIR)/opt/share/doc/cups \
        $(1)/opt/share/doc/
```

Have these folders been ommited intentionally ?

**Comment by hnyman** [comment]
I think that cups is still in located the "oldpackages" repository and currently unmaintained.
http://git.openwrt.org/?p=packages.git;a=tree;f=net/cups;hb=HEAD

Feel free to assume maintainership for the package and fix it, and then create a pull request to import it here.

**Comment by psycho-nico** [comment]
Just to let you know that I'm still working on reviving cups...

**Comment by luizluca** [comment]
@psycho-nico ,  just to let you know, I have the hplip package ready just waiting the cups package.  I'm interested only in hplip-sane but libcups is a hard build requirement.

**Comment by futurechild** [comment]
@psycho-nico , Did you find the cups version 2.1.2 Makefile currently used by Entware-ng ?
They pointed me here for changes as they just sync their repo with OpenWrt but I can only find a Makefile for version 1.5.3.

**Comment by luizluca** [comment]
@psycho-nico, is there any cups update?

**Comment by anarcat** [comment]
i have opened an issue about missing cups support in https://github.com/openwrt/packages/issues/7016

In the meantime it seems the canonical feed is https://github.com/Gr4ffy/lede-cups/ but no automated build is currently provided.
