### ISSUE TITLE
Unbound: cannot offload log from syslog

### ISSUE THREAD

**Issue by scottsteely** [openwrt/packages#24114]
Maintainer: @
Environment: ARM, PI-4  OpenWrt 23.05.3

Description:
Hello, I am trying to move the output of the unbound.log from the syslog to /var/lib/unbound.log but haven't been successful. 
I have SET the UCI parameters:

```
    option log-replies 'yes'
    option log-tag-queryreply 'yes'
    option log-local-actions 'yes'
    option logfile '/var/lib/unbound/unbound.log'
    option use-syslog: 'no'
```
I have also appended theses to unbound_srv.conf in /etc/unbound. 
After that I did UCI commit, config_reload and service unbound restart. 
Still no log.

It appears that  use-syslog is hardcoded at /usr/lib/unbound/unbound.sh : 

```
unbound_conf() {

echo "  use-syslog: yes"
```

So manual changed that but still no log in /var/lib/unbound. 

I understand I can completely remove UCI from unbound, there are some dynamic settings that I don't want to break.

**Comment by brada4** [comment]
I think need to remove colon

**Comment by dave14305** [comment]
Valid UCI options:
https://github.com/openwrt/packages/blob/master/net/unbound/files/README.md#complete-uci

The hard-coded `use-syslog` will be overridden if you add `logfile: "/var/lib/unbound/unbound.log"` in unbound_srv.conf. Just don’t mix UCI with native Unbound options in the .conf.

**Comment by scottsteely** [comment]
Thanks clearing up some misconceptions I had about UCI options. I was ably to get it to work, but I changed so many config files I'm not even sure which one did the trick.
