### ISSUE TITLE
libv4l: ERROR: Unknown variable "ir_bpf_enabled"

### ISSUE THREAD

**Issue by M95D** [openwrt/packages#24115]
Maintainer: @thess , last updated by @neheb 
Environment: mvebu, Turris Omnia

Description:
- Select mvebu / Turris Omnia.
- Select libv4l in menuconfig.
- Try to build.
Build fails with this error:
`target-arm_cortex-a9+vfpv3_musl_eabi/v4l-utils-1.26.1/meson.build:408:32: ERROR: Unknown variable "ir_bpf_enabled".`
[compile.txt](https://github.com/openwrt/packages/files/15276546/compile.txt)
[meson-log.txt](https://github.com/openwrt/packages/files/15276578/meson-log.txt)

Thanks.

**Comment by neheb** [comment]
looks like v4l-utils need to be enabled. My attempt at micro optimization failed.

**Comment by neheb** [comment]
Yeah.

https://git.linuxtv.org/v4l-utils.git/commit/?id=fee976dcfe3be03cc72c099f9ed3bac938a34b58

**Comment by neheb** [comment]
Fix pushed.
