### ISSUE TITLE
pbr: pbr has wan/wan6 interface names hard-coded, conflicts with wwan/wwan6 and travelmate

### ISSUE THREAD

**Issue by schuettecarsten** [openwrt/packages#24148]
pbr has wan/wan6 interface names hard-coded. On my setup, I have a wan interface and also a wwan/wwan6 interface to access internet via a wifi bridge. When using travelmate, these interfaces are named trm_wwan/trm_wwan6. pbr does not detect these interfaces and waits for "wan" access forever. I suggest to add an option to configure the name of the wan interfaces.

**Comment by stangri** [comment]
Upgrade to a current release from my repo and check README for option names.

**Comment by stangri** [comment]
> That's great, maybe it's a good idea to make it possible to add more than one interface name - to allow cable WAN, wifi WAN (WWAN) and QMI on the same device, depending on what's attached to the USB port.

You're welcome to contribute the code.

> When do you plan to upgrade the packages in this repo?

It has been upgraded in this repo.

**Comment by schuettecarsten** [comment]
> > When do you plan to upgrade the packages in this repo?
> It has been upgraded in this repo.

pbr is still 1.1.4...?

**Comment by stangri** [comment]
> > > When do you plan to upgrade the packages in this repo?
> > > It has been upgraded in this repo.
> 
> pbr is still 1.1.4...?

That version already has the options for specifying wan/wan6 names, does it not?

**Comment by schuettecarsten** [comment]
Yes, you're right.

Am Di., 14. Mai 2024 um 18:41 Uhr schrieb Stan Grishin <
***@***.***>:
