### ISSUE TITLE
libupm w. python 3.5

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#2420]
python2.7 is hardcoded in Makefile
python3.5 is detected by default at my end - failing build 

from CMakeCache.txt

```
PYTHON_INCLUDE_DIR:PATH=/home/user/openwrt/staging_dir/target-x86_64_musl-1.1.12/usr/include/python3.5
PYTHON_LIBRARY:FILEPATH=/home/user/openwrt/staging_dir/target-x86_64_musl-1.1.12/usr/lib/libpython3.5.so
```

@blogic

**Comment by blogic** [comment]
did you manually select 3.5 or did you use the default configuration ?

**Comment by plntyk** [comment]
i was doing a test compile with CONFIG_ALL=y

**Comment by dibdot** [comment]
please retest with latest release.
