### ISSUE TITLE
uhttpd: Invalid Lua prefix error when restarting uhttpd

### ISSUE THREAD

**Issue by vochong** [openwrt/packages#24230]
Maintainer: @nbd168
Environment: 

{
	"kernel": "6.6.30",
	"hostname": "Home",
	"system": "ARMv7 Processor rev 0 (v7l)",
	"model": "Netgear Nighthawk X4S R7800",
	"board_name": "netgear,r7800",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"revision": "r26434-0a861a0c0f",
		"target": "ipq806x/generic",
		"description": "OpenWrt SNAPSHOT r26434-0a861a0c0f"
	}
}

Description:

```
# /etc/init.d/uhttpd stop
# /etc/init.d/uhttpd start
Skipping invalid Lua prefix "/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua"
```

**Comment by brada4** [comment]
It is a warning, lua wsgi is not installed and is skipped.

**Comment by vochong** [comment]
Thank you @brada4  I will close it.

**Comment by NeroBlackstone** [comment]
Same problem..

Which package does “lua wsgi” refer to?

**Comment by NeroBlackstone** [comment]
be sure `uhttpd` and `uhttpd-mod-lua` at same version
```
root@OpenWrt:/tmp# opkg list-installed | grep uhttpd
uhttpd - 2021-03-21-15346de8-2
uhttpd-mod-lua - 2021-03-21-15346de8-2
```

**Comment by nmaupu** [comment]
> I found solution, be sure `uhttpd` and `uhttpd-mod-lua` at same version
> 
> ```
> root@OpenWrt:/tmp# opkg list-installed | grep uhttpd
> uhttpd - 2021-03-21-15346de8-2
> uhttpd-mod-lua - 2021-03-21-15346de8-2
> ```

I don't think this is the solution, I have the same version for both and I still get the problem as well...
