### ISSUE TITLE
Luci 2 does not show system->system webpage

### ISSUE THREAD

**Issue by tpham3783** [openwrt/packages#2436]
Hi,

I just installed luci2 and everything worked OK except the webpage @ system/system
The page at system/system would not load at all.

I then opened up firebug debugger and saw the below error:

TypeError: val is null
luci2.j... > eval line 240

the error is in luci2.js, line 240, or here:

 Class.require = function(name)
        {
                var path = '/' + name.replace(/\./g, '/') + '.js';

                return $.ajax(path, {
                        method: 'GET',
                        async: false,
                        cache: true,
                        dataType: 'text'
                }).then(function(text) {
                        var code = '%s\n\n//@ sourceURL=%s/%s'.format(text, window.location.origin, path);
                        var construct = eval(code); ///// <<<----error occurred here

                        var parts = name.split(/\./);
                        var cparent = L.Class || (L.Class = { });

                        for (var i = 1; i < parts.length - 1; i++)
                        {
                                cparent = cparent[parts[i]];

                                if (!cparent)
                                        throw "Missing parent class";
                        }

                        cparent[parts[i]] = construct;
                });
        };

Someone please look at it and let me know what we can do to fix it.  thanks

**Comment by yousong** [comment]
Looks like LuCI2 is not hosted here in github.  I would like to suggest posting to mailing list for timely responses, or better yet providing the patch ;)
