### ISSUE TITLE
debootstrap gives a 404 over http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap-udeb_1.0.78_all.udeb

### ISSUE THREAD

**Issue by zoobab** [openwrt/packages#2443]
debootstrap gives a 404 over http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap-udeb_1.0.78_all.udeb.

It seems that the file is gone, they have moved to 1.0.79 is seems.

**Comment by dfc-d** [comment]
This should be closed; debootstrap is updated in master
