### ISSUE TITLE
ucode 有使用发方法吗？

### ISSUE THREAD

**Issue by uosbox** [openwrt/packages#24577]
很久没玩opnwrt了！！
wifi的配置脚本竟然是ucode脚本
这怎么用 ？一点都没sh脚本好用，可能是我不会用吧！！1
各位大佬是否有ucode脚本的教程
比如哦想截取mac后6位
```
sh
mac="11:22:33:44:55:66"
mac="${mac//:/}"
mac="${mac:6:12}"
```
若是我用ucode 语法怎么写呢？

我想改的脚本路劲/lib/wifi/mac80211.uc
只是先生成wifi的ssid的时候 尾巴加上mac的后6位

**Comment by brada4** [comment]
English? Product versions?

**Comment by BKPepe** [comment]
No reply, closing.
