### ISSUE TITLE
Kernel mismatch for Asterisk11-chan-dongle

### ISSUE THREAD

**Issue by Null-Kelvin** [openwrt/packages#2465]
TL-MR3020, OpenWRT 15.05 Chaos Calmer. Kernel version - 3.18.23
Trying to install asterisk11-chan-dongle:
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for asterisk11-chan-dongle:
 *      kernel (= 3.18.20-1-7bed08fa9c06eb8089e82c200340ec66) *
 * opkg_install_cmd: Cannot install package asterisk11-chan-dongle.

**Comment by jow-** [comment]
You cannot use repository kmods with custom builds.
