### ISSUE TITLE
adblock: DNS report does not work when listening on ports other than 53

### ISSUE THREAD

**Issue by rrhett** [openwrt/packages#24685]
Maintainer: @dibdot
Environment: LuCI Master (24.201.32493~e229e1a) / OpenWrt SNAPSHOT (r26971-66177c081f)

Description:
If you have Report Ports set to ports other than 53, it seems `tcpdump -r` does not properly render the packets, so the DNS report functionality does not parse any requests sent to a DNS running on something other than port 53.

Fix:
On line 1308 and 1317 of adblock.sh, replace
`"${adb_dumpcmd}" "${resolve}" -tttt -r "${file}" 2>/dev/null |`
with
`"${adb_dumpcmd}" "${resolve}" -T domain -tttt -r "${file}" 2>/dev/null |`

(add `-T domain`)

An example of how I was able to reproduce this:
1. Install adblock, unbound, and adguardhome (and any additional packages like tcpdump, unbound-control, etc).
2. Configure adguardhome as the DNS listening on port 53, pointed to unbound as the upstream DNS listening on another port (e.g. 5153).
3. Configure adblock with "Report ports" set to 5153.

**Comment by dibdot** [comment]
Thanks, I'll add the parm with the next update.
