### ISSUE TITLE
configure-gdp fails because "expat is missing or unusable"

### ISSUE THREAD

**Issue by bobafetthotmail** [openwrt/packages#2469]
I have libexpat1 and libexpat1-dev installed in my Debian Jessie system.

this is an excerpt of the error

> checking for shared library run path origin... done
> checking for libexpat... no
> configure: error: expat is missing or unusable
> Makefile:8726: recipe for target 'configure-gdb' failed
> make[5]: *** [configure-gdb] Error 1
> make[5]: Leaving directory '/media/alby/ext4data/openwrt-sources/openwrt-trunk/build_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/gdb-7.10.1'
> Makefile:846: recipe for target 'all' failed
> make[4]: *** [all] Error 2
> make[4]: Leaving directory '/media/alby/ext4data/openwrt-sources/openwrt-trunk/build_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/gdb-7.10.1'
> Makefile:69: recipe for target '/media/alby/ext4data/openwrt-sources/openwrt-trunk/build_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/gdb-7.10.1/.built' failed
> make[3]: *** [/media/alby/ext4data/openwrt-sources/openwrt-trunk/build_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/gdb-7.10.1/.built] Error 2
> make[3]: Leaving directory '/media/alby/ext4data/openwrt-sources/openwrt-trunk/toolchain/gdb'
> toolchain/Makefile:81: recipe for target 'toolchain/gdb/compile' failed
> make[2]: *** [toolchain/gdb/compile] Error 2
> make[2]: Leaving directory '/media/alby/ext4data/openwrt-sources/openwrt-trunk'
> toolchain/Makefile:80: recipe for target '/media/alby/ext4data/openwrt-sources/openwrt-trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/stamp/.toolchain_install' failed
> make[1]: *** [/media/alby/ext4data/openwrt-sources/openwrt-trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/stamp/.toolchain_install] Error 2
> make[1]: Leaving directory '/media/alby/ext4data/openwrt-sources/openwrt-trunk'
> /media/alby/ext4data/openwrt-sources/openwrt-trunk/include/toplevel.mk:192: recipe for target 'world' failed
> make: *** [world] Error 2
> ^C/media/alby/ext4data/openwrt-sources/openwrt-trunk/include/toplevel.mk:80: recipe for target 'prepare-tmpinfo' failed
> make[1]: *** [prepare-tmpinfo] Interrupt
> /media/alby/ext4data/openwrt-sources/openwrt-trunk/include/toplevel.mk:192: recipe for target 'world' failed
> make: *** [world] Interrupt

It might be related to issue #1631 but I have no idea on how to fix this.

**Comment by hnyman** [comment]
The issue is related to the gdb on the toolchain (defined in the main build source code), and neither the toolchain gdb nor the devel/gdb package is here in the packages feed.
