### ISSUE TITLE
pciutils compile error for libudev.so.1

### ISSUE THREAD

**Issue by iryna7** [openwrt/packages#2471]
Hi, once compile the OpenWRT 15.05 source tree it shows me that following errors

`install -m0644 /var/home/iryna7/work/MT7621/openwrt/build_dir/target-mipsel_1004kc+dsp_musl-1.1.14/pciutils-3.4.1/ipkg-install/usr/share/pci.ids.gz /var/home/iryna7/work/MT7621/openwrt/build_dir/target-mipsel_1004kc+dsp_musl-1.1.14/pciutils-3.4.1/ipkg-ramips_1004kc/pciutils/usr/share/
find /var/home/iryna7/work/MT7621/openwrt/build_dir/target-mipsel_1004kc+dsp_musl-1.1.14/pciutils-3.4.1/ipkg-ramips_1004kc/pciutils -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package pciutils is missing dependencies for the following libraries:
libudev.so.1`

it is looks like linking problem comes from dependencies check, i guess. yes, it already compiled [eudev] package. 

any comment would be appreciates. thanks in advance.

**Comment by plntyk** [comment]
pciutils DEPENDS:= line should contain +eudev
