### ISSUE TITLE
tailscale: missing from 23.05.4 (aarch64_cortex-a53)

### ISSUE THREAD

**Issue by tiagoad** [openwrt/packages#24712]
Maintainer: @mochaaP 
Environment: 23.05.4 - aarch64_cortex-a53

Description:
The `tailscale` package is missing from `aarch64_cortex-a53` on all 23.05 releases.

There seems to be a build error (https://downloads.openwrt.org/releases/faillogs-23.05/aarch64_cortex-a53/packages/tailscale/compile.txt)

```
Finding targets
verifying github.com/mattn/go-runewidth@v0.0.14/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	go.sum:     h1:Jdepj2loyihRzMpdS35Xk/zdY8IAYHsh153qUoGf23w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by mochaaP** [comment]
cc @1715173329

**Comment by 1715173329** [comment]
#24570 I don't really want to repeat it again and again.

**Comment by 1715173329** [comment]
available now
