### ISSUE TITLE
v2RayA: Network Configuration Unsoliticitly Changed After Adding v2Ray Server Info

### ISSUE THREAD

**Issue by Lesita** [openwrt/packages#24710]
# Issue template (remove lines from top till here)

Maintainer: @v2RayA
Environment: amd64, generic Intel system, OpenWrt 23.05

Description:

After the v2RayA instance is installed and started, network changes unsoliticitly happened without notice, causing network traffic leakage. The software not only creates an instance to the desired server, but has changed routing parameters and "dnsmasq" configurations which resulted in unsoliticitly behaviours causing traffic leakage.

In order to prevent potential risks arising as of Iranian ISPs raising Internet moderation and censorship, automated configuration change should not happen and the user should have the option to make any changes within the app.

**Comment by 1715173329** [comment]
How v2rayA works depends on how you configure it, you should read its documentation.
v2rayA itself will not change anything without configuration.
