### ISSUE TITLE
squeezelite: probably an error in the startup script

### ISSUE THREAD

**Issue by squeezewrt** [openwrt/packages#2476]
When in the config file set parameter 'interface' to "", init script generates an incorrect command line with '-I' key without any interface name.

Perhaps in a startup script 

> [ -n $interface ] && cmdline="$cmdline -I $interface"

must be replaced by

> [ -n "$interface" ] && cmdline="$cmdline -I $interface"

A similar error is possible in

> [ -n $device ] && cmdline="$cmdline -o $device"

**Comment by thess** [comment]
Thanks - fixed in 46432e174b6c7e31cacec6f5eb597f6f16752a72
