### ISSUE TITLE
Raspberry pi 4 with Openwrt 23.05.4 cannot connect to the internet and cannot access to luci login page after installing packages 

### ISSUE THREAD

**Issue by mrusli70** [openwrt/packages#24795]
I am using Raspberry pi 4 with OpenWrt 23.05.4. And I cannot seems to get connect to the internet at all and now i cannot even access to my luci login page. 

After install Squid, Dns-http-Proxy, Banip, BCP38.

All can't seem to get access. 

It is still buggy,

**Comment by egc112** [comment]
Although it certainly is possible that there is a bug, it could also be a misconfiguration.
I suggest you turn to the  forum for discussing your problem.

But if it is a bug something more is required besides "It not does not work"
