### ISSUE TITLE
dnsproxy - latest update requires changes to init.d/dnsproxy

### ISSUE THREAD

**Issue by cyformatician** [openwrt/packages#24869]
Maintainer: @1715173329
Environment: platform independent

Description:

Latest dnsproxy update .73.0 with a fix released in .73.1 introduces a new option --hosts-file-enabled which must be added/declared in init.d as adding it to the config file is insufficient. Also, the global option hosts_file_enabled with value 'false' must be set in config/dnsproxy as the option is enabled by default which breaks dnsproxy.

Do note that if this new option is enabled without a valid hosts file assigned with --hosts-files, dnsproxy crashes/errors out.

```
append_param_arg "global" "hosts_file_enabled" "--hosts-file-enabled"
```

**Comment by 1715173329** [comment]
Ping @p-w-p could you check it please?

**Comment by 1715173329** [comment]
please check if #24875 fixes your issue

**Comment by p-w-p** [comment]
> Ping @p-w-p could you check it please?

Sorry, I didn't try an invalid hosts file when running the tests. Thanks for the patch!
