### ISSUE TITLE
sstp-client: In the interface parameters 'SSTP Port' is ignored

### ISSUE THREAD

**Issue by Rose9111** [openwrt/packages#24951]
#Maintainer: @neheb 
Description:
The parameter 'SSTP Port'  that is set in "Network -> Interfaces -> SSTP-interface" is ignored. Connecting to port 443 only.

**Comment by neheb** [comment]
ping @vgaetera

**Comment by vgaetera** [comment]
Check the output:
```sh
opkg list-installed sstp-client
```

**Comment by Rose9111** [comment]
`sstp-client - 1.0.15-1`

**Comment by vgaetera** [comment]
This functionality is only for snapshots and the next major release, but you can patch it manually:
* https://github.com/openwrt/packages/pull/22405

**Comment by Rose9111** [comment]
That's working. Thanks
