### ISSUE TITLE
tgt: please add support for thin provisioning to the init script

### ISSUE THREAD

**Issue by patrakov** [openwrt/packages#25065]
Maintainer: @mstorchak 
Environment: OpenWrt 23.05.5 on Linksys E8450 (UBI), which is aarch64_cortex-a53 (mediatek/mt7622)

Description:

The packaged version of `tgt` (1.0.86) supports thin provisioning, which means the ability to dig holes in files if an initiator DISCARDs a region of blocks, or to pass such DISCARDs down to block devices. However, the init script has no way to enable it, as `thin_provisioning` is not in the list of valid LUN keywords.

Enabling it manually works with `option 'bstype' 'rdwr'`, which is the default:

```
# tgtadm --lld iscsi --mode logicalunit --op update --tid 1 --lun 1 --params thin_provisioning=1
```

It does not work with `aio`, but this seems to be an upstream issue.

I have tested that adding `thin_provisioning` to the list of valid keywords in `validate_lun_section()` and `handle_lun()` achieves the goal of being able to use this functionality in OpenWrt.

**Comment by mstorchak** [comment]
Thanks for the idea, I'll check this out.
