### ISSUE TITLE
[Request | udp2raw] New package

### ISSUE THREAD

**Issue by lars18th** [openwrt/packages#25070]
Maintainer: @codemarauder (Nishant Sharma <nishant@hopbox.in>), Toni Uhlig <matzeton@googlemail.com>  
(maintainers of the friend package `UDPspeeder`)

Description:

Add a package for `udp2raw` https://github.com/wangyu-/udp2raw

With this tool you can add to UDPspeeder the features of FakeTCP and ICMP transports.

Thank you.

**Comment by brada4** [comment]
PR welcome?

**Comment by BKPepe** [comment]
Yeah, if you want to have new packages in this repository, please create pull request.

**Comment by lars18th** [comment]
Hi @BKPepe ,

The idea to post this request here is because the _maintainers_ of the **friend** package `UDPspeeder` could create the PR. It's a simple call to them to add the linked `udp2raw` package.

Excuse me if this is against the rules of this forum.

**Comment by brada4** [comment]
Take an inch of courage to become a co-maintainer.
