### ISSUE TITLE
PBR: No longer works after reinstalling OpenWRT 23.05.5

### ISSUE THREAD

**Issue by alehofde** [openwrt/packages#25089]
After reinstalling OpenWRT 23.05.5 with PBR 1.1.6-20, the service no longer starts

ERROR: The pbr 1.1.6-20 service failed to discover WAN gateway!

I still have an OpenWRT 23.05.03 running with pbr 1.1.1-7 and everything works fine there.

I'm sure it's a configuration error on my end but I have no idea :-(

Can anyone help?

**Comment by alehofde** [comment]
![image](https://github.com/user-attachments/assets/7cd97367-de05-49b9-9d83-0153b2067840)


I missing the service gateways. These are not displayed

**Comment by stangri** [comment]
If you have updated the luci app or if you're seeing the error in the console, it usually includes the relevant link to the README. Follow it. If you already know it's not a bug but a misconfiguration, please post in the forum thread linked from README.

**Comment by spearmootz** [comment]
this same thing happened to me.  basically my router is connected to the internet by connecting to another router by WIFI.  the service never starts because its waiting for wan.  once i plug it in the service starts no problem.

any idea how this can be mitigated?  @stangri

**Comment by stangri** [comment]
@spearmootz please post the CLI or luci app error message in its entirety.

**Comment by spearmootz** [comment]
@stangri there is no error.  you click start and it just stays like the following image. then the logs get filled with waiting for WAN.  once you connect the internet cable it successfully starts.
![Screenshot 2024-10-08 144416](https://github.com/user-attachments/assets/49dd2aa4-a2f4-46cf-bac9-7f4fcf7c43ab)
![Screenshot 2024-10-08 144330](https://github.com/user-attachments/assets/a430de2c-5236-4c2a-b8ec-564057cf8a4e)
![Screenshot 2024-10-08 144400](https://github.com/user-attachments/assets/755d951b-04c9-43d8-88ef-3a1f3dd5700b)

**Comment by spearmootz** [comment]
i am running on PRB Version 1.1.6-22 - Running (fw4 nft file mode).

**Comment by stangri** [comment]
This looks like an outdated luci app. You need to either update it or clear the browser cache (or both).

You may benefit from reviewing the README and either use an option to not wait for wan on start or set the procd_wan_interface option to wwan (or both).

**Comment by spearmootz** [comment]
i dont think i am able to update, i opened in incognito and got that version.  1.1.6-22 seems to be the latest on my version according to the opkg. 

setting the procd_wan_interface did work! thanks

**Comment by amzamzamzamz** [comment]
the same issue with tor interface

**Comment by Laitinlok** [comment]
I can no longer choose AdguardHome ipset with the new version of pbf-iptables.

**Comment by stangri** [comment]
> I can no longer choose AdguardHome ipset with the new version of pbr -iptables.

Can you please post the output of: `ubus -S call luci.pbr getPlatformSupport '{"name": "pbr" }'`?
