### ISSUE TITLE
something wrong with staging_dir

### ISSUE THREAD

**Issue by Chaosdelphin** [openwrt/packages#2508]
cp: cannot stat '.../openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/host/lib/python2.7': No such file or directory

**Comment by hnyman** [comment]
Which Openwrt version you are working with?
That does not sound like the current trunk.

Please provide also more context to the error.

**Comment by yousong** [comment]
Close this as the environment seems old and no updates for nearly 5 months
