### ISSUE TITLE
mwan3: Routes don't get removed from main routing table unless interface fully down

### ISSUE THREAD

**Issue by joshuadouch** [openwrt/packages#25119]
Maintainer: @feckert
Environment: OpenWrt 23.05.5, x86_64

Description:
I have configured mwan3, but when an interface loses connectivity (e.g. stops responding to ping) the routes don't get removed. If the interface is physically stopped, wait for failover and then started, then the routes will be removed from the main routing table. This is the case in both failover and recovery. 

I have configured this from scratch, ensuring I abide by all naming conventions, max character lengths and avoiding same name interface/member/policy/rules. However, I have also used the default example configuration (only changing config to match interface names), and I face the same issue. I have also tried this from a fresh installation of OpenWrt.

My main issue is I route all of my WAN bound traffic over a UDP L2TP VPN. I have a rule which routes src LAN subnet dst 0.0.0.0/0 over this VPN, and then a rule that routes src any to dst 0.0.0.0/0. This means a route for the VPN endpoint is automatically created in the main routing table, when the interface fails over, a new route is added for WAN2 (backup) interface, however as the old route with a lower metric still exists, the VPN does not recover (nor can any traffic route out).

I previously had this set up with a rule specifically for the dest IP of the VPN endpoint, which seemed to swap the IP route for the main offline interface for the backup interface, and traffic/VPN failed over - but when the interface came back online - it did not recover back to the main interface. 

Is this expected behavior or is this a known issue? Or have I just configured this incorrectly?

**Comment by feckert** [comment]
The route is not deleted from the main route table. This is intentional. Whether this is good or bad is the question. But the mwan3 does it like this

In your case you have to change the metric of your default routings. The interface with the lowest metric wins here. And the traffic is then processed via this interface.

**Comment by joshuadouch** [comment]
Thank you - I understand how this works better now. I was also getting confused by some unexpected behaviour from xl2tpd - it seemed to add a static route to the VPN endpoint automatically, and this was always over my backup WAN link, I assume because this always came online first at boot. 

To avoid this issue I have added the following to the Notify script

if [ "${ACTION}" = "disconnected" ] || [ "${ACTION}" = "connected" ] && [ "${INTERFACE}" = "wan_main" ] ; then
 ifdown aaisp
 ip route delete 90.155.xx.xx
 ifup aaisp
fi

And simply have two rules - one with the VPN endpoint at the top set to use a policy containing both main and backup links with a metric of 1 and 2 respectively, and a 'default' rule for everything else, routing everything over the VPN.

This was no issue with mwan3, apologies!

Thank you!

**Comment by feckert** [comment]
> This was no issue with mwan3, apologies!

No problem :-)
