### ISSUE TITLE
sstp-client: Update to 1.0.20

### ISSUE THREAD

**Issue by Neustradamus** [openwrt/packages#25134]
Maintainer: @fededim, @jow-, @hnyman, @champtar, @neheb, @harveyhu2012, @rkkoszewski, @lipnitsk, @paulfertser, @aparcar, @xback, @vgaetera
Environment: ALL

Description:
```
Update sstp-client to 1.0.20
```

Thanks in advance.

cc: @enaess

Links:
- https://github.com/openwrt/packages/tree/master/net/sstp-client
- https://gitlab.com/sstp-project/sstp-client/
- https://gitlab.com/sstp-project/sstp-client/-/releases
- https://sourceforge.net/projects/sstp-client/

**Comment by rkkoszewski** [comment]
I can have a look at it.

**Comment by enaess** [comment]
Let me know if you have any questions, @rkkoszewski

**Comment by Neustradamus** [comment]
Thanks @Ansuel, he has done it!
- https://github.com/openwrt/packages/pull/25185
