### ISSUE TITLE
ocserv: log-level set much too high by default

### ISSUE THREAD

**Issue by rhester72** [openwrt/packages#25177]
Maintainer: Nikos Mavrogiannopoulos <n.mavrogiannopoulos@gmail.com>
Environment: aarch64, Raspberry Pi Compute Module 4 Rev 1.1, 23.05.5

Description: /etc/ocserv/ocserv.conf.template as included with the package sets log-level to 3, which is MUCH too noisy - suggest 0 or commenting it out for default installation

**Comment by Ra2-IFV** [comment]
@nmav Can I ask what your idea is? Log level `0` is default in upstream

**Comment by Ra2-IFV** [comment]
I can create a simple PR if you don't mind...

**Comment by rhester72** [comment]
I don't mind...0 would work, better would probably be to comment it out in the template so it always uses the upstream default.  I can't understand the motivation of why it is set to 3 on the OpenWRT package unless the maintainer was testing something and needed debug logging and forgot to disable it after.

**Comment by Ra2-IFV** [comment]
> I don't mind...0 would work, better would probably be to comment it out in the template so it always uses the upstream default.

`0` means default, should be same as being commented out, [manual page](https://ocserv.openconnect-vpn.net/ocserv.8.html)

>  I can't understand the motivation of why it is set to 3 on the OpenWRT package unless the maintainer was testing something and needed debug logging and forgot to disable it after.

Possible, hahah

**Comment by nmav** [comment]
Hi, it makes sense, please submit a pull request.

**Comment by Ra2-IFV** [comment]
> Hi, it makes sense, please submit a pull request.

Would it be useful to update the template conf here from the [Gitlab repo](https://gitlab.com/openconnect/ocserv/-/blob/master/doc/sample.config)? I see some differences...

**Comment by Ra2-IFV** [comment]
@rhester72 you may close this issue now if you are satisfied with the change #25347

**Comment by rhester72** [comment]
Closing as working, thank you!
