### ISSUE TITLE
yggdrasil: Update to 0.5.9

### ISSUE THREAD

**Issue by timur-davletshin** [openwrt/packages#25180]
Maintainer: @wfleurant @dalfos 
Environment: ALL

Description: 

```
Update yggdrasil package to 0.5.9, because of numerous bug fixes since 0.5.4 (current stable) and changes in routing algorithm which introduced RTT-aware link costing.
```

Thank you in advance!

**Comment by Ra2-IFV** [comment]
https://github.com/openwrt/packages/commit/a26c79293982424049a97d0c7a8aff6d01626e48
You can close this issue

**Comment by timur-davletshin** [comment]
Thank you!

**Comment by timur-davletshin** [comment]
Just not to reopen it again - 0.5.11 fixes important memory leak which actually hits users on smaller memory devices like routers within several days.

**Comment by Ra2-IFV** [comment]
It's on 0.5.10; I may open a pr if you want
