### ISSUE TITLE
MIPS big-endian patch for bluez 5.37 stack

### ISSUE THREAD

**Issue by artynet** [openwrt/packages#2523]
I think that you should consider this patch for **MIPS-BE** system :

https://github.com/buildroot/buildroot/blob/master/package/bluez5_utils/0001-tools-avinfo-Fix-big-endian-build.patch

I bumped myself into it while compiling the sources for the **ar71xx** ARCH. please let me know...

Regards, Arturo.

**Comment by navinp1281** [comment]
Yes that fixes it .
See for the upstream commit bluez.git
After copying the struct or the below diff, i can compile on the latest openwrt snapshot from git . 
The file in error is avinfo.c and struct is a2d_ldap_t.
http://git.kernel.org/cgit/bluetooth/bluez.git/commit/?id=01d85fdf6a45150e82143803be3373d779d18522
