### ISSUE TITLE
Is raspberry pi kmod-net-rtl8188eu grabbing up the `.ko` from the right path?

### ISSUE THREAD

**Issue by cusspvz** [openwrt/packages#2524]
I did a fresh install of the OpenWRT snapshot on the RPi.

Everything went well until I tried to install `kmod-net-rtl8188eu`, the package was successfully installed but there was no driver, so I've checked package's contents and it was empty.

<img width="1106" alt="captura de ecra 2016-03-19 as 17 16 03" src="https://cloud.githubusercontent.com/assets/3604053/13900101/49ced122-edf6-11e5-95d0-9f3586c9f569.png">

I think path for the driver has changed, could that be the reason?

NOTE: `r8188eu.ko` is placed at `staging` directory after a kernel build.

**Comment by LipkeGu** [comment]
there are 2 Drivers for the 81xx:
- rtl8192xx <-- works also for some 8188xx chips (like 8188cu) :)
- rtl8188ru

**Comment by cusspvz** [comment]
A further investigation lead me into the patch where `8188eu` was removed because it was only compatible with `wext` driver at the time.

**Comment by diizzyy** [comment]
@thess @hnyman 
Fixed in LEDE, please close.
