### ISSUE TITLE
Error Configuring adblock.

### ISSUE THREAD

**Issue by whins** [openwrt/packages#2525]
Package installed manual (on OpenWrt Barrier Breaker 14.07)
And have next errors:
```
`//usr/lib/opkg/info/adblock.postinst: line 4: default_postinst: not found`
Collected errors:
 * pkg_run_script: package "adblock" postinst script returned status 127.
 * opkg_configure: adblock.postinst returned 127.
```

**Comment by hnyman** [comment]
It is not compatible with the old (and deprecated) BB14.07.
The package installation functions have changed since then.
