### ISSUE TITLE
fwknopd wrong file permission

### ISSUE THREAD

**Issue by coelner** [openwrt/packages#2529]
the script in rc.d doesn't set the correct file permission.
If you add after line 55 '> /etc/fwknop/access.conf'
```
chmod 600 /etc/fwknop/fwknopd.conf
chmod 600 /etc/fwknop/access.conf
```

the script sets the right permission and the daemon doesn't warn.

**Comment by oneru** [comment]
Looks reasonable, I'll take a closer look soon. Thanks!

**Comment by yousong** [comment]
@jp-bennett , updates on this?

**Comment by jp-bennett** [comment]
@yousong Thanks for the ping, will take care of this this weekend.

**Comment by jp-bennett** [comment]
PR3075 contains this fix.

**Comment by yousong** [comment]
Thanks.

BTW, I noticed that the init script would write to /etc/fwknopd/ which is very likely on flash storage on devices running OpneWrt/LEDE.  It would be better if it could be moved to /var/etc

**Comment by jp-bennett** [comment]
@yousong That's an interesting thought.  I believe that would be possible without too much trouble.  I'll pursue when I get a chance.
