### ISSUE TITLE
libsoxr: no dynamic libs

### ISSUE THREAD

**Issue by ryzhovau** [openwrt/packages#2533]
`libsoxr` Makefile is [packing](https://github.com/openwrt/packages/blob/master/libs/libsoxr/Makefile#L58) static library into repo which causes:

* meaningless ipk file,
* meaningless dependencies for `squeezelite` and `shairport-sync`.

Dynamic libs creation was [turned off](https://github.com/openwrt/packages/commit/5c7c791a7a09aded76d527ce368b09d15ac3caf5) by unknown reason.

Originally reported at https://github.com/Entware-ng/Entware-ng/issues/190

@mikebrady

**Comment by mikebrady** [comment]
Thanks for this – it's beyond my competence!
