### ISSUE TITLE
[BanIP]: user.err banIP: no download utility with SSL support

### ISSUE THREAD

**Issue by JuliusBairaktaris** [openwrt/packages#25376]
Maintainer: @dibdot
Environment: OpenWrt SNAPSHOT 6720c4ccba256186bf2f1b1edadb851c447e62a5

Description:

With the new APK transition, BanIP no longer has the necessary dependencies to download files via HTTPS.

My config file: https://github.com/JuliusBairaktaris/Qualcommax_NSS_Builder/blob/main/ax3600.config

I ran `make defconfig` to generate the full .config

**Comment by dibdot** [comment]
It's a known issue with newly introduced apk package manager in master and a workaround exists, see https://github.com/openwrt/openwrt/issues/16907#issuecomment-2478298115 for details.

**Comment by JuliusBairaktaris** [comment]
Hey @dibdot, I just clean flashed a build with BanIP 1.5 and the issue reappeared.

**Comment by dibdot** [comment]
worksforme, make sure you also have the appropriate SSL/TLS library installed (see readme)... or use curl or wget-ssl.

**Comment by JuliusBairaktaris** [comment]
![Image](https://github.com/user-attachments/assets/7654178b-22d0-475d-969f-25fb5be812a0)

Its installed. Curl works however
