### ISSUE TITLE
busybox/cron spams log with file root: wakeup dt=60

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/packages#25530]
@hnyman and @hauke 

Environment: (Xiaomi Mi Router AX3000T (OpenWrt U-Boot layout), mediatek/filogic, OpenWrt SNAPSHOT r28277-59dd9cddf9 )

Description:

After latest upgrade of firmware my log is filled with:

![image](https://github.com/user-attachments/assets/62935100-8466-47fd-a286-57397c147427)

I have wifischedule (script that uses crond to disable wifi) package installed but even after disabling it I have these errors in log...

**Comment by hnyman** [comment]
Same answer as in https://github.com/openwrt/openwrt/pull/17107#issuecomment-2528134628

* edit /etc/config/system to NOT have debug logging on for "cronloglevel" option. Option's numeric value should be 7 (or 9 for quiet), or 
* select "Normal" in LuCI" for cron logging. 

And restart the cron service after changing the setting (or reboot the router)

Ps. Not related to the packages repo.

**Comment by SuperSandro2000** [comment]
Why is the default debug?

**Comment by hnyman** [comment]
Default is actually "no setting" in the config file, but as some users have the old numeric default 5 there and busybox now handles the value 5 properly, that 5 causes debug. Just change it to 7, or remove the whole cronloglevel line from the config file.
