### ISSUE TITLE
net-snmp:  issue with the #elifdef macro definition in the patches/200-add-pcre2-support.patch

### ISSUE THREAD

**Issue by hyw0810** [openwrt/packages#25564]
Maintainer: Stijn Tintel \<stijn@linux-ipv6.be>

**PKG_VERSION:=5.9.4**
**PKG_RELEASE:=3**

Description:
In the `patches/200-add-pcre2-support.patch` file, lines 214 and 265 define `#elifdef HAVE_PCRE_H`. Is `#elifdef` correct and compliant with the C standard? As far as I know, this was introduced in C++23.

https://github.com/openwrt/packages/blame/0d478f650850deaa0c165d20b6b3a34b32af249b/net/net-snmp/patches/200-add-pcre2-support.patch#L214
https://github.com/openwrt/packages/blame/0d478f650850deaa0c165d20b6b3a34b32af249b/net/net-snmp/patches/200-add-pcre2-support.patch#L265C21-L265C21

**Comment by Yang-Wei-Ting** [comment]
I just bumped into this too and created a PR https://github.com/openwrt/packages/pull/25577
