### ISSUE TITLE
ocserv on mvebu

### ISSUE THREAD

**Issue by uk3** [openwrt/packages#2560]
ocserv (0.10.11-1) from 15.05.1 does not work on the mvebu hardware (WRT1200AC)

It dies with a segmentation fault during the startup phase.

lG uk

**Comment by nmav** [comment]
Have you tried the latest 0.10.12 in 15.05, or 0.11.1 on master?

**Comment by nmav** [comment]
@uk3

**Comment by nmav** [comment]
Closing as there was no information for long time.
