### ISSUE TITLE
wget suggest using different alternative priority for wget-ssl and wget-nossl

### ISSUE THREAD

**Issue by 1plus-1** [openwrt/packages#25625]
Currently wget-ssl and wget-nossl have the same alternative priority for link /usr/bin/wget. This causes an [issue](https://github.com/openwrt/openwrt/issues/17392) that the /usr/bin/wget is not created when both are selectd and then 'apk update' is not working.

The issue should be fix in openwrt repo but I do feel giving different priority for alternatives is a better practice.
https://github.com/openwrt/packages/blob/ca9c3d1baea38f0e5cedae7b74cfe8ef15a3ec83/net/wget/Makefile#L52

Maybe wget-ssl=400 and wget-nossl=300?

**Comment by robimarko** [comment]
I agree, if both are present it makes sense that SSL variant has higher priority, please make a PR.

**Comment by 1plus-1** [comment]
PR #25633 is created.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/packages/pull/25633
- https://github.com/openwrt/packages/issues/25625
- https://github.com/openwrt/openwrt/issues/17385
- https://github.com/openwrt/openwrt/issues/17392
