### ISSUE TITLE
[Question] Regarding adding some packages (miredo, tcpreplay)

### ISSUE THREAD

**Issue by commodo** [openwrt/packages#2574]
@sbyx @jow- @blogic @hnyman 
Hello,

I've been wanting to add 2 packages in the feeds and add me as maintainer to them.
Since squashfs-tools, Hannu said that he is hesitant to add new packages.
And I can understand that the build resources are limited.

So, then a feedback request regarding:
* miredo : http://www.remlab.net/miredo/  this is another IPv6 tunnel-through IPv4 suite + service; I saw that there are some packages that may already do some tunneling ; some in openwrt/package/network/ipv6 ; i will admit they're not too intuitive about using them (the scripts) and I did not take the time yet to understand them ; so if there are any docs about them, please point me into the right direction ; then there's aiccu, but that seems like you need some account creation ; the question here: would it make sense to add miredo to the feeds ? or is too much duplication ? (this package was present in the old packages, but it may make sense to use something else for IPv6-thru-IPv4 tunneling)
* tcpreplay: http://tcpreplay.appneta.com/ ;  this wasn't in the old packages (as far as I can tell), so this would be a new package ; we're trying to integrate this tool into our testsuite to automate some tests for some modules ; but it looks pretty neat because it looks like it can inject packets into interfaces which then can help with testing various protocol modules (like lldp, stp, and others that I don't know of). Question is: would we want to add it to the feeds ?

For both packages, I'm fine if the answer is no.
I thought I'd open a issue and ask before doing any PRs.

Thanks
Alex

**Comment by yousong** [comment]
Now tcpreplay has been merged.  I think just opening another pull request is the way to go.

Close this for it received no update for the past 4 months
