### ISSUE TITLE
How to add adblock rules outside default rules list

### ISSUE THREAD

**Issue by likemelikeit** [openwrt/packages#2579]
I want to make this  rule (no include in adblock package )`https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt` enable in adblock，could someone tell me how to do this?

**Comment by hnyman** [comment]
I have no idea what you do mean by that...
Please clarify the title and explain your question more clearly

**Comment by likemelikeit** [comment]
@hnyman I'm sorry for my poor expression，the trouble is： I want to use the adblock rule (https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt) in adblock package, the key point is it do not support by default.
I have try to add the bellow to `adblock.conf` before building package ,but it didn't work.
 `config source 'CJX'
	option enabled '1'
	option adb_src 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt&ruleset=rset_CJX'
	option adb_srcdesc 'personal use'
`

**Comment by hnyman** [comment]
I think that you also need to add the correct awk string definition for parsing the list contents (as various blocklists have different formats). See here:
https://github.com/openwrt/packages/blob/master/net/adblock/files/adblock-helper.sh#L170

@dibdot should know better.

**Comment by dibdot** [comment]
@hnyman @likemelikeit In adblock 1.0.x this is (partly) hardcoded in adblock-helper.sh, you cannot add new source sites on your own. Please use the static blacklist for manual domain additions.
In the next release cycle adblock 1.1.x this will be more flexible and the user can add new sources as you've mentioned above.
Regarding your posted list: It's a stripped down easylist. Adblock already includes easylist/ruadlist, see here: [https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt](url).
As adblock works on domain level, only "full domains" can be taken from the easylist. Full domains in easylist are qualified by "|| <domain>^" ... in your list there is not a single "full domain".

**Comment by likemelikeit** [comment]
@hnyman @dibdot Thanks very much.
