### ISSUE TITLE
sqlite version needs to be updated

### ISSUE THREAD

**Issue by mayank-sirotiya-imgtec** [openwrt/packages#2615]
As of now sqlite is getting downloaded from https://www.sqlite.org/download.html.
However, the current version in Makefile is 3.12.0, whose tar has been removed from download link above. 
Hence, version should be bumped up to 3.12.2.

**Comment by champtar** [comment]
they usually don't delete old version, but according to
https://www.sqlite.org/news.html
there is a nasty regression in 3.12.0 and 3.12.1 that's why they removed it i think

just curious, what do you do with sqlite3?

**Comment by mayank-sirotiya-imgtec** [comment]
we want i2c-tools in our project, and somehow if we enable it, OpenWrt starts building sqlite3 also.
