### ISSUE TITLE
 Tor Hidden service hostname resets after reboot

### ISSUE THREAD

**Issue by Smim0** [openwrt/packages#2624]
Hello,

I installed tor on my router Huawei EchoLife HG556a Ver A with the lastest openwrt version Chaos Calmer 10.05.1 and I activated a hidden service to ssh into the router from outside my network. Tor works fine but it generates a new hostname/private_key after every reboot, I looked all around and it seems that nobody has this issue. Can you please help?

**Comment by Smim0** [comment]
by the way, /etc/init.d/tor restart does not reset the hostname. It only does if i reboot the router

**Comment by hauke** [comment]
You should store the key on some storage which gets preserved over reboots

**Comment by EricLuehrsen** [comment]
Probably these two are related: https://github.com/openwrt/packages/issues/4391

**Comment by rfc2822** [comment]
I have moved the hidden service directory to my mSATA SSD and now it works :)

**Comment by Jookia** [comment]
I think it should be default to have it stored on the overlay. I don't think it's expected behaviour for hidden service keys to reset on reboot- it defeats the purpose of having a hidden service.

**Comment by nwf** [comment]
There should be no concern of flash durability storing the hidserv director(y|ies) in the overlay; AFAIK the private key and corresponding hostname are written at initialization and, thereafter, the directories are read-only.

**Comment by neheb** [comment]
Is this still an issue?

**Comment by Jookia** [comment]
I haven't used Tor on OpenWrt for a long time, but unless the package has specific support for this then I would think not

**Comment by Smim0** [comment]
The issue is solved

Enviado desde mi iPhone

El 12 ene 2020, a las 5:02, Jookia <notifications@github.com> escribió:

﻿

I haven't used Tor on OpenWrt for a long time, but unless the package has specific support for this then I would think not
