### ISSUE TITLE
Can't login coova-chilli miniportal

### ISSUE THREAD

**Issue by Benelli86** [openwrt/packages#2657]
Hi all.
1) Sorry for my english
2) I have mikrotik rb751u-2hnd with opewrt (OpenWrt Barrier Breaker 14.07 / LuCI Trunk (0.12+svn-r10530)) and package coova-chilli; 
captive portal works fine, i view login.chi page, but when i press "Login & Accept Terms", in chrome i have "ERR_CONN_RESET". 
In other browser i have empty page.
Why?
Please help me.
I'm desperate, I do not know what to do.
Thank's.

**Comment by diizzyy** [comment]
@Benelli86 
Still an issue?
