### ISSUE TITLE
coovachilli - Problem with mikrotik rb912uag-5hpnd

### ISSUE THREAD

**Issue by Benelli86** [openwrt/packages#2696]
Hi all. I have a problem with mikrotik rb912uag-5hpnd and covachilli hotspot.
It seems that coovachilli don't know where is his wan interface.
Part of chilli defaults conf is:
    HS_WANIF=eth0          # WAN Interface toward the Internet
    HS_LANIF=wlan0
I have a bridge with eth0 and wlan0 on my routerboard, coovachilli correctly assigns ip and dns at wireless clients, but they can not navigate (even in the walled garden).

**Comment by reinerotto** [comment]
I would try to break the bridge.

**Comment by kaloz** [comment]
this is a configuration issue, adjust your setup or the configuration for your needs
