### ISSUE TITLE
Possible compilation problems with motion on ar71xx and x86

### ISSUE THREAD

**Issue by ghost** [openwrt/packages#2702]
@roger- 

It's kind of strange. Despite the following message in compile.txt (using build logs):

  Configure status
  motion 3.4.0-Git-78ba2da

OS : Linux
pthread support: No

*\* Fatal Error YOU MUST HAVE pthread Support *

The build completes successfully. I haven't yet had the opportunity to test if motion actually works and pthreads is gettinging linked despite configure not finding it, or if this is a case where 'bad things can happen at runtime'.

**Comment by roger-** [comment]
Can you see if #2575 fixes this?

**Comment by dfc-d** [comment]
Hi,

I actually created that patch, but closed it because it doesn't solve
the problem.  I haven't had the time to really dig into what the issue
is.  It is most peculiar.

It may only have building from SDK, I'm not sure.

Regards,

Daniel

**Comment by roger-** [comment]
Ah sorry, missed that.

I haven't compiled motion in a while, so I'm assuming some recent change broke it. I'll try to do some investigation.

**Comment by karlp** [comment]
related to https://github.com/openwrt/packages/issues/1814 ?

**Comment by diizzyy** [comment]
@thess @hnyman 
Motion compiles, close.
