### ISSUE TITLE
debootstrap gives a 404 over http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap-udeb_1.0.80_all.udeb

### ISSUE THREAD

**Issue by slemke76** [openwrt/packages#2712]
It seems this file is gone:
debootstrap gives a 404 over http://ftp.debian.org/debian/pool/main/d/debootstrap/debootstrap-udeb_1.0.80_all.udeb

there is a debootstrap-udeb_1.0.81_all.udeb

**Comment by dangowrt** [comment]
Fixed in https://github.com/openwrt/packages/commit/9623e833e2e56f731612037d35a410a905cbcf3f
Thanks for reporting!
