### ISSUE TITLE
Build of libvips broken

### ISSUE THREAD

**Issue by slemke76** [openwrt/packages#2719]
Build of libvips is actually broken, see:
http://buildbot.openwrt.org:8010/broken_packages/au1000/vips/compile.txt

The reason is simple - there is a Typo mistake in 
feeds/packages/libs/vips/patches/001-no_cpp.patch

Line #101:

wrong:
 # DLLs need dependent libs there too ... put @VIPS_LIBS@ at the end
correct:
 # DLLs need dependant libs there too ... put @VIPS_LIBS@ at the end

(dependent != dependant)

Thanks,
Sebastian

**Comment by hnyman** [comment]
Thanks. I fixed it by reverting #2594 for that file. It was originally broken by #2594 as that was thought to be typo by an automatic spellchecker...
