### ISSUE TITLE
http 404 : lua-bencode-2.1.0.tar.bz2

### ISSUE THREAD

**Issue by LipkeGu** [openwrt/packages#2726]
https://github.com/openwrt/packages/blob/master/lang/lua-bencode/Makefile#L14

does not exist (only a tar.gz is available =(

**Comment by LipkeGu** [comment]
```http://sources.lede-project.org/lua-bencode-2.1.0.tar.bz2```
works...

**Comment by hnyman** [comment]
I don't see a bug there. The package Makefile uses "hg" (mercurial) to download the source and then to store the downloaded source as a newly generated bz2 archive. Both Openwrt and LEDE buildbot have recently built the package ok.
