### ISSUE TITLE
which version of wget is used depends on order installed

### ISSUE THREAD

**Issue by ghost** [openwrt/packages#2728]
Because wget vs. wget-nossl has been packaged to avoid conflicts with the old busybox wget by calling the binary wget-ssl and wget-nossl, these packages incorrectly do not conflict with each other and because of symlink funkiness which version you actually end up using depends on what order you installed the packages.

This is no longer necessary as the project no longer uses busybox wget, and installs a symlink to uclient-fetch in /bin, while these packages can be in /usr/bin.  Since in the default PATH puts /usr first, the full version would be preferred automatically rather than uclient-fetch symlink.

I am working on fixing this for a PR and include this in order to reference in the commit messages without making the commit message excessively large.

**Comment by neheb** [comment]
This is no longer relevant. wget uses ALTERNATIVES to work around this.
