### ISSUE TITLE
lm-sensors.org is down

### ISSUE THREAD

**Issue by Diftraku** [openwrt/packages#2794]
Currently, when trying to build from source with a configuration that pulls lm-sensors or i2c-tools (or anything that has the upstream code hosted on lm-sensors.org for that matter), `make download` will fail to checkout a copy of lm-sensors as the website it hosts is down.

It has been down for over 6 months but there are alternative clones hosted on GitHub: https://github.com/groeck/lm-sensors for lm-sensors and https://github.com/groeck/i2c-tools for i2c-tools
I suggest the Makefile should be changed to use that for the time being.

**Comment by hnyman** [comment]
@jow-  @dangowrt
