### ISSUE TITLE
python/python3 pip & setuptools use the same PKG_BUILD_DIR

### ISSUE THREAD

**Issue by zyxmon** [openwrt/packages#2806]
pip & setuptools have the same version number for python2.7 and python3 and have the same PKG_BUILD_DIR's - so parallel builds may fail because of it.

**Comment by zyxmon** [comment]
This is the simplest solution - https://github.com/Entware-ng/entware-packages/commit/8bd656d962320f32eceab709f474ba6a9b51383f

**Comment by hnyman** [comment]
@commodo 
any views on this?

**Comment by commodo** [comment]
yep ; it's on my todo list for today ; was busy during the week

**Comment by commodo** [comment]
ah wait ; saw the commits now ; that's a bit of a smaller change than i had in mind
@zyxmon did you try it and it worked ?
i'm not too savy with too many tar commands

I'd also extend the solution to python-pip & python-setuptools ; it would make them easier to find them in the build_dir

**Comment by zyxmon** [comment]
@commodo - yes it works in Entware. It should also work in Openwrt.

**Comment by commodo** [comment]
ok; cool :)
feel free to spin up PRs then

**Comment by commodo** [comment]
@zyxmon  are you also doing the changes for python-pip & python-setuptools ?
this is so that we don't collide ;

**Comment by zyxmon** [comment]
https://github.com/openwrt/packages/pull/2812
No, I do not change python-pip & python-setuptools

**Comment by zyxmon** [comment]
https://github.com/openwrt/packages/pull/2813

**Comment by hnyman** [comment]
This can be closed, right?

**Comment by commodo** [comment]
yes
