### ISSUE TITLE
[Request sound packages] sc2mpd & mpd2sc : stream PC sound (no lag)

### ISSUE THREAD

**Issue by schmurtzm** [openwrt/packages#2810]
sc2mpd and mpd2sc works with upmpdcli. 
It allow to send or receive Linn's songcast audio stream from/to a computer. sc2mpd is a receiver and  mpd2sc is a sender.

Songcast protocol is very interesting because it is an easy way to send sound from a computer to openWRT devices with low latency. There's already some softwares that acts as senders ([upplay](https://www.lesbonscomptes.com/upplay/index.html), [songcast](http://www.linn.co.uk/software#songcast))

Sources are here (same sources repo than upmpdcli).
https://github.com/medoc92/sc2mpd

If someone is able to create a package for it, it can be interesting :)
I can help for tests.

**Comment by mhei** [comment]
I agree that this might be interesting :smile: However, I'm closing this issue due to long inactivity. It seems that nobody else is interested in doing the initial work.
