### ISSUE TITLE
How to deal with not-yet-answered PRs?

### ISSUE THREAD

**Issue by bk138** [openwrt/packages#2818]
This is more like a meta-issue, sry for making that much noise but I couldn't find any docs abtout this. 

I have a PR https://github.com/openwrt/packages/pull/2626 that's been lingering for over a month now. Question: What is the preferred way to ask about PR status?

**Comment by jow-** [comment]
Hi @bk138 - no it is fine to make fuzz about it and I am sorry that nobody took care of it until now :(
The lack of any feedback indicates that your PR is formally fine - I guess not too many people deem a standalone `gzip` to be important so noone bothered to comment on it.

**Comment by jow-** [comment]
I think it boils down to the fact that we need more repository wide maintainers.
@openwrt/owners - any suggestions?

**Comment by jow-** [comment]
Pinging @openwrt/package-maintainers too.

**Comment by bk138** [comment]
Pinging those seems like a way to go, thanks
