### ISSUE TITLE
package openvpn-easy-rsa does not mark entire directory /etc/easy-rsa/keys to be preserved on a system upgrade

### ISSUE THREAD

**Issue by TimMillerDyck** [openwrt/packages#2864]
Hello, package openvpn-easy-rsa places generated certs in the directory /etc/easy-rsa/keys/ . However, this directory is not marked to be preserved in a system upgrade, resulting in these files being lost when OpenWrt is upgraded.

Currently, only serial and index.txt are preserved in this folder, plus /etc/easy-rsa/vars,

/lib/upgrade/keep.d# opkg list-changed-conffiles | grep easy
/etc/easy-rsa/keys/serial
/etc/easy-rsa/keys/index.txt
/etc/easy-rsa/vars

Fix:
- Create a text file /lib/upgrade/keep.d/openvpn-easy-rsa
- Contents of the file are the file and directory to preserve on a sysupgrade:
/etc/easy-rsa/keys/

Thanks,
Tim Miller Dyck

**Comment by yousong** [comment]
`openvpn-easy-rsa` is part base packages and you may get more timely response by raising the issue up there at the mailing list.

At the moment, you can consider adding those directories to `/etc/sysupgrade.conf` and see if they are preserved properly (they should :).
