### ISSUE TITLE
librpc: Can this be used instead of libtirpc?

### ISSUE THREAD

**Issue by Xotic750** [openwrt/packages#2871]
`portmap` does not appear to support IPv6, `rpcbind` appears to be it's replacement and does support this. To build `rpcbind` it depends on `libtirpc`, but all `rpc` dependant packages in OpenWRT/LEDE appear to use `librpc` (a fork from `uClibc`). Would using `librpc` for `rpcbind` (if the API is compatible) continue to allow IPv6 support and does `librpc` allow support of `krb5` like with `libtirpc`? I tried to find information but have not had any success.

For example `nfs-utils` say that `libtirpc` is required, however it is being built against `librpc`.

Note: I did try to compile `rpcbind` against `librpc` but it threw an error during compile.

**Comment by Andy2244** [comment]
@Xotic750 I'm working on this currently, trying to remove librpc completely and replacing it with libtirpc. Just finished creating the rpcbind package.

**Comment by Andy2244** [comment]
@Xotic750 @tripolar 

This can be closed as well.
