### ISSUE TITLE
stunnel - "Segmentation fault"

### ISSUE THREAD

**Issue by mdmrm** [openwrt/packages#2879]
I can't run the stunnel program 

config : stunnel.conf
; Drop privileges
;setuid = nobody
;setgid = nogroup

; When running under procd, stay in foreground
;foreground = yes

; Don't log to stderr, use syslog
;syslog = yes
output = /home/log/stunnel.log
pid = /tmp/stunnel.pid
sslVersion = all
; 1-7. Use 7 for greatest verbosity
debug = 7
;cert = /etc/stunnel/stunnel.pem
; Starting here, enter your services or uncomment the examples

; Example:
; If your local httpd does not support HTTPS, use stunnel in remote
; mode to forward TLS connections coming in on port 443 to non-TLS
; on port 80.
; Make sure that the cert is available.
[openvpn]
accept = 1443
connect = 11194
cert = /etc/stunnel/stunnel.pem

create certification :
openssl req -new -x509 -keyout stunnel.pem -out stunnel.pem -days 365 -nodes

when run 
stunnel /etc/stunnel/stunnel.conf
I get the message :
Segmentation fault
Any other information on the dmesg/ syslog.

detail of stunnel 

2539ccaf517ef070bacb4aa9a8f72d96  /usr/bin/stunnel

[.] stunnel 5.14 on mips-openwrt-linux-gnu platform
[.] Compiled with OpenSSL 1.0.2d 9 Jul 2015
[.] Running  with OpenSSL 1.0.2g  1 Mar 2016
[.] Update OpenSSL shared libraries or rebuild stunnel
[.] Threading:FORK Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI

System information
OpenWrt Chaos Calmer 15.05.1 (r49294)                        |

root@OpenWrt:~# mount
rootfs on / type rootfs (rw)
/dev/root on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/sda1 on /overlay type ext3 (rw,relatime,data=ordered)  -> EXTROOT
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)

root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    7.0G      1.2G      5.5G  17% /
/dev/root                 2.5M      2.5M         0 100% /rom
tmpfs                    61.5M    260.0K     61.3M   0% /tmp
/dev/sda1                 7.0G      1.2G      5.5G  17% /overlay
overlayfs:/overlay        7.0G      1.2G      5.5G  17% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by yousong** [comment]
With provided info I think you may want to investigate the following lines

```
[.] stunnel 5.14 on mips-openwrt-linux-gnu platform
[.] Compiled with OpenSSL 1.0.2d 9 Jul 2015
[.] Running with OpenSSL 1.0.2g 1 Mar 2016
[.] Update OpenSSL shared libraries or rebuild stunnel
```

I just built and tried stunnel 5.20 with LEDE malta in QEMU and it worked just fine.  The first few lines are as the following

```
2016.08.02 03:24:28 LOG5[ui]: stunnel 5.20 on mips-openwrt-linux-gnu platform
2016.08.02 03:24:28 LOG5[ui]: Compiled/running with OpenSSL 1.0.2h  3 May 2016
```

I am going to close this and if the issue still persists feel free to reopen it.
