### ISSUE TITLE
pythonX-distutils: exe files packed

### ISSUE THREAD

**Issue by ryzhovau** [openwrt/packages#2894]
`python_distutils` ipk package contains:
```
/tmp # find /lib/python2.7/ -name *.exe
/lib/python2.7/distutils/command/wininst-9.0.exe
/lib/python2.7/distutils/command/wininst-9.0-amd64.exe
/lib/python2.7/distutils/command/wininst-8.0.exe
/lib/python2.7/distutils/command/wininst-7.1.exe
/lib/python2.7/distutils/command/wininst-6.0.exe
/tmp # find /opt/lib/python2.7/ -name *.exe | du -hLs
3.4M    .
```
The same with `python3_distutils`.

**Comment by ryzhovau** [comment]
@commodo

**Comment by commodo** [comment]
[ i don't always respond in the weekends ; especially now with the summer high temperatures ]

will take a look ; i thought those were not packaged ;
thanks for reporting

**Comment by commodo** [comment]
PRs https://github.com/openwrt/packages/pull/2901  &  https://github.com/openwrt/packages/pull/2902

Thanks again
