### ISSUE TITLE
net/vpnc: include reboot disclaimer in readme

### ISSUE THREAD

**Issue by TaiSHiNet** [openwrt/packages#2908]
Hi,

You should include a 'reboot' disclaimer on the README. 
Even if you install the package you need to, else you wont get ANY output when trying to ifup

Bests

**Comment by yousong** [comment]
ping vpnc maintainer @danielg4 :)

**Comment by danielg4** [comment]
I keep rereading the above, but somehow, I still don't understand what you meant.

**Comment by TaiSHiNet** [comment]
If you don't reboot after installing vpnc packages and try to get it working it'll just return... nothing (I mean literally nothing, even exit code 0 on commands).
So what I mean is you should add a small disclaimer, note, postit or meme saying "Please reboot after installing this module for it to be usable"

**Comment by yousong** [comment]
After checking `files/vpnc.sh`, I think it's just that `netifd` needs a restart to load vpnc as a new protocol.  @TaiSHiNet , can you find time to give it a try?

**Comment by danielg4** [comment]
Restarting netifd may disrupt SSH, so that's not a huge distinction in all practicality…

**Comment by yousong** [comment]
Restarting netifd will cause the ssh traffic hold for a few seconds and the session should resume if everything goes okay.  I am pretty sure I have done this many times before.

**Comment by TaiSHiNet** [comment]
Restarting network wont disrupt SSH, will behave as @yousong said. I'm not sure if it'll make vpnc work.
Can't test right now, router is at home.

**Comment by danielg4** [comment]
The disclaimer is merged now. Oh well.

**Comment by yousong** [comment]
Close this one as the real cause of issue is found and suggestions for reboots is added anyway ;)
