### ISSUE TITLE
block-mount: "this file has been obseleted...."

### ISSUE THREAD

**Issue by MrM40** [openwrt/packages#2958]
Should this package be updated or I'm reading the error message correctly?

**INSTALLING:**
root@Router12:~# opkg install block-mount
Installing block-mount (2016-01-10-96415afecef35766332067f4205ef3b2c7561d21) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/base/block-mount_2016-01-10-96415afecef35766332067f4205ef3b2c7561d21_ar71xx.ipk.
Configuring block-mount.
**this file has been obseleted. please call "/sbin/block mount" directly**
block: /dev/mtdblock3 is already mounted

**UNINSTALLING:**
root@Router12:~# opkg remove block-mount
Removing package block-mount from root...
**this file has been obseleted. please call "/sbin/block umount" directly**

Installed/removed on chaos_calmer/15.05.1/ar71xx
TP-Link 1043ND

**Comment by yousong** [comment]
The message came from `/etc/init.d/fstab` which I guess is still there for compatibility reasons.  Anyway I am going to close this one as the package is part of base pacakges and issues should be directed to mailing list for timely responses.
