### ISSUE TITLE
qos-scripts generate.sh does not sanitize user input

### ISSUE THREAD

**Issue by a1291762** [openwrt/packages#2965]
I have chaos calmer (15.05.1) with luci-app-qos and qos-scripts. The generate.sh from qos-scripts does not sanitize user input properly. In particular, I had an issue because I used a single quote in the comment field (eg. Limit User's Bandwidth). The /etc/config/qos file has option comment 'Limit User'\''s Bandwidth' so I guess it's handling it properly but generate.sh just dumps the string into a single-quote shell string so it looks like iptables ... --comment 'Limit User's Bandwidth'. This breaks the rest of the script.

**Comment by yousong** [comment]
Hi,

`qos-scripts` is part of the base packages which means you'd better post to the mailing list (let it be either `openwrt-devel` or `lede-dev`) for further responses, so I am closing this one.

The content of uci config files are to be parsed by both shell and C code, and in this case the result was again feeded as arguments to another shell command, so my advice is to avoid using such "dangerous" characters in uci unless you are 100 percent sure the outcome.
