### ISSUE TITLE
aria2c 1.24 or 1.25 not running

### ISSUE THREAD

**Issue by hostkit** [openwrt/packages#2985]
Hello @kuoruan 
1. i have been installed aria2 1.25 or aria2 1.24 when i want to start aria2 /usr/bin/aria2c said not found but this file exist, if im replaced with older version work normally? can you help me?

2. after you modif /etc/init.d/aria2
```
+	option_disabled "$s" 'enable_log' || {
 +                touch "$log_file"
 +                echo -e "log=$log_file" >> $config_file
 +        }
```
/etc/init.d/aria2 not working, but if this line remove work normallly

**Comment by kuoruan** [comment]
if you want to use aria2 log, you should change user to root.

**Comment by kuoruan** [comment]
Ok, I well make a change, if chose root user, then can enable aria2 log.

**Comment by hostkit** [comment]
for question number 1, why it's  happen?
working if aria2c repalce using aria2c from old version?

**Comment by kuoruan** [comment]
Try chmod +x /usr/bin/aria2c

**Comment by kuoruan** [comment]
By the way, do you have a QICQ or WeChat?

**Comment by hostkit** [comment]
Only WhatsApp and bbm :)

**Comment by hostkit** [comment]
not working chmod +x
![aria2](https://cloud.githubusercontent.com/assets/3790389/17083543/d265886e-51ce-11e6-81fe-80365acc2cea.PNG)

**Comment by kuoruan** [comment]
Where your package from?

**Comment by hostkit** [comment]
download from downloads.openwrt.org snapshot, but my firmware 15.0.5, firmware 15.0.5.1 not working too. my connection very limited so unable build from source, i have vps but always build  fail. g++ kill selft :(

**Comment by hostkit** [comment]
i always wait update from snapshot when you update it

**Comment by kuoruan** [comment]
What's your device model, I can build one for you.

**Comment by hostkit** [comment]
TLMR3420v1 standard

**Comment by hostkit** [comment]
Its true step by step compile packages from source ?
> git clone https://git.openwrt.org/openwrt.git
> cd openwrt
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> make menuconfig
> make tools/install
> make toolchain/install
> make package/aria2/{clean,compile,install} V=99 DEVELOPER=1

**Comment by kuoruan** [comment]
You are using 15.05, you should get source use ```git clone git://git.openwrt.org/15.05/openwrt.git```

All version are here: https://dev.openwrt.org/wiki/GetSource

**Comment by hostkit** [comment]
if i am use 15.0.5 can i compile your luci-aapp-aria2 and aria2 updated from github?
i think my vps very low :(

**Comment by kuoruan** [comment]
I think they can use both in Chaos Calmer and Designated Driver.

**Comment by kuoruan** [comment]
download this: https://soft.kuoruan.com/openwrt/ar71xx/packages/packages/aria2_1.25.0-2_ar71xx.ipk

**Comment by hostkit** [comment]
ok aria2 work normally, why this happen?

**Comment by kuoruan** [comment]
Maybe it's because OpenWrt switches to musl by default, replacing uClibc in Designated Driver.

**Comment by hostkit** [comment]
how to change uclibc on image generator or must be use  source

**Comment by kuoruan** [comment]
You mast use source to build it, and uClibc is removed in trunk.
