### ISSUE TITLE
update URL for spdns is wrong, should be spdyn instead of spdns

### ISSUE THREAD

**Issue by pengel222** [openwrt/packages#2991]
Setting up ddns in OPenWRT for spdns I see warnings on spdns side:
Bitte verwenden Sie als Update-Server in Ihrem Client "update.spdyn.de" (Aktuelle Einstellung: update.spdns.de)
I believe the file /usr/lib/ddns/services needs to be changed.
Line
"spdns.de"  "http://[USERNAME]:[PASSWORD]@update.spdns.de/nic/update?hostname=[DOMAIN]&myip=[IP]"
to
"spdns.de"  "http://[USERNAME]:[PASSWORD]@update.**spdyn**.de/nic/update?hostname=[DOMAIN]&myip=[IP]"

**Comment by chris5560** [comment]
Thanks for your advice.
Will be part of next ddns-script update.

**Comment by diizzyy** [comment]
@chris5560 
Can we close this?

**Comment by mhei** [comment]
I checked that this change was part of the update in #3134, so we can close this.
