### ISSUE TITLE
Cannot download libffi during compilation

### ISSUE THREAD

**Issue by DarthLabonne** [openwrt/packages#3000]
Hello everyone,

I've been trying to compile OpenWRT today by using the command `make -j1 V=s`

But somehow, every mirror for libffi-3.2.1 seem to be down (Connection timeout or 404) and compilation fails because of it.

I configured OpenWRT with "Advanced configuration options (for developers)", "Build the OpenWrt SDK" and Python 3 packages.

Can another mirror be set, do I just need to wait for mirrors to be back online again?

**Comment by DarthLabonne** [comment]
Ok, so after searching for the problem, I found that the FTP links do work but my company's firewall was blocking the protocol.

As for the HTTP links, they ARE down, though.

**Comment by yousong** [comment]
You can consider downloading the tarball from another place and do the verification of md5sum manually.  Place the tarball inside the download directory (usually `dl/`) and the build system should pick it up.

Feel free to reopen this issue if the above method does not work (it should...)
