### ISSUE TITLE
Proposal for new package (sunwait)

### ISSUE THREAD

**Issue by szygmunt** [openwrt/packages#3034]
Please consider add a new package I mention in subject. Actually I found Makefile (https://github.com/probonopd/sunwait-for-openwrt), sucessfully compiled but can't set east longitude. Sunwait always set it to default value (Alexandria USA). As I know it's problem with parsing "E" by uClibc.

**Comment by diizzyy** [comment]
@thess @hnyman 
Not an issue, please close.

@szygmunt 
Please provide a pull request.
