### ISSUE TITLE
node: Raspberry Pi3 / brcm2710 errors due to CPU/arch

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#3057]
nodejs has multiple build issues see #3056 , argument list too long due to internal openssl (see https://github.com/imyller/meta-nodejs/issues/9 ) and multiple CPU support issues like this one:

brcm2710 (Raspberry Pi-3) is armv8-a 
other ones Raspis (brcm2709/brcm2708) are armv7-a

-mpcu=cortex-a53 emits ARM_ARCH 8

armv8-a is NOT supported by internal deps/v8 in v4.x in nodejs 
upstream commit is : https://github.com/v8/v8/commit/1d14ebfcc112b0ae8efa7568ceb9e8228142eb6d

possible solutions:
- disable nodejs on brcm2710
- use armv7-a for brcm2710 / change include/target.mk 
- update nodejs from LTS to next LTS v6 (6.x) , see https://github.com/nodejs/LTS#lts_schedule
- reported on IRC & replicated locally

**Comment by yousong** [comment]
Close this since the node v6.11.2 in the repo now has a v8 with armv8-a support.
