### ISSUE TITLE
[Request | utils/collectd] Include collectd plugin 'tail_csv'

### ISSUE THREAD

**Issue by outofrange** [openwrt/packages#3083]
I would like to use CSV entries in collectd, together with luci-app-statistics, using [tail_csv](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_tail_csv), but there is no collectd-mod-tail-csv package available (since it's not included in collectd's Makefile...)

Is there any reason it's not there?

**Comment by hnyman** [comment]
Probably no special reason. I guess that the tail_csv (former "snort") plugin for collectd has slipped unnoticed at some collectd version upgrade. I guess that it can be added rather easily to collectd itself.

However, the Luci statistics part is probably more difficult, as the plugin allow rather versatile input.
