### ISSUE TITLE
crelay: please update package to new upstream version

### ISSUE THREAD

**Issue by ondrej1024** [openwrt/packages#3108]
@thess: I just pushed a [bugfix release](https://github.com/ondrej1024/crelay/releases/tag/V0.10.1) of crelay.

* Fixed compatibility issue with PiRelay app
* Added "-D" option for daemon mode ("-D" sends crelay to backgound, "-d" leaves crelay in foregraound)
* Modified file stream handling as temporary workaround for web server connection issue on some systems (OpenWRT)
* Added LDFLAGS parameter to linker command in Makefile (needed by OpenWRT)

This should remove the need for all of the current OpenWRT patches (except 010-link_with_ftdi1.patch).
Please test and update the OpenWRT package.
Thanks, Ondrej

**Comment by thess** [comment]
You got it: d210444434340a2eb73313797704fee00c12b7ad
