### ISSUE TITLE
( Help ) Install aria2 on Tplink 1043 had openwrt 

### ISSUE THREAD

**Issue by vuhongthao** [openwrt/packages#3156]
I had openwrt 15.05.1 on tplink 1043 with usb boot........Help me install aria2 1.25 with web gui...Tks

**Comment by vuhongthao** [comment]
I had openwrt 15.05.1 on tplink 1043 with usb boot........Help me install aria2 1.25 with web gui...Tks

**Comment by thess** [comment]
I think you will find a better chance for help if you post your problem to the OpenWrt forum (https://forum.openwrt.org) instead of here. This "issues" list is for problems with the items in the packages repository only.
