### ISSUE TITLE
when does openwrt support dgnd3700v2? Can i use dgnd2700v1's file?

### ISSUE THREAD

**Issue by ub001** [openwrt/packages#3182]
Please make sure that the issue subject starts with `<package-name>: ` so that it's easily identifiable.

This repo here is ONLY for packages maintained in this repo.  For base packages residing in the same repo as the build system and maintained by core devs, please consider opening tickets there for more timely responses

 - OpenWrt: https://dev.openwrt.org/newticket
 - LEDE: https://bugs.lede-project.org/
 - Most LuCI packages: https://github.com/openwrt/luci/issues

Thanks for your contribution
Please remove this text (before ---) and fill the following template
-------------------------------

Maintainer: @<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWRT/LEDE version)

Description:

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by yousong** [comment]
Close this one as it surely does not belong here.

@ub001 you may have a better chance of geting answers by

- checking the table of hardware in OpenWrt wiki
- checking whether the support is present in the code
- asking in the OpenWrt forum
- asking in the openwrt-users mailing list
- asking in the devel mailing lists

Well, you know the communication channel is kind of fragmented here and there, but this repo here is only for packages ;)
