### ISSUE TITLE
openconnect missing depencies

### ISSUE THREAD

**Issue by hongkongkiwi** [openwrt/packages#3301]
The openconnect package needs added to dependencies to compile:

`+p11-kit +libp11`

**Comment by nmav** [comment]
That should only be the case if you are building with openssl. Is that right?

**Comment by hongkongkiwi** [comment]
Yes, your correct, I'm building with OpenSSL, so I guess it would need to be for that optional case.

**Comment by nmav** [comment]
Would you like to submit a pull request that fixes it?
