### ISSUE TITLE
package elektra error

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#3309]
[ 56%] Linking C shared module ../../../lib/libelektra-syslog.so
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
[ 56%] Built target elektra-syslog
make[6]: Entering directory`/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
Scanning dependencies of target elektra-syslog-objects
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
make[6]: Entering directory`/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
[ 56%] Building C object src/plugins/syslog/CMakeFiles/elektra-syslog-objects.dir/syslog.c.o
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
[ 56%] Built target elektra-syslog-objects
make[6]: Entering directory`/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
Scanning dependencies of target elektra-tcl
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
make[6]: Entering directory`/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
[ 56%] Building CXX object src/plugins/tcl/CMakeFiles/elektra-tcl.dir/tcl.cpp.o
In file included from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib/gcc/i486-openwrt-linux-musl/5.3.0/include/xmmintrin.h:34:0,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib/gcc/i486-openwrt-linux-musl/5.3.0/include/x86intrin.h:31,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/i486-openwrt-linux-musl/bits/opt_random.h:33,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/random:50,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/bits/stl_algo.h:66,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/algorithm:62,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/fusion/sequence/intrinsic/swap.hpp:12,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/fusion/sequence/intrinsic.hpp:23,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/fusion/include/intrinsic.hpp:11,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/proto/fusion.hpp:22,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/proto/core.hpp:21,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/proto/proto.hpp:12,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/spirit/home/support/meta_compiler.hpp:19,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/spirit/home/qi/domain.hpp:15,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/spirit/home/qi/operator/sequence_base.hpp:15,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/spirit/home/qi/operator/expect.hpp:15,
                 from /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/boost/spirit/include/qi_expect.hpp:16,
                 from /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17/src/plugins/tcl/tcl.cpp:18:
/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib/gcc/i486-openwrt-linux-musl/5.3.0/include/mm_malloc.h:34:64: **error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier**
 extern "C" int posix_memalign (void **, size_t, size_t) throw ();
                                                                ^
In file included from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/cstdlib:72:0,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/ext/string_conversions.h:41,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/bits/basic_string.h:5251,
                 from /home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/i486-openwrt-linux-musl/include/c++/5.3.0/string:52,
                 from /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17/src/bindings/cpp/include/keyset.hpp:16,
                 from /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17/src/plugins/tcl/tcl.hpp:14,
                 from /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17/src/plugins/tcl/tcl.cpp:9:
/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/stdlib.h:99:5: error: from previous declaration 'int posix_memalign(void**, size_t, size_t)'
 int posix_memalign (void *_, size_t, size_t);
     ^
make[6]: *_\* [src/plugins/tcl/CMakeFiles/elektra-tcl.dir/tcl.cpp.o] Error 1
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
make[5]: *** [src/plugins/tcl/CMakeFiles/elektra-tcl.dir/all] Error 2
make[5]: Leaving directory`/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
make[4]: **\* [all] Error 2
make[4]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17'
make[3]: *** [/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/elektra-0.8.17/.built] Error 2
make[3]: Leaving directory`/home/main/x86/feeds/packages/libs/elektra'
make[2]: **\* [package/feeds/packages/elektra/compile] Error 2
make[2]: Leaving directory `/home/main/x86'
make[1]: *** [/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory`/home/main/x86'

**Comment by yousong** [comment]
Looks like this package now compiles and is present in LEDE snapshot download.
