### ISSUE TITLE
libpam: Fix  chaos_calmer  build with eglibc/glibc

### ISSUE THREAD

**Issue by earthGavinLee** [openwrt/packages#3316]
diff --git a/feeds/packages/libs/libpam/patches/006-fix_xdr.patch b/feeds/packages/libs/libpam/patches/006-fix_xdr.patch
index 9769506..3885fb7 100644
--- a/feeds/packages/libs/libpam/patches/006-fix_xdr.patch
+++ b/feeds/packages/libs/libpam/patches/006-fix_xdr.patch
@@ -4,7 +4,7 @@
  #endif
  #include "yppasswd.h"

-+#ifdef **UCLIBC**
++#if defined **UCLIBC** || defined **GLIBC**
 +
 +static const char xdr_zero[BYTES_PER_XDR_UNIT] = {0, 0, 0, 0};
 +

**Comment by diizzyy** [comment]
@earthGavinLee 
If is still an issue, please provide a proper pull request.

**Comment by diizzyy** [comment]
@thess @hnyman @dibdot 
CC isn't supported, close this one
