### ISSUE TITLE
tcp_wrappers: don't set LIBS=-lnsl when building with eglibc

### ISSUE THREAD

**Issue by earthGavinLee** [openwrt/packages#3327]
commit 4a6449a94e2e7756984db3efd9e69c446ebfa1cb
Author: gavin <gavin@gavin-Inspiron>
Date:   Mon Oct 10 06:33:20 2016 +0800

    tcp_wrappers: don't set LIBS=-lnsl when building with eglibc

diff --git a/feeds/packages/libs/tcp_wrappers/Makefile b/feeds/packages/libs/tcp_wrappers/Makefile
index 1ea637f..76cf1ac 100644
--- a/feeds/packages/libs/tcp_wrappers/Makefile
+++ b/feeds/packages/libs/tcp_wrappers/Makefile
@@ -32,11 +32,17 @@ endef
 
 TARGET_CFLAGS += $(FPIC)
 
+ifeq ($(CONFIG_EGLIBC_OPTION_EGLIBC_INET),y)
+TARGET_EXTRA_LIBS:=
+else
+TARGET_EXTRA_LIBS:=LIBS=-lnsl
+endif
+
 define Build/Compile   
        $(MAKE) -C $(PKG_BUILD_DIR) \
                $(TARGET_CONFIGURE_OPTS) \
                OPT_CFLAGS="$(TARGET_CFLAGS)" \
-               LIBS=-lnsl \
+               $(TARGET_EXTRA_LIBS) \
                NETGROUP= \
                VSYSLOG= \
                BUGS= \

**Comment by diizzyy** [comment]
Make this a pull request instead, with proper signoff and everything.
