### ISSUE TITLE
map: map-wan6_4 not configured in trunk

### ISSUE THREAD

**Issue by mikaabra** [openwrt/packages#3362]
---

Maintainer: @sbyx  (find it by checking history of the package Makefile)
Environment: OpenWrt r49971

Description:

I have an Internet connection without native IPv4. It provides IPv4 as a service using LW4o6. In CC, this works after installing "map" package and setting "WAN" to "unmanaged". I am using Netgear WNDR3800.

I then proceeded to try this on trunk/r49971 nightly build. Installed "map" package. I properly get DHCPv6-PD prefix configured, resolver etc using DHCPv6, but the LW4o6 tunnel is never configured. In the log I get:

Thu Oct 20 11:49:50 2016 daemon.notice netifd: wan6 (3998): Command failed: Unknown error
Thu Oct 20 11:50:31 2016 daemon.notice netifd: wan6 (3998): Command failed: Unknown error
Thu Oct 20 11:51:17 2016 daemon.notice netifd: wan6 (3998): Command failed: Unknown error
Thu Oct 20 11:52:02 2016 daemon.notice netifd: wan6 (3998): Command failed: Unknown error

DHCPv6 interaction looks fine:

11:53:32.138886 IP6 (flowlabel 0x278ba, hlim 1, next-header UDP (17) payload length: 135) fe80::224e:7fff:fe91:6957.546 > ff02::1:2.547: [udp sum ok] dhcp6 renew (xid=31c983 (elapsed-time 0) (option-request SIP-servers-domain SIP-servers-address DNS-server DNS-search-list SNTP-servers NTP-server AFTR-Name opt_67 opt_82 opt_83 opt_94 opt_95 opt_96) (client-ID hwaddr type 1 204e7f916957) (server-ID hwaddr type 1 fa163e6f3a21) (Client-FQDN) (IA_PD IAID:1 T1:0 T2:0 (IA_PD-prefix 2003:1c09:24:1580::/60 pltime:0 vltime:0)))
11:53:32.251103 IP6 (class 0xe0, hlim 30, next-header UDP (17) payload length: 283) fe80::8678:acff:fe4b:15cc.547 > fe80::224e:7fff:fe91:6957.546: [udp sum ok] dhcp6 reply (xid=31c983 (server-ID hwaddr type 1 fa163e6f3a21) (client-ID hwaddr type 1 204e7f916957) (IA_PD IAID:1 T1:45 T2:72 (IA_PD-prefix 2003:1c09:24:1580::/60 pltime:90 vltime:90)) (SIP-servers-domain sip1.lab.terastrm.net. sip2.lab.terastrm.net.) (DNS-server 2003:1b0b:fffa:ffff::fc71 2003:1b0b:fffa:ffff::fc72) (SNTP-servers 2003:1b0b:fffa:ffff::fc21 2003:1b0b:fffa:ffff::fc22) (AFTR-Name aftr.lab.terastrm.net) (opt_96))

No map-wan6_4 interface is created.

**Comment by feckert** [comment]
@mikaabra does is still an issue? If so please reopen or add a new issue
