### ISSUE TITLE
debootstrap: needs xzcat

### ISSUE THREAD

**Issue by chunkeey** [openwrt/packages#3365]
Maintainer: @dangowrt
Environment: Reboot (HEAD, r1935+3)
Description:
Hello,

I tried installing jessie via debootstrap on the HDD of a WNDR4700 router and ran into the following issue: 

```
# debootstrap --arch=powerpc jessie sda3/ http://ftp.de.debian.org/debian
[...]
E: Extracting .//var/cache/apt/archives/acl_2.2.52-2_powerpc.deb requires the xzcat command, which is not available
```

This was of course easily fixed by installing the xz .ipgk with opkg on the router and restarting the debootstrap again. This time, the debootstrap "installed successfully" the base system for the power-pc jessie chroot. And I could do a quick test run to confirm that the installation does work fine.

So, can you please add the xz dependency to the debootstrap package?

Regards,
Christian

**Comment by bobafetthotmail** [comment]
dependency to xz is added now.
