### ISSUE TITLE
ffmpeg-work branch

### ISSUE THREAD

**Issue by hnyman** [openwrt/packages#3397]
@thess 

Looks like you have accidentally(?) created the ffmpeg-work branch in the main Github repo...
https://github.com/openwrt/packages/branches

That should likely be removed. 
(there seems to be no new content, as the branch is just "98 commits behind master".)

**Comment by Noltari** [comment]
Removed since @thess has that branch on his personal repo too.

**Comment by thess** [comment]
OK - shouldn't have that
