### ISSUE TITLE
libs/opencv feed want compile.

### ISSUE THREAD

**Issue by vzhirov** [openwrt/packages#3414]
Menuconfig:
        CONFIG_PACKAGE_opencv = M
Want compile with error:
        libglib2-x.x.x.so not found
Fixed it simple.
        --- a/libs/opencv/Makefile
        +++ b/libs/opencv/Makefile
        @@ -37,7 +37,7 @@ define Package/opencv
           TITLE:=OpenCV
           URL:=http://opencv.org/
           MAINTAINER:=WRTnode Team pub@wrtnode.com
        -  DEPENDS:=+libpthread +librt +libstdcpp +zlib +libjpeg
        +  DEPENDS:=+libpthread +librt +libstdcpp +zlib +libjpeg +glib2
I verify. make world works now.
I looked on OpenCV sources in build dir. And it really contains references to glib2 headers and cmake files.

**Comment by taeasy** [comment]
Thanks

**Comment by dibdot** [comment]
If its still an issue provide a PR.
