### ISSUE TITLE
perl-cgi: missing sources

### ISSUE THREAD

**Issue by ryzhovau** [openwrt/packages#3428]
I know there's no maintainer for perl packages, so I leave this issue just for history.

There's no sources for `CGI-4.28.tar.gz`: neither on [author site](http://www.cpan.org/modules/by-module/CGI/LEEJO/), nor on OpenWrt mirrors. 

Still, you can [add LEDE sources mirror](https://github.com/Entware-ng/Entware-ng/commit/d3a47393fef1a5059e0600cca218864c939974b6) to fix that.

**Comment by hnyman** [comment]
fixed with b88eb1b6e1409ef87c7922aabb99b782f12a52de
