### ISSUE TITLE
net/haproxy  [request] upgrade to V1.6?

### ISSUE THREAD

**Issue by noci2012** [openwrt/packages#3439]
Maintainer: @heil 
Environment: turris omnia

Description: haproxy 1.6 supports the use of ssl_sni (Server Name Indication) which makes it an excelent choice for lightwaight proxying of SSL sessions. (ie. No certifcates on the proxy, no en/de cryption, just a pass-on to a backend node.)
(btw, not sure why the modules isn't available on the turris omnia)

**Comment by heil** [comment]
1.5.x also supports sni in tcp mode. so iam not sure whats your use case exaclty. haproxy 1.6 will increase in size about 100K. iam working on the 1.6 version, so stay tuned.

**Comment by heil** [comment]
upgraded to haproxy 1.6.9
