### ISSUE TITLE
rtl-ais compile failed

### ISSUE THREAD

**Issue by taeasy** [openwrt/packages#3466]
. /home/main/x86/include/shell.sh; gzip -dc /home/main/x86/dl/rtl-ais-20151213-b805be0164475e58a73b57763a8cbbf8a2bd0ded.tar.gz | tar -C /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.. -xf - 
touch /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.prepared_a13dcb475cfc9a683a70e7506e00b0a7
rm -f /home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.rtl-ais_installed
(cd /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/./; if [ -x ./configure ]; then find /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/ -name config.guess | xargs -r chmod u+w; find /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/ -name config.guess | xargs -r -n1 cp --remove-destination /home/main/x86/scripts/config.guess; find /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/ -name config.sub | xargs -r chmod u+w; find /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/ -name config.sub | xargs -r -n1 cp --remove-destination /home/main/x86/scripts/config.sub; AR="i486-openwrt-linux-musl-gcc-ar" AS="i486-openwrt-linux-musl-gcc -c -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=i486-openwrt-linux-musl-ld NM="i486-openwrt-linux-musl-gcc-nm" CC="i486-openwrt-linux-musl-gcc" GCC="i486-openwrt-linux-musl-gcc" CXX="i486-openwrt-linux-musl-g++" RANLIB="i486-openwrt-linux-musl-gcc-ranlib" STRIP=i486-openwrt-linux-musl-strip OBJCOPY=i486-openwrt-linux-musl-objcopy OBJDUMP=i486-openwrt-linux-musl-objdump SIZE=i486-openwrt-linux-musl-size CFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include " LDFLAGS="-L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib -znow -zrelro "   ./configure --target=i486-openwrt-linux --host=i486-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   ; fi; )
rm -f /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.configured_*
touch /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.configured_yyyyyyyy
CFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include " CXXFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include " LDFLAGS="-L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib -znow -zrelro " make -j1 -C /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/. AR="i486-openwrt-linux-musl-gcc-ar" AS="i486-openwrt-linux-musl-gcc -c -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=i486-openwrt-linux-musl-ld NM="i486-openwrt-linux-musl-gcc-nm" CC="i486-openwrt-linux-musl-gcc" GCC="i486-openwrt-linux-musl-gcc" CXX="i486-openwrt-linux-musl-g++" RANLIB="i486-openwrt-linux-musl-gcc-ranlib" STRIP=i486-openwrt-linux-musl-strip OBJCOPY=i486-openwrt-linux-musl-objcopy OBJDUMP=i486-openwrt-linux-musl-objdump SIZE=i486-openwrt-linux-musl-size CROSS="i486-openwrt-linux-musl-" ARCH="i386" ;
make[3]: Entering directory '/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213'
i486-openwrt-linux-musl-gcc -c rtl_ais.c -o rtl_ais.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c convenience.c -o convenience.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/aisdecoder.c -o aisdecoder/aisdecoder.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/sounddecoder.c -o aisdecoder/sounddecoder.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/lib/receiver.c -o aisdecoder/lib/receiver.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/lib/protodec.c -o aisdecoder/lib/protodec.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/lib/hmalloc.c -o aisdecoder/lib/hmalloc.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc -c aisdecoder/lib/filter.c -o aisdecoder/lib/filter.o -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213:rtl-ais-20151213 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include  -I./aisdecoder -I ./aisdecoder/lib -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include/
i486-openwrt-linux-musl-gcc rtl_ais.o convenience.o ./aisdecoder/aisdecoder.o ./aisdecoder/sounddecoder.o ./aisdecoder/lib/receiver.o ./aisdecoder/lib/protodec.o ./aisdecoder/lib/hmalloc.o ./aisdecoder/lib/filter.o -o rtl_ais -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib -znow -zrelro  -lpthread -lm -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/lib -lrtlsdr -lusb-1.0
./aisdecoder/lib/filter.o: In function `__mac_g':
filter.c:(.text+0x0): multiple definition of `__mac_g'
./aisdecoder/lib/receiver.o:receiver.c:(.text+0x0): first defined here
./aisdecoder/lib/filter.o: In function `__mac_c':
filter.c:(.text+0x1f): multiple definition of `__mac_c'
./aisdecoder/lib/receiver.o:receiver.c:(.text+0x1f): first defined here
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'rtl_ais' failed
make[3]: *** [rtl_ais] Error 1
make[3]: Leaving directory '/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213'
Makefile:53: recipe for target '/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.built' failed
make[2]: *** [/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/rtl-ais-20151213/.built] Error 2
make[2]: Leaving directory '/home/main/x86/feeds/packages/utils/rtl-ais'
package/Makefile:196: recipe for target 'package/feeds/packages/rtl-ais/compile' failed
make[1]: *** [package/feeds/packages/rtl-ais/compile] Error 2
make[1]: Leaving directory '/home/main/x86'
/home/main/x86/include/toplevel.mk:192: recipe for target 'package/feeds/packages/rtl-ais/compile' failed
make: *** [package/feed

**Comment by hnyman** [comment]
This is likely related to 32bit x86, as both Openwrt and LEDE buildbots build it ok for 64bit x86 and other platforms.

you might test similar solutions as mentioned in #3655 

cc to maintainer: @nunojpg

**Comment by nunojpg** [comment]
@taeasy Since there is no testing automation for 32bits, and I don't run 32bits personally, there is no support for this package for x86 32bit.
