### ISSUE TITLE
bind: configure script checks for libjson header files in host filesystem

### ISSUE THREAD

**Issue by rah2501** [openwrt/packages#3468]
Maintainer: @nmeyerhans
Environment: LEDE packages https://git.lede-project.org/feed/packages.git

Description: The configure script searches hard coded fully-qualified directory names for libjson header files:

```
                for d in /usr /usr/local /opt/local
                do
                        if test -f "${d}/include/json/json.h"
```

The configure script fails if the host filesystem's libjson headers do not match the target's (as is the case with a Debian Jessie host).

**Comment by nmeyerhans** [comment]
This was fixed some time ago with 66231b6d24c2e8d96c6b5da0ce90410f43a34fb2
