### ISSUE TITLE
btrfs-progs maintainership

### ISSUE THREAD

**Issue by dangowrt** [openwrt/packages#3519]
I don't have any testbed for btrfs left at this point and thus cannot run-time test this package.
If @miska and folks at @CZ-NIC who are active btrfs users would like to take over, that'd be great!

**Comment by diizzyy** [comment]
While waiting for a new maintainer, create a pull request and remove yourself as maintainer.

**Comment by dangowrt** [comment]
see also https://github.com/openwrt/packages/pull/4385#issuecomment-306219893
