### ISSUE TITLE
<pip3> incorrect shebang

### ISSUE THREAD

**Issue by Strykar** [openwrt/packages#3521]
Python3 and pip3 compile and install fine.
```
root@apu:~# ls -l /usr/bin/pip3.5
-rwxr-xr-x    1 root     root           451 Oct 27 18:59 /usr/bin/pip3.5
root@apu:~# ls -l /usr/bin/pip3
lrwxrwxrwx    1 root     root             6 Oct 27 18:59 /usr/bin/pip3 -> pip3.5
root@apu:~# /usr/bin/pip3 install urllib
/bin/ash: /usr/bin/pip3: not found
root@apu:~# /usr/bin/python3 -V
Python 3.5.2
root@apu:~# uname -a
Linux apu 4.4.27 #0 SMP Thu Oct 27 13:29:36 2016 x86_64 GNU/Linux
```
`/usr/bin/pip3`'s shebang is my `#!/build_dir_path/staging_dir/target-x86_64_musl-1.1.15/host/bin/python3`
It should instead be `#!/usr/bin/python3`

**Comment by commodo** [comment]
hey ; i think i know what the issue is;
will check ; seems similar to Python [ where this is fixed ]

thanks for reporting
