### ISSUE TITLE
jool: does not compile for ar71xx

### ISSUE THREAD

**Issue by anomeome** [openwrt/packages#3657]
[This](https://github.com/openwrt/packages/pull/3604) applied to current LEDE build yields [this](http://ix.io/1MxL) in my source tree, building to target C7V2 C5V1

**Comment by hnyman** [comment]
compiling jool for ar71xx breaks also at buildbot:
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/jool/compile.txt

but compiles ok for e.g. x86_64 and arm_cortex-a15_neon-vfpv4

cc to @danrl and @jow-

**Comment by danrl** [comment]
I asked at the upstream mailing list for their point of view. I am not deep enough into the code to understand why it fails on MIPS and succeeds on X86. Will take some time.

**Comment by jow-** [comment]
Upstream likely needs a change like https://patchwork.kernel.org/patch/3233311/

**Comment by ydahhrk** [comment]
> Upstream likely needs a change like https://patchwork.kernel.org/patch/3233311/

Agree. It crashed very early, though. Did you try adding `#include net/ip6_checksum.h` to `Jool/mod/stateful/bib/db.c`, just to make sure it's all that's going to be needed?

**Comment by danrl** [comment]
I'll try that later today and let you know.

**Comment by danrl** [comment]
Patch to upstream is underway. Will bump package version once it is accepted or otherwise fixed in upstream. Thanks for the reports!
