### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by pengyou123** [openwrt/packages#3660]
mkyaffs2image.c:470:6: error: environment variable SOURCE_DATE_EPOCH must expand to a non-negative integer less than or equal to 253402300799

**Comment by hnyman** [comment]
Likely related to the main buildroot, not to any package here.

Discussion on the same problem and some proposals for getting past this problem can be found in https://forum.lede-project.org/t/lede-compile-fail-mkyaffs-problem/203/1
