### ISSUE TITLE
netatalk backport for 14.07 packages

### ISSUE THREAD

**Issue by ffainelli** [openwrt/packages#367]
Hello,

netatalk is a pretty useful package for MacOSX users using their OpenWrt device as a TimeCapsule or for AFP file sharing, it would be nice for them not to have to use an updated packages branch, and get the netatalk package in the 14.07 repository/feed.

I think this might be a little late for rebuilding packages, but if it is not, and/or we have to update ones for security reasons (e.g: bash) it would be nice to have that one too.

Thanks!

**Comment by Neustradamus** [comment]
@ffainelli: For the history:

Netatalk 3.1.7 (not merged):
- https://github.com/openwrt/packages/pull/1550

Netatalk 3.1.9:
- https://github.com/openwrt/packages/pull/3135

Netatalk 3.1.11:
- https://github.com/openwrt/packages/pull/4402

Netatalk 3.1.12:
- https://github.com/openwrt/packages/pull/7850

netatalk: drop package:
- https://github.com/openwrt/packages/pull/15873

Netatalk 3.1.13:
- https://github.com/openwrt/packages/pull/18687
- Backport: https://github.com/openwrt/packages/pull/18696

Netatalk 3.1.18 (not merged):
- https://github.com/openwrt/packages/pull/24206
- https://github.com/openwrt/packages/pull/24249

Netatalk 3.2.0:
- https://github.com/openwrt/packages/pull/24257

Netatalk 3.2.5:
- https://github.com/openwrt/packages/pull/24762

Netatalk 4.0.2 (not merged):
- https://github.com/openwrt/packages/pull/25195

Netatalk 4.0.4:
- Master: https://github.com/openwrt/packages/pull/25200 + https://github.com/openwrt/packages/pull/25251
- 24.10 backport: https://github.com/openwrt/packages/pull/25246 + https://github.com/openwrt/packages/pull/25260
