### ISSUE TITLE
bind: Set --enable-filter-aaaa to be on by default?

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/packages#3670]
Maintainer: **@nmeyerhans**

Description:

I use the bind package in Entware-ng, which uses OpenWRT packages as the upstream source. Would you be against having the `--enable-filter-aaaa` flag on by default? The reason I ask is because currently anyone wanting this functionality must compile from source with the option explicitly enabled. It would be nice if Entware and other sources built the package with it on by default.

https://github.com/Entware-ng/Entware-ng/issues/315

I thought it would be best to report upstream to see if this was possible/discuss.

To present a valid case for this functionality. I run a separate bind DNS server on my router on a non-standard port and pass specific domains to it to essentially force IPv4 One primary example is Netflix. I use an IPv6 tunnel and Netflix blocks most IPv6 tunnels as proxy servers and prevents streaming.

Having `AAAA` records removed from domains is the most elegant way to force IPv4, without having to null-route or do other dirty hacks, that's essentially against the whole point of having IPv6 deployed.

**Comment by jamesmacwhite** [comment]
@nmeyerhans Just wondering if you've managed to have a look at this at all?

**Comment by nmeyerhans** [comment]
Yeah, this is probably fine. I can't imagine that this will add significantly the the binary size, which would be my main concern. I haven't actually checked that, though...

**Comment by jamesmacwhite** [comment]
@nmeyerhans 

Thanks for your reply.

I don't believe it does, if there is an increase its only a few kilobytes. However if it would help, I can compile with the flag set against the latest version of bind and compare the ipk sizes for validation?

**Comment by nmeyerhans** [comment]
Don't bother; I've already done it. Looks like it adds all of 72 bytes to the armv7l `named` binary.

I'll merge the change shortly...

**Comment by nmeyerhans** [comment]
Pushed 909209e7531de2ea63f1f298adce985406d8ba08 to master.
