### ISSUE TITLE
bluez: missing dependencies libncursesw.so.5

### ISSUE THREAD

**Issue by lucize** [openwrt/packages#3682]
ncurses was updated to v6

**Comment by hnyman** [comment]
> ncurses was updated to v6

That is in LEDE. Likely fixed a few minutes ago by https://git.lede-project.org/?p=source.git;a=commitdiff;h=e5e98d58f794506b0193eea9dbcdd1ca08b7b873 that should trigger a rebuild of the packages depending on ncurses (like bluez).

As far as I see, bluez Makefile has no hardcoded dependency on a specific ncurses version, so rebuilding it completely (after a make clean) should solve the issue.
