### ISSUE TITLE
canutils Build Fail

### ISSUE THREAD

**Issue by riodda** [openwrt/packages#3695]
-------------------------------

Maintainer: @yegorich (find it by checking history of the package Makefile)
Environment: (x86_64, APU2, LEDE )

Description:

Despite haveing selected canutils canutils subpacakges fail to compile due to failed depedencies
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-log-conversion:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-log-conversion.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-canbusload:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-canbusload.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-can-calc-bit-timing:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-can-calc-bit-timing.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-candump:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-candump.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-cangen:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-cangen.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-cangw:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-cangw.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-canplayer:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-canplayer.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-cansniffer:
 * 	canutils * 
 * opkg_install_cmd: Cannot install package canutils-cansniffer.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for canutils-cansend:
 * 	canutils * 
```
.config extract

CONFIG_PACKAGE_canutils=y
CONFIG_PACKAGE_canutils-can-calc-bit-timing=y
CONFIG_PACKAGE_canutils-canbusload=y
CONFIG_PACKAGE_canutils-candump=y
CONFIG_PACKAGE_canutils-cangen=y
CONFIG_PACKAGE_canutils-cangw=y
CONFIG_PACKAGE_canutils-canplayer=y
CONFIG_PACKAGE_canutils-cansend=y
CONFIG_PACKAGE_canutils-cansniffer=y
CONFIG_PACKAGE_canutils-log-conversion=y

**Comment by riodda** [comment]
Commenting the dependecies in the Makefile the errors are gone but the build lacks several of the canutils execs such as slcand slcan_attach

**Comment by yegorich** [comment]
@riodda have you already looked at the patch?

**Comment by riodda** [comment]
Nope, i will
