### ISSUE TITLE
<openvpn-mbedtls> error building with latest trunk

### ISSUE THREAD

**Issue by finasfinas** [openwrt/packages#3708]
OpenWrt-libtool: link: mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -mdspr2 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2:openvpn-2.4_rc2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z -Wl,now -Wl,-z -Wl,relro -ffunction-sections -fdata-sections -std=c99 -znow -zrelro -Wl,--gc-sections -o openvpn argv.o base64.o buffer.o clinat.o comp.o compstub.o comp-lz4.o crypto.o crypto_openssl.o crypto_mbedtls.o dhcp.o error.o event.o fdmisc.o forward.o fragment.o gremlin.o helper.o httpdigest.o lladdr.o init.o interval.o list.o lzo.o manage.o mbuf.o misc.o platform.o console.o console_builtin.o console_systemd.o mroute.o mss.o mstats.o mtcp.o mtu.o mudp.o multi.o ntlm.o occ.o pkcs11.o pkcs11_openssl.o pkcs11_mbedtls.o openvpn.o options.o otime.o packet_id.o perf.o pf.o ping.o plugin.o pool.o proto.o proxy.o ps.o push.o reliable.o route.o schedule.o session_id.o shaper.o sig.o socket.o socks.o ssl.o ssl_openssl.o ssl_mbedtls.o ssl_verify.o ssl_verify_openssl.o ssl_verify_mbedtls.o status.o tls_crypt.o tun.o win32.o cryptoapi.o  -L/home/finas/lede.C5/staging_dir/target-mips_24kc_musl-1.1.15/usr/lib -L/home/finas/lede.C5/staging_dir/target-mips_24kc_musl-1.1.15/lib -L/home/finas/lede.C5/staging_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.15/usr/lib -L/home/finas/lede.C5/staging_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.15/lib ../../src/compat/.libs/libcompat.a -lresolv -llzo2 -lmbedtls -lmbedx509 -lmbedcrypto
/home/finas/lede.C5/staging_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.15/lib/gcc/mips-openwrt-linux-musl/6.3.0/../../../../mips-openwrt-linux-musl/bin/ld: copy reloc against protected `__stack_chk_guard' is dangerous
ssl_mbedtls.o: In function `tls_ctx_use_external_private_key':
ssl_mbedtls.c:(.text.tls_ctx_use_external_private_key+0x66): undefined reference to `mbedtls_pk_setup_rsa_alt'
collect2: error: ld returned 1 exit status
Makefile:575: recipe for target 'openvpn' failed
make[7]: *** [openvpn] Error 1
make[7]: Leaving directory '/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2/src/openvpn'
Makefile:421: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory '/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2/src'
Makefile:606: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2'
Makefile:494: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2'
Makefile:125: recipe for target '/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2/.built' failed
make[3]: *** [/home/finas/lede.C5/build_dir/target-mips_24kc_musl-1.1.15/openvpn-mbedtls/openvpn-2.4_rc2/.built] Error 2
make[3]: Leaving directory '/home/finas/lede.C5/package/network/services/openvpn'
package/Makefile:133: recipe for target 'package/network/services/openvpn/compile' failed
make[2]: *** [package/network/services/openvpn/compile] Error 2
make[2]: Leaving directory '/home/finas/lede.C5'
package/Makefile:129: recipe for target '/home/finas/lede.C5/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/finas/lede.C5/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/finas/lede.C5'
/home/finas/lede.C5/include/toplevel.mk:197: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by nbd168** [comment]
Fixed in latest LEDE master
