### ISSUE TITLE
Apache: do not list modules

### ISSUE THREAD

**Issue by crisc82** [openwrt/packages#3720]
I installed Apache and configured after reading this https://wiki.openwrt.org/doc/howto/http.apache
Is running fine.

httpd -M or apachectl -M in the shell should list installed modules. All i get is "Syntax OK"

The response should be something like this:
Loaded Modules:
core_module (static)
mpm_prefork_module (static)
http_module (static)
so_module (static)
auth_basic_module (shared)
cgi_module (shared)
version_module (shared)
wsgi_module (shared)
Syntax OK

http://www.shellhacks.com/en/List-Loaded-Enabled-Apache-Modules

**Comment by eliz82** [comment]
Maintainer: Thomas Heil <heil@terminal-consulting.de>
https://github.com/openwrt/packages/tree/master/net/apache
