### ISSUE TITLE
missing perl GD.pm

### ISSUE THREAD

**Issue by qbox4u** [openwrt/packages#3721]
The install of perl is an piece of cake, but GD is missing
https://github.com/Entware-ng/Entware-ng/issues/490

http://search.cpan.org/~lds/GD-2.56/lib/GD.pm

The old ipkg was
The Graphical module
[~] # ipkg install perl-gd

whenever you have time for this ^_^

**Comment by hnyman** [comment]
Sounds like a feature request. I find no trace of perl-gd in the Openwrt package repo.

If you want perl-gd, please create the package creating the support and assume maintainership for it.
