### ISSUE TITLE
Transmission needs mbed TLS-support

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#3731]
@obsy 
As mbed TLS 1.3 (PolarSSL) is EOL support for mbed TLS 2.X would be desirable. Upstream have support in tree however there's no release as of yet. Do we want to add patches or (preferably?) use a git clone for now and just spoof the reported version to the released one?

To clarify, LEDE is getting release soonish and I'd like to see a working package with mbed TLS 2.x support before that happens.

**Comment by obsy** [comment]
IMO now we should use current git version

**Comment by diizzyy** [comment]
Do you want me to have a look at it or can you handle it?

**Comment by obsy** [comment]
I will be able to take care of it next weekend. So if you want and have time..

**Comment by diizzyy** [comment]
Sounds great, thanks!

**Comment by diizzyy** [comment]
@obsy Any progress?

**Comment by obsy** [comment]
Wating for RC4, see https://github.com/lede-project/source/pull/657
Without this transmission with mbedtls simply does not compile.

**Comment by nbd168** [comment]
RC4 is now enabled in LEDE master.

**Comment by obsy** [comment]
https://github.com/openwrt/packages/pull/3795
