### ISSUE TITLE
Removing Speex codec from tree/repo

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#3747]
@thess @psycho-nico @tripolar 
It's 2017 and Speex is being deprecated by Xiph.
Does anyone have opinions about removing it the repo?

**Comment by diizzyy** [comment]
There are very few packages that uses it and I doubt it's actually used at all.
https://github.com/openwrt/packages/search?l=Makefile&q=speex&utf8=%E2%9C%93

**Comment by thess** [comment]
Fair enough - however, you should look in the **telephony** repo too.

**Comment by diizzyy** [comment]
https://github.com/openwrt/telephony/pull/130
https://github.com/openwrt/telephony/pull/131

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/3763

**Comment by tripolar** [comment]
pulseaudio also depends on libspeexdsp

**Comment by diizzyy** [comment]
@tripolar 
Good catch, not sure why both soxr and libspeexdsp are needed. Documentation is well.. incomplete ;-)

**Comment by thess** [comment]
I am not convinced we need to remove the speex codec entirely from our repo. I do think we should encourage package maintainers to phase it out if possible. I do see value in having it (speex) plus packages which use it retained in the repository as long as they build and are useful to users and developers.
