### ISSUE TITLE
keepalived: default to /etc/keepalived/keepalived.conf

### ISSUE THREAD

**Issue by stintel** [openwrt/packages#3756]
Maintainer: @commodo 
Environment: LEDE r2762-ed69e93 @ Octeon (Ubiquiti ERL)

Description:
Commit a883235e138bf06b508e3e3cdf03bddc7eeec361 breaks all existing keepalived setups. Please uncomment this in the config:
```
config global_defs
        option alt_config_file          "/etc/keepalived/keepalived.conf"
```
This way, existing setups should keep working, and the user can decide to migrate to UCI at a convenient time.

**Comment by commodo** [comment]
sure ; will push PR
