### ISSUE TITLE
isc-dhcp-relay-ipv4 and isc-dhcp-relay-ipv6 do not exist anymore for architecture arm_cortex-a9_vfpv3

### ISSUE THREAD

**Issue by Plopli** [openwrt/packages#3782]
Maintainer: @antonyantony 
Environment: Linksys WRT1900ACS - arm_cortex-a9_vfpv3

Description:
These packages are not present in the repository anymore but I'm sure they were there before.
I've no idea on how the build system decide to build or not for an architecture so I cannot debug further.

**Comment by hnyman** [comment]
Likely just a temporary buildbot problem. 

Packages are there again:

http://downloads.lede-project.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/
isc-dhcp-relay-ipv4_4.3.3-1_arm_cortex-a9_vfpv3..> 07-Jan-2017 16:40              482853
isc-dhcp-relay-ipv6_4.3.3-1_arm_cortex-a9_vfpv3..> 07-Jan-2017 16:42              564640
