### ISSUE TITLE
bcp38: implement ipv6 BCP38

### ISSUE THREAD

**Issue by bastien-roucaries** [openwrt/packages#3793]
Hi,

Could you implement BCP38 for ipv6 please ?

An example of implementation is here:
https://github.com/zec/bcp38v6

Thank you

**Comment by tohojo** [comment]
Why? Ipv6 prefixes are assigned with source specific routes, so bcp38 firewall rules are redundant for ipv6...

**Comment by bastien-roucaries** [comment]
according ro rfc6204 BCP38 should be implemented what why I asked.

Moreover I do not control myprovider router

Bastien

**Comment by bastien-roucaries** [comment]
I means martian coming from wan will be rejected instead of dropped => saturating my ADSL line => DOS

**Comment by tohojo** [comment]
Yes, but openwrt already does this because it only installs source specific default routes. So any packet with a source outside your assigned prefix will be dropped because there is no route for it. This makes the bcp38 firewall rules implemented in this package redundant for ipv6...

**Comment by bastien-roucaries** [comment]
Even for multicast ?

**Comment by bastien-roucaries** [comment]
At least if not needed could be documented in package description ?

**Comment by tohojo** [comment]
Sure, can add a note somewhere. Should work for multicast as well :)
