### ISSUE TITLE
ffmpeg: configure error in 3.2.2 update

### ISSUE THREAD

**Issue by thess** [openwrt/packages#3836]
Reported by @artynet

```
getting configure error for libmp3lame

ERROR: libmp3lame >= 3.98.3 not found

please fix this...
```

**Comment by thess** [comment]
Curious we have 3.99.5 in the repo. Configure must be finding local copy?
Will check into it today

**Comment by thess** [comment]
@artynet - need more information to track this down. I cannot see how this can happen with an up-to-date build environment. Make sure lame-lib is correctly built / installed in your setup. Some hint about the problem may be found in `build_dir/target-.../ffmpeg-3.2.2/config.log`.

Supply the following if possible:
 - Target system for which you are building
 - Software versions of LEDE/OpenWrt release, packages, etc.
 - Steps to reproduce

**Comment by diizzyy** [comment]
Not really sure how it's supposed to work in the first please because even if I select ffmpeg-full LAME doesn't get pulled/selected.

**Comment by thess** [comment]
The extra "non-free" codecs must be explicitly selected to be included. If selected, ffmpeg will get built with them. BUILD_PATENTED must also be selected.

**Comment by diizzyy** [comment]
Ahh, that's good to know. We can't do the same for fdk-aac?

**Comment by thess** [comment]
Yes, that was what I am planning - got some other stuff to finish up first.

**Comment by thess** [comment]
@artynet - Going once, twice ... ?

**Comment by thess** [comment]
Closed - no response on issue and cannot reproduce.
