### ISSUE TITLE
git-http: missing dep to ca-bundle, causing fails

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/packages#3840]
Maintainer: @tripolar 
Environment: LEDE reboot (snapshot 14.jan. 2017)

Description:
after installing git-http and using ```git fetch``` I saw the following error
> fatal: unable to access 'https://github.com/somerepo/openwrt-routing.git/': Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed

This is caused by missing /etc/ssl/certs/ca-certificates.crt. Manually installing ```ca-bundle``` fixed this, so the dependency seems wrong.

No idea what's the situation for OpenWrt.

**Comment by D-Albers** [comment]
I would say, that the package is missing at the mbedtls package and not at the git-fetch package. The mbedtls package seems not to work as expected without the ca-bundle.

**Comment by tripolar** [comment]
i think so too. creating a dep on `ca-bundle` in git-http is unclean
