### ISSUE TITLE
net/ntpclient: Retire?

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#3852]
@thess 
Is this something we still need in the repo? busybox covers this usage afaik?

**Comment by build000** [comment]
Eg. I do use it, so it is needed. ;)

**Comment by diizzyy** [comment]
What's wrong with the busybox version?

**Comment by diizzyy** [comment]
@hnyman

**Comment by diizzyy** [comment]
Any opinions, having redundant packages seems a bit wasteful and upstream seems dead?

**Comment by thess** [comment]
According to @build000 - it is still used. If so, keep it.

**Comment by diizzyy** [comment]
Ok
