### ISSUE TITLE
mail/nail: Doesn't compile, defunct upstream

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#3865]
@pfzim 
Hi, the current version in the OpenWRT package repo doesn't compile (SSLv3 support removed in OpenSSL) and is deprecated. Would you be interested in upgrading this to S-nail (https://www.sdaoden.eu/code.html) or if you aren't interesting in maintaining this package any longer please tell so we can remove it.

Thanks in advance!
Daniel

**Comment by thess** [comment]
I'd rather not sweep out packages for lack of an update - easier to fix them and move on.

**Comment by diizzyy** [comment]
I don't see how it would benefit anyone applying band-aid on abdonned software (upstream).
