### ISSUE TITLE
Problem Adblock

### ISSUE THREAD

**Issue by Ansuel** [openwrt/packages#3904]
@dibdot I have installed aria2c in my router but adblock doesn't recognize it. And i think we can't install the full wget package cause the ddns package goes in error.

**Comment by dibdot** [comment]
Did you read the online documentation? Please set 'adb_fetch' & 'adb_fetchparm' accordingly ...

**Comment by Ansuel** [comment]
Why don't include in the script something to autodetect the available downloader utility?

**Comment by dibdot** [comment]
Too complex & error prone ... uclient-fetch plus wget will probably cover > 95 % of all user requirements. Please close this ticket.
