### ISSUE TITLE
Ruby 2.4

### ISSUE THREAD

**Issue by joker5bb** [openwrt/packages#3912]
After Ruby 2.4 is built there is no ipk file in /bin/ar71xx/packages/packages/

*** Following extensions failed to configure:
../.././ext/readline/extconf.rb:0: Failed to configure readline. It will not be installed.
*** Fix the problems, then remove these directories and try again if you want.
make[5]: Entering directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
make[5]: 'ruby' is up to date.
make[5]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
make[4]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
making enc
make[4]: Entering directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
make[4]: Nothing to be done for 'enc'.
make[4]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
making trans
make[4]: Entering directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
make[4]: Nothing to be done for './enc/trans'.
make[4]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
making encs
make[4]: Entering directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
make[4]: Nothing to be done for 'encs'.
make[4]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
/home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/host/bin/ruby --disable=gems -I/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0 -rmips-linux-gnu-fake  -I`cd ./lib; pwd` --disable-gems -r./mips-linux-gnu-fake ./tool/rbinstall.rb --make="make" --dest-dir="/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0/ipkg-install" --extout=".ext" --mflags="-w" --make-flags="w" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
installing binary commands:   /usr/bin
installing base libraries:    /usr/lib
installing arch files:        /usr/lib/ruby/2.4/mips-linux-gnu
installing pkgconfig data:    /usr/lib/pkgconfig
installing command scripts:   /usr/bin
installing library scripts:   /usr/lib/ruby/2.4
installing common headers:    /usr/include/ruby-2.4
installing manpages:          /usr/man/man1
installing extension objects: /usr/lib/ruby/2.4/mips-linux-gnu
installing extension objects: /usr/lib/ruby/site_ruby/2.4/mips-linux-gnu
installing extension objects: /usr/lib/ruby/vendor_ruby/2.4/mips-linux-gnu
installing extension headers: /usr/include/ruby-2.4/mips-linux-gnu
installing extension scripts: /usr/lib/ruby/2.4
installing extension scripts: /usr/lib/ruby/site_ruby/2.4
installing extension scripts: /usr/lib/ruby/vendor_ruby/2.4
installing extension headers: /usr/include/ruby-2.4/ruby
installing default gems:      /usr/lib/ruby/gems/2.4 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.3.0
                              io-console 0.4.6
                              json 2.0.2
                              openssl 2.0.2
                              psych 2.2.2
                              rdoc 5.0.0
installing bundle gems:       /usr/lib/ruby/gems/2.4 (build_info, cache, doc, extensions, gems, specifications)
                              minitest 5.10.1
                              did_you_mean 1.1.0
                              net-telnet 0.1.1
                              power_assert 0.4.1
                              xmlrpc 0.2.1
                              rake 12.0.0
                              test-unit 3.2.3
make[3]: Leaving directory '/home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0'
touch /home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0/.built
rm -rf /home/user/openwrt/tmp/stage-ruby
mkdir -p /home/user/openwrt/tmp/stage-ruby/host /home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/packages /home/user/openwrt/staging_dir/host/packages
( cd /home/user/openwrt/build_dir/target-mips_34kc_musl-1.1.16/ruby-2.4.0/ipkg-install; tar -cf - . ) | ( cd /home/user/openwrt/tmp/stage-ruby; tar -xf - )
find /home/user/openwrt/tmp/stage-ruby -name '*.la' | xargs -r rm -f;   	find /home/user/openwrt/tmp/stage-ruby -name '*.la' | xargs -r rm -f; 
if [ -f /home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/packages/ruby.list ]; then /home/user/openwrt/scripts/clean-package.sh "/home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/packages/ruby.list" "/home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16"; fi
if [ -d /home/user/openwrt/tmp/stage-ruby ]; then (cd /home/user/openwrt/tmp/stage-ruby; find ./ > /home/user/openwrt/tmp/stage-ruby.files); 	SHELL= flock /home/user/openwrt/tmp/.staging-dir.flock -c ' mv /home/user/openwrt/tmp/stage-ruby.files /home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/packages/ruby.list && cp -fpR /home/user/openwrt/tmp/stage-ruby/* /home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/; '; fi
rm -rf /home/user/openwrt/tmp/stage-ruby
touch /home/user/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/stamp/.ruby_installed
make[2]: Leaving directory '/home/user/openwrt/feeds/packages/lang/ruby'
make[1]: Leaving directory '/home/user/openwrt'

**Comment by joker5bb** [comment]
have to close this, ruby packages were not selected in menuconfig

**Comment by luizluca** [comment]
It happens ;-)
