### ISSUE TITLE
GNU Midnight Commander 4.8.18

### ISSUE THREAD

**Issue by yabba235** [openwrt/packages#3976]
My system WNDR3700v2, 17.01-SNAPSHOT, r3106-c53bb97

In bash history after mc use i got many console output, like:
precmd() { if [ ! "${PWD##$HOME}" ]; then MC_PWD="~"; else [ "${PWD
##$HOME/}" = "$PWD" ] && MC_PWD="$PWD" || MC_PWD="~/${PWD##$HOME/}"; fi; echo "$
USER@$HOSTNAME:$MC_PWD"; pwd>&6; kill -STOP $$; }; PRECMD=precmd; PS1='$($PRECMD
)$ '
This filling bash history unnecessary and less available space on file system.

**Comment by hnyman** [comment]
cc to maintainer @dibdot

**Comment by dibdot** [comment]
@yabba235 That's a known (minor) issue with limited busybox shell & mc subshell handling. I'll try to provide a fix with the next forthcoming mc release (4.8.19).

**Comment by yabba235** [comment]
OK, thank&#39;s for fast answer :) !  
                
              
               
                 
                  Dnia 10 lutego 2017 12:17 dibdot &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   github.com @yabba235  That&#39;s a known (minor) issue with limited busybox shell &amp; mc subshell handling. I&#39;ll try to provide a fix with the next forthcoming mc release (4.8.19).

**Comment by dibdot** [comment]
@yabba235 Sorry, I didn't find an easy way to suppress these escaped characters in the subshell (this code is really hackish). If this cosmetic thing is really an issue for you, please feel free to provide a better patch ... ;-))

Thanks!

**Comment by dibdot** [comment]
#4115

**Comment by diizzyy** [comment]
@hnyman 
Can you close this?
