### ISSUE TITLE
net-snmp - perl agent extending support

### ISSUE THREAD

**Issue by blade3609** [openwrt/packages#3991]
Maintainer: @stintel 
Environment: (OpenWRT armv7)

Description:
"Perl do" commands don't work in snmpd.
Could this be implemented so that "perl do" commands work ?

**Comment by stintel** [comment]
I'm not going to add perl as a hard dependency. I am willing to accept a PR if it possible to add it as a separate packages, e.g. snmpd-perl or libnetsnmp-perl.
