### ISSUE TITLE
nginx with gzip_static module

### ISSUE THREAD

**Issue by ghost** [openwrt/packages#4018]
Maintainer: @heil 
Environment: -

Description:
Could you compile nginx with the --with-http_gzip_static_module option? This would allow to serve gzip pre-compressed assets. Note - in this case nginx does not compress anything (therefore there's no CPU overhead issue), it just checks if a file has a .gz'ipped version and serves this one instead. IMHO it's a great feature when it comes to serving webpages from home routers, where the outgoing bandwidth is usually very limited.

**Comment by linsong** [comment]
+1

**Comment by RogueScholar** [comment]
I would find this useful as well.

**Comment by dibdot** [comment]
Feel free to open a PR.
