### ISSUE TITLE
Load balancing port online is slow

### ISSUE THREAD

**Issue by kevinhya** [openwrt/packages#4041]
Description:
WHen using load balancing, each port already had public ip, but in "MWAN Interface Live Status", it may take 20 seconds to get each port online(i.e became green)... is there any way to speed up this process

**Comment by feckert** [comment]
@kevinhya sorry for the late replay i have not seen in the head that this issue is related to mwan3.
What version off mwan3 do you use?

**Comment by dibdot** [comment]
no feedback - close this by now.
