### ISSUE TITLE
mwan3 is ignoring l2tp interface

### ISSUE THREAD

**Issue by franke2** [openwrt/packages#4062]
Maintainer: @Adze1502
Environment: D-Link DIR-860L B1 LEDE Reboot 17.01.0 r3205-59508e3 / LuCI lede-17.01 branch (git-17.051.53299-a100738)

Description:

mwan3 is not working with l2tp interface. 
using the diagnostic tools i noticed that wan4 (my l2tp interface) is not able to ping.

my l2tp interface configuration is:

config interface 'wan4'
	option proto 'l2tp'
	option ifname 'eth0'
	option delegate '0'
	option server 'SERVER'
	option username 'USER'
	option password 'PASSWORD'
	option metric '40'
	option peerdns '0'
	option dns '8.8.8.8 8.8.4.4'
	option ipv6 '0'

**Comment by feckert** [comment]
@franke2 could you please send the mwan3 config as well?

**Comment by feckert** [comment]
@hnyman I think we could close this as well?
