### ISSUE TITLE
Override mac address doesn't work on wan lede-17.01.0-r3205

### ISSUE THREAD

**Issue by heiybb** [openwrt/packages#4076]
Router:WNDR4300 v1
LEDE Version:lede-17.01.0-r3205-59508e3

As what the title describes, and there is nothing wrong in the config file.

**Comment by sholwe** [comment]
Confirmed.

Just did a clean sysupgrade install from factory, and when I initially set the MAC override, it displayed it.  It continues to show in LuCI after a reboot, but does not actually reflect it anywhere.

**Comment by fehead** [comment]
Same probleam is happend.

root@LEDE:/etc/config# cat /etc/openwrt_release 
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='17.01.1'
DISTRIB_REVISION='r3316-7eb58cf109'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='LEDE Reboot 17.01.1 r3316-7eb58cf109'
DISTRIB_TAINTS='no-all'

So I edit /etc/config/network file.

config device 'wan_dev'
        option name 'eth0.2'
        option macaddr 'XX:XX:XX:XX:XX:XX'   # <-- Add 

and reboot. and It works well.
