### ISSUE TITLE
net/ ntpd: ntpd.hotplug script makes disabling service impossible [CC]

### ISSUE THREAD

**Issue by the-real-tokai** [openwrt/packages#4087]
Maintainer: Peter Wagner @tripolar
Environment: CC

Description: The provided `ntpd.hotplug` script (that is installed to `/etc/hotplug.d/iface/20-ntpd`) makes disabling the service impossible.

Basically what happens is that when the `ntpd` service gets disabled —and should stay disabled— at some point (e.g. during reboot or a reconnect) the hotplug script gets launched and fires `ntpd` up again. Not what we want in this case. 😏

Solution: Probably an extra check in the hotplug script for the respective ntpd file in `/etc/rc.d` could help?

**Comment by EricLuehrsen** [comment]
Both dnsmasq and Unbound UCI check their respective enabled status. They use NTP hotplug to know when full DNSSEC is possible (requires global time). The following is just a simplified example.
```
if [ -x /etc/init.d/[app] ] ; then
  /etc/init.d/[app] enabled && /etc/init.d/[app] restart
fi
```

**Comment by tripolar** [comment]
fixed in https://github.com/openwrt/packages/commit/228764bfe8b439e6abbd54eec3026a038e3c7a9c
