### ISSUE TITLE
motion: update package

### ISSUE THREAD

**Issue by harley4ik** [openwrt/packages#4092]
update to release version [4.0.1](https://github.com/Motion-Project/motion/releases)
Last update  in repo was at 20141018

**Comment by joelpdb** [comment]
Please do so. Hopefully it will include a fix for the issue cause the error "FFmpeg/Libav not found on computer. No RTSP support"

**Comment by diizzyy** [comment]
@harley4ik @joelpdb 
Update notifications are being sent via uscan runs by @sdwalker, no need to create issues for update requests. You are free to help by submitting a pull request of course. Please close this. :-)

**Comment by diizzyy** [comment]
@hnyman @thess 
Please close
