### ISSUE TITLE
Python 2: Samba 4.x compatibility

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#4114]
@commodo 
Hi, is it possible to add these fixes (last on the page) to the repo? It makes Samba 4.x (not in tree atm) compile without replacing the current version.
https://github.com/wongsyrone/packages-1/commits/master/lang/python?author=wongsyrone

**Comment by commodo** [comment]
@diizzyy 
short answer : yes
long answer, i'd have to walk through that patch

though, maybe it would be an idea, if you could provide me with a Samba Makefile, and I can validate the patches that I'll port ;
I'll give credit to @wongsyrone  for the patches/changes ; 
but it is a bit hard to walk through it, and harder to understand which one fixes the Samba build ;

**Comment by wongsyrone** [comment]
The most related patch is:

010-fix-python-config.patch
https://github.com/wongsyrone/packages-1/commit/60ca6f0f2b6712e023bc4af38f15a10d1aa78154

**Comment by commodo** [comment]
yeah, but that's still a pretty big patch ; 
it has whitespace in there

**Comment by commodo** [comment]
i mean, i can just take in the parts that are not whitespace, but I'd like to see for myself that it fixes Samba

**Comment by wongsyrone** [comment]
You can take https://raw.githubusercontent.com/wongsyrone/packages-1/master/lang/python/patches/010-fix-python-config.patch if you like.

For long story, you can check https://github.com/wongsyrone/openwrt-1/issues/73

**Comment by wongsyrone** [comment]
The main point of this change is to ship a modified cross-compiling-friendly python2-config, and make use of that file to satisfy samba's waf, which is only compatible with python2.

https://github.com/wongsyrone/openwrt-1/blob/master/package/external/samba44related/samba44/Makefile#L69

**Comment by commodo** [comment]
whoa, now i have my work cut out for myself 
will look into it

**Comment by diizzyy** [comment]
Samba and Heimdal can be found here:
https://github.com/wongsyrone/openwrt-1/tree/master/package/external/samba44related/samba44
You need to add the following patches to Heimdal otherwise it'll fail since EGD isn't in OpenSSL.
https://github.com/wongsyrone/lede-1/issues/32#issuecomment-280840240

**Comment by commodo** [comment]
@wongsyrone 
if you change
```
PYTHON_CONFIG="$(STAGING_DIR)/usr/bin/python2-config" \
```
to 
```
PYTHON_CONFIG="$(STAGING_DIR_HOSTPKG)/bin/python2-config" \
```

It builds on my machine.
Did you try it ?

I am not sure if it works though.
I tested on a x86_64 VM and Samba did not start; it said "Samba4 is disabled" ; maybe I need a configuration ?

Can you test ?
The only change I had to do to the Samba4 & Heimdal packages was that line.
Everything else is from here:
https://github.com/wongsyrone/openwrt-1/tree/master/package/external/samba44related/samba44

**Comment by commodo** [comment]
@diizzyy maybe you could also try real quick :) ?

**Comment by wongsyrone** [comment]
As long as I know, STAGING_DIR_HOSTPKG doesn't exist when I was testing samba4.

https://github.com/wongsyrone/openwrt-1/blob/master/package/external/samba44related/samba44/files/samba44.config#L2

You may change 'enabled' to 1 and try again. I add it to bypass autostart. https://github.com/wongsyrone/openwrt-1/blob/master/package/external/samba44related/samba44/files/samba44.init#L140

**Comment by wongsyrone** [comment]
BTW, if you leave renice disabled in busybox configs, please remove all renice calls in the init script.

**Comment by diizzyy** [comment]
@commodo 
Hmm... Samba isn't happy on ARM (Marvell)
```
Checking for program python2.7-config                                             : /home/diizzy/marvell-take2/source/staging_dir/hostpkg/bin/python2-config
Checking for custom code                                                          : Could not find the python development headers
```

**Comment by commodo** [comment]
hello again
sorry for the delays ; 
seems stuff was pouring on all sides for me

i neglected to say earlier that I did reproduce the issue

please try this patch:
https://github.com/commodo/packages/commit/0bb78f682519efafeb69cae251bf1d158effbd51

i've managed to build on ARM ; i did not run it ;
can you try the patch on your setups ? 

thanks
Alex

**Comment by diizzyy** [comment]
@commodo 
**Awesome work!** Many thanks! 👍 

![samba44-mvebu](https://cloud.githubusercontent.com/assets/11659781/24220603/25f852f6-0f4b-11e7-82ba-f033fd2cd04a.png)

**Comment by commodo** [comment]
Cool :)
Glad it worked.

I'm also happy it worked with minimal changes.

On Wed, 22 Mar 2017 at 23:02, Daniel Engberg <notifications@github.com>
wrote:

@commodo <https://github.com/commodo>
*Awesome work!* Many thanks! 👍

[image: samba44-mvebu]
<https://cloud.githubusercontent.com/assets/11659781/24220603/25f852f6-0f4b-11e7-82ba-f033fd2cd04a.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/packages/issues/4114#issuecomment-288538692>,
or mute the thread

**Comment by commodo** [comment]
@diizzyy 
can we close this issue ?
or is there anything else ?

**Comment by diizzyy** [comment]
We can close this, thanks!
