### ISSUE TITLE
luci-app-mwan3: bad formatting of troubleshooting page

### ISSUE THREAD

**Issue by psyborg55** [openwrt/packages#4131]
Maintainer: @arfett 

Description:

when there is more troubleshooting data output in one line than fits into screen the page will look strange

![screenshot](https://cloud.githubusercontent.com/assets/15853469/23778070/a13373a0-0538-11e7-8024-079958987f2e.png)

i think it needs reformatting in syslog/kernel log page style

**Comment by feckert** [comment]
That has to-do with the long output of `iptables`. The other views are effect as well if the screen is small enough
I am not sure how to fix this.
It is `css` magic.
I am not a `css` guru.
If you have a solution then go for it.

**Comment by arfett** [comment]
I spent a chunk of time trying to fix that once. As you can see I was unable to. Maybe a css wizard can be found to work it out.

**Comment by psyborg55** [comment]
not fixed with https://github.com/openwrt/luci/pull/1178/commits/e61f40ead8072fade1e2b0d24bf1ab8a195a22c6

it also happens on Configuration -> Interfaces, Rules tabs

**Comment by feckert** [comment]
@psyborg55 i could nor reproduce your issue?
Could you send me a picture who does it looks?

**Comment by feckert** [comment]
@psyborg55 have you tested the new luci master i have done some additional changes. 
If every thing is fine could you please close this issue?

**Comment by feckert** [comment]
@hnyman i think we could close this issue there was a lot work done in the luci-app-mwan3 and the reported did not react on my ping
