### ISSUE TITLE
transmissiondcfp: package (NEW)

### ISSUE THREAD

**Issue by jf-stretch** [openwrt/packages#4149]
please consideration _transmissiondcfp_
it's good stable
Optware-ng is not to sustain https://github.com/Optware/Optware-ng/issues/186
but now also not of  maintain _transmissiondcfp_   began stopped merge https://github.com/Optware/Optware-ng/pull/187/commits/d34985dfe21b45c6a33eac5d4ca00cb069e228e0

**Comment by diizzyy** [comment]
If you need it please maintain your own package. Upstream works fine.

**Comment by jf-stretch** [comment]
Ok, I not the ability of sustain maintain, but entware-ng for me the mutate. Original transmission daemon stalled at source one year insignificantly unchanged. transmissiondcfp remains stable. Thank you.

**Comment by diizzyy** [comment]
No, it did not.
https://github.com/transmission/transmission/commits/master

**Comment by jf-stretch** [comment]
> No, it did not.
> https://github.com/transmission/transmission/commits/master

Daemon of it withholds lacking enhancement features, that said remains stalled. Transmissiondcfp many of enhancement features new on daemon. It's good, each for his own.

**Comment by diizzyy** [comment]
@jf-stretch 
Please close this request, if you want a new port this isn't the right forum.
