### ISSUE TITLE
loudmouth: missing dependency for libidn

### ISSUE THREAD

**Issue by hnyman** [openwrt/packages#4187]
Maintainer: @MikePetullo 

Both LEDE and Openwrt buildbots complain that loudmouth is missing dependency for libidn. That might be just due to an eager configure script.

http://buildbot.openwrt.org:8010/broken_packages/ar71xx/loudmouth/compile.txt
http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/loudmouth/compile.txt
```
Package loudmouth is missing dependencies for the following libraries:
libidn.so.11
```

Please check if libidn is really needed for anything, and 
* if yes, please add the dependency,
* if no, please disable the check for that libidn presence in configure script/options

**Comment by MikePetullo** [comment]
Please see https://github.com/openwrt/packages/pull/4194.
