### ISSUE TITLE
freeradius3-democerts: The Demo Certs Expired on 3/Apr

### ISSUE THREAD

**Issue by loyukfai** [openwrt/packages#4239]
Maintainer: @tohojo 
Environment: LEDE 17.01.0

Description:
```
Validity
    Not Before: Feb  2 14:24:56 2017 GMT
    Not After : Apr  3 14:24:56 2017 GMT
```
It’s probably due to the makefile defaults has stipulated a valid day of 60 days.

Meanwhile, there's another issue of freeradius3 as described here:
https://bugs.lede-project.org/index.php?do=details&task_id=678

Cheers.

Note: Originally reported at https://bugs.lede-project.org/index.php?do=details&task_id=679

**Comment by tohojo** [comment]
loyukfai <notifications@github.com> writes:

> Maintainer: @tohojo
> Environment: LEDE 17.01.0
>
> Description:
>
> Validity
>     Not Before: Feb  2 14:24:56 2017 GMT
>     Not After : Apr  3 14:24:56 2017 GMT
>
> It’s probably due to the makefile defaults has stipulated a valid day of 60 days.
>
> Meanwhile, there's another issue of freeradius3 as described here:
> https://bugs.lede-project.org/index.php?do=details&task_id=678

I'll look them both over when I get a chance. Thanks for reporting :)

-Toke

**Comment by loyukfai** [comment]
Welcome, and thanks for your follow-up in advance.

Cheers.
