### ISSUE TITLE
mwan3 -> on status luci page: => daemon.err uhttpd uci: Entry not found

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#4246]
on current TRUNK, there is something wrong with the MWAN status information, as it is spaming the logs with:
Mon Apr 10 14:12:58 2017 daemon.err uhttpd[2754]: uci: Entry not found

see also:
https://dev.openwrt.org/ticket/19419

**Comment by hnyman** [comment]
> on current TRUNK, there is something wrong with the MWAN

which exact trunk build?  Openwrt or LEDE and which git revision?

cc @feckert

**Comment by camelcamro** [comment]
Sorry, forgot to tell:  Current lede trunk version

**Comment by hnyman** [comment]
> Current lede trunk version

But which build of the LEDE trunk ???
And which mwan version in use? 
Mwan was updated just a few ago, so plase tell the exact version.
("opkg list-installed" or look at installed progs in LuCI)

That error "uci: Entry not found" has usually surfaced when there is an uninitialised or empty variable. Some config item has no default? and is missing from the config?

**Comment by camelcamro** [comment]
Lede and mwan3 Version fromm today's build.
But maybe it is because had old settings. I will try to resetup from scratch

**Comment by camelcamro** [comment]
ok, i was looking into ...
well, i have maybe a special case ...
as i have a WLAN - access point + client mode (hotspot to my handset android tethering AP).
THis is mostly disabled, as if not reachable, it would also bring down the AP mode of wireless lann.
so, this interface is most of time DOWN, and maybe this is the reason, that MWAN3 - is reporting that as empty config.
it is telling me:
WARNING: some interfaces are configured incorrectly or not at all in /etc/config/network!

this internface ("wwan") called in my case is in /etc/config/networks defined.
config interface 'wwan'
<------>option _orig_ifname 'wlan0'
<------>option _orig_bridge 'true'
<------>option proto 'dhcp'
<------>option delegate '0'
<------>option metric '40'
<------>option force_link '1'


whats wrong ?
why does MWAN3 not find it ?

but in my case, - if this interface is on - it would b valid, and it is then managed also correct.
so, that means, that this warning is not valid to report and spaming the logread. with: 

Mon Apr 10 19:56:17 2017 daemon.err uhttpd[2500]: uci: Entry not found

whats wrong ?

**Comment by feckert** [comment]
@camelcamro the `uhttpd[xxx] uci: Entry not found` error is generated in this line https://github.com/openwrt/luci/blob/master/applications/luci-app-mwan3/luasrc/controller/mwan3.lua#L67 . It is related to the luci-app-mwan3 packages in the luci feed. Maybe we have to check if the interface is present in the config before we read a config option.

**Comment by camelcamro** [comment]
sounds to be ... yes ...
but i have not that much insights about howto fix ..
if someone can try to fix it and build a package -> i can support you on testing

**Comment by feckert** [comment]
I think we could close this

**Comment by feckert** [comment]
@hnyman ping
