### ISSUE TITLE
ss-tunnel 2.6.1-1 program does not start

### ISSUE THREAD

**Issue by Tamila-2017** [openwrt/packages#4259]
**ss-tunnel** for LEDE does not start

Package: **Shadowsocks-libev 2.6.1-1 for LEDE** 

The ss-tunnel program does not start:

`ss-tunnel -s 99.99.99.99 -p 8388 -l 1080 -k passpass -m aes-256-cfb`

When the program starts, it shows its '**usage**' and goes to the command line.

The program also does not start with a configuration file:

```
ss-tunnel -c /etc/config/shadowsocks-libev 
2017-04-14 00:40:30 ERROR: 2:1: Unexpected c when seeking value
```

Environment:

**Model:			GL-MT300A
Firmware: Version	LEDE Reboot 17.01.0 r3205-59508e3 / LuCI lede-17.01 branch (git-17.051.53299-a100738) 
Kernel Version:		4.4.50
Config file:**

```
config shadowsocks-libev
        option server_port '8388'
        option local_port '1080'
        option timeout '60'
        option ignore_list '/dev/null'
        option udp_mode '0'
        option tunnel_port '5300'
        option tunnel_forward '8.8.4.4:53'
        option encrypt_method 'aes-256-cfb'
        list lan_ac_ip '192.168.8.148'
        option lan_ac_mode '0'
        option tunnel_enable '0'
        option enable '0'
        option server '99.99.99.99'
        option password 'passpass'
```

**Comment by yousong** [comment]
- ss-tunnel requires `-L` argument
 - ss-tunnel accepts only json format config file.  I guess you were feeding it with uci config file with `/etc/config/shadowsocks-libev` and that won't work.
