### ISSUE TITLE
feature request: "iotop" package

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#4288]
hello,
can anyone add iotop and to build a package for openwrt hardware architectures ?

**Comment by bmork** [comment]
I tried to create a package, but it needs a few kernel features which aren't normally enabled on OpenWrt.  See pull request #4363

**Comment by camelcamro** [comment]
cool :) great ->  so this is maybe also added to LEDE trunk version ? or only be added to openwrt trunk ?

**Comment by bmork** [comment]
Both.  This repo is shared by both.  But let's see what the OpenWrt developers say first.  The kernel requirments makes this package a bit special, so I'm not sure they will want it.

**Comment by cybmp3** [comment]
I Really need it.

**Comment by dibdot** [comment]
The PR regarding iotop was not accepted - close this as well.
