### ISSUE TITLE
swap-utils_2.29.2-1_mips_24kc.ipk install error on LEDE

### ISSUE THREAD

**Issue by V10lator** [openwrt/packages#4296]
`root@router:~# opkg install zram-swap openwrt
Installing zram-swap (1-2) to root...
Downloading http://downloads.lede-project.org/releases/17.01.1/packages/mips_24kc/base/zram-swap_1-2_all.ipk
Installing libblkid (2.29.2-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.1/packages/mips_24kc/base/libblkid_2.29.2-1_mips_24kc.ipk
Installing swap-utils (2.29.2-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.1/packages/mips_24kc/base/swap-utils_2.29.2-1_mips_24kc.ipk
Unknown package 'openwrt'.
Configuring libblkid.
Configuring swap-utils.
Configuring zram-swap.
zram_start: activating '/dev/zram0' for swapping (29 MegaBytes)
zram_reset: enforcing defaults via /sys/block/zram0/reset
Setting up swapspace version 1, size = 29 MiB (30404608 bytes)
no label, UUID=df370c1d-eece-47fb-94c9-e2401eabc2ee
Collected errors:
 * opkg_install_cmd: Cannot install package openwrt.`

After that the package seems to be installed and usable.

**Comment by hnyman** [comment]
I don't understand where the error is? Except that you have specified a non-existing package "openwrt".
