### ISSUE TITLE
zerotier virison update

### ISSUE THREAD

**Issue by turing-king** [openwrt/packages#4313]
The latest version is 1.2.4, please hurry up to update it

**Comment by hnyman** [comment]
> The latest version is 1.2.4, please hurry up to update it

Feel free to contribute, do the update and submit a pull request for the maintainer  @mwarning

**Comment by mwarning** [comment]
See https://github.com/openwrt/packages/pull/4327

@turing-king please be aware that is a voluntary. :-)

**Comment by turing-king** [comment]
@mwarning  Thank you very much for your selfless dedication. I have compiled the latest version and have successfully installed it.
