### ISSUE TITLE
ipt-netflow: Feature request

### ISSUE THREAD

**Issue by nL1ght5** [openwrt/packages#4314]
Request to add netflow capabilities for LEDE/OpenWrt/... 

The ipt-netflow package (https://github.com/aabc/ipt-netflow) can apparently already  be built for LEDE/OpenWrt, could it be considered to be added as a standard package?

**Comment by hnyman** [comment]
Feel free contribute: 
* craft the needed package Makefile, compile and test it, 
* volunteer to be the maintainer for the package, and 
* submit a Pull Request for importing the package here.

If others show interest for the package, it might get accepted to the repo.)

**Comment by nL1ght5** [comment]
Update, apparently someone did the work and the needed Makefile has already been crafted.
https://github.com/alex-eri/ipt-netflow/blob/openwrt-makefile/openwrt/Readme.md

**Comment by dibdot** [comment]
feel free to open a PR.
