### ISSUE TITLE
Snort: Update to version 3.0

### ISSUE THREAD

**Issue by uihdff** [openwrt/packages#4330]
-------------------------------

Maintainer: @Luka Perkov <luka@openwrt.org>

Please update to latest version, currently 3.0.

**Comment by commodo** [comment]
I think that's the wrong luka
@lperkov

**Comment by diizzyy** [comment]
@uihdff 
Update notifications are being sent via uscan runs by @sdwalker, no need to create issues for update requests. Please close this.
