### ISSUE TITLE
How to update the software source for my OpenWrt device to the latest

### ISSUE THREAD

**Issue by turing-king** [openwrt/packages#4344]
I see your software version has been updated, but i run 'opkg update && opkg install xxx', the installation of the software is not the latest version

**Comment by porjo** [comment]
Which software are you referring to? Please provide the output of `opkg info xxx` (where xxx is the package you want to update). Also, provide the output of `cat /proc/version`

**Comment by turing-king** [comment]
@porjo 
`root@LEDE-X64:~# opkg update zerotier
Downloading https://mirror.0x.sg/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_core
Downloading https://mirror.0x.sg/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_base
Downloading https://mirror.0x.sg/lede/snapshots/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_luci
Downloading https://mirror.0x.sg/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_packages
Downloading https://mirror.0x.sg/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_routing
Downloading https://mirror.0x.sg/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/x64_telephony
root@LEDE-X64:~# zerotier-cli -v
1.2.2
`

**Comment by turing-king** [comment]
@porjo I am sorry, my mother tongue is not English, ok, this is not my reason.
I am using other linux system, are using 'update package' to update.
Openwrt is using 'upgrade'
