### ISSUE TITLE
coova-chilli: Enhanced Feed Makefile

### ISSUE THREAD

**Issue by xmaysonnave** [openwrt/packages#4350]
Maintainer: Imre Kaloz <kaloz@openwrt.org>
Environment: 
- Target:Mediatek Ralink MIPS
- Subtarget: MT7620 based boards
- Target Profile: GL-Inet GL-MT300A
- LEDE 17.01.1

Description:
The default feed Makefile for coova-chilli-1.3.0+20141128 available at OpenWRT/LEDE exposes a minimal set of compile options. The following attachments expose all the available compile option. The needed files for coova-chilli-1.3.0+20141128 and coova-chilli-1.4 are provided.
Thanks
[coova-chilli-1.3.0+20141128.tar.gz](https://github.com/openwrt/packages/files/992648/coova-chilli-1.3.0.20141128.tar.gz)
[coova-chilli-1.4.tar.gz](https://github.com/openwrt/packages/files/992649/coova-chilli-1.4.tar.gz)

**Comment by zelda14** [comment]
The default feed Makefile for coova-chilli-1.3.0+20141128 available at OpenWRT/LEDE exposes a minimal set of compile options. The following attachments expose all the available compile option. I provide either the needed files for coova-chilli-1.3.0+20141128 and coova-chilli-1.4.
Thanks
[coova-chilli-1.3.0+20141128.tar.gz](https://github.com/openwrt/packages/files/992638/coova-chilli-1.3.0.20141128.tar.gz)
[coova-chilli-1.4.tar.gz](https://github.com/openwrt/packages/files/992642/coova-chilli-1.4.tar.gz)

**Comment by dibdot** [comment]
feel free to open a PR.
