### ISSUE TITLE
pprindeville should be in @openwrt/package-maintainers group

### ISSUE THREAD

**Issue by dangowrt** [openwrt/packages#4372]
Philip maintains several packages (perl, isc-dhcp, lcdproc) but doesn't have commit access. This should be fixed and he should be invited to https://github.com/orgs/openwrt/teams/package-maintainers

**Comment by sbyx** [comment]
@pprindeville you have an invitation. 
Please read and follow our contribution guidelines at https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md and you are good to go!

**Comment by pprindeville** [comment]
Thanks!
