### ISSUE TITLE
openvswitch: build fails because "debian/ovs-monitor-ipsec': No such file or directory"

### ISSUE THREAD

**Issue by jmguzmanc** [openwrt/packages#4394]
OpenWRT build fails because some issue with openvswitch

I am using last code from master

```
install -m0755 /home/ubuntu/openwrt_kvm_last/build_dir/target-x86_64_musl-1.1.16/linux-x86_64/openvswitch-2.7.0/debian/ovs-monitor-ipsec /home/ubuntu/openwrt_kvm_last/build_dir/target-x86_64_musl-1.1.16/linux-x86_64/openvswitch-2.7.0/ipkg-x86_64/openvswitch-ipsec/usr/sbin/
install: cannot stat '/home/ubuntu/openwrt_kvm_last/build_dir/target-x86_64_musl-1.1.16/linux-x86_64/openvswitch-2.7.0/debian/ovs-monitor-ipsec': No such file or directory

```
I am not familiar with Makefiles.
Could any of you guys provide me some guidance?

Thanks a lot
JM

**Comment by commodo** [comment]
my bad for this ; 
PR https://github.com/openwrt/packages/pull/4381  should fix this

**Comment by diizzyy** [comment]
@jmguzmanc 
Please test, if it works close this issue report.

**Comment by commodo** [comment]
it seems it wasn't completely fixed ;
i submitted a PR yesterday that seems to have fixed it for buildbot

i no longer see it in buildbot's faillogs
http://downloads.lede-project.org/snapshots/faillogs/mipsel_24kc/packages/

**Comment by jmguzmanc** [comment]
It works like a charm!
All packages generated
`./bin/x86/packages/packages/kmod-openvswitch_4.4.14+2.7.0-1_x86_64.ipk
./bin/x86/packages/packages/openvswitch_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-base_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-ovs-appctl_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-ovsdb-client_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-ovs-dpctl_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-ovs-ofctl_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-ovs-vsctl_2.7.0_x86_64.ipk
./bin/x86/packages/packages/openvswitch-python_2.7.0_x86_64.ipk`

Thanks a lot, and my apologies for the delay.
JM
