### ISSUE TITLE
libaudiofile fails to compile with GCC 7.1.0

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#4396]
Bug fix is here: https://github.com/mpruett/audiofile/commit/b62c902dd258125cac86cd2df21fc898035a43d3

I tried creating a patches directory and putting the diff in there but it fails.

Posting this so someone else can fix.

**Comment by thess** [comment]
cf39348 should fixed this problem plus several other reported CVE issues.

**Comment by diizzyy** [comment]
@neheb 
Please close this one as its fixed.
