### ISSUE TITLE
CoovaChilli: HS_UAMDOMAINS not working

### ISSUE THREAD

**Issue by muhdusman** [openwrt/packages#4397]
Environment: OpenWRT 15
Description:
I have tried installing coovachilli 1.3.0 on openwrt v15, everything is working great except the Allowed Domains. Lets say if I want to allow complete Facebook domain. Its not working. If I add the corresponding IP networks in IP allowed list, then that works. But apparently the complete domain white listing is not working.

HS_DNS1=8.8.8.8
HS_DNS2=8.8.4.4
HS_UAMALLOW=8.8.8.8,8.8.4.4
HS_UAMDOMAINS="amazonaws.com,.googleapis.com"

Results;
Pinging amazonaws.com [72.21.206.80] with 32 bytes of data:
Request timed out.
Request timed out.

**Comment by dibdot** [comment]
CC 15.05 is unmaintained.
