### ISSUE TITLE
mpd: Pulls a lot of redundant libs?

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#4399]
@thess 

I might be wrong here but as far as I can tell we're pulling a lot of redundant libs as from what I can tell it'll use ffmpeg for all supported formats? That might be even more beneficial even for the mini-package.

http://wiki.hydrogenaud.io/index.php?title=Music_Player_Daemon

That would also potentially mean that we could drop packages such as libaudiofile.

**Comment by thess** [comment]
Could you be more specific -- and have you tested it with enough format variations?

I put quite a bit of work testing the 'mini' config a number of years ago and back then it was cut to the bone for the desired codecs and features. I'm sure things have aged. OK, I'm always up for a new config but don't have the time/desire to change anything at-the-moment. At least as of a couple of years ago, I could still fit mpd-full + ffmpeg-audio-dec w/ some pretty odd codecs into an 8/32 system. We may have lost that along the way - haven't tried lately.

**Comment by diizzyy** [comment]
I was more thinking of the full version, +libaudiofile  +BUILD_PATENTED:libfaad2 +libogg +libsndfile +libvorbis should all be unnecessary if you link ffmpeg no?

**Comment by thess** [comment]
If all you have is a hammer - everything looks like a nail :wink:

**Comment by thess** [comment]
@diizzyy - I think we can close this for now, OK?

**Comment by diizzyy** [comment]
Yes, I'll close it.
