### ISSUE TITLE
Upgrade Request: minidlna (ReadyMedia) to 1.2.0

### ISSUE THREAD

**Issue by ZacWolf** [openwrt/packages#4408]
Would it be possible to request an upgrade of package minidnla to latest ReadyMedia 1.2.0?

Just released a few days ago, but since it's patched so rarely...

1.2.0 - Released 17-May-2017
--------------------------------
- Add libavformat > 57 compatibility.
- Add TiVo Bonjour discovery support using Avahi for Bolt.
- Improve Samsung BD-J5500 support.
- Add quirk to fix video playback on Hyundai TVs.
- Add non-destructive update rescan support.
- Enhance bookmark support to work with Kodi.

**Comment by diizzyy** [comment]
@ZacWolf  #4421

**Comment by diizzyy** [comment]
Please test the pull request and close this issue unless you find any problems with the new version.

**Comment by ZacWolf** [comment]
I install via Entware-NG so I've opened a case for this to sync with you upstream feed, so that it builds for my router. I'll close once I'm able to install via opkg.  THANKS!!!

**Comment by diizzyy** [comment]
@ZacWolf 
Updated, please close this issue report.

**Comment by diizzyy** [comment]
@hnyman @thess 
Fixed, please close
