### ISSUE TITLE
tvheadend - Update to 4.2

### ISSUE THREAD

**Issue by lylejenson** [openwrt/packages#4409]
Any chance of updating tvheadend to the latest version 4.2?

**Comment by hnyman** [comment]
> Any chance of updating tvheadend to the latest version 4.2?

Any chance of you targeting your message to the maintainer of that package? Maintainers do not get automatically all messages...

cc to tvheadend maintainer @sairon

**Comment by sairon** [comment]
Thanks for notifying, I did not notice the new version after the long period without any public releases. I'll take a look at it soon and update it if everything goes well.

**Comment by roni261980** [comment]
anyone can update tvheadend to last stable release v4.2.3.33

**Comment by diogosena** [comment]
@sairon any news on this?

**Comment by 9000000** [comment]
Why not updated 😥😥😥😥😥

**Comment by kofec** [comment]
Hi if you have a while you can compile for yourself:
https://github.com/CZ-NIC/turris-os-packages/blob/test/multimedia/tvheadend/Makefile
I found this repo today

**Comment by 9000000** [comment]
team lede where are you ? 
,...............................................................!!!¡!!!!!!!!!!!!!!!!!!!!!!!!!!!¡

**Comment by hnyman** [comment]
> team lede where are you ?

If @sairon is not taking care of the maintainer role and version upgrades, then somebody else who is interested, could take over the maintainership and author the version upgrade Pull Request.

This is a community effort. So it might just as well be you, @9000000

**Comment by 9000000** [comment]
Share tvheadend 4.1 #5942

**Comment by sjjgo** [comment]
Please look at the PR I have created to update this package: https://github.com/openwrt/packages/pull/6386

**Comment by sjjgo** [comment]
@hnyman I'm not sure if @sairon is maintaining the package any more. I am happy to take this responsibility on if they no longer wish to be involved in looking after this package.

**Comment by benteam10** [comment]
Here is Tvheadend 4.2.6 for LEDE 17.1.4     for architecture  AR7xxx 
i run it on a Archer C7 V2  MIPS 24Kc   
https://drive.google.com/open?id=1k1Bs-GCsIyG68wdNGnPL6B-ybdjyRda5

runs very well

i couldnt compile it for chaos calmer since the built system is not complete it doesnt have the packages anymore. 
if it starts and ask for a username and password  edit the /etc/init.d/tvheadend    in the line that shows the ARGS  -B   ad  -C  save and start it, is not going to ask you for credentials anymore.

**Comment by hnyman** [comment]
closing this, as  PR #6386 contains the concrete proposal for the version bump.
