### ISSUE TITLE
shadowsocks-libev 3.0.6-1 don't have ss-local nor ss-server?

### ISSUE THREAD

**Issue by steve3d** [openwrt/packages#4435]
I know that entware-ng is mostly based on this, after shadowsocks-libev upgraded from 2.5.1 to 3.0.6, I found there is no `ss-local` program but `/opt/etc/init.d/S22shadowsocks` still want to start the `ss-local`.

So I'm sure this is a big problem, without the `ss-local` program in `shadowsocks-libev`, the whole package are rendered as totally useless.

Please see the following output by `opkg files`

```
admin@RT-AC68U-10E8:/jffs/bin# opkg files shadowsocks-libev
Package shadowsocks-libev (3.0.6-1) is installed on root and has the following files:
/opt/etc/shadowsocks.json
/opt/bin/ss-tunnel
/opt/etc/init.d/S22shadowsocks
/opt/bin/ss-rules
/opt/bin/ss-redir
admin@RT-AC68U-10E8:/jffs/bin# 
```

See? there is no `ss-local` nor `ss-server`, althought that `ss-server` is not important, but `ss-local` is the most important program in this package. This is like the gcc packages without the `gcc` program.

Hope it gets fixed soon.

BTW, the asus-ac68u is a arm platform.

**Comment by diizzyy** [comment]
@steve3d 
https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile#L62
Can you provide a pull request?

**Comment by steve3d** [comment]
sure, will do it later today.

**Comment by hkjuniordev** [comment]
Please fix this as soon as possible, shadowsocks without ss-local and ss-server is completely useless! Thanks!

**Comment by zeroxia** [comment]
It looks like the shadowsocks-libev package maintained by openwrt just does not have ss-local or ss-server (or at least this is not the first time it misses these two executables), why does it elect to do so? Just to save disk space?

**Comment by steve3d** [comment]
I've already provided a PR in #4455 , but the maintainer of this packages seems having trouble to decide what to do.

**Comment by yousong** [comment]
Hi, @steve3d , I am rewriting packaging method of shadowsocks-libev and opened a pr https://github.com/openwrt/packages/pull/4513 for this.  `ss-local` has been added there but not `ss-server`.  If you still need it, please give further comments there.

**Comment by shounak-de** [comment]
@yousong `ss-server` is the only binary that I use. Please include it.

**Comment by yousong** [comment]
hi, @shounak-de , now uci support for ss-server is added in the pull request.  Please give it a try and see if it can fulfil your needs.

I am curious about the setup.  Is the ss-server instance running on your home router and intended to provide a secure channel to connect back to your home network?

**Comment by shounak-de** [comment]
I'd need to wait till [entware-ng] (https://github.com/Entware-ng/Entware-ng) picks up your changes. It is a downstream repo that I use for my router.

My setup is quite simple. I use shadowsocks as my VPN tunnel to my home network. Server on router, clients on phone and other PCs. There are some clear advantages over a similar openvpn setup, and that is why I chose shadowsocks.

**Comment by yousong** [comment]
I am closing this now as pr #4513 was just merged.  Thanks for the feedback.

**Comment by la88962** [comment]
Please include ss-server
