### ISSUE TITLE
cfengine3 - add new package

### ISSUE THREAD

**Issue by anonymous09** [openwrt/packages#4535]
cfengine is the leanest and fastest configuration solution in the industry and written on C.

Please, add cfengine3 community version to packages.

Homepage: https://cfengine.com/

**Comment by pprindeville** [comment]
Can you add a URL to its home page?

**Comment by anonymous09** [comment]
Ok, i've updated topic.

**Comment by anonymous09** [comment]
Hi! Someone looked here?

**Comment by diizzyy** [comment]
@anonymous09 
Sorry, we don't handle package requests as "Issues"

Please close this

**Comment by diizzyy** [comment]
@hnyman @thess 
Not an "issue", please close
