### ISSUE TITLE
ntpd: Build issues relro: No such file or directory

### ISSUE THREAD

**Issue by ketulbarot** [openwrt/packages#4547]
------------------------------

Maintainer: @tripolar 
Environment: (put here arch, model, OpenWRT/LEDE version)

Description:
I was using ntpd version 4.2.8p6 earlier and tried updating it with the latest 4.2.8p10 provided here but the latest version fails to build with error "arm-none-linux-gnueabi-gcc: relro: No such file or directory
arm-none-linux-gnueabi-gcc: now: No such file or directory". I am not quite knowledgeable with package building stuff and any help on this would be appreciated.

I am also attaching the config.log file from the ntpd.

Thanks,  
Ketul

[config.txt](https://github.com/openwrt/packages/files/1125696/config.txt)

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by tripolar** [comment]
clean your build tree and try to rebuild the whole lede toolchain.

If the problem stilll persists please comment on this issue
