### ISSUE TITLE
musl compatibility: tcp-wrappers (libwrap)

### ISSUE THREAD

**Issue by nakarotori** [openwrt/packages#456]
error: 
ld: cannot find -lnsl

musl does not have separate libnsl like uclibc
Source: http://git.buildroot.net/buildroot/commit/?id=36ef1b4494f669d9c6f8507fb912f83f46a2d63d

possible solution:
use some config symbol test which libc is used and then add "-lnsl" to LIBS:
CONFIG_LIBC_USE_MUSL , CONFIG_USE_MUSL=y , CONFIG_LIBC="musl"
don't know about the differences

**Comment by diizzyy** [comment]
Compiles if you remove -lnsl in Makefile.
Tested on a ~12h old trunk and package checkout with musl and libstdc++.
