### ISSUE TITLE
package-expat: Download failure since last commit

### ISSUE THREAD

**Issue by xback** [openwrt/packages#4595]
Maintainer: @diizzyy 
Environment: LEDE master

Description:
Package download failure since commit 9460b1b1c86d6a8651eb08190c3c00efe8eaf257:

**Buildlog:**

SHELL= flock /mnt/ramdisk/test/firmware/builds/generic_cns3xxx/tmp/.expat-2.2.2.tar.bz2.flock -c '  	/mnt/ramdisk/test/firmware/builds/generic_cns3xxx/scripts/download.pl "/mnt/ramdisk/test/firmware/builds/generic_cns3xxx/dl" "expat-2.2.2.tar.bz2" "cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7" "" "@SF/expat"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.sourceforge.net/expat/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   368    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   347    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  396k  100  396k    0     0   385k      0  0:00:01  0:00:01 --:--:--  385k
Hash of the downloaded file does not match (file: 4376911fcf81a23ebd821bbabc26fd933f3ac74833f74924342c29aad2c86046, requested: cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.sourceforge.net/expat/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   368    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   347    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  396k  100  396k    0     0   399k      0 --:--:-- --:--:-- --:--:--  399k
Hash of the downloaded file does not match (file: 4376911fcf81a23ebd821bbabc26fd933f3ac74833f74924342c29aad2c86046, requested: cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.sourceforge.net/expat/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   368    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   339    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  396k  100  396k    0     0   276k      0  0:00:01  0:00:01 --:--:-- 1093k
Hash of the downloaded file does not match (file: 4376911fcf81a23ebd821bbabc26fd933f3ac74833f74924342c29aad2c86046, requested: cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.sourceforge.net/expat/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   368    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   347    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  396k  100  396k    0     0   383k      0  0:00:01  0:00:01 --:--:-- 1020k
Hash of the downloaded file does not match (file: 4376911fcf81a23ebd821bbabc26fd933f3ac74833f74924342c29aad2c86046, requested: cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.sourceforge.net/expat/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   368    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   339    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  396k  100  396k    0     0   274k      0  0:00:01  0:00:01 --:--:--  490k
Hash of the downloaded file does not match (file: 4376911fcf81a23ebd821bbabc26fd933f3ac74833f74924342c29aad2c86046, requested: cd77a2869e32354b004cc6b34fcb0bee56114caa2d9ed862aaa8071441e34eb7) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://sources.lede-project.org/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://mirror2.openwrt.org/sources/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://downloads.openwrt.org/sources/expat-2.2.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.

**Comment by thess** [comment]
Should be fixed in https://github.com/openwrt/packages/commit/b8bc3fe3f5871bdcd75991cedb542f13221cb65e 
Shame on me for not testing before merge
