### ISSUE TITLE
postfix: post install script 

### ISSUE THREAD

**Issue by flipreverse** [openwrt/packages#4620]
Hi folks,

Since issue #582 is fixed, the postfix post install script sets the right permissions for every file needed by postfix. Even though the permissions are already correct, it sets them. The kernel therefore copies the file, which gets chmodded, to the overlayfs. Since the config partition is pretty small, even on an ARCHER C2600, the postfix files consume the whole space leaving no space for any config files.

Might it be possible to patch the post-install script to check whether a chmod is necessary?
If not, it steps over leaving the file as it is, and don't waste any space.

Cheers,
Alex

**Comment by hnyman** [comment]
cc @lucize @Shulyaka

**Comment by Shulyaka** [comment]
Hi Alex

Is it the 'postfix set-permissions' command that makes the trouble?

**Comment by flipreverse** [comment]
@Shulyaka Yes.

**Comment by Shulyaka** [comment]
Ok, will try to fix it.

**Comment by Shulyaka** [comment]
@flipreverse Are you able to test the fix #4661, whether it solves the problem for you?

**Comment by flipreverse** [comment]
@Shulyaka The issue seems to be fixed. :) Thank you!

**Comment by Shulyaka** [comment]
Thank you for testing!

сб, 5 авг. 2017, 17:24 Alexander Lochmann <notifications@github.com>:
