### ISSUE TITLE
Coova Config misleading

### ISSUE THREAD

**Issue by bitdevelopment** [openwrt/packages#4655]
Coova `/etc/config/chilli` is misleading as some options are not working at all, examples:

`option debug 9` 

will raise error that --debug does not support arguments,

`option fg` 

is not applied to config file and therefore is not working.

If `option pidfile` is commented, stopping service is impossible without manually killing it.

Please take in consideration that I am new with OpenWrt. Also to mention that I am using x86 current stable released image of OpenWrt. 

I hope I helped!

**Comment by dibdot** [comment]
Sounds not like a package issue - please join the OpenWrt forum (https://forum.openwrt.org) for further support.
