### ISSUE TITLE
Travis: non-zero return codes not reflected in Travis results.

### ISSUE THREAD

**Issue by bobmseagithub** [openwrt/packages#4666]
When ./.travis_do.sh test_packages intends to return 1, the Travis log indicates "Done. Your build exited with 0."
This seems incorrect.
In this example, the message from .travis_do.sh was:
```Commit subject line MUST start with '<package name>: ' (packages/.travis_do.sh: Fix Signed-off-by Name)```

Example:
https://travis-ci.org/openwrt/packages/builds/260413806?utm_source=github_status&utm_medium=notification

**Comment by champtar** [comment]
Hi @bobmseagithub 
thanks for reporting, fixed in https://github.com/openwrt/packages/commit/0bffa6b48b6b37ba203abcc4eb661829f61e920f
