### ISSUE TITLE
netopeer-2 : build failing

### ISSUE THREAD

**Issue by shahanshasalim** [openwrt/packages#4667]
When compiling Netopeer-2 package for x86_64 target, compilation fails giving the following error.
Please find the logs attached. I am building on sdk checked out from https://github.com/openwrt/openwrt.git . All dependent packages like libyang,libnetconf2,openssh,sysrepo,etc are enabled and compilation for those were successful.  Kindly provide feed back on how to proceed. 
[log.txt](https://github.com/openwrt/packages/files/1197060/log.txt)

**Comment by dibdot** [comment]
official buildbot has no problems with netopeer for x86
