### ISSUE TITLE
mwan3: second wan tracking gets killed when first goes down

### ISSUE THREAD

**Issue by nileshgr** [openwrt/packages#4694]
Maintainer: @feckert 

Description:

When first interfaces goes down, mwan3 kills the second interface's tracking daemon (mwan3track). 

Reason: 

```
Line 452 in lib/mwan3/mwan3.sh
kill $(pgrep -f "mwan3track $1") &> /dev/null
```

So if you have named your interfaces as wan & wan2, when wan (1) goes down, it will kill wan2 because pgrep matches wan2 daemon too (pattern matching).

Possible easiest solution:
Update documentation and sample configuration files to use interfaces as wan1 and wan2.

**Comment by feckert** [comment]
I have already fixed this issue. https://github.com/openwrt/packages/commit/0b44ca505bdb882b7b2d68431ca8b2a739f6cc97

**Comment by nileshgr** [comment]
That's weird. I've been using trunk version and pulled about 2-3 days back.
You fixed it 12 days ago.

**Comment by feckert** [comment]
I made the fix 12 days ago on my forked repository.
But i have pushed the changes on Thursday after testing.
The date use see on the commit are the changes when they are committed on the forked repository!
The date will not changed if the get merged in the upstream repository.

**Comment by nileshgr** [comment]
Well since you have tested it I am closing this issue. I have already renamed my interfaces to wan1 & wan2. Not sufficient changes in core / packages for me to update my image. Saving flash cycles by not updating. 😀

**Comment by feckert** [comment]
@nileshgr thanks for feedback :-)
