### ISSUE TITLE
node: Makefile bug fixes.

### ISSUE THREAD

**Issue by take99** [openwrt/packages#4742]
There is a problem in line 86.
CONFIGURE_ARGS + = with-arm-float-abi = softfp
fixed
CONFIGURE_ARGS + = --with-arm-float-abi = softfp

**Comment by nxhack** [comment]
@take99 
fix typo done. but node.js is not work on ARM core without hardware FPU.
See: 
https://github.com/nodejs/node/issues/7343
https://bugs.chromium.org/p/v8/issues/detail?id=4704

**Comment by diizzyy** [comment]
@nxhack 
So we can close this one?
