### ISSUE TITLE
php-fpm: got segment fault when i install and load 'php7-pecl-http'

### ISSUE THREAD

**Issue by 805447391** [openwrt/packages#4753]
yesterday. i deploy nextcloud on my Raspberry Pi 3b (Firmare 17.0.2 LEDE musl, 32bit system run on aarch64 cpu), i have installed nginx and mysql-server, then i find if i do ```opkg install php7-pecl-http```and run php-* programs, i would get Segment Fault ~but if i remove this package, it works normally. so, can you find out where is problem? thanks very much!

**Comment by mhei** [comment]
@805447391: could you please post the output when you run `opkg list_installed` and the output when you run `ls -la /etc/php7/*` via SSH (or debug console). Thanks

**Comment by 805447391** [comment]
i have fixed this problem by rebuilding package php-pecl-http using my lede sdk, it works normally now, thanks very much, best wishes!
