### ISSUE TITLE
gcc:gcc must with --mfloat-abi=hard --mfpu=neon-vfpv4 can run good

### ISSUE THREAD

**Issue by 805447391** [openwrt/packages#4754]
target 17.0.2 bcm2710
32bit system in aarch64 cpu

problem : gcc could not compile helloworld.c
ps: if i run ```gcc hellowprld.c --mfloat-abi=hard -mfpu=neon-vfpv4``` is ok.
can you give me a good idea to avoid append these paramters or fix this 'bug' ?

**Comment by 805447391** [comment]
i have fixed this problem after reinstalling gcc. but i dont know what is the reason of this .

**Comment by 805447391** [comment]
sorry, i just set a alias for gcc, this problem still exist...

**Comment by 805447391** [comment]
but when i use snapshots mirror :  http://downloads.lede-project.org/snapshots/packages/arm_cortex-a53_neon-vfpv4/packages/gcc_5.4.0-2_arm_cortex-a53_neon-vfpv4.ipk
IT IS OKAY ~WTF

**Comment by 805447391** [comment]
i guess there is a small bug in gcc which in package17.0.1

**Comment by diizzyy** [comment]
@champtar @hnyman 
If anything, this is a toolchain issue. Can you close?
