### ISSUE TITLE
SOX did not install on ReSpeaker

### ISSUE THREAD

**Issue by algomusic** [openwrt/packages#4759]
Maintainer: @thess 
Environment: OpenWRT/LEDE version - (Chaos Calmer, v0.9.99)

Description:

Tried to install the SOX package on the ReSpeaker Core and got this error:

 * check_data_file_clashes: Package sox wants to install file /usr/bin/play
	But that file is already provided by package  * respeaker-os-file
 * opkg_install_cmd: Cannot install package sox.

**Comment by thess** [comment]
Apparently, the core ReSpeaker os images already have a 'play' utility installed. You can overwrite it with
__--force-overwrite__ option to opkg or. better yet, rename the existing utility to another name before installing SOX.

There is not much guaranteed (or managed) file-name uniqueness between open-source applications. I think it is up to you to sort it out.

**Comment by thess** [comment]
Closed - not a bug.
