### ISSUE TITLE
mpd: remove dependency on GLib2

### ISSUE THREAD

**Issue by LLE8** [openwrt/packages#4780]
Maintainer: @thess
Environment: LEDE master 

Description:
May be remove dependency on GLib2 in Makefile?
It was removed from original MPD
http://git.musicpd.org/cgit/master/mpd.git/plain/NEWS?h=v0.20
GLib is huge for LEDE.

**Comment by thess** [comment]
Wow - didn't notice the change even though I was never happy with the dependency. Thanks for the heads-up. 

Fixed by #4783 and #4782
