### ISSUE TITLE
lighttpd : Failing to build in LEDE snapshots

### ISSUE THREAD

**Issue by bluewavenet** [openwrt/packages#4794]
lighttpd is currently failing to build in LEDE snapshots.
Is anyone working on this?

**Comment by champtar** [comment]
http://downloads.lede-project.org/snapshots/faillogs/mipsel_24kc/packages/lighttpd/compile.txt

**Comment by champtar** [comment]
@MikePetullo

**Comment by bluewavenet** [comment]
@MikePetullo or whoever set to work - it is working this morning - brilliant thanks :-)
