### ISSUE TITLE
LuCI GUI generates incorrect fwknopd conf parameters for dropdowns

### ISSUE THREAD

**Issue by leonyu** [openwrt/packages#4795]
Maintainer: @jp-bennett 
Environment: LEDE 17.01.2 on Linksys WRT1900AC

Description:

LuCI GUI generates incorrect fwknopd conf parameters for dropdowns -- specifically `Key type` & `HMAC Key type`.

Although benign for my use, it produces following error: 
```
Sat Sep  2 00:31:54 2017 daemon.err fwknopd[1844]: [*] Ignoring unknown access parameter: 'keytype' in /var/etc/access.conf
Sat Sep  2 00:31:54 2017 daemon.err fwknopd[1844]: [*] Ignoring unknown access parameter: 'hkeytype' in /var/etc/access.conf
```

With some minor digging, problem maybe in `fwknopd.lua` file.

**Comment by jp-bennett** [comment]
I believe these parameters are stored for the luci interface, and are injected into the config file as a byproduct.  I'll take a closer look, but if I remember correctly, this is expected behavior.

**Comment by dibdot** [comment]
See also https://github.com/openwrt/luci/issues/2062
