### ISSUE TITLE
boost doesn't build since 1.65.0 upgrade

### ISSUE THREAD

**Issue by stintel** [openwrt/packages#4798]
Maintainer: @ClaymorePT 
Environment: LEDE master on x86/64

Description:
Boost no longer builds for me, but I can't immediately spot the error. Will rebuild, capture full log and update ticket.

**Comment by stintel** [comment]
Great, after failing at least 5 times, it now built fine. I'll reopen when I can reproduce it again.

**Comment by ClaymorePT** [comment]
Hi @stintel !

Thanks for the heads-up. In the past, I already notice some issues in building Boost for x86_64, due to some issues with Musl.

Feel free to send me an e-mail if you encounter some other issues.
