### ISSUE TITLE
transmission - polarssl

### ISSUE THREAD

**Issue by zero13th** [openwrt/packages#487]
Please compile transmission package using polarssl

**Comment by protectivedad** [comment]
I for one would appreciate this. The dependents are a little ridiculous. Transmission requires libopenssl and libcurl. Curl require libpolarssl. So it transmission no matter luci or not requires two different ssl libraries. Is there any way to stop this?

**Comment by obsy** [comment]
Dnia 2015-01-28, o godz. 14:56:49
protectivedad <notifications@github.com> napisał(a):

> I for one would appreciate this. The dependents are a little ridiculous. Transmission requires libopenssl and libcurl. Curl require libpolarssl. So it transmission no matter luci or not requires two different ssl libraries. Is there any way to stop this?

libcurl can depend on libopenssl, just change it in menuconfig.

-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by zero13th** [comment]
typical 'take-it-or-leave-it' developer's answer :)

**Comment by obsy** [comment]
Dnia 2015-01-28, o godz. 22:05:39
zero13th <notifications@github.com> napisał(a):

> typical 'take-it-or-leave-it' developer's answer :)

I'm not developer. Normal user like other.

-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by nmav** [comment]
That is an issue that is not restricted to this package. The best is to bring the issue to the ML.

**Comment by zero13th** [comment]
No, I am referring to people who close this ticket. Not everyone can make a
patch. Double dependency on limited disk space is inefficient


On Thu, Jan 29, 2015 at 1:08 PM, Cezary Jackiewicz <notifications@github.com
> wrote:

> Dnia 2015-01-28, o godz. 22:05:39
> zero13th <notifications@github.com> napisał(a):
>
> > typical 'take-it-or-leave-it' developer's answer :)
>
> I'm not developer. Normal user like other.
>
> --
> Pozdrawiam,
> Cezary Jackiewicz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openwrt/packages/issues/487#issuecomment-71973884>.
>



-- 
ZerO13th
