### ISSUE TITLE
ddns-scripts: should provide support for POSTed data

### ISSUE THREAD

**Issue by dkg** [openwrt/packages#4878]
ddns-scripts basically just sends HTTP and HTTPS `GET` requests that include potentially sensitive parameters like passwords.

But `GET` URLs have a tendency to be logged on server logs, stored in browser histories, etc, so a privacy- and security-preserving dynamic DNS service might prefer to use HTTP/S `POST` requests instead, and to send the sensitive parameters as part of the `POST` data.

So i'm proposing a new field for ddns client scripts, named something like `postdata`.  if that field is set, then we send a `POST` instead of a `GET`, and it has the same substitutions available as `url`.

To implement: with `wget`, you can use `--post-data`.  with `curl` you can use `--data`, i think.

@chris5560 is the maintainer

**Comment by dkg** [comment]
@chris5560 i think this is for you

**Comment by dibdot** [comment]
no feedback - close this by now.
