### ISSUE TITLE
sudo lacks sudoedit (and sudoreplay)

### ISSUE THREAD

**Issue by buergi** [openwrt/packages#4888]
The sudo package lacks the sudoedit symlink to allow users to securely edit files.
Usually it is installed in upstream [sudo](https://www.sudo.ws/repos/sudo/file/tip/INSTALL), I guess it is simply not packed into this package.
As a workaround `ln -s sudo /usr/bin/sudoedit` or similar works, but I would appreciate having this link in the package.

The same is true for sudoreplay, except that the workaround does not work here, however, maybe this tool is not necessary to have on embedded devices.

**Comment by diizzyy** [comment]
Please do a pull request if possible

**Comment by dibdot** [comment]
feel free to open a PR.
