### ISSUE TITLE
postgresql source download fails

### ISSUE THREAD

**Issue by tatel777** [openwrt/packages#4890]
-------------------------------

Maintainer: @<jow@openwrt.org> (find it by checking history of the package Makefile)
Environment: (TPLINK 841, Chaos Calmer, r49389)

Description: postgresql v9.4.4 source download fails.
Solved editing Makefile so PKG_SOURCE_URL gets:
PKG_SOURCE_URL:=\
        https://ftp.postgresql.org/pub/source/v$(PKG_VERSION)/$(PKG_SOURCE) \
        http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v$(PKG_VERSION) \
        http://ftp.be.postgresql.org/postgresql/source/v$(PKG_VERSION) \
        ftp://ftp-archives.postgresql.org/pub/source/v$(PKG_VERSION)

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/blob/master/libs/postgresql/Makefile
Please update your package tree:
```./scripts/feeds update -a
./scripts/feeds install -a ```
Keep in mind that your OpenWrt is deprecated/unsupported in favor of LEDE so your milage may vary. The plan is to merge back to OpenWrt using the LEDE tree later on.
https://github.com/lede-project/source
