### ISSUE TITLE
postfix: missing symbolic links for standard utilities

### ISSUE THREAD

**Issue by flyn-org** [openwrt/packages#492]
When I installed the postfix package on a fresh router, the package did not create symbolic links such as newaliases.postfix -> newaliases or sendmail.postfix -> sendmail. The former does not seem to run properly unless invoked as "newaliases". I think the latter is necessary for supporting MTA-independent scripts.

**Comment by MikePetullo** [comment]
I just installed OpenWrt Chaos Calmer from scratch. After doing so, I found that the postfix packages had not created the sendmail and newaliases symbolic links.

Running the commands above prints "A new symlink should have been created".

**Comment by Shulyaka** [comment]
Hi Mike,

Can you check if it created an empty /etc/postfix/opkg_postinst file in the target image? Please note that the file is deleted on the first run, so you need to check the image itself (or the directory it's built from).
Please also check if it created the postfix user entry in /etc/passwd on the first run.
