### ISSUE TITLE
luci-app-acme: upgrade, postrm script fails

### ISSUE THREAD

**Issue by Strykar** [openwrt/packages#4925]
@tohojo 
```
Linux apu 4.4.71 #0 SMP Wed Jun 7 19:24:41 2017 x86_64 GNU/Linux
LEDE Reboot 17.01.2 r3435-65eec8bd5f / LuCI lede-17.01 branch (git-17.161.67166-8eadde5)
```
Upgrading luci-app-acme fails as it did in 1.5-1 https://github.com/openwrt/packages/issues/4716
```
root@apu:~# opkg list-upgradable
luci-app-acme - 1.4-1 - 1.5-2
root@apu:~# opkg upgrade luci-app-acme
Upgrading luci-app-acme on root from 1.4-1 to 1.5-2...
Downloading http://downloads.lede-project.org/releases/17.01.2/packages/x86_64/packages/luci-app-acme_1.5-2_all.ipk
Collected errors:
 * pkg_run_script: package "luci-app-acme" postrm script returned status 1.
 * postrm_upgrade_old_pkg: postrm script for package "luci-app-acme" failed
```
Upgrading through LUCI reports the package as updated: `Package acme (1.5-2) installed in root is up to date.`

**Comment by tohojo** [comment]
The script that is failing (the postrm script) is in the old 1.4 package. The failure you are seeing is already fixed in the new version, but for obvious reasons that fix is not present in the old package, so you still get the error when upgrading. Not much to be done about that, unfortunately...
