### ISSUE TITLE
adblock - pleas add filter to most important sites (Bitcoin Mining)

### ISSUE THREAD

**Issue by build000** [openwrt/packages#4931]
@dibdot 
Blocking Web Browser Bitcoin Mining 
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
...of course, if you are not adding these pages to other filters.
info: https://zaufanatrzeciastrona.pl/post/uwazajcie-bo-znane-strony-www-kopia-kryptowaluty-na-waszych-komputerach/

**Comment by dibdot** [comment]
To use this block list, please add this to your config (untested!):

```
config source 'bitcoin'
	option enabled '0'
	option adb_src 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt'
	option adb_src_rset '\$0 ~/^0\.0\.0\.0[ \t]+([A-Za-z0-9_-]+\.){1,}[A-Za-z]+/{print tolower(\$2)}'
	option adb_src_desc 'focus malicious bitcoin mining sites, infrequent updates, approx. 15 entries'

```

**Comment by build000** [comment]
thx., added, working fine.

**Comment by dibdot** [comment]
@build000 please close this ticket, changes has been applied.

**Comment by build000** [comment]
very sorry - I forgot and in fact is already added filter - I'm already closing :+1: D
