### ISSUE TITLE
dhcpcd: needs a new maintainer

### ISSUE THREAD

**Issue by rsmarples** [openwrt/packages#4944]
I no longer use OpenWRT, nor have an environment to compile packages for it.
Please [remove me from the Makefile](https://github.com/openwrt/packages/blob/4006865ae81b20b1793ae2a07db20235fefd2c71/net/dhcpcd/Makefile#L22)

Happy to fix any reported issues though, I just can't compile or test it on the OpenWRT platform (or derivates).

**Comment by ratkaj** [comment]
If there are no objections i might as well take it. I'll throw in an update tomorrow, seems to be  outdated.

**Comment by diizzyy** [comment]
@rsmarples 
I think this is sorted now, can you close this issue?
Thanks for your contribution and future ones! :-)

**Comment by rsmarples** [comment]
Happy to close it, thanks for taking dhcpcd over in OpenWRT @ratkaj
