### ISSUE TITLE
nginx: compile --with-threads fails

### ISSUE THREAD

**Issue by jammmet** [openwrt/packages#4945]
Maintainer: @mhei
Environment: LEDE trunk

Description:

I'm trying to compile nginx `--with-threads` but receive a compile error. Am I missing a dependency?

```
src/core/ngx_spinlock.c: In function 'ngx_spinlock':
src/core/ngx_spinlock.c:47:2: error: #error ngx_spinlock() or ngx_atomic_cmp_set() are not defined !
 #error ngx_spinlock() or ngx_atomic_cmp_set() are not defined !
  ^~~~~
objs/Makefile:562: recipe for target 'objs/src/core/ngx_spinlock.o' failed
```

**Comment by diizzyy** [comment]
@jammmet 
This is fixed as far as I can tell, can you give it a try?

**Comment by diizzyy** [comment]
@thess @hnyman 
Close due to submitter timeout
