### ISSUE TITLE
for-15.05: Cannot build libsodium - url has changed

### ISSUE THREAD

**Issue by mateusz-banaszek** [openwrt/packages#5031]
Branch for-15.05:
libsodium-1.0.2.tar.gz is no longer available under PKG_SOURCE_URL:
https://github.com/openwrt/packages/blob/c52b6f8a0e09156816059142e7085cd0c3eb4c25/libs/libsodium/Makefile#L15
It seems that it was moved to https://download.libsodium.org/libsodium/releases/old/unsupported/, so the Makefile needs an update.

**Comment by thess** [comment]
Please submit a PR to branch **for-15.05** and/or notify maintainer -  @damianorenfer

**Comment by kishangondaliya** [comment]
Submitted PR: https://github.com/openwrt/packages/pull/5042 for **for-15.05** branch.

**Comment by mateusz-banaszek** [comment]
Thanks for the quick fix.
