### ISSUE TITLE
wget --post-data does not transmit data 

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#5032]
I tried the following command from x86/64 snapshot vm build and Debian 9.

`wget -O- --post-data="distro=lede" "http://192.168.1.3:5000/image-request"`

The server sides receives no data when using the snapshot, with Debian it works as expected `[”distro”, “lede”]`

**Comment by dangowrt** [comment]
I reckon you should use libuclient directly instead of relying in the
wget compatibility wrapper (or even worse: busybox-wget...).

See

https://git.lede-project.org/?p=project/uclient.git;a=summary

**Comment by diizzyy** [comment]
...or use curl for instance?

**Comment by aparcar** [comment]
@diizzyy curl isn't installed per default or am I mistaken?

**Comment by diizzyy** [comment]
No, it's an external package. "wget" is a wrapper, it's not the GNU wget which is also an external package.

**Comment by aparcar** [comment]
Thank you two for the clarification, I'll use uclient or curl. 

However, if "wget" has this option mentioned, should't it be fixed or removed from the help menu?

**Comment by aparcar** [comment]
Seems like the encoding "chunked" is in compatible to some web servers. So it's not directly a uclient-fetch issue
