### ISSUE TITLE
i2c-tools: Source download fails

### ISSUE THREAD

**Issue by jhaakana** [openwrt/packages#5075]
Maintainer: @dangowrt 
Environment: ARM Cortex A9 MV88F6720 Rev A0, OpenWRT CC r45001

Description:

The package source is no longer available on fossies.org.

```
PKG_SOURCE_URL:=http://dl.lm-sensors.org/i2c-tools/releases/ \
                http://fossies.org/linux/misc/
```

**Comment by diizzyy** [comment]
From what I can tell download URL should be @KERNEL/software/utils/$(PKG_NAME)/ and tarball should be switched to xz.
Preferably bumped to 4.0 while at it (this needs testing)

@jhaakana 
Preferably you should switch to LEDE as the package tree isn't tested against the OpenWrt tree anymore.

**Comment by jhaakana** [comment]
@diizzyy Yes, I know that I should move on to LEDE but it is not possible right now (still in few months, I think).

**Comment by diizzyy** [comment]
Please close this one, not a supported toolchain
@jhaakana @hnyman @champtar
