### ISSUE TITLE
Is it possible using second wan connection for recovery and turn back first connection when it is ready?

### ISSUE THREAD

**Issue by alptolga** [openwrt/packages#5117]
Hi,
I use  mwan3 for recovery. when my first connection fails, my second connection works. But after my first connection becomes ready,  I must turn off recovery connection to use primary connection. Is it possible to turn back my primary connection automatically?

**Comment by feckert** [comment]
@alptolga This should work out of the box. If it is configured correct. What version do you have.

**Comment by alptolga** [comment]
@feckert Thanks for your reply.
I am using  ''mwan3  1.6-2   luci-app-mwan3  1.4-3'' which are in the OpenWrt Chaos Calmer 15.05.1 default package list.

**Comment by feckert** [comment]
@alptolga It should work also for 1.6.2 but there are some issue which are fixed on lede-17.01 could you try lede-17.01 branch?

**Comment by feckert** [comment]
@alptolga any progress on your setup?

**Comment by alptolga** [comment]
I still use OpenWrt Chaos Calmer 15.05.1  with mwan3 as I wrote before. I couldn't find any solution.

**Comment by feckert** [comment]
@alptolga sorry this is only supported in the master feed with the option "initial_state"

**Comment by alptolga** [comment]
Thanks for your answers and interest about the issue I live. So the only way is closing.
