### ISSUE TITLE
missing package 'luci-proto-relay' with operwrt on dlink router

### ISSUE THREAD

**Issue by erdosnew** [openwrt/packages#5130]
i flashed openwrt firmware to my dlink dsl-2750b, Hw T1 router.
https://wiki.openwrt.org/toh/hwdata/d-link/d-link_2750_t1

I'd like to setup it as a wifi repeater.  however the needed package 'luci-proto-relay' can't be found with opkg command after i updated the package list.   

the guide i follow is https://wiki.openwrt.org/doc/recipes/relayclient

any ideas?

**Comment by dibdot** [comment]
Please join the forum (https://forum.openwrt.org/).
