### ISSUE TITLE
packet-mirroring Segmentation Fault

### ISSUE THREAD

**Issue by polachz** [openwrt/packages#5132]
Maintainer: @mmaraya 
Environment: Turris Omnia, ARM (but problem is generic)

Description:

The tool port-mirroring can't handle correctly captured packets with packet size > 2048. For example it occurs when generic receive offloading assembles several packets together. 

- In **TEE** capturing mode, it caused Segmentation Fault because fixed buffer with size 2048 is used for re-send captured packet and no check if data fit the buffer is provided, then code writes behind the buffer border.
- In **TZSP** mode packet is stripped on 2000 bytes by size check but no crash occurs.

I have prepared a patch for the 1.4.2 version (see attachment) , used in Turris Omnia, and OpenWRT. This patch checks packet size and realloc the buffer if necessary.  Of course here is question how pcap re-inject modified packet back to capturing interface (from brief check i do not see any big issues in wireshark capture), but anyway the patch solves the Seg Fault problem

IN @mmaraya  repo is now different version of the packet-mirroring daemon, but problem is here too. I believe that the patch can be easily used in this version too or based on the patch principles, the problem can be fixed there better.

Patch:
[port_mirroring_large_packet-patch.tar.gz](https://github.com/openwrt/packages/files/1478576/port_mirroring_large_packet-patch.tar.gz)

**Comment by dibdot** [comment]
feel free to open a PR.
