### ISSUE TITLE
adblock: remove disconnect.me from the default configuration

### ISSUE THREAD

**Issue by kairos10** [openwrt/packages#5146]
the filter at https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt, which is enabled by default, blocks the here.com domain (here.com is a reputable GPS navigation software and maps provider)

**Comment by dibdot** [comment]
Adblock is disabled by default. If you don't like disconnect.me simply disable this list or whitelist "here.com". Anyway, if you have issues with the list you will have to report this to maintainers of that list.

**Comment by dibdot** [comment]
I think the issue of site being blocked and possible workarounds are illustrated, so I am going to close this one.
