### ISSUE TITLE
libarchive: bsdtar depends on libarchive-noopenssl

### ISSUE THREAD

**Issue by nwf** [openwrt/packages#5147]
Maintainer: @diizzyy @morgenroth
Environment: LEDE HEAD

Description: The `bsdtar` package `DEPENDS` on `libarchive-noopenssl`, which cannot be simultaneously installed with `libarchive` itself.  I believe `bsdtar` should `DEPEND` on some symbol `PROVIDES`-ed by both `libarchive` and `libarchive-noopenssl`, but I am not sure.

**Comment by diizzyy** [comment]
Feel free to submit a patch, it should be able to use both but neither me or Johannes has considered the current configuration an issue.

**Comment by diizzyy** [comment]
Closing due to timeout
