### ISSUE TITLE
glib2: FTBFS install-data-local: Package not found in the pkg-config search path

### ISSUE THREAD

**Issue by pspoe** [openwrt/packages#5175]
-------------------------------

Maintainer: @tripolar 
Environment: ar71xx, wndr3700v2, master commit b78de6207f

Description:

Building the source on a Debian Linux Stretch/Testing system fails with
```
Package glib-2.0 was not found in the pkg-config search path.
...
make[8]: *** [install-data-local] Error 1
```
For more information see attached [glib2.log](https://github.com/openwrt/packages/files/1503940/glib2.log).
I've also attached the output of 'scripts/diffconfig.sh > [20171126-diffconfig.txt](https://github.com/openwrt/packages/files/1503945/20171126-diffconfig.txt)'

The missing file seems to be present:
```
$ find . -name glib-2.0.pc
./staging_dir/hostpkg/lib/pkgconfig/glib-2.0.pc
./build_dir/target-mips_24kc_musl/glib-2.54.2/glib-2.0.pc
./build_dir/target-mips_24kc_musl/glib-2.54.2/ipkg-install/usr/lib/pkgconfig/glib-2.0.pc
./build_dir/host/pkg-config-0.29.2/check/gtk/glib-2.0.pc
./build_dir/hostpkg/glib-2.54.2/glib-2.0.pc
```

**Comment by neheb** [comment]
Closing. There have been several version bumps that have probably fixed this.
