### ISSUE TITLE
ddns-scripts: Add DNSEver to Dynamic DNS

### ISSUE THREAD

**Issue by gschaub** [openwrt/packages#5178]
Maintainer: @chris5560
Environment: (17.1.04)

Description:

I apologize if this isn't the proper way to request an addition to the ddns-scripts package, but I was hoping you'd perform a update at your convenience to that package to add an additional provider.
```
"dnsever.com"           "http://[USERNAME]:[PASSWORD]@dyna.dnsever.com/update.php?host[[DOMAIN]]"
```
Note that I found the double brackets on domain are correct in that they keep that bracket character for the domain.  The required format is ?host[mydomain.com] rather than an = sign.

**Comment by chris5560** [comment]
Only IPv4 or also IPv6

**Comment by gschaub** [comment]
This is only IPv4.  I haven’t tested it for v6.  Is that okay to include it for v4 only?

 

Thanks…Greg

**Comment by chris5560** [comment]
It's ok for IPv4 only, but if there is IPv6 support we should implement it.

**Comment by gschaub** [comment]
I don’t see ddns for AAAA records on their site, but have sent an e-mail to verify.

**Comment by gschaub** [comment]
Note that I have verified that dnsever doesn’t currently support ddns for ip6. Please let me know if you plan to merge this into the project services file. 

Thanks...Greg
