### ISSUE TITLE
noddos:add task to cronbtab without separation from last line

### ISSUE THREAD

**Issue by DazzyWalkman** [openwrt/packages#5193]
noddos 0.5.5-1 lede r5430 x86
Install noddos via:
opkg install luci-app-noddos
Noddos will append its scheduled task to the crontab, however without proper separation from the last line of crontab, thus renders both tasks inop.

**Comment by dibdot** [comment]
@StevenHessing

**Comment by cotequeiroz** [comment]
Noddos has been removed by eb9d5bbf39e89909283c431ae981feac39b02d95.  Closing this.
