### ISSUE TITLE
ddns-scripts: Add myip.co.ua to Dynamic DNS

### ISSUE THREAD

**Issue by mavrsmart** [openwrt/packages#5199]
Is it possible to add an additional provider of myip.co.ua?
> "myip.co.ua"	"http://[USERNAME]:[PASSWORD]@myip.co.ua/update?hostname=[DOMAIN]&myip=[IP]"	"good"

**Comment by diizzyy** [comment]
Please submit a pull request, don't forget to include IPv6 functionality if available.
