### ISSUE TITLE
bird6-openwrt: Patch bad line in bird6 init script

### ISSUE THREAD

**Issue by mikma** [openwrt/packages#5249]
-------------------------------

Maintainer: Eloi Carbo <eloicaso@gmail.com>
Environment: (ar71xx, tl-wdr4300, LEDE 17.01.3)

Description:
The init script /etc/bird6/init.d/bird6 is unusable because of a newline and missing hash sign in a comment. This patch fixes the problem:

```
diff --git a/bird-openwrt/bird6-openwrt/src/init.d/bird6 b/bird-openwrt/bird6-openwrt/src/init.d/bird6
index ed99d27..c9e6a86 100755
--- a/bird-openwrt/bird6-openwrt/src/init.d/bird6
+++ b/bird-openwrt/bird6-openwrt/src/init.d/bird6
@@ -42,8 +42,7 @@ writeToConfig() {
 # $1 string. $2 string.
 # This function checks if $2 is empty. If not, it writes the string $1 in the $BIRD_CONFIG file.
 # Use write function to check if $1, value found inside $2, is not empty and can be written in the configuration file.
-# Example: 
-N=""; write "value: $N" $N; 
+# Example:  N=""; write "value: $N" $N
 write() {
     [ -n "$2" ] && writeToConfig "$1"
 }
```

**Comment by eloicaso** [comment]
Hello @mikma,

Sorry for this late reply, bird's main repository is /openwrt-routing and I was not checking this repo.

This issue should not be present anymore in the new version of the package. The new script is available here and is already fixed: https://github.com/openwrt-routing/packages/blob/679f780747dc74a3040d841c3d89116aff7a5f4a/bird-openwrt/bird6-openwrt/src/init.d/bird6-lib.sh#L30

Any other issues, please let me know.
