### ISSUE TITLE
clamav: segfault

### ISSUE THREAD

**Issue by dbrody2004** [openwrt/packages#5260]
Segfault when scanning attached file 1.txt in clamdscan.  It might be related to heap allocation, but not sure.  The error is occuring when processing the CDATA in the 1.txt - about 11000 characters into it.  This does not happen when use clamav on ubuntu 16.04.  There is also a similar segfault in lede for raspberry pi, though I don't have a backtrace for that and can't verify that it is the same issue.
[1.txt](https://github.com/openwrt/packages/files/1546436/1.txt)

------
Thread 3 "clamd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 10290.10292]
0x00007ffff7dda984 in fmt_fp (f=f@entry=0x7ffff7fcba68, y=65535, w=w@entry=0, p=p@entry=-1, fl=fl@entry=0, t=103) at src/stdio/vfprintf.c:180
180	{
(gdb) bt
#0  0x00007ffff7dda984 in fmt_fp (f=f@entry=0x7ffff7fcba68, y=65535, w=w@entry=0, p=p@entry=-1, fl=fl@entry=0, t=103) at src/stdio/vfprintf.c:180
#1  0x00007ffff7ddbd62 in printf_core (f=f@entry=0x7ffff7fcba68, fmt=fmt@entry=0x7ffff7b443ab "%g", ap=ap@entry=0x7ffff7fcb8d0, nl_arg=nl_arg@entry=0x7ffff7fcb910, 
    nl_type=nl_type@entry=0x7ffff7fcb8e8) at src/stdio/vfprintf.c:618
#2  0x00007ffff7ddc0a4 in vfprintf (f=0x7ffff7fcba68, fmt=0x7ffff7b443ab "%g", ap=<optimized out>) at src/stdio/vfprintf.c:680
#3  0x00007ffff7dde18a in vsnprintf (s=<optimized out>, n=<optimized out>, fmt=<optimized out>, ap=<optimized out>) at src/stdio/vsnprintf.c:54
#4  0x00007ffff7dd9f73 in snprintf (s=<optimized out>, n=<optimized out>, fmt=<optimized out>) at src/stdio/snprintf.c:9
#5  0x00007ffff7ab2e06 in cli_js_output ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#6  0x00007ffff7a79074 in js_process ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#7  0x00007ffff7a7a5cf in cli_html_normalise.constprop ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#8  0x00007ffff7a7bc32 in html_normalise_map ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#9  0x00007ffff7a3e5cd in cli_scanhtml ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#10 0x00007ffff7a5a0e8 in magic_scandesc ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#11 0x00007ffff7a5b4e0 in cli_base_scandesc ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#12 0x00007ffff7a5bbcf in scan_common.part ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#13 0x00007ffff7a5bded in cl_scandesc_callback ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#14 0x00007ffff7a5bf72 in cl_scanfile_callback ()
   from /home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/scripts/../staging_dir/target-x86_64_musl/root-x86/usr/lib/libclamav.so.7
#15 0x000000000040d310 in ?? ()
#16 0x0000000000000000 in ?? ()

--------

root@marco:~# clamconf -n
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
LogFile = "/tmp/clamd.log"
TemporaryDirectory = "/tmp"
LocalSocket = "/var/run/clamav/clamd.sock"
ReadTimeout = "30"
ExitOnOOM = "yes"
User = "nobody"
DetectPUA = "yes"
ArchiveBlockEncrypted = "yes"
MaxFileSize = "10485760"

Config file: freshclam.conf
---------------------------
UpdateLogFile = "/tmp/freshclam.log"
DatabaseOwner = "root"
DatabaseMirror = "database.clamav.net"
CompressLocalDatabase = "yes"

clamav-milter.conf not found

Software settings
-----------------
Version: devel-7f35f90
WARNING: Version mismatch: libclamav=devel-7f35f90, clamconf=0.99.2
Optional features supported: AUTOIT_EA06 PCRE2 ICONV RAR 

Database information
--------------------
Database directory: /usr/share/clamav
bytecode.cvd: version 318, sigs: 75, built on Thu Nov  2 20:39:06 2017
main.cvd: version 58, sigs: 4566249, built on Wed Jun  7 21:38:10 2017
daily.cld: version 24106, sigs: 1798558, built on Wed Dec  6 17:12:25 2017
Total number of signatures: 6364882

Platform information
--------------------
uname: linux-gnu   
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a2152520800000000050400

Build information
-----------------
GNU C: 5.4.0 (5.4.0)
CPPFLAGS: -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include/fortify -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include  -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr//include
CFLAGS: -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/build_dir/target-x86_64_musl/clamav-0.99.2:clamav-0.99.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -fno-strict-aliasing 
CXXFLAGS: 
LDFLAGS: -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/usr/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/lib -znow -zrelro 
Configure: '--target=x86_64-openwrt-linux' '--host=x86_64-openwrt-linux' '--build=x86_64-pc-linux-gnu' '--program-prefix=' '--program-suffix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--libexecdir=/usr/lib' '--sysconfdir=/etc' '--datadir=/usr/share' '--localstatedir=/var' '--mandir=/usr/man' '--infodir=/usr/info' '--disable-nls' '--sysconfdir=/etc/clamav/' '--prefix=/usr/' '--exec-prefix=/usr/' '--disable-xml' '--disable-bzip2' '--with-user' 'nobody' '--with-group' 'nogroup' '--with-pcre=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/' '--with-openssl=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/' '--with-zlib=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/' '--disable-zlib-vcheck' '--disable-clamdtop' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-openwrt-linux' 'target_alias=x86_64-openwrt-linux' 'CC=x86_64-openwrt-linux-musl-gcc' 'CFLAGS=-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/build_dir/target-x86_64_musl/clamav-0.99.2:clamav-0.99.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro ' 'LDFLAGS=-L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/usr/lib -L/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/lib -znow -zrelro ' 'LIBS=-lpthread -lfts' 'CPPFLAGS=-I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include/fortify -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include ' 'PKG_CONFIG=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/host/bin/pkg-config' 'PKG_CONFIG_PATH=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/lib/pkgconfig:/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/share/pkgconfig' 'PKG_CONFIG_LIBDIR=/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/lib/pkgconfig:/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/share/pkgconfig'
sizeof(void*) = 8
Engine flevel: 82, dconf: 82

-------

root@marco:~# uname -mrsp
Linux 4.9.54 x86_64 unknown

--------

Build is LEDE 17.01.

**Comment by dibdot** [comment]
feel free to re-open, if this is still an issue.
