### ISSUE TITLE
tor: error message in log requesting upgrade

### ISSUE THREAD

**Issue by badfish** [openwrt/packages#5265]
I'm getting the following message in the system log:

> Dec 11 15:27:59 2017 daemon.warn Tor[10291]: Please upgrade! This version of Tor (0.2.9.2) is not recommended, according to the directory authorities. Recommended versions are: 0.2.5.16,0.2.8.17,0.2.9.14,0.3.0.13,0.3.1.9,0.3.2.6-alpha

**Comment by diizzyy** [comment]
You're using an old package, new version is in the tree

https://github.com/openwrt/packages/tree/master/net/tor
https://github.com/openwrt/packages/tree/lede-17.01/net/tor

You need to compile your own package/firmware and/or backport.

**Comment by neheb** [comment]
This version was never part of OpenWrt. Closing.
