### ISSUE TITLE
Remove me as maintainer

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#5268]
I hereby resign as maintainer for the following packages and therefore wish do be removed as maintainer.
Feel free to leave these in the tree or remove completely

```
admin/netdata
libs/confuse
net/inadyn
net/sipgrep
net/sngrep
net/stunnel
#sound/fdk-aac
utils/pcsc-tools
utils/tio
```

@pprindeville 
Can you handle this request for me?

**Comment by pprindeville** [comment]
@champtar How do we go about handling this?

**Comment by champtar** [comment]
Hi @diizzyy 
Sorry to hear that, if you don't mind, can you explain why (I have ideas but don't want to put words in your mouth) and what we can improve?

@pprindeville I would go in the commit history of each package, see if there was commit from anyone else and offer maintainership, if we can't find anyone for any packages we will move it to package abandoned

**Comment by diizzyy** [comment]
@champtar 
Thanks, I wont go into details but due to events I've decided that it's best to step away. I wish to say thanks to the package maintainers/committers and contributors who've given me help and support along the way. I don't think there's much to improve that could've changed my decision to be honest.

**Comment by pprindeville** [comment]
> I don't think there's much to improve that could've changed my decision to be honest.

There's a _lot_ that could be improved, however it might not be realistic to wait for it...

**Comment by diizzyy** [comment]
Closing this as I've made pull requests to arrange this myself.

**Comment by thagabe** [comment]
@diizzyy I'm sadden to see you leave. Thank you for your work and support you've given me, us, while you were part of the community!
