### ISSUE TITLE
shairport-sync lagging behind

### ISSUE THREAD

**Issue by nos1609** [openwrt/packages#5289]
Maintainer: @thess @mikebrady 

As far as I can see the package is very outdated comparing to the master repo. Awaiting v3.1.5.

Thanks for keeping it alive.

**Comment by thess** [comment]
You are right - It needs updating...

**Comment by mikebrady** [comment]
Thanks for the reminders— I have neglected it, I’m afraid. I’ll do some work on it over the Christmas break.

**Comment by thess** [comment]
@mikebrady - I've got 3.1.6 ready to go. If you want to work on something, the ALAC library would be a nice addition. It kind of fell flat last attempt.

**Comment by mikebrady** [comment]
Thanks Ted. I will have a look alright. It fell flat on licensing grounds, but also someone else seems to have done a better job. I'll investigate.

**Comment by thess** [comment]
Resolved by https://github.com/openwrt/packages/commit/54927ab1dff3b54d10c5f95b33f224c8f604ef8f.
closing this
