### ISSUE TITLE
usbip: typo in last commit

### ISSUE THREAD

**Issue by dibdot** [openwrt/packages#5312]
Maintainer: @nunojpg 
Description:

In my buildroot I receive the following error:

```
sed: can't read /tools/usb/usbip/configure.ac: No such file or directory
Makefile:108: *** Download/usb.ids is missing the URL field..  Stop.
```

In the latest Makefile you've changed:
```
[...]
define Download/usb_ids
[...]
```
but the call still reference to:
```
[...]
$(eval $(call Download,usb.ids))
[...]
```

**Comment by nunojpg** [comment]
I'm sorry. I tested that it compiled and I have the clear idea it did. I'll clean this tomorow. Sorry again and thanks for reporting.
