### ISSUE TITLE
libgcrypt: switch PKG_SOURCE_URL to https

### ISSUE THREAD

**Issue by benhsmith** [openwrt/packages#5313]
Maintainer: @MikePetullo  
Environment: LEDE master (put here arch, model, OpenWRT/LEDE version)

Description:
I can't build the package and that's preventing Travis from building my package.

What's happening is that curl hangs when it gets to downloading the tar file from ftp://ftp.gnupg.org/gcrypt/libgcrypt. It also hangs when I try it with curl manually. 

When I switch the URI to https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/ the problem goes away, curl doesn't hang.

**Comment by diizzyy** [comment]
Fixed https://github.com/openwrt/packages/commit/d6eb6f056582c43585215d7a98d8d6de45ee4030
Please close

@hnyman @champtar
