### ISSUE TITLE
Remove lua and luci-base dependencies in luci-app-sqm

### ISSUE THREAD

**Issue by eterry1388** [openwrt/packages#5320]
This is causing `recursive dependency detected!` error when there are other packages that depend on `lua`.

https://github.com/openwrt/packages/blob/8c69bc44364441157ecf61707bc7ce4c74ea4746/net/sqm-scripts/Makefile#L54

I get this when running `make defconfig`:

```
Collecting package info: done
tmp/.config-package.in:15778:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:15778:	symbol PACKAGE_lua is selected by PACKAGE_luasec
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:16194:	symbol PACKAGE_luasec is selected by PACKAGE_mypackage
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:73743:	symbol PACKAGE_mypackage is selected by PACKAGE_luci-app-mypackage
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:32831:	symbol PACKAGE_luci-app-mypackage depends on PACKAGE_iptables
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:51885:	symbol PACKAGE_iptables is selected by PACKAGE_sqm-scripts
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:948:	symbol PACKAGE_sqm-scripts is selected by PACKAGE_luci-app-sqm
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:33216:	symbol PACKAGE_luci-app-sqm depends on PACKAGE_lua
```

(Note: I replaced the package name I'm developing with `mypackage` above)

**Comment by eterry1388** [comment]
See #3620 for a suggestion to remove these dependencies from this package (scroll down quite a ways to find the comment by @hnyman

**Comment by diizzyy** [comment]
Wrong repo, closing

**Comment by karlp** [comment]
@diizzyy  what do you mean, wrong repo?  THe luci app is provided in the same package makefile, which is in this package.

**Comment by karlp** [comment]
I still feel that this is a bug in your "mypackage" deps though, there's nothign wrong with having other packages depend on lua.

**Comment by diizzyy** [comment]
Terribly sorry, I misread the url

**Comment by tohojo** [comment]
Hmm, don't mind removing the lua dependency. And since we're depending on luci-compat now, that will also pull in luci-base, so I guess we can remove that as well (at least until I figure out how to avoid the -compat dependency).

**Comment by tohojo** [comment]
BTW, thanks @neheb for assigning these bugs to me; I don't follow the repo issues so if I'm not tagged in a report I generally don't see it (as you can probably tell)... :)
