### ISSUE TITLE
i2pd: Improve the package

### ISSUE THREAD

**Issue by LLE8** [openwrt/packages#5326]
Maintainer: @yangfl 
Environment: LEDE 17.01.4

I think, this build can be improved.
Look at https://forum.openwrt.org/viewtopic.php?pid=369287#p369287 please
and above, https://forum.openwrt.org/viewtopic.php?pid=368965#p368965
and https://forum.openwrt.org/viewtopic.php?pid=368966#p368966

Dependence on boost-regex is not needed, i think (~850 KB).
Do not forget add home dir creation in init.
If you wrote `MAKE_FLAGS+=USE_AESNI=no USE_AVX=no` in Makefile, you may delete patch with this options.
Add pidfile creation in init with correct permissions.
May be add tuning of tcp/ip in init (sysctl), i am not sure ,

**Comment by LLE8** [comment]
And add i2pd user creation in Makefile, do not run as root.

**Comment by yangfl** [comment]
@dartraiden Instead, I'm considering explicitly moving working dir into /etc/i2pd, since peer info can take up to 100MB which is quite large compared with typical router memory. So I'd suggest using extroot.

**Comment by LLE8** [comment]
As @orignal said, only netDB and addresses.csv are nessesary. It is less then 10 MB. But it is permanently rewritten. Flash will die.
