### ISSUE TITLE
bird-openwrt - Package should create the TCP_MD5SIG kmod?

### ISSUE THREAD

**Issue by Strykar** [openwrt/packages#5329]
_RFC2385 specifies a method of giving MD5 protection to TCP sessions. Its main (only?) use is to protect BGP sessions between core routers on the Internet_. TCP-MD5 (`CONFIG_TCP_MD5SIG`) is a common method of BGP inter-router authentication. bird appears to have support for this, but openwrt/lede do not create a kernel module available as a binary download via opkg.

Is this the bird package issue or an openwrt one?

**Comment by eloicaso** [comment]
Ping @Noltari.

From my perspective, if this kmod would be required, it should rely on the daemon's dependencies and not on the configuration wrapper ones. I will investigate the issue in more detail once I am back home from holidays with my computer.

**Comment by Strykar** [comment]
Hi @eloicaso Any updates from you or @Noltari?

**Comment by Strykar** [comment]
Wireguard is a better solution now, closing.
