### ISSUE TITLE
PERL: Please add module SASL

### ISSUE THREAD

**Issue by DocMAX** [openwrt/packages#5339]
Could you please add this module?

```
Can't locate Authen/SASL.pm in @INC (you may need to install the Authen::SASL module) (@INC contains: /usr/lib/perl5/5.22 .) at sendxmpp line 20.
BEGIN failed--compilation aborted at sendxmpp line 20.
```

**Comment by pprindeville** [comment]
It's not enough to have `Authen::SASL` -- it's just a framework.  What underlying plug-ins do you. Please see [Authen::SASL Description](http://search.cpan.org/~gbarr/Authen-SASL-2.16/lib/Authen/SASL.pod#DESCRIPTION) need?

**Comment by pprindeville** [comment]
If you can submit a patch to package `Authen::SASL::XS` I'll include it.

**Comment by pprindeville** [comment]
@DocMAX See PR #5612.  If you can test it and verify it works, I can merge it.
