### ISSUE TITLE
MWAN3: Stops NoDogSplash from working

### ISSUE THREAD

**Issue by bluewavenet** [openwrt/packages#5341]
This happens with NDS v1 and v2 and is similar to the very old problem described in:
https://wiki.openwrt.org/doc/howto/mwan3
However is not fixed by changing the NDS marking flags.
Tested on a Ubiquity EdgeRouterX with LEDE 17.01.04 and the latest version of MWAN3 here.

**Comment by feckert** [comment]
@bluewavenet 
On master there was added the possibility to make the mark flags for mwan3 configurable. Have you tested this?

**Comment by bluewavenet** [comment]
@feckert
I've not seen that. Will give it a try.

**Comment by bluewavenet** [comment]
@feckert 
I don't see that anywhere. Any pointers to where? ;-)

**Comment by bluewavenet** [comment]
@feckert 
Ah! Is it MMX_MASK in mwan3.sh?

**Comment by feckert** [comment]
@bluewavenet 
yes this is the right config option.
For now it is set to 0xFF which gives you the possibility to administrate 1-250 interfaces (see openwrt doku 250 is the max because of iproute2)
253 (blackhole)
254 (unreachable)
255 (default)

you could set this to 0xAA this will divide the interface by 16 and you will have now 16 Intefaces to administrate. The omitted marks could be used for example by NDS.

**Comment by bluewavenet** [comment]
@feckert 
mwan3.sh seems to be setting to 0xff00, not 0x00ff, am I reading this correctly?
Lines 20,21:
config_load mwan3
config_get MMX_MASK globals mmx_mask '0xff00'

I won't have suitable hardware for testing for a few days, but will do some testing then.

**Comment by feckert** [comment]
@bluewavenet 
yes this is right it uses 0xff00 if nothing is set
https://github.com/openwrt/packages/blob/master/net/mwan3/files/lib/mwan3/mwan3.sh#L21

**Comment by bluewavenet** [comment]
@feckert 
and not 0xff.
Version 1 used 0xff ?
This might explain the problem with Nodogsplash.
I need to do some testing in the light of this.
Thanks :-)

**Comment by feckert** [comment]
@bluewavenet is this issue solved?

**Comment by bluewavenet** [comment]
@feckert 
I have not had time to look at it so mo progress but I think it is relatively straightforward to fix. I will have to make time asap and revisit ;-)

**Comment by bluewavenet** [comment]
@feckert 
It is now working on 2.6.11-2 (once I got it started ;-) ), by setting higher bits than mwan3 is using eg 0x30000 etc for Nodogsplash. Running VERY well - thanks for all the work put into it!

**Comment by feckert** [comment]
@bluewavenet i think we could close this issue?

**Comment by bluewavenet** [comment]
@feckert - indeed ;-)
