### ISSUE TITLE
dnscrypt-proxy - not working (flock error)

### ISSUE THREAD

**Issue by build000** [openwrt/packages#5347]
@damianorenfer @dibdot 
OpenWrt SNAPSHOT r5671-c5ca1c9 / LuCI Master (git-18.003.32380-b121f95)

logread: 
```
(...)
Wed Jan  3 19:14:53 2018 daemon.notice procd: /etc/init.d/dnscrypt-proxy: /etc/rc.common: /lib/functions/procd.sh: line 512: flock: not found
Wed Jan  3 19:14:53 2018 user.notice root: warning: procd flock for dnscrypt-proxy failed
Wed Jan  3 19:16:16 2018 user.notice root: warning: procd flock for  failed
(...)

**Comment by dibdot** [comment]
`/lib/functions/procd.sh: line 512: flock: not found`
Please make sure, that your busybox binary includes flock support. This has been added a few days ago:

https://git.lede-project.org/?p=openwrt/openwrt.git;a=commit;h=2277cd1249a6952228f36b768beea117c91123a0

**Comment by build000** [comment]
@dibdot 
Actually, I had to overlook it because I had to manually modify this file, in which I added some functions. After adding the "flock" function, everything works without this error.
Problem solved - I am closing the issue.

**Comment by daniel-santos** [comment]
hrmm. Shouldn't this be auto-selected by whatever triggers its use?
