### ISSUE TITLE
imagemagick - missing files

### ISSUE THREAD

**Issue by eliz82** [openwrt/packages#5349]
Maintainer: no idea, i did not find the package in github repo https://github.com/openwrt/packages/tree/master/multimedia ???
Environment: Entware, Voxel Firmware, Netgear R7800

Description:
`opkg install imagemagick imagemagick-jpeg imagemagick-png imagemagick-tiff imagemagick-tools
magick convert /opt/original.png /opt/convert.jpg
`
give me an error of not finding a magic.xml file 

> convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.

`magick convert -debug configure /opt/original.png /opt/convert.jpg`
will give you more information about what file is magick binary trying to access. seems /root/.config/ImageMagick/magic.xml and other files are missing

https://github.com/ImageMagick/ImageMagick/issues/232

**Comment by mhei** [comment]
Same as #5350, imagemagick is not (yet) part of this repo, so this issue is invalid.
