### ISSUE TITLE
dnsmasq: multiple instances setup not parsed correctly

### ISSUE THREAD

**Issue by dosenflieger** [openwrt/packages#5354]
LEDE: 17.01.4 (lantiq/xway)
dnsmasq: 2.78-1

Trying to configure multiple instances of dnsmaq in /etc/config/dhcp according to https://lede-project.org/docs/user-guide/dhcp_configuration fails probably due to a parsing error. Only the first dnsmasq instance is parsed correctly. Further definitions are interpreted as dhcp instances.

Adding a 'set -x' to /etc/init.d/dnsmaq shows that the following setup 

```
config dnsmasq 'main'
   option domainneeded '1'
   ...

config dnsmasq 'tor'
   option domainneeded '1'
   ...
```

is parsed as:

```
config dnsmasq 'main'
   option domainneeded '1'
   ...

config dhcp 'tor'
   option domainneeded '1'
   ...
```

Thanks for taking a look!

**Comment by hnyman** [comment]
sorry, but dnsmasq is part of the core packages and should be discussed in  https://bugs.openwrt.org/
