### ISSUE TITLE
unbound: domain_insecure setup via uci is broken

### ISSUE THREAD

**Issue by silentcreek** [openwrt/packages#5368]
Maintainer: @EricLuehrsen 
Environment: LEDE 17.01.4, x86

I added a few domains to _domain_insecure_ list in the unbound configuration via uci, but then I noticed that they don't end up in the autogenerated configuration. I looked at the source code of _unbound.sh_ and I think I found the culprit there:

Basically, the function _unbound_conf_ sets the variable _cfg_ to the first positional parameter, see [1]. But _unbound_conf_ isn't called with any argument (see [2]), so it'll always be empty. The variable _cfg_ is required, however, when the _domain_insecure_ list is processed (see [3]), otherwise _config_list_foreach_ won't return anything.

Hence, I think the code should be fixed in a way that _unbound_conf_ will be invoked with the corresponding uci config section variable. The code is the same for master and 17.01 in this regard, so I assume both need to be fixed.

[1] https://github.com/openwrt/packages/blob/master/net/unbound/files/unbound.sh#L571
[2] https://github.com/openwrt/packages/blob/master/net/unbound/files/unbound.sh#L1162
[3] https://github.com/openwrt/packages/blob/master/net/unbound/files/unbound.sh#L866

**Comment by EricLuehrsen** [comment]
Solved in #5374 for trunk. Not a security bug, no other reported user complaints (12 months), and possible work around in `unbound_srv.conf`, so likely does not meet the bar for back port in 17.1.4. If acceptable, then please close ticket.

**Comment by silentcreek** [comment]
Thanks for the quick response and fix. Personally, I don't need a backport as I already worked around it by editing unbound_srv.conf, as you suggest, too. However, in this case, I would recommend updating the documentation/readme to reflect that domain_insecure via uci is not supported on LEDE 17.01.
