### ISSUE TITLE
utils/bonnie++  Package does not run, exits with "Large File Support not present" error

### ISSUE THREAD

**Issue by Strykar** [openwrt/packages#5422]
Maintainer: @ffainelli 
Environment: OpenWrt SNAPSHOT r5638-0f72690a2d / LuCI Master (git-18.003.80735-dac0cce)

Description: Bonnie++ does not run and instead exits with "`Large File Support not present, can't do 8192M.`"
```
root@apu:/# bonnie\+\+ -d /tmp
Large File Support not present, can't do 8192M.
usage:
bonnie++ [-d scratch-dir] [-c concurrency] [-s size(MiB)[:chunk-size(b)]]
      [-n number-to-stat[:max-size[:min-size][:num-directories[:chunk-size]]]]
      [-m machine-name] [-r ram-size-in-MiB]
      [-x number-of-tests] [-u uid-to-use:gid-to-use] [-g gid-to-use]
      [-q] [-f] [-b] [-p processes | -y] [-z seed | -Z random-file]
      [-D]

Version: 1.97
```
The Bonnie++ Makefile does not have any options set and this doesn't appear to be a Makefile config setting.
This could be due to missing _LARGEFILE64_SOURCE support, see https://github.com/Homebrew/homebrew-core/issues/17822 and https://github.com/Homebrew/homebrew-core/pull/17824

**Comment by diizzyy** [comment]
@Strykar 
https://github.com/openwrt/packages/pull/6538

You might want to consider using fio which is in the tree and works just fine :-)
