### ISSUE TITLE
Travis currently broken

### ISSUE THREAD

**Issue by champtar** [openwrt/packages#5448]
Hey all,

Travis check seems to be currently broken (I'm parsing make check output and it changed)
I'll try to fix that this week if nobody fix it before

In the mean time please ignore Travis

**Comment by pprindeville** [comment]
@champtar Thanks for looking into that!

**Comment by champtar** [comment]
Fixed by https://github.com/openwrt/packages/commit/64aa144662112d8095e0a9efb0e48a6ef343ea49
