### ISSUE TITLE
radicale: upgrade to 2.x

### ISSUE THREAD

**Issue by DragoonAethis** [openwrt/packages#5467]
Maintainer: @chris5560 
Environment: LEDE 17.01.4

Radicale 2.x (currently at 2.1.8) was released a few months ago. Now that it had some time to mature, it'd be a solid idea to upgrade the package in this repo. The 2.x branch now requires Python 3.x (dropping 2.x completely), but consumes a bit less memory than 1.x and (*finally*) properly synchronizes calendars which use a bit more obscure iCal features (date-based filters in recurring events, per-event colors, etc).

2.x isn't backwards compatible with 1.x data - storage needs to be migrated first, [as described on this page](http://radicale.org/1to2/). This can be automated, but then Radicale still needs to be reconfigured. It'd be preferred to leave 1.x up and running in LEDE/OpenWrt 17.01.x and upgrade to 2.x in the next release.

**Comment by chris5560** [comment]
Hi Dragoon,

please feel free to build a 2.x package and take over "Maintainer" for it.
I'm currently short on time to build and test a 2.x package.
I think we should have two packages for a while 1.x and 2.x, so user can decide when to change/upgrade independent from OpenWrt release.
I offer my support to (re)write a corresponding Luci application.

Christian

**Comment by DragoonAethis** [comment]
I never did any packages for OpenWrt previously, but I'll try to package it in about 2 weeks.

**Comment by jefferyto** [comment]
@DragoonAethis you may be interested in #7871.

**Comment by DragoonAethis** [comment]
Awesome, thank you! I'll try to test it soon :)
