### ISSUE TITLE
[Samba36] template is missing important entries

### ISSUE THREAD

**Issue by LipkeGu** [openwrt/packages#5469]
since the template gots updated along time ago and now some important entries are missing like:
* ```doamin master = yes```
* ```prefered master = yes```
* ```os level = 255```
* ```browseable = yes```
the last negates the guest option when it is missing. in this case noone can access samba shares

**Comment by neheb** [comment]
The last in configurable through LuCI on a per share basis. My understanding is that the global setting overrides share settings.

Based on my reading of the smb.conf man page, domain logons should be set to yes, not domain master.

I'm not sure about the os level setting. What value is set by Windows?

smb.conf warns against prefered master for a similar reason that local master was set to no.

**Comment by LipkeGu** [comment]
**domain master (G)**

_Tell smbd(8) to enable WAN-wide browse list collation. Setting this option causes nmbd to claim a special domain specific NetBIOS name that identifies it as a domain master browser for its given workgroup._ Local master browsers in the same workgroup on broadcast-isolated subnets will give this nmbd their local browse lists, and then ask smbd(8) for a complete copy of the browse list for the whole wide area network. Browser clients will then contact their local master browser, and will receive the domain-wide browse list, instead of just the list for their broadcast-isolated subnet. 

**local master (G)**

_This option allows nmbd(8) to try and become a local master browser on a subnet. If set to no then nmbd will not attempt to become a local master browser on a subnet and will also lose in all browsing elections._ By default this value is set to yes. Setting this value to yes doesn't mean that Samba will become the local master browser on a subnet, just that nmbd will participate in elections for local master browser.

**Preferred master (G)**

This boolean parameter controls if nmbd(8) is a preferred master browser for its workgroup.

_If this is set to yes, on startup, nmbd will force an election, and it will have a slight advantage in winning the election._ It is recommended that this parameter is used in conjunction with domain master = yes, so that nmbd can guarantee becoming a domain master.

Use this option with caution, because if there are several hosts (whether Samba servers, Windows 95 or NT) that are preferred master browsers on the same subnet, they will each periodically and continuously attempt to become the local master browser. This will result in unnecessary broadcast traffic and reduced browsing capabilities.

**os level (G)**

This integer value controls what level Samba advertises itself as for browse elections. The value of this parameter determines whether nmbd(8) has a chance of becoming a local master browser for the workgroup in the local broadcast area.

Note: By default, Samba will win a local master browsing election over all Microsoft operating systems except a Windows NT 4.0/2000 Domain Controller. This means that a misconfigured Samba host can effectively isolate a subnet for browsing purposes. This parameter is largely auto-configured in the Samba-3 release series and it is seldom necessary to manually override the default setting. Please refer to the chapter on Network Browsing in the Samba-3 HOWTO document for further information regarding the use of this parameter. Note: The maximum value for this parameter is 255.

**Comment by neheb** [comment]
this should not be an issue anymore. luci-app-samba handles the configuration.
