### ISSUE TITLE
libiio has a dependency on libavahi-common, which does not exist

### ISSUE THREAD

**Issue by hnyman** [openwrt/packages#5480]
Maintainer: @mhei 

build config shows now an error for libiio:

> WARNING: Makefile 'package/feeds/packages/libiio/Makefile' has a dependency on 'libavahi-common', which does not exist

https://github.com/openwrt/packages/blob/b9e0b2680cf9c3e7021ecb647ee0287ccb1dd331/libs/libiio/Makefile#L37

    +PACKAGE_libavahi-common:libavahi-common

The dependency has been there since
https://github.com/openwrt/packages/commit/c947329c6452ce21650df3a942a517be5798f525

Not sure if that has been wrong all the time, or if there has been a change in libavahi since then.

**Comment by mhei** [comment]
Thanks for reporting.
