### ISSUE TITLE
haproxy: upgrade to 1.8.3/1.7.10

### ISSUE THREAD

**Issue by easyteacher** [openwrt/packages#5485]
Maintainer: @heil 
Environment: OpenWRT Trunk/LEDE 17.01

Description:
HAProxy 1.8 brings many new features and improvements like HTTP/2 Protocol Support, Multithreading, Hitless Reloads, etc.
HAProxy 1.8 requires libatomic.
HAProxy 1.7.10 has merged the patch in the patch folder, and fixed many other bugs.

Current Makefile use _USE_REGPARM=1_, which should be x86-specificed parameter, or there will be many compiler warnings. _USE_TFO=1_ should be added for saving up to one full round-trip time.

**Comment by gladiac1337** [comment]
Something to look forward to: https://github.com/openwrt/packages/pull/5710

**Comment by easyteacher** [comment]
@gladiac1337 Great, thanks!

**Comment by diizzyy** [comment]
Superseded by https://github.com/openwrt/packages/commit/153b14cbfb32a7f959b1dffd5c481640413e957c
@hnyman @champtar 
Please close
