### ISSUE TITLE
extending OpenWrt packages maintainers by a new member

### ISSUE THREAD

**Issue by lperkov** [openwrt/packages#5486]
Dear all,

I would like to propose granting Marko Ratkaj (ratkaj on GitHub) commit access.

Over the last few years that I know him personally, Marko has done a lot of great work. He maintains a dozen of packages and is actively porting new ones to OpenWrt. He is very knowledgeable about
OpenWrt/LEDE in general and he actively pushes new packages and fixes issues in existing ones within the packages feed.

That being said, he has my vote to gain access to the above mentioned feed.

Thanks,
Luka

@karlp @tripolar @pprindeville @Noltari @jmccrohan @tohojo @NeoRaider @rmilecki @nmeyerhans @kerneis @zioproto @luizluca @acinonyx @stintel @mhei @nmav @heil @nunojpg @thess @champtar @yousong @jslachta @hnyman @Naoir @dangowrt @ratkaj

**Comment by hnyman** [comment]
Why not :-)

**Comment by thess** [comment]
ACK from me.

/ted

From: Luka Perkov
Sent: Monday, January 22, 2018 9:22 AM
To: openwrt/packages
Cc: Ted Hess ; Mention
Subject: [openwrt/packages] extending OpenWrt packages maintainers by a new member (#5486)


Dear all,

I would like to propose granting Marko Ratkaj (ratkaj on GitHub) commit access.

Over the last few years that I know him personally, Marko has done a lot of great work. He maintains a dozen of packages and is 
actively porting new ones to OpenWrt. He is very knowledgeable about
OpenWrt/LEDE in general and he actively pushes new packages and fixes issues in existing ones within the packages feed.

That being said, he has my vote to gain access to the above mentioned feed.

Thanks,
Luka

@karlp @tripolar @pprindeville @Noltari @jmccrohan @tohojo @NeoRaider @rmilecki @nmeyerhans @kerneis @zioproto @luizluca @acinonyx 
@stintel @mhei @nmav @heil @nunojpg @thess @champtar @yousong @jslachta @hnyman @Naoir @dangowrt @ratkaj

**Comment by thess** [comment]
ACK for Dirk also.

/ted

**Comment by pprindeville** [comment]
No objection to either.

**Comment by champtar** [comment]
Fine with me, the more the merrier!

**Comment by nmav** [comment]
Fine with me too. Welcome!

**Comment by jslachta** [comment]
Full ACK.

**Comment by stintel** [comment]
ACK for both

**Comment by zioproto** [comment]
Hello,

I dont know the new guys but for me it is always good to be inclusive and
welcome new people that to work for OpenWrt.
Welcome in ! ACK from me.

2018-01-23 9:46 GMT+01:00 Toke Høiland-Jørgensen <notifications@github.com>:

**Comment by thess** [comment]
Invites sent to both Marko and Dirk. Closing this for now.
Nice to have to new folks here...

**Comment by ratkaj** [comment]
Thank you everyone for your support!

**Comment by dibdot** [comment]
Many thanks for your confidence and your long lasting support. I am looking forward to working with  you ...

Best regards
Dirk
