### ISSUE TITLE
fwknop: OPEN_PORTS is ignored when a client puts open ports in the SPA

### ISSUE THREAD

**Issue by waitfor1t** [openwrt/packages#5498]
Maintainer: @jp-bennett 
Environment: all/all

Description:
fwknop: OPEN_PORTS is ignored when a client adds open ports in the SPA. This is a security risk; it allows any client to open any port. The OPEN_PORTS variable, if specified, should ignore whatever the client sends.

**Comment by jp-bennett** [comment]
On the latest LEDE release, I can't replicate this problem.  Can you sanitize and share the log file where this happened, and also check whether /tmp/etc/access.conf does indeed include the OPEN_PORTS line correctly?

**Comment by waitfor1t** [comment]
/tmp/etc/access.conf does have the OPEN_PORTS line. I've tried with spaces and without (opening multiple ports). Now I'll try a few combinations (1 port, 2 without space, etc) to see if that changes anything.

**Comment by jp-bennett** [comment]
@waitfor1t You might find the problem disappears with the latest release, but keep me updated.  If it's still an issue I want to get it fixed.

**Comment by waitfor1t** [comment]
so I'm now running the latest LEDE build and can see that the server (fwknopd 2.6.9-3) does reject any SPA from the client that doesn't match the server, so it seems resolved. closing the issue.
