### ISSUE TITLE
zsh: Failed to compile

### ISSUE THREAD

**Issue by cburlacu** [openwrt/packages#5514]
Maintainer: @msva
Environment: (mvebu, WRT3200ACM, lede-project/source@d58c8f4029fa2c214454d7a5229e4964cbbc8fe1)

Description:
I'm not able to compile zsh package (libcap is missing).
Last successful build was on 10th January 2018. I don't  know what the root cause is.
Message error:
```
Package zsh is missing dependencies for the following libraries:
libcap.so.2
```
So, as a workaround, I was able to compile it either by removing --enable-cap or by adding +libcap to dependencies.

**Comment by dibdot** [comment]
Fix applied!
