### ISSUE TITLE
empty adblock.blacklist

### ISSUE THREAD

**Issue by EngUnlimited** [openwrt/packages#5539]
Hello,

Everything works except the adbloclk.blacklist is empty, so none ads was blocked.  
adblock | 3.4.3-1
luci-app-adblock | git-18.029.54963-e6781c1-1
installed on OpenWrt Chaos Calmer 15.05 / LuCI Master (git-15.233.47308-791ca8b) 
Kernel Version	3.18.20
Memory 15% free/ 4% buffered
Thanks.

**Comment by dibdot** [comment]
obsolete
