### ISSUE TITLE
php7:Regexp issue introduced in newer commits

### ISSUE THREAD

**Issue by barhom** [openwrt/packages#5544]
The following PHP code gives different results on different versions of openwrt

```php
<?php
$value = '@if(true) bazinga! @endif';

$result = preg_replace_callback(
'/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', function ($match) {
    return '[MATCHED]';
}, $value);

var_dump($result);
```
Latest openwrt trunk:

```php
# php test.php
string(25) "@if(true) bazinga! @endif"
```
Local PHP7.2.1:
```php
➜  ~ php test.php
string(28) "[MATCHED] bazinga! [MATCHED]"
```
3v4l.org online php https://3v4l.org/rWDPs:
```php
string(28) "[MATCHED] bazinga! [MATCHED]"
```
What changed in newer commits of openwrt/openwrt or openwrt/packages that made PHP regexp produce different results from earlier?
I believe the problem in the regex is in the 
```php
'\B'
```
of
```php
'/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x'
```
Any takers on what might have caused the issue?

**Comment by mhei** [comment]
The output of phpinfo() of both installations could give a hint about used library versions.

**Comment by barhom** [comment]
> The output of phpinfo() of both installations could give a hint about used library versions.
I dont necessarily think there is something wrong with the php7 package. Might be something else that changed in openwrt build system.

For example, 
`PCRE Library Version => 8.41 2017-07-05 `
was the same on both the good and bad build.

Here's the output of phpinfo() for the latest trunk:
https://gist.github.com/barhom/74e911016521e7ead88751ea890d58c4

**Comment by mhei** [comment]
I guess you have already compared the both outputs which I requested and your did not find any remarkable differences?

PHP comes with a bundled pcre library and it seems that we use the bundled version but define a package dependency to the external library package and thus also install the external library. I'll have a detailed look next weekend and check whether we can/should fix this - I would prefer to use the external package.

However, I still have no glue what could cause your problem... do you have an idea when the "bad" build was created? On Dec 29 2017 we added a patch for MIPS which affects MIPS platforms...

**Comment by barhom** [comment]
@mhei 
I did compare both phpinfo()s and couldn't find anything useful to compare other than the pcre library.
I'll see if I can bissect and find the culprit commit. You think it only affects MIPS?

Did you try running the following?
```php
<?php
$value = '@if(true) bazinga! @endif';

$result = preg_replace_callback(
'/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', function ($match) {
    return '[MATCHED]';
}, $value);

var_dump($result);
```

What was your output?

**Comment by mhei** [comment]
I run your test script in a VM with recent LEDE built for i386:
`string(28) "[MATCHED] bazinga! [MATCHED]"`
Same output on my local desktop system, running a self-compile PHP version 7.1.5 - just as another reference.

**Comment by barhom** [comment]
Still giving me the same issue in latest trunk of openwrt/openwrt and openwrt/packages

**Comment by barhom** [comment]
@mhei Can you link the commit that you *think* might have caused it?

**Comment by barhom** [comment]
This has been tested on ipq806x which does not show the issue.
And has been verified by another openwrt user that the issue is showing up on mt7621 SoC.

**Comment by pprindeville** [comment]
What happens on an x86 or x86_64 build on KVM or Qemu?

**Comment by barhom** [comment]
> What happens on an x86 or x86_64 build on KVM or Qemu?
as @mhei already mentioned on his VM it correctly runs the code. It seem issue is only affecting RAMIPS.

**Comment by pprindeville** [comment]
Could this be related to commit #97efa62?

**Comment by barhom** [comment]
@pprindeville 
I'll give it a while and revert that patch to see.

**Comment by pprindeville** [comment]
> I'll give it a while and revert that patch to see.

I don't think it builds without that patch.

**Comment by mhei** [comment]
I've committed a change to switch from the bundled libpcre to the external library.
Can you test whether also affects this issue?

**Comment by barhom** [comment]
Commit 9ace92d fixes this issue.

**Comment by barhom** [comment]
Commit 9ace92d fixes this issue.

**Comment by mhei** [comment]
Ok, thanks for the feedback. Now we know, how to prevent this issue, but we still don't know the real problem - only that it is related to the bundled version of libpcre...
