### ISSUE TITLE
libssh2: no crypto backend choice

### ISSUE THREAD

**Issue by vampik** [openwrt/packages#5550]
Maintainer: @micmac1 
Environment: x86_64, OpenWRT trunk

Description:

I use a custom OpenWRT trunk build with openssl. Unfortunately, one of the recent commits changed the crypto backend for libssh2 from openssl to mbedtls. Now libssh2 pulls in libmbedtls which is unneeded since I already have openssl.

Could you please make an option to choose libssh2 crypto backend as it is done in all other packages?

**Comment by micmac1** [comment]
Hi Andrey,

I'll send a PR to Jiri this weekend.

Regards,
Seb

**Comment by micmac1** [comment]
Please close this issue when you get around to it.
