### ISSUE TITLE
gnupg,libgcrypt,libgpg-error add alternative PKG_SOURCE_URL

### ISSUE THREAD

**Issue by muhahacz** [openwrt/packages#5571]
Add alternative PKG_SOURCE_URL for gnupg, libgcrypt, libgpg-error, please.
Seems that ftp service ( ftp://ftp.gnupg.org ) sometimes fails.

Alternatives:
https://gnupg.org/ftp/gcrypt/gnupg/ 
https://gnupg.org/ftp/gcrypt/libgcrypt/ 
https://gnupg.org/ftp/gcrypt/libgpg-error

**Comment by dibdot** [comment]
Feel free to submit an appropriate Pull Request and please always CC: the current package maintainer.
@cshoredaniel
