### ISSUE TITLE
libvorbis

### ISSUE THREAD

**Issue by mendel129** [openwrt/packages#5576]
Maintainer: @thess 
Environment: 17.1.04

Description: end 2017, some critical security vulnerabilities were identified in the libvorbis package, and fixed in the meantime (via https://gitlab.xiph.org/xiph/vorbis/issues/2328 and https://gitlab.xiph.org/xiph/vorbis/issues/2329).
However, the libvorbis project didn't release 1.3.6 yet.

Please include the patch as described on https://github.com/xiph/vorbis/pull/34 as an additional patch to the openwrt package.

**Comment by thess** [comment]
Thanks for the heads-up -- will check on it.

**Comment by thess** [comment]
Closed via 287cb87
