### ISSUE TITLE
Wireguard: peer address have to be set

### ISSUE THREAD

**Issue by reindeer** [openwrt/packages#5587]
Wireguard is a point-to-point protocol. But currently netifd script creates a tunnel with ip/mask parameters only.
This causes some problems for OSPF — router cannot find any neighbor

**Comment by champtar** [comment]
Hi @reindeer 
what daemon are you using for OSPF (bird/quagga)? (you might fix your problem by tunning your conf / use multicast?)
Wireguard and netifd are part off OpenWrt core, and routing daemon will be in https://github.com/openwrt-routing/packages, so this bug tracker is not the right one
