### ISSUE TITLE
boost fail to compile with glibc 2.6

### ISSUE THREAD

**Issue by atyg02** [openwrt/packages#5588]
Maintainers: @diizzyy, @plntyk 
Environment: x86_64, OpenWRT/LEDE trunk

according to this #5573, glibc 2.26 has introduced a regression and needs to be patched.
do you have any idea how to solve the issue?
Thank you !

**Comment by diizzyy** [comment]
@atyg02 
glibc has been bumped several times after this report, is it still an issue?

**Comment by ClaymorePT** [comment]
@diizzyy You can close this issue. Thank you.

**Comment by diizzyy** [comment]
@hnyman 
Close this please
