### ISSUE TITLE
kmod-usb-ledtrig-usbport_4.4.92-1_mips_24kc.ipk - LED does not blink when device accessed

### ISSUE THREAD

**Issue by dr431** [openwrt/packages#5596]
# Issue template (remove lines from top till here)

Maintainer: None listed.
Environment: LEDE-17.01.4

Description: USB LED light is on, but does not blink when the device is accessed. This functionality was present in ChaosCalmer 15.05.01. There used to be a trigger  usbdev that provided this functionality in older versions of Openwrt, but doesn't appear to be available in LEDE.

**Comment by dibdot** [comment]
kernel drivers are not part of the package repo. If this issue still exist for you, please open a ticket here:
https://bugs.openwrt.org/
