### ISSUE TITLE
ubox: logd memory leak

### ISSUE THREAD

**Issue by HenryGiraldo** [openwrt/packages#5604]
I checked the use of memory with `top` command and saw that the logd was consuming memory disproportionately (around 60MB).

```
PID PPID USER STAT VSZ VSZ %CPU COMMAND
971 1 root S 59768 48% 0% /sbin/logd -S 64
```

- There was no remote log configured.
- I was using logread -f for a long time.
- When doing an /etc/init.d/log restart the consumed memory returned to normality.
- ubox version:
```
PKG_SOURCE_DATE:=2017-09-01
PKG_SOURCE_VERSION:=b1bc8d5fb874cdd22701a08d0fb0de4330f86814
PKG_MIRROR_HASH:=b07e750d941d691e2745aa3a058e504966b15d1db5636162dc686bad275eb296
```

**Comment by dibdot** [comment]
logread / logd is not part of the package repo. If this issue still exist for you, please open a ticket here:
https://bugs.openwrt.org/
