### ISSUE TITLE
libiio: missing dependencies

### ISSUE THREAD

**Issue by stintel** [openwrt/packages#5637]
Maintainer: @mhei 
Environment: OpenWrt master r6192-8651f1149d

Description:

```
Package libiio is missing dependencies for the following libraries:
libavahi-client.so.3
libavahi-common.so.3
```

**Comment by mhei** [comment]
@stintel could you provide more details, e.g. which platform and which git commit of packages etc.?
I thought this issue was already fixed and can not reproduce it here.

**Comment by stintel** [comment]
brcm2708/bcm2708, packages @ 055be639b385029a7540ec22cc926392c7ca1dde

**Comment by mhei** [comment]
I can reproduce this issue only, when I first select libavahi-client package, then manually deselect it and rebuild libiio. Then the avahi library and headers are still present in the staging directories and libiio find/use it which triggers the missing deps errors...
I wonder whether I should make the deps unconditionally (which always increases the footprint), or add a config item for this...

**Comment by stintel** [comment]
I've looked at the code and iirc there is no cmake option to disable the libavahi dependency. I think it would be best to add such an option, and disable it when libavahi-* is not enabled. I might do it myself, but didn't find the time yet.
