### ISSUE TITLE
wshaper: rename downlink and uplink in order not to confuse

### ISSUE THREAD

**Issue by giner** [openwrt/packages#564]
Hello,

What about renaming in order not to confuse?
downlink -> bw_in or bw_incoming
uplink -> bw_out or bw_outgoing

Best regards,
Stanislav

**Comment by nmav** [comment]
What is confusing about downlink and uplink?

**Comment by jow-** [comment]
I do not see the problem either, also I'm very reluctant to break existing configurations for no good reason.
