### ISSUE TITLE
Shadowsocks-libev:Shows not running anyway.

### ISSUE THREAD

**Issue by MisterLin1995** [openwrt/packages#5649]
Maintainer: @yousong
Environment: (put here arch, model, OpenWrt version)
<img width="1053" alt="2018-02-21 10 58 28" src="https://user-images.githubusercontent.com/16671583/36461142-fe572894-16f6-11e8-9d6a-6bb60f323164.png">

<img width="404" alt="2018-02-21 10 58 13" src="https://user-images.githubusercontent.com/16671583/36461208-411386fa-16f7-11e8-9e64-ad641bba8f3a.png">

Description:
The  shadowsocks-libev installed on my openwrt router is not running.
<img width="1124" alt="2018-02-21 10 56 27" src="https://user-images.githubusercontent.com/16671583/36461174-23e58808-16f7-11e8-84b2-c4d46374d66e.png">

**Comment by dibdot** [comment]
@yousong

**Comment by yousong** [comment]
@MisterLin1995 , have you tried enabling both the ss_redir and ss_server section?  From the screenshot you gave, you need to click button Enable or 启用

**Comment by MisterLin1995** [comment]
I tried to start ss-redir in command line and 
the shadowsocks-libev-3.1.3 will encounter： error loading shared library libmbedcrypto.so.0.
Finally I solved this problem by uninstalling
 all other packages
 and only using shadowsocks-libev-ss-redir-3.1.3-2.

**Comment by MisterLin1995** [comment]
@yousong And the button in screenshot means it is already enabled，pressing it only cause the pid to get killed.

**Comment by yousong** [comment]
Guess I will need remote access to see the exact cause like previously done with another issue (https://github.com/openwrt/packages/issues/4614#issuecomment-317261405).  Can you contact me by email and setup the session ready?

**Comment by MisterLin1995** [comment]
I cannot access my router now since I'm not going back in 4 months. You can email me so that I will be able to send you logs or other materials to locate the key of the problems.

**Comment by MisterLin1995** [comment]
I guess the key problem lies in my router firmware because it's a Snapshot version or there's something wrong with  shadowsocks-libev-3.1.3  since shadowsocks-libev-ss-redir-3.1.3-2 worked.

**Comment by yousong** [comment]
@MisterLin1995 , Please post the content of `/etc/config/shadowsocks-libev` with server hostname and password stripped off.  Please also share where the firmware was got and how you customised it as the libmbedcrypt.so error should not happen with vanilla OpenWrt build.

**Comment by MisterLin1995** [comment]
I have no access to that router now since I didn't open the remote access.
I bought the router on taobao.com and the firmware is built in so I have no source firmware. 
I only uninstalled all pre-installed packages installed by the seller. And then I followed the instruction of https://cokebar.info/archives/664 . 
The arch of the router cpu should be  mips 24Kc if I remember it correctly.
And the router model is wndr4300 V2, not wndr4500 V3  as shown in the scrennshot.
I can provide the purchase link if you email me so I can reply that to you privately.

**Comment by yousong** [comment]
Well, now I am in a "works for me" situation.  Please keep in mind that current packaging of shadowsocks-libev in this repo is a complete rewrite.  The link you posted above is very likely obsolete in some aspects.  You can find my email address at [1] when you are ready

[1] https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile#L23

**Comment by MisterLin1995** [comment]
Got it,thank you very much!
