### ISSUE TITLE
wshaper: settings are not applied on boot

### ISSUE THREAD

**Issue by giner** [openwrt/packages#565]
Hello,

I have configured guest network and enabled wshaper for this. However bw settings are not applied on boot for unknown reason and "tc qdisc" reports so as if nothing were configured.

When I do /etc/init.d/wshaper start then settings are applied.

Best regards,
Stanislav

**Comment by miltador** [comment]
I can confirm this bug. Still exists on latest trunk build.

**Comment by champtar** [comment]
@giner can you send a PR?

**Comment by giner** [comment]
What is PR?

**Comment by champtar** [comment]
A pull request
https://help.github.com/articles/using-pull-requests/

**Comment by giner** [comment]
Here it goes #1026

**Comment by giner** [comment]
Update: #1030
