### ISSUE TITLE
cloud flare ddns v4 subdomain support

### ISSUE THREAD

**Issue by gxgani** [openwrt/packages#5652]
ddns-scripts_cloudflare.com-v4

Maintainer: @chris5560 
Environment: WRT3200ACM

Description:
Would it be possible to implement subdomain support for cloudflare dns? I am unable to figure out the api call.

**Comment by gxgani** [comment]
found it via #5097.

**Comment by disrupted** [comment]
did you get it to work for multiple subdomains? for me currently it only updates the A record for mydomain.tld, not subdomain1.mydomain.tld, subdomain2.mydomain.tld and so on

**Comment by gxgani** [comment]
> 
> 
> did you get it to work for multiple subdomains? for me currently it only updates the A record for mydomain.tld, not subdomain1.mydomain.tld, subdomain2.mydomain.tld and so on

Yea, make sure you have ddns-scripts and ddns-scripts-cloudflarev4 is installed. This is how my config looks

![https://i.imgur.com/PbhRzPg.png](https://i.imgur.com/PbhRzPg.png)

**Comment by disrupted** [comment]
Mine looks very similar to yours but only works for the main domain for now. what did you enter for `subdomain` if you want it to update for all of your subdomains? the wildcard `*`?
also can I ask which version of OpenWRT are you running? just noticed your LuCI looks so different to mine.
