### ISSUE TITLE
adblock: How to exclude subnet/IP/VLAN

### ISSUE THREAD

**Issue by 2devnull** [openwrt/packages#5662]
Hi,
Is there a way to exclude ads from being blocked on a particular vlan, ip or subnet while continue to block on others?

**Comment by dibdot** [comment]
With dnsmasq you can configure multiple dns instances, one with enabled adblock, the other without adblock (check the serversfile directive in dnsmasq). In future please use the support forum (https://forum.lede-project.org) for these kind of questions - thanks.
