### ISSUE TITLE
dnsmasq: Fixed DHCP address fails if host responds to IP

### ISSUE THREAD

**Issue by mueslo** [openwrt/packages#5673]
Maintainer: ?
Environment: LEDE Reboot 17.01.2 r3435-65eec8bd5f 

Description:
The issue is with patch `010-Tweak-ICMP-ping-check-logic-for-DHCPv4.patch`, in particular this clause:
```
else if ((!lease || lease->addr.s_addr != config->addr.s_addr) && !do_icmp_ping(now, config->addr, 0, loopback))
  my_syslog(MS_DHCP | LOG_WARNING, _("not using configured address %s because it is in use by another host"), addrs);
```

Some hosts will continue to listen on IPs they don't actually have a lease for. If the listener is identical to the host in the configuration, then the IP is not in use by *another* host and the lease should be assigned.

**Comment by dibdot** [comment]
dnsmasq is not part of the package repo. If this issue still exist for you, please open a ticket here: https://bugs.openwrt.org/
