### ISSUE TITLE
tp-link 740 / 741 flash

### ISSUE THREAD

**Issue by sanitariu** [openwrt/packages#5685]
I flashed tp-link 740 version 4 (non removable antenna) with openwrt-ar71xx-tiny-tl-wr740n-v4-squashfs-factory.bin.
So fine everything went well but after flashing we see on web version:
TP-LINK TL-WR741ND v4 ! It should be TP-Link TL-WR740N/ND v4.
This was working before correct. Someone broke something.
Now it is impossible to flash from web again with openwrt-ar71xx-tiny-tl-wr740n-v4-squashfs-factory.bin. It says its incompatible.
Tested on: OpenWrt SNAPSHOT r6325-e9b58b22c1 / LuCI Master (git-18.051.28524-09ea6db)
Bug is very bad.

Sorry to submit here. Maybe not correct place but where is the correct ?

**Comment by dibdot** [comment]
Please open a ticket here: https://bugs.openwrt.org/
