### ISSUE TITLE
mbedtls: building with ccache: /staging_dir/host/bin/ccache: invalid option -- 'd'

### ISSUE THREAD

**Issue by felixbecker2** [openwrt/packages#5716]
[mbedtls: building with ccache: /staging_dir/host/bin/ccache: invalid option -- 'd']
Tags: mbedtls; ccache; build;

Maintainer: ??
Environment: The toolchain (`./staging_dir/toolchain-*`) is `mips_24kc_gcc-5.5.0_musl`, OpenWRT version: `git clone git://github.com/openwrt/openwrt.git` with recent `git pull`, with latest commit from 2018-03-05T10:44:20+01:00, commit hash 5cbd22bb0f.

Description:

I am currently trying to compile OpenWRT for

    CONFIG_TARGET_LANTIQ=Y
    CONFIG_TARGET_LANTIQ_XWAY=Y
    CONFIG_TARGET_lantiq_xway_DEVICE_arcadyan_arv752dpw22=y

I am using

    CONFIG_DEVEL=y
    CONFIG_CCACHE=y

I am building in the following way:

The build was carried out on a `git clone git://github.com/openwrt/openwrt.git`, later brought up to date with a `git pull`, with latest commit from 2018-03-05T10:44:20+01:00, commit hash 5cbd22bb0f.

Into this `git clone` a previously generated .config seed, made previously by `make menuconfig` and `./scripts/diffconfig.sh`, was copied over to `./.config`.

From there on, the following commands were issued:

    ./scripts/feeds update -a
    ./scripts/feeds install -a
    make -j1 V=s defconfig
    make -j1 V=s download
    make -j1 V=s IGNORE_ERRORS=m | tee make.log

When it comed to building mbedtls, there are the following lines of output which indicate something is wrong:

    [...]
    make[3]: [Makefile:75: /home/felics/download/router/OS/OpenWRT/source_build/source/batch_builds/2018-02-26_12-04-45_-_custom-wo-pie_feeds-rooter-custom/build_dir/target-mips_24kc_musl/mbedtls-2.7.0/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 123 (ignored)
    [...]
    /home/felics/download/router/OS/OpenWRT/source_build/source/batch_builds/2018-02-26_12-04-45_-_custom-wo-pie_feeds-rooter-custom/staging_dir/host/bin/ccache: invalid option -- 'd'
    Usage:
        ccache [options]
    [...]

Build continues, (seemingliy) successfully: Indicated by the further output of `make`, and issuing later a `make -j1 V=s` (i.e. without `IGNORE_ERRORS=m`), does not bring this up again.

The toolchain (`./staging_dir/toolchain-*`) is `mips_24kc_gcc-5.5.0_musl`.

Build is carried out on an x86_64 Arch Linux machine.

Attached are the following files:

- `.config-diffconfig-seed.txt`: The .config-seed used for make defconfig,
- `.config.txt`: The `.config` created by the make defconfig and used for the build,
- `mbedtls.log.txt`: The part of the output of `make -j1 V=s IGNORE_ERRORS=m` regarding building mbedtls,
- `make.log.stdout.gz`: For your interest, the full output of `make -j1 V=s IGNORE_ERRORS=m` (.xz compressed; decompresses to about 29 MB) (Note that at the end another build error occurs, which seems not to be related to embedtls),
- `feeds.conf.txt`: The `feeds.conf` used.

(Note that I just forgot to capture stderr too, but the error messages seem to be present in stdout. Since a full rebuild takes a day on my machine, I won't do that if not necessary.)

[.config-diffconfig-seed.txt](https://github.com/openwrt/packages/files/1782373/default.config-diffconfig-seed.txt)
[.config.txt](https://github.com/openwrt/packages/files/1782372/default.config.txt)
[mbedtls.log.txt](https://github.com/openwrt/packages/files/1782377/mbedtls.log.txt)
[make.log.stdout.gz](https://github.com/openwrt/packages/files/1782375/make.log.stdout.gz)
[feeds.conf.txt](https://github.com/openwrt/packages/files/1782380/feeds.conf.txt)

**Comment by dibdot** [comment]
This is OpenWrt core - please report toolchain/buildroot related things to https://bugs.openwrt.org
