### ISSUE TITLE
acme: please support dns-01 challenge

### ISSUE THREAD

**Issue by bjmgeek** [openwrt/packages#5730]
Please support the dns-01 challenge for acme.  

Maintainer: @tohojo 
Environment:
BUILD_ID="r4882-f295db6e46"
LEDE_BOARD="ramips/mt76x8"
LEDE_ARCH="mipsel_24kc"
(router is a vocore2)

Description:

I'd like to see support for the dns-01 challenge.

**Comment by tohojo** [comment]
Brian Minton <notifications@github.com> writes:

> Please support the dns-01 challenge for acme.  
>
> Maintainer: @tohojo 
> Environment:
> BUILD_ID="r4882-f295db6e46"
> LEDE_BOARD="ramips/mt76x8"
> LEDE_ARCH="mipsel_24kc"
> (router is a vocore2)
>
>
> Description:
>
> I'd like to support the dns-01 challenge.

Patches are very welcome :)

-Toke

**Comment by bjmgeek** [comment]
I'll take a look :-)
