### ISSUE TITLE
travis check: download_sdk fails

### ISSUE THREAD

**Issue by lynxis** [openwrt/packages#5757]
Maintainer: @lynxis

It looks like the download_sdk is failing, even the gpg signature verifies.

**Comment by lynxis** [comment]
https://api.travis-ci.org/v3/job/353189960/log.txt
[log.txt](https://github.com/openwrt/packages/files/1810982/log.txt)

**Comment by diizzyy** [comment]
@lynxis 
No longer valid?

**Comment by lynxis** [comment]
it got fixed
