### ISSUE TITLE
bash: use getcwd from libc instead of bash builtin

### ISSUE THREAD

**Issue by nonicknamewasleftforme** [openwrt/packages#5795]
When cross-compiled, bash disables some features and chooses to replace some libc functions by builtins. One of these is the getcwd builtin. Unfortunately, that builtin does not play well together with overlayfs, which is now heavily used in OpenWRT.

There's pull request #3252 ("bash: enable non-detectable features; unify indents"), which shows how to make configure enable non-detectable features. Similarly, one could add "bash_cv_getcwd_malloc=yes" to CONFIGURE_ARGS to make it use getcwd from libc.

More information on the general issue:
http://permalink.gmane.org/gmane.linux.embedded.yocto.general/25204
http://www.fr.linuxfromscratch.org/view/clfssysroot-svn/hppa/final-system/bash.html

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/5858

**Comment by yousong** [comment]
Fixed by 3f414a0a6790d58988779ce6590980b95645f0ee
