### ISSUE TITLE
dnsmasq - reports failed to load names from /etc/hosts: Permission denied

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#5830]
HEAD

dnsmasq runs as user dnsmasq; however, this forbids access to /etc/hosts

workaround: chown dnsmasq /etc/hosts

**Comment by yousong** [comment]
Works for me.  File `/etc/hosts` has permission bits `0644` by default.

Please report further issues at https://bugs.openwrt.org/, as dnsmasq is not part of the packages feeds here.
