### ISSUE TITLE
isc-dhcp-relay-ipv4: initscript isn't executable

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#5849]
Maintainer: @pprindeville
Environment: lede-17.01.04, isc-dhcp-relay-ipv4 - 4.3.5-1
Description: /etc/init.d/dhcrelay4 is not executable

**Comment by pprindeville** [comment]
What platform are you building for?  What owner/group and permissions does the file end up getting installed as?

**Comment by brianjmurrell** [comment]
Hrm.  Looking at the [package](http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/isc-dhcp-relay-ipv4_4.3.5-1_mips_24kc.ipk) itself:

```
curl http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/isc-dhcp-relay-ipv4_4.3.5-1_mips_24kc.ipk | cpio -i --to-stdout ./data.tar.gz | tar tzvf - ./etc/init.d/dhcrelay4
-rwxr-xr-x root/root      1085 2017-12-18 22:07 ./etc/init.d/dhcrelay4
```

It does seem to be correct.  I will check my next build to see if something is mangling it.

I should have done the above check before even opening this ticket.
