### ISSUE TITLE
wifidog-ng: broken on 4.9 kernels

### ISSUE THREAD

**Issue by MartB** [openwrt/packages#5865]
Maintainer: @zhaojh329 
Environment: ar71xx @ latest master

Description:
Does not build due to kernel 4.9, i saw you have the patch in v1.5.0 can you bump the package to 1.5.0 or release a version with the backported patch ?

Edit:
The author even has a pull request in this repo: #5850
Please accept it.

**Comment by zhaojh329** [comment]
Fixed. #5850
