### ISSUE TITLE
omap platform Flash new firmware image is fail  and not support 

### ISSUE THREAD

**Issue by guhongyeying** [openwrt/packages#5899]
1：i can find  “openwrt/target/linux/x86/base-files/lib/upgrade/platform.sh” and  platform Flash new firmware image is success
2：but  linux omap not find  “openwrt/target/linux/x86/base-files/lib/upgrade/platform.sh” and error"Sorry, there is no sysupgrade support present; a new firmware image must be flashed manually. Please refer to the OpenWrt wiki for device specific install instructions."
3： who can tell me How to do it。

**Comment by dibdot** [comment]
Crosspost & nothing todo with package repo either, see my comment in luci repo.

**Comment by guhongyeying** [comment]
luci repo where?

**Comment by guhongyeying** [comment]
luci repo where?

**Comment by guhongyeying** [comment]
luci repo where?

**Comment by guhongyeying** [comment]
luci repo where? @dibdot
