### ISSUE TITLE
libubox: Can't link libubox from c++11 application

### ISSUE THREAD

**Issue by subjectxbj** [openwrt/packages#5905]
Please make sure that the issue subject starts with `<package-name>: `

This repo here is only for packages maintained in this repo.  For base packages residing in the same repo as the build system and maintained by core devs, please consider opening tickets there for more timely responses

 - OpenWrt base system: https://bugs.openwrt.org
 - Most LuCI packages: https://github.com/openwrt/luci/issues

# Issue template (remove lines from top till here)

Maintainer: @\Felix Fietkau <nbd@nbd.name>
Environment: (put here arch, model, OpenWrt version)

Description:

I'm trying to use ubus within an application writen in c++11, but it report error during build:

```
/usr/include/libubox/blobmsg.h: In function 'char* blobmsg_get_string(blob_attr*)':
/usr/include/libubox/blobmsg.h:202:21: error: invalid conversion from 'void*' to 'char*' [-fpermissive]
  return blobmsg_data(attr);
         ~~~~~~~~~~~~^~~~~~

```

The problem is in the functions as below:
```
static inline char *blobmsg_get_string(struct blob_attr *attr)
{
        return blobmsg_data(attr);
}

```
when returning blobmsg_data(), it does not explicitely convert the return value from void* to char*. This is ok in C, but C++11 will treat this as dangerous, so the compiler report error.

There are multiple places in this file has the problem. Now I have to modify this header file to make the compiler to pass. But I think it will be good to resolve this issue in the original source code.

Thanks,

**Comment by dibdot** [comment]
libubox is OpenWrt core and not part of this repo. Please raise a ticket here: https://bugs.openwrt.org
