### ISSUE TITLE
UPnProxy Bug?

### ISSUE THREAD

**Issue by vsandre** [openwrt/packages#5907]
Is the current upnp package affected and opens its ports to the wan? According to the reasearch of Akamai there are some OpenWRT machines under the current botnet.

https://www.akamai.com/us/en/multimedia/documents/white-paper/upnproxy-blackhat-proxies-via-nat-injections-white-paper.pdf

**Comment by ja-pa** [comment]
Just for the reference link to related discusion on forum  https://forum.lede-project.org/t/akamai-upnproxy-blackhat-proxies-via-nat-injections/13492

**Comment by neheb** [comment]
This is and has been invalid. Closing.
