### ISSUE TITLE
openssh: tunneling broken on the server side in openssh 7.7p1

### ISSUE THREAD

**Issue by asferreira** [openwrt/packages#5925]
Maintainer: @tripolar
Environment:  Archer-c7, OpenWrt SNAPSHOT, r6689-31a6ee0219

Description:

After updating sshd to 7.7p1 I can't create tunnels using neither tun nor tap devices.
Starting sshd in debug mode I found the following error:

```
debug1: server_input_channel_open: ctype tun@openssh.com rchan 0 win 2097152 max 32768    
debug1: sys_tun_open: tunnel mode 2 fd 7                                                  
debug1: server_input_channel_open: failure tun@openssh.com                                
```

**Comment by tripolar** [comment]
please report this to openssh this is not openwrt related
