### ISSUE TITLE
Share tvheadend 4.1

### ISSUE THREAD

**Issue by 9000000** [openwrt/packages#5942]
Ramips 15.05
https://drive.google.com/file/d/1xhNobyUCjJ0MX_i-cCp1VX61hNzlyXf4/view?usp=drivesdk

Ar7xx 15.05
https://drive.google.com/file/d/1Q5y3cottvQhXSIm0t4lOVjjTPiZv-s2f/view?usp=drivesdk

Ar7xx 14.07
https://drive.google.com/file/d/10roipGyLOdMpYUeOSzQDIcgJZwbtqbnC/view?usp=drivesdk

Thank  you dzungvu share
http://vvd214.blogspot.com/2015/05/xem-iptv-mytv-onetv-dung-router-chay.html?m=1

**Comment by hnyman** [comment]
not a bug, bit an issue. 
Looks like stuff for the forum.

Like said, jump in to be the maintainer

**Comment by ajsomething** [comment]
These packages will not install on ddwrt router. incorrect arch. need armv7 like the current repo
