### ISSUE TITLE
uhttpd 

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#5947]
Maintainer: Felix Fietkau <nbd@nbd.name>
trunk

Description:

Inclusion of uhttpd in custom image will not result in uhttpd listening on port 443, as no certs generated.
In the (very) past, px5g was used to build certs, but now only used in case of manual inclusion in image.
Even this is not sufficient, because of reference to /lib/libustream-ssl.so, which is also not included into image by default.

**Comment by bluewavenet** [comment]
You need px5g-mbedtls, libmbedtls and libustream-mbedtls, or alternatively, a quick way if you have luci in your image just include luci-ssl as this will put everything in place.
