### ISSUE TITLE
Restore radvd package

### ISSUE THREAD

**Issue by wltjr** [openwrt/packages#5948]
This came up in issue #1458 but that got closed because the maintainer went MIA. I am available to help maintain and maybe interest from others per comments in that other issue. Filing a new issue till the other is re-opened or to use till package is restored. Thank you!

**Comment by aparcar** [comment]
I'd like to use this tool to enable mobile ipv6 to roam within a mesh network. It currently seems to be the only available solution for mipv6

**Comment by dibdot** [comment]
This is an issue tracker - feel free to open a PR with yourself as maintainer.
