### ISSUE TITLE
open2300: "Library not found: lib2300.so in path:" with CONFIG_USE_MKLIBS ("Strip unnecessary functions from libraries“) (library reduction pass 1)

### ISSUE THREAD

**Issue by felixbecker2** [openwrt/packages#5962]
Maintainer: `dev (at(localnet.hu` (found it by checking history of the package Makefile)

Environment:
`CONFIG_TARGET_ar71xx=y`
`CONFIG_TARGET_ar71xx_generic=y`
`CONFIG_TARGET_ar71xx_generic_DEVICE_gl-ar150=y`
OpenWRT stable relese LEDE 17.01.4

Applies to: `feeds/packages/utils/open2300` (`PACKAGE_open2300`)

Description:

Applies at least to the latest OpenWRT stable release (LEDE 17.01.4):

When the global build option `CONFIG_USE_MKLIBS` ("Strip unnecessary functions from libraries“) is enabled, the build will fail when `CONFIG_PACKAGE_open2300` is selected (does not matter weather `CONFIG_PACKAGE_open2300=m` or `CONFIG_PACKAGE_open2300=y`).

The relevant output of `make -j1 V=s` is:

    I: library reduction pass 1
    19602 symbols, 3 unresolved
    Library not found: lib2300.so in path: /lib:/lib/security:/lib:/usr/lib:/usr/lib/libv4l:/usr/lib/ebtables:/usr/lib:/usr/lib/perl5/5.22/CORE:/usr/lib/perl5/5.22/auto/Tie/Hash/NamedCapture:/usr/lib/perl5/5.22/auto/IO:/usr/lib/perl5/5.22/auto/List/Util:/usr/lib/perl5/5.22/auto/POSIX:/usr/lib/perl5/5.22/auto/Socket:/usr/lib/perl5/5.22/auto/Fcntl:/usr/lib/perl5/5.22/auto/Cwd:/usr/lib/perl5/5.22/auto/I18N/Langinfo:/usr/lib/perl5/5.22/auto/File/Glob:/usr/lib/perl5/5.22/auto/File/DosGlob:/usr/lib/perl5/5.22/auto/re:/usr/lib:/usr/lib/pppd/2.4.7:/usr/lib:/usr/lib/rpcd:/usr/lib:/usr/lib/python2.7/lib-dynload:/usr/lib:/usr/lib/ulogd:/usr/lib:/usr/lib/daq:/usr/lib:/usr/lib/sudo:/usr/lib:/usr/lib/ao/plugins-4:/usr/lib:/usr/lib/sasl2:/usr/lib:/usr/lib/engines:/usr/lib:/usr/lib/rsyslog:/usr/lib:/usr/lib/iptables:/usr/lib:/usr/lib/snort_dynamicengine:/usr/lib:/usr/lib/sane:/usr/lib/collectd:/usr/lib:/usr/lib/snort_dynamicpreprocessor:/usr/lib:/usr/lib/lua:/usr/lib/lua/socket:/usr/lib/lua/smartsnmp:/usr/lib/lua:/usr/lib/lua/luci/template:/usr/lib/lua/luci:/usr/lib:/usr/lib/dovecot:/usr/lib/dovecot/modules:/usr/lib/dovecot/modules/auth:/usr/lib/dovecot/modules:/usr/lib/dovecot/modules/dict:/usr/lib/dovecot/modules:/usr/lib/dovecot/modules/stats:/usr/lib/dovecot/modules:/usr/lib/dovecot/modules/doveadm:/usr/lib/dovecot/modules:/usr/lib/dovecot:/usr/lib/pptpd:/usr/lib:/usr/lib/stunnel:/usr/lib:/etc/ppp/plugins
    package/Makefile:60: recipe for target 'package/install' failed
    make[2]: *** [package/install] Error 1

Build fails.

Deselecting `CONFIG_PACKAGE_open2300` leads to a succeeding OpenWRT build.

**Comment by neheb** [comment]
I updated this package a while back. Please open a new issue if this is still a problem.
