### ISSUE TITLE
adblock: instagram, tumblr, and the other built-in ads

### ISSUE THREAD

**Issue by AddaxSoft** [openwrt/packages#6002]
Maintainer: @dibdot 
Environment: v17.01

https://github.com/openwrt/packages/tree/master/net/adblock

# Description:

The ads that are built-in apps like instagram and tumblr do not get blocked.
The rest are blocked effectively.

**Comment by dibdot** [comment]
Trace the dns queries of those (so called) social media apps and add them to you blacklist. To get all dns requests of your dnsmasq instance set the option "logqueries" and check your logfile afterwards ... 

Please remember that you block always on (sub-)domain level (and not on page element level!) - the same applies to other projects like pihole. For remaining ads on advertising platforms like youtube, facebook etc. it’s likely that you need additional (browser) plugins which are hiding ads on DOM level … anyway you’ll never get 100%.

**Comment by dibdot** [comment]
no package issue, close this for now.
