### ISSUE TITLE
lighttpd: 1.4.48 - missing openssl module in 17.01.04 release

### ISSUE THREAD

**Issue by bluewavenet** [openwrt/packages#6012]
Reference to #5343
I am, after 25th April 2018, getting this problem (lighttpd 1.4.48-1)
Before this date, lighttpd 1.4.45-3 was the release and did not have the issue.
Lighttpd in 17.01.04 is currently broken for SSL.
@MikePetullo 
@pprindeville

**Comment by pkopa** [comment]
I can confirm that version 1.4.48-2 that fixed the issue doesn't compile on mips_24kc architecture:
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/lighttpd/compile.txt

**Comment by bluewavenet** [comment]
What happened to 1.4.45-3? 
**I didn't think new package releases were pushed into the current release of LEDE/OpenWrt.**
This will effect anyone installing or image building from 17.01.04.
I have hacked the components of 1.4.45-3 out of one of my previous images and built it into my latest so I have a work around.

**Comment by bluewavenet** [comment]
@pkopa 
I have not checked them all but it looks like it does not compile in any of the mips or arm architectures.

**Comment by avijc** [comment]
I must be blind, but pkopa's log does not seem like a build failure to me. Can you please point me where the failure is? If it does not compile, any ideas why?

**Comment by avijc** [comment]
Looking at the end of that compile.txt it looks like mod_openssl.so got built, but it was not included in the package. There are various "Packaged contents of .../ipkg-mips_24kc/lighttpd-mod-accesslog" lines for the other modules, but not for mod_openssl. Perhaps the end of https://github.com/openwrt/packages/blob/master/net/lighttpd/Makefile needs to be updated to include the appropriate references to mod_openssl to get it included.

Disclaimer: I haven't used OpenWRT at all. I'm only here because someone filed an upstream bug in lighttpd's bug tracker for this OpenWRT packaging issue. I hope you can fix this by yourself.

**Comment by bluewavenet** [comment]
@avijc thanks for looking. I came to the same conclusion. I am not a maintainer on here but will raise a PR
Thanks :-)

**Comment by bluewavenet** [comment]
see PR #6029

**Comment by pprindeville** [comment]
Isn't this a duplicate of issue #5343?

**Comment by pprindeville** [comment]
@champtar How do we get a cherry-pick of PR #5344 into 17.0.4?  Thanks

**Comment by bluewavenet** [comment]
@pprindeville , no not a duplicate of #5343, but pointing out a problem with the FIX for #5343
The module ipk does not get built in 1.4.48-2

**Comment by bluewavenet** [comment]
The REALLY big issue here is the major change in **stable 17.01.4 packages** from lighttpd version 1.4.45-3 to the **known broken** version 1.4.48-1 on the 25th April 2018.

I was under the impression that packages in the OpenWrt/LEDE release were not to be changed apart from in exceptional circumstances.

I have a custom ImageBuilder process for production updates of custom code and this change caused considerable problems.

Version 1.4.48-2 in snapshots also has the problem that the mod_openssl ipk is not built.
My PR #6038 is to fix this issue

@champtar @jow- @pprindeville @MikePetullo

**Comment by MikePetullo** [comment]
OpenWrt just merged #6077. The package at https://downloads.openwrt.org/releases/17.01.4/packages/x86_64/packages/ includes mod_openssl.so as of Mon May 21 10:18:12 2018. I think this issue can close.

**Comment by bluewavenet** [comment]
Fixed! :-)
