### ISSUE TITLE
protobuf-c: host build should depend on protobuf

### ISSUE THREAD

**Issue by alyf80** [openwrt/packages#6031]
Maintainer: @jsiverskog 
Environment: openwrt trunk

Description:
Since 3581bc6 protobuf-c tries to build the host tools, but that fails if the host protobuf compiler is not present.

The Makefile sholud declare the dependency:
```
HOST_BUILD_DEPENDS:=protobuf/host
```

**Comment by neheb** [comment]
This is fixed in current version. Please close.
