### ISSUE TITLE
nginx version is too old

### ISSUE THREAD

**Issue by Magissia** [openwrt/packages#6059]
Maintainer: @heil  
Environment: mipsel

Description:

```
nginx branch 1.12 is now in "legacy" status, supported version include branch 1.13 and 1.14, they have many security improvements.
```

**Comment by diizzyy** [comment]
Hi,
Requesting version bumps for a package isn't a bug (issue) and you're providing close to little information on platform, version of OpenWrt etc. 1.14 is already in the tree https://github.com/openwrt/packages/commit/157baf5c65ffbab1f82e3896ba19bf42b84d2c74 btw

Please close
@hnyman
