### ISSUE TITLE
boost: Is it possible to select a specific lib from boost?

### ISSUE THREAD

**Issue by amiguels** [openwrt/packages#6069]
Hello!

I have a package that depends on the program_options lib from boost.
On the Makefile I have added `  DEPENDS:=+boost`, however that adds boost but not the library.

How can I add a specific library from boost?

Thanks!

**Comment by cotequeiroz** [comment]
Use `DEPENDS:=+boost-program_options` and you're good to go.
There's a list of libraries in boost's Makefile (each call to `DefineBoostLibrary` creates a `boost-<library>` package).
Cheers

**Comment by amiguels** [comment]
Yup, that did it.
Thanks!
