### ISSUE TITLE
<mjpg-streamer - r182-10> Ignoring Empty Buffer

### ISSUE THREAD

**Issue by cjp160** [openwrt/packages#6070]
When running mjpg-streamer for a long time (24-48 hours), it will occasionally print out "Ignoring empty buffer...". If it does that four times without restarting the stream, the stream will hang.

The issue was brought up in this thread: https://github.com/jacksonliam/mjpg-streamer/issues/100 and fixed in that forked version of mjpg-streamer. Is there a way to fix it in the main OpenWRT package?

**Comment by thess** [comment]
Thanks for the note - It's has been a while since I sync'd up with any dev work on mjpg-streamer. Perhaps I can get some time to switch over to the other repo (or at least co-opt some patches).

**Comment by cjp160** [comment]
That would be awesome!

**Comment by thess** [comment]
If you could give PR #6092 a test - let me know how you make out.
After I do a bit more local testing, I will merge this version into master in a day or 2.

**Comment by cjp160** [comment]
Is there a way to install this using opkg on my device?

Collin

**Comment by thess** [comment]
If you cannot build it yourself, you'll have to wait until this is merged and the buildbots produce a package for your architecture. Hmmm... you never mentioned what platform / release you are using it on.

**Comment by thess** [comment]
PR #6092 merged - please test after buildbots catch up.

**Comment by cjp160** [comment]
Will do. So this will no longer hang after the stream outputs “Ignoring empty buffer…” 4 times?

Collin

**Comment by diizzyy** [comment]
Can we close this?
