### ISSUE TITLE
bash problem with scp

### ISSUE THREAD

**Issue by ian-kelling** [openwrt/packages#6137]
https://dev.archive.openwrt.org/ticket/13852
Opened in 2014, closed as moved_to_github, but searching bash scp or the bug number has no result so afaik it was not moved to github

    scp root@192.168.1.1:/tmp/test .
    root@192.168.1.1's password:

    shell-init: error retrieving current directory: getcwd: cannot access parent directories: Inappropriate ioctl for device

**Comment by yousong** [comment]
Hi, this should be fixed now since the last version bump of bash here.  Have you tried it?

**Comment by yousong** [comment]
Feel free to report here if the issue still exists.  Thank you.

**Comment by ian-kelling** [comment]
Yes. It is fixed. Thanks.
