### ISSUE TITLE
uhttpd additional authentication

### ISSUE THREAD

**Issue by alexshalex** [openwrt/packages#6155]
ssh and LuCI login/password - root/root
in file /etc/config/uhttpd in section 'main'
option config '/etc/httpd.conf'
in file /etc/httpd.conf
/:admin:admin
After service restart uhttpd I log into the web interface. Asks to enter login in the window, I enter the admin admin and I get into the authentication LuCI. I enter the root root and get an error "Invalid username and/or password! Please try again."

**Comment by diizzyy** [comment]
Non of these packages are in the package repo, closing.
