### ISSUE TITLE
Python2.7: bad install directory or PYTHONPATH (does not support .pth files)

### ISSUE THREAD

**Issue by enigmagroup** [openwrt/packages#616]
This error happens when trying to build python2.7 with the most recent repo + package feeds:

(       export PYTHONPATH="/home/x/openwrt-banana-mostrecent/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib/python2.7:/home/x/openwrt-banana-mostrecent/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi//usr/lib/python2.7/site-packages"; export PYTHONOPTIMIZE=""; export PYTHONDONTWRITEBYTECODE=1;  cd /home/x/openwrt-banana-mostrecent/build_dir/host/Cython-0.20.2/; CFLAGS="-O2 -I/home/x/openwrt-banana-mostrecent/staging_dir/host/include -I/home/x/openwrt-banana-mostrecent/staging_dir/host/usr/include" CPPFLAGS="-I/home/x/openwrt-banana-mostrecent/staging_dir/host/include -I/home/x/openwrt-banana-mostrecent/staging_dir/host/usr/include" LDFLAGS="-L/home/x/openwrt-banana-mostrecent/staging_dir/host/lib -L/home/x/openwrt-banana-mostrecent/staging_dir/host/usr/lib"   /home/x/openwrt-banana-mostrecent/staging_dir/host/bin/python2  ./setup.py install --no-cython-compile --prefix="/home/x/openwrt-banana-mostrecent/staging_dir/host/usr" ; )
running install
Checking .pth file support in /home/x/openwrt-banana-mostrecent/staging_dir/host/usr/lib/python2.7/site-packages/
/home/x/openwrt-banana-mostrecent/staging_dir/host/bin/python2 -E -c pass
TEST FAILED: /home/x/openwrt-banana-mostrecent/staging_dir/host/usr/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

```
/home/x/openwrt-banana-mostrecent/staging_dir/host/usr/lib/python2.7/site-packages/
```

and your PYTHONPATH environment variable currently contains:

```
'/home/x/openwrt-banana-mostrecent/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib/python2.7:/home/x/openwrt-banana-mostrecent/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi//usr/lib/python2.7/site-packages'
```

Here are some of your options for correcting the problem:
- You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files
- You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)
- You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:
  
  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
make[3]: **\* [/home/x/openwrt-banana-mostrecent/build_dir/host/Cython-0.20.2/.built] Error 1
make[3]: Leaving directory `/home/x/openwrt-banana-mostrecent/feeds/enigmabox/python-cython'
make[2]: *** [package/feeds/enigmabox/python-cython/host/compile] Error 2
make[2]: Leaving directory`/home/x/openwrt-banana-mostrecent'
make[1]: **\* [/home/x/openwrt-banana-mostrecent/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/x/openwrt-banana-mostrecent'
make: **\* [world] Error 2

**Comment by linamu** [comment]
@commodo i have the same error and i'm using python2.7.3 
how to fix it ?
