### ISSUE TITLE
Nexx WT3020F firmware install issue 

### ISSUE THREAD

**Issue by danieleperera** [openwrt/packages#6187]
Hi, I am new to openwrt and i wanted to do a project on Nexx WT3020F so i followed the instructions on https://wiki.openwrt.org/toh/nexx/wt3020#installation but after i uploaded the firmware "https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/openwrt-15.05.1-ramips-mt7620-wt3020-8M-squashfs-factory.bin" the nexx wt3020F doesn't work anymore. When i connect my ethernet cable is says undefined network. I have no idea what do i do next. Thanks

**Comment by dibdot** [comment]
Not package related, please ask in the forum: https://forum.lede-project.org
