### ISSUE TITLE
Blocking capability performance comparison: adblock, ublock origin add on and pi-hole

### ISSUE THREAD

**Issue by erotavlas85** [openwrt/packages#6200]
Hi,
first of all thank you for this great package. I would like to know if there is any performance comparison in terms of blocking capability of each solution adblock, [ublock origin](https://github.com/gorhill/uBlock) and [pi-hole](https://pi-hole.net/).
I noticed that ublock origin is the best solution especially due the fact that many Web sites stream the content together with the ads and so it is the only one that can block them without blocking all the Web site. [A brief analysis](https://discourse.pi-hole.net/t/poor-performance-compared-to-ublock/3603/3) between ublock origin and pi-hole. However, in theory, adblock and pi-hole should be able to block the same contents since they work similarly at DNS level.
In practice, I noticed that pi-hole is better than adblock (I used [this](https://pi-hole.net/pages-to-test-ad-blocking-performance/) list of Web sites as benchmark). I’m using the latest version of adblock v3.4.3 with dnscrypt-proxy (force local DNS and flush DNS cache options enabled) and all block list sources enabled plus custom filter [standard privacy](https://easylist.to/easylist/easyprivacy.txt) (overall domains 102294).
Is it normal or I can do something in order to improve openWRT performance?
Thank you

**Comment by dibdot** [comment]
First of all, this is an issue tracker - and not an additional forum!
pi-hole and adblock are both working on DNS level, whenever you use the same blacklisted domains, you will get the same result => different result means different blacklisted domains.
The advantage of uBlock is the element hiding and other DOM filtering rules (you can combine tools like that with adblock of course). The advantage of adblock (and pihole) is that you get a network level protection - without browser extensions you can protect all connected devices.
