### ISSUE TITLE
luci-app-firewall: values considered invalid for multiple IPs

### ISSUE THREAD

**Issue by ggetsov** [openwrt/packages#6209]
In the **Traffic Rules** page on save you would get "Some fields are invalid, cannot save values!" if source or destination address contains dashes or commas. I've tried setting the value manually in **/etc/config/firewall** and the rule is applied flawlessly. Versions:
**uname -a**: `Linux <hostname> 4.4.92 #0 SMP Mon Oct 16 22:57:05 2017 armv7l GNU/Linux`
**iptables**: `v1.4.21`
**openwrt**: `17.01.4 r3560-79f57e422d`
**luci-app-firewall**: `git-18.147.69097-36945b5-1`

Edit: Ok, I found this is not the way this should work. Still there is no way to add a range of IP addresses even if you have the **iptables-mod-iprange** package installed. A workaround would be to add the range in the extra arguments like so: `-m iprange --src-range <start ip>-<end ip>`, although this is not visible in the rules list.

Shouldn't this be easier?

**Comment by feckert** [comment]
Please open this issue to the https://github.com/openwrt/luci because this is an luci issue.
There were recently a lot of changes on the master branch in the luci-app-firewall app.
