### ISSUE TITLE
Unable to find "xtables-addons" package to compile in openwrt/Lede

### ISSUE THREAD

**Issue by alirz1** [openwrt/packages#6234]
i cannot find the ‘xtables-addons’ as a package that i can select to be included in my build.Sorry im not an expert at development. Just enough knowledge to compile a custom image using the LEDE build environment.
it should be under Network > Firewall

Even with enabling the following, i cannot find it.

PKG_BUILD_DEPENDS:=iptables

define Package/xtables-addons
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Firewall
  TITLE:=Extensions not distributed in the main Xtables
  URL:=http://xtables-addons.sourceforge.net/
endef

**Comment by feckert** [comment]
Maybe some dependency are not satisfied so this is not an issue
