### ISSUE TITLE
nail fails to build

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#628]
The CC builder fails on the nail package with this error ->

ccache_cc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -I/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include   -DMAILRC='"/etc/nail.rc"' -DMAILSPOOL='"/var/mail"' -DSENDMAIL='"/usr/lib/sendmail"'    -c version.c
ccache_cc -L/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib  aux.o base64.o cache.o cmd1.o cmd2.o cmd3.o cmdtab.o collect.o dotlock.o edit.o fio.o getname.o getopt.o head.o hmac.o imap.o imap_search.o junk.o lex.o list.o lzw.o macro.o maildir.o main.o md5.o mime.o names.o nss.o openssl.o pop3.o popen.o quit.o send.o sendout.o smtp.o ssl.o strings.o temp.o thread.o tty.o v7.local.o vars.o version.o `grep '^[^#]' LIBS`  -o mailx
aux.o: In function `alter':
aux.c:(.text+0x60e): warning: the use of OBSOLESCENT `utime' is discouraged, use `utimes'
fio.o: In function `sopen':
fio.c:(.text+0xe9c): warning: gethostbyname is obsolescent, use getnameinfo() instead.
openssl.o: In function `ssl_open':
openssl.c:(.text+0x674): undefined reference to `SSLv2_client_method'
collect2: error: ld returned 1 exit status

**Comment by champtar** [comment]
fixed with de0ab13

**Comment by taeasy** [comment]
make[2]: Entering directory '/home/main/lede/feeds/packages/mail/nail'
CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5:heirloom-mailx-12.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5:heirloom-mailx-12.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/include -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/include " LDFLAGS="-L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/lib -znow -zrelro " make -j1 -C /home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5:heirloom-mailx-12.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" ;
make[3]: Entering directory '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5'
x86_64-openwrt-linux-musl-gcc -L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/target-x86_64_musl-1.1.15/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/usr/lib -L/home/main/lede/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.15/lib -znow -zrelro aux.o base64.o cache.o cmd1.o cmd2.o cmd3.o cmdtab.o collect.o dotlock.o edit.o fio.o getname.o getopt.o head.o hmac.o imap.o imap_search.o junk.o lex.o list.o lzw.o macro.o maildir.o main.o md5.o mime.o names.o nss.o openssl.o pop3.o popen.o quit.o send.o sendout.o smtp.o ssl.o strings.o temp.o thread.o tty.o v7.local.o vars.o version.o grep '^[^#]' LIBS -o mailx
openssl.o: In function ssl_open': openssl.c:(.text+0xa2f): undefined reference toSSLv3_client_method'
collect2: error: ld returned 1 exit status
Makefile:92: recipe for target 'mailx' failed
make[3]: *** [mailx] Error 1
make[3]: Leaving directory '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5'
Makefile:58: recipe for target '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5/.built' failed
make[2]: *** [/home/main/lede/build_dir/target-x86_64_musl-1.1.15/heirloom-mailx-12.5/.built] Error 2
make[2]: Leaving directory '/home/main/lede/feeds/packages/mail/nail'
package/Makefile:127: recipe for target 'package/feeds/packages/nail/compile' failed
make[1]: *** [package/feeds/packages/nail/compile] Error 2
make[1]: Leaving directory '/home/main/lede'
/home/main/lede/include/toplevel.mk:194: recipe for target 'package/feeds/packages/nail/compile' failed
make: *** [package/feeds/packages/nail/compile] Error 2
