### ISSUE TITLE
freeswitch fails to build

### ISSUE THREAD

**Issue by blogic** [openwrt/packages#630]
The CC builder fails on the freeswitch package with this error ->

Checking for Locking...
checking for semget... yes
checking for semctl... yes
checking for flock... yes
checking for semaphore.h... (cached) yes
checking OS.h usability... no
checking OS.h presence... no
checking for OS.h... no
checking for sem_close... yes
checking for sem_unlink... yes
checking for sem_post... yes
checking for sem_wait... yes
checking for create_sem... no
checking for working sem_open... no
checking for union semun in sys/sem.h... no
checking for LOCK_EX in sys/file.h... yes
checking for F_SETLK in fcntl.h... yes
checking for SEM_UNDO in sys/sem.h... yes
checking for POLLIN in poll.h sys/poll.h... yes
checking for PTHREAD_PROCESS_SHARED in pthread.h... yes
checking for pthread_mutexattr_setpshared... yes
checking for pthread_setschedparam in -lpthread... yes
checking for working PROCESS_SHARED locks... configure: error: in `/CC/build/ar71xx/generic.sdk/build_dir/target-mips_34kc_uClibc-0.9.33.2/freeswitch-1.5.15b/libs/apr':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
configure: error: ./configure.gnu failed for libs/apr
make[3]: *** [/CC/build/ar71xx/generic.sdk/build_dir/target-mips_34kc_uClibc-0.9.33.2/freeswitch-1.5.15b/.configured_yyyyyynyyynnnynnyynynnyyynynyyyyyyyyyyyyynyynyyyyyyyyyyyyyyyyynyyyyyyynyynyyyynynynyyyynyyyyyyynnnnyyyyyynnynnyyyyynyyyyyyyyyyyyyyyyynyyyyyyyyynnnnnnyyyyyyynyyyyyyyyyynyn] Error 1

**Comment by champtar** [comment]
hi @blogic 
wrong feed :)
(i've openned openwrt/telephony#10)
