### ISSUE TITLE
Erlang Need erl_interface

### ISSUE THREAD

**Issue by mifadirx** [openwrt/packages#6321]
the erlang package need erl_interface, its a c lib to call c code as erlang process
i wanted to compiled elixir on openwrt, and it need erl_interface, i know its a bit hard in cross compiling it, but if you can fix it it will be good

**Comment by dibdot** [comment]
@cretingame

**Comment by cretingame** [comment]
Hey, I can see that, next week. I will upgrade at the same the erlang package because it's too old.

**Comment by cretingame** [comment]
I actually already included erl_interface to openwrt package repository. https://github.com/openwrt/packages/commit/5a56e39f1dc610ca8244fbac67d8a98657c9bf31

**Comment by feckert** [comment]
@mifadirx is this still an issue? If not please close.

**Comment by neheb** [comment]
Closing due to timeout
