### ISSUE TITLE
golang: download failed

### ISSUE THREAD

**Issue by zhaojh329** [openwrt/packages#6326]
Maintainer: @jefferyto
Compile tested: (mipsel,miwifi-mini, master)

Description:
Cannot access https://go.googlesource.com/go in China.
So I requested to change BOOTSTRAP_SOURCE_URL to https://github.com/golang/go.

**Comment by kofec** [comment]
As far As I know there can be more than one sources

**Comment by jefferyto** [comment]
Thanks @zhaojh329 and @yousong, I've changed the bootstrap source URL to the GitHub mirror. I also added some mirrors for the main src tarball (thanks @diizzyy for the Gentoo link) as I believe golang.org isn't accessible in China either.
