### ISSUE TITLE
NCM Proto for LTE Sticks.... rework needed?

### ISSUE THREAD

**Issue by ThomasCr** [openwrt/packages#6329]
Hi,
I want to talk about the ncm protocal implementation which currently exist in openwrt.

What is the reason, that such ncm interface starts a new pseudo interface with _4 or _6 and the end?
I am asking, because it is not well supported in openwrt to do so.

We getting problems in mwan3 and also on luci network pages... we don't get the ip address of the interface displayed, because of the extra _4/_6 interfaces, which are not joined/connected together.
I don't know what other packages also need to be specially suited to this interface style?!

Maybe I am wrong?

**Comment by dibdot** [comment]
Please join https://forum.openwrt.org
