### ISSUE TITLE
luci-app-acme and nginx

### ISSUE THREAD

**Issue by lucize** [openwrt/packages#6335]
with new LUCI support for nginx one also needs to have luci-app-uhttpd if luci-app-acme is needed, maybe doing a config for nginx also and depend on what webserver is selected ?
@Ansuel @tohojo

**Comment by Ansuel** [comment]
think i will have to make a matepackage for nginx...

**Comment by diizzyy** [comment]
@Ansuel 
This is fixed now as far as I can tell?

**Comment by Ansuel** [comment]
ummm no... we still need to create e metapackage for acme on nginx... 

also i can't understand, acme needs uhttpd to validate the certs or just to autoinstall it? @lucize can you give me some info about it... 

(Create a configuration to use nginx to validate the cert is not so easy i think....)

**Comment by Ansuel** [comment]
think you were referring to ariang package?

**Comment by lucize** [comment]
right now the dependency is more like a theoretical one, you need to define a folder for key validation so the dependency makes it easy for you to do that but is not automatically done if you have it installed (luci-app-uhttpd) so not really needed. I can't test right now, I'm on holidays
