### ISSUE TITLE
prometheus-node-exporter-lua: Metric names do not follow recommended practices

### ISSUE THREAD

**Issue by ciphermenial** [openwrt/packages#6353]
Maintainer: @aparcar 
Environment: All

Description: Not really a bug, just a problem. I am having to modify downloaded Grafana templates to work with the metrics output since they don't follow the recommended practices from [Prometeus for Metric Naming](https://prometheus.io/docs/practices/naming/).

**Comment by aparcar** [comment]
Hi @simplexion and thanks for opening an issue. 

Could you elaborate on which metric doesn't fit? I think some parts are not directly comparable with the official `node_exporter` written in Go.

**Comment by simplexion** [comment]
It's the suffix/base units that appear to be missing from this exporter. I can easily make the Grafana templates work by removing _bytes or _total from the information it is creating the graphs from and they work with the data from the router. This means requiring separate dashboards for my router as opposed to all the rest of the hosts using the official node exporter.

**Comment by simplexion** [comment]
I wouldn't know where to start.

**Comment by aparcar** [comment]
it would help me very much if you'd post a list of "bad" metric names and your suggested replacement

**Comment by aparcar** [comment]
@champtar I'd be up to create a PR but it somewhat crashes compatibility with previous releases. However, I think it's reasonable to be conform with the official exporters. Thoughts?

**Comment by champtar** [comment]
I'm fine following official node_exporter, and they seem to be fine breaking everything :) (https://github.com/prometheus/node_exporter/blob/master/CHANGELOG.md)
@simonswine any thoughts ?
@aparcar if you remember any other user of this package please ping them, else please go ahead
Also as you are the most active contributor to this package, maybe put yourself as `PKG_MAINTAINER`

**Comment by aparcar** [comment]
@simplexion please review this PR here https://github.com/openwrt/packages/pull/6356 and complain on odd names, I hope I renamed them all

**Comment by simplexion** [comment]
Haha! I figured the fault here was on Prometheus. Fingers crossed they don't decide to break it again.
PR makes sense to me and it looks like it should be all right now. Thanks!

**Comment by aparcar** [comment]
Please close this issue if fixed by the previous PR
