### ISSUE TITLE
Unbound: configure DNS over TLS with UCI

### ISSUE THREAD

**Issue by localnet** [openwrt/packages#6381]
Maintainer: @EricLuehrsen 

Do you have any plans to permit configure DNS over TLS with UCI?

My better idea is add a config option, for example:
  - option tls_auth_name 'cloudflare-dns.com'

In the unbound script if the option "tls_auth_name" has value assigned, check if exist "/etc/ssl/certs/ca-certificates.crt". if it exist add:
  - tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

In the unbound script at the function "unbound_forward" if the option "tls_auth_name" has value assigned cacatenate the value to the forwarders (in this example "#cloudflare-dns.com") and add:
  - forward-tls-upstream: yes

Trouble: all forwarders need be of the same provider (cloudflare, quad9, etc.) It can not mix. If this approach seems you valid I can try to implement it.

More information about unbound and DNS over TLS: https://nlnetlabs.nl/bugs-script/show_bug.cgi?id=658

**Comment by EricLuehrsen** [comment]
First a work around and experimental location, if you haven't already been using it. If you use LuCI, you can edit the added conf files in luci-app-unbound.

I have been thinking the same thing. Cloudflare make a good example of standard use for DNS TLS. There are however custom needs and installations. My concern for UCI is it is supposed to make things easier for the _"more average"_ user. We need the certs installed. We need fall back configured for a minimum set of locations out of TLS (get new certs). Some certs could be found in DANE through Unbound itself, which would require a restart to add them. It all would be interesting, but rushing the design could constrain it.

**Comment by localnet** [comment]
I know about "unbound_ext.conf" and "unbound_srv.conf", I am using them.

I thought it was interesting for the _"more average"_ user. But my better idea didn't seems enough solid, so I prefered ask before try to implement it. And you are right, better stability.

One time more, thanks for your great work.

PS: Feel free to close the issue, or maintain it open if you can and want investigate more about it. As you prefer.

**Comment by EricLuehrsen** [comment]
It **is** a good idea. One of the problems I have with Unbound is that the forward-zone: clause is per zone, and it would be nice if that was done in reciprocal order. That is define a forward-server: clause, and assign it zones, so UCI could fix that. Upstream ISP forward has a UCI already which should be reworked to play well with this (special forward IP/Domain "resolve-conf"). Then add a TLS cert file location option, so non-empty to enable TLS. Probably can kill or substantially trim the dnsmasq script also. This would be a repeatable subsection in Unbound UCI. Right now I am cleaning UCI due to features I added without proper foresight.

**Comment by EricLuehrsen** [comment]
```
section forward
  list server '1.1.1.1'
  list server '1.0.0.1'
  list zone 'example.com'
  list zone 'example.org'
  option cert_file '/etc/ca/cloudflare'
  option fwd_prefernce 'only' 
  # Unbound permits forward only or forward first with recursive fall back
  option tls_preference 'preferred'
  # Could be disabled or required, default allows fallback if cert file defined but not found or bad
```

**Comment by localnet** [comment]
Excuse late response, again I am busy with real live.

The separate configuration section for "forward" seems a more solid solution. But I like the simplicity to use upstream resolvers from "resolv.conf.auto". Maybe a posibility would to do option "list server" optional, if it is not specified use upstream resolvers from "resolv.conf.auto".

**Comment by EricLuehrsen** [comment]
Yes, there will need to be a option for resolv.conf.auto which removes the simple (and limited usefulness) of the current forward option. The option in my mind would be a few pre-configured choices including "resolv-auto", "cloudflare", "cloudflare_tls", "quad9" and so on. If empty, "custom," or just unrecognized, then server and TLS options are used. I am trying to think of the best fall back solution, if the cert bundle is not installed or out of date. Total DNS black out is the default and conservative solution, but then you need to reconfigure Unbound and download new cert. Maybe black list most zones (Unbound "static"), disable forwards, and permit recursion on github.com, openwrt.org, debian.org, and others.

**Comment by localnet** [comment]
I think the better solution is the most obvious, that ca-bundle be a dependency of unbound. Or split in two packages unbound-tls and unbound, the first with dependency of ca-bundle and the second without this dependency.

The pre-configured choices are a good idea, too have the risk of changes in upstream but I think this risk is minimal.

**Comment by EricLuehrsen** [comment]
I have updated the recipes in both master and openwrt-18.06 as interim actions. [openwrt.org](https://openwrt.org/docs/guide-user/services/dns/unbound) documentation pointer is updated also. It will take some time to scratch out a thorough solution.

**Comment by EricLuehrsen** [comment]
@localnet Please close this issue. Lets continue in PR #6573 including code review, testing, complaints, and whatever. :-)

**Comment by localnet** [comment]
Thanks you.
