### ISSUE TITLE
ca-certificates broken on lede

### ISSUE THREAD

**Issue by jhiswin** [openwrt/packages#6388]
# opkg install ca-certificates
Installing ca-certificates (20170717) to root...
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/base/ca-certificates_20170717_all.ipk
Configuring ca-certificates.
# ls /etc/ssl/certs/ca-certificates.crt
ls: /etc/ssl/certs/ca-certificates.crt: No such file or directory

**Comment by chris5560** [comment]
#> ls /etc/ssl/certs/* and you will see all the certificates

**Comment by jow-** [comment]
`ca-certificates.crt` is part of `ca-bundle`, not `ca-certitificates`.
