### ISSUE TITLE
ddns-scripts: curl should allow to use --interface with ipaddress, not device

### ISSUE THREAD

**Issue by luizluca** [openwrt/packages#6391]
Maintainer: @chris5560 
Environment: OpenWrt Trunk

Description:

My ISP is blocking IPv6 WAN address but allow IPv6 LAN (delegated prefix). I need to use 
```curl --interface <my_lan_IPv6_address>```
but ddns-scripts forces curl to use LAN device. It's not the same.

Please, allow a way to force curl to use the same bind_network code that wget does. I simply replaced the curl code by the wget one (that gets IP address) and it worked for me.

**Comment by dibdot** [comment]
@luizluca ddns-scripts is currently unmaintained. Feel free to open a PR with your enhancement.
