### ISSUE TITLE
lxc-checkconfig: Checks for non existing modules in openwrt-18.06

### ISSUE THREAD

**Issue by lukasmrtvy** [openwrt/packages#6409]
lxc-checkconfig in openwrt-18.06 is checking for modules 8021q,bridge. But these are not available as kmod-modules. 

It seems that these are removed from 3.18 kernel https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=7096ed58fdc908144d2c52bf416e9b3b0e48795a

Can anyone update/patch lxc-checkconfig package?

EDIT:
Rest of modules from misc section:

kmod-veth #veth-> loaded by LXC_NETWORKING symbol
kmod-macvlan #macvlan -> loaded by LXC_NETWORKING symbol
kmod-nft-core #nf_tables -> not loaded by default
kmod-nft-nat4 #nf_nat_ipv4, nf_nat_masquerade_ipv4
kmod-nft-nat6 #nf_nat_ipv6, nf_nat_masquerade_ipv6 -> not loaded by default
kmod-ipt-core  #xt_comment
kmod-ipt-checksum  #xt_checksum  -> not loaded by default
kmod-fuse #fuse  -> not loaded by default

**Comment by lukasmrtvy** [comment]
@lperkov ping to package maintainer

**Comment by zxdavb** [comment]
FWIW: These are the changes I make to **lxc-checkconfig** to fix various issues that are resolved in a later release than that currently used by OpenWrt:
```
    sed -i '/SETCOLOR_FAILURE/   s/\"\$SET/\$SET/'  /usr/bin/lxc-checkconfig
    sed -i '/SETCOLOR_FAILURE/   s/ILURE\"/ILURE/'  /usr/bin/lxc-checkconfig
    sed -i '/xt_CHECKSUM$/a echo'                   /usr/bin/lxc-checkconfig
    sed -i '/E_INSTANCES$/a echo'                   /usr/bin/lxc-checkconfig
    sed -i '/ROUP_NS yes$/a echo'                   /usr/bin/lxc-checkconfig
    sed -i '/CAPABILITIES/  s/ES )/ES; echo \)/'    /usr/bin/lxc-checkconfig
```

**Comment by neheb** [comment]
@zxdavb can you make a PR?

**Comment by zxdavb** [comment]
no, sorry - I have too much git on my plate as it is

**Comment by cotequeiroz** [comment]
18.06 is EOL now, so I'm closing this.
