### ISSUE TITLE
Mwan3 cannot load balance traffic through transparent proxy

### ISSUE THREAD

**Issue by cjjdaq** [openwrt/packages#6455]
Mwan3 2.6.18
Kernel version 4.14.52
I use koolproxy as a transparent proxy to filter tcp 80, 443 port ads.
Koolproxy listens on the tcp 3000 port.
Koolproxy use mark mode, set the socket mark(src ip) when connect to remote host.
Iptables -t nat -N KOOLPROXY
iptables -t nat -A KOOLPROXY -p tcp -m multiport --dport 80,443 -j REDIRECT --to-ports 3000

This can be used to load acl rules in nat->output.
For example: -A OUTPUT -p tcp -m mark --mark 0xc0a80100/0xffffff00 -j SHADOWSOCKS_EXT

Ip addr add "192.168.2.1/32" dev lo
  Ip route add default 192.168.2.1 dev lo
But the problem is coming.
There is no problem with the traffic load balancing initiated by the route itself, but the traffic passing the koolproxy cannot use mwan3 load balancing.

**Comment by feckert** [comment]
@cjjdaq Have you tested this with the new 2.7.1 version?
If this solve your issue then please close this.

**Comment by feckert** [comment]
@hnyman no reaction from issue creater and I think this is solved. So could you also please this issue?
