### ISSUE TITLE
xmail:Failed to create for eventfd

### ISSUE THREAD

**Issue by mariarti** [openwrt/packages#6464]
Maintainer: ??
Environment: 
ar71xx
MikroTik RouterBOARD 951G-2HnD
OpenWrt Barrier Breaker 14.07 r44952
Kernel Version	3.10.49
package xmail 	1.27-1

Description:
daemon start failed with error: daemon.err XMail[3182]: Failed to create for eventfd

**Comment by diizzyy** [comment]
OpenWrt BB isn't supported, please upgrade to 17.X, 18.X or Master

Please close this issue report 
@hnyman

**Comment by thess** [comment]
@mariarti - You might want to see if you can get help on this in the forum (if you haven't already).
https://forum.lede-project.org/
