### ISSUE TITLE
Python3-setuptools: request update package from 39.0.1 .

### ISSUE THREAD

**Issue by Kirya2k** [openwrt/packages#6473]
Maintainer: @commodo 
Environment: Openwrt-18.06 and Master.

Description: Modules pycryptodome and uvloop don't build pip3 with python3-setupttols 39.0.1.
Update package plz.
Thanks a lot.

**Comment by commodo** [comment]
Hey,

The version of this package is controlled by the python3 package.
Whenever we update python3 we get the version that Python3 has built-in.

Can you update this package via pip3 ?
Would that work ?

Something like: ‘pip3 install —upgrade setuptools ‘
 It could be a good idea to also upgrade pip3 in a similar fashion, if upgrading setuptools.

Thanks
Alex

**Comment by Kirya2k** [comment]
build-in pip3 make update setuptools normally.
But me also have to install the gcc-toolchain, which is inconvenient.
So I ask you to update setuptools in ipk of python-stream Openwrt.
pip3 I haven't tried to update.

With best regards, Kirya.

**Comment by commodo** [comment]
i will take a look at a solution for this :)
maybe there is something that works in-between for this

**Comment by jefferyto** [comment]
Does #7849 (and #7854) fix this issue?

**Comment by commodo** [comment]
I think @Kirya2k needs to be take a look closer.
`python3-setuptools` did upgrade ; hopefully the version that is shipped now is good enough to meet the requiremenets here.
But if a newer version is desired, then this will be a permanent/ongoing issue, as the version of setuptools will always be tied to the version that comes shipped with Python/Python3.

**Comment by Kirya2k** [comment]
Yes, version 40.6.2 is enough for build.
Thx a lot !
