### ISSUE TITLE
openwrt 18.06 runs in netgear r6220 , shadowsocks-libev cannot work well

### ISSUE THREAD

**Issue by kevinqiu0098** [openwrt/packages#6479]
Description:
openwrt new install version is 18.06
rourter model :netgear r6220
problem : shadowsocks works failed
![1](https://user-images.githubusercontent.com/41245016/42731189-97a0ee22-883a-11e8-8734-b105baeb2a7d.png)
![2](https://user-images.githubusercontent.com/41245016/42731190-99ac9496-883a-11e8-8e60-45649f1de314.png)
can someone show me how to troubleshoot with it ? thanks for your help @yousong

**Comment by kevinqiu0098** [comment]
![Uploading 4.png…]()
@yousong  i try restart  shadowsocks but got nothing  it looks  didnt install right (btw i install from sofeware )

**Comment by kevinqiu0098** [comment]
@yousong 
first thanks for the reply it mean so much for me   
it's strange I can open google.com and get the search result page once(youtube twitter etc. cannot open) but now it looks like being block again 
does dns setting need additional setting ?
I am current live in china I am expecting local website visit directly and the block website just take the ss server

**Comment by yousong** [comment]
@kevinmehall , you may want to enable a ss_tunnel instance and point dhcp server to the local endpoint of the tunnel.

**Comment by kevinqiu0098** [comment]
sorry I am not quite familiar with openwrt, kindly check below 
![121](https://user-images.githubusercontent.com/41245016/42734606-70571c44-8879-11e8-87ef-7b577d971ba7.png)
instance won't enable correctly
and the red mark I dont konw what to do with it

**Comment by yousong** [comment]
Tunnel address can be `8.8.8.8:53`.  You can read an introduction to how each shadowsocks-libev component works at https://github.com/openwrt/packages/tree/master/net/shadowsocks-libev

**Comment by kevinqiu0098** [comment]
ss_tunnel instance still can not running back to the began...
it 's late thanks for your help

**Comment by yousong** [comment]
@kevinqiu0098 , any updates on this one?

**Comment by kevinqiu0098** [comment]
Nope ...back to beginning   I will figure another  Way thanks anyway

**Comment by yousong** [comment]
No problem.  I am closing this one for now.  Feel free to post here in case anything new pops up.
