### ISSUE TITLE
lxc-start: compile: network.c: instantiate_veth: 130 Failed to create veth pair "vethLTDK87" and "vethGUMB46": Not supported

### ISSUE THREAD

**Issue by alex9434** [openwrt/packages#6480]
OpewnWRT 18.06-RC1, x64

Working on getting network to lxc container.

1. Set-up standalone bridge under OpenWrt according to https://wiki.debian.org/LXC/SimpleBridge#Additonal_bridge_device_instead_of_changing_a_host_device_to_br0. Named new bridge lxcbr0

2. added the following lines to container config
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:46:82:35

3. Tried to start the container:
lxc-start -n compile -F
The configuration file contains legacy configuration keys.
Please update your configuration file!
lxc-start: compile: network.c: instantiate_veth: 130 Failed to create veth pair "vethLTDK87" and "vethGUMB46": Not supported
lxc-start: compile: network.c: lxc_create_network_priv: 2402 Failed to create network device
lxc-start: compile: start.c: lxc_spawn: 1206 Failed to create the network.
lxc-start: compile: start.c: __lxc_start: 1459 Failed to spawn container "compile".
lxc-start: compile: tools/lxc_start.c: main: 371 The container failed to start.
lxc-start: compile: tools/lxc_start.c: main: 375 Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by dibdot** [comment]
Please join the forum (see #6481)
