### ISSUE TITLE
lxc-stop: hangs when trying to stop ubuntu container

### ISSUE THREAD

**Issue by alex9434** [openwrt/packages#6481]
OpenWrt 18.06-rc1 on X64

I have created a ubuntu bionic amd64 container. When I try to stop the container, I get the following message:

sudo shutdown -h
System has not been booted with systemd as init system (PID 1). Can't operate.

When I exit the container and try to stop it with lxc-stop, lxc-stop never finishes. The container continues to run, as demonstrated by the process list (lxc-start -n containername -d is still in the list of processes)

**Comment by dibdot** [comment]
OpenWrt as a container host does not use systemd, therefore most probably some /sys directories/mounts are missing. Anyway, that's an configuration problem we can't solve within the package. Please ask in the forum for support: https://forum.lede-project.org
