### ISSUE TITLE
Privoxy - broken in recent OpenWrt builds

### ISSUE THREAD

**Issue by Aldaris1985** [openwrt/packages#6521]
There is an issue with the latest OpenWrt Version and Privoxy where the configs seem not to be pulled correctly. I am using David's OpenWrt build and the last version Privoxy is working correctly is r7093. There are some details here:

https://forum.lede-project.org/t/openwrt-snapshot-privoxy-error/15919

**Comment by dibdot** [comment]
this has been fixed with #6531
