### ISSUE TITLE
libprotobuf-c: Requires protobuf to build in v18.06.0-rc2 but dependency is broken

### ISSUE THREAD

**Issue by Per9** [openwrt/packages#6522]
Maintainer: @jsiverskog 
Environment: MediaTek Ralink MIPS, RT3662/RT3883, Asus RT-N56U, 18.06.0-rc2
Build environment: Debian 9.4, x86_64

Description:
I tried to add the OpenConnect server and got this error:
```
checking for protobuf >= 2.6.0... no
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

No package 'protobuf' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Makefile:67: recipe for target '/home/user/git/openwrt/build_dir/hostpkg/libprotobuf-c-v1.2.1/.configured' failed
make[3]: *** [/home/user/git/openwrt/build_dir/hostpkg/libprotobuf-c-v1.2.1/.configured] Error 1
make[3]: Leaving directory '/home/user/git/openwrt/feeds/packages/libs/protobuf-c'
Command exited with non-zero status 2
time: package/feeds/packages/protobuf-c/host-compile#7.62#0.48#11.76
package/Makefile:107: recipe for target 'package/feeds/packages/protobuf-c/host/compile' failed
make[2]: *** [package/feeds/packages/protobuf-c/host/compile] Error 2
make[2]: Leaving directory '/home/user/git/openwrt'
package/Makefile:103: recipe for target '/home/user/git/openwrt/staging_dir/target-mipsel_74kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/user/git/openwrt/staging_dir/target-mipsel_74kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/git/openwrt'
/home/user/git/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
```
It works after I selected the protobuf library manually and made sure libprotobuf-c was not selected. I could then reselect it and compile everything successfully.  Including protobuf made the firmware much larger, though.

A recent snapshot build has the same error here: https://downloads.lede-project.org/snapshots/faillogs/mips64_octeon/packages/ola/compile.txt

**Comment by neheb** [comment]
Looks related to https://github.com/openwrt/packages/issues/6031

**Comment by neheb** [comment]
This can be closed.

**Comment by predators46** [comment]
Eror build openwrt 18.06.4
configure: error: Package requirements (protobuf >= 2.6.0) were not met

**Comment by neheb** [comment]
I see the problem.

https://github.com/openwrt/packages/commit/983bd037030c8e3b90f297937d1f5fc460746285#diff-39318c270584a33d0c4751352d899978

Overrides the first.......

**Comment by neheb** [comment]
Fixed here: https://github.com/openwrt/packages/commit/340d5ce71ee60c1d699e7e0ead9422bed6f8519f

Please test again.

**Comment by predators46** [comment]
i have a new problem i made all ipk files using buildrot and there was an error

make[4]: Entering directory '/home/server/openwrt/build_dir/target-mips_24kc_musl/automake-1.15'
: && /bin/mkdir -p doc && { PATH='/home/server/openwrt/build_dir/target-mips_24kc_musl/automake-1.15/t/wrap:'$PATH && export PATH; } && /home/server/openwrt/staging_dir/host/bin/perl ./doc/help2man --output=doc/automake-1.15.1 automake-1.15
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
make[4]: *** [doc/automake-1.15.1] Error 255
make[4]: Leaving directory '/home/server/openwrt/build_dir/target-mips_24kc_musl/automake-1.15'
Makefile:65: recipe for target '/home/server/openwrt/build_dir/target-mips_24kc_musl/automake-1.15/.built' failed
make[3]: *** [/home/server/openwrt/build_dir/target-mips_24kc_musl/automake-1.15/.built] Error 2
make[3]: Leaving directory '/home/server/openwrt/feeds/packages/devel/automake'
time: package/feeds/packages/automake/compile#0.31#0.07#0.39
package/Makefile:107: recipe for target 'package/feeds/packages/automake/compile' failed
make[2]: *** [package/feeds/packages/automake/compile] Error 2
make[2]: Leaving directory '/home/server/openwrt'
package/Makefile:103: recipe for target '/home/server/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/server/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/server/openwrt'
/home/server/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by neheb** [comment]
Probably some cross-compile error with automake. Any specific reason why you're compiling automake?

**Comment by predators46** [comment]
I want to make all ipk files

Pada tanggal 2 Nov 2019 1:01 PM, "Rosen Penev" <notifications@github.com>
menulis:

**Comment by neheb** [comment]
Note that some are not available: https://downloads.openwrt.org/releases/faillogs-18.06/mips_24kc/packages/

**Comment by predators46** [comment]
Can the automake file be created? or maybe there can be explained clearly

Pada tanggal 2 Nov 2019 2:27 PM, "Rosen Penev" <notifications@github.com>
menulis:

**Comment by neheb** [comment]
You'd probably have to patch out the docs directory from being compiled.

**Comment by predators46** [comment]
thank you for replying everything and i will try it

Pada tanggal 2 Nov 2019 2:36 PM, "Rosen Penev" <notifications@github.com>
menulis:

**Comment by predators46** [comment]
can you give me advice?
how do I make openwrt so that when I do opkg update on the router my own
build can be used from the openwrt repo?
if you have a suggestion and it can I will not make all the ipk files
because it takes time and energy to complete, until I refuse my
girlfriend's invitation to go for the sake of making this ipk file. like my
post opkg_cmd ...... I have succeeded in making firwmaware openwrt but when
the opkg update and opkg install fail, opkg_cmd even the kernel does not
match and then I try to install it offline I take the ipk file in the
openwrt repo but the problem is still the same

Pada tanggal 2 Nov 2019 2:38 PM, "andy syam" <andysyam61@gmail.com> menulis:

**Comment by neheb** [comment]
...Don't refuse your girlfriend.

opkg update grabs files from URLs configured in /etc/opkg.conf .
