### ISSUE TITLE
syslog-ng fails on buildbots due to dependency issue

### ISSUE THREAD

**Issue by diizzyy** [openwrt/packages#6566]
http://downloads.lede-project.org/snapshots/faillogs/mips64_octeonplus/packages/syslog-ng/compile.txt

Pasted here in case it gets lost:

```
...
Package syslog-ng is missing dependencies for the following libraries:
libevtlog.so.0
```

@MikePetullo

**Comment by MikePetullo** [comment]
The package now uses its internal event log library. Is it possible that this is the same as issue #6523?

**Comment by diizzyy** [comment]
This might be is what makes it throw an error (./configure)?

```
EVTLOG_NO_LIBTOOL_LIBS="\$(top_builddir)/lib/eventlog/src/.libs/libevtlog.so"
```

**Comment by MikePetullo** [comment]
Please see https://github.com/openwrt/packages/pull/6601.

**Comment by diizzyy** [comment]
Fixed
