### ISSUE TITLE
ddns-scripts: sed error if the password contains a slash

### ISSUE THREAD

**Issue by patrakov** [openwrt/packages#6568]
Maintainer: @michallipka 
Environment: mvebu, LEDE 17.01.4 with ddns-scripts installed from 18.04 feed (because of Amazon Route 53 support)

Description: If the ddns password contains a slash, then each attempt to update the dynamic DNS produces errors such as this:

```
sed: bad option in substitution expression
```

This is caused by attempts to hide passwords from the logs, which end up running commands such as this:

```
... | sed "s/pass/word/*password*/g" | logger ...
```
So, passwords must be escaped before being turned into sed arguments.

This issue is especially important in the context of Route 53, because the secret keys (to be used as passwords) are generated by Amazon for you, and they almost always contain a slash.

**Comment by dibdot** [comment]
Should be fixed.
