### ISSUE TITLE
libwebsockets compile error with "TCP_USER_TIMEOUT" undefined

### ISSUE THREAD

**Issue by rhyttr** [openwrt/packages#6591]
Maintainer: @karlp 
Environment: 
mipsel, mt7688, openwrt 15.05
libwebsockets 3.0.0 stable

Description:

libwebsockets 3.0.0 compile error with: "TCP_USER_TIMEOUT" undefined
there was not defined "TCP_USER_TIMEOUT" in <netinet/tcp.h> header

here is the patch tested:
```
--- a/lib/plat/lws-plat-unix.c	2018-05-07 13:38:53.000000000 +0800
+++ b/lib/plat/lws-plat-unix.c	2018-07-27 12:01:20.115515000 +0800
@@ -351,6 +351,9 @@
 		/* set the keepalive conditions we want on it too */
 
 #if defined(LWS_HAVE_TCP_USER_TIMEOUT)
+	#ifndef TCP_USER_TIMEOUT
+	#define TCP_USER_TIMEOUT	18	/* How long for loss retry before timeout */
+	#endif
 		optval = 1000 * (vhost->ka_time +
 				 (vhost->ka_interval * vhost->ka_probes));
 		if (setsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT,
```
Is there any other good solution?

**Comment by karlp** [comment]
and is it a problem with 17.01, 1806 or master?  I'm not patching 15.05.

**Comment by diizzyy** [comment]
@karlp 
Close due to timeout?

**Comment by karlp** [comment]
works for me.
