### ISSUE TITLE
nfs-kernel-server compile error

### ISSUE THREAD

**Issue by nouman8** [openwrt/packages#6592]
i reported this error here https://bugs.openwrt.org/index.php?do=details&task_id=1694

**Comment by dibdot** [comment]
Fix b1be3f9 your issue? Please retest with a current snapshot - thanks

**Comment by nouman8** [comment]
that commit fixed it.
Thanks.

**Comment by dibdot** [comment]
@nouman8 That's great - please be so kind and set the above referenced master ticket to resolved as well. Thanks.

**Comment by nouman8** [comment]
Done.
