### ISSUE TITLE
midnight commander (mc) 4.8.20 openwrt 18.06.0-rc2 - mouse control doesnt work at all

### ISSUE THREAD

**Issue by tojestzart** [openwrt/packages#6599]
at lede 17.01 does

mc_4.8.18-1_mipsel_24kc.ipk | 363.5 KB | Sat Jul 21 00:11:23 2018
-- | -- | --

**Comment by dibdot** [comment]
This is intentionally disabled to save space.

**Comment by tojestzart** [comment]
@dibdot  funny, routers growing with ram and flash year by year, and you reducing package features , package which is not even in base (required to work openwrt)
