### ISSUE TITLE
6rd - feature request - support subnet

### ISSUE THREAD

**Issue by Arduous** [openwrt/packages#6630]
Hello,

Depending on the providers deploying 6rd, there might be some subnet id bits available to the user if all of the first 64 bits of the IPv6 are not used. 

In the example below 64 - 28 - 32 = 4 bits are available to define subnets so the end user can use any network prefix from 2a02:1205:5050:7ab0:: to 2a02:1205:5050:7abf::

![image](https://user-images.githubusercontent.com/115884/43468177-a2918890-94e3-11e8-9f90-b2d33521763f.png)

Currently the lowest prefix is chosen by default, without opportunity to specify the subnet. 

The feature would add a new "subnet" field to 6rd, available through UCI and the UI. Appropriate checks are performed regarding the maximum value of the field given the constraints given by the ip6prefixlen and ip4prefixlen.

**Comment by hnyman** [comment]
6rd is in the main Openwrt, not here in the packages feed.
