### ISSUE TITLE
miniupnpd: aMule fails to open ports through upnp in OpenWrt 18.06

### ISSUE THREAD

**Issue by BUG-reporter** [openwrt/packages#6631]
**Environment**:
arch: Atheros AR9132 rev 2
model: TP-Link TL-WR1043N/ND v1
OpenWrt: 18.06

**Description**:
After upgrading to 18.04 and installing luci-upnp package I found aMule fails to open ports through upnp. In both previous version there was no problems with opening ports.

For any additional info, please, ask.

**Comment by tchakabum** [comment]
have you tried enabling IGDv1?

**Comment by BUG-reporter** [comment]
> have you tried enabling IGDv1?
Yes, I've tried but it didn't helped.

**Comment by no1dea** [comment]
I'm having the same problem with miniupnp on 18.06. My Router is an TP-Link TL-WDR4900 v1.

The kernel log just says:

[  998.421261] miniupnpd[7770]: unhandled signal 11 at 00000000 nip b7d88400 lr 1000a780 code 30001
[  998.558272] miniupnpd[7781]: unhandled signal 11 at 00000000 nip b7b76400 lr 1000a780 code 30001
[ 1000.212992] miniupnpd[7800]: unhandled signal 11 at 00000000 nip b77d7400 lr 1000a780 code 30001

my config looks like this:

`
config upnpd 'config'
	option external_iface 'wan'
	option internal_iface 'lan'
	option port '5000'
	option upnp_lease_file '/var/upnp.leases'
	option uuid '56a271dc-248c-4926-98ef-4518546d3d59'
	option enabled '1'
	option download '300000'
	option upload '30000'
	option igdv1 '1'

config perm_rule
	option action 'allow'
	option ext_ports '1024-65535'
	option int_addr '0.0.0.0/0'
	option int_ports '1024-65535'
	option comment 'Allow high ports'
`

**Comment by neheb** [comment]
Please test the referenced pull request to see if it fixes your issue.

**Comment by no1dea** [comment]
Tested  #6674 

With miniupnpd updated to 2.1.20180706-1 the kernel log still says

[   46.663532] miniupnpd[3296]: unhandled signal 11 at 00000000 nip b7a87400 lr 10012a48 code 30001

**Comment by neheb** [comment]
I force pushed a new commit that has a new workaround. It uses -O2 vs. Os. This was an issue with dropbear where the transition from GCC5 to GCC7 made it miscompile with Os but where it was fine with O2.

LEDE 17.01.x uses GCC5.

**Comment by no1dea** [comment]
thank you @neheb that last commit fixed the issue.
