### ISSUE TITLE
adblock: missing button text

### ISSUE THREAD

**Issue by facled** [openwrt/packages#6703]
how you can see, sometimes i dont see text from both buttons.

Architecture ARMv7 Processor rev 1 (v7l)
Firmware Version OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.216.65174-3d5d9dc)
Kernel Version 4.14.54
adblock 3.5.4-2	
luci-app-adblock git-18.216.65174-3d5d9dc-1

![c699541c-ff84-4913-9863-e752ebe3d5a6](https://user-images.githubusercontent.com/23004217/43777094-18e7a3d0-9a52-11e8-8ee6-1cc744967fbe.png)

**Comment by dibdot** [comment]
Yep, that's a known bug - after the first run you see the buttons, right?

**Comment by dibdot** [comment]
I've looked into it and the bug should already be fixed in 18.06 tree as well. Please reset your luci caches (rm -rf /tmp/luci-*) and check again.

**Comment by dibdot** [comment]
@facled does the cache reset help regarding your issues (#6703, #6704)?

**Comment by dibdot** [comment]
not reproducible, no more user feedback - close this for now.
