### ISSUE TITLE
adblock: empty view logfile

### ISSUE THREAD

**Issue by facled** [openwrt/packages#6704]
on adblock -> View Logfile i see every time nothing. only empty
option adb_debug is 1

Architecture ARMv7 Processor rev 1 (v7l)
Firmware Version OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.216.65174-3d5d9dc)
Kernel Version 4.14.54
adblock 3.5.4-2
luci-app-adblock git-18.216.65174-3d5d9dc-1

**Comment by dibdot** [comment]
Please provide the output of `logread -e "adblock-"`

**Comment by dibdot** [comment]
not reproducible, no more user feedback - close this for now.
