### ISSUE TITLE
python-dateutil: remove Python 2.x dependency or build a 3.x version

### ISSUE THREAD

**Issue by chris5560** [openwrt/packages#6741]
@kissg1988 
Please remove Python 2.x dependency or build a 3.x version because also used/needed for Python 3.x based software. Looking on "dateutil" project-page https://pypi.org/project/python-dateutil/ it's also supported for Python 3.3 to 3.7.
I.e. Radicale CalDAV/CardDAV-Server 2.x is using it on Python 3.x
Many thanks

**Comment by kissg1988** [comment]
@chris5560 
Unfortunately, I'm not actively maintaining my packages anymore but feel free to make the changes if you have the time and knowledge to do so. I'm happy to review and approve your changes.

As a quick hint, I'd use b61864cdce3bd18388f8b010b5c8d24932a2729a as a template to create a python3 version of the package. Feel free to add yourself as a second maintainer if you wish.

Thanks,
Gergely

**Comment by jefferyto** [comment]
With #7899 merged, this can probably be closed as well.

@chris5560 you may be interested in #7871 (I'm not really involved though)

**Comment by commodo** [comment]
i also agree to close this

@hnyman 
thoughts ?
shall we close this after a given timeout ?
