### ISSUE TITLE
luci-app-openvpn : comp-lzo not working, compress lzo needed

### ISSUE THREAD

**Issue by adverserath** [openwrt/packages#6750]
I may have used far to many hours getting my router into a vpn.
The UI for luci-app-openvpn only allows comp-lzo flags to be set. When the server is started up the config writes out into /var/etc/xxxx.conf
if there is a flag for comp-lzo in the openvpn config (etc/config/openvpn) file this does not get reflected in the used config file.
My fix was to manually add "compress lzo" into etc/config/openvpn, which did write out into the used config file. The UI doesnt have an option for the compress flag, as such no values are shown.

**Comment by gabbe** [comment]
Thank you for submitting this workaround, I also spent too much time getting this to work. 
Even though it would be nice to be able to set option "compress" from Luci, I guess the real question is why the option "comp-lzo" is not passed to the openvpn-service.

**Comment by dartraiden** [comment]
> if there is a flag for comp-lzo in the openvpn config (etc/config/openvpn) file this does not get reflected in the used config file

Yes, comp-lzo is deprecated in OpenVPN and removed from OpenWrt
https://github.com/openwrt/openwrt/commit/89b8ba96b404d2e412d5573e25348287255671dd#diff-37e75a0201711d64802dc863bc6019f5

**Comment by diizzyy** [comment]
Neither OpenVPN or luci-app-openvpn are in this repo, closing

**Comment by yousong** [comment]
For archive purposes, the issue was by openwrt/openwrt@3850b41f01925a7eddc24033ed155503c1ad2112 and backported to openwrt-18.06 branch.
