### ISSUE TITLE
stubby: integrate with uci

### ISSUE THREAD

**Issue by jonathanunderwood** [openwrt/packages#6787]
Maintainer: @iamperson347
Environment: OpenWRT 18.06.0

Description:
At present, stubby has no uci integration, which makes it difficult to integrate with Luci. It would be great if the stubby package gained uci integration.

**Comment by EricLuehrsen** [comment]
That would not be much to add but not advised. Again Stubby is a reference example of GetDNS and experimental. It has no persistent cache, so resolving each full DNSSEC chain is a continuous burden. If down stream clients are DNSSEC aware or validating, then the load can balloon. If DNSSEC is desired, then consider alternate package `dnsmasq-full` with switch enabled, and use Stubby merely as TLS tunnel. (If more work goes into Stubby, then maybe some day it could replace the DNS half of dnsmasq.)

**Comment by jonathanunderwood** [comment]
I think with stubby doing dnssec, and dnsmasq option dnssec-proxy set, you get the caching by dnsmasq, and Stubby validating. Empirically, this seems to perform better than having dnsmasq do the dnssec validation.

**Comment by jonathanunderwood** [comment]
PR #7122  submitted implementing UCI integration.

**Comment by jonathanunderwood** [comment]
Closing now that #7122 has been merged.

**Comment by spookyUnknownUser** [comment]
This might be quite stupid on my part so maybe I missed something, but when I try and run stubby without the `yml` config, so with manual `0` - stubby doesn't seem to see the UCI configuration file and prints `WARNING: No Stubby config file found... using minimal default config (Opportunistic Usage)` when I start it for the first time.

If I see this message does it mean stubby is actually using the UCI configuration file in `/etc/config/stubby`?

**Comment by jonathanunderwood** [comment]
> This might be quite stupid on my part so maybe I missed something, but when I try and run stubby without the `yml` config, so `with manual '0'` - stubby doesn't seem to see the UCI configuration file and prints `WARNING: No Stubby config file found... using minimal default config (Opportunistic Usage)` when I start it for the first time.
> 

I can't reproduce this.

Please see the README.md for more details.

When `manual` is 0, the UCI config file will be used at startup to create a `stubby.yml` file under `/var/etc/stubby`.

When  `manual` is 1, the UCI config is ignored, and `/etc/stubby/stubby.yml` is used for con figuration.

> If I see this message does it mean stubby is actually using the UCI configuration file in `/etc/config/stubby`?
> 
> This is probably a different issue but I noticed stubby overwrote my `etc/stubby/` directory and `/etc/config/stubby` files on install. Wasn't expecting this so luckily I had backups.

If you created those, and then installed stubby, I am not surprised they were overwritten - I don't think opkg has the smarts to deal with that situation, which is a weird corner case.

**Comment by jonathanunderwood** [comment]
Also: please don't continue discussion on closed Issues. Instead, if you have a genuine issue (rather than a support question), please open a new issue.
