### ISSUE TITLE
Update motion 4.1.1

### ISSUE THREAD

**Issue by tapper82** [openwrt/packages#6830]
Hi update motion to 4.1.1
https://github.com/Motion-Project/motion/releases

**Comment by tapper82** [comment]
The build in packages now is a old one from Aug 14, 2016.

**Comment by dibdot** [comment]
Please always inform the package maintainer (@roger- ) and/or provide a PR on your own.

**Comment by tapper82** [comment]
Ok I will next time. Thanks for the heads up.

**Comment by neheb** [comment]
This can be closed.

**Comment by thess** [comment]
OK: https://github.com/openwrt/packages/commit/95cce73642591c708c6553a397b7cd418dce4ac3
