### ISSUE TITLE
v4l-utils update to 1.14.1 

### ISSUE THREAD

**Issue by tapper82** [openwrt/packages#6831]
The package is now at Jun 15, 2016  
v4l-utils-1.10.1 
The latest is:
on Dec 27, 2017  
v4l-utils-1.14.1

**Comment by dibdot** [comment]
@thess

**Comment by thess** [comment]
Updated to 1.14.2 and added the RDS and CED components.
Ref: https://github.com/openwrt/packages/commit/b2b44c9f3e673a23868eea62bd10816d6746ff33
