### ISSUE TITLE
kmod-brcm-wl, wl, nas and wlc package is not available in bcm53xx

### ISSUE THREAD

**Issue by RussianNeuroMancer** [openwrt/packages#6858]
Maintainer: @KanjiMonster 
Environment:  bcm53xx, Asus RT-AC56U, OpenWrt 18.06.1

Description:

kmod-brcm-wl, wl, nas and wlc package is not available in bcm53xx. If possible, please build this packages for bcm53xx target too.

**Comment by jow-** [comment]
It is not possible as we only have access to precompiled MIPS binaries.

**Comment by RussianNeuroMancer** [comment]
@jow- It's impossible to use binaries from asuswrt image builder published by ASUS?

**Comment by jow-** [comment]
Yes, unfortunately this is not possible. These binaries require specific, immutable kernel abis.
