### ISSUE TITLE
Adblock: Disable yoyo as it now blocks Google analytics, etc.

### ISSUE THREAD

**Issue by rasa** [openwrt/packages#6865]
https://github.com/openwrt/packages/blob/0194bf7d07563d707d3669d4970badb4f790850f/net/adblock/files/adblock.conf#L199

**Comment by dibdot** [comment]
Huh? That's the main purpose of adblock to block one of the main ad/tracking sites in the net ...

**Comment by rasa** [comment]
Understood, but it's blocking analytics.google.com, which is the admin backend, not the googleadservices.com tracking site.

**Comment by janusqa** [comment]
Was there a solution for this?
How can i access the analytics.google.com interface.

**Comment by rasa** [comment]
@dibdot Please reopen, as it is blocking analytics.google.com when it shouldn't. Thx.

**Comment by rasa** [comment]
So yoyo still blocks analytics.google.com per
https://pgl.yoyo.org/as/details.php?hostname=analytics.google.com
To disable yoyo, type:
```sh
uci del_list adblock.global.adb_sources=yoyo
uci commit
/etc/init.d/adblock restart
```
