### ISSUE TITLE
miniupnpd security issue

### ISSUE THREAD

**Issue by axet** [openwrt/packages#6867]
Maintainer: @ldir-EDB0 

Hello! By default miniupnpd listening for 'lan' interface. But for routers configured to use IPv6 it can be a security issue to allow guests from IPv6 help us setup our port mapping.

Seems like default config has perm_rule with int_addr '0.0.0.0/0', restricting this mask to local network will help to prevent guests to change local port mapping, but it keep 5000 port open to the everyone from ipv6, and it is completely useless for miniupnpd to listen for ipv6 which help port mapping for ipv4 puposes. And miniupnpd crashing a lot on my router, I guess this is the reason (some one DoS'ing it)

Unfortunately, it is not possible to force miniupnpd to listen for ipv4 only due to some strange error configuring 'listening_ip' to specific IP (with or without mask not work):

    Error: please specify LAN network interface by name instead of IPv4 address : 192.168.0.1
    can't parse "192.168.0.1/24" as a valid interface name

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.conf

Config saying we can configure 'listening_ip' to point to the actual ip. But in won't work.

It can be due to some changes to the source code?

It is possible to update /etc/init.d/miniupnpd 

'network_get_device' -> 'network_get_subnet'

                local iface                                                  
                for iface in ${intiface:-lan}; do                        
                        local device                           
                        network_get_subnet device "$iface" && {             
                                echo "listening_ip=$device" >>$tmpconf
                        }                         
                done  

Which is not going to work, due to error above.

Also it is possible to automatically fill up proper local network and mask for int_addr;

Another idea is to setup proper 'ipv6_listening_ip' based on local node ipv6 address of the interface fe80:: prefix. Not sure how to get those..

**Comment by ffrediani** [comment]
@axet the fact the OpenWrt device has a IPv6 address in the LAN doesn't mean it is exposed and opened to the public internet and is a security issue. In OpenWrt the default behaviour for IPv6 incoming connections is deny and that is a correct behaviour.

So the fact a device in your LAN has an IPv6 address it doesn't mean it is exposed to the Internet nor the miniupnpd listening on the LAN Interface.

It actually has to listen on both IPv4 and IPv6 so it is possible to make PCP (Port Control Protocol) requests to allow traffic to be forwarded to internal IPv6 applications running in the LAN in a similar way it is done with NAT Port Forward.
