### ISSUE TITLE
nfs broken after switch to libtirpc

### ISSUE THREAD

**Issue by nouman8** [openwrt/packages#6871]
im getting timed out error when i try to mount nfs share
on client running rpcinfo gives
`rpcinfo -p 192.168.1.1
192.168.1.1: RPC: Remote system error - Connection refused.`
while on router eveything seems ok.
`root@OpenWrt:~# cat /etc/exports `
`/mnt	*(rw,async)`
`root@OpenWrt:~# /etc/init.d/nfsd restart`
`exportfs: /etc/exports [1]: Neither 'subtree_check' or 'no_subtree_check' specified for` `export "*:/mnt".`
`  Assuming default behaviour ('no_subtree_check').`
`  NOTE: this default has changed since nfs-utils version 1.0.x`

root@OpenWrt:~# ps
  PID USER       VSZ STAT COMMAND
    1 root      1532 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    4 root         0 SW   [kworker/0:0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW<  [lru-add-drain]
    8 root         0 SW   [kworker/u2:1]
   31 root         0 SW   [oom_reaper]
   49 root         0 SW   [kworker/u2:2]
   72 root         0 SW<  [writeback]
   74 root         0 SW<  [crypto]
   75 root         0 SW<  [bioset]
   77 root         0 SW<  [kblockd]
  100 root         0 SW   [kworker/0:1]
  107 root         0 SW   [kswapd0]
  156 root         0 SW   [kworker/u2:3]
  166 root         0 SW   [spi0]
  185 root         0 SW<  [bioset]
  191 root         0 SW<  [bioset]
  197 root         0 SW<  [bioset]
  198 root         0 SW<  [bioset]
  206 root         0 SW<  [bioset]
  212 root         0 SW<  [bioset]
  302 root         0 SW<  [kworker/0:1H]
  343 root         0 SW   [kworker/0:2]
  371 root         0 SW   [scsi_eh_0]
  373 root         0 SW<  [scsi_tmf_0]
  374 root         0 SW   [usb-storage]
  391 root         0 SW<  [bioset]
  395 root         0 SW<  [bioset]
  422 root         0 SWN  [jffs2_gcd_mtd3]
  488 root      1184 S    /sbin/ubusd
  489 root       900 S    /sbin/askfirst /usr/libexec/login.sh
  521 root         0 SW<  [rpciod]
  523 root         0 SW<  [xprtiod]
  529 root         0 SW<  [nfsiod]
  538 root         0 SW<  [cfg80211]
  699 rpc       1236 S    /usr/sbin/rpcbind -f -w
  735 root      1644 S    /sbin/netifd
  754 root         0 SW   [jbd2/sda2-8]
  756 root         0 SW<  [ext4-rsv-conver]
  796 root      1044 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
  825 root       904 S    /usr/bin/hd-idle -d -i 0 -a sda -i 180
  954 root      1184 S<   /usr/sbin/ntpd -n -N -S /usr/sbin/ntpd-hotplug -p 0.
 1016 root         0 SW   [lockd]
 1017 root         0 SW   [nfsd]
 1018 root         0 SW   [nfsd]
 1019 root         0 SW   [nfsd]
 1020 root         0 SW   [nfsd]
 1021 root         0 SW   [nfsd]
 1022 root         0 SW   [nfsd]
 1023 root         0 SW   [nfsd]
 1024 root         0 SW   [nfsd]
 1047 root      1692 S    /usr/sbin/rpc.statd -p 32778 -o 32779 -F
 1048 root      1952 S    /usr/sbin/rpc.mountd -p 32780 -F
 1132 root      1680 S    /usr/sbin/hostapd -s -P /var/run/wifi-phy0.pid -B /v
 1211 dnsmasq   1312 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c
 1250 root      1112 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
 1251 root      1192 S    -ash
 1259 root      1184 R    ps

**Comment by Andy2244** [comment]
Need to setup nfs myself first, but can you try without firewall enabled, just to-be sure.

**Comment by nouman8** [comment]
following is the output of rpcinfo on router and i didn't compile with firewall either.
program version netid     address                service    owner
    100000    4    local     /var/run/rpcbind.sock  -          superuser
    100000    3    local     /var/run/rpcbind.sock  -          superuser
    100003    3    tcp       0.0.0.0.8.1            -          superuser
    100021    1    udp       0.0.0.0.128.9          -          superuser
    100021    3    udp       0.0.0.0.128.9          -          superuser
    100021    4    udp       0.0.0.0.128.9          -          superuser
    100021    1    tcp       0.0.0.0.128.9          -          superuser
    100021    3    tcp       0.0.0.0.128.9          -          superuser
    100021    4    tcp       0.0.0.0.128.9          -          superuser
    100024    1    udp       0.0.0.0.128.10         -          superuser
    100005    1    udp       0.0.0.0.128.12         -          superuser
    100024    1    tcp       0.0.0.0.128.10         -          superuser
    100005    1    tcp       0.0.0.0.128.12         -          superuser
    100005    2    udp       0.0.0.0.128.12         -          superuser
    100005    2    tcp       0.0.0.0.128.12         -          superuser
    100005    3    udp       0.0.0.0.128.12         -          superuser
    100005    3    tcp       0.0.0.0.128.12         -          superuser

**Comment by nouman8** [comment]
the following link is the .config file from my openwrt build folder maybe im missing some package [https://pastebin.com/UwrYZg9L](url)

**Comment by Andy2244** [comment]
Can you paste the output of `cat /etc/services`?

**Comment by nouman8** [comment]
output of cat /etc/services.
https://pastebin.com/6CwWW6bq

**Comment by Andy2244** [comment]
try change those lines to:
```
sunrpc		111/tcp		rpcbind
sunrpc		111/udp		rpcbind
```

**Comment by nouman8** [comment]
already restarted rpcbind multiple times but no luck + i have unchecked multiple packages in the configuration file posted above like ipv6,firewall lots of other,maybe some necessary configuration was unchecked while trimming down...plz have a look at config file.

**Comment by Andy2244** [comment]
Did you edit the `/etc/services` file on the router as described above? I might have forgotten this manual change and it slipped through the PR.

There should be entries for port 111 on the router, yet i don't see any.
```
rpcinfo -p
   program vers proto   port  service
    100000    4   tcp    111
    100000    3   tcp    111
    100000    2   tcp    111
    100000    4   udp    111
    100000    3   udp    111
    100000    2   udp    111
```

**Comment by nouman8** [comment]
i just edited that file.. now output of rpcinfo -p is same as you posted above
program vers proto   port  service
    100000    4   tcp    111
    100000    3   tcp    111
    100000    2   tcp    111
    100000    4   udp    111
    100000    3   udp    111
    100000    2   udp    111

**Comment by nouman8** [comment]
i can now mount nfs share successfully after editing that file as you told.

**Comment by Andy2244** [comment]
Ah glad this worked, seems rpcinfo is using the alias, instead of hard-coding the port. I had this change on my test system, but seems i forget to add this to the PR. 😞

**Comment by nouman8** [comment]
Thanks a lot . been searching solution of it for the past few days.

**Comment by tripolar** [comment]
i don't want to be unpolite but this is not the rpcbind bugtracker. and it's no bug - here is the commit that changed this ( http://git.linux-nfs.org/?p=steved/rpcbind.git;a=commit;h=2e9c289246c647e25649914bdb0d9400c66f486e ) and only allows localhost connections if it's not enabled explicitly with --enable-rmtcalls at configure time (i think this shouldn't be enabled)
