### ISSUE TITLE
nginx failure with ipv6 disabled

### ISSUE THREAD

**Issue by lucize** [openwrt/packages#6905]
@Ansuel 
compiled a x86 target with nginx-luci support, but disabled ipv6 globally, the service will fail with
`nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)`
I see in default config  `listen [::]:80 default_server;` is there a way to prevent this if ipv6 is not selected ?
do we need ipv6 support by default ?

**Comment by neheb** [comment]
Is this still an issue?

**Comment by lucize** [comment]
still, disable ipv6 overall an nginx will not start

**Comment by neheb** [comment]
Can you post an strace log?

**Comment by peter-stadler** [comment]
I think this is a configuration issue (removing the `listen [::] …` solves it, right?) I am on the way changing the default configuration (see #11081) to make it easier extensible and want to address also this.

**Comment by lucize** [comment]
Yes, just a config, I think is useless to listen on ipv6 by default, who want it should set it
