### ISSUE TITLE
swig: how to build the .ipk file of swig?

### ISSUE THREAD

**Issue by Grassboy** [openwrt/packages#6914]
Maintainer: @nxhack
Environment:  CHAOS CALMER (15.05.1, r48749) in MediaTek LinkIt MT7688

Description:
I am trying to run swig in my MT7688 board...
But I don't know if there is a swig.ipk package file.
So... Can you give me some advise for cross-compileing swig's source code in Ubuntu?
Thankyou!!

**Comment by nxhack** [comment]
Hi @Grassboy 

CC is no longer supported.

If you are interested, please look at the wiki pge that I am working on.
https://github.com/nxhack/openwrt-node-packages/wiki
