### ISSUE TITLE
packages: Update README Buildroot-Installation links?

### ISSUE THREAD

**Issue by jimt** [openwrt/packages#6918]
The README.md file still contains links to the old wiki.

Should it be updated?

|Text           | old  | new |
|---------------|------|-------|
|OpenWrt SDK | http://wiki.openwrt.org/doc/howto/obtain.firmware.sdk | https://openwrt.org/docs/guide-developer/obtain.firmware.sdk |
|OpenWrt Buildroot – Installation| http://wiki.openwrt.org/doc/howto/buildroot.exigence | https://openwrt.org/docs/guide-developer/build-system/install-buildsystem |

**Comment by thess** [comment]
Done via https://github.com/openwrt/packages/commit/160bf84ab96e85c3e8b3997ebb08e801a8124e0a
Thanks.
