### ISSUE TITLE
php intl modle compile error 

### ISSUE THREAD

**Issue by andsontan** [openwrt/packages#6943]
Please make sure that the issue subject starts with `<package-name>: `

This repo here is only for packages maintained in this repo.  For base packages residing in the same repo as the build system and maintained by core devs, please consider opening tickets there for more timely responses

 - OpenWrt base system: https://bugs.openwrt.org
 - Most LuCI packages: https://github.com/openwrt/luci/issues

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

**Open wrt version: OpenWrt Chaos Calmer 15.05.1**

/bin/sh /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/libtool --silent --preserve-dup-deps --mode=install cp ext/iconv/iconv.la /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/modules
/bin/sh /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/libtool --silent --preserve-dup-deps --mode=compile ccache_cc -I/usr/include  -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/intl/ -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/intl/ -DPHP_ATOM_INC -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/main -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9 -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/date/lib -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/include/libxml2 -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/include/freetype2/freetype2 -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/include/freetype2 -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libintl-full/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libiconv-stub/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/mbstring/oniguruma -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/mbstring/libmbfl -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/mbstring/libmbfl/mbfl -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/zip/lib -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/TSRM -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/Zend  -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/toolchain-aarch64_cortex-a53+neon_gcc-4.9-linaro_glibc-2.19/usr/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/toolchain-aarch64_cortex-a53+neon_gcc-4.9-linaro_glibc-2.19/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libiconv-stub/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libintl-stub/include  -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libiconv-stub/include -Os -pipe -fno-caller-saves -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libiconv-stub/include -I/home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/libintl-stub/include -fvisibility=hidden -DZEND_SIGNALS    -c /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/intl/php_intl.c -o ext/intl/php_intl.lo 
In file included from /usr/include/features.h:399:0,
                 from /usr/include/stdlib.h:24,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/include/../main/php_config.h:2573,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/Zend/zend_config.h:1,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/Zend/zend_portability.h:45,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/Zend/zend_types.h:27,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/Zend/zend.h:29,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/main/php.h:35,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/intl/php_intl.h:23,
                 from /home/tgm/rtk/NorFlash/1st/NVR_18_sw_root/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/php-7.2.9/ext/intl/php_intl.c:25:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>

**Comment by dibdot** [comment]
This release is several years old & unsupported. Please update to 17.01 or latest 18.06.
