### ISSUE TITLE
mpd-full: missing in mips_mips32

### ISSUE THREAD

**Issue by 2e0byo** [openwrt/packages#6987]
Maintainer: @\thess 
Environment: mips_mips32/brcm63xx 18.06

Description:  Package doesn't seem to be available as per https://forum.openwrt.org/t/mpd-package-gone-in-18-06/20902

Any chance someone could look at why it's failing?

**Comment by thess** [comment]
Target builds are fixed. However, MPD cannot be built due to a platform problem building the **boost** libraries. See #7000

**Comment by 2e0byo** [comment]
thanks.  I'll watch that bug and see if it gets fixed.

**Comment by thess** [comment]
Closed via #7067

**Comment by thess** [comment]
Not fixed... see #7000

**Comment by thess** [comment]
Finally closed by #7100 on trunk. Soon to be in 18.06
