### ISSUE TITLE
ntpdate: failed to build

### ISSUE THREAD

**Issue by erdoukki** [openwrt/packages#699]
Package ntpdate is missing dependencies for the following libraries:
libcrypto.so.1.0.0
libpthread.so.0

**Comment by annbigbig** [comment]
I have the same problem , so how to fix it ???

**Comment by annbigbig** [comment]
install -d -m0755 /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ipkg-ar71xx/ntpdate/usr/sbin
install -m0755 /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ntpdate/ntpdate /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ipkg-ar71xx/ntpdate/usr/sbin/
install -d -m0755 /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ipkg-ar71xx/ntpdate/etc/init.d
install -m0755 ./files/ntpdate.init /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ipkg-ar71xx/ntpdate/etc/init.d/ntpdate
find /home/anntony/openwrt/trunk/build_dir/target-mips_34kc_uClibc-0.9.33.2/ntp-4.2.8/ipkg-ar71xx/ntpdate -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package ntpdate is missing dependencies for the following libraries:
libcrypto.so.1.0.0
libpthread.so.0
make[3]: *** [/home/anntony/openwrt/trunk/bin/ar71xx/packages/packages/ntpdate_4.2.8-1_ar71xx.ipk] Error 1
make[3]: Leaving directory `/home/anntony/openwrt/trunk/feeds/packages/net/ntpd'
make[2]: *** [package/feeds/packages/ntpd/compile] Error 2
make[2]: Leaving directory `/home/anntony/openwrt/trunk'
make[1]: *** [/home/anntony/openwrt/trunk/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/anntony/openwrt/trunk'
make: *** [world] Error 2
anntony@anntony-Lenovo-B590 ~/openwrt/trunk $

**Comment by thess** [comment]
See PR #747 -- waiting for maintainer (@tripolar) review

**Comment by annbigbig** [comment]
I tried the way you mod here a day ago
https://github.com/thess/OpenWrt-packages/commit/50b5fe2e46c82987594dda3d4e206cd184826a43
and I finally got the openwrt-ar71xx-generic-tl-wr841n-v8-squashfs-factory.bin successfully compiled in trunk/bin/ar71xx/ subdirectory , thank you very much for solving this problem ! :)

**Comment by annbigbig** [comment]
it was so fresh ya XD

anntony@anntony-Lenovo-B590 ~/openwrt/trunk/bin/ar71xx $ ls -al|grep 841
-rw-r--r-- 1 anntony anntony 16515072  1月  8 01:49 openwrt-ar71xx-generic-tl-wr841n-v8-squashfs-factory.bin
-rw-r--r-- 1 anntony anntony  6619140  1月  8 01:49 openwrt-ar71xx-generic-tl-wr841n-v8-squashfs-sysupgrade.bin
anntony@anntony-Lenovo-B590 ~/openwrt/trunk/bin/ar71xx $

**Comment by yeewang** [comment]
Please fix it. I how to skip this module now.

**Comment by tripolar** [comment]
should be fixed with https://github.com/openwrt/packages/commit/99aad1438a032aaa3d74137abe24d5641e181219
