### ISSUE TITLE
luai2c fails to build on fresh 17.01.x build

### ISSUE THREAD

**Issue by JasonChalmers** [openwrt/packages#6994]
when building with make -j1 V=scw I get the following issue.

make[3]: Entering directory '/home/wrt/openwrt/feeds/packages/lang/luai2c'
mkdir -p /home/wrt/openwrt/dl
SHELL= flock /home/wrt/openwrt/tmp/.luai2c-1.0.0.tar.xz.flock -c ' echo "Checking out files from the git repository..."; mkdir -p /home/wrt/openwrt/tmp/dl && cd /home/wrt/openwrt/tmp/dl && rm -rf luai2c-1.0.0 && [ ! -d luai2c-1.0.0 ] && git clone https://github.com/mrpace2/i2c-lua.git luai2c-1.0.0 && (cd luai2c-1.0.0 && git checkout 1.0.0 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=cd luai2c-1.0.0 && git log -1 --format='\''@%ct'\'' && rm -rf luai2c-1.0.0/.git && tar --numeric-owner --owner=0 --group=0 --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c luai2c-1.0.0 | xz -zc -7e > /home/wrt/openwrt/tmp/dl/luai2c-1.0.0.tar.xz && mv /home/wrt/openwrt/tmp/dl/luai2c-1.0.0.tar.xz /home/wrt/openwrt/dl/ && rm -rf luai2c-1.0.0; '
Checking out files from the git repository...
Cloning into 'luai2c-1.0.0'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/mrpace2/i2c-lua.git/'
Makefile:45: recipe for target '/home/wrt/openwrt/dl/luai2c-1.0.0.tar.xz' failed
make[3]: *** [/home/wrt/openwrt/dl/luai2c-1.0.0.tar.xz] Error 128
make[3]: Leaving directory '/home/wrt/openwrt/feeds/packages/lang/luai2c'
package/Makefile:105: recipe for target 'package/feeds/packages/luai2c/compile' failed
make[2]: *** [package/feeds/packages/luai2c/compile] Error 2
make[2]: Leaving directory '/home/wrt/openwrt'
package/Makefile:101: recipe for target '/home/wrt/openwrt/staging_dir/target-mips_mips32_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/home/wrt/openwrt/staging_dir/target-mips_mips32_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wrt/openwrt'
/home/wrt/openwrt/include/toplevel.mk:205: recipe for target 'world' failed
make: *** [world] Error 2

The repo at github does not exist any more

**Comment by karlp** [comment]
https://github.com/robbie-cao/i2c-lua might be the same, you can try fixing the makefile for that.  The readme at the bottom still refers to mrpace2, so... *shrugs*

Only other option is one of the alternative libraries, and repackaging them, or finding someone who still has a downloaded tarball.

**Comment by ahmadrasyidsalim** [comment]
See : https://github.com/openwrt/packages/issues/3040#issue-170167295

**Comment by neheb** [comment]
This package was removed by https://github.com/openwrt/packages/pull/6379

Closing
