### ISSUE TITLE
git: create git user on install?

### ISSUE THREAD

**Issue by MikePetullo** [openwrt/packages#6996]
Maintainer: @tripolar
Environment: All

Description:

I install the git package on OpenWrt in order to provide a Git service using git-shell. When I do this, I manually create a new user on the OpenWrt host called "git". I wonder if it would be a good idea to create such a user when installing the git package, i.e., add a USERID statement to its Makefile.

**Comment by cshoredaniel** [comment]
If you do this pls notify me so I can remove the git user creation from gitolite package.

**Comment by tripolar** [comment]
i wouldn't do this in the git package as it implements no server/init file so i see no need for this
