### ISSUE TITLE
stubby: image-builder doesn't find stubby

### ISSUE THREAD

**Issue by bogi788** [openwrt/packages#6998]
Maintainer: @iamperson347
Environment: mips_24kc, TP-Link Archer C7 v2, OpenWRT Development Snapshot

Description: The image builder currently fails to build my custom image (with kernel modules and packages for my LTE modem) and stubby for DNS over TLS and DNSSEC. The error message is:

```Unknown package 'stubby'.```

**Comment by dibdot** [comment]
stubby is currently broken for your arch, see: https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/stubby/compile.txt, therefore it's not included in image builder.

**Comment by bogi788** [comment]
Apparently this is caused by the getdns dependency also failing to build: https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/getdns/compile.txt

**Comment by bogi788** [comment]
The getdns problem is probably related to https://github.com/openwrt/packages/pull/6960

**Comment by adagari** [comment]
I am also having errors on mvebu when trying to use the image builder.

**Comment by yousong** [comment]
The getdns missing dependency on libbsd issue should now be worked around by pull request #6960
