### ISSUE TITLE
mc - missing virtual file system support

### ISSUE THREAD

**Issue by ThomasCr** [openwrt/packages#6999]
Hi,
today I wanted to use mc to browse a tar archiv to extract only some files. I know it is possible to list content with tar command and than extract it manually, but with many files it feels not really comfortable.

thats why I use mc for those tasks, for easer extraction... problem is, that mc is not build with any Virtual File System, and so I can't open 

```
root@gw:~# mc --version
GNU Midnight Commander 4.8.20
Built with GLib 2.56.1
Using the ncurses library
With builtin Editor
With subshell support as default
With mouse support on xterm
With multiple codepages support
Data types: char: 8; int: 32; long: 32; void *: 32; size_t: 32; off_t: 64;

```

Is there a way to add it in oncoming releases, maybe in a extra package (aka mc-full) ?

Thanks,
Thomas

**Comment by dibdot** [comment]
Enabling VFS support adds round 40KB to resulting binary (tested on mips target, 390KB vs. 433KB). Maybe it doesn't matter much to enable this by default cause it's already a big package ... any thoughts?

**Comment by DazzyWalkman** [comment]
VFS support adds libtirpc dependency, that's another few KBs. 
To make it more convenient for packages repo users, I will think about adding an extra package (aka mc-full) , as OP suggests.  
For those who build packages for themselves, like me, leaving config options in menuconfig is already good enough.

**Comment by mhei** [comment]
Maintainer decided to enable VFS support by default, so I think we can close this issue.
