### ISSUE TITLE
odhcpd + bind-server: Should be moved into base-system instead of using dnsmasq

### ISSUE THREAD

**Issue by LipkeGu** [openwrt/packages#7005]
OpenWrt contains a daemon ```o(penwrt)dhcpd``` and is mostly supported in Luci. For the dns part we could use bind-Server without any zones (forwarder mode). Also we have a few problems with dnsmasq:
* dnsmasq does not Forward SRV entries.
* dnsmasq has a very slow tftp service (no window size Support at all)
* pxe (Apple BSDP and Intel RBCP) is able with two options in odhcpd.
* we should use bind + odhcpd/c (its smaller than dnsmasq itself) and increases performance
* alot of the users does not using PXE boot by default and dnsmasq have problems with PXE.

**Comment by dibdot** [comment]
please discuss removal of core components on the dev mailing list.
