### ISSUE TITLE
getdns: missing dependency for libbsd.so.0

### ISSUE THREAD

**Issue by bogi788** [openwrt/packages#7019]
Maintainer: @iamperson347
Environment: mips_24kc, TP-Link Archer C7 v2, OpenWRT Development Snapshot

As mentioned in https://github.com/openwrt/packages/issues/6998 stubby doesn't build because it is missing getdns, which itself fails to build: https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/getdns/compile.txt

The log seems to indicate that a libbsd dependency is not specified.

**Comment by dibdot** [comment]
@bogi788 I don't think that we need separate tickets here. Maintainer is informed about stubby, that should do it, thanks.
