### ISSUE TITLE
vala fails to build with CONFIG_ALL

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#702]
vala complains because some pkg-config files from glib2 are missing
those were not built yet at the time vala was built
After some time glib2 gets build and manually rebuilding vala later is successful.

diffconfig is:
```
CONFIG_TARGET_ar71xx=y
CONFIG_TARGET_ar71xx_generic=y
CONFIG_TARGET_ar71xx_generic_Default=y
CONFIG_ALL=y
CONFIG_DEVEL=y
CONFIG_BUILD_LOG=y
```
all feeds are installed (including oldpackages)

building with / result:
```
make -j 9 IGNORE_ERRORS=m
.
.
. (many oldpackages entries)
    ERROR: package/feeds/packages/vala failed to build.
. (many oldpackages entries)
```
building is done on Arch Linux

**Comment by kissg1988** [comment]
Sorry for late response, pkg maintainer here. I'm not sure why this happens, as you can see in the Makefile, vala has glib2 as a build dependency:

[code]
PKG_BUILD_DEPENDS:=glib2/host vala/host
[/code]

Can you please try whether adding glib2 as a build dependency helps?

[code]
PKG_BUILD_DEPENDS:=glib2/host vala/host glib2
[/code]

If it helps please let me know and I patch the makefile (or feel free to do that yourself).

Thanks!

**Comment by plntyk** [comment]
adding glib2 as build dependency helps - cannot replicate this error any more
