### ISSUE TITLE
Freeradius2 Error

### ISSUE THREAD

**Issue by bboy519** [openwrt/packages#7021]
Please make sure that the issue subject starts with `<package-name>: `

This repo here is only for packages maintained in this repo.  For base packages residing in the same repo as the build system and maintained by core devs, please consider opening tickets there for more timely responses

 - OpenWrt base system: https://bugs.openwrt.org
 - Most LuCI packages: https://github.com/openwrt/luci/issues

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

Description:
 ```
Fri Sep 14 23:22:39 2018 : Debug:  }
/opt/sbin/radiusd: '/lib/' is not an ELF file
/opt/sbin/radiusd: '/opt/lib/' is not an ELF file
/opt/sbin/radiusd: '/opt/lib/' is not an ELF file
Fri Sep 14 23:22:40 2018 : Debug: radiusd: #### Instantiating modules ####
Fri Sep 14 23:22:40 2018 : Debug:  instantiate {
Fri Sep 14 23:22:40 2018 : Debug:  }
Fri Sep 14 23:22:40 2018 : Debug: radiusd: #### Loading Virtual Servers ####
Fri Sep 14 23:22:40 2018 : Debug: server { # from file /opt/etc/freeradius2/radiusd.conf
Fri Sep 14 23:22:40 2018 : Debug:  modules {
Fri Sep 14 23:22:40 2018 : Debug:  Module: Checking authenticate {...} for more modules to load
/opt/sbin/radiusd: '/opt/lib/freeradius2/rlm_pap.so' is not an ELF file
/opt/sbin/radiusd: '/opt/lib/freeradius2/rlm_pap.so' is not an ELF file
Fri Sep 14 23:22:40 2018 : Error: /opt/etc/freeradius2/modules/pap[20]: Failed to link to module 'rlm_pap': file not found
Fri Sep 14 23:22:40 2018 : Error: /opt/etc/freeradius2/sites/default[258]: Failed to find "pap" in the "modules" section.
Fri Sep 14 23:22:40 2018 : Error: /opt/etc/freeradius2/sites/default[258]: Failed to parse "pap" entry.

Formating code blocks by wrapping them with pairs of ```
```

**Comment by dibdot** [comment]
This doesn't look like a OpenWrt package at all. This repo ships freeradius3 only, the referenced /opt directory structure is not used ... further more the issue template has been ignored (OpenWrt version, maintainer etc.). Close this by now.
