### ISSUE TITLE
Tinyproxy - Enable reverse proxying

### ISSUE THREAD

**Issue by cminois** [openwrt/packages#7024]
Hi,

Could you modify the configuration of the Tinyproxy package to enable reverse proxying?
Adding --enable-reverse argument in the makefile should do it.

Thanks.

**Comment by dibdot** [comment]
Please always inform the package maintainer: @jow-

**Comment by cminois** [comment]
Hi @jow-, could you have a look at my request? Thanks.

**Comment by OzgurBagci** [comment]
This is not fixed contrary to what is stated in #11002.
