### ISSUE TITLE
chrony: "allow" statement doesn't allow IPv6

### ISSUE THREAD

**Issue by jech** [openwrt/packages#7039]
Maintainer: @mlichvar
Environment: 18.06.1

Using `option "interface" "lan"` in `/etc/config/chrony` only allows the IPv4 address of the `lan` interface; it doesn't open the IPv6 listening port.  Whilte that's easy worked around by adding suitable directives to `/etc/chrony/chrony.conf`, it's annoying since it forces hard-wiring the IPv6 addresses.

(My clients are configured using the router's DNS name, so they automatically try to use the router's IPv6 ULA.  So it's not simply a matter of being pedantic.)

**Comment by dibdot** [comment]
seems to be fixed.
