### ISSUE TITLE
mwan3: MWAN - Rules - Source address & squid

### ISSUE THREAD

**Issue by lucize** [openwrt/packages#7042]
@feckert adding multiple ip addresses to the `Source address` is possible but then the `iptables -vL -t mangle` will not show the rule in `Chain mwan3_rules`

also I'm trying to make squid work only on one interface (or on any)
if I add multiple source address in the rules (all ip on router as per issue stated above) then squid works but the tcp_outgoing_address will have no importance, testing on sites shows random random outgoing ip

squid works ok with interception but not if is manually added in the browser

when is manual set I get this error
`NONE/000 0 NONE error:transaction-end-before-headers - HIER_NONE/- -`
I opened a discussion at https://forum.openwrt.org/t/solved-mwan3-and-squid/20854

![image](https://user-images.githubusercontent.com/6313831/45598404-305ec780-b9e4-11e8-9788-110a773c2863.png)

**Comment by feckert** [comment]
> NONE/000 0 NONE error:transaction-end-before-headers - HIER_NONE/- -

What program generates this output?

**Comment by lucize** [comment]
in squid access log, when you try multiple pages with manual proxy setup, no redirect (interception)

**Comment by feckert** [comment]
@lucize no problem which version of mwan3 do you use on issue creation? The version 2.7.8 is the latest one from master.

**Comment by lucize** [comment]
it was the one that had source route option

**Comment by feckert** [comment]
It would be better if you could tell me the version ;-) or the openwrt version 17.01 /18.06 with this version information i know the mwan3 version

**Comment by lucize** [comment]
I'm always on master,so I did an update to it (one per month or so), but I managed to satisfy my needs using transparent proxy because it was time pressing, I'll try to recreate the scenario with manual proxy setup

**Comment by lucize** [comment]
I am pretty sure it was 2.7.2

**Comment by feckert** [comment]
@lucize ping does your setup work with the last master?

**Comment by neheb** [comment]
ping @lucize

**Comment by lucize** [comment]
followed mwan commits and didn't see anything related to this, I'll close this as it seems to be a best effort support
