### ISSUE TITLE
php5 GD not working - (Unable to load dynamic library '/usr/lib/php/gd.so' - (null) in Unknown on line 0))

### ISSUE THREAD

**Issue by guentir** [openwrt/packages#706]
php5-mod-gd not working since a long time, also on latest trunk (x86) (PHP 5.4.36) (r43795):

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/gd.so' - (null) in Unknown on line 0

gd.so exists in /usr/lib/php/

more information:
https://dev.openwrt.org/ticket/17303

**Comment by guentir** [comment]
works.

**Comment by gideaofranco** [comment]
Hi guys,

I m trying to install from OPKG and not work yet.

URI: http://downloads.openwrt.org/attitude_adjustment/12.09/x86/generic/packages/Packages.gz

Any suggestion?

Thank you!
