### ISSUE TITLE
admin/syslog-ng: Config file needs to be updated to 3.16

### ISSUE THREAD

**Issue by jeffsf** [openwrt/packages#7072]
Re-starting syslog-ng with the supplied config file logs

> WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.16 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;

While syslog-ng appears to run, the message can be distracting for users trying to properly configure on their system.

https://github.com/openwrt/packages/blob/master/admin/syslog-ng/files/syslog-ng.conf

See also https://forum.openwrt.org/t/system-log-level-with-logd/16798/10?u=jeff

**Comment by dibdot** [comment]
Please always inform the package maintainer: @MikePetullo

**Comment by MikePetullo** [comment]
The configuration file version issue should be fixed by pull request #6796, which is waiting to be merged.

**Comment by dibdot** [comment]
Should be fixed in master - thanks.
