### ISSUE TITLE
luasec: Update to v0.7

### ISSUE THREAD

**Issue by vshymanskyy** [openwrt/packages#7073]
Maintainer: @MikePetullo @sbyx @cotequeiroz 
Environment: any

Please update to v0.7 with official openssl 1.1.0 support.

**Comment by cotequeiroz** [comment]
Done in a48a5c0e26139f43a9899882529589ce4b69ca49.  I guess this should be closed.

**Comment by vshymanskyy** [comment]
@cotequeiroz Thanks!
