### ISSUE TITLE
netopeer2: Failed to set hostkey

### ISSUE THREAD

**Issue by hzc9107** [openwrt/packages#7075]
Hello, I am trying to setup a netopeer2 server on a software switch using OpenWRT. I have managed to install the server correctly. Nevertheless, when I try to establish a connection I receive the error:

 Failed to set hostkey "ssh_host_rsa_key" (/etc/keystored/keys/ssh_host_rsa_key.pem)

After looking for the problem, I found out that it may be an issue with the libssh library. Also, the maintainer of netopeer2 says in some of this that there are some modules that shouldn't be supported anymore like ietf-system and ietf-keystore. Both of this are installed in the current netopeer2 distribution in openWRT. Have you experienced similar issues with this package? If so, could you maybe give me advice on how to go about it?

**Comment by dibdot** [comment]
At this stage please discuss this in the forum: https://forum.openwrt.org/
