### ISSUE TITLE
OpenVPN ignores options from /etc/config/openvpn if there is a link to an external .ovpn

### ISSUE THREAD

**Issue by dartraiden** [openwrt/packages#7090]
My /etc/config/openvpn:

```
config openvpn antizapret

    option enabled 1
    option config /etc/openvpn/antizapret-tcp.ovpn
    option auth_nocache 1
```

**Current behavior**
`auth_nocache` is ignored, because there is a link to an external .ovpn

It is better to pass options from /etc/config/openvpn to OpenVPN command line. For example, desktop OpenVPN allows smth like
`openvpn --config /path/to/antizapret-tcp.ovpn --auth-nocache`

**Comment by yousong** [comment]
Openvpn is part of the base system.  Issues or feature request should be directed to bugs.openwrt.org.  I am closing this.

That set aside.  I do not like the added complexity.  It's not much burden to just edit the config file.  It's more clean and clear.  On the other hand, overriding may not always work as expected [1].  These extra caveats/exceptions spoil the fun

 [1] https://forums.openvpn.net/viewtopic.php?t=26229
