### ISSUE TITLE
fdm - now that is compiles, can it be included in 18.06.2?

### ISSUE THREAD

**Issue by OhSoGood** [openwrt/packages#7092]
As per discussion in the forum ( https://forum.openwrt.org/t/fdm-package-not-in-18-06-1-can-anybody-add-it/21861 ),

> Basically, one of fdm's dependencies, tdb, was not built because of an unfortunate side effect of making libbsd not restricted to glibc. This is fixed in snapshot. fdm will appear in 19.01, coming early next year.
>
> If you want it for 18.06.2, open an issue in the packages feed and ping @thess

So... can you include fdm in 18.06.2 ? Thank you a lot!

**Comment by thess** [comment]
Done via: https://github.com/openwrt/packages/commit/218a7a6868fdc2bf8862e6f057a0d13dace33885
Should be in downloads after buildbots catch up in a day or 2.
