### ISSUE TITLE
jool: build fails on ath79 target with current kernel (4.14.79)

### ISSUE THREAD

**Issue by Leo-PL** [openwrt/packages#7095]
Maintainer: @danrl  
Environment: OpenWrt 18.06, ath79 target, building on Ubuntu 16.04.

Description:
With current OpenWrt master at 958dc59136752ead23124b78ca22ffc41b1cb7bb, build fails with the following error, because INETFRAGS_HASHSZ symbol was removed in kernel 4.14
On ar71xx target with 4.9 kernel, the package builds fine.

```
make[3]: Entering directory '/mnt/work/priv/openwrt/ath79/feeds/packages/net/jool'
rm -f /mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/.built
touch /mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/.built_check
make -C "/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.14.71" KERNEL_DIR="/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.14.71" ARCH="mips" CROSS_COMPILE="mips-openwrt-linux-musl-" SUBDIRS="/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful" V="s" modules
make[4]: Entering directory '/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.14.71'
  CC [M]  /mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.o
/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
  return c & (INETFRAGS_HASHSZ - 1);
              ^~~~~~~~~~~~~~~~
              INET_FRAG_LAST_IN
/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:328: recipe for target '/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.o' failed
make[5]: *** [/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful/fragment_db.o] Error 1
Makefile:1525: recipe for target '_module_/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful' failed
make[4]: *** [_module_/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/mod/stateful] Error 2
make[4]: Leaving directory '/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.14.71'
Makefile:110: recipe for target '/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/.built' failed
make[3]: *** [/mnt/work/priv/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/Jool-3.5.7/.built] Error 2
make[3]: Leaving directory '/mnt/work/priv/openwrt/ath79/feeds/packages/net/jool'
time: package/feeds/packages/jool/compile#1.00#0.25#4.96
package/Makefile:107: recipe for target 'package/feeds/packages/jool/compile' failed
make[2]: *** [package/feeds/packages/jool/compile] Error 2
make[2]: Leaving directory '/mnt/work/priv/openwrt/ath79'
package/Makefile:103: recipe for target '/mnt/work/priv/openwrt/ath79/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/mnt/work/priv/openwrt/ath79/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/work/priv/openwrt/ath79'
/mnt/work/priv/openwrt/ath79/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
```

**Comment by Leo-PL** [comment]
@neheb

**Comment by neheb** [comment]
Weird. I could have sworn it built fine on mvebu. I won't be able to fix this for a while as my laptop is out of commission due to a bad BIOS flash.

**Comment by neheb** [comment]
Just add this as a patch to get it to build: https://github.com/NICMx/Jool/commit/de791931d94e972c36bb3c102a9cadab5230c285

**Comment by the-eric-kwok** [comment]
Built failed with master at `e1db49310e9912f4076789e704180ab3b9ea0184`.

Enviroment: Allwinner A20, built on Deepin Linux 15.7

Before I add the patch I got this
```
...
/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
  return c & (INETFRAGS_HASHSZ - 1);
              ^~~~~~~~~~~~~~~~
              INET_FRAG_LAST_IN
/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[5]: *** [scripts/Makefile.build:329: /home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful/fragment_db.o] Error 1
make[4]: *** [Makefile:1525: _module_/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/mod/stateful] Error 2
make[4]: Leaving directory '/home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/linux-4.14.76'
make[3]: *** [Makefile:113: /home/eric/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-sunxi_cortexa7/Jool-3.5.7/.built] Error 2
make[3]: Leaving directory '/home/eric/openwrt/feeds/packages/net/jool'
time: package/feeds/packages/jool/compile#6.03#1.17#8.56
make[2]: *** [package/Makefile:109: package/feeds/packages/jool/compile] Error 2
make[2]: Leaving directory '/home/eric/openwrt'
make[1]: *** [package/Makefile:103: /home/eric/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/eric/openwrt'
make: *** [/home/eric/openwrt/include/toplevel.mk:218：world] Error 2
```

And then I add the patch, `make dirclean` and recompile, I somehow got this:
```
...
Configuring kmod-nf-ipt6.
Configuring kmod-ip6tables.
Configuring odhcp6c.
Configuring uci.
Configuring curl.
Configuring mtd.
Configuring odhcpd-ipv6only.
Configuring ppp.
Configuring logd.
Configuring libss.
Configuring iptables.
Configuring kmod-rtc-sunxi.
Configuring libext2fs.
Configuring e2fsprogs.
Configuring hwclock.
Configuring gawk.
Configuring openssh-sftp-client.
Configuring libevent2-core.
Configuring ip6tables.
Configuring openssh-sftp-avahi-service.
Configuring kmod-sun4i-emac.
Configuring ntpdate.
Configuring kmod-ipt-offload.
Configuring ntp-keygen.
Configuring ppp-mod-pppoe.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/eric/openwrt'
make[1]: *** [package/Makefile:104: /home/eric/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/eric/openwrt'
make: *** [/home/eric/openwrt/include/toplevel.mk:218：world] Error 2
```

I have no idea what's going on.

**Comment by neheb** [comment]
This fixes is: https://github.com/openwrt/packages/pull/7176

Someone needs to merge

**Comment by briskycat** [comment]
Somehow I still face this issue on the `openwrt-18.06` branch (beyond the `18.06.2` release tag):
```
make[3]: Entering directory '/home/user/openwrt/feeds/packages/net/jool'
rm -f /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built
touch /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built_check
make -C "/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97" KERNEL_DIR="/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97" ARCH="arm" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" SUBDIRS="/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful" V="s" modules
make[4]: Entering directory '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97'
  CC [M]  /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o
/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
  return c & (INETFRAGS_HASHSZ - 1);
              ^~~~~~~~~~~~~~~~
              INET_FRAG_LAST_IN
/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:326: recipe for target '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o' failed
make[5]: *** [/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o] Error 1
Makefile:1533: recipe for target '_module_/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful' failed
make[4]: *** [_module_/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful] Error 2
make[4]: Leaving directory '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97'
Makefile:113: recipe for target '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built' failed
make[3]: *** [/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built] Error 2
make[3]: Leaving directory '/home/user/openwrt/feeds/packages/net/jool'
time: package/feeds/packages/jool/compile#1.29#0.37#1.66
package/Makefile:107: recipe for target 'package/feeds/packages/jool/compile' failed
make[2]: *** [package/feeds/packages/jool/compile] Error 2
make[2]: Leaving directory '/home/user/openwrt'
package/Makefile:103: recipe for target '/home/user/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/user/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/openwrt'
/home/user/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
```
Stranger still is that it happens whith the following configuration options:
```
CONFIG_PACKAGE_kmod-jool=m
# CONFIG_PACKAGE_jool is not set
# CONFIG_PACKAGE_jool-tools is not set
```

**Comment by neheb** [comment]
Not really. It's fixed for the next version, but not for 18.06.

**Comment by mcarlsonO** [comment]
> Somehow I still face this issue on the `openwrt-18.06` branch (beyond the `18.06.2` release tag):
> 
> ```
> make[3]: Entering directory '/home/user/openwrt/feeds/packages/net/jool'
> rm -f /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built
> touch /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built_check
> make -C "/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97" KERNEL_DIR="/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97" ARCH="arm" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" SUBDIRS="/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful" V="s" modules
> make[4]: Entering directory '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97'
>   CC [M]  /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o
> /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
> /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
>   return c & (INETFRAGS_HASHSZ - 1);
>               ^~~~~~~~~~~~~~~~
>               INET_FRAG_LAST_IN
> /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
> /home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> scripts/Makefile.build:326: recipe for target '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o' failed
> make[5]: *** [/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o] Error 1
> Makefile:1533: recipe for target '_module_/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful' failed
> make[4]: *** [_module_/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful] Error 2
> make[4]: Leaving directory '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/linux-4.14.97'
> Makefile:113: recipe for target '/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built' failed
> make[3]: *** [/home/user/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built] Error 2
> make[3]: Leaving directory '/home/user/openwrt/feeds/packages/net/jool'
> time: package/feeds/packages/jool/compile#1.29#0.37#1.66
> package/Makefile:107: recipe for target 'package/feeds/packages/jool/compile' failed
> make[2]: *** [package/feeds/packages/jool/compile] Error 2
> make[2]: Leaving directory '/home/user/openwrt'
> package/Makefile:103: recipe for target '/home/user/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile' failed
> make[1]: *** [/home/user/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
> make[1]: Leaving directory '/home/user/openwrt'
> /home/user/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
> make: *** [world] Error 2
> ```
> 
> Stranger still is that it happens with the following configuration options:
> 
> ```
> CONFIG_PACKAGE_kmod-jool=m
> # CONFIG_PACKAGE_jool is not set
> # CONFIG_PACKAGE_jool-tools is not set
> ```

make[3]: Entering directory '/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/feeds/packages/net/jool'
rm -f /home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built
touch /home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built_check
make -C "/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.156" KERNEL_DIR="/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.156" ARCH="mips" CROSS_COMPILE="mips-openwrt-linux-musl-" SUBDIRS="/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful" V="sc" modules
make[4]: Entering directory '/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.156'
  CC [M]  /home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o
/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
  return c & (INETFRAGS_HASHSZ - 1);
              ^~~~~~~~~~~~~~~~
              INET_FRAG_LAST_IN
/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:304: recipe for target '/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o' failed
make[5]: *** [/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o] Error 1
Makefile:1528: recipe for target '_module_/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful' failed
make[4]: *** [_module_/home/mcarlson/OPENWRT/build_trees/ar71xx-generic-wzr-hp-ag300h/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful] Error 2

I am seeing the same issue on the stable openwrt-18.06 branch (updated a hour ago) with a nearly default config.
CONFIG_PACKAGE_kmod-jool=m
# CONFIG_PACKAGE_jool is not set
# CONFIG_PACKAGE_jool-tools is not set

So I suppose the solution here is to forcibly disable this thing?

**Comment by predators46** [comment]
Eror jool lede 17.01.7
Kernel 4.4.182

`/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function)
  return c & (INETFRAGS_HASHSZ - 1);
              ^
/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:277: recipe for target '/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful/fragment_db.o' failed
make[5]: *** [/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful/fragment_db.o] Error 1
Makefile:1436: recipe for target '_module_/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful' failed
make[4]: *** [_module_/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/mod/stateful] Error 2
make[4]: Leaving directory '/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/linux-4.4.182'
Makefile:112: recipe for target '/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/.built' failedmake[3]: *** [/home/ubuntu/openwrt/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/jool-66a791c90751d7941b08c142babe1deec73d0996/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/openwrt/feeds/packages/net/jool'
package/Makefile:105: recipe for target 'package/feeds/packages/jool/compile' failed
make[2]: *** [package/feeds/packages/jool/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/openwrt'
package/Makefile:101: recipe for target '/home/ubuntu/openwrt/staging_dir/target-mips_24kc_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/openwrt/staging_dir/target-mips_24kc_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt'
/home/ubuntu/openwrt/include/toplevel.mk:205: recipe for target 'world' failed
make: *** [world] Error 2`
