### ISSUE TITLE
domoticz needs to be recompiled

### ISSUE THREAD

**Issue by lollul** [openwrt/packages#7116]
Maintainer: Stijn Tintel <stijn@linux-ipv6.be>
Environment: Openwrt 18.06

Description: boost components have been upgraded to 1.68 release but looks like domoticz wasn't recompiled.

Error loading shared library libboost_thread.so.1.67.0: No such file or directory (needed by /usr/bin/domoticz)
Error loading shared library libboost_system.so.1.67.0: No such file or directory (needed by /usr/bin/domoticz)
Error loading shared library libboost_chrono.so.1.67.0: No such file or directory (needed by /usr/bin/domoticz)
Error loading shared library libboost_date_time.so.1.67.0: No such file or directory (needed by /usr/bin/domoticz)
Error loading shared library libboost_atomic.so.1.67.0: No such file or directory (needed by /usr/bin/domoticz)
Error relocating /usr/bin/domoticz: _ZN5boost6thread21start_thread_noexceptEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6thread6detachEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6detail16thread_data_baseD2Ev: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6thread13native_handleEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6system15system_categoryEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6thread9interruptEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost11this_thread18interruption_pointEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6threadC1Ev: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6detail23get_current_thread_dataEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost11this_thread20disable_interruptionC1Ev: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost11this_thread20disable_interruptionD1Ev: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6thread13join_noexceptEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6system16generic_categoryEv: symbol not found
Error relocating /usr/bin/domoticz: _ZN5boost6thread26do_try_join_until_noexceptERKNS_6detail23mono_platform_timepointERb: symbol not found
Error relocating /usr/bin/domoticz: _ZTVN5boost6detail16thread_data_baseE: symbol not found
Error relocating /usr/bin/domoticz: _ZTIN5boost6detail16thread_data_baseE: symbol not found

**Comment by thess** [comment]
Fixed in 18.06 by 482d94bf4725f95710369dd31ed0b49cce593ed7
