### ISSUE TITLE
coova-chilli: Build does not honor "disable-IPV6 for packages"

### ISSUE THREAD

**Issue by reinerotto** [openwrt/packages#7120]
Maintainer: Jaehoon You <teslamint@gmail.com>
Environment: trunk

When building image _without_ support for ipv6 for packages, this is not honored for coova-chilli.
May be, to introduce additional option for "make menuconfig" like
$(if $(CONFIG_COOVACHILLI_IPV6),--with,--without)-ipv6 \

Actually, coova-chilli is always built incl. ipv6

**Comment by dibdot** [comment]
Please always use the @-notation to inform the maintainer: @teslamint
