### ISSUE TITLE
i2pd needs to be recompiled

### ISSUE THREAD

**Issue by dartraiden** [openwrt/packages#7136]
i2pd wasn't recompiled and search boost 1.67, but boost already bumped to 1.68

`Error loading shared library libboost_system.so.1.67.0: No such file or directory`

**Comment by thess** [comment]
Is this 18.06 release or master branch orr both?

**Comment by thess** [comment]
Fixed in 18.06 by 482d94bf4725f95710369dd31ed0b49cce593ed7
