### ISSUE TITLE
Aircrack-ng 1.4 Makefile

### ISSUE THREAD

**Issue by akavish12** [openwrt/packages#7174]
is there a Makefile for the new version of aircrack-ng?
tried to cross compile using the toolchain and had too many dependency problems :(

thanks!

**Comment by dibdot** [comment]
Obviously "No". Please discuss your issue in the forum and maybe come back with a proper PR for an updated aircrack-ng package.

**Comment by kevinpostal** [comment]
didbot stop being so autistic
