### ISSUE TITLE
perl: build broken for octeon (mips64)

### ISSUE THREAD

**Issue by nortobor** [openwrt/packages#718]
build stops with:
"sed: can't read files/config.sh-mips64.in: No such file or directory"

could you please provide a config for mips64?

TIA!

**Comment by Naoir** [comment]
I've just pushed perl 5.20.1-2, adding a mips64 configuration file.
I don't have access to a stable mips64 system for extensive testing at the moment. It does start and run some basic programs though. Feel free to submit any resulting bugs if you encounter one.

Thanks
