### ISSUE TITLE
isc-dhcp-relay-v4 installs the /etc/config/dhcrelay.conf file instead of /etc/config/dhcrelay

### ISSUE THREAD

**Issue by garrymar** [openwrt/packages#7235]
Dear maintainers,

Recently I noticed that the package `isc-dhcp-relay-v4` installs default configuration file as `/etc/config/dhcrelay.conf`, but the corresponding init script looks for the `/etc/config/dhcrelay`. Thanks.

**Comment by pprindeville** [comment]
On it.

**Comment by pprindeville** [comment]
Resolved with PR #7270.

Thanks
