### ISSUE TITLE
poco: being built for --minimal, why not --typical?

### ISSUE THREAD

**Issue by chmorgan** [openwrt/packages#7253]
I have use for poco libraries that are excluded in the --minimal build, such as crypto and netssl.

Would a PR to change from minimal to typical be accepted? If not is it easy to replace the poco recipe with my own version that builds for --typical?

**Comment by neheb** [comment]
Post one and we'll see.

**Comment by chmorgan** [comment]
@neheb, I can see about doing so!

**Comment by feckert** [comment]
I close this issue because of https://github.com/openwrt/packages/pull/9009
