### ISSUE TITLE
[FEATURE REQUEST] adblock: add energized sources

### ISSUE THREAD

**Issue by n00bundercover** [openwrt/packages#7256]
I hope this is the right way to propose something rather than filing a bug. Just let me know if I'm wrong!

I want to propose to add the sources from energized as predefined options in adblock.

https://energized.pro/
https://github.com/EnergizedProtection/block

I could add a single energized "pack" like described in the readme, looking something like this:

`config source 'reg_ro'
  option enabled '0'
  option adb_src 'https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/filter'
  option adb_src_rset 'BEGIN{FS=\"[|^]\"}/^\|\|([^([:space:]|#|\*|\/).]+\.)+[[:alpha:]]+\^("\\\$third-party")?$/{print tolower(\$3)}'
  option adb_src_desc 'Energized Ultimate, aprox. 575.000 entries.'`

But:

1. energized offers multiple formats. I don't know if there is a difference in performance, requirements like ram etc. Which format would be the best to use?

2. some default packs offer multiple options, like "shalla":
`config source 'shalla'
	option adb_src 'http://www.shallalist.de/Downloads/shallalist.tar.gz'
	option adb_src_rset '/^([[:alnum:]_-]+\.)+[[:alpha:]]+([[:space:]]|$)/{print tolower(\$1)}'
	option adb_src_desc 'huge blocklist archive subdivided in different categories, daily updates. Check http://www.shallalist.de/categories.html for more categories'
	list adb_src_cat 'adv'
	list adb_src_cat 'costtraps'
	list adb_src_cat 'spyware'
	list adb_src_cat 'tracker'
	list adb_src_cat 'warez'
option enabled '0'`
... but I do not understand the logic behind it, how could I do something like this for energized?

I would really love to see this as one of the default options. Imho it is the best block list collection out there. Let me know what you think!

**Comment by dibdot** [comment]
Thanks for your input!

> energized offers multiple formats. I don't know if there is a difference in performance, requirements like ram etc. Which format would be the best to use?

Please use always the 'domains.txt' format, e.g.:

```
config source 'energized_basic'
	option adb_src 'https://raw.githubusercontent.com/EnergizedProtection/block/master/basic/formats/domains.txt'
	option adb_src_rset '/^([[:alnum:]_-]+\.)+[[:alpha:]]+([[:space:]]|$)/{print tolower(\$1)}'
	option adb_src_desc 'energized blocklist compilation, approx. ??? entries'
	option enabled '1'
```

> how could I do something like this for energized?
you can't, energized doesn't provide an archive with different categories (like shalla or ut_capitole). 

I don't plan to add this to the default adblock config. Even the basic energized variant provides more than 400k domains (compressed only ~280k), simply too much for average routers.
Anyway, feel free to add this to your personal configuration.
