### ISSUE TITLE
mariadb is crashing after first connection attempt

### ISSUE THREAD

**Issue by silvah2** [openwrt/packages#7348]
OpenWrt SNAPSHOT, r8431-df1191bcea, linksys wrt1200ac, mariadb 10.2.17

After migration from older snapshot (about maybe 3 months old) first connection attempt makes mariadb crash. (mysqld is going down)

All the configs are fine. Something is broken.

**Comment by micmac1** [comment]
Hello @silvah2 

I've seen reports before that there are problems on mvebu. Are you also seeing "illegal instruction" in the syslog when this happens?

I won't be able to debug this myself as I don't have this hardware.

Kind regards,
Sebastian

**Comment by micmac1** [comment]
I've had some feedback that this may not be related to a kernel version bump. I see the following changes not too long ago which might be of interest:

1) commit [kernel: only optimized for size if small_flash](https://github.com/openwrt/openwrt/commit/cf7154db07c0b8746be290c9e11dcab3c91d237e)
2) commit [binutils: Use 2.31.1 by default](https://github.com/openwrt/openwrt/commit/fface27db82e7926c86a6b15746446f633d533f3)

I think 2) might fit the timeline better. Could you try fresh git checkout, change binutils version in menuconfig to 2.30 and try if that is the culprit?

Kind regards,
Seb

**Comment by silvah2** [comment]
where is this in menuconfig?

**Comment by micmac1** [comment]
1. Global build settings  --->
      Kernel build options  --->
        Compiler optimization level (Optimize for performance)  --->

2. Advanced configuration options (for developers)  --->
      Toolchain Options  --->
        Binutils Version (Binutils 2.30)  --->

**Comment by silvah2** [comment]
ok, compiling

**Comment by silvah2** [comment]
still not working:
first connection attempt:
ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 11

and then
root@LEDE:~# ps|grep mysql
 4014 root      1052 S    grep mysql

**Comment by micmac1** [comment]
Hello,

Could you try out the pull request #7379? That issue caused a segfault for me on mips. I'm not sure if your issue is the same (different arch, no debug provided). But timeline-wise it might be.

Regards,
Seb

**Comment by champtar** [comment]
Just merged #7379

**Comment by silvah2** [comment]
works now, thx
