### ISSUE TITLE
mc (midnight commander) - package missing in TRUNK

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#7349]
mc (midnight commander) - package missing in TRUNK
only available in stable builds which is very old, but in trunk missing

**Comment by dibdot** [comment]
Duplicate of #7180 ... probably I will disable VFS support (again) with the next mc update as long as the underlying librpc issue has not been fixed.

**Comment by dibdot** [comment]
done, let's see if buildbot is happy again ...;-)
