### ISSUE TITLE
simple adblock problem in openwrt 

### ISSUE THREAD

**Issue by jkle112** [openwrt/packages#7457]
running error 
![image 0](https://user-images.githubusercontent.com/17021524/48662072-4b6ab800-eab7-11e8-8f40-0db1b219b125.jpg)
![image 1](https://user-images.githubusercontent.com/17021524/48662073-4f96d580-eab7-11e8-9980-d29680f27236.jpg)

**Comment by dibdot** [comment]
Please always inform the maintainer: @stangri

**Comment by stangri** [comment]
@jkle112 -- set verbosity to 2 and check the logs to see which list failed to download. Download errors are not the package bugs, provided you find out which list is failing to download, you may want to seek additional help at forums.

**Comment by dibdot** [comment]
as @stangri said, probably a temporary download issue.

**Comment by jkle112** [comment]
The same problem in LEDE firmware!

![image 3](https://user-images.githubusercontent.com/17021524/49695332-7d61cc80-fbd4-11e8-8b80-936644bf31fd.png)
