### ISSUE TITLE
packages/utils/sispmctl: new upstream version 4.1

### ISSUE THREAD

**Issue by xypron** [openwrt/packages#7468]
@neheb @rkunze  @champtar 

I have created a new upstream version (4.1)

The most prominent change is added support for Gembird EG-PMS2 with idVendor=04b4, idProduct=fd15.

Best regards

Heinrich

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/7466

**Comment by xypron** [comment]
duplicate
