### ISSUE TITLE
mwan3: About policy route

### ISSUE THREAD

**Issue by leotian111** [openwrt/packages#7474]
Hi, I'm testing newest version 2.7.6 of mwan3.
But I can't succeed through lan.  I must modify from "iif $2 lookup $id" to "iif $2 lookup main" in shell function mwan3_create_iface_rules. then we can work in br-lan

I wonder if there are any special settings! 
thks!!

**Comment by dibdot** [comment]
@feckert

**Comment by leotian111** [comment]
@feckert

**Comment by leotian111** [comment]
@dibdot  
thks

**Comment by leotian111** [comment]
@feckert
Hi, Can I ask you a question about mwan3-2.7.6?

**Comment by leotian111** [comment]
@feckert
Hi, I'm testing newest version 2.7.6 of mwan3.
But I can't succeed through lan. I must modify from "iif $2 lookup $id" to "iif $2 lookup main" in shell function mwan3_create_iface_rules. then we can work in br-lan

I wonder if there are any special settings!
thks!!

**Comment by leotian111** [comment]
I have known reason, mwan3rtmon not work proper,  not update direct route into $id rules!

**Comment by feckert** [comment]
@leotian111 did you solved your issue?

**Comment by leotian111** [comment]
yes, thank you,  i see the shell function mwan3_rtmon_ipv4 detailed and found that we must have option family in file /etc/config/mwan3,  after adding it the problem solved!
