### ISSUE TITLE
shadowsocks-libev: "Dst ip/net forward file" does not accept ipv6 address

### ISSUE THREAD

**Issue by ccaapton** [openwrt/packages#7508]
Maintainer: @yousong 

Environment: ramips, Netgear R6220, OpenWrt SNAPSHOT r7526-02d53e6

Description:
I'm trying to add a file with ipv6 address as ''Dst ip/net forward file", but the 'ss-rules' script does not accept it and give such error:
`ipset v6.34: Error in line 487: Syntax error: cannot parse 2001:4860::: resolving to IPv4 address failed`

**Comment by yousong** [comment]
@ccaapton I just opened a pull request to add IPv6 support into ss-rules script.  Please give it a try and see if it works for you.

To give it a quick test, you can copy the updated shadowsocks-libev.init and ss-rules scripts to your board and restart the service.  The IPv6 support will require package `ip6tables-mod-nat`.

I only run-tested to observed whether the necessary ipsets, route rules and ip6table rules are present.  Please focus more on the actual traffic.  Thank you.
