### ISSUE TITLE
lang/erlang: wrong license

### ISSUE THREAD

**Issue by ng-0** [openwrt/packages#7549]
Maintainer: @cretingame

Description:

In https://github.com/openwrt/packages/blob/master/lang/erlang/Makefile#L18
it states that Erlang is (still) released under the Erlang Public License. This is
wrong, since OTP 18.0 Erlang uses the Apache Software License 2.0

**Comment by cretingame** [comment]
I will correct this, thank you for your remark

**Comment by cretingame** [comment]
I did a pull request
https://github.com/openwrt/packages/pull/7584

Thank you

**Comment by BKPepe** [comment]
@ng-0  or @hnyman  could you please close this issue?
