### ISSUE TITLE
Update E2guardian

### ISSUE THREAD

**Issue by tapper82** [openwrt/packages#7568]
From this link it seems that  e2guardian could do with updateing. https://openwrt.org/packages/pkgdata/e2guardian
From Version: 
3.2.0-1 to E2guardian 5.2.2 
http://e2guardian.org/cms/index.php/news/24-e2guardian-5-2-2

**Comment by diizzyy** [comment]
Yes, however e2guardian seems quite memory hungry which isn't a good thing as most routers are quite a "dinky" even when it comes to ARM-based ones. Combine that with general interest and you have a (very) stale package...

**Comment by neheb** [comment]
e2guardian was nuked.
