### ISSUE TITLE
sound/mocp: MOC 2.5.0 Released

### ISSUE THREAD

**Issue by ralemb** [openwrt/packages#761]
Would you please update mocp from the 2.5.0-beta2 release?

[MOC 2.5.0 Released] (http://moc.daper.net/node/1068)
> Well, finally, it's here! MOC 2.5.0, the stable version of the MOC 2.5 release series, "Consolidation".
> Here is a summary of the significant changes since the 2.5.0-beta2 release:
>    Better handling of huge and broken files
>    Improved (drastically in some cases) the accuracy of AAC durations
>    Screen handling improvements and bug fixes
>    Fixed various crashes, freezes, assertions and aborts

**Comment by thess** [comment]
Done, see: 070a01b6fd893386f499ce55b8d2de9bb0051a0e
