### ISSUE TITLE
Dnsmasq-full: ipv6 ipset wrongly working

### ISSUE THREAD

**Issue by kidome** [openwrt/packages#7643]
commit 8c0f6a010a5b7011acbbf2ac5b345d9cf1c14b1f

after this commit Dnsmasq ipset for ipv6 is filled not correct, it fills not the ip but the network in.

**Comment by ldir-EDB0** [comment]
I'll take a look

**Comment by ldir-EDB0** [comment]
Fixed by https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=ad8a5aa06a58b22657f7628c3d5eb4aae2db47f1

please test.

**Comment by kidome** [comment]
Great, tested and it's fixed.
