### ISSUE TITLE
grep: external routing not working

### ISSUE THREAD

**Issue by wapebira** [openwrt/packages#7764]
Maintainer: @\Zokormazo
Environment: arm_cortex-a9_vfpv3
mvebu/cortexa9; OPenwrt 18.06.1 stable and snapshot;  also with Lede SNAPSHOT, r8810-09004e6e13

Description:
Not sure if grep is the issue or other components, but here is what I did:
- flashed the image and installed grep using "opkg install grep"
- reboot the router
- after router comes back, the routing to internet is broken
- tested with external hostname and ip address (eg www.google.com and 172.217.1.4) so that is not the DNS the issue
- this does not apply to local network private ip. they continue to work
- it looks like after 8-9sec the connection drops, coming back after 29-30sec

![grep issue](https://user-images.githubusercontent.com/33706212/50406317-19710380-0791-11e9-98c1-44f21f9c29e1.png)
![grep issue2](https://user-images.githubusercontent.com/33706212/50406316-1249f580-0791-11e9-8730-90beb2edd42d.png)

**Comment by diizzyy** [comment]
I wouldn't be surprised if some script relies on busybox grep specific behaviour and by replacing it with gnu grep stuff breaks. This is why I don't think we shouldn't replace distro applications, perhaps a better solution is to place it in a directory where it doesn't replace busybox grep.

**Comment by wapebira** [comment]
It looks like something is trying to use the busybox grep version. But don't know how to take the necessary logs to investigate any further. I tested with grep 2.26 just to make sure is not greo 3.1 issue and the problem persists.

**Comment by wapebira** [comment]
Sorry for mentioning you as maintainer. I correct the initial post.

**Comment by neheb** [comment]
Does this still happen with 19.07?

**Comment by neheb** [comment]
Closing due to timeout. If still an issue, please reopen.

**Comment by natumbri** [comment]
Still happens in trunk...

**Comment by neheb** [comment]
Can you debug?

**Comment by natumbri** [comment]
Hi @neheb - I can't at the moment, but on a miwifi mini, installing the grep package broke a working system and restoring the link to busybox (without removing grep) fixed it.  I might be able to look more closely in a few weeks. Really difficult to spot when it happens - who would have thought installing grep could break anything?!

**Comment by neheb** [comment]
My guess is that this is either a problem with base-files or with netifd.

The way to test this is to replace all instances of grep with busybox grep and see if it works.
