### ISSUE TITLE
jq: running immediately causes segmentation fault

### ISSUE THREAD

**Issue by MikePetullo** [openwrt/packages#7785]
Maintainer: @ratkaj 
Environment: x86_64, OpenWrt master

Description:
Running "jq" immediately generates a segmentation fault.

I tried running jq in GDB. It seems that the line "`jq_set_attr(jq, jv_string("JQ_ORIGIN"), jv_string(dirname(origin)));`" in src/main.c is causing the segmentation fault. I see this just before executing this line:

```
(gdb) print origin
$1 = 0xfffffffff7f85c20 <error: Cannot access memory at address 0xfffffffff7f85c20>
```

Indeed, running "`set origin = argv[0]`" in GDB allows execution to continue, at least to the point the program prints its help message.

It appears strdup is failing for some reason.

**Comment by MikePetullo** [comment]
See also the following reports:

https://github.com/stedolan/jq/issues/1598
https://github.com/stedolan/jq/issues/1676

**Comment by ldvc** [comment]
Hi! Just installed `jq` on my new Turris Mox and get the `Segmentation fault` error.
Is the binary in the opkg repo still not refreshed?

More info:
```
root@turris:~# cat /etc/openwrt_version
d4ba1f0
root@turris:~# cat /etc/openwrt_release
DISTRIB_ID='TurrisOS'
DISTRIB_RELEASE='4.0-beta7'
DISTRIB_REVISION='d4ba1f0'
DISTRIB_TARGET='mvebu/cortexa53'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='TurrisOS 4.0-beta7 d4ba1f0'
DISTRIB_TAINTS='busybox'
root@turris:~# uname -ar
Linux turris 4.14.132 #0 SMP Mon Jul 22 23:09:55 2019 aarch64 GNU/Linux
root@turris:~# opkg list-installed | grep jq
jq - 1.5-2.0
```

**Comment by neheb** [comment]
@ldvc I just pushed the fix to the openwrt-18.06 branch. I don't know how TurrisOS packaging works.

**Comment by BKPepe** [comment]
I've just found it. @ldvc the cherry-picked commit made it into Turris OS 4.0-beta8 release, which was released 4 days ago. May I ask you to update your OS and let us know if it works?

**Comment by ldvc** [comment]
@BKPepe thanks! `jq` is working properly on 4.0-beta9.
