### ISSUE TITLE
luci-app-acme: Accept keylength ec-256, ec-384

### ISSUE THREAD

**Issue by andersk** [openwrt/packages#7825]
Maintainer: @tohojo
Environment: ar71xx, TL-WDR3600 v1, OpenWrt 18.06.1

Description:

The `acme.sh --keylength` parameter [accepts](https://github.com/Neilpang/acme.sh#10-issue-ecc-certificates) `ec-256` or `ec-384` to get an ECDSA certificate, instead of just a number to get an RSA certificate. I just verified after manually running `uci set acme.example.keylength=ec-256` that the script successfully gets an ECDSA certificate that works with `uhttpd`. ECDSA is way faster than RSA on my device, to the point where I saw it making the difference between the realtime graphs working smoothly and not working at all.

The only missing piece is that `luci-app-acme` currently [only accepts a number](https://github.com/openwrt/packages/blob/5240700752d734664afb9e65aeed599b4c0965af/net/acme/files/acme-cbi.lua#L56-L59) for `keylength`. Can we add `ec-256` and `ec-384` as valid values?

**Comment by andersk** [comment]
Thanks! For what it’s worth, the Let’s Encrypt servers don’t support RSA keys longer than 4096 bits. If you try to select RSA 8192, your device spends like 20 minutes generating a key before you get

```
run-acme[498]: Sign failed: "detail":"Invalid key in certificate request :: key too large: 8192 \u003e 4096"
```

and you wonder what made you think it sounded like a fun idea to actually try that. Maybe take out the RSA 8192 option and put in RSA 3072 instead?

**Comment by tohojo** [comment]
Anders Kaseorg <notifications@github.com> writes:

> Thanks! For what it’s worth, the Let’s Encrypt servers don’t support RSA keys longer than 4096 bits. If you try to select RSA 8192, your device spends like 20 minutes generating a key before you get
>
> ```
> run-acme[498]: Sign failed: "detail":"Invalid key in certificate request :: key too large: 8192 \u003e 4096"
> ```
>
> and you wonder what made you think it sounded like a fun idea to
> actually try that. Maybe take out the RSA 8192 option and put in RSA
> 3072 instead?

Right, good point (and thanks for testing!). Fixed :)
