### ISSUE TITLE
xl2tpd: Network error

### ISSUE THREAD

**Issue by adililhan** [openwrt/packages#7890]
Hi,

OpenWRT Version: 18.06.1
xl2tpd version: xl2tpd-1.3.12
uname -a: Linux OpenWrt 4.9.120 #0 Thu Aug 16 07:51:15 2018 mips GNU/Linux

I've installed xl2tpd on my OpenWRT router. I've configured the xl2tpd. However, it doesn't connect to my server. I'm absolutely sure the credentials are correct. The credentials are working fine on my computer.

Some outputs:

cat /etc/xl2tpd/xl2tp-secrets:

`* * SERVER_SHARED_KEY_HERE`

cat /etc/xl2tpd/xl2tpd.conf

> [global]
> port = 1701
> auth file = /etc/xl2tpd/xl2tp-secrets
> access control = no
> 
> ;[lns default]
> ;exclusive = yes
> ;ip range = 192.168.254.202-192.168.254.210
> ;lac = 10.0.1.2
> ;hidden bit = no
> ;local ip = 192.168.254.200
> ;length bit = yes
> ;refuse authentication = yes
> ;name = VersaLink
> ;ppp debug = yes
> ;pppoptfile = /etc/ppp/options.xl2tpd
> 
> ;[lac left]
> ;lns = 10.0.1.2
> ;refuse authentication = yes
> ;name = VersaLink
> ;ppp debug = yes
> ;pppoptfile = /etc/ppp/options.xl2tpd

cat /etc/config/network

> config interface 'thel2tp'
> 	option proto 'l2tp'
> 	option server 'L2TP_SERVER_IP'
> 	option username 'MY_USER'
> 	option password 'MY_PASS'
> 	option defaultroute '0'
> 	option keepalive 12
> 	option mtu 1410

When I start the L2TP service I get this error:

> daemon.notice xl2tpd[1180]: Maximum retries exceeded for tunnel 22298.  Closing.
> daemon.info xl2tpd[1180]: Connection 0 closed to L2TP_SERVER_IP, port 1701 (Timeout)
> daemon.debug xl2tpd[1180]: Unable to deliver closing message for tunnel 22298. Destroying anyway.

When I start the L2TP service I get this error sometimes:

```
xl2tpd: message repeated 3 times: [ udp_xmit failed to L2TP_SERVER_IP with err=-1:No such device]
```

This error sounds familiar with https://github.com/xelerance/xl2tpd/issues/147

Is there any idea regarding this problem?

**Comment by yousong** [comment]
upstream issue xelerance/xl2tpd#168

**Comment by yousong** [comment]
close for long inactivity.  Feel free to report back if things change.
