### ISSUE TITLE
CircleCI / python{,3}: Doesn't fail on missing dependencies

### ISSUE THREAD

**Issue by cshoredaniel** [openwrt/packages#7915]
So I found out the hard way that CircleCI will pass python packages which have dependencies on other python packages, even if the other packages are not actually available.  This probably should be considered a fatal error, as otherwise things can look fine that will have missing dependencies when merged.

**Comment by thess** [comment]
Can I have another hint? Example?

**Comment by cshoredaniel** [comment]
Also https://github.com/openwrt/packages/pull/7871 should have failed as it depends on vobject which isn't in the tree yet.

**Comment by cshoredaniel** [comment]
And vobject https://github.com/openwrt/packages/pull/7900 should have failed because it was pushed before the python3-dateutil update.

**Comment by cshoredaniel** [comment]
A combination of factors has interfered with working on much of anything non-local for 2-3 months now and in any event I am considering dropping OpenWrt from my roster of 'Things To Do' even when the difficulties are resolved, as I need to consider where too allocate my limited time.
