### ISSUE TITLE
prosody 10: package request

### ISSUE THREAD

**Issue by vfiuchcikicshuusrch** [openwrt/packages#7916]
Environment: armv7 k2.6

Description:
Need package prosody 10 or 11. v.9 crashes everytime.
need support for database via lua-dbi-*

**Comment by gonsalez-ru** [comment]
As for me, nigtly builds of Prosody v.Trunk are more functional and reliable.
https://prosody.im/nightly/trunk/latest/

**Comment by vfiuchcikicshuusrch** [comment]
what about dependecies ?

**Comment by neheb** [comment]
Prosody has been updated.
