### ISSUE TITLE
new package request: tinyssh

### ISSUE THREAD

**Issue by mistepien** [openwrt/packages#7919]
https://tinyssh.org/

Small ssh2 server with public key authorization only, working in inetd mode.

**Comment by neheb** [comment]
Not sure how to package this. This requires an SSH key to be generated before it can be used. OpenSSH has ssh-keygen and dropbear has its own thing as well.

Shipping built-in keys would be a nono.

**Comment by neheb** [comment]
Here's a skeleton (it doesn't work): https://github.com/neheb/packages/commit/b0139c009f73c65610b468c9f7cdd14ccc6213f0
