### ISSUE TITLE
Help compile gitea software

### ISSUE THREAD

**Issue by caifenglin** [openwrt/packages#7929]
Gitea is a very good lightweight git warehouse management software. I hope it can run on openwrt. Can I compile a gitea ipk package? Thank you very much!
Link：https://github.com/go-gitea/gitea

**Comment by caifenglin** [comment]
I'd like to help you with any good tutorials on openwrt compiler software, but I don't know much about Linux and I don't have any good tutorials.

**Comment by diizzyy** [comment]
Hi,
Please use the forums ( https://forum.openwrt.org/ ) instead as package "requests" are not handled in the "Issues" section
