### ISSUE TITLE
ulogd2 json timestamp 1969 without realtime clock

### ISSUE THREAD

**Issue by CanadianJeff** [openwrt/packages#7934]
this bug only affects devices that do not have a real time clock [RTC] installed in them

my APU2 is a full on x86 board and comes with a bios battery and [RTC] to keep date/time across reboots

my TP-LINK WDR4300 is just a simple store bought cheapo router which does the have a [RTC] installed so the timestamps in ulogd firewall logs all show up as 1969 even after the device has grabbed the updated date time from a valid NTP server

**Comment by CanadianJeff** [comment]
not sure if this bug exists in the new version 2.0.7 listed on the official website
https://netfilter.org/projects/ulogd/downloads.html

**Comment by CanadianJeff** [comment]
the file in question would be
https://git.netfilter.org/ulogd2/tree/output/ulogd_output_JSON.c
and
https://github.com/openwrt/packages/tree/master/net/ulogd

**Comment by neheb** [comment]
My guess is that this line is the problem: https://git.netfilter.org/ulogd2/tree/output/ulogd_output_JSON.c#n299

No idea why they don't use use time(NULL)

**Comment by neheb** [comment]
Maybe check /var/log/ulogd.log for any hints.

**Comment by neheb** [comment]
Yeah I was right: https://git.netfilter.org/ulogd2/commit/?id=2b39df550fbad944b4aab77617d4272c5d62ba70

It seems this packet timestamp routine is failing.

**Comment by CanadianJeff** [comment]
closing this issue as it might no longer be needed feel free to reopen
