### ISSUE TITLE
acme: acme wrongly update nginx or uhttpd when selecting ECC certificates

### ISSUE THREAD

**Issue by hzdrro** [openwrt/packages#7941]
If you selected ECC certificates, the path of certificates would be set wrongly to "$STATE_DIR/${main_domain}/" rather than "$STATE_DIR/${main_domain}_ecc/".

**Comment by satmandu** [comment]
@tohojo Do you have a preferred method of changing this?

The logic in https://github.com/openwrt/packages/blob/master/net/acme/files/run.sh#L213 seems to require handling the renaming of staging directories as well when modifying the ${main_domain} in paths. Can the acme_args variables tell us if an ECC certificate is selected, or do we have to check for the existence of a "$STATE_DIR/${main_domain}_ecc/" folder?

**Comment by tohojo** [comment]
Well, the upstream script just matches on keylength starting with ec-, so I guess we could do the same :)
