### ISSUE TITLE
minidla metadata.c:806: debug: Unhandled audio codec

### ISSUE THREAD

**Issue by FireCulex** [openwrt/packages#7965]
Appears to be Vorbis. Unhandled audio codec [0x15005]

$sudo opkg list | grep "vorbis"
libvorbis - 1.3.6-1
$

File 1:
Audio #1
ID                                       : 2
Format                                   : Vorbis
Format settings, Floor                   : 1
Codec ID                                 : A_VORBIS
Duration                                 : 32 min 39 s
Bit rate mode                            : Variable
Bit rate                                 : 48.0 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 11.2 MiB (9%)
Writing application                      : HandBrake
Writing library                          : aoTuV 20110424 (UTC 2011-04-24)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

File 2:
Audio #1
ID                                       : 2
Format                                   : Vorbis
Format settings, Floor                   : 1
Codec ID                                 : A_VORBIS
Duration                                 : 32 min 39 s
Bit rate mode                            : Variable
Bit rate                                 : 48.0 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 11.2 MiB (9%)
Writing application                      : HandBrake
Writing library                          : aoTuV 20110424 (UTC 2011-04-24)
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

They are unrelated except for being in Japanese, 2 audio streams and they apparently both used same writing library.

I have a 3rd larger file with the same writing library thats crashing the router itself.  Tried to write the kernel log to a mounted drive but reveal anything. WNDR3800.

I'm also seeing unhandled audio codecs [0x1502D] and [0x15029]

**Comment by diizzyy** [comment]
Not a bug, you need to select the "right" (the ones you need) codecs.

**Comment by diizzyy** [comment]
@hnyman @thess
Please close, not a bug

**Comment by diizzyy** [comment]
If you want a possible quick fix (it's not ideal on MIPS boxes but should work) you can try to import this:

https://github.com/diizzyy/packages/tree/ffmpeg4/multimedia/ffmpeg4
https://github.com/diizzyy/packages/tree/multimedia-minidlna/multimedia/minidlna

Make sure you select ffmpeg4 before selecting minidlna
