### ISSUE TITLE
ddns-scripts: Fix update url response of ddnss.de

### ISSUE THREAD

**Issue by jkirk** [openwrt/packages#8013]
The response of the DynDNS service `ddnss.de` looks like this (even if no IP change took place):
```
<head>
<meta name="robots" content="noindex">
<title>DDNSS - Kostenloser DynDNS Service : Re-ProutDNS v5.01v</title>
</head>
<body>
<p><font face="Verdana" size="2"></font></p>
<p><font face="Verdana" size="2">Updated 1 hostname.</font></p>
</body>
```

I think `"good|nochg"` should be changed to `"Updated"` in the following line, right?:

https://github.com/openwrt/packages/blob/c059c283fed882885afb2c854ea9c55700df8d4c/net/ddns-scripts/files/services#L60

**Comment by neheb** [comment]
PR welcome.

Note that ddns-scripts are unmaintained.
