### ISSUE TITLE
nlbwmon: does not show previous period stats

### ISSUE THREAD

**Issue by fantom-x** [openwrt/packages#8034]
Maintainer: @jow- 
Environment: Netgear R7800, the latest 18.06

The display page "Netlink Bandwidth Monitor" shows a drop down box to chose an accounting period, but chosing a different period does not change the data displayed. It seems like it is only displaying the current period only.
I am seeing this issue in MacOS with Firefox and Chrome.

**Comment by jow-** [comment]
Dupe of https://github.com/jow-/nlbwmon/issues/25
