### ISSUE TITLE
Stunnel

### ISSUE THREAD

**Issue by micky1067** [openwrt/packages#8056]
(Stunnel) 
This time I find only stunnel in version 5.44-3. Is there a Chance to become the new version 5.49 for arm7 systems. 
In the old version I can not bind localhost to ports. 

I use it for a netgear r7000. 
Thanks

**Comment by diizzyy** [comment]
It's not backported.
Current version is 5.49 so you can either build your own firmware or use snapshots.

**Comment by micky1067** [comment]
Thanks for your information.
Means it will never give a new ipk for entware? Or can I compile my own one?
I don't know how to do make firmware or snapshot...

**Comment by diizzyy** [comment]
@micky1067 
I have no idea what entware tracks (follows) so you need to ask the maintainers for that project.

**Comment by diizzyy** [comment]
@thess @hnyman 
Please close
