### ISSUE TITLE
pulseaudio -- deadlocak while dlopen and dlclose

### ISSUE THREAD

**Issue by zeusshuang** [openwrt/packages#8067]
Hi Experts,

I got problem while running pulseaudio, it cause deadlock after running dlopen and dlclose several times.
It's on ARM embedded system, is anyone have suggestions ?

Thanks,

**Comment by diizzyy** [comment]
Provide information which makes your report useful...

master branch or release of OpenWrt? musl or glibc? master branch of packages? Versions of libraries? Which application triggers a deadlock?

**Comment by neheb** [comment]
uClibc-ng is listed as BROKEN. It's only kept around because of the ARC target. Closing.
