### ISSUE TITLE
acme: consider moving luci-app-acme to openwrt/luci

### ISSUE THREAD

**Issue by dengqf6** [openwrt/packages#8078]
Maintainer: @tohojo 

Description:
Please consider moving luci-app-acme to openwrt/luci

**Comment by tohojo** [comment]
Deng Qingfang <notifications@github.com> writes:

> Maintainer: @tohojo 
>
> Description:
> Please consider moving luci-app-acme to openwrt/luci

I already considered that and decided not to. It (a) doubles the
maintenance work and (b) makes it harder to keep package versions in
sync.
