### ISSUE TITLE
acme: credentials not loaded for cert renewal

### ISSUE THREAD

**Issue by dauriata** [openwrt/packages#8081]
Maintainer: @tohojo

When using credentials in the /etc/config/acme file, those credentials are not loaded when renewing a certificate but only when issuing new ones. 

This behaviour can be fixed by moving this code :
```
  handle_credentials() {
        local credential="$1"
        eval export $credential
    }
    config_list_foreach "$section" credentials handle_credentials
```
up before this part : 

```
if [ -e "$STATE_DIR/$main_domain" ]; then
        if [ "$use_staging" -eq "0" ] && is_staging "$main_domain"; then
            log "Found previous cert issued using staging server. Moving it out of the way."
            mv "$STATE_DIR/$main_domain" "$STATE_DIR/$main_domain.staging"
            moved_staging=1
        else
            log "Found previous cert config. Issuing renew."
            $ACME --home "$STATE_DIR" --renew -d "$main_domain" $acme_args || return 1
            return 0
        fi
    fi
```

I can make a PR if needed

**Comment by tohojo** [comment]
Adrien DAURIAT <notifications@github.com> writes:

> Maintainer: @tohojo
>
> When using credentials in the /etc/config/acme file, those credentials
> are not loaded when renewing a certificate but only when issuing new
> ones.

Ah yes; for the longest time I was convinced that the credentials are
not needed for renewing. But you're right of course, they can be :)

> I can make a PR if needed

Sure, please do!

**Comment by neheb** [comment]
Wait this was fixed in https://github.com/openwrt/packages/pull/8083 . Closing.
