### ISSUE TITLE
i2pd package improvements

### ISSUE THREAD

**Issue by dartraiden** [openwrt/packages#8088]
@yangfl

1) subscriptions.txt is not used by i2pd daemon and [deprecated](https://github.com/PurpleI2P/i2pd/issues/890#issuecomment-308394499) so we can remove it from Makefile

https://github.com/openwrt/packages/blob/a50f269411ba6538665ff840e44f5d9eab8b9834/net/i2pd/Makefile#L42
https://github.com/openwrt/packages/blob/a50f269411ba6538665ff840e44f5d9eab8b9834/net/i2pd/Makefile#L60

2) It's better to use INSTALL_CONF instead of INSTALL_BIN for configs

https://github.com/openwrt/packages/blob/a50f269411ba6538665ff840e44f5d9eab8b9834/net/i2pd/Makefile#L55
https://github.com/openwrt/packages/blob/a50f269411ba6538665ff840e44f5d9eab8b9834/net/i2pd/Makefile#L61

**Comment by neheb** [comment]
This is fixed.
