### ISSUE TITLE
ddns-scripts:  add no-ip.com support for ipv6

### ISSUE THREAD

**Issue by jimstever1** [openwrt/packages#8095]
While configuring IPv6 on my network and setting up with my ddns provider, no-ip.com I found the support is missing from opewrt packages.

http://www.noip.com/support/knowledgebase/what-is-an-ipv6-or-aaaa-record/

**Comment by neheb** [comment]
That's handled by the ddns-scripts_no-ip_com package. Closing.

**Comment by EmbeddedG** [comment]
Opened new issue with corrected subject: #11152
