### ISSUE TITLE
Asterisk 11 srtp: not supporting key lifetime and will fail if an application uses it

### ISSUE THREAD

**Issue by schoerg** [openwrt/packages#811]
It was fixed there:
https://issues.asterisk.org/jira/browse/ASTERISK-17721

https://issues.asterisk.org/jira/secure/attachment/50695/srtpMKI_Asterisk11.patch

I tried to compile this on my own, but I get an
Module 'res_srtp.so' was not compiled with the same compile-time options as this version of Asterisk.
error when I try SRTP connections.

**Comment by jslachta** [comment]
Hi @schoerg,

I moved the issue to telephony repository issue tracker. Closing it here.
