### ISSUE TITLE
CC/Luci - all-zero mac address for eth0 reported on Archer C7v2

### ISSUE THREAD

**Issue by stangri** [openwrt/packages#812]
![screen shot 2015-01-22 at 14 51 55](https://cloud.githubusercontent.com/assets/4768176/5866560/6efb1646-a247-11e4-9620-ca78706e7363.png)

As seen above luci reports an incorrect mac address for eth0. ifconfig reports the actual mac address tho.

Not sure if it's limited to Archer C7v2. 

Here's the Luci version from the footer: Powered by LuCI (git-15.017.51462-30d45d0).

**Comment by jow-** [comment]
Please paste the full output of "ubus call network.interface dump" and "ubus call network.device status"

**Comment by stangri** [comment]
Uhm, you said full, but I've sanitized it a little for obvious reason.

ubus call network.interface dump:
{
	"interface": [
		{
			"interface": "cfg0c4d8f",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"uptime": 65665,
			"l3_device": "br-lan",
			"proto": "static",
			"device": "br-lan",
			"updated": [
				"addresses"
			],
			"metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "192.168.1.11",
					"mask": 24
				}
			],
			"ipv6-address": [

			],
			"ipv6-prefix": [

			],
			"ipv6-prefix-assignment": [

			],
			"route": [

			],
			"dns-server": [

			],
			"dns-search": [

			],
			"inactive": {
				"ipv4-address": [

				],
				"ipv6-address": [

				],
				"route": [

				],
				"dns-server": [

				],
				"dns-search": [

				]
			},
			"data": {

			}
		},
		{
			"interface": "lan",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"uptime": 65665,
			"l3_device": "br-lan",
			"proto": "static",
			"device": "br-lan",
			"updated": [
				"addresses"
			],
			"metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "192.168.1.1",
					"mask": 24
				}
			],
			"ipv6-address": [

			],
			"ipv6-prefix": [

			],
			"ipv6-prefix-assignment": [
				{
					"address": "fd8d:b5d0:1059::",
					"mask": 60
				}
			],
			"route": [

			],
			"dns-server": [

			],
			"dns-search": [

			],
			"inactive": {
				"ipv4-address": [

				],
				"ipv6-address": [

				],
				"route": [

				],
				"dns-server": [

				],
				"dns-search": [

				]
			},
			"data": {

			}
		},
		{
			"interface": "loopback",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"uptime": 65665,
			"l3_device": "lo",
			"proto": "static",
			"device": "lo",
			"updated": [
				"addresses"
			],
			"metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "127.0.0.1",
					"mask": 8
				}
			],
			"ipv6-address": [

			],
			"ipv6-prefix": [

			],
			"ipv6-prefix-assignment": [

			],
			"route": [

			],
			"dns-server": [

			],
			"dns-search": [

			],
			"inactive": {
				"ipv4-address": [

				],
				"ipv6-address": [

				],
				"route": [

				],
				"dns-server": [

				],
				"dns-search": [

				]
			},
			"data": {

			}
		},
		{
			"interface": "wan",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"uptime": 3453,
			"l3_device": "eth0",
			"proto": "dhcp",
			"device": "eth0",
			"metric": 0,
			"delegation": false,
			"ipv4-address": [
				{
					"address": "",
					"mask": 27
				}
			],
			"ipv6-address": [

			],
			"ipv6-prefix": [

			],
			"ipv6-prefix-assignment": [

			],
			"route": [
				{
					"target": "0.0.0.0",
					"mask": 0,
					"nexthop": "",
					"source": ""
				}
			],
			"dns-server": [
				"8.8.8.8",
				"8.8.4.4"
			],
			"dns-search": [

			],
			"inactive": {
				"ipv4-address": [

				],
				"ipv6-address": [

				],
				"route": [

				],
				"dns-server": [
					"",
					""
				],
				"dns-search": [
					"unet.ca"
				]
			},
			"data": {

			}
		}
	]
}

ubus call network.device status:
{
	"br-lan": {
		"external": false,
		"present": true,
		"type": "Bridge",
		"up": true,
		"carrier": true,
		"bridge-members": [
			"eth1",
			"wlan0",
			"wlan1"
		],
		"macaddr": "c4:6e:1f:b8:62:1e",
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 181904521,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 2560790,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 8,
			"tx_aborted_errors": 0,
			"tx_packets": 3465741,
			"rx_errors": 0,
			"tx_bytes": 3167728194,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"eth0": {
		"external": false,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"link-advertising": [
			"1000F"
		],
		"link-supported": [
			"1000F"
		],
		"speed": "1000F",
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 3016258869,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 2044350,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 1093124,
			"rx_errors": 0,
			"tx_bytes": 85993839,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"eth1": {
		"external": false,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"ipv6": false,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 4270081365,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 7348560,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 3,
			"tx_aborted_errors": 0,
			"tx_packets": 4502688,
			"rx_errors": 0,
			"tx_bytes": 3100679872,
			"tx_window_errors": 0,
			"rx_fifo_errors": 4,
			"tx_carrier_errors": 0
		}
	},
	"lo": {
		"external": false,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 33776157,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 496533,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 496533,
			"rx_errors": 0,
			"tx_bytes": 33776157,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"wlan0": {
		"external": true,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"ipv6": false,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 261568754,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 2502391,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 3809423,
			"rx_errors": 0,
			"tx_bytes": 3272334323,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"wlan1": {
		"external": true,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"ipv6": false,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 104425265,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 1380749,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 4022739,
			"rx_errors": 0,
			"tx_bytes": 1398958204,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	}
}

**Comment by jow-** [comment]
Ok, so this problem is not LuCI related, the mac address information is not exposed via ubus for eth0/eth1.

**Comment by stangri** [comment]
As I have no idea about how ubus is supposed to work, could you then please open the bug in openwrt project tracker when you close this one?

**Comment by champtar** [comment]
@stangri @jow-, can we close this one?

**Comment by stangri** [comment]
It's not a Luci bug, but it's still a bug -- the mac address information is not exposed via ubus for eth0/eth1. Either a new one needs to be opened (and I do not understand ubus stuff so it would be great if developers opened it) and this one closed or this one needs to be adjusted and kept open. Your call.

**Comment by FedericoVaga** [comment]
I stumbled upon the same issue. From *sysfs* and *ifconfig* I get the correct MAC address. But from *ubus* (so luci) the MAC address is not there. It's not clear to me how *ubus* get the information from the system.

**Comment by stangri** [comment]
I no longer own an Archer C7v2. If the problem persists for other users, maybe they could open an issue against ubus, but I'm closing this as I can't even confirm it's still an issue.
