### ISSUE TITLE
Boost does not build if no libraries are selected

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#8146]
Maintainer: @ClaymorePT 
Environment: master

Errors with

```
cp: cannot stat '/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/boost_1_69_0/ipkg-install/lib/*.so*': No such file or directory
```

There's only a single .la file in usr/lib, so this fails.

edit: this situation I ran into with a package not depending on boost but having PKG_BUILD_DEPENDS:=boost

**Comment by ClaymorePT** [comment]
I'll check it out. Thank you for pointing the issue.

**Comment by NickSchaf** [comment]
Would it be possible to apply this fix to the 18.06 branch?

**Comment by ClaymorePT** [comment]
@NickSchaf I think that can be arranged. 

@neheb Can specific commits like these be cherrypicked to the 18.06 branch?

**Comment by neheb** [comment]
https://github.com/openwrt/packages/commit/d8ecf9cb7c8ea949b212809d6a8a64a35041c49f
