### ISSUE TITLE
Adblock: Adguard list blocks Disconnect.me list

### ISSUE THREAD

**Issue by guinhas** [openwrt/packages#8148]
Maintainer: @dibdot 
Environment: Adblock 3.5.1 using Kresd as DNS Backend, Target: mvebu, Architecture: arm-cortex-a9, Turris Omnia, OpenWrt omnia 15.05 r47055

Description:

```
When Adguard list is enabled, Disconnect.me list can't be reached. Adguard list, somehow, blocks https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt. Thank you.
```

**Comment by guinhas** [comment]
Never mind. I added the latest version of Adblock's Adguard config and everything is working now. I shouldn't be using old versions of the package. Sorry and thank you for your work.

**Comment by dibdot** [comment]
With forthcoming Turris OS 4.x you can safely update to current adblock 3.6.x - I've already tested this setup.
