### ISSUE TITLE
LUCI DDNS error

### ISSUE THREAD

**Issue by meganetrix** [openwrt/packages#8171]
I just updated the latest Luci DDNS and this is what I get after the update when I go to services and click on DDNS

Failed to execute cbi dispatcher target for entry '/admin/services/ddns'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/ddns.lua:107: attempt to index field '?' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/ddns.lua:107: in function 'service_version'
	/usr/lib/lua/luci/controller/ddns.lua:117: in function 'service_ok'
	/usr/lib/lua/luci/model/cbi/ddns/overview.lua:20: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:838: in function </usr/lib/lua/luci/dispatcher.lua:832>

Tried reloading the software, clearing cache but no luck I can't get into the DDNS page  

# Issue template (remove lines from top till here)

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

Description:

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by dibdot** [comment]
wrong repo, please use issue tracker under openwrt/luci for such errors or ask in the forum first. 
To fix this issue, please do not remove package 'opkg' from your build.
