### ISSUE TITLE
mariadb: mariadb-server-plugin-ha-innodb is not longer available

### ISSUE THREAD

**Issue by p4u** [openwrt/packages#8199]
Maintainer: @micmac1 
Environment: master/snapshot

Description:

`mariadb-server-plugin-ha-innodb` is not longer available, why?

**Comment by micmac1** [comment]
Because xtradb isn't available in 10.2 and innodb is the default (baked-in).

**Comment by p4u** [comment]
So it's expected to not have innodb support anymore on OpenWRT? Many databases will broke...

**Comment by p4u** [comment]
Sorry I did not read your reply correctly, forget my previous comment.

So if innodb is the default, should be enabled when installing mariadb-server. But in my tests it did not work. I'll try again to be sure.
