### ISSUE TITLE
new package request: rrredir

### ISSUE THREAD

**Issue by lars18th** [openwrt/packages#8202]
https://github.com/rofl0r/rrredir

RR Redir - Round-Robin Port Redirector:
This is a port redirector program like the well-known `redir`, but with the ability to specify more than one target ip/port which will be tried one after the other in round-robin fashion, until the connection succeeds.

**Comment by lars18th** [comment]
No one interested?

**Comment by diizzyy** [comment]
Hi,
Package requests are not handled in the "Issues" sections
