### ISSUE TITLE
nfs-kernel-server: exportfs segfault

### ISSUE THREAD

**Issue by DazzyWalkman** [openwrt/packages#8205]
Maintainer: @tripolar
Environment: (x86_64, OpenWrt snapshot r9305-0c24b363a6, nfs-kernel-server - 2.3.3)

Description:
I make snapshot builds from source and test them in Virtualbox. 
nfs-kernel-server is build clean, related configs are all package-defaults.
When boot up, kernel squawk:

> [11.352013] exportfs[3728]: segfault at 28 ip 00007f4118256afe sp 00007ffcaff55430 error 4 in libc.so[7f4118233000+48000]

Switching from kernel 4.14 to 4.19 made no difference.

No such problem in the build of Feb 2, 2019, snapshot r9254-3b40121530.  

Here are similar observations from different user on other target:
https://bugs.openwrt.org/index.php?do=details&task_id=2105

**Comment by tripolar** [comment]
should be fixed with https://github.com/openwrt/packages/commit/274ce493eb4baacf9748ed795e22b178611c92d4
