### ISSUE TITLE
prometheus: Builds have been failing

### ISSUE THREAD

**Issue by jefferyto** [openwrt/packages#8210]
Maintainer: @aparcar 
Environment: too many to list here

Description:
Faillogs:

* [aarch64_generic](https://downloads.openwrt.org/snapshots/faillogs/aarch64_generic/packages/prometheus/)
* [arm_cortex-a15_neon-vfpv4](https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/prometheus/)
* [i386_pentium](https://downloads.openwrt.org/snapshots/faillogs/i386_pentium/packages/prometheus/)
* [mips_24kc](https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/prometheus/)
* and many more

Looks like it is failing because `bzr` isn't installed on buildbots.

**Comment by aparcar** [comment]
Can't we install `bzr` on the buildbots?

**Comment by aparcar** [comment]
If I remember correctly we did the same for the CI build containers...

**Comment by diizzyy** [comment]
The general rule of thumb is to not require additional external deps except the ones specified/required by OpenWrt. I personally think that requiring bzr on host should be avoided if possible.

**Comment by jefferyto** [comment]
As @neheb [noted](https://github.com/openwrt/packages/pull/8451#issuecomment-475034811), upstream has removed the bzr dependency (prometheus/prometheus#5378). I assume the change will be reflected in the next upstream release.

**Comment by aparcar** [comment]
@jefferyto could you helpme backport that patch to 2.8.0? Or would that be a waste of time?

**Comment by jefferyto** [comment]
Fixed by #8468.
