### ISSUE TITLE
SslStrip: update package request

### ISSUE THREAD

**Issue by risinek** [openwrt/packages#8215]
Hi,
I would be really grateful, if somebody is able to update sslStrip package to latest version from official repo.
Current version is outdated and there are some issues using it with current browsers..

I tried to make a package by myself, but without success, so I'm trying it this way, as someone here is probably used to build packages for openWRT.

Thanks in advance!

**Comment by diizzyy** [comment]
Version bumps are not "bugs", if you run you into issues can ask for help in the OpenWrt forums.
