### ISSUE TITLE
ddns-script duckdns problem

### ISSUE THREAD

**Issue by dnecro** [openwrt/packages#8221]
there is missing setting in duckdns provider.

I needed to add manually **option "username"** in /etc/config/ddns file because it don't give me that option  in luci nor it created when setup completed.

**Comment by dibdot** [comment]
According to duckdns FAQ the update is token based, e.g. `https://www.duckdns.org/update?domains=abc&token=064a0540-864c-4f0f-8bf5-23857452b0c1&ip=`. Therefore there is no need to input a username.
