### ISSUE TITLE
coovachilli does not force upload limit

### ISSUE THREAD

**Issue by gilfrade** [openwrt/packages#8222]
Using coova-chilli 1.4 (latest) but this was already an issue with 1.3.2.

``` bash
00-00-00-00-00-00 10.255.255.3 pass 5c65c6cb00000002 1 00-00-00-00-00-00@demo 857/0 0/0 27011267/0 36785705/0 0 1 99%/2097152 0%/2097152 http://xpto
```

As you can see RADIUS rules seems enforced on chilli (2Mbps UP, 2Mbps DOWN) and Download is correctly enforced but in case of Uploading clients do not have a limit. In this example the client upload speed was 10Mbps.

I have two radios (wlan0  and wlan1) in a bridge (br-lanportal) and configured chilli to use it.
xt_coova is loaded and i already tried the ethtool -K "iface" gso off gro off tso off trick with no success.

If tun0 from chilli really is trying to enforce upload rule but somehow packets are being forward directly anyway then is it a firewall problem?

@teslamint any thoughts?

**Comment by teslamint** [comment]
That's a long and old upstream problem without solid solution AFAIK.
