### ISSUE TITLE
banIP: banip.sh[xxx] sort: out of memory

### ISSUE THREAD

**Issue by vovan69** [openwrt/packages#8226]
Maintainer: @neheb/p112
Environment: mips_24kc/ar71xx/generic/WNDR3700/r9330-880f8e6d32

Description:

If I enable the firehol2 list, I see
```
banip.sh[xxxxx]: sort: out of memory
```
and the list isn't processed.
The system has 64M of memory.
```
              total        used        free      shared  buff/cache   available
Mem:          59896       22112       21820        3532       15964       16768
Swap:             0           0           0
```

Regards,
Vlad.

**Comment by dibdot** [comment]
You can try to install 'coreutils-sort', maybe it behaves better than the busybox variant - if not, this list is to heavy for your router.
