### ISSUE TITLE
perl: spurious build failures on openwrt-18.06 branch

### ISSUE THREAD

**Issue by mweinelt** [openwrt/packages#8238]
Maintainer: @pprindeville
Environment: 
- Build Host: Debian 9.8 (x86_64)
- Build Target: brcm2708-bcm2710, mpc85xx-generic
- OpenWrt https://github.com/openwrt/openwrt/commit/62feabecd8a84cfe0d6a5aa3bad2720dbf328370
- packages.git https://github.com/openwrt/packages/commit/d05b98c6c86da58db5cbda3c945007be09583609

Description:
I'm regularly building OpenWrt 18.06 through the Gluon mesh framework. Building Perl spuriously fails every once in a while. I managed to capture a build log this time.

brcm2708-bcm2710: https://gist.github.com/mweinelt/50691b00d47dd1cb6107d1c183182f02
mpc85xx-generic: https://gist.github.com/mweinelt/1925156fbca42559f5dae24c7c1dc234

**Comment by mweinelt** [comment]
5d3cb594e49132158ca7b41f4246421078e8f92a

brcm2708-bcm2708
https://gist.github.com/mweinelt/9bec3e1559b94bd34f683c120a4c0761

**Comment by mweinelt** [comment]
Still failing on

**Comment by mweinelt** [comment]
Still failing on 619961596091449e8c95d98e591e02745b086a71.
https://github.com/freifunk-gluon/gluon/runs/578339551?check_suite_focus=true

Meanwhile I've disabled parallel builds of perl and I've yet to encounter this build failure again:

```
From: Martin Weinelt <martin@darmstadt.freifunk.net>
Date: Wed, 19 Jun 2019 01:28:44 +0200
Subject: parallel: don't build in parallel

diff --git a/lang/perl/Makefile b/lang/perl/Makefile
index b92b00279631ae07a0f23b063571d97eb8ed3efc..81dbfcdd5bd6cad92b9552f491b200fc85fd0084 100644
--- a/lang/perl/Makefile
+++ b/lang/perl/Makefile
@@ -33,8 +33,8 @@ PKG_BUILD_DIR:=$(BUILD_DIR)/perl/$(PKG_NAME)-$(PKG_VERSION)
 HOST_BUILD_DIR:=$(BUILD_DIR_HOST)/perl/$(PKG_NAME)-$(PKG_VERSION)
 PKG_INSTALL:=1
 PKG_BUILD_DEPENDS:=perl/host
-PKG_BUILD_PARALLEL:=1
-HOST_BUILD_PARALLEL:=1
+PKG_BUILD_PARALLEL:=0
+HOST_BUILD_PARALLEL:=0
 
 # Variables used during configuration/build
 HOST_PERL_PREFIX:=$(STAGING_DIR_HOSTPKG)/usr
```

**Comment by pprindeville** [comment]
Odd that this isn't a problem with the nightlies.

**Comment by pprindeville** [comment]
Is this still going on?  Do you have a root-cause?

**Comment by mweinelt** [comment]
It's spurious, so it will take me a while to reproduce, as I've used said patch for the last year or so.

**Comment by mweinelt** [comment]
Yep, still failing. Attaching a proper log from the package build.
[compile.txt](https://github.com/openwrt/packages/files/5992022/compile.txt)

**Comment by blocktrron** [comment]
@pprindeville Any objections against merging this? This issue has been present for quite some time but never occurred with this fix.

**Comment by mweinelt** [comment]
Can still reproduce this :tada: and would appreciate a decision.

**Comment by mweinelt** [comment]
It's finally here! :)
