### ISSUE TITLE
OpenSSL fails compiling on current snapshot (version mismatch)

### ISSUE THREAD

**Issue by NexusAlpha** [openwrt/packages#8267]
When trying to build OpenWRT for the WR841N v13 it fails because OpenSSL is a dependency of something (and I don't know what because I'd like to use WolfSSL anyway). The error is "syntax error in VERSION script" within compiling libcrypto.so, it expects 1.1.1a but get 1.1.1 and sees it as a version mismatch and exits.

**Comment by diizzyy** [comment]
Wrong repo (OpenSSL is in base distribution not in the package repo) and http://www.catb.org/esr/faqs/smart-questions.html#beprecise

**Comment by NexusAlpha** [comment]
Happens on the Turris Omnia as well, both using GCC 8.2. The base repo doesn't allow opening issues and I thought it's a package so my bad then.
