### ISSUE TITLE
Transmission problem

### ISSUE THREAD

**Issue by fuqiang03** [openwrt/packages#8276]
![qq 20190222220157](https://user-images.githubusercontent.com/26851715/53247170-a7b02a00-36ed-11e9-84cf-f0f89608b7a0.png)
Unable to start under openwrt 18.06 branch

**Comment by neheb** [comment]
I've seen this issue under different circumstances. Either reboot the router or run /etc/init.d/transmission start manually.

I have no idea why this happens.

**Comment by fuqiang03** [comment]
Upgrade to the new "Luci" problem
The SHELL file needs to be modified
I replaced it with someone else's source code.

**Comment by fuqiang03** [comment]
![qq 20190226181331](https://user-images.githubusercontent.com/26851715/53405263-6de36a00-39f2-11e9-840f-2c6b286da6dd.png)
![qq 20190226181415](https://user-images.githubusercontent.com/26851715/53405266-6f149700-39f2-11e9-96bc-7bfcc289fbf8.png)

**Comment by diizzyy** [comment]
@hnyman @thess 
Please close
