### ISSUE TITLE
collectd-mod-mqtt cannot connect via ssl

### ISSUE THREAD

**Issue by arkhub** [openwrt/packages#8288]
Maintainer: @hnyman  @jow- 
Environment: 
OpenWRT 18.06.2
collectd-moq-mqtt  5.8.1-1
libmosquitto-ssl 1.5.6-1 and 1.5.7-1 (default from 18.06.2 are 1.5.6-1 which try to upgrade to 1.5.7-1)

Description:
I plan to send collectd output to mqtt (cloudmqtt) via ssl by installing collectd-mod-mqtt and adding new files in ```/etc/collectd/conf.d/``` which contains :
```
LoadPlugin mqtt
<Plugin "mqtt">
  # Send values to an MQTT server
  <Publish "cloudmqtt">
    Host "<cloudmqtt domain>"
    Port "<secure port>"
    User "<cloudmqtt user>"
    Password "<cloudmqtt password>"
    ClientId "<my device name>"
    QoS 0
    Prefix "collectd"
    Retain true
    CACert "/etc/ssl/certs/COMODO_RSA_Certification_Authority.crt"
    TLSProtocol tlsv1.2
  </Publish>
</Plugin>
```
I restart collectd and type "collectd -T" which shows ```plugin_load: plugin "mqtt" successfully loaded.```, however when I view the log from cloudmqtt says :
 ```<date and time>: New connection from <my device ip address> on port <ssl port>.``` 
followed by long silent then the next message says : 
```
<date and time>: OpenSSL Error: error:140780E5:SSL routines:SSL23_READ:ssl handshake failure
<date and time>: Socket error on client <unknown>, disconnecting.
<date and time>: Client <unknown> has exceeded timeout, disconnecting.
```
I tried changing  multiple setting in .conf like "TLSProtocol" and different ca certificate to no avail, however changing the port to non secure cloudmqtt success, I can see data transmitted from my router / device. Also running mosquitto_pub with the same certificate result in success. Is there something that I miss?

**Comment by hnyman** [comment]
Related to 18.06.2 with old collectd etc.
