### ISSUE TITLE
smartmontools failing with buildbots

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#8300]
https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/smartmontools/compile.txt as an example. I think it has to do with the new drivedb work.

@mstorchak

**Comment by mstorchak** [comment]
It's working now. I was not able to download that log - it was already gone when I noticed this bug.
https://downloads.openwrt.org/snapshots/packages/x86_64/packages/smartmontools-drivedb_7.0-2_all.ipk

**Comment by mstorchak** [comment]
https://downloads.openwrt.org/snapshots/faillogs/arm_arm1176jzf-s_vfp/packages/smartmontools/compile.txt contains
```
cp: cannot overwrite non-directory '/opt/buildbot/slaves/lede-slave-tah/arm_arm1176jzf-s_vfp/build/sdk/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/root-brcm2708/./usr/share/smartmontools' with directory '/opt/buildbot/slaves/lede-slave-tah/arm_arm1176jzf-s_vfp/build/sdk/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/smartmontools-7.0/.pkgdir/smartmontools-drivedb/./usr/share/smartmontools'
```
which looks like a result from improper cleanup of the previous build. Before #8220 the *file* `/usr/share/smartmontools` contained drive database, and now it's a directory containing `drivedb.h`

**Comment by mstorchak** [comment]
@neheb , is there anything  I can do from my side?

**Comment by diizzyy** [comment]
@neheb 
Looks like this is resolved on the buildbots?

**Comment by neheb** [comment]
It appears from time to time. But doesn't look like a big deal. Closing.
