### ISSUE TITLE
File dependency error “gnunet”

### ISSUE THREAD

**Issue by fuqiang03** [openwrt/packages#8331]
Description:
File dependency error
openwrt 18.06
![qq 20190303124337](https://user-images.githubusercontent.com/26851715/53691112-7650f180-3db2-11e9-9ca8-7e85a76f0a52.png)

**Comment by dangowrt** [comment]
Fixed by
https://github.com/openwrt/packages/commit/0ba0e0d1b533b0fc7dc47180e38f729a84ddf020
https://github.com/openwrt/packages/commit/cb253649a0ac9def03e2bfc6913b3721261fb3be
https://github.com/openwrt/packages/commit/5fff8047252a78196eed483a7a868b730dc4b494
