### ISSUE TITLE
cmake.ipk

### ISSUE THREAD

**Issue by caojing1996** [openwrt/packages#8340]
i want to install kaa terminal in openwrt,but it need install cmake ,i can not find any cmake.ipk.mably i should  make a kaa.ipk and then install it in openwrt?

**Comment by diizzyy** [comment]
Use the toolchain and make a package
https://openwrt.org/docs/guide-developer/packages

You can close this now

**Comment by diizzyy** [comment]
@hnyman @thess 
Please close
