### ISSUE TITLE
ddns-scripts: dyn.com update for IPV6 fails with nochng response code

### ISSUE THREAD

**Issue by jwepaterson** [openwrt/packages#8360]
Maintainer: @mark0n 
Environment: TP-Link Archer C7 v2, Qualcomm Atheros QCA9558 ver 1 rev 0, OpenWrt 18.06.2 r7676-cddd7b4c77

Description:

Attempting to update the IPV6 address with dyn.com fails to change the IPV6 address with a return code of nochng and the existing IPV4 address.  

Looking at the logs, it appears that the script is using the legacy update URL (see https://help.dyn.com/remote-access-api/perform-update/).  Using the legacy update URL in a browser results in the same behaviour.

Attempting to update just the IPV6 address using the new update URL (see https://help.dyn.com/remote-access-api/perform-update/) updates the IPV6 address but removes the IPV4 address.  Updating with just the IPV4 address removes the AAAA record.  To update both addresses, they both must be included in a comma separated list with the myip parameter, but ddns-scripts does not allow the update of both IPV4 and IPV6 at the same time.

**Comment by maody** [comment]
Hello.

I am quite new to all of this: openWrt, ipv6, dndns... and just spent a whole day searching for a fix on my my router not being able to update the dyndns.org ipv6 record correctly. Finally found this issue report. 

I think it is quite easy to fix:

Change the legacy update URL: 
http://{username}:{password}@members.dyndns.org/nic/update?hostname={yourhostname}&myip={ipaddress}&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG
in dyndns update script to the new one:
https://{user}:{updater client key}@members.dyndns.org/v3/update?hostname={hostname}&myip={IP4 Address},{IP6 Address} 
and let users select both IP Versions in luci.
