### ISSUE TITLE
 Instance unbound::unbound s in a crash loop 6 crashes, 0 seconds since last crash

### ISSUE THREAD

**Issue by birdie-github** [openwrt/packages#8364]
I'm running [OpenWRT 18.06.2](http://downloads.openwrt.org/releases/18.06.2/targets/ar71xx/generic/openwrt-18.06.2-ar71xx-generic-tl-wdr3600-v1-squashfs-sysupgrade.bin)

```
# opkg install unbound
Installing unbound (1.8.1-1) to root...
Downloading http://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/packages/unbound_1.8.1-1_mips_24kc.ipk
Installing zlib (1.2.11-2) to root...
Downloading http://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/base/zlib_1.2.11-2_mips_24kc.ipk
Installing libopenssl (1.0.2q-1) to root...
Downloading http://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/base/libopenssl_1.0.2q-1_mips_24kc.ipk


Installing libunbound (1.8.1-1) to root...
Downloading http://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/packages/libunbound_1.8.1-1_mips_24kc.ipk
Configuring zlib.
Configuring libopenssl.
Configuring libunbound.
Configuring unbound.
unbound: default root hints (built in rootservers.net)
unbound: default protocol configuration
unbound: default memory configuration
unbound: default recursion configuration
```

```
Fri Mar  8 13:06:35 2019 daemon.info unbound: [2881:0] info: service stopped (unbound 1.8.1).
Fri Mar  8 13:06:35 2019 daemon.info unbound: [2881:0] info: server stats for thread 0: 1088 queries, 1088 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
Fri Mar  8 13:06:35 2019 daemon.info unbound: [2881:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
Fri Mar  8 13:07:06 2019 daemon.info procd: Instance unbound::unbound s in a crash loop 6 crashes, 0 seconds since last crash
```

Scrap it. unbound crashes with **100% default config**.

**Comment by simonbytes** [comment]
Read the wiki: https://openwrt.org/docs/guide-user/services/dns/unbound

unbound needs to be configured besides dnsmasq (which is the standard dns server) or on top of dnsmasq.

**Comment by birdie-github** [comment]
Nothing in this manual says that any defaults must be changed, so that unbound could work.

It's crashing. That's a fact.

**Comment by EricLuehrsen** [comment]
You would get "can't bind port" errors if their were a conflict with dnsmasq. You did get 1088 lookup's before the crash. Are there any automatic lookups you have scripted when you boot such that there is a common domain each time? A domain with a weirdly recursive CNAME or malformed DNSSEC-RR may expose a Unbound bug in its normal robustness to these things. (Don't forget to @ericluehrsen the maintainer next time.)

**Comment by EricLuehrsen** [comment]
Maybe unrelated, but worth noting that Unbound 1.9.1 is being brought into 18.06 for OpenSSL 1.0.2 use improvements. #8395

**Comment by EricLuehrsen** [comment]
@hnyman no response from @birdie-github. what would be a fair countdown to close?

**Comment by birdie-github** [comment]
>  Are there any automatic lookups you have scripted when you boot such that there is a common domain each time?

No, nothing.

> Also what size of device do you have? Unbound allocates about 10MB RAM when it starts. (Don't forget to @EricLuehrsen the maintainer next time.)

```
root@OpenWrt:~# free
             total       used       free     shared    buffers     cached
Mem:        125272      37628      87644       1300       2308      13192
-/+ buffers/cache:      22128     103144
Swap:            0          0          0
```

Looks like I've got lots of free RAM, in fact over 85MB.

**Comment by EricLuehrsen** [comment]
In your log file Unbound did run and was stopped. It spit out the first two lines of closing session statistics. It was restarted and crashed on the restart. I must assume it was an interface up event. I have had this problem long ago on weaker routers. Unbound cannot close shop fast enough to be out of the way of the next session. I added a delay for this in init scripts a long time ago. Maybe you have a older device or a lot of other packages? Maybe the sleep isn't long enough for your use case. Maybe the procd ifup delay is not sufficient, if you have lots of packages dependent on ifup. You can tweak these and see if it solves your problem. Also have you tried 1.9.1-1? It uses openssl a bit cleaner and this may help some execution bottlenecks. 
**/etc/init.d/unbound**
```
stop_service() {
  ... ...
  # Wait! on restart Unbound may take time writing closure stats to syslog
  pidof $PROG && sleep 1
}

service_triggers() {
  ... ...
  PROCD_RELOAD_DELAY=2000
  ... ...
}
```

**Comment by birdie-github** [comment]
I launch unbound manually and it crashes, so timings/device speed/etc. most likely have nothing to do with this issue.

**Comment by EricLuehrsen** [comment]
I really don't know how to repeat your problem nor do I have reports of a similar problem on 17.01, 18.06, or master. I respect that people have good reason not to publish too much about their configuration, but I will need more that you are willing to share, because this does not seem to be a generic issue. I can suggest something to try to remove UCI from the loop and get more log information.
**/etc/config/unbound**
```
config unbound
    option manual_conf '1'
```
**/etc/unbound/unbound.conf**
```
    # verbosity number, 0 is least verbose. 1 is default.
    verbosity: 4
```

**Comment by birdie-github** [comment]
I'll get back to this issue once a new release of OpenWRT is made available.

**Comment by mariarti** [comment]
I had same issue, and for me helped command:
# `unbound-checkconf `
unbound-checkconf: no errors in /etc/unbound/unbound.conf

**Comment by birdie-github** [comment]
I've long switched to stubby - it's miles faster and more reliable.
