### ISSUE TITLE
tor: wants to own its storage directories

### ISSUE THREAD

**Issue by Traumflug** [openwrt/packages#8375]
Note: this misbehavior was observed when upgrading OpenWRT, which keeps settings and tor storage files from the previous installation, but requires to re-install the packages. I hope the description is correct.

Steps to reproduce:

- Have an OpenWRT installation (18.06.2 as of this report).
- Install tor:
    ```
    opkg update
    opkg install tor
    # (or by the graphical package manager)
    ```
- (Maybe one has to configure something in `/etc/tor/torrc` to get the thing barely running) 
- Try to run tor manually:
    ```
    tor -f /etc/tor/torrc
    ```

Expected result:
- Tor starting to serve.

Actual result
- Tor reports a problem:
    _/var/lib/tor is not owned by this user (tor, 52) but by root (0). Perhaps you are running Tor as the wrong user?_
- Fixing this, it starts up a bit further, but then reports errors again, this time to the system log:
    _/var/lib/tor/keys is not owned by this user (tor, 52) but by root (0). Perhaps you are running Tor as the wrong user?_

Workaround:
- After installation, connect to the router by command line and run this command:
    ```
    chown tor:tor /var/lib/tor /var/lib/tor/keys
    ```
- This command might be a good addition for the post-installation script.

Additional notes:
- As this was observed when updating, `/var/lib/tor` and `/var/lib/tor/keys` existed before package installation already, including their content, so there's a small chance this doesn't happen on a fresh installation.
- Obviously, package manager changes ownership of already existing directories back to root, without deleting their content.
- tor also wants restricted permissions for these directories:
    ```
    # ls -ld /var/lib/tor /var/lib/tor/keys
    drwx------    4 tor      tor            220 Mar 11 01:37 /var/lib/tor
    drwx------    2 tor      tor            220 Jan  1  1970 /var/lib/tor/keys
    ```
    However, tor manages to fix these permissions its self, so it's not a crucial issue.

# Issue template

Maintainer: @tripolar
Environment: (OpenWrt 18.06.2, should be hardware independent)

**Comment by tripolar** [comment]
should be fixed with https://github.com/openwrt/packages/commit/c6aa3d1fabff6dbf54bb2d081662fa6d2263b1be
