### ISSUE TITLE
shorewall: update to latest 5.2.0.x release (at least)?

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/packages#8382]
Maintainer: @wvdakker
Environment: 18.06

Description: I wonder if an update of the shorewall* packages to at least the most recent 5.2.0.x release could be made to pick up the latest bug fixes there.

In particular 5.2.0.5 fixes some locking specifically for OpenWRT.

**Comment by brianjmurrell** [comment]
I'd push a PR my self, but the 18.06.2 SDK seems to be acting up -- or more likely I'm just not remembering (or the steps have changed since I last used it) all of the magic incantations needed to get it to build select packages.

**Comment by wvdakker** [comment]
If you found a problem in the 5.2.0.x release can you submit an issue
on the version?It can be easier to track down the fixes/issues.Then I
will make a PR for the 18.06 branch.

**Comment by wvdakker** [comment]
PR made for 5.2.0.5

**Comment by brianjmurrell** [comment]
Thanks.

**Comment by diizzyy** [comment]
@brianjmurrell 
Please close this as it's resolved

**Comment by brianjmurrell** [comment]
@hnyman Was just waiting for the actual packages to show up at https://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/packages/ before closing this.

**Comment by wvdakker** [comment]
They will be available when 18.03 is released. Until then you have to build the package yourself.

**Comment by hnyman** [comment]
cc @jow- 

> > Was just waiting for the actual packages to show up at https://downloads.openwrt.org/releases/18.06.2/packages/mips_24kc/packages/ before closing this.
> 
> They will be available when 18.03 is released. Until then you have to build the package yourself.

No, the updated packages should be built immediately by the 18.06 buildbot.

I think that the 18.06 buildbot is temporarily offline since Tuesday morning, likely due to some unplanned incident.  Maybe @jow-  knows more.

**Comment by jow-** [comment]
@hnyman - right. The build cluster needs to be rebuilt due to some expired server sponsorship. Will hopefully done by Tuesday or Wednesday

**Comment by brianjmurrell** [comment]
Looks like it must be back online.  The new shorewall packages are there along with what looks like a full rebuild of all of the packages.

Cheers!
