### ISSUE TITLE
postgresql: dependency on zlib/host does not exist

### ISSUE THREAD

**Issue by EricLuehrsen** [openwrt/packages#8393]
:/home/github/openwrt-wrt-3200$ make menuconfig
WARNING: Makefile 'package/feeds/packages/postgresql/Makefile' has a build dependency on 'zlib/host', which does not exist

@dangowrt

**Comment by BKPepe** [comment]
Should be fixed by this: https://github.com/openwrt/packages/commit/d8e61d49da52e86994492c9c274da35dd3b214fc

**Comment by EricLuehrsen** [comment]
resloved
