### ISSUE TITLE
Toolchain compilation error

### ISSUE THREAD

**Issue by fuqiang03** [openwrt/packages#8419]
Description:
Ubuntu 18.06 
gcc8.3
glibc2.27
Router Model:WRT1900acs

Partial screenshots

![QQ截图20190316153006](https://user-images.githubusercontent.com/26851715/54472260-84fec600-4800-11e9-8274-6d20d5769d0a.png)
![QQ截图20190316153021](https://user-images.githubusercontent.com/26851715/54472261-85975c80-4800-11e9-801d-4baf8a1fbe09.png)
![QQ截图20190316153037](https://user-images.githubusercontent.com/26851715/54472262-85975c80-4800-11e9-9159-fb087ebc2875.png)

**Comment by fuqiang03** [comment]
![QQ图片20190316233901](https://user-images.githubusercontent.com/26851715/54477670-bef1bb80-4844-11e9-906c-b62465151e09.png)

**Comment by diizzyy** [comment]
Wrong repo...

Known bug on ARM
https://github.com/openwrt/openwrt/pull/1203 (HACK)
https://github.com/openwrt/openwrt/pull/1913 (Most likely better/proper fix)
