### ISSUE TITLE
LVM2.2.02.115.tgz file not present in source host and its mirror

### ISSUE THREAD

**Issue by ambrosa** [openwrt/packages#842]
Package LVM2
CC trunk@44234

My OpenWrt build today fails because package in subject is not present in redhat repo and its mirror.
Are present .114 and .116  version,  .115 is disappeared everywhere.

So I've upgraded myself feeds/packages/utils/lvm2/Makefile to download LVM2.2.02.116.tgz (md5sum 3a1104e3d1dc4d5e92a40228161cd660 ) and build is successful.

Please update LVM2 package with LVM2.2.02.116

**Comment by champtar** [comment]
fixed by ac2a414592bb7dd8bc9b77fa474b9b31a21d9c29
