### ISSUE TITLE
Zoneinfo : MD5 mismatch

### ISSUE THREAD

**Issue by ambrosa** [openwrt/packages#843]
Package feeds/packages/utils/zoneinfo
CC trunk@44234

mismatch MD5SUm in Makefile about file tzcode2015a.tar.gz
Correct is 8f375ede46ae137fbac047ac431bda37

Tzdata the same.
Correct md5 is 4ed11c894a74a5ea64201b1c6dbb8831

**Comment by hnyman** [comment]
Already fixed by https://github.com/openwrt/packages/commit/1b5d9a6fb37c7b55e3ee50593361aec6ce914e09

See discussion at https://github.com/openwrt/packages/pull/838#issuecomment-72360399 forwars
