### ISSUE TITLE
safe-search ; per mac support

### ISSUE THREAD

**Issue by acsdkquery** [openwrt/packages#8439]
Hi Gregory, 

Maintainer: @farmergreg
Environment: ddwrt, version - r7527-5849e2dd1b

Description:
Is it possible to have safe-search support per client (per MAC)?

**Comment by farmergreg** [comment]
Hi @acsdkquery,
Sorry, no, that can't be done easily.

With a lot of effort, it may be possible. Unfortunately I don't have the time to do that work. One option might be to have multiple dnsmasq instances and multiple lan zones. Then safe-search could protect one dnsmasq instance, while leaving the others alone.

**Comment by acsdkquery** [comment]
Ok. Thanks @farmergreg
