### ISSUE TITLE
How to set up the Openconnect client on Openwrt?

### ISSUE THREAD

**Issue by lordarthas1995** [openwrt/packages#8456]
Something was wrong, check it please!

```
Sat Mar 16 09:20:32 2019 daemon.info openconnect[20669]: POST https://209.141.33.97:8030/
Sat Mar 16 09:20:32 2019 daemon.info openconnect[20669]: Connected to 209.141.33.97:8030
Sat Mar 16 09:20:32 2019 daemon.info openconnect[20669]: SSL negotiation with 209.141.33.97
Sat Mar 16 09:20:32 2019 daemon.info openconnect[20669]: Server certificate verify failed: signer not found
Sat Mar 16 09:20:32 2019 daemon.notice openconnect[20669]: Server SSL certificate didn't match: sha256:b2d2d2806b16de44b421d97af477766e492f92b8afdb262530969764ed6e1c78
Sat Mar 16 09:20:32 2019 daemon.notice openconnect[20669]: SSL connection failure: Error in the certificate.
Sat Mar 16 09:20:32 2019 daemon.notice openconnect[20669]: Failed to open HTTPS connection to 209.141.33.97
Sat Mar 16 09:20:32 2019 daemon.notice netifd: openconnect (20669): Failed to obtain WebVPN cookie
Sat Mar 16 09:20:32 2019 user.notice openconnect: bringing down openconnect
Sat Mar 16 09:20:32 2019 daemon.notice netifd: Interface 'openconnect' is now down
Sat Mar 16 09:20:32 2019 daemon.notice netifd: Interface 'openconnect' is setting up now
```

**Comment by yousong** [comment]
Try adding `option serverhash <sha1-hash-of-the-crt>`

**Comment by lordarthas1995** [comment]
@yousong How to type this command line in SSH screen

**Comment by yousong** [comment]
You need to edit `/etc/config/network` and add that uci option to the `openconnect` section.  See the readme at https://github.com/openwrt/packages/tree/master/net/openconnect for an example.

**Comment by lordarthas1995** [comment]
@yousong 没用，在接口那里一直显示0发送0接收
这是系统内核日志

Wed Mar 20 18:29:21 2019 daemon.notice netifd: Interface 'openconnect' is setting up now
Wed Mar 20 18:29:21 2019 user.notice openconnect: initializing...
Wed Mar 20 18:29:21 2019 user.notice openconnect: adding host dependency for 209.141.33.97 at openconnect
Wed Mar 20 18:29:21 2019 user.notice openconnect: adding host dependency for 209.141.33.97 at openconnect
Wed Mar 20 18:29:21 2019 user.notice openconnect: executing 'openconnect 209.141.33.97:8030 -i vpn-openconnect --non-inter --syslog --script /lib/netifd/vpnc-script  --servercert=b2d2d2806b16de44b421d97af477766e492f92b8afdb262530969764ed6e1c78 --no-system-trust --authgroup DEFAULT -u admin'
Wed Mar 20 18:29:21 2019 daemon.info openconnect[31802]: POST https://209.141.33.97:8030/
Wed Mar 20 18:29:21 2019 daemon.info openconnect[31802]: Connected to 209.141.33.97:8030
Wed Mar 20 18:29:21 2019 daemon.info openconnect[31802]: SSL negotiation with 209.141.33.97
Wed Mar 20 18:29:21 2019 daemon.info openconnect[31802]: Server certificate verify failed: signer not found
Wed Mar 20 18:29:21 2019 daemon.notice openconnect[31802]: Server SSL certificate didn't match: sha256:b2d2d2806b16de44b421d97af477766e492f92b8afdb262530969764ed6e1c78
Wed Mar 20 18:29:21 2019 daemon.notice openconnect[31802]: SSL connection failure: Error in the certificate.
Wed Mar 20 18:29:21 2019 daemon.notice openconnect[31802]: Failed to open HTTPS connection to 209.141.33.97
Wed Mar 20 18:29:21 2019 daemon.notice netifd: openconnect (31802): Failed to obtain WebVPN cookie
Wed Mar 20 18:29:21 2019 user.notice openconnect: bringing down openconnect
Wed Mar 20 18:29:21 2019 daemon.notice netifd: Interface 'openconnect' is now down

**Comment by yousong** [comment]
Use `option serverhash sha256:b2d2d2806b16de44b421d97af477766e492f92b8afdb262530969764ed6e1c78` if you cannot get sha1 value.

**Comment by lordarthas1995** [comment]
> Use `option serverhash sha256:b2d2d2806b16de44b421d97af477766e492f92b8afdb262530969764ed6e1c78` if you cannot get sha1 value.

It not work
https://i.postimg.cc/hP1YXd5x/TIM-20190320201304.png
https://i.postimg.cc/9QxNpjVQ/TIM-20190320201349.png

**Comment by yousong** [comment]
please read the log and the reply here more carefully.

**Comment by lordarthas1995** [comment]
> please read the log and the reply here more carefully.

I do not understand why you close my issue?  Can you upload a video tutorial about how to set up Openconnect client on Openwrt? Please

And I don't know how to make "option serverhash sha256:xxx" work in /etc/config/network?
