### ISSUE TITLE
nfs-kernel-server: libevent2 dependency can be removed?

### ISSUE THREAD

**Issue by dengqf6** [openwrt/packages#8470]
Maintainer: @tripolar 
Environment: master
Description:
Seems like `gssd` and `rpc.idmapd` is the only two execs that use libevent2 functions:
https://git.linux-nfs.org/?p=steved%2Fnfs-utils.git&a=search&h=d38cdff811b1090b9ba4c7bb4b945dd0bdd4f0fc&st=grep&s=event.h
Since neither of them is installed, can the libevent2 dependency be removed?
I've tried removing the `+libevent2` in Makefile and it still built without "missing dependency" error.

**Comment by tripolar** [comment]
fix in 6d65505c26751d60cedee83383dc82cf067e7aa2
