### ISSUE TITLE
rpcbind: service will not start without warmstart support

### ISSUE THREAD

**Issue by marcin1j** [openwrt/packages#8476]
Maintainer: @Andy2244
Environment: ar71xx, TP-Link TL-WR710N v1, r9669

Description:
Rpcbind init script has fixed command line:
```
/usr/sbin/rpcbind -f -w 
```
However `-w` flag is supported only if `CONFIG_RPCBIND_WARMSTARTS` is enabled. As a result  daemon won't start unless it's compiled with warm start support.
Users will notice procd disabling rpcbind service because of a crash loop.

**Comment by Andy2244** [comment]
Thanks, seems like a oversight. 
Will just always build with warmstart support as a fix on next release.

**Comment by Andy2244** [comment]
fixed by #8510

**Comment by cotequeiroz** [comment]
#8510 was merged.  I'm closing this.
