### ISSUE TITLE
acme: luci-app-acme requires luci-lib-ipkg

### ISSUE THREAD

**Issue by karlp** [openwrt/packages#8529]
Maintainer: @tohojo 
Environment: master luci git.

Description:
the acme-cbi uses the luci.model.ipkg lua module to check what webserver is installed.  This module is "deprecated" in current luci, and has been moved to an extra package.  The acme app either needs to move to another method, or make sure it's depending on that package.

**Comment by tohojo** [comment]
Karl Palsson <notifications@github.com> writes:

> Maintainer: @tohojo 
> Environment: master luci git.
>
> Description:
> the acme-cbi uses the luci.model.ipkg lua module to check what
> webserver is installed.  This module is "deprecated" in current luci,
> and has been moved to an extra package.  The acme app either needs to
> move to another method, or make sure it's depending on that package.

Ah, bugger. Any suggestions for what "another method" might be?

**Comment by jow-** [comment]
Maybe a simple test for the actual executables? Like `nxio.fs.access("/usr/sbin/uhttpd")`

**Comment by tohojo** [comment]
Jo-Philipp Wich <notifications@github.com> writes:

> Maybe a simple test for the actual executables? Like
> `nxio.fs.access("/usr/sbin/uhttpd")`

Sure, can do...

**Comment by orangepizza** [comment]
but wouldn't it break with luci with nginx?

> 
> 
> Maybe a simple test for the actual executables? Like `nixio.fs.access("/usr/sbin/uhttpd")`

**Comment by jow-** [comment]
> but wouldn't it break with luci with nginx?

No.
