### ISSUE TITLE
pcre-8.42 configure: error: Invalid C++ compiler or C++ compiler flags 

### ISSUE THREAD

**Issue by porroso** [openwrt/packages#8594]
I get "configure: error: Invalid C++ compiler or C++ compiler flags" when compiling on OSX. Last error free revision for me is r9750. How to resolve?

**Comment by linbox1968** [comment]
I am running into the same issue today with latest trunk

**Comment by linbox1968** [comment]
How did you get it to work? I see you closed your comment from April 5

**Comment by linbox1968** [comment]
@porroso How did you solve it to close the issue you had April 5

**Comment by neheb** [comment]
Could be related to uclibc++. Try switching the c++ library to libstdcpp.

**Comment by linbox1968** [comment]
Thanks  --> I am not familiar how to do this. Do I change the make file of pcre? I usual don't have to dig that deep into the source code.

**Comment by linbox1968** [comment]
would I change the makefile?

This line

26 include $(INCLUDE_DIR)/uclibc++.mk 

what would I change it too?

**Comment by neheb** [comment]
Remove it and change $(CXX_DEPENDS) to +libstdcpp

**Comment by linbox1968** [comment]
Thanks that worked, but will I have to do this now all the time when I want to upgrade?

**Comment by neheb** [comment]
The fact that that worked indicates something broken with your setup.

**Comment by porroso** [comment]
> @porroso How did you solve it to close the issue you had April 5

@linbox1968 I'm sorry for very late reply, I simple switched to Debian since in Mojave I start to have problems compiling
