### ISSUE TITLE
xl2tpd startup errors

### ISSUE THREAD

**Issue by qiuzi** [openwrt/packages#860]
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 2851     1 root     R      880   1%  29% xl2tpd

xl2tpd[2851]: network_thread: recvfrom returned error 95 (Socket operation on non-socket)

**Comment by dangowrt** [comment]
Please provide info on the hardware you are running on, more complete logs and openwrt config, so I can try reproducing the issue.

**Comment by jow-** [comment]
Reporter went MIA
