### ISSUE TITLE
minidlna: new files are not indexed

### ISSUE THREAD

**Issue by craibuc** [openwrt/packages#8610]
minidlna: new files are not indexed.

Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: OpenWrt omnia 15.05 r47055 
Description: When new video files are added to the directory (`/mnt/raid/Media/Movies`) that is referenced in `/etc/config/minidlna`, they are not being indexed by the service.  Removing a file, however, is captured by the indexing mechanism.

To get new files indexed, I need to remove the minidlna directory:
```
# rm -rf /var/run/minidlna
```
then restart the service (in Luci).

Oddly enough, there isn't a log file in `/var/logs`.

At one point, the indexing services worked correctly, as did the logging feature.

The content of `/etc/config/minidlna`:

```
config minidlna 'config'
	option port '8200'
	option interface 'br-lan'
	option db_dir '/var/run/minidlna'
	option log_dir '/var/log'
	option log_level 'general,artwork,database,inotify,scanner,metadata,http,ssdp=debug'
	option inotify '1'
	option notify_interval '900'
	option serial '12345678'
	option model_number '1'
	option root_container '.'
	option album_art_names 'Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg'
	option friendly_name 'Turris'
	list media_dir 'V,/mnt/raid/Media/Movies'
	list media_dir 'V,/mnt/raid/Media/Series'
	list media_dir 'V,/mnt/raid/Media/Videos'
	list media_dir 'P,/mnt/raid/Media/Pictures'
	list media_dir 'A,/mnt/raid/Media/Music'
	option enabled '1'
```

**Comment by diizzyy** [comment]
@craibuc 
OpenWrt 15.X isn't supported and you're highly adviced to update to either 18.X, use snapshots (of master branch) or compile your own firmware of either of the previously mentioned branches.
