### ISSUE TITLE
zerotier: 1.2.8 (current 18.06.2 stable package) cannot orbit moons

### ISSUE THREAD

**Issue by ogarcia** [openwrt/packages#8630]
Maintainer: @mwarning 

Please update current stable package of zerotier because it have a BIG BUG and cannot orbit moons correctly: https://github.com/zerotier/ZeroTierOne/issues/744

In my case it fails every restart. Don't read the moons.d.

Ah. And would be great add support to orbit moons from configuration file. :wink:

**Comment by mwarning** [comment]
Merged. :-)
Moons are another topic.
