### ISSUE TITLE
perl-compress-bzip2 compile Error

### ISSUE THREAD

**Issue by love4taylor** [openwrt/packages#868]
/home/love4taylor/openwrt/trunk/staging_dir/target-arm_mpcore_uClibc-0.9.33.2_eabi/usr/lib/perl5/5.20/CORE/perl.h:2385:22: error: unknown type name 'off64_t'
 #       define Off_t off64_t
                      ^
/home/love4taylor/openwrt/trunk/staging_dir/target-arm_mpcore_uClibc-0.9.33.2_eabi/usr/lib/perl5/5.20/CORE/proto.h:8081:15: note: in expansion of macro 'Off_t'
 PERL_CALLCONV Off_t Perl_PerlIO_tell(pTHX_ PerlIO *f);
               ^
make[4]: *** [Bzip2.o] Error 1
make[4]: Leaving directory `/home/love4taylor/openwrt/trunk/build_dir/target-arm_mpcore_uClibc-0.9.33.2_eabi/perl/Compress-Bzip2-2.20'
make[3]: *** [/home/love4taylor/openwrt/trunk/build_dir/target-arm_mpcore_uClibc-0.9.33.2_eabi/perl/Compress-Bzip2-2.20/.built] Error 2
make[3]: Leaving directory `/home/love4taylor/openwrt/trunk/feeds/packages/lang/perl-compress-bzip2'
make[2]: *** [package/feeds/packages/perl-compress-bzip2/compile] Error 2
make[2]: Leaving directory `/home/love4taylor/openwrt/trunk'
make[1]: *** [/home/love4taylor/openwrt/trunk/staging_dir/target-arm_mpcore_uClibc-0.9.33.2_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/love4taylor/openwrt/trunk'

**Comment by Naoir** [comment]
Thank you for your report. Fixed in perl 5.20.1-4.
