### ISSUE TITLE
redis: add this package?

### ISSUE THREAD

**Issue by pansila** [openwrt/packages#8711]
Maintainer: if anyone can help
Environment: 18.06.2 or newer

Description:
Is it possible to add the redis to openwrt packages?

There has been an effort out [there](https://github.com/patrikx3/openwrt-redis), it would be nice to bring it to the upstream packages.

Thanks for your help,

**Comment by BKPepe** [comment]
You may ask @p3x-robot , if he is interested in upstreaming the package, which he maintain. ;-)

**Comment by diizzyy** [comment]
No package requests are considered "issues", closing.
