### ISSUE TITLE
nginx-ssl libopenssl1.1 SSL_CTX_set_next_protos_advertised_cb symbol not found

### ISSUE THREAD

**Issue by avengermsoft** [openwrt/packages#8729]
Last snapshot https://downloads.openwrt.org/snapshots/packages/mips_24kc

libopenssl1.1 - 1.1.1b-4 
nginx-ssl - 1.15.10-1

Start nginx - Error relocating /usr/sbin/nginx: SSL_CTX_set_next_protos_advertised_cb: symbol not found

Please reassemble libopenssl1.1 with SSL_CTX_set_next_protos_advertised_cb symbol.

**Comment by neheb** [comment]
nginx needs to be recompiled. A simple PKG_RELEASE bump will suffice.
