### ISSUE TITLE
nsd still being maintained?

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#8732]
@acinonyx  

Having looked at the package history (in current and master) with version 4.1.13 and compared to upstream version 4.1.27 I am curious thus whether the package is still actively maintained?

**Comment by neheb** [comment]
The answer is no

**Comment by n8v8R** [comment]
There are other packages that appear not being maintained any more. Why would such packages are not being marked as outdated/unmaintained, respectively being carried in the repo at all?

**Comment by neheb** [comment]
Would you like to take over? The package compiles.

**Comment by n8v8R** [comment]
I would not mind if I would have the resource to compile/build.

But that was not really question but rather why those package are not being marked as outdated/unmaintained - which would save opening this kind of thread?
Respectively being carried in the repo at all considering that features/security patches being missed and notwithstanding potential compatibility issues?

**Comment by acinonyx** [comment]
If you could submit an upgrade patch, I would be happy to compile and test it.

**Comment by n8v8R** [comment]
is it not compiled from upstream srouce https://www.nlnetlabs.nl/projects/nsd/download/ ?

**Comment by neheb** [comment]
He means a patch to the OpenWrt Makefile.
