### ISSUE TITLE
nfs-kernel-server: does not create nfs user

### ISSUE THREAD

**Issue by MikePetullo** [openwrt/packages#8746]
Maintainer: @tripolar
Environment: x86_64

Description:
/etc/init.d/nfsd now contains the line `chown nfs:nfs $VAR_NFS` and thus expects the nfs user and group to exist. The nfs-kernel-server package creates neither the nfs user or group. When I run `/etc/init.d/nfsd`, the script prints "chown: unknown user/group nfs:nfs."

**Comment by tripolar** [comment]
fixed in 20468cfef1d335fbe37979833a30b9d72acb071d
