### ISSUE TITLE
ntpclient never restart working while procps-ng-ps is installed

### ISSUE THREAD

**Issue by zhanhb** [openwrt/packages#8748]
https://github.com/openwrt/packages/blob/ffdbc7a637df8e3f39dd6916405f78840edccfb4/net/ntpclient/files/ntpclient.hotplug#L69
Command `ps` will only got two processes as following once `procps-ng-ps` is installed.
```
  PID TTY          TIME CMD
13773 pts/0    00:00:00 ash
20022 pts/0    00:00:00 ps
```

**Comment by zhanhb** [comment]
Maybe busybox ps should be used here.

**Comment by neheb** [comment]
Could also replace it with ps aux.

**Comment by zhanhb** [comment]
I execute `ps w`, got as following.
```
  PID TTY      STAT   TIME COMMAND
  476 ttyS0    Ss+    0:00 /sbin/askfirst /usr/libexec/login.sh
 9947 pts/1    Ss     0:00 -ash
23382 pts/1    R+     0:00 ps w
```

**Comment by neheb** [comment]
Guess the BusyBox solution is the one.

**Comment by neheb** [comment]
@zhanhb please test https://github.com/openwrt/packages/pull/8803

**Comment by zhanhb** [comment]
I replace the script file, work as expected. No issue for package `ntpclient`.
