### ISSUE TITLE
Openconnect should backup the folder /etc/openconnect

### ISSUE THREAD

**Issue by ravageralpha** [openwrt/packages#882]
Since there is hook script support therefore should backup the folder instead of cert files only.

**Comment by nmav** [comment]
What isn't included in the current backup?

**Comment by ravageralpha** [comment]
Currently the pacakge backup cert files only:

```
/etc/openconnect/user-cert-vpn-*.pem
/etc/openconnect/user-key-vpn-*.pem
/etc/openconnect/ca-vpn-*.pem
```

So i think since the vpnc-script have implemented the hook script support therefore it should backup the folders as well.

```
/etc/openconnect/connect.d/
/etc/openconnect/post-connect.d/
/etc/openconnect/disconnect.d/
/etc/openconnect/post-disconnect.d/

```
