### ISSUE TITLE
snort3: fails to build

### ISSUE THREAD

**Issue by rakesh2215** [openwrt/packages#8839]
Maintainer: @W. Michael Petullo <mike@flyn.org>
Environment: (x86_64, OpenWrt snapshot SDK)

Tried building snort3 with latest x86_64 sdk.
Failing to build with below error:

```
  The C++ compiler

    "openwrt_sdk/openwrt-sdk-x86-64_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/bin/x86_64-openwrt-linux-musl-g++"

  is not able to compile a simple test program.

  
    openwrt_sdk/openwrt-sdk-x86-64_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/bin/../lib/gcc/x86_64-openwrt-linux-musl/7.4.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -ltirpc
```

**Comment by cshoredaniel** [comment]
Occurs with ath79 as well.

**Comment by Strykar** [comment]
@rakesh2215 Have you tried with current, you can checkout the release you want? I've had trouble building with the SDK in the past. Using snort 2 here.

**Comment by rakesh2215** [comment]
Current release 18.6.2 doesn't have snort3.
Snort3 Makefile is added only in snapshot.
Do you mean I use this Makefile and build with 18.6.2?

**Comment by cshoredaniel** [comment]
@flyn-org

**Comment by cshoredaniel** [comment]
@flyn-org Buildbots see it too: https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/snort3/compile.txt

**Comment by neheb** [comment]
That build failure has to do with not having host GCC 32-bit binaries.

Is the libtirpc error still an issue?

**Comment by DaveRush82** [comment]
> That build failure has to do with not having host GCC 32-bit binaries.
> 
> Is the libtirpc error still an issue?

Which libtirpc error?

**Comment by rakesh2215** [comment]
@DaveRush82     

openwrt_sdk/openwrt-sdk-x86-64_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/bin/../lib/gcc/x86_64-openwrt-linux-musl/7.4.0/../../../../x86_64-openwrt-linux-musl/bin/ld: **cannot find -ltirpc**

**Comment by flyn-org** [comment]
I was able to build snort3 using the current openwrt-sdk-bcm47xx-generic_gcc-11.2.0_musl.Linux-x86_64. @rakesh2215, is this still and issue?

**Comment by rakesh2215** [comment]
probably not.

**Comment by hnyman** [comment]
Currently builds ok for master in buildbot.
