### ISSUE TITLE
stubby: support resolver option tls_port (uci)

### ISSUE THREAD

**Issue by bjmi** [openwrt/packages#8889]
Maintainer: @jonathanunderwood 
Environment: 18.06.02

Description:

Some dns servers aren't bind to default ports therefore stubby supports _tls_port_ in _upstream_recursive_servers_ section.

The corr. resolver option in uci is missing.

Please support within _config resolver_ an
```
option tls_port
```
and _README.md_ should mention this resolver option.

**Comment by jonathanunderwood** [comment]
PRs are always welcome ;) I'll have a look at this when I update to 0.2.6.

**Comment by jonathanunderwood** [comment]
This has been implemented in the 18.06 and master branches. 

This issue can be closed.
