### ISSUE TITLE
opennhrp: depends on ipsec-tools, which is being removed

### ISSUE THREAD

**Issue by nmeyerhans** [openwrt/packages#8904]
Maintainer: @DerArtem 
Environment: any

Description:

As documented in #7832, ipsec-tools is being removed from the packages repository. Because opennhrp depends on ipsec-tools, it will be broken by this change. I am not familiar with opennhrp, so I don't know what components of ipsec-tools it uses, or if it already supports alternatives, but it would be advisable to look into this. If it depends on racoon for IKE negotiations, consider migrating to [strongswan](/openwrt/packages/net/strongswan) or [libreswan](/openwrt/packages/net/libreswan). If it just depends on the setkey tool, then `ip xfrm` should be a suitable replacement.

**Comment by lucize** [comment]
this https://github.com/openwrt-routing/packages/pull/319 claims to have nhrp support, didn't test it

**Comment by nmeyerhans** [comment]
opennhrp was removed with #9881
