### ISSUE TITLE
snmpd crash loop

### ISSUE THREAD

**Issue by lleachii** [openwrt/packages#8926]
Upgraded to OpenWrt SNAPSHOT r9945-bc85640cdc, I'm now receiving:

`Tue May 7 15:04:40 2019 daemon.info procd: Instance snmpd::instance1 s in a crash loop 6 crashes, 0 seconds since last crash`

Snapshots a few days ago worked.

**Comment by diizzyy** [comment]
Platform? Any changes to default config?

**Comment by lleachii** [comment]
- Installed on apm821xx.
- I'm using default snmpd file from opkg.

**Comment by lleachii** [comment]
- I was unable to reproduce the issue on another apm821xx device
- Re flashing the same device with r9945-bc85640cdc and reinstalling seems to have solved the issue

Thanks for your time and attention.

**Comment by lleachii** [comment]
- This has reoccurred using r10084-b97d44af67
- This time, I **am able** to reproduce the issue on an identical device
- Re flashing does not solve the issue this time

```
root@OpenWrt:~# opkg list-installed | grep snmp
libnetsnmp - 5.8-1
snmpd - 5.8-1
```

**Comment by lleachii** [comment]
https://forum.openwrt.org/t/snmpd-crash-loop/37779

**Comment by lleachii** [comment]
Also occurs on OpenWrt SNAPSHOT r10124-405e08bee6

**Comment by lleachii** [comment]
No crash loop with OpenWrt SNAPSHOT r10127-3209f5ae3d

**Comment by diizzyy** [comment]
Closing this as it's resolved

**Comment by lleachii** [comment]
Upgraded from OpenWrt SNAPSHOT r10325-b16faf9bc7 (working)

Now not working: OpenWrt SNAPSHOT r10494-e05310b9b8

**Comment by diizzyy** [comment]
Hmm... I wonder if it's some kind of race condition as it seems to occur randomly. Could you try compiling r10325 and r10494 by hand and see if it you get the same results as it may be a specific buildbot that's causing the issues.
