### ISSUE TITLE
ddns-scripts: error on startup

### ISSUE THREAD

**Issue by spdrl60** [openwrt/packages#8971]
Maintainer: @\<github-user>
Environment: ddns-scripts - 2.7.8-1

Description: When using a read-only filesystem there is an error on startup of ddns, because in the file "dynamic_dns_functions.sh" in the function "get_service_data" there is the command "mkfifo pipe_$$" which causes the error. Moving the pipe to a temporary filesystem will solve this problem.

**Comment by dibdot** [comment]
@spdrl60 could you please test above mentioned fix for your issue? Thanks!
