### ISSUE TITLE
gammu: not found

### ISSUE THREAD

**Issue by bruceleerabbit** [openwrt/packages#8985]
Maintainer: @aTanW or @neheb or @micmac1 
Environment:
$ uname -r
4.14.95

Description:
I'm looking to install [gammu](https://github.com/openwrt/packages/tree/master/utils/gammu).  When I run `opkg list | grep gammu` there is nothing.  Is this caused by the [migration](https://github.com/openwrt/packages/issues/8893) to python 3?  Someone mentioned having [trouble](https://github.com/openwrt/packages/issues/1522) building it.  I don't even see how to build it.  The Gammu [installation guide](https://github.com/gammu/gammu/blob/master/docs/manual/project/install.rst) neglects openwrt.

**Comment by neheb** [comment]
which platform?

**Comment by neheb** [comment]
I see it here: https://downloads.openwrt.org/releases/18.06.2/packages/mipsel_74kc/packages/gammu_1.38.4-2_mipsel_74kc.ipk

**Comment by bruceleerabbit** [comment]
Oh, sorry for the trouble.. apparently I needed do an `opkg update`.
