### ISSUE TITLE
[feature suggestion] logrotate - enable ACL

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#9004]
Maintainer: @bk138 
Environment: current | Master

Description: Not sure why ACL is explicitly stripped?

`CONFIGURE_ARGS += --with-acl=no`

**Comment by bk138** [comment]
6cb753511af5d128369c38e0f1f847e512faf888 introduced this. Git blame can help you find this yourself :-)

**Comment by n8v8R** [comment]
I have seen it and that was not the the question - why ACL is explicitly stripped?

**Comment by neheb** [comment]
Do you have a usecase for ACL?

**Comment by n8v8R** [comment]
yes

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/9373

**Comment by cotequeiroz** [comment]
Fixed by #9373.
