### ISSUE TITLE
nfs-kernel-server: fail to host compile

### ISSUE THREAD

**Issue by wongsyrone** [openwrt/packages#9017]
Description:

It is introduced by samba4's host compilation dependencies and complains `fail to find rpcgen or use --with-rpcgen`, I fix it by adding `--with-rpcgen=internal` to HOST_CONFIGURE_ARGS

**Comment by wongsyrone** [comment]
Maintainer: @tripolar

**Comment by BKPepe** [comment]
2 days ago, @tripolar  committed it to master branch -https://github.com/openwrt/packages/commit/c86fdd679ba5431b3f9e6dc44cd2c59abeeba822 . 

Can you please confirm it that it helps and close this issue?
