### ISSUE TITLE
libfstrm: missing URL and TITLE is too long

### ISSUE THREAD

**Issue by BKPepe** [openwrt/packages#9022]
Maintainer: @James-TR

Description:

Recently added package #8983 has formal issues.

- Missing URL
- Mixing tabs and 2 spaces. Use 2 spaces in the description instead of tabs.
- PKG_TITLE is too long and that's why the title isn't shown in make menuconfig
![image](https://user-images.githubusercontent.com/4096468/57957823-00165280-78fe-11e9-9a1e-8dc79f37f71b.png)

Not sure, but isn't there missing dependency, which has @ja-pa in his [Makefile](https://gitlab.labs.nic.cz/turris/turris-os-packages/commit/953d0ed46e9c0769e6ed53b1759bde2984356c71) in his dev branch?

**Comment by James-TR** [comment]
Hello, I am not aware of any missing dependencies for this package and have confirmed it works correctly already. PR #9027 should resolve the remaining issues with formatting and even fixed up the description as it did not show correctly.

**Comment by James-TR** [comment]
The dependency for libevent2 is not required as it is only used to build the example programs provided by the package, which are disabled by passing the "--disable-programs" CONFIGURE flag.

As addressed in the fstrm github:
> Reference programs fstrm_capture, fstrm_dump, and fstrm_replay are provided. In order to build fstrm_capture, the libevent library must be installed. The option --disable-programs can be passed to configure to disable building these programs.
