### ISSUE TITLE
gst1-plugins-bad : mpegtsdemux fails to install

### ISSUE THREAD

**Issue by bhargavbhoot** [openwrt/packages#9143]
Maintainer: W. Michael Petullo <mike@flyn.org> (@flyn-org )
                   Ted Hess <thess@kitschensync.net> (@thess )

Environment: (put here arch, model, OpenWrt version)

Description: enabling the mpegtsdemux fails with the following message : 

Package gst1-mod-mpegtsdemux is missing dependencies for the following libraries:
libgstcodecparsers-1.0.so.0
libgstmpegts-1.0.so.0

I have checked in the build_dir mpegtsdemux, mpegts and codecparsers are getting compiled. but anyhow the plugin mpegtsdemux is not getting installed.

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by neheb** [comment]
Is this with latest master or 18.06?

**Comment by neheb** [comment]
Closing due to timeout.
