### ISSUE TITLE
libffmpeg-custom does not generate the ffserver package

### ISSUE THREAD

**Issue by mgondium** [openwrt/packages#9157]
The libffmpeg-custom option to build the command line utilities does not generate the ffserver package when ffserver support is selected. The utilities are compiled but the package is not generated and there is no ffserver binary on the target image.

The following solves it for me, I'm not sure if it's nonsense.

```
--- ./feeds/packages/multimedia/ffmpeg/Makefile
+++ ./feeds/packages/multimedia/ffmpeg/Makefile

@@ -746,6 +746,8 @@
 endef
 
 Package/ffmpeg-custom/install = $(Package/ffmpeg/install)
+Package/ffserver-custom/install = $(Package/ffserver/install)
+Package/ffprobe-custom/install = $(Package/ffprobe/install)
 
 define Package/ffprobe/install
 	$(INSTALL_DIR) $(1)/usr/bin
```

**Comment by antonlacon** [comment]
Right idea, different location to put it. Feel free to test the linked PR.
