### ISSUE TITLE
dnscrypt proxy 1.9.5

### ISSUE THREAD

**Issue by jglooije** [openwrt/packages#9158]
Latest libsodium update to 1.0.18 causes error in excecution:
libsodium change log related to error
- randombytes_salsa20 has been renamed to randombytes_internal

**Comment by porroso** [comment]
same error here:
daemon.err uhttpd[3008]: Error relocating /usr/sbin/dnscrypt-proxy: randombytes_salsa20_implementation: symbol not found

compilied rev Openwrt-ar71xx-r10263_gcc8.3.0_kern_4.14.127

**Comment by porroso** [comment]
thanks @neheb !! problem solved after git pull and manually add your patch net/dnscrypt-proxy/patches/010-internal.patch

**Comment by neheb** [comment]
Cool. Now just waiting for maintainer to ACK. After that I will backport to 19.07 branch as it's broken there.
________________________________

**Comment by neheb** [comment]
Fixed and backported to 19.07.
