### ISSUE TITLE
[shadow-newuidmap | shadow-newgidmap] feature suggestion

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#9175]
Maintainer: @sbyx 

Environment: 18.06 | Master
___
Description: Each package would store their respective conf in /etc/subgid | /etc/subuid but neither is provided by either and thus have to be created manually by the user.
Thus the suggestion to add such conf files.

Additionally it is suggest to remove `--without-acl `. Not sure what the purpose/merit of this setting is when at the same time the repo is providing packages `acl` | `libacl`

**Comment by neheb** [comment]
Fixed with https://github.com/openwrt/packages/commit/87e5ded04cf65fbaa398568efe41830c4b60397a
