### ISSUE TITLE
avrdude: bad %ud formattiong in linuxgpio

### ISSUE THREAD

**Issue by jh-cg** [openwrt/packages#9194]
Maintainer: @thess 
Environment: ar71xx, Mikrotik mAP lite, OpenWRT 18.06.2

Description:
The driver `linuxgpio` in file `linuxgpio.c` uses `%ud` to format numbers when building strings (which are then used as filenames and to interface with `/sys`). This format string is not understood by openwrt libc, the number becomes `<number>d`, and this leads to various errors.

Running find and replace `%ud` with `%u` on `linuxgpio.c` and rebuilding the package fixed the problem.

I'm not sure whether this should be considered as an openwrt or upstream bug (as %ud is AFAIK rather uncommon).

**Comment by neheb** [comment]
Upstream issue yes.

**Comment by jh-cg** [comment]
Oh, it seems to be already reported (3 years ago). https://savannah.nongnu.org/bugs/?49450

**Comment by neheb** [comment]
In the meantime, I recommend submitting a pull request that fixes this.

**Comment by neheb** [comment]
Added a pull request. Test if you can.

**Comment by neheb** [comment]
I fixed this. Closing.
