### ISSUE TITLE
[qrencode] cannot generate svg image

### ISSUE THREAD

**Issue by n8v8R** [openwrt/packages#9200]
Maintainer: @jp-bennett 
Environment: 18.06 && Master
___
Description: generating a svg token image with

```
qrencode "foo://$(ubus call network.interface.lan status | sed -n 's|.*"address": "\([0-9.]*\)"
.*|\1|p')/luci-static/my_secret_url.token?scheme=http&hostname=$HOSTNAME&board_name=bar" -o /www/luci-static/my_secret_url.svg
```

fails with

> PNG output is disabled at compile time. No output generated.
___
Apparently the package is compiled with `--without-png`. Not sure what the merit of this flag is but it would be appreciated to remove it in order to be able to generate svg token images

**Comment by dibdot** [comment]
You have to define the output type (which default is png) with `--type=SVG`

**Comment by n8v8R** [comment]
fabulous

**Comment by firewire10000** [comment]
How do I compile qrencode with PNG support if I'm compiling my own OpenWrt firmware?
