### ISSUE TITLE
libevent2 Makefile error

### ISSUE THREAD

**Issue by whales-yao** [openwrt/packages#9237]
# this line should changed to below
#PKG_BUILD_DIR:=$(BUILD_DIR)/libevent-$(PKG_VERSION)-stable
#
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)

**Comment by whales-yao** [comment]
after tar the package, directory chaged, patch can't find the correct directory.

**Comment by diizzyy** [comment]
Wrong repo (it's in openwrt/openwrt on GitHub) and please least at least platform, revision/hash and error log.
