### ISSUE TITLE
seafile-server failing on ARC

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9255]
Maintainer: @commodo 

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/seafile-server/compile.txt

One way I've found to solve this issue is with PKG_SSP:=0. I can't test this as glib2 doesn't build on my setup for some reason.

**Comment by commodo** [comment]
FWIW, there is some insight in this commit https://github.com/openwrt/openwrt/commit/241e6dd3e92c4f215b8ac75379a4b5aeaeb92171

**Comment by neheb** [comment]
Interesting...

My solution to this problem is here: https://github.com/openwrt/packages/blob/master/utils/powertop/Makefile#L43

I reverted and added -lssp to LDFLAGS and that works as well. I wonder if this also fails with glibc...

**Comment by commodo** [comment]
Adding the patch in `include/hardening.mk` also works.
After looking around the current packages, I am not completely sure about patching this in core.
There are only 2-3 packages [in the OpenWrt project] that may benefit from this [i.e. patching this in core]; maybe there may be a few others, but I am not sure.

I'll just patch seafile-server only then.

**Comment by neheb** [comment]
I backported this to 19.07. Hope you don't mind.

**Comment by commodo** [comment]
No worries from me.

Thanks :)
Alex
