### ISSUE TITLE
python-requests

### ISSUE THREAD

**Issue by pawisoon** [openwrt/packages#9270]
Is it possible to include python-requests in openwrt packages?
Cheers,
Pawel

**Comment by jefferyto** [comment]
It might help to [check](https://github.com/openwrt/packages/blob/master/lang/python/python-requests/Makefile) the repo before asking.

**Comment by pawisoon** [comment]
> It might help to [check](https://github.com/openwrt/packages/blob/master/lang/python/python-requests/Makefile) the repo before asking.

Hey, 
I saw it but forgot to mention Im trying to build it under 15.05. I tried using current Makefile with my changes but it failed to compile: 
<img width="1199" alt="Screenshot 2019-06-19 at 16 15 03" src="https://user-images.githubusercontent.com/6951295/59774409-b1b6f380-92af-11e9-870e-773cff92461b.png">

**Comment by jefferyto** [comment]
15.05 is 4 years old and isn't supported anymore - I would advise you to upgrade.

**Comment by BKPepe** [comment]
@jefferyto said everything. Closing.
