### ISSUE TITLE
pdns not compiling under ARC

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9311]
Maintainer: @James-TR 
Environment: arc

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/pdns/compile.txt

execinfo is not available.

**Comment by James-TR** [comment]
Here's the offending code https://github.com/PowerDNS/pdns/blob/master/pdns/receiver.cc#L357-L378

I'm guessing we should modify the conditional so it doesn't blindly try to bring it in?

**Comment by James-TR** [comment]
`#if defined(__GLIBC__) && !defined(__UCLIBC__)`

**Comment by James-TR** [comment]
@neheb ... I've tracked this down to PR's I made in 2014 when I was compiling PowerDNS under musl-libc. I've opened PR PowerDNS/pdns#7980
