### ISSUE TITLE
Package request : Neofetch

### ISSUE THREAD

**Issue by NatoBoram** [openwrt/packages#9374]
> [Neofetch](https://github.com/dylanaraps/neofetch) is a command-line system information tool written in Bash 3.2+. Neofetch displays information about your operating system, software and hardware.

![NVIDIA_Share_l3PxZMp1Pl](https://user-images.githubusercontent.com/10495562/60562607-3715bb80-9d26-11e9-9994-4680054eb72d.png)

On OpenWrt, installing it is very easy. It only depends on `bash`.

```bash
opkg install bash ca-certificates git git-http make
git clone https://github.com/dylanaraps/neofetch.git
cd neofetch
make install
```

Still, I prefer using a package manager rather than `git clone`ing my software and installing them à la Windows.

I tried to get it added to https://github.com/Entware/Entware/issues/177, but it got denied.

**Comment by diizzyy** [comment]
While I personally agree with Alexander feel free to do a proper pull request.

**Comment by NatoBoram** [comment]
Looks like a PR is up:

* https://github.com/openwrt/packages/pull/27949
