### ISSUE TITLE
node-mozilla-iot-gateway missing dependencies

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9392]
https://downloads.openwrt.org/snapshots/faillogs/i386_pentium4/packages/node-mozilla-iot-gateway/compile.txt

@BKPepe

**Comment by BKPepe** [comment]
I'm not maintaintainer, tho,  I noticed it as well,  but they are preparing a new release soon, so I will fix it once they release it.

**Comment by neheb** [comment]
Maintainer is inactive. Having said that, I do remember you updating the package :).

**Comment by cotequeiroz** [comment]
@nxhack may be able to help.  It is probably host-building some modules, and also has a problem with openssl 1.1.x while buiding ursa native module.

**Comment by nxhack** [comment]
OK. I will try some work.

**Comment by cotequeiroz** [comment]
This appears to be fixed by #9422, so I'm closing this.
