### ISSUE TITLE
SSH login fails on Openwrt 18.06 for Comfast CF-E5

### ISSUE THREAD

**Issue by LiveAction-SunArc-Op** [openwrt/packages#9424]
Unable to SSH on 192.168.1.1, the CF-E5 listens on 192.168.10.1.
I tried  logging into 192.168.10.1 with no passphrase for first time, it didn't work.

I couldn't use the device, need support in cracking the password.

**Comment by feckert** [comment]
Please use the openwrt forum for this kind of issue.
