### ISSUE TITLE
collectd-exec-mod -> does not execute shell scripts since ~1-2 weeks on startup

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#9427]
collectd-exec-mod
tried current trunk from today ....

collectd - exec-plugin does not execute shell scripts since ~1-2 weeks
was there a change ?

**Comment by neheb** [comment]
ping @feckert

**Comment by camelcamro** [comment]
i see that the luci_statistic is generating the config for collectd ...
and there is the problem
is total different as the old for few weeks

=> stat-genconfig
i have no clue if that was tested, but with an older version it is working fine. no clue .. what was done :(
also the firewall collectd are not correct, i would recommend to do a rollback

**Comment by feckert** [comment]
Indeed there are problem with plugins which need a special treatment!

- network
- iptables
- exec
- curl
- maybe collectd as well
- maybe logfile as well

ping @mberndt123

> i would recommend to do a rollback

@camelcamro If this not get fixed in the next days I will revert the changes

**Comment by camelcamro** [comment]
is not urgent i guess, i will use the old from v.18.06 or 04 .. already tested with the old one, and works fine
so, just relax .. tranquilo
 :)

**Comment by feckert** [comment]
@camelcamro Please try this
[stat-genconfig.txt](https://github.com/openwrt/packages/files/3372457/stat-genconfig.txt)

The changes should solve your issue :-)

**Comment by feckert** [comment]
This should fix the issue
https://github.com/openwrt/luci/pull/2844

**Comment by feckert** [comment]
@camelcamro did my change fix your issue? If so please close.

**Comment by camelcamro** [comment]
tested it now ....and is OK :)
thx a lot. pls close ticket (not sure if i have rights to close ...)
