### ISSUE TITLE
luci system => TypeError can't convert null to object

### ISSUE THREAD

**Issue by camelcamro** [openwrt/packages#9429]
on current trunk, there is an error on that page:
trunk: Powered by LuCI Master (f138fc93) / OpenWrt SNAPSHOT r10444-5c094ff660 

#eg: https://192.168.1.2/cgi-bin/luci/admin/system/system

TypeError
can't convert null to object
  at render (https://192.168.1.2/luci-static/resources/ui.js:12:190)
  at renderWidget (https://192.168.1.2/luci-static/resources/form.js:155:769)

was working on old (10 days ago) version

**Comment by diizzyy** [comment]
Report it here:
https://github.com/openwrt/luci
Include platform and changes to stock config
