### ISSUE TITLE
prometheus fails on mips64

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9494]
https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/prometheus/compile.txt

ping @aparcar and @jefferyto 

Any idea what's happening? Closest thing I see to an error are these lines:

```
# gopkg.in/fsnotify/fsnotify.v1
pkg/mod/gopkg.in/fsnotify/fsnotify.v1@v1.3.1/inotify.go:39:15: undefined: unix.InotifyInit
```

**Comment by jefferyto** [comment]
@aparcar are you looking into this?

**Comment by aparcar** [comment]
I'm not really a go person but a prometheus user person :( I'll try to look into it but likely can't find a solution...

**Comment by aparcar** [comment]
@neheb which target/subtarget is this actually?

**Comment by neheb** [comment]
octeonplus

**Comment by neheb** [comment]
This is also an issue on 19.07: https://downloads.openwrt.org/releases/faillogs-19.07/mips64_octeonplus/packages/prometheus/compile.txt
