### ISSUE TITLE
net/kea: Unusable -- Requires "all" of Python 3

### ISSUE THREAD

**Issue by jeffsf** [openwrt/packages#9495]
`kea` does not have a run-time dependency on Python 3, which gets dragged in by the current package definition.

This is potentially due to the boost library being built with Python support.

Python 3 is not a run-time dependency of kea.

https://ftp.isc.org/isc/kea/1.3.0/doc/kea-guide.html#required-software

**Comment by neheb** [comment]
dependency is here: https://github.com/openwrt/packages/blob/master/net/kea/Makefile#L79

**Comment by neheb** [comment]
ping @rosysong @hbl0307106015

**Comment by rosysong** [comment]
@jeffsf  all right, will drop it, Thanks!

**Comment by tiagogaspar8** [comment]
After removing the python3 dependency Kea disappears from the make menuconfig
