### ISSUE TITLE
pptpd can not start via /etc/init.d/pptpd start

### ISSUE THREAD

**Issue by rufengsuixing** [openwrt/packages#9554]
Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: openwrt 18.06.4

Description:

pptpd can not start via /etc/init.d/pptpd start
can start via ssh

**Comment by feckert** [comment]
Please add a description how to reproduce this issue.

**Comment by neheb** [comment]
It's not starting because "enabled" is 0 in /etc/config/pptpd . Closing.
