### ISSUE TITLE
gpsd compilation error on master

### ISSUE THREAD

**Issue by zdz2019** [openwrt/packages#9599]
Did not choose to compile gpsd, but still reported an error.

Platform: x86_64
Description:
make[3]: Entering directory '/home/kghx/x86/openwrt/feeds/packages/utils/gpsd'
touch /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/.prepared_b39b9c80694dfbf45c37238415ab45e2_6664517399ebbbc92a37c5bb081b5c53_check
. /home/kghx/x86/openwrt/include/shell.sh; gzip -dc /home/kghx/x86/openwrt/dl/gpsd-3.17.tar.gz | tar -C /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17

Applying ./patches/0002-ncurses6_detection.patch using plaintext: 
patching file SConstruct

Applying ./patches/010-musl.patch using plaintext: 
patching file driver_ais.c
patching file gpsctl.c
patching file gpsd_json.c
patching file libgpsd_core.c
touch /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/.prepared_b39b9c80694dfbf45c37238415ab45e2_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/.configured_*
rm -f /home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/stamp/.gpsd_installed
(cd /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17; CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17:gpsd-3.17 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17:gpsd-3.17 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/include -I/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/include -I/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include/fortify -I/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include " LDFLAGS="-L/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/lib -L/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/lib -L/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/lib -znow -zrelro " DESTDIR="/home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/ipkg-install" LINKFLAGS="-L/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/lib -L/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/lib -L/home/kghx/x86/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/lib -znow -zrelro" scons prefix=/usr dbus_export=no tsip=no fv18=no tripmate=no earthmate=no itrax=no navcom=no ubx=no evermore=no ntrip=no libgpsmm=no libQgpsmm=no bluez=no nostrip=yes python=no implicit_link=no chrpath=no manbuild=no target="x86_64-openwrt-linux-musl" install )
scons: Reading SConscript files ...
  File "/home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/SConstruct", line 378

    print msg

            ^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?

make[3]: *** [Makefile:145: /home/kghx/x86/openwrt/build_dir/target-x86_64_musl/gpsd-3.17/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 2
make[3]: Leaving directory '/home/kghx/x86/openwrt/feeds/packages/utils/gpsd'
time: package/feeds/packages/gpsd/compile#0.23#0.32#0.72
make[2]: *** [package/Makefile:109: package/feeds/packages/gpsd/compile] Error 2
make[2]: Leaving directory '/home/kghx/x86/openwrt'
make[1]: *** [package/Makefile:103: /home/kghx/x86/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2

**Comment by neheb** [comment]
Fixed by https://github.com/openwrt/packages/pull/9588
