### ISSUE TITLE
banip: /etc/banip/banip.whitelist keeps growing on each router reboot

### ISSUE THREAD

**Issue by R-Adrian** [openwrt/packages#9631]
Maintainer: @dibdot 
Environment:
```
system type             : Qualcomm Atheros QCA9558 ver 1 rev 0
machine                 : TP-LINK TL-WR1043ND v2
processor               : 0
cpu model               : MIPS 74Kc V5.0
```
using a custom build (made from snapshot)
 SuperWRT SNAPSHOT, r10641-1d2b2e744e
```
#cat /proc/version
Linux version 4.14.134 (contact@superwrt.download) (gcc version 7.4.0 (OpenWrt GCC 7.4.0 r9875-3e803499c3)) #0 Wed Jul 31 14:53:41 2019

# opkg info banip
Package: banip
Version: 0.1.4-1
Depends: libc, jshn, jsonfilter, ip, ipset, iptables
Status: install user installed
Architecture: all
[...snip...]

# opkg list-installed | grep -i ban
banip - 0.1.4-1
luci-app-banip - git-19.212.79585-05cad42-1
```

**Description:**
i use dual-stack PPPoE IPv4 + IPv6 dynamic addresses from my ISP and have a daily reboot scheduled in crontab.

A while ago i discovered that the banip whitelist (`/etc/banip/banip.whitelist`) keeps growing and on each reboot the ip addresses (v4 and v6) of the active wan interfaces keep getting added to the whitelist and are never removed.

Since my ISP allocates different addresses each time that the PPPoE session is re-created, that means the whitelist keeps growing forever, a little bit at each reboot.

**Am I doing something wrong or is the whitelist really supposed to be cleaned up manually from time to time?**

current configuration of /etc/config/banip is:
```
config banip 'global'
        option ban_automatic '1'
        option ban_fetchutil 'uclient-fetch'
        option ban_iface 'wan'
        option ban_enabled '1'

config banip 'extra'
        option ban_debug '0'
        option ban_nice '10'
        option ban_backup '0'
        option ban_maxqueue '1'

config source 'whitelist'
        option ban_src '/etc/banip/banip.whitelist'
        option ban_src_6 '/etc/banip/banip.whitelist'
        option ban_src_desc 'Always allow these IPs (IPv4/IPv6)'
        option ban_src_rset '/^(([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,2})?)([[:space:]]|$)/{print \"add whitelist \"\$1}'
        option ban_src_rset_6 '/^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}(:\/[0-9]{1,2})?([[:space:]]|$)/{print \"add whitelist_6 \"\$1}'
        option ban_src_settype 'net'
        option ban_src_ruletype 'src+dst'
        option ban_src_on '1'
        option ban_src_on_6 '1'

(...snip... 
and then are more sections for the definitions of the individual lists themselves... using the standard format there. )
```

**Comment by dibdot** [comment]
Works as designed! :smile: 
New ISP/Uplink subnets will be always automatically added to the whitelist  & whitelist ipset to prevent major lock outs. Maybe I could add an extra option in a future version, that these kind of entries are only stored temporary in the whitelist ipset but not in the whitelist itself.
Anyway, you have to maintain the whitelist always manually ...

**Comment by R-Adrian** [comment]
yes, please, 

storing them temporary only in the ipset instead of appending them to the file will limit the wear-out of the router's flash memory chips. (minuscule as it is, it can add up)

Also, having to manually scrub the whitelist stale IP addresses is becoming annoying.
