### ISSUE TITLE
Please update wview package to latest source (wview_5.21.7 / may 2014)

### ISSUE THREAD

**Issue by martlaak** [openwrt/packages#970]
Weather station package wview port to OpenWrt is working but rather old (wview_5.19.0-jgoerzen / 2012). Please somebody update it to wview_5.21.7 (may 2014).

Attached are patches for the wview_5.21.7, for files:
Makefile
patches/010-fix-cross-compile.patch
patches/020-use-standard-awk.patch
patches/040-WMRUSB-process-absent-dewpoint.patch

NB! patches/050-WMRUSB-fix-segfault-buffer-overflow.patch is not needed anymore as it is incorporated in wview source now.

Regards,
Märt Laak

---
<pre>
diff -ruN wview-5.19.0-jgoerzen/Makefile wview-5.21.7/Makefile
--- wview-5.19.0-jgoerzen/Makefile	2015-02-28 17:25:53.595765600 +0200
+++ wview-5.21.7/Makefile	2015-02-23 16:59:28.808672200 +0200
@@ -8,12 +8,12 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=wview
-PKG_VERSION:=5.19.0-jgoerzen
-PKG_RELEASE=$(PKG_SOURCE_VERSION)-r2
-PKG_SOURCE_URL:=git://github.com/jgoerzen/wview.git
-PKG_SOURCE_VERSION:=7bfac6c11e756290c38e7b5862a4c51b6bc6c51e
-PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
-PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION).tar.gz
+PKG_VERSION:=5.21.7
+PKG_RELEASE:=1
+
+PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
+PKG_SOURCE_URL:=@SF/$(PKG_NAME)
+PKG_MD5SUM:=a296932574ffb4a3855e505a73daf9c5
 
 PKG_FIXUP:=autoreconf
 
@@ -22,7 +22,7 @@
 define Package/wview
   SECTION:=utils
   CATEGORY:=Utilities
-  DEPENDS:=+libcurl +zlib +libpng +libgd +libreadline +libsqlite3 +libusb-1.0 +radlib +sqlite3-cli +libopenssl
+  DEPENDS:=+libcurl +zlib +libpng +libgd +libreadline +libsqlite3 +libusb-1.0 +radlib +sqlite3-cli +libopenssl +udev
   TITLE:=Wview Weather Station Software
   URL:=http://www.wviewweather.com/
 endef
diff -ruN wview-5.19.0-jgoerzen/patches/010-fix-cross-compile.patch wview-5.21.7/patches/010-fix-cross-compile.patch
--- wview-5.19.0-jgoerzen/patches/010-fix-cross-compile.patch	2015-02-28 17:25:53.579275500 +0200
+++ wview-5.21.7/patches/010-fix-cross-compile.patch	2015-02-21 21:37:40.157653500 +0200
@@ -12,7 +12,7 @@
  wvalarmd_LDADD   =
  
  # define library directories
--wvalarmd_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wvalarmd_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wvalarmd_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -32,7 +32,7 @@
  wvcwopd_LDADD   =
  
  # define library directories
--wvcwopd_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wvcwopd_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wvcwopd_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -52,7 +52,7 @@
  wviewftpd_LDADD   = -lssl -lcurl
  
  # define library directories
--wviewftpd_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewftpd_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewftpd_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -72,7 +72,7 @@
  htmlgend_LDADD   =
  
  # define library directories
--htmlgend_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-htmlgend_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -htmlgend_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -94,7 +94,7 @@
  wvhttpd_LDADD     = -lssl -lcurl
  
  # define library directories
--wvhttpd_LDFLAGS   = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wvhttpd_LDFLAGS   = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wvhttpd_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -114,7 +114,7 @@
  wvpmond_LDADD   =
  
  # define library directories
--wvpmond_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wvpmond_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wvpmond_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -134,7 +134,7 @@
  wviewsshd_LDADD   =
  
  # define library directories
--wviewsshd_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewsshd_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewsshd_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -154,7 +154,7 @@
  wviewd_sim_LDADD       =
  
  # define library directories
--wviewd_sim_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_sim_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_sim_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -196,7 +196,7 @@
  wviewd_twi_LDADD       =
  
  # define library directories
--wviewd_twi_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_twi_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_twi_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -216,7 +216,7 @@
  wviewd_vpro_LDADD       =
  
  # define library directories
--wviewd_vpro_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_vpro_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_vpro_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -236,7 +236,7 @@
  vpconfig_LDADD   =
  
  # define library directories
--vpconfig_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-vpconfig_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -vpconfig_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -257,7 +257,7 @@
  wviewd_virtual_LDADD     =
  
  # define library directories
--wviewd_virtual_LDFLAGS   = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_virtual_LDFLAGS   = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_virtual_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -299,7 +299,7 @@
  wviewd_wmr918_LDADD       =
  
  # define library directories
--wviewd_wmr918_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_wmr918_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_wmr918_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -341,7 +341,7 @@
  wviewd_ws2300_LDADD       =
  
  # define library directories
--wviewd_ws2300_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_ws2300_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_ws2300_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -361,7 +361,7 @@
  wviewd_wxt510_LDADD       =
  
  # define library directories
--wviewd_wxt510_LDFLAGS     = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wviewd_wxt510_LDFLAGS     = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wviewd_wxt510_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -381,7 +381,7 @@
  wxt510config_LDADD   =
  
  # define library directories
--wxt510config_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wxt510config_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wxt510config_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -401,7 +401,7 @@
  arc_be2le_LDADD   =
  
  # define library directories
--arc_be2le_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-arc_be2le_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -arc_be2le_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -421,7 +421,7 @@
  arc_le2be_LDADD   =
  
  # define library directories
--arc_le2be_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-arc_le2be_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -arc_le2be_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -441,7 +441,7 @@
  hilowcreate_LDADD   =
  
  # define library directories
--hilowcreate_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-hilowcreate_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -hilowcreate_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -461,7 +461,7 @@
  sqlite2wlk_LDADD   =
  
  # define library directories
--sqlite2wlk_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-sqlite2wlk_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -sqlite2wlk_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
@@ -481,19 +481,9 @@
  wlk2sqlite_LDADD   =
  
  # define library directories
--wlk2sqlite_LDFLAGS = -L$(prefix)/lib -L$(prefix)/usr/lib -L/usr/lib
+-wlk2sqlite_LDFLAGS = -L$(prefix)/lib -L/usr/lib
  
  if CROSSCOMPILE
 -wlk2sqlite_LDFLAGS += $(prefix)/lib/crt1.o $(prefix)/lib/crti.o $(prefix)/lib/crtn.o
  endif
  
---- a/stations/common/hidapi-linux.c
-+++ b/stations/common/hidapi-linux.c
-@@ -79,7 +79,6 @@
- #else
- #include "libusb-1.0/libusb.h"
- #endif
--#include "iconv.h"
- 
- #include "hidapi.h"
- 
diff -ruN wview-5.19.0-jgoerzen/patches/040-WMRUSB-process-absent-dewpoint.patch wview-5.21.7/patches/040-WMRUSB-process-absent-dewpoint.patch
--- wview-5.19.0-jgoerzen/patches/040-WMRUSB-process-absent-dewpoint.patch	2015-02-28 17:25:53.566283300 +0200
+++ wview-5.21.7/patches/040-WMRUSB-process-absent-dewpoint.patch	2015-02-21 21:52:07.651153500 +0200
@@ -2,22 +2,24 @@
 ===================================================================
 --- wview-5.19.0-jgoerzen.orig/stations/WMRUSB/wmrusbprotocol.c	2012-12-15 15:32:03.000000000 +0000
 +++ wview-5.19.0-jgoerzen/stations/WMRUSB/wmrusbprotocol.c	2012-12-15 15:36:47.199715376 +0000
-@@ -70,12 +70,9 @@
+@@ -69,12 +69,9 @@
  {
      a &= 0xff;
      b &= 0xff;
--    int t = (b << 8) | a;
--    if (t & 0x8000)
+-    int t = ( b << 8 ) | a;
+-    if( t & 0x8000 )
 -    {
 -        t &= 0x7FFF;
 +    int t = ((b & 0x0f) << 8) | a;
 +    if (b & 0x80)
-         return -(t / 10.0);
+         return -( t / 10.0 );
 -    }
      else
-         return t / 10.0;
+     {
+         return ( t / 10.0 );
+     }
  }
-@@ -166,6 +163,9 @@
+@@ -200,6 +197,9 @@
              return;
          }
  
diff -ruN wview-5.19.0-jgoerzen/patches/050-WMRUSB-fix-segfault-buffer-overflow.patch wview-5.21.7/patches/050-WMRUSB-fix-segfault-buffer-overflow.patch
--- wview-5.19.0-jgoerzen/patches/050-WMRUSB-fix-segfault-buffer-overflow.patch	2015-02-28 17:25:53.549293500 +0200
+++ wview-5.21.7/patches/050-WMRUSB-fix-segfault-buffer-overflow.patch	1970-01-01 03:00:00.000000000 +0300
@@ -1,18 +0,0 @@
-Index: wview-5.19.0-jgoerzen/stations/WMRUSB/wmrusbprotocol.c
-===================================================================
---- wview-5.19.0-jgoerzen.orig/stations/WMRUSB/wmrusbprotocol.c	2013-03-10 22:24:28.000000000 +0400
-+++ wview-5.19.0-jgoerzen/stations/WMRUSB/wmrusbprotocol.c	2013-03-10 22:25:01.000000000 +0400
-@@ -897,8 +897,11 @@
- // Read raw USB data and buffer it for later processing:
- void wmrReadData (WVIEWD_WORK *work, WMRUSB_MSG_DATA* msg)
- {
--    memcpy(&wmrWork.readData[wmrWork.readIndex], msg->data, msg->length);
--    wmrWork.readIndex += msg->length;
-+    if (wmrWork.readIndex + msg->length <= WMR_BUFFER_LENGTH)
-+    {
-+        memcpy(&wmrWork.readData[wmrWork.readIndex], msg->data, msg->length);
-+        wmrWork.readIndex += msg->length;
-+    }
- 
-     return;
- }
</pre>

**Comment by champtar** [comment]
hi @martlaak 
please send a pull request

**Comment by thess** [comment]
ref: #967 
Looking for a volunteer...

**Comment by hayden-t** [comment]
hey, im curious about all this, im in a pickle, want to compile this for mipsel, have tried the sdk approach, but as discussed here its not in the feeds anymore, tried with the cross compile toolchain made, but radlib complains of stub.h missing, which afaik is part of glibc which has been replaced by musl , and in the advanced dev option in make menuconfig there is no options at all, such as the use uclibc instead of musl ??
