### ISSUE TITLE
yggdrasil failing to compile

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9712]
https://downloads.openwrt.org/releases/faillogs-19.07/mips64_octeonplus/packages/yggdrasil/compile.txt

Seems there are some git shenanigans going on.

ping @wfleurant

**Comment by wfleurant** [comment]
Somebody stubbed their toe alright. Issue and discussion below, Thanks.  
> known issue https://github.com/yggdrasil-network/yggdrasil-go/issues/503
> tl;dr we had to rebase our fork of the "water" dependency (tun/tap code) to try to get a PR accepted upstream, and this accidentally broke the old commit history
> we'll be releasing v0.3.7 with some bugfixes soon, which should build
