### ISSUE TITLE
It seems that there's no php* packages in the newest opkg source

### ISSUE THREAD

**Issue by guzhiyong** [openwrt/packages#9723]
Maintainer: @\<github-user> (find it by checking history of the package Makefile)
Environment: (put here arch, model, OpenWrt version)

Description:

I have updated to the newest source and when I try _opkg list php*_ I got nothing.
It seems that there's no php packages in the newest opkg source
```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by mhei** [comment]
You must describe in more detail, what you've done. The issue template helps you to fill in expected information to allow supporting you, also the helping texts should be removed before submitting the issue. Please fix this.
BTW: did you run "opkg update" before "opkg list..."?

**Comment by neheb** [comment]
Yeah that was my bad. I messed up when backporting an icu patch, which broke PHP. It should be fine soon.

**Comment by mhei** [comment]
No response from @guzhiyong, closing since this was probably a temporary issue.
