### ISSUE TITLE
prometheus-node-exporter-lua: Please add 'architecture'

### ISSUE THREAD

**Issue by systemcrash** [openwrt/packages#9730]
Ping @klukonin

When scraping, I get e.g.:

```
...
node_openwrt_info{revision="r7808-ef686b7292",model="TP-LINK Archer C7 v4",id="OpenWrt",board_name="archer-c7-v4",release="18.06.4"} 1
...
```

Could someone please add the architecture field? Like what we see when logging in to the device via GUI:

Model blah
Architecture blah
Firmware Version blah
Kernel Version blah

producing e.g.

```
...
node_openwrt_info{revision="r7808-ef686b7292",model="TP-LINK Archer C7 v4",architecture="Qualcomm Atheros QCA956X ver 1 rev 0",id="OpenWrt",board_name="archer-c7-v4",release="18.06.4"} 1
...
```

If ```architecture``` doesn't belong under ```node_openwrt_info``` I can live with it anywhere else.

**Comment by systemcrash** [comment]
Architecture seems to be pulled like so:

https://github.com/openwrt/luci/blob/36f226548a4b0eee66695a163c728089e60d28ca/modules/luci-mod-status/luasrc/view/admin_status/index/10-system.htm

This references ```boardinfo.system```

**Comment by systemcrash** [comment]
I guess that stuff goes here:

https://github.com/openwrt/packages/blob/master/utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/openwrt.lua

**Comment by systemcrash** [comment]
Also located when running:
```ubus call system board```

**Comment by klukonin** [comment]
Yes, it's possible.
I'm not sure about which method would be the best.
May be ubus call will be optimal.

Also you should call a maintainer of this package.
I'm just a guy ho did a small commit for personal purposes.
