### ISSUE TITLE
libgd: please add webp support by default

### ISSUE THREAD

**Issue by crisc82** [openwrt/packages#9740]
Package: libgd https://github.com/openwrt/packages/blob/master/libs/libgd/Makefile
Maintainer: @jow- / Jo-Philipp Wich <jo@mein.io>
Environment: Netgear R7800 with Nginx and PHP

Description:
As Microsoft Edge added WebP support in November 2018 and Mozilla Firefox added support in January 2019 , WebP format is almost universally supported on client side.  https://caniuse.com/#feat=webp

To start to adopt this more efficient image format, server side support is also necessary. 
The package php7-mod-gd use libgd.

Dependencies:
https://github.com/libgd/libgd
https://github.com/webmproject/libwebp

**Comment by jow-** [comment]
Can you provide a patch? I won't have time to work on that.

**Comment by rmandrad** [comment]
compilation on wrt3200acm (mvebu) fails .. fixed by adding --disable-neon to the makefile

**Comment by stefaang** [comment]
@neheb I see you've disabled several libs in libwebp... I'll have a look for a libwebp-full package including the cwebp converter tool.

**Comment by neheb** [comment]
Which do you need?

**Comment by stefaang** [comment]
I'd be mainly interested in jpeg --> webp for now.

**Comment by mhei** [comment]
My last upgrade of PHP probably broke your use-case since PHP now relies on the external libgd and not anymore on the bundled/internal library.
Meanwhile we also have a libgd-full package, maybe this helps to bake a nice dependency chain without making the whole thing too complex...

**Comment by neheb** [comment]
Seems everything got merged. Closing.
