### ISSUE TITLE
opkg: image builder pulls in dnsmasq-full instead of dnsmasq

### ISSUE THREAD

**Issue by fantom-x** [openwrt/packages#9750]
Environment: Image builder with 19.07-SNAPSHOT for Gl.iNet gl-ar750

The latest version of **travelmate** has introduced an explicit dependency on **dnsmasq**, but the image builder is adding **dnsmasq-full** to the image instead. That increases the image size by ~0.5MB and it actually does not work without a workaround #9749 .

**Comment by dibdot** [comment]
Strange, maybe a problem in imagebuilder with "PROVIDES"!? I don't now ... anyway, as a workaround you should set explicit dnsmasq in first place as well, e.g.:

`make image PROFILE="glinet_gl-ar750s" PACKAGES="dnsmasq travelmate"`

**Comment by fantom-x** [comment]
Thx, your workaround worked very well. But I would still like to keep the other issue open as it is a separate one: dnsmasq-full can be added explicitly and then the build breaks.

This issue is about pulling in **dnsmasq-full** instead of **dnsmasq**.

**Comment by dibdot** [comment]
Please open a image builder related ticket at bugs.openwrt.org.
