### ISSUE TITLE
Compiled luaposix lacks dependencies!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/packages#9783]
![@YO~5U3YE7~BJB `Z$7GU9D](https://user-images.githubusercontent.com/45259624/63359739-d60e7980-c39f-11e9-83c8-614040385069.png)

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/9707

**Comment by hnyman** [comment]
#9707 was merged. That should fix this.
