### ISSUE TITLE
net-snmp: enable pass_persist for snmpd in Makefile

### ISSUE THREAD

**Issue by ionum** [openwrt/packages#980]
pass_persist allows to extend snmpd with persistent scripts (better performance). the snmpd init script already parses config entries for pass_persist, but the snmpd package is not compiled with pass_persist support.

SNMP_MIB_MODULES_INCLUDED in Makefile should contain ucd-snmp/pass_persist

**Comment by champtar** [comment]
hi @ionum,
can you send a pull request ?

**Comment by ionum** [comment]
Here we are: #1031

**Comment by ionum** [comment]
Any progress on this?

**Comment by champtar** [comment]
#1031 was merged
