### ISSUE TITLE
Upgrade Problem

### ISSUE THREAD

**Issue by jkle112** [openwrt/packages#9817]
Simple-Adblock that installled in OpenWrt version 18.06.4 within Linksys WRT1900AC

When add more sources urls in the Simple-Adblock,but it is full not download more new sources to update cache file.

Need upgrade Simple-Adblock to support Big Data for powerful security,and add more functions to speed up ,dns fast look up,low memory.

![Image 1](https://user-images.githubusercontent.com/17021524/63634568-cdd86780-c647-11e9-8c10-20358e0286ce.png)

**Comment by DazzyWalkman** [comment]
Maybe you can look at package adblock. 
Some of your expections may not go 'simple'.

**Comment by jkle112** [comment]
Adblock :could not to upgrade by myself,because when it is starting,download config file from github.com with author ,rewrite my config file.If used it for big data,could not to deal with that without enough memory.Sometimes ,that's could not to processing very well,and downloading error,some AD that could not to filter.
Simple-Adblock:only one problems:could not support big data.Downloading error ,that need support curl /wget with SSL to fix .
So if use more better hardware like X64,need Simple-Adblock to upgrade.I will use it more powerful and become a loacal big cache DNS sever.
Thank you !

**Comment by jkle112** [comment]
Simple-Adblock that installled in openwrt-koolshare-mod-v2.32-r11575

![Image 4](https://user-images.githubusercontent.com/17021524/64092700-5e4c3180-cd45-11e9-91bb-93ef9e9a9504.png)


When add more sources urls in the Simple-Adblock,but it is full not download more new sources to update cache file.
![Image 0](https://user-images.githubusercontent.com/17021524/64092726-758b1f00-cd45-11e9-9326-8f11403cb8b6.png)

Need upgrade Simple-Adblock to support Big Data for powerful and add more functions to speed up ,dns fast look up low memory
![Image 0](https://user-images.githubusercontent.com/17021524/64092733-7ae86980-cd45-11e9-8ec2-434f4e74ab85.png)

![Image 3](https://user-images.githubusercontent.com/17021524/64092735-7cb22d00-cd45-11e9-82cd-2d49803519cd.png)
Hope  Simple-Adblock add a button:manual update for every url,that update more quickly.
Thank you!

**Comment by neheb** [comment]
ping @stangri

**Comment by stangri** [comment]
There is a newer version of Luci app which has force redownload button. If your request was about something else, please clarify.

**Comment by stangri** [comment]
How long do we keep this open if there's no comment from OP?

**Comment by neheb** [comment]
I’ll close. @jkle112 please open a new issue if you still have problems.
