### ISSUE TITLE
bfdd not compiling with uClibc-ng

### ISSUE THREAD

**Issue by neheb** [openwrt/packages#9831]
Maintainer: @lucize 

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/bfdd/compile.txt

Looks like a missing header.

**Comment by lucize** [comment]
is the ipv6 that conflicts with musl, I wonder if uclibc has a way to identify itself ?

**Comment by lucize** [comment]
I'll have to dig a bit for this, frr is using the same code and is working on arc.

**Comment by neheb** [comment]
I tried looking at this before. Wasn't successful. We shouldn't be spending resources on uClibc-ng. It's marked BROKEN for a reason...
