### ISSUE TITLE
PPPoE problem network is unreachable

### ISSUE THREAD

**Issue by bogdik** [openwrt/packages#9835]
Please make sure that the issue subject starts with `pppoe: `

Problem on trunk
If add pppoe interface i get error “network is unreachable” ( wan one interface )

on OpenWrt Designated Driver 49994 / LuCI branch (git-16.315.66848-d4bbf44) - no this error

[Normal screen Old version](https://sun9-10.userapi.com/c851320/v851320367/1a1e54/7gbPyn4Q7SA.jpg)
[Error on Trunk now](https://sun9-32.userapi.com/c851320/v851320367/1a1e5e/uJ-k6z3KhZ0.jpg)

**Comment by diizzyy** [comment]
Invalid, use https://bugs.openwrt.org/
