### ISSUE TITLE
kea: Unable to select in the menuconfig

### ISSUE THREAD

**Issue by tiagogaspar8** [openwrt/packages#9839]
Maintainer: BangLang Huangbanglang.huang@foxmail.com, Rosy Songrosysong@rosinson.com
Environment: ARM Latest OpenWRT Trunk

Description:

Since the removal of the python3 dependency the package doesn't appear in the menuconfig.
As soon as I add the python3 dependency it shows up again.
Also, I don't believe that the options are correctly configured as they don't appear as a menu and require us to select kea-admin, which is not the required package.

**Comment by neheb** [comment]
ping @rosysong @hbl0307106015

**Comment by tiagogaspar8** [comment]
This is fixed so I'll close this issue.
