### ISSUE TITLE
python3-idna: missing unicodedata

### ISSUE THREAD

**Issue by alexandrevicenzi** [openwrt/packages#9874]
Maintainer: @jefferyto
Environment:  GL-AR750S / OpenWrt 18.06.1

Description:

unicodedata module is missing from idna and without it idna does not work.
unicodedata should be installed/shipped with idna.

Is there any way to install unicodedata?

Steps to reproduce:

1. Install python3
2. Install python3-idna
3. Import idna in python shell

```
# python3
Python 3.6.5 (default, Jul 15 2018, 12:30:50) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import idna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/__init__.py", line 2, in <module>
  File "/core.py", line 3, in <module>
ModuleNotFoundError: No module named 'unicodedata'
```

**Comment by BKPepe** [comment]
The missing dependency `python[3]-codecs` for `python[3]-idna` was included in OpenWrt 18.06.02, which was released on 1st February. See https://github.com/openwrt/packages/pull/8048. I'd suggest updating your router to the latest stable version of OpenWrt, which is 18.06.04.

You need to install package python[3]-codecs.
