### ISSUE TITLE
dovecot: adding dovenull user removed dovecot user

### ISSUE THREAD

**Issue by flyn-org** [openwrt/packages#9939]
Maintainer: @lucize
Environment: x86_64 master beyond e27438f1

Description:

Commit e27438f1 modified the dovecot package Makefile so that installing the package also creates the dovenull user. However, this was done in such a way that it rendered the previous line, which created the dovecot user, void. Both users are necessary for a proper Dovecot installation.

The Makefile now contains:

  [...]
  USERID:=dovecot=59:dovecot=59
  USERID:=dovenull=60:dovenull=60
  [...]

The second definition overwrites the first.

**Comment by BKPepe** [comment]
Good catch. On the second line, there should be `+` instead of `:`
Anyway, space also works.
